### ISSUE TITLE
iosDLAN协议投屏到tvOS上面失效在tun里希望加个exclude route 

### ISSUE THREAD

**Issue by akaagiao1** [SagerNet/sing-box#1005]
### 操作系统

Apple tvOS

### 系统版本

最新的bata版

### 安装类型

sing-box for Apple tvOS 图形客户端程序

### 版本

<details>
```console
# 使用输出内容覆盖此行
```
</details>

### 该环境都是tvos sing-box开启状态
ios：虎牙  开关sing-box均无法投屏，使用时sing-box时开启"source_ip_cidr"直连和"ip_cidr"直连也无法使用
tvos投屏软件：DLPlay
安卓：安桌端未开启sing-box  虎牙能够正常投屏，开启未测试

## 描述
最近英雄联盟S13世界赛开始可，但是虎牙斗鱼等App使用dlan投屏的时候投屏失败，翻了翻资料隔壁surge是在tun上下的功夫
**tun-excluded-routes = 239.255.255.250/32**
<img width="908" alt="image" src="https://github.com/SagerNet/sing-box/assets/94331537/3a478b94-2e37-4273-8823-acc717dee265">
`tun-excluded-routes = 239.255.255.250/32`
作为菜鸡的我在路由里加上  

 ```
 "ip_cidr": [
                    "239.255.255.250/32"
                ],
                "outbound": "direct"
            },
```
还是不能用

## 猜测
在群里问群佬说要加个 **_exclude route_** 的功能吧，可以解决。那就太感谢了
能更好的娱乐大伙，辛苦了。佬

### 重现方式

。。。

### 日志

<details>
```console
# 使用日志内容覆盖此行
```
</details>

**Comment by uenokatsura** [comment]
> 你可以启用 `auto_route` 并自行配置 `inet4_route_address` 与 `inet6_route_address`，将需要“绕过”的 CIDR 取反。

不太清楚tvOS，但是在iOS上配置inet6_route_address會導致無法啟動，配置inet4_route_address亦不完全遵循配置內容。
