### ISSUE TITLE
geoip.db download problem

### ISSUE THREAD

**Issue by johnthecoderpro** [SagerNet/sing-box#1014]
### Operating system

Linux

### System version

1.6.0-rc.1 

### Installation type

Original sing-box Command Line

### Version

<details>

```
sing-box version 1.6.0-rc.1
Environment: go1.21.3 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api
Revision: 03f4cd115c7bc2b8d2547c63b07c020882765521
CGO: disabled
```

</details>

### Description

if geoip.db download get error or timeout sing-box create empty file geoip.db with 0 byte
so i try to restart sing-box because i think will it try to redownload the geoip.db file
but it is not . becuase geoip.db file created but with empty content
so it throw error 

> open geoip database : error opening database: invalid MaxMind DB file

i think you must check the file size and if it is 0 try to redownload the file

### Reproduction

if you have some slow network you can test to download geoip.db and if you get timeout for download file an empty geoip.db  is create so the sing-box think that the file is downloaded!

**Comment by johnthecoderpro** [comment]
i fix the problem 
please accept this pr
https://github.com/SagerNet/sing-box/pull/1022

**Comment by johnthecoderpro** [comment]
can you check this please 
thank you

**Comment by ParseDark** [comment]
> There are many third-party `geoip` projects so it is impractical to add some checksum functions, and sing-box is not a download manager.


I think you miss understand the issue. The problem is when user start use the clinet side. It will block at the geoip.db file download. 

<img width="767" alt="image" src="https://github.com/SagerNet/sing-box/assets/26950370/ff570fdf-9cea-4de8-9871-3989d657d9cb">

**Comment by Developer27149** [comment]
![image](https://github.com/SagerNet/sing-box/assets/23721611/b27dcb3d-b444-446e-bab6-41baca8b29e5)
@dyhkwong hi there.What's about name error.

**Comment by llplmlyd** [comment]
？
