### ISSUE TITLE
users的重复UUID配置相关问题咨询

### ISSUE THREAD

**Issue by znlsl** [SagerNet/sing-box#1016]
你好！
我在配置tuic的inbounds时候发现，对于users的配置，不同name、password的情况下，如果有相同的uuid，应该是匹配第一个uuid的password，
例如：
{
    "name": "111",
    "uuid": "111111",
    "password": "111"
},
{
    "name": "222",
    "uuid": "111111",
    "password": "222"
},
如果想用user是222时，会报错：
-0400 2023-10-28 13:45:38 ERROR inbound/tuic[tuic-in]: connection failed: handle uni stream: authentication: token mismatch
-0400 2023-10-28 13:45:38 ERROR inbound/tuic[tuic-in]: handle stream request: handle uni stream: authentication: token mismatch
pkill sing-box;

我想修改这部分的逻辑，遍历全部users的uuid，看是否有能匹配上的password，然后用对应的name作为出站。

但是我拉了最新的1.6.3的代码，没有找到上面打印log地方的代码，想请教下这部分逻辑在哪里，我想自己尝试修改下

感谢感谢！

**Comment by ekenchan** [comment]
在这个依赖的项目中[https://github.com/sagernet/sing-quic](https://github.com/sagernet/sing-quic)

**Comment by znlsl** [comment]
> 在这个依赖的项目中https://github.com/sagernet/sing-quic

好嘞！感谢感谢~
