### ISSUE TITLE
Sing-box with gvisor stack stopping but vpn service doesn't [Android]

### ISSUE THREAD

**Issue by Hryniuk1** [SagerNet/sing-box#1024]
### Operating system

Android

### System version

Realme GT Master Edition, Realme UI 4, Android 13

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.6.0(134)

### Description

Sometimes, trying to stop the sing-box in the graphical interface results in the sing-box seeming to turn off, but the vpn service continues to work. At the same time, there is no Internet. I have to either start the singbox service again and stop it or force stop 
 application in system settings.
 Also this happens to Nekobox for Android
 Actually is duplicate of #921 but with logs :)
![Screenshot_2023-10-31-21-12-11-45_d2ee0e1115b0a64ebff5994ebce8502f](https://github.com/SagerNet/sing-box/assets/29910078/157f52f5-d5ae-45e0-ac67-e4939bfb701f)
![Screenshot_2023-10-31-21-12-17-29_41a74ddf68be21faad2fbbb691b15143](https://github.com/SagerNet/sing-box/assets/29910078/c640edb0-79d1-41ae-9e3f-d4fea0c0dd9b)

### Reproduction

1. Choose "gvisor" stack. There is no such bug when use "system" stack
2. Use sing-box for a long time (30 minutes or more)

### Logs

Client config: 
[client_config.json](https://github.com/SagerNet/sing-box/files/13221009/client_config.json)
sing-box service log: 
[singbox-log.txt](https://github.com/SagerNet/sing-box/files/13220786/singbox-log.txt)
Logcat:
[logcat.zip](https://github.com/SagerNet/sing-box/files/13220800/logcat.zip)

**Comment by usaxyh** [comment]
yes, I had the same issue while using gvisor stack. System stack seems OK.

**Comment by lux5am** [comment]
the same with openwrt linux-arm64. internet stuck after 30min+. the connections was under direct rule. changed to system seems ok.

**Comment by Arunmor1510** [comment]
I think the old sing-box service is not entirely terminated, if I try to restart the VPN multiple times, I can see that the memory usage in the dashboard will ramp up, unless I force stop the app. The initial memory usage is around 8~10MB but restarting I'd get 17~20MB, maybe even more if I continue to restart. Tested with SFA-1.6.5-arm64-v8a.apk, both system and gvisor stack.
