### ISSUE TITLE
macOS 客户端启动服务失败

### ISSUE THREAD

**Issue by sososdk** [SagerNet/sing-box#1026]
### 操作系统

macOS

### 系统版本

Sonoma 14.1

### 安装类型

sing-box for macOS 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

Version 1.6.0 (106)

### 版本

<details>
```console
# 使用输出内容覆盖此行
```
</details>

### 描述

启动后弹窗:
<img width="260" alt="image" src="https://github.com/SagerNet/sing-box/assets/46806014/f450ed27-c75f-44ab-ab7a-67830287a8a4">

日志:
<img width="900" alt="image" src="https://github.com/SagerNet/sing-box/assets/46806014/664e2215-e08b-4909-8751-9b71fc40f0f4">

### 重现方式

从 app store 下载 sing-box, 打开 app 添加可用配置(配置可在android 版 sing-box 上正常使用)后, 启动服务.   

### 日志

<details>
```console
# 使用日志内容覆盖此行
```
</details>

**Comment by nekohasekai** [comment]
Run `sudo systemextensionsctl reset` in Terminal to fix this problem
