### ISSUE TITLE
Win TUN 下 Beta 4 后续版本原神连接超时

### ISSUE THREAD

**Issue by SimonWe1** [SagerNet/sing-box#103]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

测试方式： Beta 4 对比 Beat 6，outbound 仅有 direct，Powershell 管理员身份运行，防火墙规则正常，其他联网正常。
稳定复现：原神可正常登录，但 Beta 6 无法从“点击进入”进入游戏画面，进入后切换 Beta 6 也能正常继续游戏。Beta 4 一切正常，gvisor 和 system 现象一致。
实际操作为 .\sing-box run -c .\test.json 后进入游戏点“点击进入”，后续正常进入或连接超时后 ctrl+c 停止。

![image](https://user-images.githubusercontent.com/58877008/191798640-e01e9f90-6ba8-444c-a6fd-3d2eb655edb9.png)

### Version of sing-box

<details>

```console
$ sing-box version
https://github.com/SagerNet/sing-box/releases/download/v1.1-beta4/sing-box-1.1-beta4-windows-amd64v3.zip
https://github.com/SagerNet/sing-box/releases/download/v1.1-beta6/sing-box-1.1-beta6-windows-amd64v3.zip
```

</details>

### Server and client configuration file

<details>

```console
{
    "log": {
        "disabled": false,
        "level": "debug",
        "output": "box.log",
        "timestamp": true
    },
    "dns": {
        "servers": [
            {
                "tag": "dns",
                "address": "tls://223.5.5.5",
                "detour": "direct"
            }
        ],
        "strategy": "ipv4_only"
    },
    "inbounds": [
        {
            "type": "tun",
            "inet4_address": "172.19.0.1/30",
            "inet6_address": "fdfe:dcba:9876::1/126",
            "mtu": 9000,
            "auto_route": true,
            "stack": "system",
            "sniff": true,
            "sniff_override_destination": false
        }
    ],
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        }
    ],
    "route": {
        "rules": [
            {
                "protocol": "dns",
                "outbound": "dns-out"
            }
        ],
        "auto_detect_interface": true
    }
}
```

</details>

### Server and client log file

<details>

```console
# paste log here
```
[beta4.log](https://github.com/SagerNet/sing-box/files/9627450/beta4.log)
[beta6.log](https://github.com/SagerNet/sing-box/files/9627454/beta6.log)

</details>

**Comment by nekohasekai** [comment]
Can you spot a more general problem? I don't use windows.

**Comment by nekohasekai** [comment]
Try 1.1-beta7.

**Comment by SimonWe1** [comment]
> Try 1.1-beta7.

解决了，非常感谢！辛苦了！
另外 1.1-beta 7 的 sing-box version 显示还是 1.1-beta 6（影响不大）。
