### ISSUE TITLE
FATAL[0000] start service: initialize inbound/vless[vless-in]: Proxy Protocol is deprecated and removed in sing-box 1.6.0

### ISSUE THREAD

**Issue by imagecreation1** [SagerNet/sing-box#1030]
Hi there. 
I had a nginx with website along with my vmess+cdn+ws and reality. (
map $ssl_preread_server_name $stream_map {
    www.microsoft.com local_https;
    xxx.com original_dest;
    default local_https;
)
Is there a way to make it work after the update? Because without "proxy_protocol": true, and "proxy_protocol_accept_no_header": false my reality doesn't work. 
I don't want to disable my website - I need it. 
Thank you very much.

**Comment by mrsrimar22** [comment]
you can't use proxy protocol after 1.6.0 version,is deprecated and removed

**Comment by Weltolk** [comment]
https://sing-box.sagernet.org/deprecated/#proxy-protocol

https://github.com/SagerNet/sing-box/releases/tag/v1.6.0
