### ISSUE TITLE
Add mutiple ip supoort for server

### ISSUE THREAD

**Issue by johnthecoderpro** [SagerNet/sing-box#1032]
i use test.com in `server ` config
test.com has 3 A record:
```
test.com -> 192.168.1.1, 192.168.1.2, 192.1681.1.3
```
each time user wants to connect the dns manager give them random ip
but many users has dns issue and it's cause users to get disconnected every 5 minute
in iran many dns servers are block and only some udp dns works but they have hijak the dns requests

so if you please add multiple ip support for server  so we can set array of ips directly in configs like that : 

```
{
  "outbounds": [
    {
      "type": "vless",
      "server": [
        "192.168.1.1",
        "192.168.1.2",
        "192.168.1.3"
      ],
      "server_port": 80,
      "tag": "proxy",
      "uuid": "uuid"
    }
    }
  }
```

and each time user wants to connect the sing-box pick one of them randomly

**Comment by Weltolk** [comment]
https://sing-box.sagernet.org/configuration/outbound/urltest/

**Comment by johnthecoderpro** [comment]
i can not use this in gui programs like nekoray or nenobox
also it is not random
i want to loadbalance traffic . the urltest only connect to the best server

**Comment by johnthecoderpro** [comment]
you can just add an if and check if the value is array pick one of them randomly

**Comment by johnthecoderpro** [comment]
please help
@nekohasekai

**Comment by mahdi13617370** [comment]
Please add manual options for v²ray or other protocols without domain ip address.
I want to add manual servers in app.

Thanks a lot 😊
