### ISSUE TITLE
求助：sing-box能动态更新route和outbound吗？

### ISSUE THREAD

**Issue by ccdd4ever** [SagerNet/sing-box#1034]
请问一下singbox能否在不重启的情况下动态更新route和outbound？

**Comment by CHIZI-0618** [comment]
不能

**Comment by ccdd4ever** [comment]
当前sighup信号触发的check()函数会重新加载配置，重新加载配置会终端原有的连接吗？

**Comment by CHIZI-0618** [comment]
> 当前sighup信号触发的check()函数会重新加载配置，重新加载配置会终端原有的连接吗？

会

**Comment by ccdd4ever** [comment]
感谢支持
