### ISSUE TITLE
无法监测自己的VPN是否被其他VPN顶掉

### ISSUE THREAD

**Issue by ersonstar** [SagerNet/sing-box#1037]
### 操作系统

Android

### 系统版本

Android13

### 安装类型

sing-box for Android 图形客户端程序

### 描述

在sing-box APP中开启了VPN代理，
切换其他代理APP去开启代理，sing-box的VPN代代理被顶替或者VPN服务关闭。
返回sing-box app 状态依然为代理状态，无法检测到当前VPNService是否是自己的

### 重现方式

如上述

**Comment by chise0713** [comment]
![Screenshot_20231106-202421_设置](https://github.com/SagerNet/sing-box/assets/123655015/49eb3bf4-7ea0-41c8-8d43-71dd9b80112b)

**Comment by nekohasekai** [comment]
Should be fixed in alpha.10

**Comment by ersonstar** [comment]
Blessed you
