### ISSUE TITLE
无法导入配置

### ISSUE THREAD

**Issue by 2SHANINGITHUB** [SagerNet/sing-box#1038]
### 操作系统

Android

### 系统版本

Android13

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.6.0

### 描述

在使用url导入配置时，提示
Error
decode config:invalid character 'c' looking for beginning of value:row1, column 1
![IMG_20231103_170333](https://github.com/SagerNet/sing-box/assets/90484463/52f9713b-cefb-4959-9cb1-8c79e3ef0c1d)

### 重现方式

使用URL导入配置

**Comment by xywf221** [comment]
检查是否能直接通过浏览器打开，建议使用一个匿名窗口访问

**Comment by jackson-xp** [comment]
IOS遇到同样的问题。同样的地址 clash导入正常。

**Comment by ShuaiHuiEE** [comment]
怎么办

**Comment by just2so** [comment]
出现同样的错误，别的客户端都可以用，怎么办

**Comment by neverdead117** [comment]
一样的问题

**Comment by qq1012827513** [comment]
same as u
