### ISSUE TITLE
点击Install SystemExtension 无效

### ISSUE THREAD

**Issue by An0nymous0** [SagerNet/sing-box#1039]
### Operating system

macOS

### System version

1.6.0

### Installation type

sing-box for macOS Graphical Client

### Version

<details>
```console
# Replace this line with the output
```
</details>

### Description

<img width="892" alt="image" src="https://github.com/SagerNet/sing-box/assets/6836030/7230e458-0591-4f3c-8061-01929a9d5c75">

### Reproduction

点击Install SystemExtension 无反应，之前应该是点过弹出一个界面，点没之后再点就没反应了

### Logs

<details>
```console
# Replace this line with logs
```
</details>

**Comment by sunxiaoshi** [comment]
解决了吗，我也遇到这个问题

**Comment by IViDerNvI** [comment]
> 解决了吗，我也遇到这个问题

我同样遇到了这个问题，一个可行的解决方法如下：
可以尝试在恢复模式启用系统扩展选项，并在登录项与扩展中找到sing-box选项并启用。之后可以启用面板。
希望这个方法有所帮助！
