### ISSUE TITLE
通知图标优化

### ISSUE THREAD

**Issue by nasheep** [SagerNet/sing-box#1047]
### 操作系统

Android

### 系统版本

Android 14

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.6.0

### 版本

<details>
```console
# 使用输出内容覆盖此行
```
</details>

### 描述

通知图标的尺寸~~似乎不符合规范~~ （强迫症很难受）

![图标尺寸对比](https://raw.githubusercontent.com/nasheep/images/main/1699090990304.png "notification icon")

修改后的图标文件：
https://github.com/nasheep/images/blob/main/icon.png

望采纳！

### 重现方式

每次

### 日志

<details>
```console
# 使用日志内容覆盖此行
```
</details>

**Comment by nekohasekai** [comment]
Can you explain what spec it doesn't conform to? I noticed that this new image has reduced quality, is there any reason for this?
