### ISSUE TITLE
无法设置使用websocket作为传输方式的vmess中的http header中的Host

### ISSUE THREAD

**Issue by OrLojqrG** [SagerNet/sing-box#1049]
### 操作系统

Windows

### 系统版本

Windows 11

### 安装类型

sing-box 原始命令行程序

### 版本

<details>
```console
sing-box version 1.7.0-alpha.5

Environment: go1.21.3 windows/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api
Revision: c2ce1d0024c03b74ca92fa7ad860433f550e0d7e
CGO: disabled
```
</details>

### 描述

在使用websocket作为vmess的传输方式时，在配置文件中为"headers"中设置"Host"的内容，使用wireshark抓包发现实际的http请求中的Host为配置文件中的"server"所设置的内容，而不是在"headers"中设置的内容，但是"headers"中设置的其他内容（比如"User-Agent"等）是可以正常设置并显示的。

### 重现方式

所使用的配置文件格式如下
{
    "server": "server.com",
    "server_port": 1234,
    "tag": "proxy1",
    "transport": {
        "headers": {
            "Host": [
                "host.com"
            ],
            "User-Agent": [
                "Random-User-Agent"
            ]
        },
        "path": "/",
        "type": "ws"
    },
    "type": "vmess",
    "security": "auto",
    "uuid": ""
}
使用wireshark对出口的网卡抓包设置fliter为http.host
发现实际的http请求中的Host为配置文件中的"server"所设置的内容(server.com)，而不是在"headers"中设置的内容(host.com)，但是"headers"中设置的其他内容（比如"User-Agent"等）是可以正常设置并显示的。

### 日志

<details>
```console
# 使用日志内容覆盖此行
```
</details>

**Comment by moosetk** [comment]
嗯  17 支持了 httpupgrade 就不支持 ws 了

**Comment by lux5am** [comment]
probably due to migration to gobwas

**Comment by nekohasekai** [comment]
Shoud be fixed in beta 8.
