### ISSUE TITLE
VLESS协议报错HTTP 403 无法连接 切回旧版本正常

### ISSUE THREAD

**Issue by sck0537** [SagerNet/sing-box#1056]
### Operating system

Windows

### System version

windows11

### Installation type

Original sing-box Command Line

### Version

<details>
```
sing-box version 1.7.0-alpha.6
Environment: go1.21.3 windows/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api
Revision: 171e42887b3cbd4bfd46b9eb6cf6bf2beef2a8e0
CGO: disabled
```
</details>

### Description

![image](https://github.com/SagerNet/sing-box/assets/61313985/1b63e4ae-5de2-47b8-a78b-11f098d0c468)

### Reproduction

![image](https://github.com/SagerNet/sing-box/assets/61313985/67356c32-7a25-4d0a-8fa3-68b2aa7ea38d)

在1.70 alpha 6版本使用此节点 报错HTTP 403
切回sing-box 1.60正式版 正常连接

### Logs

![image](https://github.com/SagerNet/sing-box/assets/61313985/338c2085-08e1-4418-a402-7b24e4dc3678)

**Comment by moosetk** [comment]
用 httpupgrade
