### ISSUE TITLE
clash全线爆炸，sing-box什么时候能出GUI界面

### ISSUE THREAD

**Issue by yzx1208** [SagerNet/sing-box#1064]
### 操作系统

Windows

### 系统版本

Windows11

### 安装类型

其他

### 如果您使用图形客户端程序，请提供该程序版本。

官方能出一个GUI界面的么？

### 版本

<details>
```console
# 使用输出内容覆盖此行
```
</details>

### 描述

官方能出一个GUI界面的么？

### 重现方式

官方能出一个GUI界面的么？

### 日志

<details>
```console
# 使用日志内容覆盖此行
```
</details>

**Comment by xaotag** [comment]
使用clash_api就行了
