### ISSUE TITLE
Add feature: a widget for ios & macos  enabling a shortcut ( for opening proxy & monitoring)

### ISSUE THREAD

**Issue by levihuayuzhang** [SagerNet/sing-box#1065]
### Operating system

iOS

### System version

latest

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

latest

### Version

null, this is a feature request.

### Description

Add a widget so that community users can enable proxy without opening the app. (may require more background control)
These may benefit both Mac and IOS users cause the widget on IOS of some apps can be enabled on Mac (if using same iCloud account)

### Reproduction

null, this is a feature request.

### Logs

null

**Comment by nekohasekai** [comment]
sing-box already has full support for Shortcut.
