### ISSUE TITLE
iOS客户端无法启动

### ISSUE THREAD

**Issue by xishang0128** [SagerNet/sing-box#1066]
### 操作系统

iOS

### 系统版本

IOS 17.2

### 安装类型

sing-box for iOS 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.7.0-alpha.8

### 版本

<details>
```console
# 使用输出内容覆盖此行
```
</details>

### 描述

在入站中配置tun入站,并添加 `inet6_address` 在iOS客户端会启动失败,其他平台(安卓客户端/命令行程序)的同版本程序测试正常
删除 `inet6_address` 后在iOS客户端正常启动

### 重现方式

在入站中配置tun的 `inet6_address`  ,如
```json
{
  "inbounds": [
    {
      "type": "tun",
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "auto_route": true,
      "stack": "system",
      "sniff": true
    }
  ]
}
```

### 日志

<details>
```console
Service Log中无日志,Logs中也无任何有效日志
```
</details>

**Comment by nekohasekai** [comment]
Shoud be fixed in alpha.10
