### ISSUE TITLE
Mac client start error: missing default profile

### ISSUE THREAD

**Issue by peixin** [SagerNet/sing-box#1073]
### Operating system

macOS

### System version

13.2

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.7.0-alpha.9

### Version

<details>
```console
# Replace this line with the output
```
</details>

### Description

<img width="900" alt="image" src="https://github.com/SagerNet/sing-box/assets/1221523/fae4d7eb-ccb0-4cd0-96b2-4e61452be9ef">
<img width="480" alt="image" src="https://github.com/SagerNet/sing-box/assets/1221523/f5cb01d9-a7f2-4451-a2f2-2285b636b973">

首次打开正常，stop 之后，按钮灰色不可点。再 start 就这样了， 一启动。vpn 一直处于 Disconnecting 状态。

### Reproduction

首次打开正常，stop 之后，按钮灰色不可点。再 start 就这样了， 一启动。vpn 一直处于 Disconnecting 状态。

### Logs

<details>
```console
# Replace this line with logs
```
</details>

**Comment by Sped0n** [comment]
Same here, macOS Sonoma 14.1
<img width="900" alt="image" src="https://github.com/SagerNet/sing-box/assets/70063177/0505306e-0ff0-4311-bdd5-b9bc74bebf51">

**Comment by KitwahSin** [comment]
I met the same issue.But it runs well by command line, using the same profile file.

**Comment by nekohasekai** [comment]
Is this the App Store version or the Github Release version?

**Comment by Sped0n** [comment]
> Is this the App Store version or the Github Release version?

* First attempt: App Store v1.6.2 (Failed to start)
* Second attempt: gh release v1.7.0-alpha.10 (Failed to start)
* Third attempt: gh-release v1.6.2 (Working)

Also, the config file used in all three versions are the same, it doesn’t seem to be a problem with the configuration files. I have also tried using remote config after local config failed, but still couldn’t start.

**Comment by KitwahSin** [comment]
oh, i installed the app by homebrew, version: 1.6.3;
and now it runs well by performing a full reinstall?

**Comment by peixin** [comment]
I download 1.7.0-beta.3 from github, reinstall. It is working.

**Comment by vstar37** [comment]
同样的问题，楼主解决了么？

**Comment by xbpk3t** [comment]
This error still exists in version 1.10.1 installed by brew. And how to resolve it?
