### ISSUE TITLE
1.7.0-alpha.10關於Multiplex, 在服務端啟用Multiplex且"padding": true的情況沒有拒絕客戶端"padding": false 的連線

### ISSUE THREAD

**Issue by chaosoffire** [SagerNet/sing-box#1075]
### 操作系统

Windows

### 系统版本

Windows 11 amd64 23H2

### 安装类型

sing-box 原始命令行程序

### 版本

<details>
```console
sing-box version 1.7.0-alpha.10

Environment: go1.21.3 windows/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api
Revision: 0abe9d38147cd4128b3ec34fbeafa825de7b4534
CGO: disabled
```
</details>

### 描述

根據文檔Multiplex Inbound Fields padding (If enabled, non-padded connections will be rejected.)

服務端inbound 中設了padding: true的情況下，理論上的表現應該為客戶端outbound padding: false 時服務端拒絕連接

只測試了trojan, 無論有沒有開tls, 服務端multiplex enable: true & padding: true, 客戶端multiplex enable: false & padding: false 仍然能夠正常連接，不知是否為bug

### 重现方式

Server config
"""
{
  "log": {
    "level": "debug",
    "output": "server.log",
    "timestamp": true
  },
  "inbounds": [
    {
      "type": "trojan",
      "tag": "trojan-in",
      "listen": "127.0.0.1",
      "listen_port": 10005,
      "users": [
        {
          "name": "0",
          "password": "On1THjyIm7dKyxrkM+pnxQ=="
        }
      ],
      "tls": {
        "enabled": true,
        "server_name": "test.localhost",
        "certificate": [
          "-----BEGIN CERTIFICATE-----\r",
          "MIIDDTCCAfWgAwIBAgIRAKGtB+swgu4sPDn4HbobUK0wDQYJKoZIhvcNAQELBQAw\r",
          "GTEXMBUGA1UEAxMOdGVzdC5sb2NhbGhvc3QwHhcNMjMxMTA4MDMzMTM2WhcNMjMx\r",
          "MjA4MDQzMTM2WjAZMRcwFQYDVQQDEw50ZXN0LmxvY2FsaG9zdDCCASIwDQYJKoZI\r",
          "hvcNAQEBBQADggEPADCCAQoCggEBANQ6HXOb60ID3aGIwax4/F2nTIXTMVXmEQ29\r",
          "YAuz0woyTn90yl8hQHq4dENFgNI1dHLedJLLQSyPbVe4i8jtW2Pdd574v3yEcbhs\r",
          "fwkuh3pEvev0DVGbu+6U2fq0Polr8IXZmxBezfBXJ1ejl21vNTBrmPgaevawa/K3\r",
          "8DrFZnCwflybZFRWuLRz3QUj9WjYpiTzPBGvwwcOE+JvqkAfAyHFYAtssoeIiE5U\r",
          "LyBEv6wTCuwkdRrkT+68j6UL+bfJEUV2xgFNmC3Wnx3DwUPWMRMlx4HIsr1ZP0xA\r",
          "4Cfaxmfyi/KTLTEudhsJJjRD/JFnQUeAtuMpjjQ95WPehEx2jJkCAwEAAaNQME4w\r",
          "DgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQC\r",
          "MAAwGQYDVR0RBBIwEIIOdGVzdC5sb2NhbGhvc3QwDQYJKoZIhvcNAQELBQADggEB\r",
          "AGMwLLdtHhz+6xT9+bg892fWH5cmXqBf7Xd+myC56vJME9dV4zoRgvxC8h8Nx8Ur\r",
          "YTqZvRO+OHyx9jnLFCrsrE8VbZChQ0NO3lQ2VBioSHE3ifoflwqCCob3JSS6CWe6\r",
          "TMyT5CmZUY4UVKe1heSaaYQSf/9uegwB1MYVWHto1dnOI1wVUCVSt20gjZL40sGH\r",
          "ZvmuYGbT18Gz0QBPgygSFjiJIJd3DGMqIJ2Ljv/Nr8qZ9yEyJwNh9snwiMPI3IBo\r",
          "sKIyRthLDy5LLdo1TCH1Mhum9vO81zPTS74O0hqMpMwkP8HmcpaX+7Okm1Zw3KNo\r",
          "gbxtFfHwU2H94rlMo1yFDoo=\r",
          "-----END CERTIFICATE-----"
        ],
        "key": [
          "-----BEGIN PRIVATE KEY-----\r",
          "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDUOh1zm+tCA92h\r",
          "iMGsePxdp0yF0zFV5hENvWALs9MKMk5/dMpfIUB6uHRDRYDSNXRy3nSSy0Esj21X\r",
          "uIvI7Vtj3Xee+L98hHG4bH8JLod6RL3r9A1Rm7vulNn6tD6Ja/CF2ZsQXs3wVydX\r",
          "o5dtbzUwa5j4Gnr2sGvyt/A6xWZwsH5cm2RUVri0c90FI/Vo2KYk8zwRr8MHDhPi\r",
          "b6pAHwMhxWALbLKHiIhOVC8gRL+sEwrsJHUa5E/uvI+lC/m3yRFFdsYBTZgt1p8d\r",
          "w8FD1jETJceByLK9WT9MQOAn2sZn8ovyky0xLnYbCSY0Q/yRZ0FHgLbjKY40PeVj\r",
          "3oRMdoyZAgMBAAECggEAcN+X2m0K6slzjv5VQ431azoXkPWKP81lNJGMC61QiRPI\r",
          "fDF5kK72xE5mR4EnyqVzkcSO66P+vdxqo0Ub03mqKasYfAyAi5FFinjp99AvbfAx\r",
          "stTSYJ0bjwDMDnLe7+fgvM/HkSVbEoDIA+yWFTYYa/BOI2ayD5I1V5pMwnVKzpOY\r",
          "E0XA2DTeoboYnYjVz1bWnEtnbOUzAPOqE20g4v6p9WLUJrTIvu9AZYh+MPUS7Mzy\r",
          "/I2XgbO/FLof9dZgCcPXFOh0U4LCc0Rd5IIzuobVCqN7F0CguzYmq4AhjT5PHLhD\r",
          "EPPvUsiTYa4nkGohD9ufkP9BpUew1uE8efaUtxB8AQKBgQDwRYaEFv/PQlo5BsH5\r",
          "/EVHDld+N02S2UjaRb6/wprjQYZenXM2uHvCacSZzM2Ze3UTK+Z/d5/28HRqqpp6\r",
          "Ro5/Z2Siqhks7lRyNMly312Q6IzJy7jRtM/tJFB/xylvlgSIPyCSmW2dJ9UwIzEY\r",
          "LBiOHBl335kXzea8o9o4nGoOqQKBgQDiHp5GqpVv1L8FiAmWqACsNkNYYRO/6NwA\r",
          "CbB5FxuPqK+/Qk/b6AVu9R+gL2yLaauKv1s/u/q4d+XetNRmWjoI5tQzPAHnWvTM\r",
          "x15dsWw7NnZmgwjUFC2lz/1xJHgFIH27t0YuqtmJ2QuWL/ePTWsGRn+cSQENh9/6\r",
          "MRmEK2X0cQKBgC16q4STKeacQ6GpssvTwXU6tLryUt+p+009iGaZumGrxHhiSy2f\r",
          "a+WXyZvnFT+pC7cORzn3dbLzPsX19vmQI2bgNj9H/S3xCtD3Ru5Uc0x7iDKmOhyP\r",
          "og/cINSe6Svy9HappEu7ePEXWhYbgy51Iky76uIy07KaycMJLMQsbzLJAoGAXF7N\r",
          "oWiF600pS4UrBZRT0gXItQ3TF450cL+Ei7LY23K5eJQKM3cw4QbZiIJXAQyFuwQ4\r",
          "rmyIG1s/WB7etYEePAyvms5kqLILVqwK7JNR905kR7Q3owsrKpUwn0uai92d/1T7\r",
          "Io1AmINFrHCj3LJvify6nIlmGLTs1jPAjLF90MECgYA82iZECWcK+6e4otmTpBfj\r",
          "3X6j1lMtvTpqror7Txfu7+GaazqgddhAqZFRivFFqjCqtBMhBZJd077/ui4YyuXf\r",
          "YFGtV+g9yVWSm00RZTr/UNU8NDv5jhJYAiPtmVQz1FdXQxii/Z5Vsll+OAHoLijd\r",
          "oduKzV7aBOYyHKnK1foDuQ==\r",
          "-----END PRIVATE KEY-----"
        ]
      },
      "multiplex": {
        "enabled": true,
        "padding": true
      }
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct-out"
    }
  ]
}
"""

Client condig
"""
{
  "log": {
    "level": "debug",
    "output": "client.log",
    "timestamp": true
  },
  "inbounds": [
    {
      "type": "socks",
      "tag": "socks-in",
      "listen": "127.0.0.1",
      "listen_port": 10006
    }
  ],
  "outbounds": [
    {
      "type": "trojan",
      "tag": "trojan-out",
      "server": "127.0.0.1",
      "server_port": 10005,
      "password": "On1THjyIm7dKyxrkM+pnxQ==",
      "tls": {
        "enabled": true,
        "server_name": "test.localhost",
        "certificate": [
          "-----BEGIN CERTIFICATE-----\r",
          "MIIDDTCCAfWgAwIBAgIRAKGtB+swgu4sPDn4HbobUK0wDQYJKoZIhvcNAQELBQAw\r",
          "GTEXMBUGA1UEAxMOdGVzdC5sb2NhbGhvc3QwHhcNMjMxMTA4MDMzMTM2WhcNMjMx\r",
          "MjA4MDQzMTM2WjAZMRcwFQYDVQQDEw50ZXN0LmxvY2FsaG9zdDCCASIwDQYJKoZI\r",
          "hvcNAQEBBQADggEPADCCAQoCggEBANQ6HXOb60ID3aGIwax4/F2nTIXTMVXmEQ29\r",
          "YAuz0woyTn90yl8hQHq4dENFgNI1dHLedJLLQSyPbVe4i8jtW2Pdd574v3yEcbhs\r",
          "fwkuh3pEvev0DVGbu+6U2fq0Polr8IXZmxBezfBXJ1ejl21vNTBrmPgaevawa/K3\r",
          "8DrFZnCwflybZFRWuLRz3QUj9WjYpiTzPBGvwwcOE+JvqkAfAyHFYAtssoeIiE5U\r",
          "LyBEv6wTCuwkdRrkT+68j6UL+bfJEUV2xgFNmC3Wnx3DwUPWMRMlx4HIsr1ZP0xA\r",
          "4Cfaxmfyi/KTLTEudhsJJjRD/JFnQUeAtuMpjjQ95WPehEx2jJkCAwEAAaNQME4w\r",
          "DgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQC\r",
          "MAAwGQYDVR0RBBIwEIIOdGVzdC5sb2NhbGhvc3QwDQYJKoZIhvcNAQELBQADggEB\r",
          "AGMwLLdtHhz+6xT9+bg892fWH5cmXqBf7Xd+myC56vJME9dV4zoRgvxC8h8Nx8Ur\r",
          "YTqZvRO+OHyx9jnLFCrsrE8VbZChQ0NO3lQ2VBioSHE3ifoflwqCCob3JSS6CWe6\r",
          "TMyT5CmZUY4UVKe1heSaaYQSf/9uegwB1MYVWHto1dnOI1wVUCVSt20gjZL40sGH\r",
          "ZvmuYGbT18Gz0QBPgygSFjiJIJd3DGMqIJ2Ljv/Nr8qZ9yEyJwNh9snwiMPI3IBo\r",
          "sKIyRthLDy5LLdo1TCH1Mhum9vO81zPTS74O0hqMpMwkP8HmcpaX+7Okm1Zw3KNo\r",
          "gbxtFfHwU2H94rlMo1yFDoo=\r",
          "-----END CERTIFICATE-----"
        ]
      },
      "multiplex": {
        "enabled": false,
        "padding": false
      }
    }
  ]
}

"""

### 日志

<details>
```console
表現為正常連接

Server log
"""
+0800 2023-11-08 13:16:31 INFO router: updated default interface 乙太網路, index 24
+0800 2023-11-08 13:16:31 INFO inbound/trojan[trojan-in]: tcp server started at 127.0.0.1:10005
+0800 2023-11-08 13:16:31 INFO sing-box started (0.11s)
+0800 2023-11-08 13:16:36 INFO [1732772754 0ms] inbound/trojan[trojan-in]: inbound connection from 127.0.0.1:4851
+0800 2023-11-08 13:16:36 INFO [1732772754 1ms] inbound/trojan[trojan-in]: [0] inbound connection to sing-box.sagernet.org:443
+0800 2023-11-08 13:16:36 INFO [1732772754 1ms] outbound/direct[direct-out]: outbound connection to sing-box.sagernet.org:443
+0800 2023-11-08 13:16:36 DEBUG [1732772754 1ms] dns: lookup domain sing-box.sagernet.org
+0800 2023-11-08 13:16:36 DEBUG [1732772754 11ms] dns: lookup succeed for sing-box.sagernet.org: 104.21.91.14 172.67.164.149
+0800 2023-11-08 13:16:36 INFO [1718850581 0ms] inbound/trojan[trojan-in]: inbound connection from 127.0.0.1:4857
+0800 2023-11-08 13:16:36 INFO [1718850581 2ms] inbound/trojan[trojan-in]: [0] inbound connection to fonts.googleapis.com:443
+0800 2023-11-08 13:16:36 INFO [1718850581 2ms] outbound/direct[direct-out]: outbound connection to fonts.googleapis.com:443
+0800 2023-11-08 13:16:36 DEBUG [1718850581 2ms] dns: lookup domain fonts.googleapis.com
+0800 2023-11-08 13:16:36 DEBUG [1718850581 2ms] dns: lookup succeed for fonts.googleapis.com: 216.58.203.74
+0800 2023-11-08 13:16:36 INFO [2547760359 0ms] inbound/trojan[trojan-in]: inbound connection from 127.0.0.1:4860
+0800 2023-11-08 13:16:36 INFO [2547760359 1ms] inbound/trojan[trojan-in]: [0] inbound connection to fonts.gstatic.com:443
+0800 2023-11-08 13:16:36 INFO [2547760359 1ms] outbound/direct[direct-out]: outbound connection to fonts.gstatic.com:443
+0800 2023-11-08 13:16:36 DEBUG [2547760359 1ms] dns: lookup domain fonts.gstatic.com
+0800 2023-11-08 13:16:36 DEBUG [2547760359 3ms] dns: lookup succeed for fonts.gstatic.com: 216.58.203.67
"""

Client log
"""
+0800 2023-11-08 13:16:33 INFO router: updated default interface 乙太網路, index 24
+0800 2023-11-08 13:16:33 INFO inbound/socks[socks-in]: tcp server started at 127.0.0.1:10006
+0800 2023-11-08 13:16:33 INFO sing-box started (0.11s)
+0800 2023-11-08 13:16:36 INFO [3929972810 0ms] inbound/socks[socks-in]: inbound connection from 127.0.0.1:4850
+0800 2023-11-08 13:16:36 INFO [3929972810 0ms] inbound/socks[socks-in]: inbound connection to sing-box.sagernet.org:443
+0800 2023-11-08 13:16:36 INFO [3929972810 0ms] outbound/trojan[trojan-out]: outbound connection to sing-box.sagernet.org:443
+0800 2023-11-08 13:16:36 INFO [4229999775 0ms] inbound/socks[socks-in]: inbound connection from 127.0.0.1:4856
+0800 2023-11-08 13:16:36 INFO [4229999775 0ms] inbound/socks[socks-in]: inbound connection to fonts.googleapis.com:443
+0800 2023-11-08 13:16:36 INFO [4229999775 0ms] outbound/trojan[trojan-out]: outbound connection to fonts.googleapis.com:443
+0800 2023-11-08 13:16:36 INFO [3861457292 0ms] inbound/socks[socks-in]: inbound connection from 127.0.0.1:4859
+0800 2023-11-08 13:16:36 INFO [3861457292 0ms] inbound/socks[socks-in]: inbound connection to fonts.gstatic.com:443
+0800 2023-11-08 13:16:36 INFO [3861457292 0ms] outbound/trojan[trojan-out]: outbound connection to fonts.gstatic.com:443
"""
```
</details>

**Comment by nekohasekai** [comment]
多路复用设置不拒绝非多路复用连接。

**Comment by nobody-99** [comment]
> 多路复用设置不拒绝非多路复用连接。

指的是这吗
> padding
> If enabled, non-padded connections will be rejected.

我跟楼主一样的配置 出现同样的现象
