### ISSUE TITLE
remote超时

### ISSUE THREAD

**Issue by snakexgc** [SagerNet/sing-box#1078]
### Operating system

Android

### System version

Android 13

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.6.2

### Version

<details>
```console
context deadline exceeded(Client.Timeout exceeded while awaiting headers)
```
</details>

### Description

remote默认超时时间太短，订阅链接访问速度较慢，浏览器加载需要10秒左右，但是sfa的默认超时时间是5秒，希望能够延长超时时间，或者增加一个自定义超时时长的选项

### Reproduction

订阅一个连接速度较慢的订阅链接即可复现

### Logs

<details>
```console
context deadline exceeded(Client.Timeout exceeded while awaiting headers)
```
</details>

**Comment by nekohasekai** [comment]
Increased to 15 seconds in alpha.11

**Comment by snakexgc** [comment]
Thanks to every developer!
