### ISSUE TITLE
Need Freebsd Version And Tun not work on freebsd

### ISSUE THREAD

**Issue by Error996** [SagerNet/sing-box#108]
build code：
```
git clone https://github.com/SagerNet/sing-box.git
cd sing-box
export GOPROXY=https://goproxy.cn
export CGO_ENABLED=0 GOOS=freebsd
make
```
tun is not work,include system and gvisor
```
FATAL[0000] start service: initialize inbound/tun[0]: configure tun interface: invalid argument
```

**Comment by Error996** [comment]
see this:
https://github.com/xjasonlyu/tun2socks

it's good

**Comment by nekohasekai** [comment]
sing-box's tun support includes a lot more than other projects. Since I don't use *bsd, you may need to write and submit MR yourself, pay attention to writing tests.
