### ISSUE TITLE
自动刷新配置功能不起作用

### ISSUE THREAD

**Issue by Kia678** [SagerNet/sing-box#1081]
### 操作系统

Android

### 系统版本

Android13

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.6.1

### 版本

<details>

```console
# 使用输出内容覆盖此行
```
</details>

### 描述

设置15分钟间隔自动刷新配置，但是始终从来没有自动刷新配置
Android与iOS的都无法自动刷新配置
希望能推出默认在app启动时自动刷新配置功能

### 重现方式

无法自动刷新配置

### 日志

<details>

```console
# 使用日志内容覆盖此行
```
</details>

**Comment by nekohasekai** [comment]
Shoud be fixed in alpha.11

**Comment by Kia678** [comment]
iOS 1.6.4版本没有修复，依然无法自动刷新配置
