### ISSUE TITLE
支持从clash订阅链接中导入节点

### ISSUE THREAD

**Issue by nick008a** [SagerNet/sing-box#1086]
### Operating system

Windows

### System version

11

### Installation type

Original sing-box Command Line

### Description

clash 所有upstream均匀停止维护，如果能支持clash订阅链接就太好了

### Reproduction

clash 所有upstream均匀停止维护，如果能支持clash订阅链接就太好了

### Logs

<details>

```console
# Replace this line with logs
```
</details>

**Comment by KangMing-ux** [comment]
see https://github.com/xmdhs/clash2singbox
