### ISSUE TITLE
WireGuard's system_interface fails in beta versions.

### ISSUE THREAD

**Issue by heygo1345678** [SagerNet/sing-box#1089]
### Operating system

Linux

### System version

openwrt 23.05

### Installation type

Original sing-box Command Line

### Version

<details>

```console
sing-box version 1.7.0-alpha.11

Environment: go1.21.3 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api
Revision: 567d4f3db5ea69c8e80157b9ed241e57633782ad
CGO: disabled
```
</details>

### Description

wireguard outbound 开启  "system_interface": true, 后走代理网站打不开, v4 & v6 网站都是，ipv6测试没有 ipv6网络，tg可访问,
关闭 "system_interface": true, 后恢复。
或者回滚到 1.6.2 正式版 开启"system_interface": true, 问题消失

![image](https://github.com/SagerNet/sing-box/assets/79509309/02b941a8-1cd8-49e4-a881-008d0080fc2c)
![image](https://github.com/SagerNet/sing-box/assets/79509309/8a2b858a-6cd9-43c1-9dc1-1857e02335d1)

### Reproduction

 {
   "log": {
    "disabled": false,
    "level": "info",
    "timestamp": true
  },
  
  
  "inbounds": [
    

{
  "type": "socks",
  "tag": "socks-in",
  "listen": "::",
  "listen_port": 15353,
  "sniff": true
 
}

  ],
  "outbounds": [

	    {    
		      "system_interface": true,
                      "interface_name": "wgvps",
		      "routing_mark": 255,	 
                     "type": "wireguard",
                     "tag": "wgvps",
                     "server": "2406: ",   
                     "server_port": 12345,
                     "local_address": [
                "192.168.169.2/24",
                "fd22:2222::2/32" 
            ],
                     "private_key": "GB0JitcoD+Obv0E=", 
                    "peer_public_key": "+Y6fxw="
           
        },

    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    }

  ],
  "route": {
	  
    "rules": [
	  
	  {
		  		  
	
      {
        "geosite": "cn",
        "geoip": [
         
          "cn"
        ],
        "outbound": "direct"
      },
	  
	  
	  
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      }

    ],
    "auto_detect_interface": true,
	//"default_mark": 255, // 仅Linux
	"final": "wgvps"
	
  }
 
}

### Logs

<details>

```console
+0800 2023-11-10 08:36:52 ERROR [2996290461 3ms] inbound/tproxy[tproxy-in]: process connection from [2409:xxxx:xxxx:]:22000: dial tcp [2400:6180:100:d0::741:a001]:443: connect: network is unreachable
```
</details>

**Comment by chise0713** [comment]
当你的v6地址出现 `preferred_lft 0` 时会出现默认路由到另一个 `preferred_lft` 不为0的地址上，试试看重新拨号或者dhcp重新问询。

**Comment by nekohasekai** [comment]
Can you try 1.7.0-beta.2?

**Comment by heygo1345678** [comment]
Okay, I'll test it when I go home

**Comment by heygo1345678** [comment]
I have tested version 1.7.0-beta.2 and this bug has been fixed.
