### ISSUE TITLE
请大佬增加一下FreeBSD的编译包下载。

### ISSUE THREAD

**Issue by tomxiang1** [SagerNet/sing-box#1092]
### 操作系统

其他

### 系统版本

1.7

### 安装类型

其他

### 版本

<details>

```console
# 使用输出内容覆盖此行
```
</details>

### 描述

请大佬增加一下FreeBSD的编译包下载，谢谢了。
自己实在是没有能力和环境编译，希望大佬增加一下。

### 重现方式

无

### 日志

<details>

```console
# 使用日志内容覆盖此行
```
</details>

**Comment by molezz** [comment]
little white man need this bin ~~~ 
![image](https://github.com/SagerNet/sing-box/assets/695412/2f8cbb8f-743e-4301-8646-98a7a3487bd6)

**Comment by sshpem** [comment]
https://github.com/sshpem/monitor-build-sing_box/releases

**Comment by xujiegb** [comment]
> https://github.com/sshpem/monitor-build-sing_box/releases

@sshpem  请问这里面有FreeBSD的包吗？
@fujiwarabach(Fedora)  Maybe we can add v2rayN Support for FreeBSD

**Comment by fujiwarabach** [comment]
@xujiegb Sure
@KevinMX Fuck you! Closing an issue without discussion.

**Comment by xujiegb** [comment]
> [@xujiegb](https://github.com/xujiegb) Sure

So. Wait for FreeBSD 15 or use 14.3 now?

> [@KevinMX](https://github.com/KevinMX) Fuck you! Closing an issue without discussion.

As a Chinese, I also believe this behavior is absurd and arbitrary.

**Comment by fujiwarabach** [comment]
> So. Wait for FreeBSD 15 or use 14.3 now?

Use 14.3
<img width="1728" height="1117" alt="Image" src="https://github.com/user-attachments/assets/3d3b2968-d1d7-437d-953e-deee66f8b893" />

**Comment by fujiwarabach** [comment]
> So. Wait for FreeBSD 15 or use 14.3 now?

@xujiegb I found compiled i386 .NET 8 files in the FreeBSD community repo.

**Comment by KevinMX** [comment]
> [@xujiegb](https://github.com/xujiegb) Sure [@KevinMX](https://github.com/KevinMX) Fuck you! Closing an issue without discussion.

https://github.com/SagerNet/sing-box/issues/1036
https://github.com/SagerNet/sing-box/issues/108
https://github.com/SagerNet/sing-box/issues/635

Please, search before you ask.

This isn't closed as duplicated without a reason ;)

And you really don't have to use the F word. You really shouldn't.
