### ISSUE TITLE
请支持 hysteria2 中的 userpass 验证方式

### ISSUE THREAD

**Issue by cnkmmk** [SagerNet/sing-box#1109]
现在的 sing-box 好像只支持 hysteria2 的 password 验证，如果服务端采用的是 userpass 验证，就无法正常使用，还请支持 userpass 的验证。

**Comment by nekohasekai** [comment]
<img width="783" alt="image" src="https://github.com/SagerNet/sing-box/assets/56506714/dfef55e8-2030-4454-878e-ff7ba8989995">

**Comment by wlrsx** [comment]
我服务端使用 sing-box 的 hysteria 入口，使用 hysteria 官方客户端连接提示 failed to initialize client     {"error": "connect error: timeout: no recent network activity"}
