### ISSUE TITLE
feature request: 为 grpc transport 启用 tcp-brutal 

### ISSUE THREAD

**Issue by KoriIku** [SagerNet/sing-box#1118]
Hi Team:

由于 tcp-brutal 需要多路复用，因此当前的实现与 mux 放在了一起。

注意到 grpc 同样有多路复用的特性，是否有可能为 grpc 在服务端单独启用 tcp-brutal ?

**Comment by nekohasekai** [comment]
技术层面，sing-box 的多路复用中多路复用在协议里层，而在 v2ray transport 中 grpc 在协议外层，由于 go http2 与 grpc 的实现问题，无法访问原始连接，即使通过不优雅的手段拿到了，也没有办法保证同时只存在一条连接。

规范层面，v2ray transport 是 v2ray 的私有协议，应与 v2ray 保持一致，不应随意增删协议片段。

**Comment by chise0713** [comment]
将mux的 `max_connections` 设为1可以得到类似grpc的效果
