### ISSUE TITLE
在windows上使用tun模式时，是否只能通过 手动修改物理网卡dns地址 的方式，才能避免dns泄露？

### ISSUE THREAD

**Issue by GeorgeRudd** [SagerNet/sing-box#112]
本地ipv4和ipv6都有，使用tun模式时，必须配置"inet4_address": "172.19.0.1/30"和"inet6_address": "fdfe:dcba:9876::1/126",然后手动修改物理网卡dns地址为172.19.0.2和fdfe:dcba:9876::2，才不会出现dns泄露 https://www.astrill.com/dns-leak-test

**Comment by database64128** [comment]
This is just how Windows works. See also: https://git.zx2c4.com/wireguard-windows/about/docs/netquirk.md#firewall-considerations-for-0-allowed-ips
