### ISSUE TITLE
get geoip.db timeout: no recent network activity

### ISSUE THREAD

**Issue by closernow** [SagerNet/sing-box#1126]
### Operating system

iOS

### System version

15.4.1

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.7.0-beta.2

### Version

<details>

```console
# Replace this line with the output
```
</details>

### Description

我无论是安卓还是windows还是ios均出现无法下载geoip的情况，是哪里出问题了吗

### Reproduction

无法正常开启，安卓直接闪退，ios弹窗提示packet-tunnel error: start service: get "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db": timeout：no recent network activity

### Logs

<details>

```console
# Replace this line with logs
```
</details>

**Comment by mountainguan** [comment]
(packet-tunnel) error: start service: Get "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db": unexpected HTTP response status: 403

**Comment by willfulpeople** [comment]
the same question

**Comment by DoubleMiao** [comment]
the same problem on my iphone

**Comment by hankcook** [comment]
can you tell us how to fix this problem

**Comment by jasonyun** [comment]
![img_v2_729de0eb-19a6-4662-8acf-10935879e6li](https://github.com/SagerNet/sing-box/assets/738056/e5500968-7712-4059-a630-c00ab6fb404c)

**Comment by DoubleMiao** [comment]
![IMG_8121](https://github.com/SagerNet/sing-box/assets/38652958/d26c7413-e46a-4784-afa9-e6cdc79bbd1f)
尝试改动一下这里

**Comment by DoubleMiao** [comment]
可以把你的规则集贴出来看一下
![IMG_8122](https://github.com/SagerNet/sing-box/assets/38652958/c9347234-f4ae-47cc-9d8a-a24f6070ffb3)

**Comment by jasonyun** [comment]
"rule_set": [
        {
          "type": "remote",
          "tag": "geoip-cn",
          "format": "binary",
          "url": "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs",
          "download_detour": "direct"
        },
        {
          "type": "remote",
          "tag": "geosite-cn",
          "format": "binary",
          "url": "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs",
          "download_detour": "direct"
        },
        {
          "type": "remote",
          "tag": "geosite-geolocation-!cn",
          "format": "binary",
          "url": "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-!cn.srs",
          "download_detour": "direct"
        },
        {
          "type": "remote",
          "tag": "geosite-category-ads-all",
          "format": "binary",
          "url": "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ads-all.srs",
          "download_detour": "direct"
        }
      ]
    }

**Comment by jasonyun** [comment]
{
    "dns": {
        "fakeip": {
            "enabled": true,
            "inet4_range": "198.18.0.0/15",
            "inet6_range": "fc00::/18"
        },
        "independent_cache": true,
        "rules": [
            {
                "outbound": [
                    "any"
                ],
                "server": "local"
            },
            {
                "disable_cache": true,
                "geosite": [
                    "category-ads-all"
                ],
                "server": "block"
            },
            {
                "query_type": [
                    "A",
                    "AAAA"
                ],
                "rewrite_ttl": 1,
                "server": "fakeip"
            },
            {
                "clash_mode": "global",
                "server": "remote"
            },
            {
                "clash_mode": "direct",
                "server": "local"
            },
            {
                "geosite": "cn",
                "server": "local"
            }
        ],
        "servers": [
            {
                "address": "8.8.8.8",
                "detour": "select",
                "tag": "remote"
            },
            {
                "address": "223.5.5.5",
                "detour": "direct",
                "tag": "local"
            },
            {
                "address": "rcode://success",
                "tag": "block"
            },
            {
                "address": "fakeip",
                "tag": "fakeip"
            }
        ],
        "strategy": "prefer_ipv4"
    },
    "experimental": {
        "clash_api": {
            "external_controller": "127.0.0.1:9090",
            "secret": ""
        }
    },
    "inbounds": [
        {
            "auto_route": false,
            "domain_strategy": "prefer_ipv4",
            "endpoint_independent_nat": true,
            "inet4_address": "172.19.0.1/30",
            "inet6_address": "2001:0470:f9da:fdfa::1/64",
            "mtu": 9000,
            "strict_route": true,
            "type": "tun"
        },
        {
            "domain_strategy": "prefer_ipv4",
            "listen": "127.0.0.1",
            "listen_port": 2333,
            "tag": "socks-in",
            "type": "socks",
            "users": []
        },
        {
            "domain_strategy": "prefer_ipv4",
            "listen": "127.0.0.1",
            "listen_port": 2334,
            "set_system_proxy": true,
            "tag": "mixed-in",
            "type": "mixed",
            "users": []
        }
    ],
    "log": {},
    "outbounds": [
        {
            "tag": "select",
            "type": "selector",
            "default": "urltest",
            "outbounds": [
                "urltest",
                "剩余流量：264.7 GB",
                "距离下次重置剩余：29 天",
                "套餐到期：2025-03-28",
                "🇨🇳 fby666.icu网址发布",
                "🇨🇳 TG:newnetyiyun",
                "IEPL丨香港 01",
                "IEPL丨香港 02",
                "IEPL丨土耳其 01",
                "IEPL丨美国 03",
                "IEPL丨新加坡 01",
                "IEPL丨台湾 01",
                "IEPL丨尼日利亚 01",
                "IEPL丨菲律宾 01",
                "IEPL丨越南 01",
                "IEPL丨日本01",
                "CM丨香港 05",
                "CT丨香港04",
                "CU丨香港 03",
                "CM丨香港 02",
                "CU丨香港 01",
                "CU丨日本 01",
                "CT丨日本 03",
                "CM丨日本 04",
                "CU丨俄罗斯 01",
                "CU丨荷兰 01",
                "CM丨韩国 01",
                "CU丨韩国 02",
                "CT丨阿根廷 01",
                "CT丨美国01",
                "CU丨美国02",
                "CM丨美国03",
                "CT丨美国04",
                "CU丨英国01",
                "海外直连丨台湾01",
                "海外直连丨新加坡01",
                "海外直连丨香港01",
                "CM丨新加坡 02",
                "CU丨新加坡03",
                "CM丨台湾02",
                "CT丨泰国 01",
                "CM丨印尼 01",
                "EMBY丨 新加坡",
                "EMBY丨 香港"
            ]
        },
        {
            "server": "www.baidu.com",
            "server_port": 80,
            "tag": "剩余流量：264.7 GB",
            "transport": {
                "type": "ws"
            },
            "type": "vmess",
            "security": "auto",
            "uuid": "1edfe31c-5c83-4985-99ee-eec336edb35f"
        },
        {
            "server": "www.baidu.com",
            "server_port": 80,
            "tag": "距离下次重置剩余：29 天",
            "transport": {
                "type": "ws"
            },
            "type": "vmess",
            "security": "auto",
            "uuid": "1edfe31c-5c83-4985-99ee-eec336edb35f"
        },
        {
            "server": "www.baidu.com",
            "server_port": 80,
            "tag": "套餐到期：2025-03-28",
            "transport": {
                "type": "ws"
            },
            "type": "vmess",
            "security": "auto",
            "uuid": "1edfe31c-5c83-4985-99ee-eec336edb35f"
        },
        {
            "server": "www.baidu.com",
            "server_port": 80,
            "tag": "🇨🇳 fby666.icu网址发布",
            "transport": {
                "type": "ws"
            },
            "type": "vmess",
            "security": "auto",
            "uuid": "1edfe31c-5c83-4985-99ee-eec336edb35f"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "www.baidu.com",
            "server_port": 80,
            "tag": "🇨🇳 TG:newnetyiyun",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "wyhk01.wyyiepl.top",
            "server_port": 32135,
            "tag": "IEPL丨香港 01",
            "tls": {
                "enabled": true,
                "server_name": "hk01.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "wysshk02.wyyiepl.top",
            "server_port": 10007,
            "tag": "IEPL丨香港 02",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "wytr01.wyyiepl.top",
            "server_port": 32129,
            "tag": "IEPL丨土耳其 01",
            "tls": {
                "enabled": true,
                "server_name": "tr01.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "wyus03.wyyiepl.top",
            "server_port": 12999,
            "tag": "IEPL丨美国 03",
            "tls": {
                "enabled": true,
                "server_name": "us03.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "wysg01.wyyiepl.top",
            "server_port": 13009,
            "tag": "IEPL丨新加坡 01",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "wystw01.wyyiepl.top",
            "server_port": 12008,
            "tag": "IEPL丨台湾 01",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "wyng01.wyyiepl.top",
            "server_port": 13002,
            "tag": "IEPL丨尼日利亚 01",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "wyph01.wyyiepl.top",
            "server_port": 13031,
            "tag": "IEPL丨菲律宾 01",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "vn01.wyyiepl.top",
            "server_port": 12998,
            "tag": "IEPL丨越南 01",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "wyjp01.wyyiepl.top",
            "server_port": 16020,
            "tag": "IEPL丨日本01",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "sshk04.wyycloud.top",
            "server_port": 12009,
            "tag": "CM丨香港 05",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "hk03.wyycloud.top",
            "server_port": 13008,
            "tag": "CT丨香港04",
            "tls": {
                "enabled": true,
                "server_name": "hk03.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "sshk03.wyycloud.top",
            "server_port": 13013,
            "tag": "CU丨香港 03",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "hk02.wyycloud.top",
            "server_port": 12002,
            "tag": "CM丨香港 02",
            "tls": {
                "enabled": true,
                "server_name": "hk02.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "sshk05.wyycloud.top",
            "server_port": 13033,
            "tag": "CU丨香港 01",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "jp01.wyycloud.top",
            "server_port": 13000,
            "tag": "CU丨日本 01",
            "tls": {
                "enabled": true,
                "server_name": "jp01.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "jp02.wyycloud.top",
            "server_port": 13019,
            "tag": "CT丨日本 03",
            "tls": {
                "enabled": true,
                "server_name": "jp02.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "ssjp03.wyycloud.top",
            "server_port": 13029,
            "tag": "CM丨日本 04",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "rus.wyycloud.top",
            "server_port": 13023,
            "tag": "CU丨俄罗斯 01",
            "tls": {
                "enabled": true,
                "server_name": "rus01.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "nl01.wyycloud.top",
            "server_port": 13037,
            "tag": "CU丨荷兰 01",
            "tls": {
                "enabled": true,
                "server_name": "nl01.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "kr01.wyycloud.top",
            "server_port": 13003,
            "tag": "CM丨韩国 01",
            "tls": {
                "enabled": true,
                "server_name": "kr01.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "kr02.wyycloud.top",
            "server_port": 32136,
            "tag": "CU丨韩国 02",
            "tls": {
                "enabled": true,
                "server_name": "kr02.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "ar01.wyycloud.top",
            "server_port": 13005,
            "tag": "CT丨阿根廷 01",
            "tls": {
                "enabled": true,
                "server_name": "ar01.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "us01.wyycloud.top",
            "server_port": 13011,
            "tag": "CT丨美国01",
            "tls": {
                "enabled": true,
                "server_name": "us01.wyyniubi.com",
                "insecure": true
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "us02.wyycloud.top",
            "server_port": 12996,
            "tag": "CU丨美国02",
            "tls": {
                "enabled": true,
                "server_name": "us02.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "sus03.wyycloud.top",
            "server_port": 13017,
            "tag": "CM丨美国03",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "us04.wyycloud.top",
            "server_port": 13020,
            "tag": "CT丨美国04",
            "tls": {
                "enabled": true,
                "server_name": "us04.wyyniubi.com",
                "insecure": true
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "uk01.wyycloud.top",
            "server_port": 32133,
            "tag": "CU丨英国01",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "sstw03.wyyniubi.com",
            "server_port": 11331,
            "tag": "海外直连丨台湾01",
            "tls": {
                "enabled": true,
                "server_name": "sstw03.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "sg01.wyyniubi.com",
            "server_port": 11013,
            "tag": "海外直连丨新加坡01",
            "tls": {
                "enabled": true,
                "server_name": "sg01.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "hk02.wyyniubi.com",
            "server_port": 13030,
            "tag": "海外直连丨香港01",
            "tls": {
                "enabled": true,
                "server_name": "hk02.wyyniubi.com"
            },
            "type": "trojan"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "sssg02.wyycloud.top",
            "server_port": 13012,
            "tag": "CM丨新加坡 02",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "sssg03.wyycloud.top",
            "server_port": 12011,
            "tag": "CU丨新加坡03",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "sstw02.wyycloud.top",
            "server_port": 12008,
            "tag": "CM丨台湾02",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "ssth01.wyycloud.top",
            "server_port": 13009,
            "tag": "CT丨泰国 01",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "ssind01.wyycloud.top",
            "server_port": 13015,
            "tag": "CM丨印尼 01",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "emby01.wyycloud.top",
            "server_port": 13038,
            "tag": "EMBY丨 新加坡",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "password": "1edfe31c-5c83-4985-99ee-eec336edb35f",
            "server": "emby02.wyycloud.top",
            "server_port": 13039,
            "tag": "EMBY丨 香港",
            "type": "shadowsocks",
            "method": "aes-128-gcm"
        },
        {
            "tag": "urltest",
            "type": "urltest",
            "outbounds": [
                "剩余流量：264.7 GB",
                "距离下次重置剩余：29 天",
                "套餐到期：2025-03-28",
                "🇨🇳 fby666.icu网址发布",
                "🇨🇳 TG:newnetyiyun",
                "IEPL丨香港 01",
                "IEPL丨香港 02",
                "IEPL丨土耳其 01",
                "IEPL丨美国 03",
                "IEPL丨新加坡 01",
                "IEPL丨台湾 01",
                "IEPL丨尼日利亚 01",
                "IEPL丨菲律宾 01",
                "IEPL丨越南 01",
                "IEPL丨日本01",
                "CM丨香港 05",
                "CT丨香港04",
                "CU丨香港 03",
                "CM丨香港 02",
                "CU丨香港 01",
                "CU丨日本 01",
                "CT丨日本 03",
                "CM丨日本 04",
                "CU丨俄罗斯 01",
                "CU丨荷兰 01",
                "CM丨韩国 01",
                "CU丨韩国 02",
                "CT丨阿根廷 01",
                "CT丨美国01",
                "CU丨美国02",
                "CM丨美国03",
                "CT丨美国04",
                "CU丨英国01",
                "海外直连丨台湾01",
                "海外直连丨新加坡01",
                "海外直连丨香港01",
                "CM丨新加坡 02",
                "CU丨新加坡03",
                "CM丨台湾02",
                "CT丨泰国 01",
                "CM丨印尼 01",
                "EMBY丨 新加坡",
                "EMBY丨 香港"
            ]
        },
        {
            "tag": "direct",
            "type": "direct"
        },
        {
            "tag": "block",
            "type": "block"
        },
        {
            "tag": "dns-out",
            "type": "dns"
        }
    ],
    "route": {
        "auto_detect_interface": true,
        "rules": [
            {
                "geosite": "category-ads-all",
                "outbound": "block"
            },
            {
                "outbound": "dns-out",
                "port": 53
            },
            {
                "clash_mode": "direct",
                "outbound": "direct"
            },
            {
                "clash_mode": "global",
                "outbound": "select"
            },
            {
                "geoip": [
                    "cn",
                    "private"
                ],
                "outbound": "direct"
            }
        ]
    }
}

**Comment by jasonyun** [comment]
![img_v2_24986323-3dd0-4ef6-b375-7c8b884f87li](https://github.com/SagerNet/sing-box/assets/738056/fec093e4-c0e7-4356-a88a-27b83864b825)
然后就提示这个

**Comment by mymicroblog** [comment]
这怎么解决的1.9的客户端报同样错误
