### ISSUE TITLE
Trojan Protocol

### ISSUE THREAD

**Issue by Ali-Khazaee** [SagerNet/sing-box#1136]
### Operating system

Android

### System version

Android 10

### Installation type

Original sing-box Command Line

### Version

<details>

```console
sing-box version 1.6.5

Environment: go1.21.4 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: 36dff630d683ca78f59efcf8bc24ccfbe2df4e85
CGO: disabled

```
</details>

### Description

I've configured Trojan as outbound and there is a field called Password

https://sing-box.sagernet.org/configuration/outbound/trojan/#password

But for Trojan as inbound there is no field as Password, Why is that ?

### Reproduction

Trojan as inbound: https://sing-box.sagernet.org/configuration/inbound/trojan

Trojan as outbound: https://sing-box.sagernet.org/configuration/outbound/trojan

**Comment by misagh72** [comment]
there is password
`{
  "type": "trojan",
  "tag": "trojan-in",

  ... // Listen Fields

  "users": [
    {
      "name": "sekai",
      "**password**": "8JCsPssfgS8tiRwiMlhARg=="
    }
  ],
  "tls": {},
  "fallback": {
    "server": "127.0.0.1",
    "server_port": 8080
  },
  "fallback_for_alpn": {
    "http/1.1": {
      "server": "127.0.0.1",
      "server_port": 8081
    }
  },
  "multiplex": {},
  "transport": {}
}
`
