### ISSUE TITLE
下载geoip失败

### ISSUE THREAD

**Issue by wushuang5112** [SagerNet/sing-box#114]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

# systemctl status sing-box
● sing-box.service - sing-box service
     Loaded: loaded (/etc/systemd/system/sing-box.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-09-26 23:30:57 UTC; 5s ago
       Docs: https://sing-box.sagernet.org
   Main PID: 734871 (sing-box)
      Tasks: 6 (limit: 527)
     Memory: 1.7M
        CPU: 11ms
     CGroup: /system.slice/sing-box.service
             └─734871 /usr/local/bin/sing-box run -c /usr/local/etc/sing-box/config.json

Sep 26 23:30:57 vultr systemd[1]: Started sing-box service.
Sep 26 23:30:57 vultr sing-box[734871]: WARN[0000] router: geoip database not exists: geoip.db
Sep 26 23:30:57 vultr sing-box[734871]: INFO[0000] router: downloading geoip database
Sep 26 23:30:57 vultr sing-box[734871]: INFO[0000] outbound/shadowsocks[0]: outbound multiplex connection to github.com:443
Sep 26 23:30:57 vultr sing-box[734871]: ERROR[0000] router: download geoip database: Get "[https://github.com/SagerNet/sing-geoip/rele>](https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db“

### Version of sing-box

<details>

```console
$ sing-box version
sing-box 1.0.5 (go1.19, linux/amd64, CGO enabled)
```

</details>

### Server and client configuration file

<details>

```console
{
  "inbounds": [
    {
      "type": "mixed",
      "listen_port": 1080,
      "sniff": true,
      "set_system_proxy": true
    }
  ],
  "outbounds": [
    {
      "type": "shadowsocks",
      "method": "2022-blake3-aes-128-gcm",
      "password": "YouPassword",
      "detour": "shadowtls-out",
      "multiplex": {
        "enabled": true,
        "max_connections": 4,
        "min_streams": 4
      }
    },
    {
      "type": "shadowtls",
      "tag": "shadowtls-out",
      "server": "You IP Address",
      "server_port": 443,
      "tls": {
        "enabled": true,
        "server_name": "www.sina.com.cn"
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    }
  ],
  "route": {
    "rules": [
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "geosite": "cn",
        "geoip": "cn",
        "outbound": "direct"
      }
    ]
  }
}

```

</details>

### Server and client log file

<details>

```console
# no, server is not runing.
```

</details>

**Comment by WFBIT** [comment]
我在小米15pro hyperOS 2.0.116系统复现同样问题。请问如何解决？
