### ISSUE TITLE
Cannot not start sing-box. "invalid MaxMind DB file"

### ISSUE THREAD

**Issue by talrasha007** [SagerNet/sing-box#1140]
### Operating system

iOS

### System version

17.1.1

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.6.6

### Description

When click start, got a  "invalid MaxMind DB file" error dialog.

### Reproduction

Actually, i tried both android & ios, if the app is newly installed ( or clear all data of the app ) , and profile has geosite/geoip rule(s), it will happen.

If updated from previous version, it works fine.

**Comment by talrasha007** [comment]
![WechatIMG1592](https://github.com/SagerNet/sing-box/assets/1478334/b819e786-6795-4883-9986-d503c201764d)

Here's the screenshot.

**Comment by CHIZI-0618** [comment]
Please configure route.geoip correctly and clear the working directory to re-download the geoip.db file
