### ISSUE TITLE
Please uninstall SystemExtension when macOS standalone version gets uninstalled

### ISSUE THREAD

**Issue by aur3l14no** [SagerNet/sing-box#1142]
### Operating system

macOS

### System version

macOS 14.1.1 23B81 arm64

### Installation type

Others

### If you are using a graphical client, please provide the version of the client.

macOS standalone 1.6.6 (from brew)

### Description

macOS standalone variant achieves VPN functionality through SystemExtension. But the installed extension is preserved after `brew uninstall sfm`.

Although the AppStore version has similar behavior by leaving the NetworkExtension on the system, the NetworkExtension is much easier to clean up. **Because cleaning up SystemExtension requires turning off the SIP,** I really hope that uninstallation can be done by sing-box.

### Reproduction

1. `brew install --cask sfm`
2. Install SystemExtension
3. `brew uninstall --cask sfm`
4. `sudo systemextensionsctl list` and it is still there

```
*       *       Z56Z6NYZN2      io.nekohasekai.sfa.system (1.6.6/1)     SystemExtension [activated enabled]
--- com.apple.system_extension.driver_extension
```

**Comment by nekohasekai** [comment]
We will be adding a button to uninstall the System Extension in the next version, and it seems you can't do it outside of the app without systemextensionsctl, nor with homebrew. Maybe you can send this issue to homebrew maintainers.
