### ISSUE TITLE
Libbox.xcframework lose

### ISSUE THREAD

**Issue by lifufa** [SagerNet/sing-box#1144]
### 操作系统

iOS

### 系统版本

any

### 安装类型

sing-box for macOS 图形客户端程序

### 版本

<details>

```console
# 使用输出内容覆盖此行
```
</details>

### 描述

source code Libbox.xcframework lose 

### 重现方式

git clone 

### 日志

<details>

```console
# 使用日志内容覆盖此行
```
</details>

**Comment by bigphonex** [comment]
没有打算提供Libbox库吗？

**Comment by huhuang03** [comment]
same as #734
