### ISSUE TITLE
Feature request: Dokodemo

### ISSUE THREAD

**Issue by jellybean13** [SagerNet/sing-box#115]
This feature can be used for port mapping.

https://www.v2ray.com/en/configuration/protocols/dokodemo.html
https://xtls.github.io/config/inbounds/dokodemo.html

**Comment by nekohasekai** [comment]
Read the documentation.

**Comment by its0ka** [comment]
@nekohasekai which page?

**Comment by its0ka** [comment]
figured it out, https://sing-box.sagernet.org/configuration/outbound/direct/
example:
{
            "listen": "0.0.0.0",
            "listen_port": 5353,
            "network": "udp",
            "override_address": "1.1.1.1",
            "override_port": 53,
            "tag": "direct-in-dns",
            "type": "direct"
}
