### ISSUE TITLE
Android 版 sing-box 1.7.0 需要获取定位权限，访问当前位置

### ISSUE THREAD

**Issue by icebluey** [SagerNet/sing-box#1160]
### 操作系统

Android

### 系统版本

Android 13

### 安装类型

sing-box for Android 图形客户端程序

### 版本

sing-box 1.7.0

### 描述

原来使用 sing-box 1.6，只有一个通知的权限。 今天升级到 sing-box 1.7.0 后，多了一个定位权限。
运行sing-box，提示获取定位信息。

一个代理软件，为什么要收集这么敏感的个人信息。

![sb](https://github.com/SagerNet/sing-box/assets/25545175/a0b57105-faa8-4c14-991a-175caa814eec)

### 重现方式

.

**Comment by kkocdko** [comment]
访问 WIFI SSID 来做分流需要这个权限。可以不给权限，不影响其他功能。

**Comment by shallbytwo** [comment]
禁用位置权限后，软件界面点击日志和配置菜单无反应，另外两个菜单点击卡顿，而且无法点击关闭代理按钮。
