### ISSUE TITLE
需要PC界面么？我想加入相关的开发工作不知道可以吗 ？

### ISSUE THREAD

**Issue by Neo110** [SagerNet/sing-box#1161]
### 操作系统

Windows

### 系统版本

QT 做界面

### 安装类型

sing-box 原始命令行程序

### 如果您使用图形客户端程序，请提供该程序版本。

需要PC界面么？我想加入相关的开发工作不知道可以吗 ？

### 版本

<details>

```console
# 使用输出内容覆盖此行
```
</details>

### 描述

需要PC界面么？我想加入相关的开发工作不知道可以吗 ？

### 重现方式

需要PC界面么？我想加入相关的开发工作不知道可以吗 ？

### 日志

<details>

```console
# 使用日志内容覆盖此行
```
</details>

**Comment by jose-C2OaWi** [comment]
你可能会对这个项目感兴趣[nekoray](https://github.com/MatsuriDayo/nekoray)
