### ISSUE TITLE
[SFA] Decode config: rule set: time: unknown unit "d" in duration "1d"

### ISSUE THREAD

**Issue by hagerliu** [SagerNet/sing-box#1163]
### Operating system

Android

### System version

crDroid-Android-14

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.8.0-alpha.5

### Description

```
"update_interval": "24h"
```
设为24h可以通过检查。

```
"update_interval": "1d"
```
按照sing-box的doc中“1d will be used if empty.”配置1d，会报错（unknown unit "d" in duration "1d"）

### Reproduction

```
"route": {
    "rule_set": [
        {
            "update_interval": "1d"
        }
    ]
}
```

**Comment by nekohasekai** [comment]
Try 1.8.0-alpha.6

**Comment by hagerliu** [comment]
solved.
