### ISSUE TITLE
Service Error

### ISSUE THREAD

**Issue by liujb** [SagerNet/sing-box#1164]
### Operating system

macOS

### System version

Version 14.1.1 (23B81)

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

Version 1.6.6 (116)

### Version

<details>

```console
# Replace this line with the output
```
</details>

### Description

(packet-tunnel) log server started
(packet-tunnel) error: start service: open geoip database: error opening database: invalid MaxMind DB file

### Reproduction

![WX20231201-142701@2x](https://github.com/SagerNet/sing-box/assets/1448432/eff35a0e-a2ee-4e4b-84ff-9c07008330ba)

### Logs

<details>

```console
# Replace this line with logs
```
</details>

**Comment by mask0918** [comment]
same with u
