### ISSUE TITLE
create service: create clash api server: cache_file and related fields in Clash API is deprecated in sing-box 1.8.0, use experimental.cache_file instead. Cannot mix synchronous and asynchronous operation on process stream.

### ISSUE THREAD

**Issue by delikkkk** [SagerNet/sing-box#1177]
### Operating system

Windows

### System version

23H2

### Installation type

Third-party graphical clients that advertise themselves as using sing-box (Windows)

### If you are using a graphical client, please provide the version of the client.

v2rayn6.30

### Version

<details>

```console
# Replace this line with the output
```
</details>

### Description

create service: create clash api server: cache_file and related fields in Clash API is deprecated in sing-box 1.8.0, use experimental.cache_file instead. Cannot mix synchronous and asynchronous operation on process stream.

### Reproduction

create service: create clash api server: cache_file and related fields in Clash API is deprecated in sing-box 1.8.0, use experimental.cache_file instead. Cannot mix synchronous and asynchronous operation on process stream.

### Logs

<details>

```console
# Replace this line with logs
```
</details>

**Comment by gg4924** [comment]
提示很清楚啊，sing-box核心自1.8版本后使用了新的配置格式，cache_file独立出来了，你使用的v2rayn6.30可能使用了新版本核心，但没有更新配置格式，还在使用旧版本配置。你要么替换v2rayn中的sing-box核心，要低于1.8版本的，比如刚发布的1.7.1，要么更新你在v2rayn中的sing-box配置。
https://sing-box.sagernet.org/migration/

**Comment by ansonfish** [comment]
> 提示很清楚啊，sing-box核心自1.8版本后使用了新的配置格式，cache_file独立出来了，你使用的v2rayn6.30可能使用了新版本核心，但没有更新配置格式，还在使用旧版本配置。你要么替换v2rayn中的sing-box核心，要低于1.8版本的，比如刚发布的1.7.1，要么更新你在v2rayn中的sing-box配置。 https://sing-box.sagernet.org/migration/

r如何更新“在v2rayn中的sing-box配置”？
