### ISSUE TITLE
打开谷歌商店会卡在启始页面

### ISSUE THREAD

**Issue by zqcnbi** [SagerNet/sing-box#1178]
### 操作系统

其他

### 系统版本

鸿蒙3.0

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.8

### 版本

<details>

```console
# 使用输出内容覆盖此行
```
</details>

### 描述

打开谷歌商店会卡在那里，不会英语 不知道是不是画圈部分的原因，有什么解决办法吗
![Screenshot_20231203_081339_io nekohasekai sfa_edit_158514953187790](https://github.com/SagerNet/sing-box/assets/52245548/126a9f40-1ec5-40dc-beec-35c95d8d3c43)
![Screenshot_20231203_081331_com android vending](https://github.com/SagerNet/sing-box/assets/52245548/d6595c35-2629-4e9a-9070-06f1ebb328e3)
，不知道是不是画圈部分的原因，有什么解决办法吗

### 重现方式

这是我的订阅       https://api.v1.mk/sub?target=singbox&url=https%3A%2F%2Fgetinfo.bigwatermelon.org%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D30b0dbae38000c36cd60bd3d035f14c4&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Mini_AdblockPlus.ini&emoji=false&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false

### 日志

<details>

```console
# 使用日志内容覆盖此行
```
</details>

**Comment by zqcnbi** [comment]
其它应用暂时没有发现这个情况，

**Comment by gg4924** [comment]
错误是fakeip-ipv6的问题，看了下你fakeip的配置：
```json
"fakeip":{"enabled":true,"inet4_range":"198.18.0.0/15"}
```
也许你需要为ipv6的fakeip指定一个范围：https://sing-box.sagernet.org/zh/configuration/dns/fakeip/
```json
{
  "enabled": true,
  "inet4_range": "198.18.0.0/15",
  "inet6_range": "fc00::/18"
}
```

**Comment by zqcnbi** [comment]
> 错误是fakeip-ipv6的问题，看了下你fakeip的配置：
> 
> ```json
> "fakeip":{"enabled":true,"inet4_range":"198.18.0.0/15"}
> ```
> 
> 也许你需要为ipv6的fakeip指定一个范围：https://sing-box.sagernet.org/zh/configuration/dns/fakeip/
> 
> ```json
> {
>   "enabled": true,
>   "inet4_range": "198.18.0.0/15",
>   "inet6_range": "fc00::/18"
> }
> ```

好的，我用的是订阅转换，不会写配置，先这样用着吧，不是什么大问题，不是软件问题就行。
