### ISSUE TITLE
Smart quotes should be disabled in the TextEditor window of the Edit Content feature.

### ISSUE THREAD

**Issue by blastmann** [SagerNet/sing-box#1182]
### Operating system

macOS

### System version

14.1.2 (23B92)

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.7.1

### Description

Smart quotes should be disabled in the TextEditor window.

<img width="314" alt="image" src="https://github.com/SagerNet/sing-box/assets/2032369/1c61959a-ec22-4779-bc2b-c0be6339b1e8">

Save the result with this, SFM will launch with error like this:

<img width="260" alt="image" src="https://github.com/SagerNet/sing-box/assets/2032369/cd724e3a-3547-4a8a-b1b6-56ccd54ed5a3">

### Reproduction

Modify text with qutoes in "Edit Content" window of profile, the orginal quotes (`"debug"`) will be replaced with Smart Quotes like `“debug”`.

**Comment by nekohasekai** [comment]
Try 1.8.0-alpha.11

**Comment by blastmann** [comment]
Not fix yet.

**Comment by nekohasekai** [comment]
Sorry, but I'm not a professional iOS developer, I tried:

```swift
TextEditor(text: $profileContent)
  .autocorrectionDisabled(true)
  .textContentType(.init(rawValue: ""))
```

But it doesn't seem to work, if you can help I'd appreciate it.

**Comment by shangjiyu** [comment]
what about this setting @blastmann 

<img width="687" alt="image" src="https://github.com/SagerNet/sing-box/assets/1223130/26fa639d-4937-44fc-a244-5c3ce4c3b4c2">

**Comment by blastmann** [comment]
> what about this setting @blastmann
> 
> <img alt="image" width="687" src="https://private-user-images.githubusercontent.com/1223130/288314953-26fa639d-4937-44fc-a244-5c3ce4c3b4c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjkzMDgsIm5iZiI6MTcwMjM2OTAwOCwicGF0aCI6Ii8xMjIzMTMwLzI4ODMxNDk1My0yNmZhNjM5ZC00OTM3LTQ0ZmMtYTI0NC01YzNjZTRjM2I0YzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMDgxNjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjhhOWI2NWU0ZmY3OWFkNjc1ZTZkNjBmZmUxNWJiZmVkOWQxNzViOTAwYWU3OTEyZmY5ZjRiN2JlZjA1YjY3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LHpALr2NCf-2j9iyoch6dnn0aXPA5UzBH_GO5knljbU">

Of course it works. But I think that is not a proper resolution for all users.
