### ISSUE TITLE
`sing-box merge` sets ntp.server_port to 0 by default instead of documented 123

### ISSUE THREAD

**Issue by aur3l14no** [SagerNet/sing-box#1186]
### Operating system

Linux

### System version

NixOS Unstable

### Installation type

Original sing-box Command Line

### Version

<details>

```console
sing-box version 1.8.0-alpha.12

Environment: go1.21.4 linux/amd64
Tags: with_quic,with_grpc,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_v2ray_api,with_gvisor
CGO: enabled
```
</details>

### Description

`sing-box merge` sets ntp.server_port to 0 by default instead of documented 123

### Reproduction

Prepare `/tmp/in.json`

``` json
{ "ntp": {} }
```

Run `sing-box merge /tmp/out.json -c /tmp/in.json`

`/tmp/out.json` now contains

``` json
{
  "ntp": {
    "enabled": false,
    "server": "",
    "server_port": 0
  }
}
```

### Logs

<details>

```console
# Replace this line with logs
```
</details>

**Comment by nekohasekai** [comment]
In most sing-box configurations, the default value is equal to unset, such as the empty string, false, or zero.

You are encountering this problem because sing-box does not have a mechanism to remove empty JSON objects during formatting. We will consider adding it.

**Comment by nekohasekai** [comment]
Shoud be fixed in the latest pre-release version.
