### ISSUE TITLE
domain_suffix不完整匹配二级域名

### ISSUE THREAD

**Issue by AoEiuV020** [SagerNet/sing-box#1189]
### Operating system

Android

### System version

13

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.7.2

### Description

clash难民刚研究换用singbox，google.com死活走了直连，研究一晚上发现，我用的规则[ChinaDomain.list](https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list) 里有一个domain_suffix le.com走直连，就是这个规则把google.com也拐到直连去了，
按理说这种domain_suffix应该要和clash一样完整匹配到某一级域名，而不是简单的字符串endsWith的逻辑， 
比如 le.com 应该匹配 *.le.com 和 le.com , 不应该匹配到google.com,

### Reproduction

添加优先规则 domain_suffix le.com 走直连，
请求 google.com， 匹配到规则, 走了直连，
实际不应该被匹配，

**Comment by PuerNya** [comment]
请变更你的写法到
```json
{
  "domain": "le.com",
  "domain_suffix": ".le.com"
}
```

**Comment by AoEiuV020** [comment]
@PuerNya 确定这样的话，那只能建议subconverter那边改了，
但是真的是这样设计的吗，有点理解不能，为什么suffix不和别家做成一样的含义，

**Comment by AoEiuV020** [comment]
@nekohasekai 还请来个有权限的给个定论，如果确实设计如此的话请直接关闭issue我好尽快推动其他项目适配这点，

**Comment by nekohasekai** [comment]
这是一个历史遗留问题，且一直无人指出。暂时没有更改语义的计划。

**Comment by alanwang776** [comment]
![image](https://github.com/SagerNet/sing-box/assets/45194309/6444a94a-5eed-4b99-bf3e-1821c79c74f5)
6万条记录变12万条呗，小菜

**Comment by muink** [comment]
确实, clash 那边用 `+.google.com` 解决 主域和子域, sing-box 需要 `domain` 和 `domain_suffix`, 仅仅只差一个 `.`, 就要两倍的儲存空间和网络传输开销.
还有想请问一下 @nekohasekai 同样的规则如果转换为 `domain_regex` 比如 `^([a-zA-Z0-9_-]+\\.)*google\\.com$`
会导致性能开销大幅提升吗

**Comment by nekohasekai** [comment]
只有 JSON 会有存储空间和流量开销，使用二进制格式没有开销。
