### ISSUE TITLE
Problem if ALPN set as h2

### ISSUE THREAD

**Issue by robin98** [SagerNet/sing-box#1190]
### Operating system

Others

### System version

Windows 10 / Android

### Installation type

Third-party graphical clients that advertise themselves as using sing-box (Windows)

### If you are using a graphical client, please provide the version of the client.

Nekoray 3.25 / Nekobox 1.2.9

### Description

In both windows and android, I have this same problem; And I came with this conclusion that maybe you can assist.
In all my Vless configs with these specifications --> (vless, Cloudflare's CDN enabled, ws tls, alpn: 2), they are all unavailable while I use the sing-box as the core, but there is NO problem about vless-reality ones.
After many attempts, I find out that the problem was the ALPN! in fact, when I set the ALPN to `http/1.1` or `h3` they will became available right away.
why sing-box can't handle the `h2` as ALPN in my case? 
The short-term solution I came around that I set all the ALPNs as `h3`, but for long-term solution it is not the answer.

_Also, I have this idea that h2 is better and faster than http/1.1 (as a parameter in the ALPN field), But I'm not sure if it has any advantage in real scenarios, that's why I like to keep h2 as my default ALPN_ 

### Reproduction

- In the Nekoray for windows, set the sing-box as the core
- Select a server with this these specification --> (vless, Cloudflare's CDN enabled, ws tls, alpn: 2)
- - I don't know if you apply alpn: 2 on your vmess, you hit the same problem or not
- After that, run a `Url Test` or just simply try to connect it
- You can see there is no Rx/TX
- Then change the ALPN manually into `h3`
- Now it may starts working for you

### Logs

<details>

```console
# ERROR[0025] [3152271769 1.72s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:9523: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00d\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\x7f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"
```
</details>

**Comment by KevinMX** [comment]
Sorry but we usually don't handle issues from 3rd party GUI clients here.
I suggest you refer this issue to Nekoray / Nekobox themselves.

**Comment by molink36** [comment]
I have the same problem using sing-box v1.8.12. Setting ALPN as h3 or http/1.1 instead of h2 in the configuration file resolves the problem.
