### ISSUE TITLE
服务端必须指定 Method of HTTP request

### ISSUE THREAD

**Issue by nobody-99** [SagerNet/sing-box#1191]
### Operating system

Linux

### System version

debian 11

### Installation type

Original sing-box Command Line

### Version

<details>

```console
# Replace this line with the output
```
</details>

### Description

 > method
 >Method of HTTP request.
 >The server will verify if not empty.

按我的理解 服务端如果留空的话, 客户端可以任意配置, 实际上 服务端必须配置成与客户端一致
其他的配置选项`host` `path` `header` 则可以留空

### Reproduction

- server config
```json
"transport": {
        "type": "http"
      }
```

- client config
```json
"transport": {
        "type": "http",
        "host": [
          "***"
        ],
        "path": "/",
        "method": "CONNECT",
        "headers": {
          "Connection": [
            "keep-alive"
          ]
        }
      }
```

### Logs

<details>

```console
ERROR inbound/vmess[3]: process connection from *** bad method: CONNECT
```
</details>

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/466985403932f9ea965ff8f6f7f2d9678d430d4c
