### ISSUE TITLE
Wonder whether Sing-box supports multiple configure

### ISSUE THREAD

**Issue by ChaingTsung** [SagerNet/sing-box#1195]
There is a lot of configs in dir `/etc/sing-box`:
- 01-hy.json
- 02-ss.json
- 03-troja.json

### Does `sing-box` make  them work fine at the same time ?

**Comment by CHIZI-0618** [comment]
https://sing-box.sagernet.org/changelog/#12-beta10
https://sing-box.sagernet.org/changelog/#120
