### ISSUE TITLE
局域网内共享代理出错

### ISSUE THREAD

**Issue by Xie-Muxi** [SagerNet/sing-box#1201]
### 操作系统

Linux

### 系统版本

服务端: Ubuntu 22.04.2 LTS

### 安装类型

sing-box 原始命令行程序

### 版本

<details>

```console
sing-box version 1.8.0-alpha.13

Environment: go1.21.4 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: e839711d43996a819c7f3add3286ca1fc53f19fa
CGO: disabled
```
</details>

### 描述

两台内网中的Linux（A，B），A部署sing-box，A 中设置http，https ，socks5 使用sing box的2080端口代理，“curl google.com” 有结果。
但是 B 设置 http，https，socks5 代理均为 A的2080端口，B中curl google.com 超时。
同样的操作使用clash就没问题，B中一切正常

clash代理，Connection 中 仅有socks5 -> direct，但"curl google.com" 有结果
sing-box代理，Connection 中 仅有 ip_is_private -> direct，"curl google.com" 超时

### 重现方式

0. 任一“https://sing-box-subscribe.vercel.app” 订阅转换后修改配置文件
```
    "inbounds": [
        {
            "type": "tun",
            "inet4_address": "172.19.0.1/30",
            "mtu": 9000,
            "auto_route": true,
            "strict_route": true,
            "sniff": true,
            "endpoint_independent_nat": false,
            "stack": "system",
            "platform": {
                "http_proxy": {
                    "enabled": true,
                    "server": "127.0.0.1",
                    "server_port": 2080
                }
            }
        },
        {
            "type": "mixed",
            "listen": "0.0.0.0",
            "listen_port": 2080,
            "sniff": true
        }
```
1. 局域网内一台机器A部署sing-box代理， 局域网内另一台机器B在终端中
```shell
export http_proxy="http://server_ip:2080"
export https_proxy="http://server_ip:2080"
export all_proxy=socks5://server_ip:2080
```
2. B中测试
```shell
curl google.com 
```

### 日志

<details>

```console
# 使用日志内容覆盖此行
```
</details>

**Comment by nekohasekai** [comment]
http://sing-box.sagernet.org/configuration/inbound/tun/#strict_route

**Comment by Xie-Muxi** [comment]
> http://sing-box.sagernet.org/configuration/inbound/tun/#strict_route

谢谢您，还有个问题方便请教么？

我发现在macOS端设置
        {
            "type": "mixed",
            "listen": "0.0.0.0",
            "listen_port": 2080,
            "sniff": true
        }
会无网络，而Linux端则不会，可能的原因是？
