### ISSUE TITLE
Sing-Box内核连接Vless节点时，出现各种大量ERROR

### ISSUE THREAD

**Issue by cjchome** [SagerNet/sing-box#1202]
### 操作系统

Windows

### 系统版本

Windows 11

### 安装类型

sing-box 原始命令行程序

### 如果您使用图形客户端程序，请提供该程序版本。

NekoRay 3.25 / V2RayN 6.31

### 版本

Sing-box 1.6.4-2
Sing-box 1.6.7

### 描述

使用NekoRay的Sing-Box内核连接Vless节点时，出现大量ERROR ，每次访问网页都会循环出现以下几类错误，同样的节点换到V2RayN的Xray内核就不会报错，但将V2RayN切换成Sing-Box内核又出现同样的错误，所以判断是Sing-Box的问题，请帮忙解决一下，谢谢！多数ERROR信息如下面的截图或日志里的Log：
![Vless01](https://github.com/SagerNet/sing-box/assets/30073216/41a8712b-06f9-4a93-9537-3b2da28dc9b2)
![Vless02](https://github.com/SagerNet/sing-box/assets/30073216/7f3f32df-f8ae-43eb-b5c4-ed8f6d7d45c4)
![Vless03](https://github.com/SagerNet/sing-box/assets/30073216/65d0b48f-4d1f-4e76-b7fc-5cf8ccaf78f5)

### 重现方式

内核切换成Sing-Box，连接Vless节点

### 日志

ERROR[0478] [2050828555 1m25s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:62620: download: websocket: close 1005 (no status)
ERROR[0478] [1125965107 1m25s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:62619: download: websocket: close 1005 (no status)
ERROR[0478] [1775301189 1m25s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:62624: download: websocket: close 1005 (no status)
ERROR[0478] [4196978538 1m25s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:62618: download: websocket: close 1005 (no status)
......
ERROR[0203] [3557768884 2.23s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:17223: upload: read tcp 127.0.0.1:2080->127.0.0.1:17223: wsarecv: An existing connection was forcibly closed by the remote host. | download: websocket: close 1005 (no status)
......
ERROR[0217] [346144037 24ms] inbound/mixed[mixed-in]: process connection from 127.0.0.1:32169: exchange6: name error | exchange4: name error
......
ERROR[0217] [2992198765 0ms] inbound/mixed[mixed-in]: process connection from 127.0.0.1:32170: exchange4: name error | exchange6: name error
......
ERROR[0215] [1688793217 390ms] inbound/mixed[mixed-in]: process connection from 127.0.0.1:47529: download: write tcp 127.0.0.1:2080->127.0.0.1:47529: wsasend: An established connection was aborted by the software in your host machine.
ERROR[0215] [3097292674 507ms] inbound/mixed[mixed-in]: process connection from 127.0.0.1:47528: download: websocket: close 1005 (no status)

**Comment by KevinMX** [comment]
- 缺少配置文件
- 这里通常不处理第三方图形客户端的问题
