### ISSUE TITLE
Sing-Box内核连接ws协议的Vless节点时，出现各种ERROR

### ISSUE THREAD

**Issue by cjchome** [SagerNet/sing-box#1206]
### Operating system

Windows

### System version

Windows 11

### Installation type

Original sing-box Command Line

### Version

sing-box-1.7.2-windows-amd64

### Description

使用Sing-Box内核连接ws协议的Vless节点，出现大量各种ERROR ，每次访问网页都会循环出现以下几类错误，开启tls的节点也有，同样节点在Xray内核下没有这些错误，请帮忙解决一下，谢谢！
Ps：因为节点的隐私性，其server、uuid和 Host已被修改，仅供分析，不能连接，请理解
[config.json](https://github.com/SagerNet/sing-box/files/13607600/config.json)
[sing-box.log](https://github.com/SagerNet/sing-box/files/13607601/sing-box.log)

### Reproduction

用Sing-box跑一个ws协议的Vless节点，多访问几个网站，就会有ERROR显现。

### Logs

PS A:\sing-box-1.7.2-windows-amd64> .\sing-box.exe run -c .\config.json
+0800 2023-12-08 07:57:56 ERROR [4165414488 830ms] inbound/http[http]: process connection from 127.0.0.1:63479: download: ws closed: 1005
+0800 2023-12-08 07:58:22 ERROR [2189582976 79ms] inbound/http[http]: process connection from 127.0.0.1:45499: download: read tcp 192.168.50.120:45502->116.236.212.152:443: wsarecv: An existing connection was forcibly closed by the remote host.
+0800 2023-12-08 07:58:31 ERROR [573280310 882ms] inbound/http[http]: process connection from 127.0.0.1:45509: download: write tcp 127.0.0.1:10809->127.0.0.1:45509: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 07:58:51 ERROR [173304806 29.14s] inbound/http[http]: process connection from 127.0.0.1:45497: download: write tcp 192.168.50.120:45503->172.64.146.66:80: wsasend: A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call.
+0800 2023-12-08 07:59:12 ERROR [3674660129 749ms] inbound/http[http]: process connection from 127.0.0.1:27894: download: write tcp 127.0.0.1:10809->127.0.0.1:27894: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 07:59:24 ERROR [1012762786 2.20s] inbound/http[http]: process connection from 127.0.0.1:18660: download: write tcp 127.0.0.1:10809->127.0.0.1:18660: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 07:59:28 ERROR [70017414 2.25s] inbound/http[http]: process connection from 127.0.0.1:18668: download: write tcp 127.0.0.1:10809->127.0.0.1:18668: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 07:59:29 ERROR [2598617036 896ms] inbound/http[http]: process connection from 127.0.0.1:18670: download: write tcp 127.0.0.1:10809->127.0.0.1:18670: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 07:59:47 ERROR [1758898792 18.97s] inbound/http[http]: process connection from 127.0.0.1:18671: download: write tcp 127.0.0.1:10809->127.0.0.1:18671: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:00:04 ERROR [1530473533 1.33s] inbound/http[http]: process connection from 127.0.0.1:14165: download: write tcp 127.0.0.1:10809->127.0.0.1:14165: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:00:09 ERROR [1292114278 537ms] inbound/http[http]: process connection from 127.0.0.1:14187: download: write tcp 127.0.0.1:10809->127.0.0.1:14187: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:00:13 ERROR [1360999890 2.12s] inbound/http[http]: process connection from 127.0.0.1:14207: download: write tcp 127.0.0.1:10809->127.0.0.1:14207: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:00:13 ERROR [1930066432 2.13s] inbound/http[http]: process connection from 127.0.0.1:14205: download: write tcp 127.0.0.1:10809->127.0.0.1:14205: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:00:14 ERROR [4248027421 56.61s] inbound/http[http]: process connection from 127.0.0.1:27926: download: write tcp 127.0.0.1:10809->127.0.0.1:27926: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:00:14 ERROR [2020154287 56.61s] inbound/http[http]: process connection from 127.0.0.1:27928: download: write tcp 127.0.0.1:10809->127.0.0.1:27928: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:00:15 ERROR [113338469 1.11s] inbound/http[http]: process connection from 127.0.0.1:14219: download: write tcp 127.0.0.1:10809->127.0.0.1:14219: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:02:55 ERROR [903983702 737ms] inbound/http[http]: process connection from 127.0.0.1:14265: download: write tcp 127.0.0.1:10809->127.0.0.1:14265: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:02:55 ERROR [2951322198 777ms] inbound/http[http]: process connection from 127.0.0.1:14270: download: write tcp 127.0.0.1:10809->127.0.0.1:14270: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:02:55 ERROR [2931361796 807ms] inbound/http[http]: process connection from 127.0.0.1:14263: download: write tcp 127.0.0.1:10809->127.0.0.1:14263: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:02:55 ERROR [1559021688 781ms] inbound/http[http]: process connection from 127.0.0.1:14266: download: write tcp 127.0.0.1:10809->127.0.0.1:14266: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:02:55 ERROR [3150329545 820ms] inbound/http[http]: process connection from 127.0.0.1:14269: download: write tcp 127.0.0.1:10809->127.0.0.1:14269: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:07:12 ERROR [3986262565 908ms] inbound/http[http]: process connection from 127.0.0.1:14985: download: write tcp 192.168.50.120:14986->172.64.146.66:80: wsasend: A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call.
+0800 2023-12-08 08:07:16 ERROR [2634980286 1.12s] inbound/http[http]: process connection from 127.0.0.1:24516: download: write tcp 127.0.0.1:10809->127.0.0.1:24516: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:07:16 ERROR [1102162649 1.12s] inbound/http[http]: process connection from 127.0.0.1:24517: download: write tcp 127.0.0.1:10809->127.0.0.1:24517: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:07:22 ERROR [3331195170 552ms] inbound/http[http]: process connection from 127.0.0.1:22121: download: write tcp 127.0.0.1:10809->127.0.0.1:22121: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:07:28 ERROR [4214512663 1.82s] inbound/http[http]: process connection from 127.0.0.1:22130: download: write tcp 127.0.0.1:10809->127.0.0.1:22130: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:07:37 ERROR [1881137071 577ms] inbound/http[http]: process connection from 127.0.0.1:22172: download: write tcp 127.0.0.1:10809->127.0.0.1:22172: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:07:40 ERROR [3983357830 733ms] inbound/http[http]: process connection from 127.0.0.1:22189: download: write tcp 127.0.0.1:10809->127.0.0.1:22189: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:07:43 ERROR [1492425537 235ms] inbound/http[http]: process connection from 127.0.0.1:32169: exchange6: name error | exchange4: name error
+0800 2023-12-08 08:07:46 ERROR [1492425535 702ms] inbound/http[http]: process connection from 127.0.0.1:22200: download: write tcp 127.0.0.1:10809->127.0.0.1:22200: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:08:28 ERROR [2635344273 27.72s] inbound/http[http]: process connection from 127.0.0.1:22229: download: write tcp 127.0.0.1:10809->127.0.0.1:22229: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:08:31 ERROR [2130094447 3.17s] inbound/http[http]: process connection from 127.0.0.1:22258: download: write tcp 127.0.0.1:10809->127.0.0.1:22258: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:08:33 ERROR [2362042991 532ms] inbound/http[http]: process connection from 127.0.0.1:32170: exchange4: name error | exchange6: name error
+0800 2023-12-08 08:08:36 ERROR [2362042994 2.55s] inbound/http[http]: process connection from 127.0.0.1:22274: download: write tcp 127.0.0.1:10809->127.0.0.1:22274: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:09:03 ERROR [669704674 753ms] inbound/http[http]: process connection from 127.0.0.1:22287: download: write tcp 127.0.0.1:10809->127.0.0.1:22287: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:09:30 ERROR [2652808885 816ms] inbound/http[http]: process connection from 127.0.0.1:12855: download: write tcp 127.0.0.1:10809->127.0.0.1:12855: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:09:30 ERROR [3793748738 840ms] inbound/http[http]: process connection from 127.0.0.1:12854: download: write tcp 127.0.0.1:10809->127.0.0.1:12854: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:09:37 ERROR [4005573102 731ms] inbound/http[http]: process connection from 127.0.0.1:1210: download: write tcp 127.0.0.1:10809->127.0.0.1:1210: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:09:40 ERROR [2357981274 1.71s] inbound/http[http]: process connection from 127.0.0.1:1222: download: write tcp 127.0.0.1:10809->127.0.0.1:1222: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:09:53 ERROR [826508251 925ms] inbound/http[http]: process connection from 127.0.0.1:1258: download: write tcp 127.0.0.1:10809->127.0.0.1:1258: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:11:48 ERROR [759421203 821ms] inbound/http[http]: process connection from 127.0.0.1:53181: download: write tcp 127.0.0.1:10809->127.0.0.1:53181: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:13:44 ERROR [876468909 26ms] inbound/http[http]: process connection from 127.0.0.1:4046: dial tcp [2408:8220:310:76f0::8]:443: connectex: A socket operation was attempted to an unreachable network.
+0800 2023-12-08 08:13:44 ERROR [3897632689 1ms] inbound/http[http]: process connection from 127.0.0.1:4050: dial tcp [2408:8220:310:76f0::8]:443: connectex: A socket operation was attempted to an unreachable network.
+0800 2023-12-08 08:13:44 ERROR [2319517123 1ms] inbound/http[http]: process connection from 127.0.0.1:4052: dial tcp [2408:8220:310:76f0::8]:443: connectex: A socket operation was attempted to an unreachable network.
+0800 2023-12-08 08:13:45 ERROR [2923011861 25ms] inbound/http[http]: process connection from 127.0.0.1:4064: dial tcp [2408:8220:310:76f0::8]:443: connectex: A socket operation was attempted to an unreachable network.
+0800 2023-12-08 08:13:45 ERROR [967286643 1ms] inbound/http[http]: process connection from 127.0.0.1:4066: dial tcp [2408:8220:310:76f0::8]:443: connectex: A socket operation was attempted to an unreachable network.
+0800 2023-12-08 08:13:45 ERROR [3783896827 0ms] inbound/http[http]: process connection from 127.0.0.1:4068: dial tcp [2408:8220:310:76f0::8]:443: connectex: A socket operation was attempted to an unreachable network.
+0800 2023-12-08 08:15:19 ERROR [3735832019 14.43s] inbound/http[http]: process connection from 127.0.0.1:61857: write tcp 127.0.0.1:10809->127.0.0.1:61857: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:16:29 ERROR [1307559391 750ms] inbound/http[http]: process connection from 127.0.0.1:9008: download: write tcp 127.0.0.1:10809->127.0.0.1:9008: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:17:15 ERROR [557946059 545ms] inbound/http[http]: process connection from 127.0.0.1:39626: download: write tcp 127.0.0.1:10809->127.0.0.1:39626: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:17:15 ERROR [4075658537 117ms] inbound/http[http]: process connection from 127.0.0.1:39628: download: write tcp 127.0.0.1:10809->127.0.0.1:39628: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:19:06 ERROR [450146656 8.21s] inbound/http[http]: process connection from 127.0.0.1:46924: download: write tcp 127.0.0.1:10809->127.0.0.1:46924: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:19:06 ERROR [880946348 8.26s] inbound/http[http]: process connection from 127.0.0.1:46925: download: write tcp 127.0.0.1:10809->127.0.0.1:46925: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:19:06 ERROR [441337118 5.62s] inbound/http[http]: process connection from 127.0.0.1:46928: download: write tcp 127.0.0.1:10809->127.0.0.1:46928: wsasend: An established connection was aborted by the software in your host machine.
+0800 2023-12-08 08:19:06 ERROR [3088295930 11.3s] inbound/http[http]: process connection from 127.0.0.1:46918: download: write tcp 127.0.0.1:10809->127.0.0.1:46918: wsasend: An established connection was aborted by the software in your host machine.

**Comment by hb-0** [comment]
为什么close了？我也发现ws协议会出现exchange4: name error问题了，grpc的不没发现有同样问题。

**Comment by softenware** [comment]
> 解决了大哥，我也遇到这个问题了

怎么解决的？

**Comment by YangWudi233** [comment]
我也没解决，我感觉是服务器vps的问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月10日 12:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [SagerNet/sing-box] Sing-Box内核连接ws协议的Vless节点时，出现各种ERROR (Issue #1206) |

解决了大哥，我也遇到这个问题了

怎么解决的？
