### ISSUE TITLE
我不明白软件要求用户的精准定位是啥意思

### ISSUE THREAD

**Issue by ts2021a** [SagerNet/sing-box#1212]

**Comment by shallbytwo** [comment]
1.7.0加入的新功能（获取SSID信息），而谷歌要求获取SSID信息必须获取位置权限，所以开发者只能要求这个权限了。实测关闭位置权限软件界面卡死，建议优化下。

**Comment by nekohasekai** [comment]
AOSP 没有任何问题，如果你在国产 ROM 遇到问题，请提交 logcat。

**Comment by shallbytwo** [comment]
> AOSP 没有任何问题，如果你在国产 ROM 遇到问题，请提交 logcat。

日志文件有点大，超过github大小了，怎么能发给你

**Comment by Weltolk** [comment]
> > 1.7.0加入的新功能（获取SSID信息），而谷歌要求获取SSID信息必须获取位置权限，所以开发者只能要求这个权限了。实测关闭位置权限软件界面卡死，建议优化下。
> 
> 为什么要获取SSID呢？哪个功能需要SSID的信息呀？

[https://sing-box.sagernet.org/configuration/dns/rule/#wifi_ssid](https://sing-box.sagernet.org/configuration/dns/rule/#wifi_ssid)

![Image](https://github.com/user-attachments/assets/e667203f-6583-43fd-85bf-10a44e129289)
