### ISSUE TITLE
macOS无法监听0.0.0.0端口

### ISSUE THREAD

**Issue by Xie-Muxi** [SagerNet/sing-box#1214]
### 操作系统

macOS

### 系统版本

14.2 (23C64)

### 安装类型

sing-box for macOS 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.8.0-alpha.13

### 描述

配置文件 inbounds
{
"type": "mixed",
"listen": "0.0.0.0",
"listen_port": 2080,
"sniff": true
}
会无网络，同样配置文件在Ubuntu22.04 LTS 不会， macOS 防火墙已关闭

此时9091端口的WebUI也打不开

### 重现方式

    "experimental": {
        "clash_api": {
            "external_controller": "0.0.0.0:9091",
            "external_ui_download_url": "",
            "external_ui_download_detour": "",
            "external_ui": "ui",
            "secret": "",
            "default_mode": "rule"
        },
        "cache_file": {
            "enabled": true,
            "store_fakeip": false
        }
        
            "inbounds": [
        {
            "type": "tun",
            "inet4_address": "172.19.0.1/30",
            "mtu": 9000,
            "auto_route": true,
            "strict_route": false,
            "sniff": true,
            "endpoint_independent_nat": false,
            "stack": "system",
            "platform": {
                "http_proxy": {
                    "enabled": true,
                    "server": "127.0.0.1",
                    "server_port": 2080
                }
            }
        },
        {
            "type": "mixed",
            "listen": "0.0.0.0",
            "listen_port": 2080,
            "sniff": true
        }

### 完整性要求

- [X] 我保证

### 负责性要求

- [X] 我保证

**Comment by nekohasekai** [comment]
Network Extension 导致的的预期行为，使用 `127.0.0.1` 以供本机访问。
