### ISSUE TITLE
TUN Exclude  0.0.0.0/8 后无法隐藏VPN图标

### ISSUE THREAD

**Issue by peanut996** [SagerNet/sing-box#1216]
### Operating system

iOS

### System version

17.1.2

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.7.2

### Description

在 tun 的配置中尝试 exclude `0.0.0.0/8` 路由，无法隐藏iOS状态栏vpn图标
配置如下

```json 
    {
      "type": "tun",
      "tag": "tun-in",
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "sniff": true,
      "inet4_route_exclude_address": [
        "0.0.0.0/8"
      ]
    }
```

### Reproduction

iOS客户端写入tun配置，启动后，vpn图标仍然存在

**Comment by shallbytwo** [comment]
> ### Operating system
> iOS
> 
> ### System version
> 17.1.2
> 
> ### Installation type
> sing-box for iOS Graphical Client
> 
> ### If you are using a graphical client, please provide the version of the client.
> 1.7.2
> 
> ### Version
> _No response_
> 
> ### Description
> 在 tun 的配置中尝试 exclude `0.0.0.0/8` 路由，无法隐藏iOS状态栏vpn图标 配置如下
> 
> ```json
>     {
>       "type": "tun",
>       "tag": "tun-in",
>       "inet4_address": "172.19.0.1/30",
>       "auto_route": true,
>       "sniff": true,
>       "inet4_route_exclude_address": [
>         "0.0.0.0/8"
>       ]
>     }
> ```
> 
> ### Reproduction
> iOS客户端写入tun配置，启动后，vpn图标仍然存在
> 
> ### Logs
> _No response_

试试0.0.0.0/31

**Comment by peanut996** [comment]
> > ### Operating system
> > iOS
> > ### System version
> > 17.1.2
> > ### Installation type
> > sing-box for iOS Graphical Client
> > ### If you are using a graphical client, please provide the version of the client.
> > 1.7.2
> > ### Version
> > _No response_
> > ### Description
> > 在 tun 的配置中尝试 exclude `0.0.0.0/8` 路由，无法隐藏iOS状态栏vpn图标 配置如下
> > ```json
> >     {
> >       "type": "tun",
> >       "tag": "tun-in",
> >       "inet4_address": "172.19.0.1/30",
> >       "auto_route": true,
> >       "sniff": true,
> >       "inet4_route_exclude_address": [
> >         "0.0.0.0/8"
> >       ]
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Reproduction
> > iOS客户端写入tun配置，启动后，vpn图标仍然存在
> > ### Logs
> > _No response_
> 
> 试试0.0.0.0/31

试了以下也还是不行。。。

**Comment by peanut996** [comment]
iOS1.7.5版本已经修复

exclude 路由0.0.0.0/31即可隐藏
