### ISSUE TITLE
singbox 安卓版 禁用位置权限卡顿问题

### ISSUE THREAD

**Issue by shallbytwo** [SagerNet/sing-box#1219]
### Operating system

Android

### System version

hyperOS 和MIUI

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.7.2及以上

### Description

禁用位置权限后，软件界面开启代理后下面菜单点击卡顿，只有最左边和最右边偶尔能点击，停止按钮点击也没有反应。

### Reproduction

必复现，开启位置权限后一切正常

### Logs

```shell
https://file.io/ZZxpL3lKUMGd
```

**Comment by nekohasekai** [comment]
AOSP 没有问题。我没有相关设备用于测试。

**Comment by OG-C** [comment]
同样有这个问题
