### ISSUE TITLE
Ws + host

### ISSUE THREAD

**Issue by M03ED** [SagerNet/sing-box#1235]
### Operating system

Android

### System version

Android 13

### Installation type

sing-box for Android Graphical Client

### Description

hey guys 
there is any way to use ws transport with request host ?
in your configuration host its only available for http transport but in v2rayn we can use it with ws too.
here is a example config
```
vless://c2631dbd-ec58-4b27-acbf-0e31b6207916@cloudflare.com:2052?encryption=none&security=none&fp=random&type=ws&host=randomkajvd.tech&path=%2F#WS%20%2B%20Host
```
this is useable for cloudflare configs and its very good

### Reproduction

unknown field "host"

**Comment by lux5am** [comment]
```json
{
  "type": "ws",
  "path": "/",
  "headers": {
    "Host": "randomkajvd.tech"
  }
}
```

**Comment by M03ED** [comment]
> ```json
> "transport": {
>   "type": "ws",
>   "path": "/",
>   "headers": {
>     "Host": "randomkajvd.tech"
>   }
> }
> ```

thank you
so if we should put host in headers , what is host usage in http ?
```json
{
  "type": "http",
  "host": [],
  "path": "",
  "method": "",
  "headers": {},
  "idle_timeout": "15s",
  "ping_timeout": "15s"
}
```
