### ISSUE TITLE
win11跑核心，用winsw把singbox添加为系统服务开机自启动，当DNS设置为dhcp://auto，win开机后singbox服务启动后秒停止

### ISSUE THREAD

**Issue by caigemy** [SagerNet/sing-box#1242]
### 操作系统

Windows

### 系统版本

win11 X64 23H2

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
winsw.log
2023-12-14T23:25:07.190 DEBUG console - Starting WinSW in service mode.
2023-12-14T23:25:07.232 INFO  console - Service 'sing-box (sing-box)' was refreshed successfully.
2023-12-14T23:25:07.250 INFO  service - Starting ./sing-box.exe
2023-12-14T23:25:07.295 INFO  service - Started process sing-box (6988).
2023-12-14T23:25:07.313 INFO  service - Service started successfully.
2023-12-14T23:25:07.467 WARN  service - Child process 'sing-box (6988)' finished with code 1.
```

### 描述

第一次提issue。我是win11跑核心，用winsw把sing-box添加为系统服务开机自启动，当直连DNS设置为dhcp://auto，win开机后singbox服务启动后秒停止，需要自己手动重新启动sing-box服务，才能正常运行，只要运行起来，上网是正常的。如果DNS不用dhcp://auto，用公共DNS或者路由器地址，就不会出现开机启动秒停止这样的问题。因为sing-box开机启动到停止，时间不到1S，所以输出的日志为空，但是winsw输出了工作日志和崩溃的原因，我把它上传了，本人比较小白，不知道是否还需要别的信息。如果需要我会继续上传，我家里的上网环境也比较简单，光猫下面接了一个tp的硬路由拨号然后一根网线连接电脑。现在就是不知道问题到底出在哪里？有没有大佬帮忙诊断一下。

### 重现方式

{
  "log": {
    "level": "debug",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "proxy",
        "address": "https://1.1.1.1/dns-query"
      },
      {
        "tag": "local",
        "address": "dhcp://auto",
        "detour": "direct"
      },
      {
        "tag": "fakeip",
        "address": "fakeip"
      }
    ],
    "rules": [
      {
        "outbound": "any",
        "server": "local"
      },
      {
        "clash_mode": "direct",
        "server": "local"
      },
      {
        "clash_mode": "global",
        "server": "proxy"
      },
      {
        "ip_version": 4,
        "rule_set": "geosite-cn",
        "server": "local"
      },
      {
        "query_type": [
          "A",
          "AAAA"
        ],
        "server": "fakeip"
      }
    ],
    "strategy": "prefer_ipv4",
    "fakeip": {
      "enabled": true,
      "inet4_range": "198.18.0.0/15",
      "inet6_range": "fc00::/18"
    },
    "independent_cache": true
  },
  "inbounds": [
    {
      "type": "tun",
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "auto_route": true,
      "strict_route": true
    },
    {
      "type": "mixed",
      "listen": "0.0.0.0",
      "listen_port": 2080,
      "users": []
    }
  ],
  "outbounds": [
    {
      "type": "selector",
      "tag": "🪜 proxy",
      "outbounds": [
        "🚗 auto",
        "direct",
        "节点名"
      ],
      "filter": [
        {
          "action": "include",
          "keywords": [
            "🇸🇬|SG|sg|新加坡|狮|🇭🇰|HK|hk|香港|港|HongKong|🇯🇵|JP|jp|日本|日|🇹🇼|🇺🇸|US|us|美国|美|TW|tw|台湾|台|🇰🇷|kr|KR|韩国|韩"
          ]
        }
      ]
    },
    {
      "type": "selector",
      "tag": "🌏 Google",
      "outbounds": [
        "节点名"
      ],
      "filter": [
        {
          "action": "include",
          "keywords": [
            "🇸🇬|SG|sg|新加坡|狮|🇭🇰|HK|hk|香港|港|HongKong|🇯🇵|JP|jp|日本|日|🇹🇼|🇺🇸|US|us|美国|美|TW|tw|台湾|台|🇰🇷|kr|KR|韩国|韩"
          ]
        }
      ]
    },
    {
      "type": "selector",
      "tag": "✈️ Telegram",
      "outbounds": [
        "节点名"
      ],
      "filter": [
        {
          "action": "include",
          "keywords": [
            "🇸🇬|SG|sg|新加坡|狮|🇭🇰|HK|hk|香港|港|HongKong|🇯🇵|JP|jp|日本|日|🇹🇼|🇺🇸|US|us|美国|美|TW|tw|台湾|台"
          ]
        }
      ]
    },
    {
      "type": "selector",
      "tag": "🧩 Microsoft",
      "outbounds": [
        "direct",
        节点名
      ],
      "filter": [
        {
          "action": "include",
          "keywords": [
            "🇸🇬|SG|sg|新加坡|狮|🇭🇰|HK|hk|香港|港|HongKong|🇯🇵|JP|jp|日本|日|🇹🇼|🇺🇸|US|us|美国|美|TW|tw|台湾|台|🇰🇷|kr|KR|韩国|韩"
          ]
        }
      ]
    },
    {
      "type": "selector",
      "tag": "🤖 OpenAI",
      "outbounds": [
        "direct",
        "节点名"
      ],
      "filter": [
        {
          "action": "include",
          "keywords": [
            "🇺🇸|US|us|美国|美|🇸🇬|SG|sg|新加坡|狮|🇯🇵|JP|jp|日本|日|🇹🇼|TW|tw|台湾|台"
          ]
        }
      ]
    },
    {
      "type": "urltest",
      "tag": "🚗 auto",
      "outbounds": [
        "节点名"
      ],
      "filter": [
        {
          "action": "include",
          "keywords": [
            "🇸🇬|SG|sg|新加坡|狮|🇭🇰|HK|hk|香港|港|HongKong|🇯🇵|JP|jp|日本|日|🇹🇼|🇺🇸|US|us|美国|美|TW|tw|台湾|台|🇰🇷|kr|KR|韩国|韩"
          ]
        }
      ],
      "url": "https://www.gstatic.com/generate_204",
      "interval": "1m",
      "tolerance": 50
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "dns",
      "tag": "dns"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      所有节点的配置
    }
  ],
  "route": {
    "rules": [
      {
        "type": "logical",
        "mode": "or",
        "rules": [
          {
            "protocol": "dns"
          },
          {
            "port": 53
          }
        ],
        "outbound": "dns"
      },
      {
        "type": "logical",
        "mode": "or",
        "rules": [
          {
            "protocol": [
              "quic",
              "stun"
            ]
          },
          {
            "network": "udp",
            "port": [
              443,
              853
            ]
          }
        ],
        "outbound": "block"
      },
      {
        "clash_mode": "direct",
        "outbound": "direct"
      },
      {
        "clash_mode": "global",
        "outbound": "🪜 proxy"
      },
      {
        "rule_set": "geosite-openai",
        "outbound": "🤖 OpenAI"
      },
      {
        "rule_set": [
          "geosite-onedrive"
        ],
        "outbound": "🪜 proxy"
      },
      {
        "rule_set": [
          "geosite-google",
          "geosite-google@cn",
          "geosite-github",
          "geosite-youtube",
          "geosite-youtube@cn"
        ],
        "outbound": "🌏 Google"
      },
      {
        "rule_set": "geoip-google",
        "outbound": "🌏 Google"
      },
      {
        "rule_set": "geosite-microsoft",
        "outbound": "🧩 Microsoft"
      },
      {
        "rule_set": [
          "geosite-telegram",
          "geosite-twitter",
          "geosite-facebook"
        ],
        "outbound": "✈️ Telegram"
      },
      {
        "rule_set": [
          "geoip-telegram",
          "geoip-twitter",
          "geoip-facebook"
        ],
        "outbound": "✈️ Telegram"
      },
      {
        "ip_is_private": true,
        "outbound": "direct"
      },
      {
        "rule_set": "geosite-cn",
        "outbound": "direct"
      },
      {
        "rule_set": "geoip-cn",
        "outbound": "direct"
      }
    ],
    "final": "🪜 proxy",
    "auto_detect_interface": true,
    "rule_set": [
      {
        "type": "remote",
        "tag": "geosite-cn",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/cn.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geoip-cn",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/cn.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geosite-openai",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/openai.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geosite-onedrive",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/onedrive.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geosite-google",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/google.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geosite-google@cn",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/google%40cn.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geoip-google",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/google.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geosite-github",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/github.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geosite-youtube",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/youtube.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geosite-youtube@cn",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/youtube%40cn.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geosite-microsoft",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/microsoft.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geosite-telegram",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/telegram.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geosite-twitter",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/twitter.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geosite-facebook",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/facebook.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geoip-telegram",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/telegram.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geoip-twitter",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/twitter.srs",
        "download_detour": "🪜 proxy"
      },
      {
        "type": "remote",
        "tag": "geoip-facebook",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/facebook.srs",
        "download_detour": "🪜 proxy"
      }
    ]
  },
  "experimental": {
    "clash_api": {
      "external_controller": "0.0.0.0:9090",
      "external_ui_download_url": "https://github.com/MetaCubeX/metacubexd/archive/gh-pages.zip",
      "external_ui_download_detour": "",
      "external_ui": "ui",
      "secret": "",
      "default_mode": ""
    },
    "cache_file": {
      "enabled": true,
      "path": "",
      "cache_id": "",
      "store_fakeip": false
    }
  }
}

### 日志

```shell
[31mFATAL[0m[0000] start service: initialize DNS server[1]: dhcp: prepare interface: missing default interface
```

### 完整性要求

- [X] 我保证

### 负责性要求

- [X] 我保证

**Comment by CHIZI-0618** [comment]
> start service: initialize DNS server[1]: dhcp: prepare interface: missing default interface

联网后再启动 sing-box
