### ISSUE TITLE
Please tell me how to uninstall the network extension of the client under Mac

### ISSUE THREAD

**Issue by dovil** [SagerNet/sing-box#1244]
### Operating system

macOS

### System version

13.2.1 (22D68)

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.7.4

### Description

How to uninstall the network extension? After deleting the app, the network disconnection prompt still appears.

### Reproduction

Uninstalling the sing-box client on Mac still prompts the network link or disconnection

**Comment by sieveLau** [comment]
First, find out which folder contains the sing-box system extension: `ls -R /Library/SystemExtensions/`
You will need to reboot into the recovery mode to disable SIP first, and then reboot to Safe Mode, then run `sudo rm -rf ` the extension folder you found.
