### ISSUE TITLE
Android tun 接管流量不完全

### ISSUE THREAD

**Issue by PuerNya** [SagerNet/sing-box#1248]
### 操作系统

Android

### 系统版本

Android 14

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
1.7.5-0c8d6e6a
```

### 描述

使用命令行启动核心之后，在日志中仅仅观察到 dns 流量，其他流量在日志中完全看不到，通过 clash api 拿到的 connections 里也仅有 dns 流量

### 重现方式

`./sing-box.exe run -D ./ -c config.json`

### 完整性要求

- [X] 我保证

### 负责性要求

- [X] 我保证

**Comment by PuerNya** [comment]
在尝试将 sing-tun 回退到 v0.2.0-beta.1 后，tun 可以正常接管所有流量

**Comment by shallbytwo** [comment]
> 在尝试将 sing-tun 回退到 v0.2.0-beta.1 后，tun 可以正常接管所有流量

怎么判断的是否接管了全部流量？
