### ISSUE TITLE
Lisent too many ports as a tuic server

### ISSUE THREAD

**Issue by Vincent-bin** [SagerNet/sing-box#1260]
### Operating system

Linux

### System version

Ubuntu 23.10

### Installation type

Original sing-box Command Line

### Version

```shell
1.7.5
```

### Description

Found too many listening ports after running for a while as a tuic server
![image](https://github.com/SagerNet/sing-box/assets/16644208/6f1d40d7-4990-4d9b-861e-02e9d070a1f6)

### Reproduction

just normal config from example
{
    "log": {
        "disabled": false,
        "level": "info",
        "output": "/usr/local/sing-box/sing-box.log",
        "timestamp": true
    },
    "inbounds": [
        {
            "type": "tuic",
            "listen": "::",
            "listen_port": 3553,
            "users": [
                {
                    "uuid": "BE688B07-EE5E-4C34-AB8D-2B2BAAD5B418",
                    "password": "123456"
                }
            ],
            "congestion_control": "bbr",
            "tls": {
                "enabled": true,
                "alpn": [
                    "h3"
                ],
                "server_name": "xxx.com",
                "certificate_path": "/root/.acme.sh/xxx.com_ecc/fullchain.cer",
                "key_path": "/root/.acme.sh/xxx.com_ecc/xxx.com.key"
            }
        }
    ],
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        }
    ]
}

**Comment by EkkoG** [comment]
The behavior like the Tuic server's QUIC relay mode, each UDP datagram is transmitted over a separate unidirectional stream.
