### ISSUE TITLE
Crashing app after checking config file

### ISSUE THREAD

**Issue by M450ud** [SagerNet/sing-box#1277]
### Operating system

Windows

### System version

10

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box 1.8-rc2
```

### Description

Checked config file using command :
sing-box.exe check
then app crashed with the below Error. also android version crashing with same config.

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/sagernet/sing-box/transport/v2raywebsocket.NewClient({0xc000448a60?, 0xd?}, {0x19f88d0?, 0xc000919100}, {{{0x0, 0xffffb9e6f5d2}, 0xc000008060}, 0xcea, {0x0, 0x0}}, ...)
        /Users/sekai/Projects/sing-box/transport/v2raywebsocket/client.go:65 +0x72b
github.com/sagernet/sing-box/transport/v2ray.NewClientTransport({_, _}, {_, _}, {{{0x0, 0xffffb9e6f5d2}, 0xc000008060}, 0xcea, {0x0, 0x0}}, ...)
        /Users/sekai/Projects/sing-box/transport/v2ray/transport.go:56 +0xcb
github.com/sagernet/sing-box/outbound.NewTrojan({0x19ff8e8, 0xc00091f530}, {0x1a15350?, 0xc00017c2c0}, {_, _}, {_, _}, {{{0x0, 0x0}, ...}, ...})
        /Users/sekai/Projects/sing-box/outbound/trojan.go:60 +0x697
github.com/sagernet/sing-box/outbound.New({_, _}, {_, _}, {_, _}, {_, _}, {{0xc000448470, 0x6}, ...})
        /Users/sekai/Projects/sing-box/outbound/builder.go:39 +0x88c
github.com/sagernet/sing-box.New({{{0xc0002a8000, 0x4745c, 0x7fe00}, {0x0, 0x0}, 0xc00040ac00, 0xc000076840, 0x0, {0xc00042a000, 0x3, ...}, ...}, ...})
        /Users/sekai/Projects/sing-box/box.go:130 +0xe9b
main.check()
        /Users/sekai/Projects/sing-box/cmd/sing-box/cmd_check.go:34 +0x138
main.glob..func1(0xc000177900?, {0x24654e0?, 0x4?, 0x1801d73?})
        /Users/sekai/Projects/sing-box/cmd/sing-box/cmd_check.go:16 +0x17
github.com/spf13/cobra.(*Command).execute(0x2402c20, {0x24654e0, 0x0, 0x0})
        pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x2404040)
        pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /Users/sekai/Projects/sing-box/cmd/sing-box/main.go:38 +0x1e

### Reproduction

[config.json](https://github.com/SagerNet/sing-box/files/13751298/config.json)

**Comment by nekohasekai** [comment]
Try 1.8.0-rc.4
