### ISSUE TITLE
出现几千条ipv6连接

### ISSUE THREAD

**Issue by love796-QAQ** [SagerNet/sing-box#1300]
### 操作系统

Windows

### 系统版本

windows11 26016

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.8.0-rc.5
```

### 描述

用tun模式启动，看b站视频就会出现这么多的ipv6的连接，关闭tun的ipv6就正常了，但是我需要用到ipv6
![屏幕截图 2023-12-26 214145](https://github.com/SagerNet/sing-box/assets/80121684/8ef3a443-8c47-40a5-9928-fbb1060f61d7)

### 重现方式

用tun模式启动，观看b站视频`{
  "log": {
    "level": "warn",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "remote",
        "address": "tcp://8.8.8.8",
        "detour": "proxy"
      },
      {
        "tag": "local",
        "address": "223.5.5.5",
        "detour": "direct"
      },
      {
        "tag": "block",
        "address": "rcode://success"
      },
      {
        "tag": "local_local",
        "address": "223.5.5.5",
        "detour": "direct"
      }
    ],
    "rules": [
      {
        "server": "local",
        "disable_cache": true,
        "geosite": [
          "cn"
        ]
      },
      {
        "server": "block",
        "disable_cache": true,
        "geosite": [
          "category-ads-all"
        ]
      },
      {
        "outbound": "any",
        "server": "local_local"
      }
    ],
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "interface_name": "singbox_tun",
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "mtu": 9000,
      "auto_route": true,
      "strict_route": true,
      "stack": "system",
      "sniff": true
    }
  ],
  "outbounds": [
    {
      "type": "vless",
      "tag": "proxy",
      "server": "****************",
      "server_port": 40200,
      "uuid": "******************",
      "flow": "xtls-rprx-vision",
      "packet_encoding": "xudp",
      "tls": {
        "enabled": true,
        "server_name": "www.amazon.com",
        "insecure": false,
        "utls": {
          "enabled": true,
          "fingerprint": "firefox"
        },
        "reality": {
          "enabled": true,
          "public_key": "*******************",
          "short_id": "*********"
        }
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns_out"
    }
  ],
  "route": {
    "auto_detect_interface": true,
    "rules": [
      {
        "outbound": "dns_out",
        "inbound": [
          "dns_in"
        ]
      },
      {
        "outbound": "dns_out",
        "protocol": [
          "dns"
        ]
      },
      {
        "outbound": "block",
        "network": "udp",
        "port": [
          135,
          137,
          138,
          139,
          5353
        ]
      },
      {
        "outbound": "block",
        "ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ]
      },
      {
        "outbound": "block",
        "source_ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ]
      },
      {
        "outbound": "dns_out",
        "port": [
          53
        ],
        "process_name": [
          "wv2ray.exe",
          "v2ray.exe",
          "SagerNet.exe",
          "v2ray.exe",
          "v2ray.exe",
          "xray.exe",
          "wxray.exe",
          "clash-windows-amd64-v3.exe",
          "clash-windows-amd64.exe",
          "clash-windows-386.exe",
          "clash.exe",
          "Clash.Meta-windows-amd64-compatible.exe",
          "Clash.Meta-windows-amd64.exe",
          "Clash.Meta-windows-386.exe",
          "Clash.Meta.exe",
          "clash.exe",
          "hysteria-windows-amd64.exe",
          "hysteria-windows-386.exe",
          "hysteria.exe",
          "naiveproxy.exe",
          "naive.exe",
          "tuic-client.exe",
          "tuic.exe",
          "juicity-client.exe",
          "juicity.exe",
          "hysteria-windows-amd64.exe",
          "hysteria-windows-386.exe",
          "hysteria.exe"
        ]
      },
      {
        "outbound": "direct",
        "process_name": [
          "wv2ray.exe",
          "v2ray.exe",
          "SagerNet.exe",
          "v2ray.exe",
          "v2ray.exe",
          "xray.exe",
          "wxray.exe",
          "clash-windows-amd64-v3.exe",
          "clash-windows-amd64.exe",
          "clash-windows-386.exe",
          "clash.exe",
          "Clash.Meta-windows-amd64-compatible.exe",
          "Clash.Meta-windows-amd64.exe",
          "Clash.Meta-windows-386.exe",
          "Clash.Meta.exe",
          "clash.exe",
          "hysteria-windows-amd64.exe",
          "hysteria-windows-386.exe",
          "hysteria.exe",
          "naiveproxy.exe",
          "naive.exe",
          "tuic-client.exe",
          "tuic.exe",
          "sing-box-client.exe",
          "sing-box.exe",
          "juicity-client.exe",
          "juicity.exe",
          "hysteria-windows-amd64.exe",
          "hysteria-windows-386.exe",
          "hysteria.exe"
        ]
      },
      {
        "outbound": "direct",
        "domain": [
          "example-example.com",
          "example-example2.com"
        ],
        "domain_suffix": [
          ".example-example.com",
          ".example-example2.com"
        ]
      },
      {
        "outbound": "block",
        "geosite": [
          "category-ads-all"
        ]
      },
      {
        "outbound": "direct",
        "geosite": [
          "cn"
        ]
      },
      {
        "outbound": "direct",
        "geoip": [
          "private",
          "cn"
        ]
      }
    ]
  }
}`

### 完整性要求

- [ ] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [ ] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [ ] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by reeceyng** [comment]
我有一次从休眠唤醒后遇到过，好像是sing-box流量回环了

**Comment by CCJ623** [comment]
我也遇到了这个问题，出现的挺频繁的，至今找不出原因

**Comment by Sduby22** [comment]
> 我有一次从休眠唤醒后遇到过，好像是sing-box流量回环了

is it because of a sing-box bug or mis-configuration?
