### ISSUE TITLE
无法使用Port规则

### ISSUE THREAD

**Issue by phantastar** [SagerNet/sing-box#1313]
### Operating system

Android

### System version

Android 13

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.8.0-rc.7

### Description

无法设置port规则，插入port规则就会报错

### Reproduction

规则中添加
```
{"port":"8080","outbound":"Proxy"}
{"port":"443","outbound":"Proxy"}
```

### Logs

```shell
Error decode config: route.rules[5].port: json: cannot unmarshal string into Go value of type[]uint16 | json: cannot unmarshal string into Go value of type uint16
```

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by Mahdi-zarei** [comment]
Port is a number and should not be quoted, you need to use something like:
{"port":8080,"outbound":"Proxy"}

**Comment by phantastar** [comment]
> Port is a number and should not be quoted, you need to use something like: {"port":8080,"outbound":"Proxy"}

thank you a lot, let me try
