### ISSUE TITLE
Libbox Documentation

### ISSUE THREAD

**Issue by Ali-Khazaee** [SagerNet/sing-box#1322]
### Operating system

Android

### System version

Android

### Installation type

Third-party graphical clients that advertise themselves as using sing-box (Android)

### Description

I am trying to use Sing-box in my app, but there is no documentation about how to use Libbox ( sing-box as .aar )

is there any details about how to use sing-box as library ?

### Reproduction

-

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
It's easy to use if you have some basic experience, otherwise we won't teach.

**Comment by Ali-Khazaee** [comment]
I'm not talking about teaching. I were looking for documentation for the implementing it in correct way.

It is already integrated to my app, I got information from sing-box-android repo. but still there are a few unknown things to me.

For example:

```Java
@Override
public boolean useProcFS()
{
    return Build.VERSION.SDK_INT < Build.VERSION_CODES.Q;
}
```

There is no information about this function, even why would it be true or false ?
