### ISSUE TITLE
SFM 能否提供对低版本macos系统的支持，

### ISSUE THREAD

**Issue by JogFeelingVI** [SagerNet/sing-box#1323]
### 操作系统

macOS

### 系统版本

macos 10.15

### 安装类型

sing-box for macOS 图形客户端程序

### 描述

SFM现在只支持macos 13+ 希望添加对低版本macos的支持。

### 重现方式

老版本的macos无法运行图形界面的SFM，但命令行的可以使用，但是似乎有些问题，

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by KevinMX** [comment]
https://github.com/SagerNet/sing-box/issues/1031
https://github.com/SagerNet/sing-box/issues/1028

**Comment by Mon-ius** [comment]
actually, the new macOS not support yet, e.g. macOS 14.5 (23F79)

**Comment by fred402** [comment]
macos 10.15.7 catalina用户，希望能支持
