### ISSUE TITLE
sing-tun undefined: lwip.LWIPStack  undefined: lwip.NewLWIPStack  undefined: lwip.RegisterOutputFn

### ISSUE THREAD

**Issue by slkbnt** [SagerNet/sing-box#1338]
### Operating system

Linux

### System version

Debian 12

### Installation type

Original sing-box Command Line

### Version

```shell
Latest version
```

### Description

cross compile error with golang version 1.21.5

### Reproduction

git clone https://github.com/SagerNet/sing-box.git

cd sing-box

go get -v -d

go install -v github.com/sagernet/sing-box/cmd/sing-box@latest 

CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v -tags with_quic,with_grpc,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_v2ray_api,with_gvisor,with_lwip ./cmd/sing-box

### Logs

```shell
$ CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v -tags with_quic,with_grpc,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_v2ray_api,with_gvisor,with_lwip ./cmd/sing-box
github.com/sagernet/sing-tun
# github.com/sagernet/sing-tun
../../.gobrew/current/go/packages/pkg/mod/github.com/sagernet/sing-tun@v0.1.12-0.20230920060816-9c933ea55308/stack_lwip.go:25:18: undefined: lwip.LWIPStack
../../.gobrew/current/go/packages/pkg/mod/github.com/sagernet/sing-tun@v0.1.12-0.20230920060816-9c933ea55308/stack_lwip.go:37:17: undefined: lwip.NewLWIPStack
../../.gobrew/current/go/packages/pkg/mod/github.com/sagernet/sing-tun@v0.1.12-0.20230920060816-9c933ea55308/stack_lwip.go:45:7: undefined: lwip.RegisterOutputFn
../../.gobrew/current/go/packages/pkg/mod/github.com/sagernet/sing-tun@v0.1.12-0.20230920060816-9c933ea55308/stack_lwip.go:91:7: undefined: lwip.RegisterOutputFn
```

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by reF1nd** [comment]
LWIP stack has been deprecated and removed after 1.8.0, use other stack instead.
