### ISSUE TITLE
sing-box在iOS手机版中切换节点不生效

### ISSUE THREAD

**Issue by ouojk** [SagerNet/sing-box#1349]
### 操作系统

iOS

### 系统版本

iOS17.1.2

### 安装类型

sing-box for iOS 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.8

### 版本

```shell
1.8
```

### 描述

我在切换节点时候发现节点IP没有变化，只有关闭重新打开才能切换成功

### 重现方式

无

### 日志

```shell
无
```

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by MiniKoro** [comment]
可以切换 没有问题 是你的问题
