### ISSUE TITLE
从clash切sing-box已经有月余，使用中发现几个问题反馈一下，如果能解决就太好了！！感恩！

### ISSUE THREAD

**Issue by KGorham123** [SagerNet/sing-box#1359]
### Operating system

iOS

### System version

17.1.2

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.8

### Description

2个问题：
1、所有的**ADSL原生宽带服务器 连接上后Downlink都为0B，都无法使用**，看是不是mtu的原因，，这些服务器设备mtu应该都是1450的，服务器系统的mtu是1500，使用v2ray和clash、小火箭可以正常连接使用。
2、一直开启着代理，**一段时间不用后，此时访问外部网络将不能连接**（有时可以，大部份情况下不行），这时重新关闭代理，再开启，又可以正常使用了，v2ray与clash、小火箭不存在此问题。

### Reproduction

问题1中，在面板Dashboard项中，Traffic Total显示Uplink有数据，而Downlink是0B，延迟显示正常！

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by jiania** [comment]
确实 我也经常碰到这情况。
