### ISSUE TITLE
URLTest Fallback to first outbound

### ISSUE THREAD

**Issue by MataAzi** [SagerNet/sing-box#1372]
I'm using 1.8.1 version of ios singbox.

When network loss the URLTest will fallback to first outbound in the list but I think it should stick with the latest one selected before network loss.

Because of that the user will not auto reconnect if the first one wont work. Please do a rework on this and make the url test stick to selected one until interval.

Thanks.

**Comment by M03ED** [comment]
I have same problem on a Poco x3 pro device

**Comment by MataAzi** [comment]
@nekohasekai  Thanks for great work! you are a life saver :)
 
https://github.com/SagerNet/sing-box/commit/b85725c009334979e233d1f77cabcb3ae4b21ce6

Closing As Resolved
