### ISSUE TITLE
[Features] Hysteria多用户支持

### ISSUE THREAD

**Issue by Mars160** [SagerNet/sing-box#138]
希望添加对Hysteria的多用户支持
即将auth和auth_str字段改为数组，可以传入多个用户信息

**Comment by nekohasekai** [comment]
Try 617aba84e437df0a42aa1c5502361b2be8c5bde5

**Comment by cxlxkin** [comment]
> Try [617aba8](https://github.com/SagerNet/sing-box/commit/617aba84e437df0a42aa1c5502361b2be8c5bde5)

1.0.7 不行，提示“FATAL[0000] decode config: inbound options: json: unknown field "users"”
