### ISSUE TITLE
Clear code of conduct and contribution guide

### ISSUE THREAD

**Issue by nimagp** [SagerNet/sing-box#1381]
Practically speaking, sing-box doesn't accept any contribution right now. PRs are responded with "This doesn't comply with our code style" and "This feature doesn't work in China".

The point of sing-box is to help all people fight censorship, or most have assumed so. China isn't the only country with internet censorship, it goes without saying that there are countless different systems with the very same purpose in many regions. 

As for the quality of code, you haven't specified a contribution guide or a general policy for PRs. How is another developer supposed to comply with your unwritten rules?

I, and many more, appreciate it greatly if your consider these points. Otherwise, if you are unwilling to make contributions streamline, state it.

**Comment by Ali-Khazaee** [comment]
If you really have will to do it. Fork/Clone the project as it is open source project, then do your improvement

**Comment by nimagp** [comment]
@Ali-Khazaee Then repackage all the toolchains and clients built around singbox, maintain and ship them?

**Comment by deuteros-gex** [comment]
You seem to regard sing-box as some kind of fundamental IT infrastructure which is so irreplaceable that it must be shipped with detailed documentation in case  someone wants to participate in its development.

And you also seem to suppose this project is written by an ambitious author who wants to attract so many people that any suggestions or demands would be considered seriously and responded.

But that is not the case.

**Comment by nimagp** [comment]
> You seem to regard sing-box as some kind of fundamental IT infrastructure which is so irreplaceable that it must be shipped with detailed documentation in case  someone wants to participate in its development.

It certainly isn't "critical IT infrastructure", but both as a client and a server, it's convenient and important.

I can definitely replace it as a server with xray-core (at the price of some speed), but as a client, it really is irreplaceable. Both Nekoray and Nekobox use singbox, v2rayN isn't accessible on Linux and v2rayNG is strangely unstable. 

I'm not the only one with these conditions, and so, yes. It is critical in a way, at least in my country. 

> And you also seem to suppose this project is written by an ambitious author who wants to attract so many people that any suggestions or demands would be considered seriously and responded.
> 
> But that is not the case.

That *is* the case. I think taking a look at the repository stars or the projects that use singbox under the hood should be enough evidence of my point.

Also, PRs are work already done, not "suggestions and demands". 

I'm not implying @nekohasekai or the team behind this are obligated to accept and implement anything, that would be catastrophic. 

The PRs that I'm referring to have legitimate and clear use cases. But regardless, if the they don't want contributions, it should be plainly visible in the README. This would at least let others know to not waste their time and focus on maintaining a fork of sing-box or write a new project from scratch.

**Comment by deuteros-gex** [comment]
Stop making a fuss about those closed PRs.
A project of this size doesn't need a COMITTEE and effectively the owner **DICTATES** where the project is moving anyway. 
When you disagree and fail to be persuasive, make your fork if you can. **And why should the Common Practice for Open Source Community be stated Deliberately?**

**Comment by nimagp** [comment]
> Stop making a fuss about those closed PRs.
> A project of this size doesn't need a COMITTEE and effectively the owner **DICTATES** where the project is moving anyway. 
> When you disagree and fail to be persuasive, make your fork if you can. **And why should the Common Practice for Open Source Community be stated Deliberately?**

I'm not making a fuss, I'm asking for improvement in documentations, and unless you are the owner of this project, I don't see the point in arguing further.

**Comment by markpash** [comment]
Hi, this is not a new problem and indeed people are free to make a fork. So I have decided to try and maintain one in my free time. The purpose of it would be to only maintain patchsets from the Iranian community and continue to rebase on new upstream releases from this repo. If the Iranian community does find bugs or issues in the upstream code, they should of course be reported here. After speaking to a few of the prominent Iranian projects and people who use sing-box, they have agreed to start using the fork, provided that it contains their patchsets and is well maintained. This requires time and effort, so help from the Iranian community is vital.

More details here: https://github.com/markpash/sing-box-ir/wiki

By doing this, I hope we can reduce the problems and arguments. And just to make sure it's clear for everyone, the first priority of this fork is to make sure that bug fixes and vital changes **always** go to the original project, so that the quality always improves.
