### ISSUE TITLE
URL Test improvement

### ISSUE THREAD

**Issue by M450ud** [SagerNet/sing-box#1385]
### Operating system

Android

### System version

11

### Installation type

Original sing-box Command Line

### If you are using a graphical client, please provide the version of the client.

1.8.2

### Description

Sometimes when we have a config with some outbounds it may currently selected node not transmit any data but has the lowest ping time in URLTets and will cause a connection block out.
recommended that the app use the next node after a period of time with no data transmission. 

### Reproduction

In my config, the first node had the best ping time but not working at all. when I found the problem had to remove the server from the config file manually.

[config.json](https://github.com/SagerNet/sing-box/files/13998430/config.json)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by read8873** [comment]
sounds like a failover rule
