### ISSUE TITLE
服务端可以同时存在多个入站协议，那有没有办法使用多个出站协议？并且可以自由指定不同的入站协议走不同的出口？

### ISSUE THREAD

**Issue by cooler37** [SagerNet/sing-box#1386]
比方说让config.json里可以写很多对 inbounds 和 outbounds ?

**Comment by CHIZI-0618** [comment]
多看文档

```json
{
  "route": {
    "rules": [
      {
        "inbound": [
          "mixed-in"
        ],
        "outbound": "direct"
      }
    ]
  }
}
```

**Comment by cooler37** [comment]
> 多看文档
> 
> ```json
> {
>   "route": {
>     "rules": [
>       {
>         "inbound": [
>           "mixed-in"
>         ],
>         "outbound": "direct"
>       }
>     ]
>   }
> }
> ```

比方说在服务端同时配置了 hysteria,  trojan, shadowsocks,现在我想让shadowsocks 的出口是另一台服务器上配置的shandowsocks， 让剩下两个走" direct“出口，这样可以做到吗？

**Comment by cooler37** [comment]
> 多看文档
> 
> ```json
> {
>   "route": {
>     "rules": [
>       {
>         "inbound": [
>           "mixed-in"
>         ],
>         "outbound": "direct"
>       }
>     ]
>   }
> }
> ```
我是说服务端，这是客户端配置？

**Comment by MiniKoro** [comment]
> > 多看文档
> > ```json
> > {
> >   "route": {
> >     "rules": [
> >       {
> >         "inbound": [
> >           "mixed-in"
> >         ],
> >         "outbound": "direct"
> >       }
> >     ]
> >   }
> > }
> > ```
> 
> 我是说服务端，这是客户端配置？

多看文档

**Comment by MiniKoro** [comment]
配置入站ss

**Comment by MiniKoro** [comment]
配置入站ss
配置出站ss
配置路由规则 入站ss指定出站ss访问
多看文档
