### ISSUE TITLE
导入配置时报错 MacOS 和IOS

### ISSUE THREAD

**Issue by Richard5256** [SagerNet/sing-box#1388]
### Operating system

iOS

### System version

IOS 17

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.8.2

### Description

在MacOS和IOS上导入配置的时候报错，提示如附件中截图所示，这是因为配置文件不支持吗？
![error](https://github.com/SagerNet/sing-box/assets/63089119/7cd7bfb4-50b0-4e78-9062-c192ecc5d21c)

### Reproduction

在导入配置的时候点击create

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by Richard5256** [comment]
@codingiran  在网上找到一些网页格式的转换工具，请问有可以推荐的吗？

**Comment by Richard5256** [comment]
问题以解决。

**Comment by abc32173705-debug** [comment]
可以添加配置文件但是无法开始使用   提示：(packet-tunnel)error: start service: opengeoip database: error opening database:invalid MaxMind DB file
