### ISSUE TITLE
`packet-tunnel` does not have read permission to iCloud profile

### ISSUE THREAD

**Issue by ladit** [SagerNet/sing-box#1390]
### Operating system

macOS

### System version

14.2

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.8.2

### Description

see reproduction below.

### Reproduction

- create a `test` profile in SFM which type is `iCloud` and path is `test.json`
- start with the profile
- SFM complains `(packet-tunnel) error: read config file test.json: The file “test.json” couldn’t be opened because you don’t have permission to view it.`

### Logs

```shell
（packet-tunnel） log server started

（packet-tunnel）error: read config file test.json: The file "test.json" couldn't be opened because you don't have permission to view it.

（packet-tunnel）stopping, reason: NEProviderStopReason （rawValue: 1）
```

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
Can’t reproduce

**Comment by ladit** [comment]
I replaced brew version with App Store version. The iCloud profile works. It may be a problem with brew version.

**Comment by stllfe** [comment]
Confirming the same for brew version. The App Store one is okay.
To whom it may concern, I've found this stackoverflow thread regarding the issue:

https://stackoverflow.com/questions/49054485/file-couldn-t-be-opened-because-you-don-t-have-permission-to-view-it-error

**Comment by lanhailin** [comment]
Encountered the same issue.
macOS 14.4 SFM-1.9.0-beta.17
The TestFlight version works fine, but when switching to the Github SFM version, this error occurs.

**Comment by mxin99** [comment]
yes, the version of brew will occurs,the version of appstore won't.
