### ISSUE TITLE
Auto update doesn't work

### ISSUE THREAD

**Issue by shayandavoodii** [SagerNet/sing-box#1397]
Profiles do not get updated automatically, as you can see in the following snapshots:
![IMG_20240123_113332_186.jpg](https://github.com/SagerNet/sing-box/assets/52105833/e0b59f96-1b17-4e95-925c-6628456cc9bd)

![IMG_20240123_113333_621.jpg](https://github.com/SagerNet/sing-box/assets/52105833/97ffb846-28de-4506-82df-da996d5e3f5c)

I took these snapshots a couple of minutes ago on `v1.8.4`. This problem has existed since a couple of releases ago.

**Comment by shayandavoodii** [comment]
Actually, SFA triggers updating the profiles after being connected as long as the auto-update interval (60 minutes, in my case).

For your attention, @zaskochill @SpilexX

**Comment by shayandavoodii** [comment]
Isn't it better to change the behaviour? I mean, updating the profiles if it's been more than an auto-update interval since the last update.

**Comment by Karabasina** [comment]
I faced the same problem. Subscriptions do not renew automatically; changing the renewal interval does not help. As far as I know, the problem is widespread.
