### ISSUE TITLE
[求助帖] openwrt 到底怎么使用docker sing-box 作为客户端? 求一份教程... 文档资料实在太稀缺了...

### ISSUE THREAD

**Issue by gowy222** [SagerNet/sing-box#1404]
### Operating system

openwrt

### System version

暂时不涉及

### Installation type

Others

### Version

```shell
docker拉取默认最新版
```

### Description
网上相关资料零零散散，拼凑在一起没法完全工作..
----
各种尝试，每次都是要么国内访问不出去，要么外网访问不出去...
尤其是这个tun，在openwrt里面 docker 特权模式，sing-box 不会自动建立tun0和配置防火墙？一定要使用tun？电脑免配置。openwrt全局代理模式怎么弄?

多网口软路由 本身就有多个lan口和一个br-lan，需要特别绑定？
其次就是 怎么指定 docker sing-box 用nftables 而不是iptable，毕竟和系统混合起来容易底层规则侧漏...
最后: 分流, fake dns 防止dns泄露的配置可有完整示范？ (分流dns+fakeip同时使用)

---
openwrt + docker - sing - box  至今没有实现 dns + fake ip 分流防泄露... 核心是防泄露
目前尝试过 https://github.com/immortalwrt/homeproxy 这个项目，
但是https://browserleaks.com/dns 测试下来 dns 100%泄露.

### Reproduction

求助帖..忽略此项

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by onlyfirer** [comment]
怎么会呢，防泄漏还是没有问题，主要是分流
