### ISSUE TITLE
ios 锁屏一段时间后wireguard出站报错无法使用

### ISSUE THREAD

**Issue by eyebrowkang** [SagerNet/sing-box#1406]
### Operating system

iOS

### System version

17.3

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.8.4

### Description

iOS使用wireguard作为outbound，锁屏一段时间后会出现下图中的错误信息，没有service log，开关一次sing-box会恢复，基本每次锁屏都会出现。重启手机及sing-box无效

部分配置：
```json
{
  "route": {
    "auto_detect_interface": true
 },
 "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "inet4_address": "172.15.0.1/30",
      "inet6_address": "fdfe:dcba:6789::1/126",
      "auto_route": true,
      "strict_route": true,
      "sniff": true
    }
  ],
  "outbounds": [
    {
      "type": "wireguard",
      "tag": "wireguard-out",
      "local_address": [
        "10.0.0.2/32"
      ],
      "private_key": "xxxxx=",
      "peers": [
        {
          "server": "xxxxx",
          "server_port": 1111,
          "public_key": "xxxxxx=",
          "allowed_ips": [
            "10.0.0.0/24"
          ]
        }
      ],
      "mtu": 1420
    }
  ]
}
```

![sing-box-error-log](https://github.com/SagerNet/sing-box/assets/48169104/3b2b6191-6c13-47ca-b347-f4845660b369)

### Reproduction

正常启动sing-box，锁屏，等待约五分钟，打开手机

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
#1432

**Comment by HiHenryLeo** [comment]
有解决方法了吗？请问。我正遇到这个问题。iOS 17.4.1
