### ISSUE TITLE
sing_box_reality_vision部署出现的相关问题

### ISSUE THREAD

**Issue by 123Diego** [SagerNet/sing-box#1409]
### 操作系统

Android

### 系统版本

Android13

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
1.8.4
```

### 描述

通过sing-box部署的reality_vision，在v2rayng不可用，在sing-box Android客户端下可用，通过xray部署的reality_vision则没有此问题

### 重现方式

如描述中提到的

### 日志

```shell
inbound/vless[VLESSReality]: process connection from 127.0.0.1:47742: REALITY: processed invalid connection

inbound/vless[VLESSReality]: process connection from 127.0.0.1:46572: flow mismatch: expected xtls-rprx-vision, but got none
```

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by KevinMX** [comment]
检查你的服务端配置文件&客户端配置。
