### ISSUE TITLE
编译后version unknown

### ISSUE THREAD

**Issue by meokey** [SagerNet/sing-box#1412]
### 操作系统

Linux

### 系统版本

Ubuntu 22.04 LTS 5.15.0-92-generic

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
root@RAC:~/github/sing-box# ./sing-box version
sing-box version unknown

Environment: go1.21.6 linux/amd64
Tags: with_clash_api,with_quic,with_grpc,with_wireguard,with_reality_server,with_v2ray_api,with_utls,with_ech,with_gvisor
Revision: 38f76ddd2ec18dc8f4f4b85f579c00fc8d6f7e21
CGO: enabled
```

### 描述

如./sing-box version命令所描述的，第一行不能显示version

但Makefile里的VERSION的命令是有效的：
root@RAC:~/github/sing-box# GOHOSTOS=$(go env GOHOSTOS)
root@RAC:~/github/sing-box# GOHOSTARCH=$(go env GOHOSTARCH)
root@RAC:~/github/sing-box# CGO_ENABLED=0 GOOS=$GOHOSTOS GOARCH=$GOHOSTARCH go run ./cmd/internal/read_tag
1.8.4-38f76ddd
root@RAC:~/github/sing-box# CGO_ENABLED=1 GOOS=$GOHOSTOS GOARCH=$GOHOSTARCH go run ./cmd/internal/read_tag
1.8.4-38f76ddd

go的编译命令如下：
root@RAC:~/github/sing-box# go build -a -v -tags "with_clash_api with_quic with_grpc with_wireguard with_reality_server with_v2ray_api with_utls with_ech with_gvisor" ./cmd/sing-box

### 重现方式

./sing-box version

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by CodingMoeButa** [comment]
问题解决了吗？如何解决的？我使用`go build`命令编译有同样的问题。
