### ISSUE TITLE
当 rule_set format 为 source 时无法正确解析

### ISSUE THREAD

**Issue by TDYQ-Liu** [SagerNet/sing-box#1419]
### Operating system

Linux

### System version

fedora39

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.8.4

Environment: go1.21.6 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: c8318058bb4a15e9d6751a71e78bdd3b68c57b32
CGO: disabled
```

### Description

当 rule_set format 为 source 时无法正确解析, 显示 unknown field

### Reproduction

rule_set 配置
```json
            {
                "tag": "mybypass",
                "type": "local",
                "path": "/etc/sing-box/mybypass.json",
                "format": "source"
            },
```
当 mybypass.json 内容为 
```json
{
  "version": 1,
  "rules": []
}
```
的时候提示 `FATAL[0000] decode config at /etc/sing-box/mybypass.json: version: json: unknown field "version"`

当 mybypass.json 内容为 
```json
{
  "rules": []
}
```
的时候提示 `FATAL[0000] decode config at /etc/sing-box/mybypass.json: rules: json: unknown field "rules"`

当 mybypass.json 内容为 
```json
{
}
```
的时候提示 `FATAL[0000] create service: parse route options: parse rule-set[1]: missing rule set version`

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by poetlife** [comment]
你的rule_set.json是不是放在了`/etc/sing-box`下，看上去，如果按照默认的安装方式，systemd管理的sing-box是默认解析/etc/sing-box目录下 所有的json文件的，因此程序是将你的rule_set解析成了通用的配置。

**Comment by TDYQ-Liu** [comment]
> 你的rule_set.json是不是放在了`/etc/sing-box`下，看上去，如果按照默认的安装方式，systemd管理的sing-box是默认解析/etc/sing-box目录下 所有的json文件的，因此程序是将你的rule_set解析成了通用的配置。

是的。更改rule set 路径后可以正常解析
