### ISSUE TITLE
shadowTLS + shadowsocks only worked with sagernet or sing-box

### ISSUE THREAD

**Issue by everyx** [SagerNet/sing-box#143]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

I use shadowTLS + shadowsocks on server side(in us), and add another server(in china) use shadowTLS as default outbound, and `direct` as default inbound, and connect to the server in China use shadowsocks protocol, but I can only connect via sagernet or sing-box, another shadowsocks client (v2rayNG, v2rayN, shadowrocket) is not working.

### Version of sing-box

<details>

```console
$ sing-box version
Environment: go1.19.2 linux/amd64
Tags: with_clash_api,with_quic,with_wireguard,with_acme
Revision: 39c141651a145ebf4406b07cafe887978022471e
CGO: disabled
```

</details>

### Server and client configuration file

<details>
<summary>us.server.json</summary>

```json
{
  "log": {
    "level": "warn",
    "timestamp": false
  },
  "inbounds": [
    {
      "type": "shadowtls",
      "listen": "::",
      "listen_port": 443,
      "handshake": {
        "server": "cloud.tencent.com",
        "server_port": 443
      },
      "detour": "shadowsocks-in"
    },

    {
      "tag": "shadowsocks-in",
      "type": "shadowsocks",
      "listen": "127.0.0.1",
      "method": "2022-blake3-aes-128-gcm",
      "password": "asj5u3hjoMPVrLrRIPxD6A==",
      "users": [
        { "name": "user@example.com", "password": "H0egJ0m2TzV6++rsQ73NVA==" },
      ]
    }
  ]
}

```

</details>

<details>
<summary>cn.server.json</summary>

```json
{
  "log": {
    "level": "warn",
    "timestamp": false
  },
  "inbounds": [
    {
      "type": "direct",
      "listen": "::",
      "listen_port": 3443
    }
  ],
  "outbounds": [
    {
      "tag": "cloudcone01",
      "type": "shadowtls",
      "server": "xxx.xxx.xxx.xxx",
      "server_port": 443,
      "tls": {
        "enabled": true,
        "server_name": "cloud.tencent.com"
      }
    },
  ]
}

```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by nekohasekai** [comment]
sing-box has been tested to show no compatibility issues with the official program, so send your issue to shadowrocket.
