### ISSUE TITLE
geoip.db 数据文件写入错误（geoip.db i/o timeout）

### ISSUE THREAD

**Issue by xvv6u577** [SagerNet/sing-box#1431]
### Operating system

macOS

### System version

14.2.1 (23C71)

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.8.4

### Description

Service Error
(packet-tunnel) error: start service: Get "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db": dial tcp 20.78.11.72:19302: i/o timeout

### Reproduction

{
    "log": {
        "disabled": false,
        "level": "info",
        "timestamp": true
    },
    "dns": {
        "rules": [
            {
                "outbound": [
                    "any"
                ],
                "server": "local"
            },
            {
                "disable_cache": true,
                "geosite": "category-ads-all",
                "server": "block"
            },
            {
                "clash_mode": "global",
                "server": "remote"
            },
            {
                "clash_mode": "direct",
                "server": "local"
            },
            {
                "geosite": "cn",
                "server": "local"
            }
        ],
        "servers": [
            {
                "address": "https://1.1.1.1/dns-query",
                "detour": "select",
                "tag": "remote"
            },
            {
                "address": "https://223.5.5.5/dns-query",
                "detour": "direct",
                "tag": "local"
            },
            {
                "address": "rcode://success",
                "tag": "block"
            }
        ],
        "strategy": "prefer_ipv4"
    },
    "inbounds": [
        {
            "auto_route": true,
            "domain_strategy": "prefer_ipv4",
            "endpoint_independent_nat": true,
            "inet4_address": "172.19.0.1/30",
            "inet6_address": "2001:0470:f9da:fdfa::1/64",
            "mtu": 9000,
            "sniff": true,
            "sniff_override_destination": true,
            "stack": "mixed",
            "strict_route": true,
            "type": "tun"
        },
        {
            "domain_strategy": "prefer_ipv4",
            "listen": "127.0.0.1",
            "listen_port": 2333,
            "sniff": true,
            "sniff_override_destination": true,
            "tag": "socks-in",
            "type": "socks",
            "users": []
        },
        {
            "domain_strategy": "prefer_ipv4",
            "listen": "127.0.0.1",
            "listen_port": 2334,
            "sniff": true,
            "sniff_override_destination": true,
            "tag": "mixed-in",
            "type": "mixed",
            "users": []
        }
    ],
    "experimental": {},
    "outbounds": [
        {
            "default": "urltest",
            "outbounds": [
                "urltest",
            ],
            "tag": "select",
            "type": "selector"
        },
        {
            "outbounds": [
            ],
            "tag": "urltest",
            "type": "urltest"
        },
        {
            "type":"vless"
            ...
        },
        {
            "type":"hysteria2"
            ...
        },
        {
            "tag": "direct",
            "type": "direct"
        },
        {
            "tag": "block",
            "type": "block"
        },
        {
            "tag": "dns-out",
            "type": "dns"
        }
    ],
    "route": {
        "auto_detect_interface": true,
        "geoip": {
            "download_detour": "select"
        },
        "geosite": {
            "download_detour": "select"
        },
        "rules": [
            {
                "geosite": "category-ads-all",
                "outbound": "block"
            },
            {
                "outbound": "dns-out",
                "protocol": "dns"
            },
            {
                "clash_mode": "direct",
                "outbound": "direct"
            },
            {
                "clash_mode": "global",
                "outbound": "select"
            },
            {
                "geoip": [
                    "cn",
                    "private"
                ],
                "outbound": "direct"
            },
            {
                "geosite": "geolocation-!cn",
                "outbound": "select"
            },
            {
                "geosite": "cn",
                "outbound": "direct"
            }
        ]
    }
}

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by cguo2013** [comment]
I got a similar error on sing box 1.8.7 MacOS, but with "connection reset by peer", see below:

(packet-tunnel) error: start service: Get "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db": read tcp 192.168.1.4:51029->172.67.163.116:2083: read: connection reset by peer

any comments on how to fix this problem?

**Comment by lzou** [comment]
I also encountered this problem on iOS 16. Deleting the configuration and adding it again did not work.

**Comment by tst-pandit-pan** [comment]
Running on latest 1.9.1 version, this problem still exists...
Meanwhile on my Mac it works fine without error, what’s the problem over there?
![Screenshot 2024-06-09 at 10 31 31 AM](https://github.com/SagerNet/sing-box/assets/112232636/e85ebcea-0364-44ed-ad26-913a3e06d7d4)
