### ISSUE TITLE
interrupt_exist_connections: true not interrupt existing connections

### ISSUE THREAD

**Issue by dimzon** [SagerNet/sing-box#1452]
### Operating system

Android

### System version

A14

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

SFA 1.8.5

### Description

I'm using [https://whoer.net/](https://whoer.net/) to check my IP.
Each time im switching active proxy in selector I'm trying to update a page in browser to see another IP/county. No luck - it reloads same page with same IP.
I need to competly stop/start in SB or close and reopen my browser process to obtain a new address. 

### Reproduction

[test1.json](https://github.com/SagerNet/sing-box/files/14217974/test1.json)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by BK8000L** [comment]
on sing-box android gui 1.8.11 it's still broken: i check my ip address here http://1.1.1.2/cdn-cgi/trace (1.1.1.2 - 1.1.1.254) and on 1.1.1.2/3 it gets stuck on default selector, it works properly on 1.1.1.4 - 254

**Comment by BK8000L** [comment]
still an issue
