### ISSUE TITLE
clash-api 无法访问

### ISSUE THREAD

**Issue by caixiaomao** [SagerNet/sing-box#1471]
### Operating system

Windows

### System version

windows 11

### Installation type

Original sing-box Command Line

### Version

```shell
1.9.0-alpha.8
```

### Description

clash api 配置如下：
```json
{
"experimental": {
    "clash_api": {
      "external_controller": "127.0.0.1:9090",
      "external_ui": "",
      "secret": "",
      "external_ui_download_url": "https://mirror.ghproxy.com/https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip",
      "external_ui_download_detour": "direct",
      "default_mode": "rule"
    }
  }
}
```

访问 web 界面 http://127.0.0.1:9090/ui/ 并填写配置如下：
![image](https://github.com/SagerNet/sing-box/assets/5171685/cad408a3-fd86-4fe2-b075-60743dbc515d)

报错：
401 Unauthorized

### Reproduction

clash api 配置如下：
```json
{
"experimental": {
    "clash_api": {
      "external_controller": "127.0.0.1:9090",
      "external_ui": "",
      "secret": "",
      "external_ui_download_url": "https://mirror.ghproxy.com/https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip",
      "external_ui_download_detour": "direct",
      "default_mode": "rule"
    }
  }
}
```

访问 web 界面 http://127.0.0.1:9090/ui/ 并填写配置如下：
![image](https://github.com/SagerNet/sing-box/assets/5171685/cad408a3-fd86-4fe2-b075-60743dbc515d)

报错：
401 Unauthorized

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by KevinMX** [comment]
![image](https://github.com/SagerNet/sing-box/assets/17025286/3208d3fc-b401-40f6-85da-aa447993c1a8)
未能复现。

**Comment by caixiaomao** [comment]
好的，我再仔细检查一下，非常感谢
