### ISSUE TITLE
下载windows 1.9.0alfa 9 显示检测到病毒

### ISSUE THREAD

**Issue by wyw1018** [SagerNet/sing-box#1476]
### 操作系统

Windows

### 系统版本

win10 22H2 19045.3803专业版

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box-1.9.0-alpha.9-windows-amd64
```

### 描述

下载完成后显示：sing-box-1.9.0-alpha.9-windows-amd64 .zip 失败 - 检测到病毒
未安装其它杀毒软件，只有windows defender。
其中  sing-box-1.9.0-alpha.9-windows-amd64 .zip 有一段横线穿越整个文字
1.8.5版本在本机使用没有问题

### 重现方式

再次下载
sing-box-1.9.0-alpha.9-windows-amd64 (1).zip失败 - 检测到病毒

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by Zxilly** [comment]
https://www.virustotal.com/gui/file/18d6a865167a8e292705f3d44540638366b46a1d5f13c07f2dc79d2a5d7b0084

应该是Windows Defender误报了
