### ISSUE TITLE
Does shadowsocks-2022 support dynamically add or delete users?

### ISSUE THREAD

**Issue by moranno** [SagerNet/sing-box#148]
Hi,

I want to dynamically add or delete users for an inbound using shadowsocks-2022 multi-users feature. Does sing-box shadowsocks-2022 support dynamically add or delete users?

Thanks for the great work!

**Comment by nekohasekai** [comment]
Not currently. Designing and maintaining a stable management API is a lot of work, and not particularly useful to myself.
