### ISSUE TITLE
Auto update doesn't work on iOS

### ISSUE THREAD

**Issue by Karabasina** [SagerNet/sing-box#1483]
### Operating system

iOS

### System version

17.2.1

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.8.5

### Description

Subscriptions do not update automatically; changing the renewal interval does not help. As far as I know, the problem is widespread.

### Reproduction

1. Add a subscription 
2. Set Auto Update Interval = 10 
3. I’ve been waiting for 2 days

I am attaching a screenshot from 02/19/2024
![IMG_4861](https://github.com/SagerNet/sing-box/assets/101506720/c84bed5d-0e21-4ef8-8f66-5bbceb4ec28a)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by zaskochill** [comment]
I have a similar problem on iOS and Mac OS.
Both of them have the latest versions of the program.
The update happens about once a day at some random time, although it should be once every 60 minutes

**Comment by Karabasina** [comment]
@zaskochill My connection has been connected for days and is not updated at all, only manually.

**Comment by burjuyz** [comment]
Auto update is broken me too. The same symptoms like @zaskochill

**Comment by RoninReilly** [comment]
Same

![image](https://github.com/SagerNet/sing-box/assets/69353457/0414c418-2ea3-415d-902f-bd4f301adb0c)

**Comment by mcdemon05** [comment]
same problem

**Comment by VladimirFedulov** [comment]
Same issue

**Comment by yolo-spolo** [comment]
same problem, iOS 17.3.1

**Comment by ssydb** [comment]
借楼问一下 ios 系统 报以下错误要怎么解决

ERROR[0000] router: download geoip database: Get "https://github.com/ SagerNet/sing-geoip/releases/latest/ download/geoip.db": dial tcp
[ipv6]:443: connect:
connection refused (packet-tunnel) error: start service: Get "https: //github.com/ SagerNet/sing-geoip/releases/latest/ download/geoip.db": dial tcp
[ipv6]:443: connect:
connection refused (packet-tunnel) stopping, reason:
NEProviderStopReason (rawValue: 1)

配置文件如下

{
  "log": {
    "level": "info",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "cloudflare",
        "address": "2606:4700:4700::1111"
      },
      {
        "tag": "dnspod",
        "address": "2402:4e00::",
        "detour": "direct"
      },
      {
        "tag": "block",
        "address": "rcode://success"
      }
    ],
    "rules": [
      {
        "geosite": "category-ads-all",
        "server": "block",
        "disable_cache": true
      },
      {
      	"outbound": "any",
      	"server": "dnspod"
      },
      {
        "geosite": "cn",
        "server": "dnspod"
      }
    ],
    "strategy": "ipv6_only"
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "interface_name": "tun0",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "auto_route": true,
      "strict_route": true,
      "stack": "system",
      "sniff": true
    }
  ],
  "outbounds": [
    {
      "type": "vless",
      "tag": "vless-out",
      "server": "ipv6",
      "server_port": 443,
      "uuid": "uuid",
      "flow": "",
      "tls": {
        "enabled": true,
        "server_name": "www.docker.com",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
         },
        "reality": {
          "enabled": true,
          "public_key": "public_key",
          "short_id": "short_id"
        }
      },
      "packet_encoding": "xudp",
      "multiplex": {
      	"enabled": true,
      	"protocol": "h2mux",
        "max_streams": 10,
      	"padding": true,
      	"brutal":{
      	  "enabled": true,
      	  "up_mbps": 30,
      	  "down_mbps": 1000
      	}
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns"
    }
  ],
  "route": {
    "geoip": {
      "download_url": "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db",
      "download_detour": "vless-out" 
    },
    "geosite": {
      "download_url": "https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db",
      "download_detour": "vless-out"
    },
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns"
      },
      {
        "geosite": "cn",
        "geoip": [
          "cn",
          "private"
        ],
        "outbound": "direct"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      }
    ],
    "auto_detect_interface": true
  }
}
