### ISSUE TITLE
mac第一次打开 提示(packet-tunnel) error: start service: open geoip database: error opening database: invalid MaxMind DB file

### ISSUE THREAD

**Issue by WarmBlackClouds** [SagerNet/sing-box#1489]
### Operating system

macOS

### System version

14.2.1

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.9.0-alpha.10

### Description

第一次打开就提示
(packet-tunnel) error: start service: open geoip database: error opening database: invalid MaxMind DB file

### Reproduction

可视化SFM客户端 添加完一个地址，然后运行，提示错误信息

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by wuweikang** [comment]
i've have the same issue, how could I proceed ? any response on this problem?

**Comment by ChihGodlee** [comment]
这个问题怎么解决啊？
