### ISSUE TITLE
Tun + fake-ip 模式接管局域网流量一段时间后连接堆积不释放

### ISSUE THREAD

**Issue by jerrita** [SagerNet/sing-box#1496]
### 操作系统

Linux

### 系统版本

Linux esxi 6.7.5 #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 16 18:14:32 UTC 2024 x86_64 GNU/Linux

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.8.5

Environment: go1.21.6 linux/amd64
Tags: with_quic,with_grpc,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_v2ray_api,with_gvisor
CGO: enabled
```

### 描述

看上去和 #1187 有着同样的表现，`tun` + `fake-ip` 模式在运行 **一段时间之后** 连接会持续堆积，tcp 连接即使在请求方关闭后，clash api 中也可以看到仍然存在。作为路由器使用，一般一个小时后会有接近一万条连接同时存在。

### 重现方式

准备多台机器，将一台机器配置为路由器，在此机器上执行以下：

1. 在本地 5353 端口搭建一份 dns 服务器
  
2. 在 53 端口运行一份 dnsmasq，将国内域名转向 5353 端口
  
3. dnsmasq 设置默认 Server=127.0.0.1#5355，将其他域名转向 sing-box
  
4. 编辑 sing-box 配置如下，填入服务器地址，更改 geoip 与 geosite 的地址。对于远程服务器，我使用了 shadowTLS + ss 以及 vless + reality 的配置。
  

```
{
  "dns": {
    "fakeip": {
      "enabled": true,
      "inet4_range": "198.18.0.0/15",
      "inet6_range": "fc00::/18"
    },
    "independent_cache": true,
    "rules": [
      {
        "disable_cache": true,
        "geosite": "category-ads-all",
        "server": "nxdomain"
      },
      {
        "inbound": "dns-in",
        "server": "remote"
      }
    ],
    "servers": [
      {
        "address": "127.0.0.1:5353",
        "address_resolver": "bootstrap",
        "detour": "direct",
        "tag": "local"
      },
      {
        "address": "223.5.5.5",
        "detour": "direct",
        "tag": "bootstrap"
      },
      {
        "address": "fakeip",
        "tag": "remote"
      },
      {
        "address": "rcode://name_error",
        "tag": "nxdomain"
      }
    ],
    "strategy": "prefer_ipv6"
  },
  "experimental": {
    "cache_file": {
      "enabled": true,
      "store_fakeip": false
    },
    "clash_api": {
      "external_controller": "0.0.0.0.0:9090",
      "external_ui": "/nix/store/z99aa1jxw69ib5546dcafapmynfjcaxa-source"
    }
  },
  "inbounds": [
    {
      "listen": "::",
      "listen_port": 5355,
      "network": "udp",
      "tag": "dns-in",
      "type": "direct"
    },
    {
      "gso": true,
      "inet4_address": "172.19.0.1/30",
      "type": "tun"
    }
  ],
  "log": {
    "level": "warn"
  },
  "outbounds": [
    {
      "default": "jp01-ss",
      "interrupt_exist_connections": true,
      "outbounds": [
        ......
      ],
      "tag": "select",
      "type": "selector"
    },
    {
      "tag": "direct",
      "type": "direct"
    },
    {
      "tag": "block",
      "type": "block"
    },
    {
      "tag": "dns-out",
      "type": "dns"
    },
    ......... 
  ],
  "route": {
    "default_interface": "ppp0",
    "geoip": {
      "path": "/nix/store/74ya2gp1rds44b9rq2d5kas2nniqdbry-sing-geoip-2024-02/share/sing-box/geoip.db"
    },
    "geosite": {
      "path": "/nix/store/ss6rnz3p3lm5rnvlkpi9crrnz07xzm3d-sing-geosite-20240208184303/share/sing-box/geosite.db"
    },
    "rules": [
      {
        "inbound": "dns-in",
        "outbound": "dns-out"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      }
    ]
  }
}
```

5. 启动 sing-box，并执行以下 bash 脚本配置分流：
  

```bash
declare -a ncn_list=(
    "198.18.0.0/15"
    "8.8.8.8/32"
    "1.1.1.1/32"
    "91.108.4.0/22"
    "91.108.8.0/22"
    "91.108.12.0/22"
    "91.108.16.0/22"
    "91.108.20.0/22"
    "91.108.56.0/22"
    "91.108.192.0/22"
    "149.154.160.0/20"
    "185.76.151.0/24"
)
declare -a ncn_list6=(
    "fc00::/18"
    "2001:b28:f23d::/48"
    "2001:b28:f23f::/48"
    "2001:67c:4e8::/48"
    "2001:b28:f23c::/48"
    "2a0a:f280::/32"
)
while ! ip a show tun0 &> /dev/null; do sleep 1; done
for cidr in "''${ncn_list[@]}"; do
    ip route add $cidr dev tun0
done
for cidr in "''${ncn_list6[@]}"; do
    ip -6 route add $cidr dev tun0
done
```

6. 局域网设备正常上网，等待一段时间可见服务端连接堆积。
  

### 完整性要求

- [x] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [ ] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [ ] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by nekohasekai** [comment]
尝试使用 `auto_route`, `inet4_route_address` 和 `inet6_route_address` 替换你自行添加的 ip route add 命令。

**Comment by jerrita** [comment]
链接数量也是在持续上涨，连接方中断 tcp 连接且等待几分钟后，在活动连接里还是能看到这条连接，应该和路由设置手段关系不大（复现方式编辑了下

**Comment by nekohasekai** [comment]
不，您没有提供：

1. 可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
2. 可用于重现我报告的错误的最简配置，而不是依赖远程服务器、或者其他软件。
3. 日志。

由于您的问题似乎并不常见，除非您尝试 https://github.com/SagerNet/sing-box/issues/1496#issuecomment-1962920049 且描述结果（或者赞助我），我不会购买一个 Linux 设备并尝试解决您的问题。

**Comment by jerrita** [comment]
实在抱歉回复不够明晰，我无意对您有所冒犯。碍于个人对此项目的理解水平低下，难以独立完成问题的 trace 以及分析，因此能力不足以提出 PR 请求。又难以割舍使用此工具，因此不得不选择开 Issue 询问此下策。

> 链接数量也是在持续上涨，连接方中断 tcp 连接且等待几分钟后，在活动连接里还是能看到这条连接，应该和路由设置手段关系不大（复现方式编辑了下

此条评论便是在尝试了 `auto_route, inet4_route_address 和 inet6_route_address 替换你自行添加的 ip route add 命令。` 基础之上发出，评论前我已去除了自定义脚本并将配置中的 tun 改为了：

```json
{
  "auto_route": true,
  "gso": true,
  "inet4_address": "172.19.0.1/30",
  "inet4_route_address": [
    "198.18.0.0/15",
    "8.8.8.8/32",
    "1.1.1.1/32",
    "91.108.4.0/22",
    "91.108.8.0/22",
    "91.108.12.0/22",
    "91.108.16.0/22",
    "91.108.20.0/22",
    "91.108.56.0/22",
    "91.108.192.0/22",
    "149.154.160.0/20",
    "185.76.151.0/24"
  ],
  "inet6_route_address": [
    "fc00::/18",
    "2001:b28:f23d::/48",
    "2001:b28:f23f::/48",
    "2001:67c:4e8::/48",
    "2001:b28:f23c::/48",
    "2a0a:f280::/32"
  ],
  "type": "tun"
}
```
但是结果与先前描述一致：

> 链接数量也是在持续上涨，连接方中断 tcp 连接且等待几分钟后，在活动连接里还是能看到这条连接

**Comment by jerrita** [comment]
至于日志，在 warn 以上并没有值得注意的条目，因此我之前未附上：

[sing-box.txt](https://github.com/SagerNet/sing-box/files/14396423/sing-box.txt)

而这个场景我觉得应该也不会有什么异常日志出现。

至于排查是不是 tun 才会出现的问题，需要的话我会换回 tcp redir + udp tproxy 的代理模式并更新答案。

**Comment by jerrita** [comment]
> 至于排查是不是 tun 才会出现的问题，需要的话我会换回 tcp redir + udp tproxy 的代理模式并更新答案。

也有同样的问题，但不清楚不开监控的行为，或许是 clash api 的 tcp tracker 所致，或是作为路由器代理局域网所造成的问题。

既然此问题非常见，此 issue 关闭。抱歉给您心情造成了不愉快。

**Comment by nekohasekai** [comment]
我平等的如此回复所有我没有精力处理的没有贡献的最终用户工单，而不会因为大量的此类问题不愉快。

如果您不想为您的问题提供开发人员可重现的配置，则捐赠给我们。

**Comment by suikastar** [comment]
我也遇到了类似的问题，昨天在路由器重新部署的，今天发现连接不回收，连接数破千，请问你解决了吗？

https://github.com/SagerNet/sing-box/issues/1902
