### ISSUE TITLE
[SFI] Route rule 'wifi_ssid' still applied after switching from wifi to cellular data 

### ISSUE THREAD

**Issue by kabegoe** [SagerNet/sing-box#1497]
### Operating system

iOS

### System version

iOS 17.3.1

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.8.6

### Description

Route rule `wifi_ssid` works without any problems initially when the iOS device is connected to internet with Wi-Fi or cellular data. However, even if the internet connection is changed from Wi-Fi to cellular (/cellular to Wi-Fi) while sing-box running, the rule is stilled applied (/not be applied). This behavior is not expected.

### Reproduction

1. Launch the sing-box with attached config.
2. Route rule `wifi_ssid` applied without any problems (blocked all traffic as expected).
3. Turn off Wi-Fi and use cellular data to connect to internet.
4. Route rule `wifi_ssid` still applied and keeping block all traffic (there is no more Wi-Fi connection which means `wifi_ssid` should not to be applied and traffic is supposed to be send to `direct` as described in config).

### Logs

config.json
```json
{
  "log": {
    "level": "trace"
  },
  "dns": {
    "servers": [
      {
        "tag": "ali",
        "address": "udp://223.5.5.5",
        "detour": "direct-out"
      }
    ],
    "final": "ali",
    "strategy": "prefer_ipv6",
    "disable_cache": true
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "auto_route": true,
      "stack": "mixed",
      "sniff": true,
      "sniff_override_destination": false
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct-out"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    },
    {
      "type": "block",
      "tag": "block-out"
    }
  ],
  "route": {
    "rules": [
      {
        "wifi_ssid": "WIFISSID",
        "outbound": "block-out"
      },
      {
        "protocol": "dns",
        "outbound": "dns-out"
      }
    ],
    "final": "direct-out",
    "auto_detect_interface": true
  }
}
```

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
Can you try the latest version?

**Comment by kabegoe** [comment]
It seems like that the symptom still persists with SFI 1.8.8 and 1.9.0-beta.12 (iOS 17.4).

**Comment by nekohasekai** [comment]
Try 1.9.0-beta.13

**Comment by kabegoe** [comment]
It works like a charm with 1.9.0-beta.13. Thank you🚀
