### ISSUE TITLE
[BUG]url-test如果outbounds字段为[]，内核无法运行

### ISSUE THREAD

**Issue by LittleTurtle2333** [SagerNet/sing-box#1499]
### Operating system

Windows

### System version

Windows 11 版本 10.0.22631 版本 22631

### Installation type

Third-party graphical clients that advertise themselves as using sing-box (Windows)

### If you are using a graphical client, please provide the version of the client.

GUI.for.SingBox v1.4.6

### Version

```shell
sing-box version 1.8.6

Environment: go1.22.0 windows/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: d32c30c4b7eebaef62dc2b7351dd85e9140def62
CGO: disabled
```

### Description

url-test如果outbounds字段为[]，内核无法运行
GUI.for.SingBox中的过滤字段填写为 **`KR|Korea|KOR|首尔|韩|韓`**

生成出来的singbox配置如下
`{
      "tag": "🇰🇷 韩国节点",
      "type": "urltest",
      "outbounds": [],
      "url": "https://www.gstatic.com/generate_204",
      "interval": "300s",
      "tolerance": 150
}`  

其中字段**`outbounds`**为空，运行singbox报错如下
`FATAL[0000] create service: parse outbound[27]: missing tags`  

像**Quantumult X**如果匹配为空的话会有相应的处理，例如QuanX会警告但保留代理组但是引用为空
但是Clash的话也有相应的处理就是报错，`proxy group[2]:kr韩国节点：use or proxies missing`
所以看看能不能两种解决方式采取任意一种，警告或者报错。

### Reproduction

[BUG]url-test如果outbounds字段为[]，内核无法运行
GUI.for.SingBox中的过滤字段填写为 `**KR|Korea|KOR|首尔|韩|韓**`

### Logs

```shell
FATAL[0000] create service: parse outbound[27]: missing tags
```

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
By design
