### ISSUE TITLE
更新a15后有断流现象。

### ISSUE THREAD

**Issue by lifeva** [SagerNet/sing-box#1503]
### Operating system

iOS

### System version

17.3.1

### Installation type

sing-box for iOS Graphical Client

### Version

```shell
1.9.0.a15
```

### Description

由a13版本更新后，断流。

### Reproduction

经测试，如果tun配置里stack设为system则出现youtube x等国外应用无法访问。如果将stack改为givsor，则恢复正常。同时测试了macos版本，情况类似，如果stack为system，则无法dig到解析结果，报错，改为givsor后，可以dig到解析结果，使用正常。

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by AmberisMyShiba** [comment]
alpha15 在默认的stacks为system的情况下，开启tun-in会让udp查询dns的方式超时，用tcp、DoH和DoT等udp以外的方式查询dns则正常。
stack设置为gvisor则没有上述问题

**Comment by debiansid** [comment]
我这是也是这样的

**Comment by OsemDing** [comment]
> alpha 15 ，amd64版本，Archlinux系统。 在默认的stacks为system的情况下，开启tun-in会让udp查询dns的方式超时，用tcp、DoH和DoT等udp以外的方式查询dns则正常。 stack设置为gvisor则没有上述问题

windows, 在默认的stacks为system的情况下，开启strict_route后，dns解析不了，改为false后可以上网，但打开网页解析dns时候偶尔有卡顿现象。改gvisor后，好了，感谢。
