### ISSUE TITLE
[Feature Request] QUIC with HTTP headers

### ISSUE THREAD

**Issue by radioactiveAHM** [SagerNet/sing-box#1506]
To enable proxy pass using NGINX or utilize a CDN like Cloudflare, support for HTTP headers is required for QUIC transport.

**Comment by radioactiveAHM** [comment]
> Does Cloudflare support to reverse proxy QUIC connections to a QUIC upstream? With the free plan?

It does support when using Cloudflare tunnel (Argo). But with the normal usage i haven't checked.

**Comment by nekohasekai** [comment]
We will not add proprietary functionality to "v2ray transport", send your request to v2ray.
