### ISSUE TITLE
从Alpha.14开始Tproxy入站异常

### ISSUE THREAD

**Issue by bxyun0** [SagerNet/sing-box#1508]
### 操作系统

Linux

### 系统版本

OpenWRT 21.02

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.9.0-alpha.15

Environment: go1.22.0 linux/arm64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: 9e957c7f8b13bdea8c8e872d25d255f5c92e14dd
CGO: disabled
```

### 描述

从Alpha.14开始，使用Tproxy入站，局域网设备及网关网络异常，表现为获取不到DNS，浏览器显示“无网络连接”，Clash面板中显示有大量192.168.6.1:53的连接，Sing-box无错误日志输出，Microsoft Edge有时可以连接直连网站，其它浏览器、Windows及手机均无法联网，相同配置下将内核替换为Alpha.13及之前的版本可正常获取DNS；若修改使用Tun入站新版内核也可以正常上网。Alpha.14和Alpha.15都是同样的问题。
`"inbounds":[
  {
    "tag": "Tproxy-in",
    "type": "tproxy",
    "listen": "::",
    "listen_port": 2053,
    "tcp_fast_open": true,
    "tcp_multi_path": false,
    "udp_fragment": true,
    "sniff": true,
    "sniff_override_destination": false
  }
]`

`ip route add local default dev lo table 100
ip rule add fwmark 1 table 100

iptables -t mangle -N SING
iptables -t mangle -A SING -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A SING -d 10.0.0.0/24 -j RETURN
iptables -t mangle -A SING -d 127.0.0.1/32 -j RETURN
iptables -t mangle -A SING -d 192.0.0.0/24 -j RETURN
iptables -t mangle -A SING -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A SING -d 255.255.255.255/32 -j RETURN
iptables -t mangle -A SING -d 192.168.0.0/16 -p tcp -j RETURN
iptables -t mangle -A SING -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN
iptables -t mangle -A SING -j RETURN -m mark --mark 0xff
iptables -t mangle -A SING -p udp -j TPROXY --on-ip 127.0.0.1 --on-port 2053 --tproxy-mark 1
iptables -t mangle -A SING -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port 2053 --tproxy-mark 1
iptables -t mangle -A PREROUTING -j SING

iptables -t mangle -N SING_MASK
iptables -t mangle -A SING_MASK -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A SING_MASK -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A SING_MASK -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A SING_MASK -d 192.0.0.0/24 -j RETURN
iptables -t mangle -A SING_MASK -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A SING_MASK -d 255.255.255.255/32 -j RETURN
iptables -t mangle -A SING_MASK -d 192.168.0.0/16 -p tcp -j RETURN
iptables -t mangle -A SING_MASK -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN
iptables -t mangle -A SING_MASK -j RETURN -m mark --mark 0xff
iptables -t mangle -A SING_MASK -p udp -j MARK --set-mark 1
iptables -t mangle -A SING_MASK -p tcp -j MARK --set-mark 1
iptables -t mangle -A OUTPUT -j SING_MASK

iptables -t mangle -N DIVERT
iptables -t mangle -A DIVERT -j MARK --set-mark 1
iptables -t mangle -A DIVERT -j ACCEPT
iptables -t mangle -I PREROUTING -p tcp -m socket -j DIVERT`

### 重现方式

使用自定义编译和修改iptables规则等手段均无法解决，是否与“Improve DNS truncate behavior”有关

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by AmberisMyShiba** [comment]
你是否可以在开启tun-in的情况下，测试以下两个命令
1.dig baidu.com @223.5.5.5
2.dig baidu @223.5.5.5 +tcp
我的情况是命令2可以正常获取dns,命令1超时。不知你的情况是否如此？

**Comment by bxyun0** [comment]
> 你是否可以在开启tun-in的情况下，测试以下两个命令 1.dig baidu.com @223.5.5.5 2.dig baidu @223.5.5.5 +tcp 我的情况是在Archlinux和gentoo 系统下，命令2可以正常获取dns，但是命令1超时。同版本的SFA则正常。不知你的情况是否如此？

acc@Acc-M7600RE:~$ dig baidu.com @223.5.5.5

; <<>> DiG 9.18.18-0ubuntu0.22.04.2-Ubuntu <<>> baidu.com @223.5.5.5
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49246
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;baidu.com.			IN	A

;; ANSWER SECTION:
baidu.com.		97	IN	A	110.242.68.66
baidu.com.		97	IN	A	39.156.66.10

;; Query time: 8 msec
;; SERVER: 223.5.5.5#53(223.5.5.5) (UDP)
;; WHEN: Wed Feb 28 13:40:38 CST 2024
;; MSG SIZE  rcvd: 70

acc@Acc-M7600RE:~$ dig baidu @223.5.5.5 +tcp

; <<>> DiG 9.18.18-0ubuntu0.22.04.2-Ubuntu <<>> baidu @223.5.5.5 +tcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 60791
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; WARNING: EDNS query returned status FORMERR - retry with '+noedns'

;; QUESTION SECTION:
;baidu.				IN	A

;; Query time: 148 msec
;; SERVER: 223.5.5.5#53(223.5.5.5) (TCP)
;; WHEN: Wed Feb 28 13:40:53 CST 2024
;; MSG SIZE  rcvd: 23

**Comment by AmberisMyShiba** [comment]
> > 你是否可以在开启tun-in的情况下，测试以下两个命令 1.dig baidu.com @223.5.5.5 2.dig baidu @223.5.5.5 +tcp 我的情况是在Archlinux和gentoo 系统下，命令2可以正常获取dns，但是命令1超时。同版本的SFA则正常。不知你的情况是否如此？
> 
> acc@Acc-M7600RE:~$ dig baidu.com @223.5.5.5
> 
> ; <<>> DiG 9.18.18-0ubuntu0.22.04.2-Ubuntu <<>> baidu.com @223.5.5.5 ;; global options: +cmd ;; Got answer: ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49246 ;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION: ; EDNS: version: 0, flags:; udp: 1232 ;; QUESTION SECTION: ;baidu.com. IN A
> 
> ;; ANSWER SECTION: baidu.com. 97 IN A 110.242.68.66 baidu.com. 97 IN A 39.156.66.10
> 
> ;; Query time: 8 msec ;; SERVER: 223.5.5.5#53(223.5.5.5) (UDP) ;; WHEN: Wed Feb 28 13:40:38 CST 2024 ;; MSG SIZE rcvd: 70
> 
> acc@Acc-M7600RE:~$ dig baidu @223.5.5.5 +tcp
> 
> ; <<>> DiG 9.18.18-0ubuntu0.22.04.2-Ubuntu <<>> baidu @223.5.5.5 +tcp ;; global options: +cmd ;; Got answer: ;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 60791 ;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 ;; WARNING: recursion requested but not available
> 
> ;; WARNING: EDNS query returned status FORMERR - retry with '+noedns'
> 
> ;; QUESTION SECTION: ;baidu. IN A
> 
> ;; Query time: 148 msec ;; SERVER: 223.5.5.5#53(223.5.5.5) (TCP) ;; WHEN: Wed Feb 28 13:40:53 CST 2024 ;; MSG SIZE rcvd: 23

谢谢反馈。
