### ISSUE TITLE
分流问题请教

### ISSUE THREAD

**Issue by jh0072110** [SagerNet/sing-box#152]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

我就直接发脱敏config了，我其实不太知道这是bug还是我写的有问题，抛砖引玉一下吧…
现在问题是vps1分流netflix去vps2，但netflix无法连接（或者其实很偶然的能连一下……）
完全不知道哪里出了错……
拜求各位大佬了……
PS：我编译了grpc所以不是grpc的问题
![image](https://user-images.githubusercontent.com/50496854/195413626-56ad3a35-f650-466b-8651-0be29f3a9cc8.png)

### Version of sing-box

sing-box 1.1 beta9 最新编译版本

### Server and client configuration file

{
    "inbounds": [
        {
            "type": "vmess",
            "listen": "::",
            "listen_port": 123,
            "users": [
                {
                    "name": "me",
                    "uuid": "xxxuuid",
                    "alterId": 0
                }
            ],
            "sniff": true,
            "sniff_override_destination": true,
            "domain_strategy": "ipv4_only",
            "tls": {
                "enabled": true,
                "server_name": "vps1.com",
                "alpn": [
                    "h2"
                ],
                "certificate_path": "/xx/xx.crt",
                "key_path": "/xx/xx.key"
            },
            "transport": {
                "type": "grpc",
                "service_name": "ola"
            }
        }
    ],
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "shadowsocks", 
            "tag": "Unlock",
            "server": "vps2ip",     
            "server_port": 123,
            "method": "aes-128-gcm",
            "password": "secret"
        }
    ],
    "route": {
        "geosite": {
            "path": "geosite.db",
            "download_url": "https://github.com/1715173329/sing-geosite/releases/latest/download/geosite.db"
        },
        "geoip": {
            "path": "geoip.db",
            "download_url": "https://github.com/1715173329/sing-geoip/releases/latest/download/geoip.db"
        },
        "rules": [
            {
                "geoip": "cn",
                "outbound": "block"
            },
            {
                "domain_keyword": [
                    "ip.sb"
                ], 
                "geosite": [
                    "netflix"
                ],
                "outbound": "Unlock"
            }
        ]
    }
}

### Server and client log file

none yet

**Comment by chika0801** [comment]
"domain_strategy": "ipv4_only",

要删了这个，开它意思是，如果你从路由器（传过来的是IP），或者你是电脑上用v2rayN到VPS的请求也是域名

请求到VPS这，是IP的请求被域名嗅探还原成域名，是域名的请求，还是域名。因为上面的参数，在进路由模块前，用你VPS的系统DNS，把域名解析成了IP。

再进路由规模块，因为进来的都是IP了，所以只能匹配禁止CNIP的规则 ，你转发到VPS2的规则是基于域名的。2都不能都兼得。

所以你把 "domain_strategy": "ipv4_only", 删了好了，

{
"geoip": "cn",
"outbound": "block"
},

这个也可以删了。

**Comment by lin1123** [comment]
我的情况是一台连接落地鸡可以分流，另一台就连不上。
