### ISSUE TITLE
 http: authentication failed, no Proxy-Authorization header

### ISSUE THREAD

**Issue by chenxudong2020** [SagerNet/sing-box#1524]
### Operating system

Windows

### System version

win10

### Installation type

Original sing-box Command Line

### Version

```shell
1.8.7
```

### Description

![image](https://github.com/SagerNet/sing-box/assets/61214170/f3f4ae41-4a2b-478c-aa9e-bd4f6881a573)
swith omeya set right username and password
mixed or  http  inbound same error!!!!!!!!
![image](https://github.com/SagerNet/sing-box/assets/61214170/f00241eb-1ae1-42d1-9360-a222de93d54c)

### Reproduction

{
  "experimental": {
    "clash_api": {
      "external_controller": "127.0.0.1:9090",
      "external_ui": ""
    }
  },
  "log": {
    "level": "info",
    "timestamp": false
  },
  "inbounds": [
    {
      "type": "http",
      "tag": "http-in",
      "listen": "::",
      "listen_port": 54322,
	  "users": [
		{
      "username": "admin",
      "password": "admin"
    }
	  ],
      "set_system_proxy": false
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "selector",
      "tag": "proxy",
      "outbounds": [
        "overtls"
      ],
      "default": "overtls"
    },
    {
      "type": "socks",
      "tag": "overtls",
      "server": "127.0.0.1",
      "server_port": 1080,
	  "version": "5",
	  "network": "tcp",
	  "udp_over_tcp": {
		  "enabled": false,
		  "version": 2
		}
    }
  ],
  "route": {
    "rules": [
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "process_name": [
		  "TencentMeeting",
          "NemoDesktop",
          "ToDesk",
          "ToDesk_Service",
          "WeChat",
          "OpenLens",
          "Tailscale",
          "wireguard-go",
          "Tunnelblick",
          "softwareupdated",
          "kubectl"
        ],
        "outbound": "direct"
      },
      {
        "geosite": "cn",
        "geoip": [
          "cn",
          "private"
        ],
        "outbound": "direct"
      },
      {
        "geosite": "geolocation-!cn",
        "geoip": "!cn",
        "outbound": "proxy"
      }
    ]
  }
}

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by chenxudong2020** [comment]
It seems that these two issues are not the same. HTTP uses basic authentication. If the Proxy Authorization header is intercepted from the inbound for authentication, because most browsers use HTTPS to access websites, they cannot be obtained. I am not sure about the principle, but I am just guessing; But if I replace singbox with v2rayN and use the same HTTP inbound username and password authentication, then there is no such problem

**Comment by chenxudong2020** [comment]
@dyhkwong @tobyxdd @nekohasekai

**Comment by DuFoxit** [comment]
@chenxudong2020  You can try to clear your browser's cookies and history before testing.

**Comment by chenxudong2020** [comment]
> @chenxudong2020 You can try to clear your browser's cookies and history before testing.

Clear cache test still doesn't work
