### ISSUE TITLE
SFI 1.8.6 UI 更新后失去了Always On开关，无法开启/关闭Always On功能

### ISSUE THREAD

**Issue by CJinfaOneH** [SagerNet/sing-box#1530]
### 操作系统

iOS

### 系统版本

17.3.1

### 安装类型

sing-box for iOS 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.8.7

### 描述

SFI 1.8.6 UI更新后，在Setting的Always On开关并没有出现在新的UI上。
这导致从1.8.5更新至新版本后，原本如果打开的Always On功能无法关闭。
新安装1.8.6后，无法打开Always On功能。

### 重现方式

UI Issue
设置中Core/Packet Tunnel/Profile Override均没有Always On的选项。

![issue](https://github.com/SagerNet/sing-box/assets/147702808/54d814ef-d06b-4ea3-98b2-a9cdf5d3179e)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by LTACHTM** [comment]
+1  这两天出现莫名其妙的关闭  之后无法自动重启

**Comment by love4taylor** [comment]
1.8.11 加回来了

![IMG_8410.png](https://cdn.sa.net/2024/04/08/3POGfFuy7ieoUCM.png)
