### ISSUE TITLE
配置process_name，日志提示 failed to search process

### ISSUE THREAD

**Issue by nmweizi** [SagerNet/sing-box#1533]
### Operating system

macOS

### System version

14.3

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.9.0.beta7

### Version

安装包从https://github.com/SagerNet/sing-box/releases下载

### Description

基于进程名称，调度outbound，日志提示failed to search process,并且不能调度到"outbound": "http-out"
，匹配了缺省"final": "节点选择"。

查看文档，支持Only supported on Linux, Windows, and macOS.

```
curl -vvvv http://www.google.cn
```

curl提示如下：

```
* Uses proxy env variable http_proxy == 'http://127.0.0.1:7891'
*   Trying 127.0.0.1:7891...
* Connected to 127.0.0.1 (127.0.0.1) port 7891
> GET http://www.google.cn/ HTTP/1.1
> Host: www.google.cn
> User-Agent: curl/8.4.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
```

配置
```json
  "route": {
    "auto_detect_interface": true,
    "rules": [
      {
        "process_name": [
          "curl"
        ],
        "outbound": "http-out"
      },
     ]
    "final": "节点选择"
  }
```

### Reproduction

curl -vvvv http://www.google.cn
看日志

### Logs

```shell
596 +0800 2024-03-03 13:16:58 INFO [3529341379 388ms] router: failed to search      process: The operation couldn’t be completed. (not implemented error 0.)
 597 +0800 2024-03-03 13:16:58 INFO [1070883390 244ms] router: failed to search      process: The operation couldn’t be completed. (not implemented error 0.)
```

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by choicky** [comment]
@nmweizi It's said that `process_name` is not supported in sfm (sing-box for mac).  However, `sing-box` supports `process_name` in macOS.  You could just run `sing-box run -c config.json` in a terminal to get what you want.
