### ISSUE TITLE
TPROXY下根据源地址进行分流，目标地址为本机ip时出现udp socket冲突

### ISSUE THREAD

**Issue by Alozxy** [SagerNet/sing-box#1536]
### Operating system

Linux

### System version

OpenWrt 23.05.0

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.8.4

Environment: go1.21.5 linux/arm64
Tags: with_clash_api,with_ech,with_gvisor,with_quic,with_reality_server,with_utls,with_wireguard
CGO: enabled
```

### Description

在openwrt上使用sing-box进行透明代理，TPROXY模式下想要根据局域网客户端ip进行源地址分流。部分相关脚本如下：

#!/usr/sbin/nft -f
add table ip sing-box
table ip sing-box {
        chain prerouting {
                type filter hook prerouting priority mangle
                ip daddr $RESERVED_IP return
                ip saddr != 192.168.1.100/32 return
                ip daddr 192.168.0.0/16 tcp dport != 53 return
                ip daddr 192.168.0.0/16 udp dport != 53 return
                meta mark 2 return
                meta l4proto {tcp, udp} mark set 1 tproxy to 127.0.0.1:11111 accept
        }
}

其中，局域网客户端192.168.1.100为需要代理的客户端，其余地址直连。问题在于，使用tproxy拦截192.168.1.100的dns请求，其余地址的dns请求由dnsmasq 192.168.1.1:53处理。但是直连客户端会不定期出现dns请求无响应的情况。

经过一番折腾，我发现问题似乎是这样的：当192.168.1.100主机发出dns请求之后，被TPROXY拦截然后进入到sing-box中，sing-box在回复dns响应的时候会创建一个新的socket： 

udp    192.168.1.1:53    0.0.0.0:*    sing-box

但是问题在于，dnsmasq也会监听这个地址，所以也一直存在这样的一个socket：

udp    192.168.1.1:53    0.0.0.0:*    dnsmasq

所以当一个直连客户端请求192.168.1.1:53时，会使用udp4_lib_lookup函数进行socket匹配，但是以上两个socket的匹配度是一样的，所以就会选择新创建的sing-box的socket，从而导致了直连主机的dns没有响应。当sing-box的socket被关闭后，dns响应恢复正常。

源码相关部分位于 
https://github.com/SagerNet/sing-box/blob/c8318058bb4a15e9d6751a71e78bdd3b68c57b32/inbound/tproxy.go#L112
我在想如果使用DialUDP代替ListenConfig，那么socket的remote address就会是代理客户端的源地址而不是0.0.0.0:*，这样就不会产生冲突了。不知道这个想法可不可行？

### Reproduction

使用上述nftables规则进行分流，代理客户端不断进行dns请求，直连客户端在进行dns请求的时候偶尔会卡住没有响应。

根据几次尝试，只要是根据源ip地址进行分流，且目的地址为路由器本机的udp服务，直连客户端均会出现这种情况。
目的地址不是本机地址的不会出现这样的问题，因为直连客户端发出的请求会直接被内核转发，不会进行socket选择。

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
> 被TPROXY拦截然后进入到sing-box中，sing-box在回复dns响应的时候会创建一个新的socket：

tproxy 就是像这样运行的。
