### ISSUE TITLE
当使用Naive协议入站时，客户端传输UDP协议会导致服务端panic

### ISSUE THREAD

**Issue by Mandi-Sa** [SagerNet/sing-box#155]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

如题，客户端为SagerNet 0.8.1-rc02，Naive Plugin版本为106.0.5249.91-1，启用了SagerNet上的UDP Over TCP功能。想问一下sing-box是不支持SagetNet的UDP Over TCP功能吗？

### Version of sing-box

sing-box version 1.1-beta9

Environment: go1.19.2 linux/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_clash_api
Revision: 143b62218040348c7c165ecec27c25e324dffee9
CGO: disabled

### Server and client configuration file

服务器配置：
{
	"inbounds": [
		{
			"type": "naive",
			"tag": "naive-in",
			"listen": "::",
			"listen_port": 8443,
			"tcp_fast_open": true,
			"sniff": true,
			"sniff_override_destination": false,
			"domain_strategy": "prefer_ipv4",
			"udp_timeout": 300,
			"proxy_protocol": false,
			"users": [
				{
					"username": "xxx",
					"password": "xxx"
				}
			],
			"tls": {
				"enabled": true,
				"min_version": "1.2",
				"max_version": "1.3",
				"certificate_path": "/www/certificates/fullchain_ecc.pem",
				"key_path": "/www/certificates/private_ecc.pem"
			}
		}
	],
	"outbounds": [
		{
			"type": "direct",
			"tag": "direct"
		}
	],
	"route": {
		"rules": [
			{
				"inbound": [
					"naive-in"
				],
				"outbound": "direct"
			}
		]
	}
}

客户端（SargeNet）配置：
服务器：example.com
服务器端口：8443
用户名：xxx
密码：xxx
协议：HTTPS
附加标头：未设置
不安全并发：0
UDP Over TCP：启用

### Server and client log file

INFO[0018] [3649522395] inbound/naive[naive-in]: inbound connection from 111.23.xxx.xxx:40078
INFO[0018] [3649522395] inbound/naive[naive-in]: inbound connection to sp.udp-over-tcp.arpa:443
INFO[0018] [3649522395] router: inbound UoT connection
2022/10/13 16:39:35 http2: panic serving 111.23.xxx.xxx:40078: runtime error: slice bounds out of range [:3] with capacity 1
goroutine 109 [running]:
net/http.(*http2serverConn).runHandler.func1()
        $GOROOT/src/net/http/h2_bundle.go:5904 +0x125
panic({0xea2d60, 0xc000047410})
        $GOROOT/src/runtime/panic.go:884 +0x212
github.com/sagernet/sing-box/inbound.(*naiveH2Conn).read(0xc00013c540, {0xc00016ba24, 0x1, 0x1})
        /home/sekai/Projects/sing-box/inbound/naive.go:427 +0x1c8
github.com/sagernet/sing-box/inbound.(*naiveH2Conn).Read(0x7fe663f19b58?, {0xc00016ba24?, 0x7fe68b41a108?, 0x0?})
        /home/sekai/Projects/sing-box/inbound/naive.go:403 +0x1e
io.ReadAtLeast({0x10a5c00, 0xc000260540}, {0xc00016ba24, 0x1, 0x1}, 0x1)
        $GOROOT/src/io/io.go:332 +0x9a
io.ReadFull(...)
        $GOROOT/src/io/io.go:351
github.com/sagernet/sing/common/rw.ReadByte({0x10a5c00, 0xc000260540})
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221006081821-c4e9bf11fa00/common/rw/read.go:22 +0x67
github.com/sagernet/sing/common/metadata.(*Serializer).ReadAddress(0xc0000110e0, {0x10a5c00, 0xc000260540})
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221006081821-c4e9bf11fa00/common/metadata/serializer.go:120 +0x67
github.com/sagernet/sing/common/metadata.(*Serializer).ReadAddrPort(0xc0000110e0, {0x10a5c00, 0xc000260540})
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221006081821-c4e9bf11fa00/common/metadata/serializer.go:167 +0x74
github.com/sagernet/sing/common/uot.(*ClientConn).ReadPacket(0xc000260540, 0x4000?)
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221006081821-c4e9bf11fa00/common/uot/client.go:30 +0xd7
github.com/sagernet/sing-box/route.(*Router).RoutePacketConnection(_, {_, _}, {_, _}, {{0xc000043e08, 0x8}, {0xf28992, 0x5}, 0x0, ...})
        /home/sekai/Projects/sing-box/route/router.go:635 +0x8cf
github.com/sagernet/sing-box/route.(*Router).RouteConnection(_, {_, _}, {_, _}, {{0xc000043e08, 0x8}, {0xf28992, 0x5}, 0x0, ...})
        /home/sekai/Projects/sing-box/route/router.go:553 +0x151a
github.com/sagernet/sing-box/inbound.(*myInboundAdapter).newConnection(_, {_, _}, {_, _}, {{0xc000043e08, 0x8}, {0xf28992, 0x5}, 0x0, ...})
        /home/sekai/Projects/sing-box/inbound/default.go:121 +0x155
github.com/sagernet/sing-box/inbound.(*myInboundAdapter).routeTCP(_, {_, _}, {_, _}, {{0xc000043e08, 0x8}, {0xf28992, 0x5}, 0x0, ...})
        /home/sekai/Projects/sing-box/inbound/default_tcp.go:66 +0x145
github.com/sagernet/sing-box/inbound.(*Naive).newConnection(0xc000113860, {0x10b41a0, 0xc0000d1cb0}, {0x10bc960, 0xc00013c540}, {{{0x0, 0xffff6f171383}, 0xc000010030}, 0x9c8e, {0x0, ...}}, ...)
        /home/sekai/Projects/sing-box/inbound/naive.go:178 +0x185
github.com/sagernet/sing-box/inbound.(*Naive).ServeHTTP(0xc000113860, {0x10b3090?, 0xc0000121b8}, 0xc00017c900)
        /home/sekai/Projects/sing-box/inbound/naive.go:173 +0x9fc
net/http.serverHandler.ServeHTTP({0x130100010304?}, {0x10b3090, 0xc0000121b8}, 0xc00017c900)
        $GOROOT/src/net/http/server.go:2947 +0x30c
net/http.initALPNRequest.ServeHTTP({{0x10b41a0?, 0xc00014e150?}, 0xc000150a80?, {0xc0000f82d0?}}, {0x10b3090, 0xc0000121b8}, 0xc00017c900)
        $GOROOT/src/net/http/server.go:3556 +0x245
net/http.(*http2serverConn).runHandler(0x10b0238?, 0x1737c28?, 0x0?, 0x0?)
        $GOROOT/src/net/http/h2_bundle.go:5911 +0x78
created by net/http.(*http2serverConn).processHeaders
        $GOROOT/src/net/http/h2_bundle.go:5641 +0x5b9

**Comment by nekohasekai** [comment]
Try 92a92f39c57dc250fefb69d55b5d32b7ee77d4f6

**Comment by Mandi-Sa** [comment]
> 

能够正常使用了，谢谢！
