### ISSUE TITLE
tls指定证书路径，如果证书文件发生变化，sing-box会自动重新加载证书吗？还是需要手动重启一次？

### ISSUE THREAD

**Issue by yzxiu** [SagerNet/sing-box#1553]
### Operating system

Linux

### System version

ubuntu22.04

### Installation type

Original sing-box Command Line

### Description

tls指定证书路径，如果证书文件发生变化，sing-box会自动重新加载证书吗？还是需要手动重启一次？

### Reproduction

使用acme配置总会有问题，反而是使用caddy申请的证书倒是正常。所以有这个疑问

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
会。
