### ISSUE TITLE
netlink: 'sing-box': attribute type 22 has an invalid length.

### ISSUE THREAD

**Issue by ziyouwa** [SagerNet/sing-box#1566]
### 操作系统

Linux

### 系统版本

Gentoo Linux  

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.8.4

Environment: go1.21.6 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: c8318058bb4a15e9d6751a71e78bdd3b68c57b32
CGO: disabled
```

### 描述

linux kernel 6.1~6.7，sing-box版本1.8.4、1.8.7都试过，工作倒是正常，就是dmesg可以看到报’netlink: 'sing-box': attribute type 22 has an invalid length.‘。频率不高，但是一直有报，能解决的话最好。inbound是tun，outbound是hysteria2 。好用，非常感谢！

### 重现方式

systemd服务的方式，开机启动。运行一段时间后dmesg可以看到：
[ 1176.771967] netlink: 'sing-box': attribute type 22 has an invalid length.
[ 1176.772060] netlink: 'sing-box': attribute type 22 has an invalid length.
[ 1179.113263] netlink: 'sing-box': attribute type 22 has an invalid length.
[ 1179.113373] netlink: 'sing-box': attribute type 22 has an invalid length.
[61348.177042] netlink: 'sing-box': attribute type 22 has an invalid length.
[61348.177115] netlink: 'sing-box': attribute type 22 has an invalid length.

### 日志

```shell
未启用日志，另外，希望能加入日志按日期分割的功能，历史日志以压缩文件的方式存放更好。
```

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by nekohasekai** [comment]
Caused by https://github.com/vishvananda/netlink
