### ISSUE TITLE
SFM App   No response when clicked "install system extension"

### ISSUE THREAD

**Issue by 192114** [SagerNet/sing-box#1571]
### Operating system

macOS

### System version

macos sonoma 14.4

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.8.8

### Description

In dashboard , click "install system extension"  no response

### Reproduction

In dashboard , click "install system extension"  no response

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by 192114** [comment]
`brew install sfm` have this problem

**Comment by gemili** [comment]
same issue

> `brew install sfm` have this problem

You need to allow SFM to run in Privacy & Security manually

**Comment by KingAmo** [comment]
error when click `Install System Extention` :
```
The operation couldn’t be completed. (OSSystemExtensionErrorDomain error 10.)
```

no "allow" request in system's "Privacy & Security"

I install SFM by `brew install sfm`, any help please ?

**Comment by sumwai** [comment]
macOS version: 15.0
SFM version: 1.9.6 (1)
SFM installed by `brew install sfm`

<img width="587" alt="image" src="https://github.com/user-attachments/assets/1cec71f0-4de1-4b66-bd57-9734a2ae20c7">
You can find 'Network Extension' in the 'System Settings'>' General '>' Login and Extension 'page ->' Extension 'block, click the' i 'button on the right to see' SFM ', turn it on, and then try' Install System Extension 'again`

in Chinese: 
`系统设置` -> `通用` -> `登录项与扩展` -> `扩展` -> `网络扩展` -> 右侧`i`按钮，点击进去就能找到SFM了，打开选项，重新在`SFM`中点击`Install System Extention`，就会有系统弹窗了

**Comment by Touchpeach** [comment]
<img width="474" alt="image" src="https://github.com/user-attachments/assets/3650aa3b-f198-4f4f-b77d-2bbece51220e">
You need to open both of them
