### ISSUE TITLE
文档能否增加一些解释，像v2fly.org v5这样，感觉稍微好些

### ISSUE THREAD

**Issue by zwl1619** [SagerNet/sing-box#1578]
文档能否增加一些解释（具体就是一些项的含义和用途），像v2fly.org v5这样，感觉稍微好些。
当然sing-box.sagernet.org也有比v2fly.org v5好的地方。

https://www.v2fly.org/v5/config/overview.html

**Comment by lifei6671** [comment]
这个项目主打的就是爱用不用，小白别用。
