### ISSUE TITLE
[Feature Request] Wireguard Inbound

### ISSUE THREAD

**Issue by hiddify-com** [SagerNet/sing-box#1580]
It would be great if you can add Wireguard inbound which is useful to be used as transparent proxy in Mikrotik.

I have tried to add Wireguard inbound but i was stocked in its implementation.
I've seen that in your code you have implemented most of the functionality for wireguard Inbound.

Thanks

**Comment by Palatis** [comment]
just create a wireguard interface with the wg script, and re-route the traffic to your tunnel.

**Comment by andy72630** [comment]
> Mikrotik

AFAIK , Mikrotik natively supports wireguard itself.
if you want to initiate a connection from your Mikrotik to the proxy server despite of using Wireguard directly . you may consider using Container.

**Comment by syk6666** [comment]
[功能请求] Wireguard 入站  这个很有用 希望能有

**Comment by dumkin** [comment]
This would be a very convenient way to connect some closed devices (like a TV or a router) wireguard client is available on almost any platform, and I personally am really looking forward to this opportunity
