### ISSUE TITLE
Feature Request: Port Hopping Functionality for Hysteria2 Protocol

### ISSUE THREAD

**Issue by Sortnz** [SagerNet/sing-box#1584]
Dear Sing-box Developers,

I am writing to suggest an enhancement for the Hysteria2 protocol within Sing-box. Specifically, I propose the implementation of a port hopping feature, which has been successfully integrated into Clash-Meta, see https://github.com/MetaCubeX/mihomo/pull/1064.

I believe that incorporating this functionality into Hysteria2 would not only align with the current advancements in similar projects but also enhance the user experience for those relying on Sing-box for their networking needs.

Thank you for considering this request. I look forward to your thoughts and the potential integration of port hopping into Hysteria2.

**Comment by DushesS01** [comment]
Port hopping functionality is implemented since 1.11*
