### ISSUE TITLE
Serious problem with Apple TV

### ISSUE THREAD

**Issue by behzad94** [SagerNet/sing-box#1587]
### Operating system

Apple tvOS

### System version

tvos 17

### Installation type

sing-box for Apple tvOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.8.9

### Description

Hello
Thank you for your super powerful program

In the latest update
There is a problem with Apple TV
No matter how many times you press the enable button, the screen just flashes and does not connect.

I deleted the program and reinstalled it.
It can no longer get configuration from the phone (photo of the error is attached)
The configuration of the remote also has a problem and it does not connect
please check it.
Thankful

### Reproduction

No matter how many times you press the enable button, the screen just flashes and does not connect.

I deleted the program and reinstalled it.
It can no longer get configuration from the phone (photo of the error is attached)
The configuration of the remote also has a problem and it does not connect

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by hugit6** [comment]
same issue on my atv.
suddenly broken can not enable.
reinstall can not fix it.

**Comment by behzad94** [comment]
I had the tvOS 17.3 operating system, and the connection problem was solved today with the operating system update.

**Comment by jemerci** [comment]
I reboot my iphone , the issue gone.
ATV 17.5.1
