### ISSUE TITLE
Feature request: Trojan connection fallback

### ISSUE THREAD

**Issue by zakuwaki** [SagerNet/sing-box#16]
Hi, is there any feature that works like fallbacks in xray or trojan which redirect un-authorized traffic to local http server

**Comment by nekohasekai** [comment]
It's only to deceive yourself

**Comment by zakuwaki** [comment]
Honestly, in some cases you are right. However when GFW performs active probing on your fake https website, always return 503 errors while transferring massive data is a typical signal of a proxy server.

**Comment by zakuwaki** [comment]
So could you please take this feature into consideration? Thanks.

**Comment by nekohasekai** [comment]
There is no evidence that GFW performs blocking based on http responses.

**Comment by nekohasekai** [comment]
Since this is a classic feature loved by users, reopen it.

**Comment by nekohasekai** [comment]
Try 9b97a462af187b9ccb95a6888f4b7cb6eec0e34e

**Comment by zakuwaki** [comment]
Awesome!

**Comment by zakuwaki** [comment]
It works! Thank you!

**Comment by zakuwaki** [comment]
BTW, I suggest that it should fallback to different ip:port based on alpn and also consider supporting proxyprotocol.

**Comment by nekohasekai** [comment]
What is proxyprotocol for?

**Comment by zakuwaki** [comment]
For example, fallback backend (like nginx) can read real ip using proxyprotocol and much more works and functions could be done.

**Comment by zakuwaki** [comment]
I think sing-box is much better than v2ray/xray when performs like a proxy platform in the view of arch, performance and functional. Also it could bring more useful features (not hard or complicated) that makes it powerful.

**Comment by zakuwaki** [comment]
Hi, I've read the Xray code, and
- it implements fallbacks with alpn in https://github.com/XTLS/Xray-core/blob/main/proxy/trojan/server.go#L75-L123
- and writes proxy proto info in https://github.com/XTLS/Xray-core/blob/main/proxy/trojan/server.go#L523-L552
I'm not good in Go and it may be hard for me to patch these features to sing-box. I'm learning, but the structure of Xray is too hard to understand...

**Comment by nekohasekai** [comment]
proxyprotocol is already implemented in sing-box.

**Comment by zakuwaki** [comment]
Thank you.
I've read the [commit](https://github.com/SagerNet/sing-box/commit/1413c5022a8e4747bad82f8a01394ce3fe23f17e). And I noticed that proxy protocol is implemented in parser/listener for sing-box running in backend behind nginx/caddy. While, if it runs as frontend, it need to write proxy protocol info for backend.
