### ISSUE TITLE
inbound/tun[0]: batch read packet: too many segments

### ISSUE THREAD

**Issue by bi4nbn** [SagerNet/sing-box#1605]
### 操作系统

Linux

### 系统版本

Version sing-box 1.8.9

### 安装类型

其他

### 如果您使用图形客户端程序，请提供该程序版本。

docker镜像 gzxhwq/sing-box:dev

### 描述

24-03-22 10:09:27[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:27[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:25[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:25[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:25[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:25[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:25[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:22[ error ][451426613 5.0s] inbound/tun[0]: dial tcp 198.18.4.220:443: i/o timeout
24-03-22 10:09:21[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:21[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:21[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:21[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:20[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:20[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:20[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:19[ error ][2193148148 5.0s] inbound/tun[0]: dial tcp 198.18.4.215:80: i/o timeout
24-03-22 10:09:17[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:17[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:15[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:15[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:14[ error ][3279733594 5.0s] inbound/tun[0]: dial tcp 198.18.4.215:80: i/o timeout
24-03-22 10:09:13[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:13[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:13[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:11[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:09[ error ][1723515323 5.0s] inbound/tun[0]: dial tcp 198.18.4.193:443: i/o timeout
24-03-22 10:09:05[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:05[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:05[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:05[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:03[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:03[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:02[ error ][2201628007 5.0s] inbound/tun[0]: dial tcp 198.18.4.243:443: i/o timeout
24-03-22 10:09:02[ error ][2331813018 5.0s] inbound/tun[0]: dial tcp 198.18.4.234:80: i/o timeout
24-03-22 10:09:02[ error ][1553543518 5.0s] inbound/tun[0]: dial tcp 198.18.4.243:443: i/o timeout
24-03-22 10:09:02[ error ][2191526011 5.0s] inbound/tun[0]: dial tcp 198.18.4.235:80: i/o timeout
24-03-22 10:09:00[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:00[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:09:00[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:08:58[ error ][991803387 5.0s] inbound/tun[0]: dial tcp 198.18.4.193:443: i/o timeout
24-03-22 10:08:58[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:08:58[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:08:58[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:08:58[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:08:58[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:08:56[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:08:56[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:08:56[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:08:56[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:08:52[ error ]inbound/tun[0]: batch read packet: too many segments
24-03-22 10:08:51[ error ][3299791400 5.0s] inbound/tun[0]: dial tcp 198.18.4.193:443: i/o timeout
### 重现方式

只要流量起来就报错 配置如下

  "inbounds": [{
    "type": "tun",
    "mtu": 9000,
    "inet4_address": "172.19.0.1/30",
    "stack": "mixed",
    "sniff": true,
    "auto_route": true,
    "sniff_override_destination": true,
    "sniff_timeout": "300ms",
    "gso": true
  },
  {
    "type": "direct",
    "listen": "::",
    "listen_port": 53,
    "sniff": true,
    "tag": "dns-in"
  }],

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by nekohasekai** [comment]
Try 1.8.10 or 1.9.0-rc.2
