### ISSUE TITLE
SFA客户端无法选择节点

### ISSUE THREAD

**Issue by tooadstool** [SagerNet/sing-box#1608]
### 操作系统

Android

### 系统版本

Android 13

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.9.0-beta.17

### 描述

当Groups界面前面分组均为Selector，并且Selector数量大于8时，从9个Selector开始，选择节点有bug，选择节点无法生效，并且会导致前面第1-8个Selector的节点变动。并且从第9个Selector开始，当节点足够多时，选择节点会提示“outbound not found in selector: XXXXXX”。详见视频。

https://github.com/SagerNet/sing-box/assets/26811405/35e5c328-416c-4490-9075-a85c6e5dccdc

### 重现方式

当Groups界面前面分组均为Selector，并且Selector数量大于8时，从9个Selector开始，选择节点有bug，选择节点无法生效，并且会导致前面第1-8个Selector的节点变动。并且从第9个Selector开始，当节点足够多时，选择节点会提示“outbound not found in selector: XXXXXX”。

### 支持我们

- [x] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by cap153** [comment]
play商店更新到1.8.9版本同样遇到这个问题，暂时用回1.8.8了

**Comment by Toad-stool** [comment]
已更新问题描述与重现方式，以及视频。 @nekohasekai 麻烦大佬花时间看看

**Comment by guanchan** [comment]
我也遇到这个问题了，1.8.9以后都存在这个问题。还有另一个可能和这个有关联的就是，无法手动选择节点：不管怎么选择，选完后测试IP都是自动选择的节点。我换了两个机场，也在两台不同版本的安卓手机上进行过测试，都是这样。@nekohasekai

**Comment by zqcnbi** [comment]
1.902还是不行

**Comment by kenszx** [comment]
安卓客户端1.9.0-rc.3，类似的问题，国家分组下的节点无法选中，同样的配置在Apple TV，MAC，IOS没有问题，请关注一下安卓APK
![Screenshot_20240401_201258_io nekohasekai sfa](https://github.com/SagerNet/sing-box/assets/89292661/9a85eb85-5926-4070-8e7d-339a0307216d)

**Comment by yanDebug** [comment]
安卓1.8.10存在同样问题

**Comment by tooadstool** [comment]
1.9.0-rc.6版本测试正常。
