### ISSUE TITLE
Sing-box does not route when DNS returns NX domain and inbound domain_strategy is non-empty

### ISSUE THREAD

**Issue by read8873** [SagerNet/sing-box#1615]
### Operating system

Linux

### System version

Ubuntu 22.04

### Installation type

Original sing-box Command Line

### Description

Sing-box does not route when DNS returns NX domain (due to DNS pollution) and inbound domain_strategy is non-empty.

Sing-box should fallback to use domain name and send it to the outbound for resolve in this case.

### Reproduction

```
{
  "dns": {
    "servers": [
      {
        "tag": "google",
        "address": "tls://8.8.8.8"
      },
      {
        "tag": "local",
        "address": "223.5.5.5",
        "detour": "direct"
      }
    ],
    "rules": [
      {
        "outbound": "any",
        "server": "local"
      }
    ],
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
      "type": "tun",
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "strict_route": false,
      "domain_strategy": "prefer_ipv4", // inbound domain_strategy is non-empty
    }
  ],
  "outbounds": [

    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "geoip": [
          "private"
        ],
        "outbound": "direct"
      }
    ],
    "auto_detect_interface": true
  }
}

```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by RS0485** [comment]
I guess this is the build-in behavior of clients(chrome browser for example) but not sing-box. 
When a domain resolves to NXDOMAIN, the browser understands there's no valid IP address.  Therefore, it avoids attempting a connection and displays an error message, no traffic goes to route module on this case.

**Comment by read8873** [comment]
Can sing-box DNS somehow skip NXDOMAIN and use the response from a second DNS server(like fakeip?) in such case?
