### ISSUE TITLE
[iOS] wireguard outbound stop working after turning off the screen

### ISSUE THREAD

**Issue by KdeInit** [SagerNet/sing-box#1626]
### Operating system

iOS

### System version

17.4.1

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.8.10

### Description

WireGuard works fine on startup. But when the iPhone screen turns off and wakes up again, it reject connections.

Related issues:
https://github.com/SagerNet/sing-box/issues/1415
https://github.com/SagerNet/sing-box/issues/1432

### Reproduction

Configure the WireGuard official client as the server
Use sing-box wireguard outbound on the client side
Turn off the screen and turn it back on, now I cannot access the Internet
[sing-box_test.json](https://github.com/SagerNet/sing-box/files/14794636/sing-box_test.json)

### Screenshots of logs
IMG_1 shows a normal connection before turning off the screen
IMG_2 and IMG_3 show abnormal connections after turning off the screen
[IMG_1](https://github.com/SagerNet/sing-box/assets/162863344/64a4173e-f6fb-454d-a423-491a331dbc67)
[IMG_2](https://github.com/SagerNet/sing-box/assets/162863344/1755bcf2-5a34-4c75-a8c9-497323141db0)
[IMG_3](https://github.com/SagerNet/sing-box/assets/162863344/adc4445e-ceaa-4182-af6a-0ecd9718a142)

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by HiHenryLeo** [comment]
me same. how to handle it?sir.

**Comment by amin2plus** [comment]
i have the same issue on my iPad air 2020, i think this is a RAM issue with the app on latest iOS/iPadOS , since most newer iPhones _usually_ doesn't have this issue with the same json config!

**Comment by amin2plus** [comment]
> i have the same issue on my iPad air 2020, i think this is a RAM issue with the app on latest iOS/iPadOS , since most newer iPhones _usually_ doesn't have this issue with the same json config!

update: This issue persists in v1.8.11. When I remove the WireGuard outbound from the configuration, the app functions as expected. 
it seems, if there is any WireGuard outbound in the configuration, the app fails to work after the screen wakes up. however the issue will be resolved if you remove all the WireGuard outbound

**Comment by KdeInit** [comment]
fixed
