### ISSUE TITLE
安卓端国际化支持

### ISSUE THREAD

**Issue by sunlewuyou** [SagerNet/sing-box#1645]
请问Android客户端是否计划添加中文支持？
自行增加中文后有部分下拉选项切换中文会引发异常，看代码是枚举类的问题，是否会修改适配中文？然后有些地方并没有对应的中文翻译，比如下面所示：
![IMG_20240407_032430](https://github.com/SagerNet/sing-box/assets/19728435/027cbf7b-3f93-4477-bbc7-67669a346130)
请问该如何替换中文，谢谢！

**Comment by tooadstool** [comment]
![Screenshot_20240408195242](https://github.com/SagerNet/sing-box/assets/26811405/5d2cef33-6463-4c81-8f93-79412ab5fe5d)


Mode你写什么就是什么，跟翻译有什么关系。

**Comment by tooadstool** [comment]
> > ![Screenshot_20240408195242](https://private-user-images.githubusercontent.com/26811405/320469223-5d2cef33-6463-4c81-8f93-79412ab5fe5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzMyODksIm5iZiI6MTcxMjYzMjk4OSwicGF0aCI6Ii8yNjgxMTQwNS8zMjA0NjkyMjMtNWQyY2VmMzMtNjQ2My00YzgxLThmOTMtNzk0MTJhYjVmZTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAzMjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MTg5YTgyNmVmMjRlYWQ4NTc2MWI2MjQ4MDcwYTU5M2RmZTU3MDhhMDU3ZDMzNWFiMTA2OGUxMDE0OTdhZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kE-5gM5Pn846_neGkGOnMgkThYe7oTEbJ0z4q8FI_Jc)
> > Mode你写什么就是什么，跟翻译有什么关系。
> 
> @tooadstool 你好，不是太明白，请问怎么你的代理模式有6个？不是只有3个固定的吗？

https://sing-box.sagernet.org/configuration/route/rule/#clash_mode

👆官方文档Route Rule里clash mode部分可以再学习一下。

**Comment by Bibabbox** [comment]
> > > ![Screenshot_20240408195242](https://private-user-images.githubusercontent.com/26811405/320469223-5d2cef33-6463-4c81-8f93-79412ab5fe5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzMyODksIm5iZiI6MTcxMjYzMjk4OSwicGF0aCI6Ii8yNjgxMTQwNS8zMjA0NjkyMjMtNWQyY2VmMzMtNjQ2My00YzgxLThmOTMtNzk0MTJhYjVmZTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAzMjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MTg5YTgyNmVmMjRlYWQ4NTc2MWI2MjQ4MDcwYTU5M2RmZTU3MDhhMDU3ZDMzNWFiMTA2OGUxMDE0OTdhZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kE-5gM5Pn846_neGkGOnMgkThYe7oTEbJ0z4q8FI_Jc)
> > > Mode你写什么就是什么，跟翻译有什么关系。
> > 
> > 
> > @tooadstool 你好，不是太明白，请问怎么你的代理模式有6个？不是只有3个固定的吗？
> 
> https://sing-box.sagernet.org/configuration/route/rule/#clash_mode
> 
> 👆官方文档Route Rule里clash mode部分可以再学习一下。

我靠，你知道我找了多久这东西吗？感谢干洗分享啧啧啧
