### ISSUE TITLE
outbound not found in selector

### ISSUE THREAD

**Issue by tangnahuaite** [SagerNet/sing-box#1657]
### Operating system

Android

### System version

Android13

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

SFA1.8.9---SFA1.9.0-rc.4

### Description

SFA1.8.9&1.8.10&1.9.0-rc.1---1.9.0-rc.4 diarrhea update resulted in this bug never being fixed. <#1680> A friend has already mentioned lssue. Now I don't know how to use the new version of SFA. I've moved next door to using mihomo core. I will leave for a while, and if the developers fix this bug in the next iteration, I may come back. Thanks to the developers for their hard work.

### Reproduction

When the groups in front of the Groups interface are all Selectors, and the number of Selectors is greater than 8, starting from 9 Selectors, there is a bug in the selection node, the selection node cannot take effect, and it will cause the nodes of the 1st to 8th Selector to change. And starting from the 9th Selector, when there are enough nodes, the selection node will prompt "outbound not found in selector: XXXXXX".
<img width="682" alt="bug" src="https://github.com/SagerNet/sing-box/assets/75670474/beb18ffb-300a-4eec-9775-10850ca8130b">

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by YoloBird** [comment]
遇到了同样的问题，解决后求踢

**Comment by leic4u** [comment]
I got the same issue either.

**Comment by ccolorcat** [comment]
Same issue
