### ISSUE TITLE
[Feature Request] VPN On Demand for Apple Devices

### ISSUE THREAD

**Issue by uenokatsura** [SagerNet/sing-box#1670]
Hi.
It's pretty annoying to switch on and off SFI when connected to Wi-Fi or Cellular.
So would to great to have On-demand Activation for Apple devices like WireGuard do.
Thanks in advance.

https://developer.apple.com/documentation/networkextension/personal_vpn/vpn_on_demand_rules
![IMG_0010](https://github.com/SagerNet/sing-box/assets/45501123/eea923d6-ae26-4f32-8166-0d711f21d86c)

**Comment by ashton2914** [comment]
> Hi.
> 
> It's pretty annoying to switch on and off SFI when connected to Wi-Fi or Cellular.
> 
> So would to great to have On-demand Activation for Apple devices like WireGuard do.
> 
> Thanks in advance.
> 
> 
> 
> https://developer.apple.com/documentation/networkextension/personal_vpn/vpn_on_demand_rules
> 
> ![IMG_0010](https://github.com/SagerNet/sing-box/assets/45501123/eea923d6-ae26-4f32-8166-0d711f21d86c)
> 
> 

you can use Shortcuts app Automation function to automatic switch sing-box vpn when connected or disconnected Wi-Fi

![image](https://github.com/SagerNet/sing-box/assets/17692778/f25c4c5b-cf2d-44f7-8661-eaca38b95706)
![image](https://github.com/SagerNet/sing-box/assets/17692778/0291b221-2609-494c-b547-5584d8727fe0)
![image](https://github.com/SagerNet/sing-box/assets/17692778/9bfbc2ca-0d4f-4b0d-a060-201b6d60343a)
