### ISSUE TITLE
Failed to request VPN permisson

### ISSUE THREAD

**Issue by leic4u** [SagerNet/sing-box#1675]
### 操作系统

Android

### 系统版本

MIUI 14.0.10 ( Android 13 )

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

Google Play SFA 1.9.0-rc.7

### 描述

点击右下角的启动按钮，提示 Failed to request VPN permission

![Screenshot_2024-04-09-14-40-38-205_io nekohasekai sfa](https://github.com/SagerNet/sing-box/assets/32786903/a172a6d1-8123-47ff-ac3b-eceb5d431815)

### 重现方式

1. 在 MIUI 14 安装 SFA
2. 导入订阅配置
3. 启动配置
4. 出现报错

### 日志

```shell
日志为空
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by leic4u** [comment]
@CHIZI-0618 请问一下还需要提供什么过程步骤吗？我就是安装，导入订阅，启动就报错了。不知道还需要提供什么过程。

**Comment by martint028** [comment]
> @CHIZI-0618 请问一下还需要提供什么过程步骤吗？我就是安装，导入订阅，启动就报错了。不知道还需要提供什么过程。

找到解决办法了，删除掉系统设置里面全部旧的vpn配置，重新开启singbox就行了，安卓的bug
