### ISSUE TITLE
使用DNS地址筛选规则时，设置了server.strategy，结果不符合预期

### ISSUE THREAD

**Issue by ericsyj** [SagerNet/sing-box#1682]
### 操作系统

Android

### 系统版本

Android 13

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.9.0-rc9

### 描述

```
{
    "dns": {
        "servers": [
            {
                "tag": "googledns",
                "address": "h3://8.8.8.8/dns-query",
                "detour": "direct"
            },
            {
                "tag": "alidnsv4",
                "address": "h3://223.6.6.6/dns-query",
                "strategy": "ipv4_only",
                "detour": "direct"
            },
            {
                "tag": "alidnsv6",
                "address": "h3://223.6.6.6/dns-query",
                "strategy": "ipv6_only",
                "detour": "direct"
            }
        ],
        "rules": [
            {
                "rule_set": "geoip-cn",
                "server": "alidnsv4"
            },
            {
                "rule_set": "geoip-cn",
                "server": "alidnsv6"
            }
        ]
    },
    "final": "googledns"
}
```

使用以上配置，只要应用发起任意DNS AAAA请求，均会命中第一条规则，且被拒绝，无法解析到IP。按本人理解，若应用发起DNS AAAA请求，由于没有解析到IP，则不会命中第一条地址筛选规则，应进行后续规则判断，不知道是不是我的理解有误，请大佬看看。

### 重现方式

发起任意DNS AAAA请求，均会命中上述第一条规则，且被拒绝，无法解析到IP

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by Chaxcy** [comment]
在我的理解里，你的规则应该所有解析都会从googledns走。规则指定googledns解析，那不管解没解析出来，都是走googledns，没有回落一说。
