### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [SagerNet/sing-box#1714]
### Operating system

Android

### System version

-

### Installation type

Others

### Version

```shell
1.8.12 ( 323 )
```

### Description

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6726032618#L3696

but the diff log is really small:
```
│ │ │   --- SFA-1.8.12-foss-universal/smali/go/Seq.smali
│ │ ├── +++ io.nekohasekai.sfa_323/smali/go/Seq.smali
│ │ │ @@ -2,21 +2,21 @@
│ │ │  .super Ljava/lang/Object;
│ │ │  .source "SourceFile"
│ │ │  
│ │ │  
│ │ │  # annotations
│ │ │  .annotation system Ldalvik/annotation/MemberClasses;
│ │ │      value = {
│ │ │ -        Lgo/Seq$RefTracker;,
│ │ │ -        Lgo/Seq$GoObject;,
│ │ │ -        Lgo/Seq$GoRefQueue;,
│ │ │ -        Lgo/Seq$Ref;,
│ │ │          Lgo/Seq$RefMap;,
│ │ │          Lgo/Seq$GoRef;,
│ │ │ -        Lgo/Seq$Proxy;
│ │ │ +        Lgo/Seq$GoRefQueue;,
│ │ │ +        Lgo/Seq$RefTracker;,
│ │ │ +        Lgo/Seq$Ref;,
│ │ │ +        Lgo/Seq$Proxy;,
│ │ │ +        Lgo/Seq$GoObject;
│ │ │      }
│ │ │  .end annotation
│ │ │  
│ │ │  
│ │ │  # static fields
│ │ │  .field private static final NULL_REFNUM:I = 0x29
```

### Reproduction

@linsui ever saw this type of diff?

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/c63d456e77d185230a50b29eeae51fa504a4ddf1

**Comment by linsui** [comment]
Yep, I thought this is generated by gomobile. I guess we need to sort something.

**Comment by linsui** [comment]
It seems to be a random issue. https://gitlab.com/linsui/fdroiddata/-/jobs/6726879863

**Comment by linsui** [comment]
I thought this issue is caused by the jdk 11 installed by the last build. https://gitlab.com/fdroid/fdroiddata/-/jobs/6726032618

**Comment by licaon-kter** [comment]
Ah, maybe, feel free to reenable then  👍
