### ISSUE TITLE
Outbound is not a selector

### ISSUE THREAD

**Issue by AzunyanDaisuki** [SagerNet/sing-box#1729]
### 操作系统

Android

### 系统版本

三星One UI version: 5.1, Android version: 13

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.9.0-rc.14

### 描述

URLTest 类型的 outbound 导致弹出提示 Outbound is not a selector
![SmartSelect_20240501_100309_sing-box](https://github.com/SagerNet/sing-box/assets/18110400/4c13c3c6-152c-459f-8d23-37602b2c6a9b)

### 重现方式

配置文件中包含 URLTest 类型的 outbound，在 Groups 页面滑动到这些 outbounds 的时候会弹出错误提示 Outbound is not a selector
这些 outbound 本来就是 URLSelector 类型，只配置了 type, tag, outbounds, url 这几项设置
[test.json](https://github.com/SagerNet/sing-box/files/15172928/test.json)
导入这个配置就可以复现

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by bamboodew** [comment]
我的也是，不影响联网，但弹窗不断，影响操作

**Comment by ccolorcat** [comment]
Me too
