### ISSUE TITLE
undefined: control.BindManager

### ISSUE THREAD

**Issue by Narixius** [SagerNet/sing-box#173]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

Hi there, thank you for this fantastic project!
I'm using this project as a dependency on another project.
And I am facing this error when I run `go mod tidy`

```
ERROR: 
# github.com/sagernet/sing-box/adapter
../../go/pkg/mod/github.com/sagernet/sing-box@v1.0.6/adapter/router.go:34:33: undefined: control.BindManager

exit status 2
```

### Version of sing-box

<details>

```console
$ sing-box version
1.0.6
```
as it is mentioned in the error message
</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by nekohasekai** [comment]
You depend on the stable version of sing-box but depend on the development version of a library.

https://go.dev/ref/mod
