### ISSUE TITLE
'Error while parsing metalink' using dnf package manager

### ISSUE THREAD

**Issue by Hiiirad** [SagerNet/sing-box#1766]
### Operating system

Linux

### System version

Fedora Linux 39 (Workstation Edition) x86_64

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.8.13

Environment: go1.22.2 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: a07c4add78da08e5731257256706a2422e0fd661
CGO: disabled
```

### Description

After running the update command `sudo dnf update --refresh`, I noticed an error message in the log file `/var/log/dnf.librepo.log`. The error message indicates "Error while parsing metalink".

### Reproduction

Install the sing-box application using the instruction below as the [document](https://sing-box.sagernet.org/installation/package-manager/) instructed:

```bash
sudo dnf -y install dnf-plugins-core
sudo dnf config-manager --add-repo https://sing-box.app/sing-box.repo
sudo dnf install sing-box
```

Then, execute the `sudo dnf update --refresh` command to see the warning in the logs file located at: `/var/log/dnf.librepo.log`

### Logs

```shell
2024-05-14T23:30:40+0330 INFO Downloading: https://sing-box.app/sing-box.repo
2024-05-14T23:30:40+0330 WARNING Error while parsing metalink
2024-05-14T23:30:40+0330 WARNING LRO_METALINKURL processing failed: Parse error at line: 1 (Document is empty
)
2024-05-14T23:30:40+0330 INFO Downloading: https://sing-box.app/sing-box.repo
2024-05-14T23:30:41+0330 WARNING Error while parsing metalink
2024-05-14T23:30:41+0330 WARNING LRO_METALINKURL processing failed: Parse error at line: 1 (Document is empty
)
2024-05-14T23:30:41+0330 INFO Downloading: https://rpm.sagernet.org/repodata/repomd.xml
2024-05-14T23:30:42+0330 INFO Downloading: https://rpm.sagernet.org/repodata/repomd.xml.asc
2024-05-14T23:30:43+0330 INFO Downloading: https://rpm.sagernet.org/repodata/primary.xml
2024-05-14T23:30:43+0330 INFO Downloading: https://rpm.sagernet.org/repodata/filelists.xml
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by Fei1Yang** [comment]
Hello. during my tests, both `dnf` and `dnf5` on Fedora Workstation 40 can use the current repo config correctly.

Please try the following steps to see if they can fix your problem:
- Check if you have the old broken repo config which has a `metalink=` line, remove it and try again.
- Fedora 39 which is the oldstable release, as it could be a `dnf` bug, try upgrade to the current stable release.
