### ISSUE TITLE
hysteria: INTERNAL_ERROR: invalid packet

### ISSUE THREAD

**Issue by sougouzhinan** [SagerNet/sing-box#178]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

长时间使用`hysteria`发现: 每隔段时间服务器端日志会出现 `INTERNAL_ERROR: invalid packet` ,导致客户端无法上网,必须重启服务器端sing-box.service才能再次正常使用

### Version of sing-box

<details>

```console
sing-box version 1.1-beta10

Environment: go1.18.5 linux/amd64
Tags: with_quic,with_grpc,with_acme
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```json

```

</details>

### Server and client log file

<details>

```console

```

</details>

**Comment by moranno** [comment]
我这边也发现相同的问题。
