### ISSUE TITLE
Naive 没有出站的配置吗？

### ISSUE THREAD

**Issue by qiumzh** [SagerNet/sing-box#181]
只看到Naive入站配置，没找到Naive出站的配置。请问是不支持Naive出站吗？

**Comment by perfxiao** [comment]
https://sing-box.sagernet.org/faq/#naive-outbound

naive在服务端没有什么特点，主要是客户端部分，实现起来得背着一个cronet库走。后者因为是c写的针对每个平台都得打包一次然后再用cgo包一层，比较麻烦。可能是这个原因大多数跨平台的程序对他的支持都不是很好，sing-box也是。

只是我的猜测，并不是sing-box的开发人员
