### ISSUE TITLE
Unable to connect to hysteria2 using userpass type 

### ISSUE THREAD

**Issue by Hiradpi** [SagerNet/sing-box#1844]
### Operating system

Android , Arch linux LTS 

### System version

latest 

### Installation type

Third-party graphical clients that advertise themselves as using sing-box (Android)

### If you are using a graphical client, please provide the version of the client.

nekobox version 1.2.9 , nekoray  3.26 , sing-box version 1.9.0

### Description

```json 
{
            "domain_strategy": "prefer_ipv4",
            "down_mbps": 0,
            "password": "user1:mypassword",
            "server": "domain",
            "server_port": 443,
            "tag": "proxy",
            "tls": {
                "alpn": "h3",
                "certificate": "",
                "disable_sni": false,
                "enabled": true,
                "insecure": false,
                "server_name": ""
            },
            "type": "hysteria2",
            "up_mbps": 0
}
```
        
        
 outbound config for client i get 403 auth error invalid hash
 
 and servers config (related part)
 ```yml
auth:
  type: userpass  
  userpass:
    user1: mypassword
```

but when i change the type to password and set a password insted of userpass it works fine 

### Reproduction

just try to connect to a hysteria2 server using userpass 

### Logs

`ERROR[0059] [2379516189 1.10s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:35446: authentication failed, status code: 403`

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by CASCfans** [comment]
same issue

**Comment by nekohasekai** [comment]
nekobox and nekoray use a modified fork of sing-box, especially hysteria related protocols. Please open an issue for sing-box itself according to the issue template, or send this issue to the relevant third-party project.
