### ISSUE TITLE
Domain and subdomain rules

### ISSUE THREAD

**Issue by papampi** [SagerNet/sing-box#1868]
### Operating system

Linux

### System version

1.9.3

### Installation type

Original sing-box Command Line

### Description

When using domain rules it does not include sub domains, is this intentional or misbehaviour?

For example if we set direct domain rule for `domain.com` , `sub.domain.com` wont go direct so we should also add a regex for subdomain `^(.*\.)?domain\.com$` too?

Is this the intentional behavior?

### Reproduction

Add domain rule and expect subdomains follow the rule too.

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by BK8000L** [comment]
just use domain_suffix?

**Comment by papampi** [comment]
> just use domain_suffix?

Thanks, I thought domain_suffix is for .ir, .cn, ...
