### ISSUE TITLE
求助，sing-box 不支持 Proxy Protocol 后如何使用NGINX前置分流

### ISSUE THREAD

**Issue by SuperNG6** [SagerNet/sing-box#1878]
如题，求助。
因为服务器用途还挺多的（有些网站在上面，443端口只想给NGINX），现在新版 sing-box 已经不支持 Proxy Protocol ，还有没有其他方法（不想用xray）使用NGINX前置分流？

https://sing-box.sagernet.org/deprecated/

**Comment by SuperNG6** [comment]
> 可以直接分流，不用配置Proxy Protocol

求配置文件参考

**Comment by SuperNG6** [comment]
> > > 可以直接分流，不用配置Proxy Protocol
> > 
> > 
> > 求配置文件参考
> 
> 就是直接配置nginx的stream啊，不支持Proxy Protocol就不配置Proxy Protocol 不如发出你的配置，看看问题在哪里

配置是reality+h2mux，singbox:v1.5.5支持Proxy Protocol，所以nginx 开启Proxy Protocol on，singbox开启 "proxy_protocol": true 后，是可以正常使用的，后续版本的singbox不支持Proxy Protocol，所以nginx sni分流不到singbox的 reality+h2mux端口
```
        {
            "type": "vless",
            "tag": "reality-h2mux",
            "listen": "::",
            "listen_port": 5010,
            "sniff": true,
            "sniff_override_destination": true,
            "users": [
                {
                    "uuid": "",
                    "flow": ""
                }
            ],
            "tls": {
                "enabled": true,
                "server_name": "",
                "reality": {
                    "enabled": true,
                    "handshake": {
                        "server": "",
                        "server_port": 443
                    },
                    "private_key": "",
                    "short_id": [
                        ""
                    ]
                }
            }
        },
```

**Comment by CXwudi** [comment]
顺便提醒一下，sni分流对ws和httpupgrade有效，无论有没有proxy protocol

**Comment by SuperNG6** [comment]
> 我从第一个回复就在说了，不支持Proxy Protocol就不配置它，请问你试过了吗？ 你的nginx的stream字段也发出来。
> 
> 发issue的时候应该附带可以直接复现你描述问题的最小化脱敏配置。

感谢，已解决， sing-box 和nginx 都禁用 Proxy Protocol后成功联通；（不过以前调试配置的时候没有Proxy Protocol是无法使用的，不知道这次为什么成功了。可能是更新到最新版的原因？亦或者是之前配置文件写的不对）

**Comment by SuperNG6** [comment]
> 我从第一个回复就在说了，不支持Proxy Protocol就不配置它，请问你试过了吗？ 你的nginx的stream字段也发出来。
> 
> 发issue的时候应该附带可以直接复现你描述问题的最小化脱敏配置。

感谢，已解决， sing-box 和nginx 都禁用 Proxy Protocol后成功联通；（不过以前调试配置的时候没有Proxy Protocol是无法使用的，不知道这次为什么成功了。可能是更新到最新版的原因？亦或者是之前配置文件写的不对）

**Comment by zxkws** [comment]
> > 我从第一个回复就在说了，不支持Proxy Protocol就不配置它，请问你试过了吗？ 你的nginx的stream字段也发出来。
> > 发issue的时候应该附带可以直接复现你描述问题的最小化脱敏配置。
> 
> 感谢，已解决， sing-box 和nginx 都禁用 Proxy Protocol后成功联通；（不过以前调试配置的时候没有Proxy Protocol是无法使用的，不知道这次为什么成功了。可能是更新到最新版的原因？亦或者是之前配置文件写的不对）

请问可以参考一下配置吗，或者有没有相关教程推荐呀

**Comment by Buer-Nahida** [comment]
@SuperNG6 
> 如题，求助。 因为服务器用途还挺多的（有些网站在上面，443端口只想给NGINX），现在新版 sing-box 已经不支持 Proxy Protocol ，还有没有其他方法（不想用xray）使用NGINX前置分流？
> 
> https://sing-box.sagernet.org/deprecated/

提供个思路，其实如果想要拿到真实 IP 可以在 sing-box 上层套个 HAProxy 消化掉 Proxy Protocol，假如你的 sing-box 开在 50000 端口上，就可以这么写：
```
frontend f_singbox
  bind unix@/run/haproxy/tcp.sock mode 666 accept-proxy
  mode tcp
  default_backend singbox

backend singbox
  mode tcp
  retry-on conn-failure empty-response response-timeout
  server singbox localhost:50000 tfo
```
然后在 nginx 里配置 stream：
```
stream {
  upstream proxy {
      server unix:/run/haproxy/tcp.sock;
  }
  upstream nginx {
      server unix:/run/nginx/http.sock;
  }
 
  map $ssl_preread_server_name $upstream {
    "gateway.icloud.com" proxy;
    default              nginx;
  }
 
  server {
    listen 443      fastopen=256;
    listen [::]:443 fastopen=256;
 
    ssl_preread on;
 
    proxy_protocol         on;
    proxy_socket_keepalive on;
 
    proxy_pass $upstream;
  }
}
```
如果你不怕麻烦，可以尝试配置 nginx 的 IP Transparency，使用 `proxy_bind $upstream transparent;` 启用 nginx 的支持，但还没完，你需要将 nginx 后端监听的 unix socket 改为监听 TCP 端口，如 `localhost:11451`，使用 root 运行 nginx，并配置 nftables 以让流量重新回到 nginx，详情见：https://www.f5.com/company/blog/nginx/ip-transparency-direct-server-return-nginx-plus-transparent-proxy

**Comment by DongLiusuo** [comment]
如果拿不到原始ip，对于reality伪装，会破坏伪装效果吗？

**Comment by Buer-Nahida** [comment]
> 如果拿不到原始ip，对于reality伪装，会破坏伪装效果吗？

不会，只会影响你在日志里看到的 IP 地址，因为源站如果不是你自己的本来就不会接受你发给他的 IP 地址
