### ISSUE TITLE
[Feature Request]: implement splitHttp Transport from xray core v1.8.16

### ISSUE THREAD

**Issue by iamtrazy** [SagerNet/sing-box#1882]
Xray core has announced [splitHttp](https://xtls.github.io/en/config/transports/splithttp.html) which is an alternative transport similar to meek which able to bypass lot of CDN providers  who doesn't support websocket or grpc transport protocols. it is much faster than meek and has almost similar performance to websocket. please consider adding support for this transport protocol for sing-box as well.

**Comment by wendig0x** [comment]
Is there a plan to implement SplitHTTP or not?
