### ISSUE TITLE
请教win10，tun模式下在clash api切换节点不能立即生效，必须重开chrome才行

### ISSUE THREAD

**Issue by ssidef** [SagerNet/sing-box#1886]
我加了"interrupt_exist_connections": true好像没用，请教该如何解决，谢谢

**Comment by yanhao98** [comment]
确实有问题。需要手动断开所有链接。
我是Mac，我测试发现如果是由 "type": "urltest" 切换的节点没有这个问题。"type": "selector" 有问题。
