### ISSUE TITLE
MacOS 14.4 SFM can't edit local profile

### ISSUE THREAD

**Issue by zzhi-github** [SagerNet/sing-box#1909]
### Operating system

macOS

### System version

14.4

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.9.3

### Description

It's not possible to edit the profile contents. After the edition, starting sing-box reports different errors like unknown character "a" or unkown character "\n". 
If I just edit the contents in an editor application, and copy it back to sing-box. The profile can work well.
I suppose something wrong with character set. Not sure if someone had the same issue?

### Reproduction

New a local profile and input new contents in the profile. 
Start the sing-box client with the profile.

### Logs

```shell
(packet-tunnel): Here I stand
(packet-tunnel) error: create service: decode config: invalid character '\n' in string literal: row 311, column 0
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by zzhi-github** [comment]
Does anyone have the same issue here?

**Comment by duskmoon314** [comment]
It seems related to #1909

This is really bothering me.

**Comment by zzhi-github** [comment]
@yanhao98 
I did the same thing like you, only copy&paste can work.
I have to copy the profile to the text editor, and copy it back afterwards. Very annoying.
