### ISSUE TITLE
[Feature Request] script support for the subscribe

### ISSUE THREAD

**Issue by abzdocker** [SagerNet/sing-box#1917]

**Comment by abzdocker** [comment]
**Background**: Most of the time we get the sing-box configuration file through the remote subscription of the airport, but the DNS and diversion rules in the configuration do not meet everyone's needs well. Even if I change the configuration file, the changes I made will be overwritten when the configuration file is updated next time.

**Feature Description:**, I hope to provide a function to parse the configuration file. Through this function, the configuration file finally used is not the configuration file provided by the airport, but the configuration file processed by the script. In this way, all remote configurations can become the configuration files I want, so that sing-box can run according to the rules I set myself.

This function is similar to the script parsing function of clients such as Clash for Windows.
In fact, most of the time, only the node server and other information in the remote file are needed. As for other configurations such as diversion rules and DNS, I hope to run them in my own way.

**Comment by nekohasekai** [comment]
https://github.com/sagerNet/serenity
