### ISSUE TITLE
Request for AmneziaWG Protocol Integration

### ISSUE THREAD

**Issue by tredntredn** [SagerNet/sing-box#1928]
Good day,

I would like to see support for the AmneziaWG protocol, which is essentially WireGuard with additional parameters that enable it to easily bypass restrictions. More details about this can be found on the developer's website https://docs.amnezia.org/documentation/amnezia-wg/
thanks

**Comment by nekohasekai** [comment]
Commercial and unprofessional. They do not have a correct understanding of China's Internet censorship.

**Comment by OmlineEditor** [comment]
> Commercial and unprofessional. They do not have a correct understanding of China's Internet censorship.


please explain in more detail what do you mean?

**Comment by realkarmakun** [comment]
This is very confusing. AmneziaWG - fork of a wireguard protocol with junk packets that make it hard for Passive DPI to infer Wireguard is being used. AmneziaWG protocol is opensource and not commercial. 
https://github.com/amnezia-vpn/amneziawg-go
The small team behind it is selling their protocol as a VPN service, don't see anything wrong with that.
