### ISSUE TITLE
Vless 协议断流

### ISSUE THREAD

**Issue by donnanszex7654** [SagerNet/sing-box#1929]
### 操作系统

Linux

### 系统版本

Ubuntu 22.02

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
1.9.0
```

### 描述

在服务器中使用singbox进行网络代理，进行文件下载（大文件）下载的时候，vless协议会出现下载中断的现象，而使用其他的协议进行下载的时候则不会出现下载中断的现象。同样在安卓端发现有同样的问题。推测可能是下载的时候出现断流的情况导致链接中断出现下载失败的情况。

### 重现方式

singbox配置文件如下https://[raw.githubusercontent.com/donnanszex7654/action/435297c0a1415cdc3ebba20649f7810f5c57b86d/singbox.json](https://raw.githubusercontent.com/donnanszex7654/action/435297c0a1415cdc3ebba20649f7810f5c57b86d/singbox.json)
命令行参考：sing-box run -c path_to_config_file

### 支持我们

- [X] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by Oliver-Yue** [comment]
请提供相关日志

**Comment by nekohasekai** [comment]
****
