### ISSUE TITLE
feature request: singbox selector test url

### ISSUE THREAD

**Issue by m0x61h0x64i** [SagerNet/sing-box#1930]
Hi, In singbox configuration we should have a selector to let user select an outbound but when we have a selector and when user clicks on lightning icon it does not use urltest's url for the ping tests, since in our country the default test url does not work well I want to request that if its possible please let the configuration decide which url test should be used for selector.

OR

It could be best if we let user decide to use which outbound they want to click on and use for urltest type's outbounds.

OR

When users clicks on lightning icon of a selector app decides to use urltest's url for the ping tests.

**Comment by simplerick-simplefun** [comment]
try this logic:

selector: [
   urltestA,
   urltestB
]

urltestA: [
url: AAA.com
outbound1,
outbound2
]

urltestB: [
url: BBB.com
outbound1,
outbound2
]

**Comment by m0x61h0x64i** [comment]
thanks for reply, but nothing changed only one url test added, whats new in this?
