### ISSUE TITLE
[Features] Add process-path data to clash api connections part

### ISSUE THREAD

**Issue by kaniwow** [SagerNet/sing-box#194]
To get a better connections information display, we need process-path information to help us display more useful information

**Comment by kaniwow** [comment]
it's okay if there's a new metadata value named 'process' provided

**Comment by nekohasekai** [comment]
If anyone defines an enhanced crash api specification.

**Comment by kaniwow** [comment]
after turning on the "find_process" option, I've gotten the process_path data, and I've found that the data seems display incorrectly.  I've gotten some data like "\\Device\\HarddiskVolume3\\". Is that a feature or a bug which will be fixed?
