### ISSUE TITLE
The sing-box proxy mode turns on tun mode, which conflicts with docker. Services in the container, such as mysql, cannot be accessed from outside.

### ISSUE THREAD

**Issue by CHAOS-YD** [SagerNet/sing-box#1953]
### Operating system

Linux

### System version

Ubuntu 22.04

### Installation type

Original sing-box Command Line

### Version

```shell
1.9.3
```

### Description

  After turning on the tun mode, the MySQL database in the container cannot be accessed and a connection cannot be established.

### Reproduction

That is, turn on the tun mode proxy, turn off the strict routing mode, connect to the server from ssh, and turn on the tun mode proxy. You cannot use database management tools to connect to it from other clients, such as dbeaver

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by simplerick-simplefun** [comment]
It is the correct and expected behaviour of tun.
Either change the routing rules/tables in your container, or use separate containers for different services and manage the routing rules/tables in the host system.
Or, turn off sing-box config outbound[].tun.auto_route, and manage all the routing manually.
