### ISSUE TITLE
DNS地址筛选不符合预期

### ISSUE THREAD

**Issue by ghost** [SagerNet/sing-box#1965]
### 操作系统

Linux

### 系统版本

OpenWrt 23.05.2

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.10.0-alpha.22
```

### 描述

1，通过dns logical规则筛选结果，首次会返回非预期结果
2，在dns logical中设置client_subnet后，会导致不符合规则的域名查询下一个dns服务器时，仍旧附带此client_subnet，导致结果非预期

### 重现方式

```
[
  {
    "type": "logical",
    "mode": "and",
    "rules": [
      {
        "domain_suffix": "google.com"
      },
      {
        "rule_set": "geoip-cn"
      }
    ],
    "server": "google1",
    "client_subnet": "114.114.114.114"
  }
],
"final": "google"
```

其中google带靠近服务器subnet，google1带223.5.5.5subnet

当logical不配置subnet时，第一次返回非预期结果，后续结果正常
![QQ_1721560014355](https://github.com/user-attachments/assets/33fcc232-cfa9-45ab-8ebd-c45bbee039b9)

当logical配置subnet后，每次结果均返回非预期结果，预期跳过此规则查询默认规则应使用服务器subnet而非这里设置的114subnet
![QQ_1721560155311](https://github.com/user-attachments/assets/db2ebe12-6c89-4319-bb69-1eea57f697a6)

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by nekohasekai** [comment]
应已于 alpha 14 中修复。

**Comment by a1024123** [comment]
@nekohasekai 未修复，还产生了新的问题
当筛选规则设置subnet后，跳过查询默认服务器时，还是会携带此subnet
![QQ_1721910415033](https://github.com/user-attachments/assets/ba454d83-a648-4987-863c-849a938909f6)
当筛选规则未设置subnet，问题依旧，且跳过查询默认服务器时，**直接忽略了默认服务器的subnet**
![QQ_1721910758106](https://github.com/user-attachments/assets/1036b800-d34c-4505-a87a-1b09ecf66e91)

**Comment by a1024x** [comment]
@nekohasekai 而且现在好像dns服务器设置的subnet均失效
dns筛选未设置subnet时，只有第一次不匹配时会有subnet，其他情况查询均没有subnet
![QQ_1721916076819](https://github.com/user-attachments/assets/03035c05-284d-41e7-9492-c54c011759ca)
