### ISSUE TITLE
Android下同局域网设备无法访问这台Android

### ISSUE THREAD

**Issue by w311ang** [SagerNet/sing-box#1968]
### 操作系统

Android

### 系统版本

12

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.10.0-alpha.22

### 描述

开启tun代理情况下，例如MT管理器开启远程管理监听0.0.0.0，但是同局域网Windows却无法访问，在tun中的route_exclude_address添加192.168.0.0/16确实可以解决这个问题，但是会造成DNS服务器为路由器时的DNS泄漏

### 重现方式

```json
{
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "address": [
        "172.18.0.1/30",
        "fdfe:dcba:9876::1/126"
      ],
      "auto_route": true,
      "strict_route": true,
      "sniff": true
    }
  ]
}
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by simplerick-simplefun** [comment]
route_exclude_address添加需要排除代理的IP即可（电脑）。或者route.rules[]里面将需要的目标IP设为直连（电脑和手机）。
这是tun的正常运行模式，不是bug。

**Comment by w311ang** [comment]
我看了下无论是clash还是sagernet对于请求路由器DNS都是直连，是我多虑了

**Comment by w311ang** [comment]
> route_exclude_address添加需要排除代理的IP即可（电脑）。或者route.rules[]里面将需要的目标IP设为直连（电脑和手机）。 这是tun的正常运行模式，不是bug。

但是A仅仅在route.rules[]添加进要直连的目标IP仍无法让目标IP主机访问A

**Comment by simplerick-simplefun** [comment]
> > route_exclude_address添加需要排除代理的IP即可（电脑）。或者route.rules[]里面将需要的目标IP设为直连（电脑和手机）。 这是tun的正常运行模式，不是bug。
> 
> 但是A仅仅在route.rules[]添加进要直连的目标IP仍无法让目标IP所在主机访问A，只有在route_exclude_address中添加才可以让目标IP所在主机访问A

是的，设置route直连不行。因为经过sing-box代理的直连会导致通信端口改变。如果你手机是安卓，可以设置tun.exclude_package或tun.exclude_uid来排除掉需要提供网络服务的app。如果是苹果，就只能用tun.exclude_address。

**Comment by SuperKenVery** [comment]
请问一下tun为什么会这样呢？strict route和dns泄漏和局域网访问在安卓上是什么关系呢？

**Comment by w311ang** [comment]
> 请问一下tun为什么会这样呢？strict route和dns泄漏和局域网访问在安卓上是什么关系呢？

我在这里看到应用在创建vpn时是可以指定dns的，可能就是因为这个所以才没有泄漏吧
"addDnsServer"
https://developer.android.com/develop/connectivity/vpn#:~:text=)%0A%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20.-,addDnsServer,-(%22192.168.1.1%22

**Comment by ElvenP** [comment]
我之前也有这个问题。一直不知道怎么解决。看了你这个终于知道怎么解决了。但是我还有一个疑问，在这种情况下。手机却能访问电脑上的服务比如alist 的5244。电脑 却不能访问手机上的alist的5244.这个是什么原理呢。
