### ISSUE TITLE
🌹建议安卓能添加“从最近任务中隐藏”来防止误杀后台

### ISSUE THREAD

**Issue by HiHenryLeo** [SagerNet/sing-box#1969]
### Operating system

Android

### System version

14

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.9.3

### Description

建议安卓能添加“从最近任务中隐藏”来防止误杀后台

### Reproduction

建议，安卓能添加“从最近任务中隐藏”来防止误杀后台

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by HiHenryLeo** [comment]
sing-box is a good tool

**Comment by simplerick-simplefun** [comment]
这种功能需要root，或root衍生的magisk module/xposed之类的方法。
如果已经root，可以自行搜索工具隐藏其他应用的后台。或直接使用模块运行命令行的sing-box。

**Comment by yaohuow** [comment]
> 这种功能需要root，或root衍生的magisk module/xposed之类的方法。 如果已经root，可以自行搜索工具隐藏其他应用的后台。或直接使用模块运行命令行的sing-box。

应该不需要吧，GKD中的就不需要Root权限 https://github.com/gkd-kit/gkd
