### ISSUE TITLE
different from xray TCP + HTTP (head)

### ISSUE THREAD

**Issue by sadeepa24** [SagerNet/sing-box#1977]
### Operating system

Windows

### System version

10

### Installation type

Original sing-box Command Line

### Version

```shell
1.9.3
```

### Description

  {
      "type": "vless",
      "tag": "D_zero",
      "server": "<ip>",
      "server_port": 80,
      "uuid": "<uuid>",
      "transport": {
        "type": "http",
        "host": ["host"],
        "path": "/",
        "method": "HEAD",
        "headers": {
          "Host": "host"
        },
        "idle_timeout": "15s",
        "ping_timeout": "15s"
      }
    },

when I connect to this oubound after tcp auth http requsts does not reach the server. But I connect same config with Xray core I can connect with the server (also my server is running on sing-box)

I tried in many ways but I go the same result.

you can also check above screenshot of wireshark sing-box vs xray(client side)
 
![Screenshot (461)](https://github.com/user-attachments/assets/15ae09cc-14f5-49db-a640-18fe9d544124)

### Reproduction

Server Inbound
 {
      "sniff": true,
      "sniff_override_destination": false,
      "sniff_timeout": "500ms",
      "type": "vless",
      "tag": "vless-in",
      "listen": "::",
      "listen_port": 80,
      "tcp_fast_open": true,
      "users": [
        {
          "name": "any",
          "uuid": "<you'r uuid>"
        }
      ],
      "transport": {
        "type": "http",
        "host": ["<any_host>"],
        "path": "/",
        "method": "HEAD",
        "idle_timeout": "15s",
        "ping_timeout": "15s"
      }
    }

By the way server side is working perfectly

Client Outbound
   {
      "type": "vless",
      "tag": "D_zero",
      "server": "<server_ip>",
      "server_port": 80,
      "uuid": "<you'r uuid>",
      "transport": {
        "type": "http",
        "host": ["<any_host>"],
        "path": "/",
        "method": "HEAD",
        "headers": {
          "Host": "<any_host>"
        },
        "idle_timeout": "15s",
        "ping_timeout": "15s"
      }
    }

equant xray outbound for sing-box above outbound is downhere
  {
      "mux": {
        "concurrency": -1,
        "enabled": false,
        "xudpConcurrency": 8,
        "xudpProxyUDP443": ""
      },
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": ""<server_ip>",
            "port": 80,
            "users": [
              {
                "encryption": "none",
                "flow": "",
                "id": "9559d583-3825-4015-844e-1a6dce3772b9",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "",
        "tcpSettings": {
          "header": {
            "request": {
              "headers": {
                "Host": ["edge-mqtt-mini-shv-01-bom2.facebook.com"],
              },
              "method": "HEAD",
              "path": [
                "/"
              ],
              "version": "1.1"
            },
            "type": "http"
          }
        }
      },
      "tag": "proxy"
    },

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [x] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by sadeepa24** [comment]
what I want is working sing-box client exactly as xray client in this case

**Comment by nekohasekai** [comment]
Read the documentation.

**Comment by sadeepa24** [comment]
if its not gonna fix. that's okay
