### ISSUE TITLE
[Feature Request] Support custom port of DNS servers

### ISSUE THREAD

**Issue by ftiasch** [SagerNet/sing-box#1989]
I have sing-box and [smartdns](https://github.com/pymumu/smartdns) running on my router, where smartdns is used to choose the fastest IP for domestic domains. Since sing-box doesn't support ports other than the default 53 yet, I cannot use smartdns as the upstream server for sing-box. 

I think it could be nice to support this.

**Comment by simplerick-simplefun** [comment]
use iptables/nftables NAT the packet to the desired port? dnat the packet from sing-box to smartdns, and snat the packet back.

**Comment by yanhao98** [comment]
支持的吧？
```
"address": "127.0.0.1:553"
```

**Comment by ftiasch** [comment]
> 支持的吧？
> 
> ```
> "address": "127.0.0.1:553"
> ```

I tried, it seems to succeed. 

Would it be better to document the usage in https://sing-box.sagernet.org/configuration/dns/server/#address?

**Comment by nrjycyd** [comment]
smartdns+singbox 的配置，可以分享下吗大神
