### ISSUE TITLE
Sing-box crashes when updating remote ruleset is not possible

### ISSUE THREAD

**Issue by molink36** [SagerNet/sing-box#1997]
Sing-box crashes when updating remote ruleset is not possible (for example if the computer which sing-box is running on, is offline or if the website which is providing the ruleset is not accessible). One suggestion is that in these circumstances the previous cached ruleset be used, until the next update interval.

Is there any workaround for this with the current possible configurations for Sing-box?

**Comment by OmlineEditor** [comment]
tell me, has the problem been solved in the new versions, or has the ticket been closed and the problem remains unresolved?
