### ISSUE TITLE
"fatal error: too many callback functions" after too many box.New() instance initialized and started then closed

### ISSUE THREAD

**Issue by bayard** [SagerNet/sing-box#2006]
### Operating system

Windows

### System version

Windows 11

### Installation type

Others

### Description

I am developing a Windows App which introduce "github.com/sagernet/sing-box" package using Golang.

I use a loop to initialized a *box.Box instance using box.New(), start it by calling instance.Start(), then do a http client connection test, finally call instance.Close() at the end of the loop. After about 1997 times iterations, app crashed with panic of "fatal error: too many callback functions".

Pseudo code:
`
for idx, ipEntry := range ip_pool {
		server_ip := ipEntry[0]
		server_port, _ := strconv.Atoi(ipEntry[1])
		if server_port > 0 {
			server_tls := true
			uuid := "uuid"
			sni := "sni"
			wshost := "ws_host"
			wspath := "ws_path"
			config_json, _ := sb_config_from_json()
			var from_json option.Options
			from_json.UnmarshalJSON([]byte(config_json))

			ctx := context.WithoutCancel(context.Background())

			var instance *box.Box
			instance, err = box.New(box.Options{
				Context: ctx,
				Options: from_json,
			})
			if err != nil {
				log.Printf("New box error")
				panic(err)
			}

			err = instance.Start()
			if err != nil {
				log.Println("Box starting error")
				// panic with "fatal error: too many callback functions" after 1997 iterations
				panic(err)
			}

			http_result := sb_http_client_test()

			instance.Close()
		}
	}
`

I do some google searches and found the article [https://stackoverflow.com/questions/66864829/golang-fatal-error-too-many-callback-functions](url), the crash was caused by Windows callback handling mechanism and Golang codebase hardcoded limitation of callback functions.

The crash stack:
`
#1997 iteration: x.x.x.x:443
trojan server: x.x.x.x:443
ws: host=/?ed=2560, path=[xxxx.com]
fatal error: too many callback functions

goroutine 1 [running]:
runtime.throw({0x16add8a?, 0xc000046000?})
        C:/dev/Go/src/runtime/panic.go:1077 +0x65 fp=0xc000b48838 sp=0xc000b48808 pc=0xe49cc5
syscall.compileCallback({0x159cda0?, 0xc002610250?}, 0x20?)
        C:/dev/Go/src/runtime/syscall_windows.go:338 +0x485 fp=0xc000b48938 sp=0xc000b48838 pc=0xe7a925
syscall.NewCallback(...)
        C:/dev/Go/src/syscall/syscall_windows.go:214
golang.org/x/sys/windows.NewCallback(...)
        C:/Users/xxxx/go/pkg/mod/golang.org/x/sys@v0.22.0/windows/syscall_windows.go:137
github.com/sagernet/sing/common/winpowrprof.NewEventListener(0xc002610230)
        C:/Users/xxxx/go/pkg/mod/github.com/sagernet/sing@v0.4.1/common/winpowrprof/event_windows.go:59 +0x91 fp=0xc000b48968 sp=0xc000b48938 pc=0x1495d11
github.com/sagernet/sing-box/route.(*Router).Start(0xc0025d7600)
        C:/Users/xxxx/go/pkg/mod/github.com/sagernet/sing-box@v1.9.3/route/router.go:513 +0x3c9 fp=0xc000b48b38 sp=0xc000b48968 pc=0x149e1e9
github.com/sagernet/sing-box.(*Box).preStart(0xc003a84c80)
        C:/Users/xxxx/go/pkg/mod/github.com/sagernet/sing-box@v1.9.3/box.go:273 +0x9f3 fp=0xc000b48cd8 sp=0xc000b48b38 pc=0x14fd273
github.com/sagernet/sing-box.(*Box).start(0xc003a84c80)
        C:/Users/xxxx/go/pkg/mod/github.com/sagernet/sing-box@v1.9.3/box.go:277 +0x2a fp=0xc000b48e70 sp=0xc000b48cd8 pc=0x14fd5aa
github.com/sagernet/sing-box.(*Box).Start(0xc003a84c80)
        C:/Users/xxxx/go/pkg/mod/github.com/sagernet/sing-box@v1.9.3/box.go:219 +0x36 fp=0xc000b48f00 sp=0xc000b48e70 pc=0x14fc496
main.do_real_proxy_test()
        D:/git/cfip/cf_ping/cf_ping.go:596 +0x896 fp=0xc000b4bed8 sp=0xc000b48f00 pc=0x1521776
main.main()
        D:/git/cfip/cf_ping/cf_ping.go:672 +0x13 fp=0xc000b4bf40 sp=0xc000b4bed8 pc=0x1521ed3
runtime.main()
        C:/dev/Go/src/runtime/proc.go:267 +0x2b2 fp=0xc000b4bfe0 sp=0xc000b4bf40 pc=0xe4c512
runtime.goexit()
        C:/dev/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000b4bfe8 sp=0xc000b4bfe0 pc=0xe7e401

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/dev/Go/src/runtime/proc.go:398 +0xce fp=0xc000081fa8 sp=0xc000081f88 pc=0xe4c94e
runtime.goparkunlock(...)
        C:/dev/Go/src/runtime/proc.go:404
runtime.forcegchelper()
        C:/dev/Go/src/runtime/proc.go:322 +0xb8 fp=0xc000081fe0 sp=0xc000081fa8 pc=0xe4c7b8
runtime.goexit()
        C:/dev/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000081fe8 sp=0xc000081fe0 pc=0xe7e401
created by runtime.init.6 in goroutine 1
        C:/dev/Go/src/runtime/proc.go:310 +0x1a
`

Is it possible to modified callback mechanism in sing-box codebase to reuse callbacks to avoid hitting the Golang limitation? 

Thanks!

### Reproduction

2000 times iterations of 
`
{
  instance := New(Box...)
  instance.Start()
  ...
  instance.Stop()
}
`

### Logs

```shell
#1997 iteration: x.x.x.x:443
trojan server: x.x.x.x:443
ws: host=/?ed=2560, path=[xxxx.com]
fatal error: too many callback functions

goroutine 1 [running]:
runtime.throw({0x16add8a?, 0xc000046000?})
        C:/dev/Go/src/runtime/panic.go:1077 +0x65 fp=0xc000b48838 sp=0xc000b48808 pc=0xe49cc5
syscall.compileCallback({0x159cda0?, 0xc002610250?}, 0x20?)
        C:/dev/Go/src/runtime/syscall_windows.go:338 +0x485 fp=0xc000b48938 sp=0xc000b48838 pc=0xe7a925
syscall.NewCallback(...)
        C:/dev/Go/src/syscall/syscall_windows.go:214
golang.org/x/sys/windows.NewCallback(...)
        C:/Users/xxxx/go/pkg/mod/golang.org/x/sys@v0.22.0/windows/syscall_windows.go:137
github.com/sagernet/sing/common/winpowrprof.NewEventListener(0xc002610230)
        C:/Users/xxxx/go/pkg/mod/github.com/sagernet/sing@v0.4.1/common/winpowrprof/event_windows.go:59 +0x91 fp=0xc000b48968 sp=0xc000b48938 pc=0x1495d11
github.com/sagernet/sing-box/route.(*Router).Start(0xc0025d7600)
        C:/Users/xxxx/go/pkg/mod/github.com/sagernet/sing-box@v1.9.3/route/router.go:513 +0x3c9 fp=0xc000b48b38 sp=0xc000b48968 pc=0x149e1e9
github.com/sagernet/sing-box.(*Box).preStart(0xc003a84c80)
        C:/Users/xxxx/go/pkg/mod/github.com/sagernet/sing-box@v1.9.3/box.go:273 +0x9f3 fp=0xc000b48cd8 sp=0xc000b48b38 pc=0x14fd273
github.com/sagernet/sing-box.(*Box).start(0xc003a84c80)
        C:/Users/xxxx/go/pkg/mod/github.com/sagernet/sing-box@v1.9.3/box.go:277 +0x2a fp=0xc000b48e70 sp=0xc000b48cd8 pc=0x14fd5aa
github.com/sagernet/sing-box.(*Box).Start(0xc003a84c80)
        C:/Users/xxxx/go/pkg/mod/github.com/sagernet/sing-box@v1.9.3/box.go:219 +0x36 fp=0xc000b48f00 sp=0xc000b48e70 pc=0x14fc496
main.do_real_proxy_test()
        D:/git/cfip/cf_ping/cf_ping.go:596 +0x896 fp=0xc000b4bed8 sp=0xc000b48f00 pc=0x1521776
main.main()
        D:/git/cfip/cf_ping/cf_ping.go:672 +0x13 fp=0xc000b4bf40 sp=0xc000b4bed8 pc=0x1521ed3
runtime.main()
        C:/dev/Go/src/runtime/proc.go:267 +0x2b2 fp=0xc000b4bfe0 sp=0xc000b4bf40 pc=0xe4c512
runtime.goexit()
        C:/dev/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000b4bfe8 sp=0xc000b4bfe0 pc=0xe7e401

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/dev/Go/src/runtime/proc.go:398 +0xce fp=0xc000081fa8 sp=0xc000081f88 pc=0xe4c94e
runtime.goparkunlock(...)
        C:/dev/Go/src/runtime/proc.go:404
runtime.forcegchelper()
        C:/dev/Go/src/runtime/proc.go:322 +0xb8 fp=0xc000081fe0 sp=0xc000081fa8 pc=0xe4c7b8
runtime.goexit()
        C:/dev/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000081fe8 sp=0xc000081fe0 pc=0xe7e401
created by runtime.init.6 in goroutine 1
        C:/dev/Go/src/runtime/proc.go:310 +0x1a
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/304031d75c31b3c2506ca153cb820097034edfd0

**Comment by bayard** [comment]
> Try [3b6518f](https://github.com/SagerNet/sing-box/commit/3b6518f1e9c37a75d2c649797b32511b8962f0bf)

Issue fixed confirmed! Thanks!
