### ISSUE TITLE
无法在 iOS App Store 中下载 sing-box 客户端

### ISSUE THREAD

**Issue by s-leeq** [SagerNet/sing-box#2024]
### 操作系统

iOS

### 系统版本

17.3.1

### 安装类型

sing-box for iOS 图形客户端程序

### 描述

无法通过任何方式在 App Store 中下载 sing-box 应用，请问是需要开发者在后台重新提交审核或者其他操作吗？

### 重现方式

通过 [sing-box 官网](https://sing-box.sagernet.org/clients/apple/)给出的[App Store链接](https://apps.apple.com/us/app/sing-box/id6451272673)，在马来西亚、土耳其、美国地区的App Store中均提示未在该国家上架；

通过 App Store 内搜索 `sing-box` 关键词得到的内容均为无关项；

通过 Apple ID 的已购买项目中下载时提示 `This item is being modified. Please try again later.`。

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by shadowwider** [comment]
me too

**Comment by ponyspy** [comment]
Confirm. Not available on all apple platforms.

**Comment by riitax** [comment]
一样的

**Comment by zacred0rryn** [comment]
https://t.me/yapnc/249

**Comment by ponyspy** [comment]
Maybe place SFI build (without sign) in releases section to simplify [sideloading](https://sideloadly.io)?

**Comment by zhthy** [comment]
官方TG群公告：Due to problems with our Apple developer account, sing-box apps on Apple platforms are temporarily unavailable for download or update. We estimate that it may take more than a month to resolve this issue.

**Comment by s-leeq** [comment]
感谢，前面已经有朋友提及了，在重新上架后会关闭此issue
