### ISSUE TITLE
服务端屏蔽 geoip CN 命中 1.1.1.1

### ISSUE THREAD

**Issue by lvii** [SagerNet/sing-box#2025]
### Operating system

Linux

### System version

CentOS

### Installation type

Original sing-box Command Line

### Version

```
sing-box version 1.9.3

Environment: go1.22.3 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: 085f60337799afc906069b540a38368968c123e4
CGO: disabled
```

### Description

服务端屏蔽 CN GEOIP 会将 1.1.1.1 请求 **block 掉** ；如果增加 1.1.1.1 直连规则是可以的。

服务端配置：

```json
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    },
    {
      "type": "block",
      "tag": "block"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      // {
      //   "ip_cidr": [ "1.1.1.1" ],
      //   "outbound": "direct"
      // },
      {
        "rule_set": [ "geoip-cn" ],
        "domain_suffix": [ ".cn" ],
        "outbound": "block"
      }
    ],
    "rule_set": [
      {
        "tag": "geoip-cn",
        "type": "remote",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs",
        "download_detour": "direct"
      }
    ]
  }
```
### Reproduction

日志：

```
INFO[0051] [3880622932 0ms] inbound/tuic[0]: [home] inbound connection to 1.1.1.1:443
DEBUG[0051] [3880622932 0ms] router: match[1] domain_suffix=.cn rule_set=geoip-cn => block
INFO[0051] [3880622932 0ms] outbound/block[block]: blocked connection to 1.1.1.1:443
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by scplay** [comment]
1.1.1.1 在 geoip 中的 Location 不是空吗？为什么会被会到 cn 里面呢
