### ISSUE TITLE
Support bind_address both ipv4 and ipv6

### ISSUE THREAD

**Issue by sougouzhinan** [SagerNet/sing-box#203]
Outbounds Dial Fields

```json
"bind_address_ipv4": "127.0.0.1" //send all ipv4 traffic through 127.0.0.1
"bind_address_ipv6": "::1" //send all ipv4 traffic through ::1
```

        bind_outbound 能同时绑定ipv6和ipv4吗？ 我发现DNS那里没办法设置ipv6 dns.

_Originally posted by @liuxyon in https://github.com/HyNetwork/hysteria/issues/375#issuecomment-1182838717_

**Comment by nekohasekai** [comment]
Try f1c6b35c37e2d0f7886fdc9650ce84b836f1eecf
