### ISSUE TITLE
安卓app：tun inbound使用route_exclude_address时报错，无法运行vpn

### ISSUE THREAD

**Issue by simplerick-simplefun** [SagerNet/sing-box#2030]
### 操作系统

Android

### 系统版本

Android 13

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.10.0-alpha.29

### 描述

使用环境：
Android 13
SFA-1.10.0-alpha.29-arm64-v8a.apk

问题：
在tun inbound里，如果写入route_exclude_address/inet4_route_exclude_address/inet6_route_exclude_address，那么启动vpn时，会报错弹出窗口：initialize inbound/tun[in-tun]: configure tun interface: Bad address
报错截图：
![Screenshot_2024-08-16-16-43-47-453_com tencent mm-edit](https://github.com/user-attachments/assets/47fef036-1209-4c1c-8290-5d24ce7c1097)

配置：
```
"inbounds": [
    {
      "type": "tun",
      "tag": "in-tun",
      "inet4_address": [
        "172.19.0.1/30"
      ],
      "inet6_address": [
        "fdfe:dcba:9876::1/126"
      ],
      "stack": "gvisor",
      "auto_route": true,
      "strict_route": true,
      "endpoint_independent_nat": true,
      "sniff": true,
      "sniff_timeout": "100ms",
      "inet4_route_exclude_address": [
        "127.0.0.0/16"
      ],
      "inet6_route_exclude_address": [
        "fc00::/7"
      ]
    }
]
```
或
```
"inbounds": [
    {
      ......
      "route_exclude_address": [
        "127.0.0.0/16",
        "fc00::/7"
      ]
    }
]
```

### 重现方式

在tun inbound里，如果写入route_exclude_address/inet4_route_exclude_address/inet6_route_exclude_address。

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by kicre** [comment]
1.11.4 同样的问题，同时在windows裸核运行没有问题。

**Comment by kicre** [comment]
@

> 1.11.4 同样的问题，同时在windows裸核运行没有问题。

` 127.0.0.0/16 ` 这一条地址不能用，删除后就好了。

**Comment by astramare** [comment]
我也碰到了，版本号 v1.14.0-alpha.31

原因是：inbounds.route_exclude_address 不能包含回环地址。

> IPv4 回环地址：`127.0.0.0/8`
> IPv6 回环地址：`::1/128`

目前已知：Windows 没有这个限制，只有 Android 不要放这两个回环地址就能正常启动。
