### ISSUE TITLE
Appstore can not find and download sing-box app

### ISSUE THREAD

**Issue by mrbin22** [SagerNet/sing-box#2032]
### Operating system

iOS

### System version

16

### Installation type

sing-box for iOS Graphical Client

### Description

i need reinstall sing-box but appstore can not see app

### Reproduction

nothing

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by CHIZI-0618** [comment]
Duplicated from https://github.com/SagerNet/sing-box/issues/2024

**Comment by noobkar** [comment]
Apple Reviewers are such a piece of shit
