### ISSUE TITLE
route_exclude_address_set 在 android 上不工作

### ISSUE THREAD

**Issue by moosetk** [SagerNet/sing-box#2034]
### Operating system

Android

### System version

Android 14

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box-1.10.0-alpha.29-android-arm64
```

### Description

route_exclude_address_set 在 android 上不工作，无论是 termux 用命令行跑，或者 SFA 客户端都不工作，ip规则集里的地址仍然会走 tun 入栈。而 route_exclude_address / inet4_route_exclude_address / inet6_route_exclude_address 是正常的。"auto_route": true 。

### Reproduction

```
"route_exclude_address_set": [
				"moose-bypass",
				"geoip-cn"
			],
```

### Logs

```shell
inbound/tun[tun-in]: connection closed: download: read tcp ***(已在规则集中的ip):***->***:***: use of closed network connection | upload: io: read/write on closed pipe
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by CHIZI-0618** [comment]
安卓没有 ipset

**Comment by danya0123** [comment]
route_exclude_address_set 如果是基于ipset实现的，是不是独立出来更好？

singbox配置只需要能提供ip列表给内核即可，用户可以自己编写sh脚本实现tun/tproxy/redirct等功能，尤其是在路由器等接口情况比较复杂时。
