### ISSUE TITLE
SingBoxV1.9.3 Android unsupported "DustinWin/ruleset_geodata" version 2

### ISSUE THREAD

**Issue by github-faning-net** [SagerNet/sing-box#2041]
### Operating system

Android

### System version

14

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.9.3

### Description

When using file [https://github.com/DustinWin/ruleset_geodata/releases/download/sing-box-ruleset/cnip.srs](https://github.com/DustinWin/ruleset_geodata/releases/download/sing-box-ruleset/cnip.srs),

SingBoxV1.9.3 Android's Logs output:

>   ERROR router: fetch rule-set cnip: unsupported version: 2

### Reproduction

1. `route.rule_set` field in `config.json` contains
```json
{
  "tag": "cnip",
  "type": "remote",
  "format": "binary",
  "url": "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/sing-box-ruleset/cnip.srs"
 }
```
2. Start Sing-Box App

### Logs

```shell
ERROR router: fetch rule-set cnip: unsupported version: 2
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
Report your issue to DustinWin/ruleset_geodata
