### ISSUE TITLE
1.10.0-beta.1 启动运行一段时间会报错退出

### ISSUE THREAD

**Issue by zcluo** [SagerNet/sing-box#2043]
### 操作系统

Linux

### 系统版本

openwrt 23.05

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
1.10.0-beta.1
```

### 描述

1.10.0-beta.1版本在op下在auto_redirect模式下跑一段时间报错退出，同样的配置之前的[1.10.0-alpha.29](https://github.com/SagerNet/sing-box/releases/tag/v1.10.0-alpha.29)没有这个问题

### 重现方式

每次重跑后隔段时间，差不多几分钟就复现。

### 日志

```shell
goroutine 883 [running]:
github.com/sagernet/sing/common/pipe.(*Deadline).Set.func1()
	github.com/sagernet/sing@v0.5.0-alpha.18/common/pipe/pipe.go:58 +0x1b
created by time.goFunc
	time/sleep.go:177 +0x2d
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by tx-anin** [comment]
ProductName: macOS
ProductVersion: 14.6.1
BuildVersion: 23G93

**Comment by tx-anin** [comment]
ProductName: macOS
ProductVersion: 14.6.1
BuildVersion: 23G93
也出现类似问题
