### ISSUE TITLE
[Question] What apk FOSS variant difference?

### ISSUE THREAD

**Issue by SilmorSenedlen** [SagerNet/sing-box#2048]
Good day
I don't find any description about FOSS variant of APK releases.

1) What differences between  SFA-1.9.4-foss-universal.apk and SFA-1.9.4-universal.apk ?

2) Are other APKs (arm64-v8a / armeabi-v7a / x86 / x86_64) non-FOSS ?

**Comment by nekohasekai** [comment]
The default version includes QR code scanning implemented by mlkit, and checking for updates implemented by play services, which are non-free. The foss version does not include these features, and is a reproducible compiled apk to be submitted to F-Droid.

**Comment by SilmorSenedlen** [comment]
@nekohasekai thank you for explanation!
