### ISSUE TITLE
documentation bug: centos/yum should be merged with redhat/dnf

### ISSUE THREAD

**Issue by Artoria2e5** [SagerNet/sing-box#2049]
### Operating system

Linux

### System version

CentOS Stream 9

### Installation type

Original sing-box Command Line

### Description

https://sing-box.sagernet.org/installation/package-manager/#__tabbed_1_3 still has a CentOS/yum selection. Currently supported versions of CentOS are identical to RHEL in that there is only dnf.

### Reproduction

Click on the link!

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
Would you like to open a pull request?
