### ISSUE TITLE
[功能请求]支持同一个dns server下配置多个dns地址进行负载均衡，以解决dns的频率限制问题。

### ISSUE THREAD

**Issue by raybinson** [SagerNet/sing-box#2054]
### 操作系统

其他

### 系统版本

All

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.9.4
```

### 描述

由于阿里云开始限制doh的查询频率，希望能在dns server的配置中提供配置多个dns地址进行负载均衡的能力。这样可以在一个dns server里面去增加诸如腾讯云的dns查询来减少因为doh服务器频率限制带来的性能问题。

### 重现方式

无。

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by senkiss** [comment]
加大CACHE不就可以了
