### ISSUE TITLE
TUN 中同时启用 route_exclude_address_set 和 exclude_uid 时后者无法生效

### ISSUE THREAD

**Issue by doveccl** [SagerNet/sing-box#2059]
### 操作系统

Linux

### 系统版本

Debian 12

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.10.0-beta.4

Environment: go1.23.0 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: 68ec00aaa5a20f1adbf9dfb56804ee2e0c4d0671
CGO: disabled
```

### 描述

TUN 中同时开启 route_exclude_address_set 和 exclude_uid
使用对应 uid 发起请求仍然可以看到 sing-box 中有相关请求日志
并且 nftables 中 skuid 那一行的 counter 始终为 0
复现方式和日志贴在后面

另外还有一个 nftables 相关的问题是，sing-box 会把 counter 放在 dnat 指令之后
导致 dns 53 hijack 那几行的统计 counter 永远是 0（功能上不会受影响）

### 重现方式

创建配置文件 `test.json`
```json
{
  "dns": {
    "servers": [{ "address": "local" }]
  },
  "inbounds": [
    {
      "type": "tun",
      "auto_route": true,
      "auto_redirect": true,
      "exclude_uid": [1000],
      "route_exclude_address_set": ["ip:cn"],
      "address": ["172.18.0.1/30"]
    }
  ],
  "outbounds": [
    { "tag": "direct", "type": "direct" },
    { "tag": "dns", "type": "dns" }
  ],
  "route": {
    "auto_detect_interface": true,
    "rules": [{ "protocol": "dns", "port": [53, 853], "outbound": "dns" }],
    "rule_set": [
      {
        "tag": "ip:cn",
        "type": "remote",
        "format": "binary",
        "url": "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/srs/cn.srs"
      }
    ]
  }
}
```
使用 `sing-box run -c test.json` 启动服务后
通过 `setpriv --reuid 1000 curl 1.1.1.1` 进行测试
发现 sing-box 中仍然有请求日志，并且 nftables 的 skuid 相关行 counter 为 0

此时 nft -f 增加一个自定义监控
```nft
table ip test {
	chain output {
		type filter hook output priority filter
		meta skuid 1000 counter
	}
}
```
跑同样的 curl 测试命令，可以发现 counter 不为 0

### 日志

sing-box 日志
```txt
INFO[0339] [2832095099 0ms] inbound/tun[0]: inbound connection to 1.1.1.1:80
INFO[0339] [2832095099 0ms] outbound/direct[direct]: outbound connection to 1.1.1.1:80
```

`nft list ruleset | grep -A 5 -B 3 skuid` 结果
```txt
	chain output {
		type nat hook output priority mangle; policy accept;
		meta mark 0x00002024 counter packets 535 bytes 40329 return
		meta skuid { 1000 } counter packets 0 bytes 0 return
		meta nfproto ipv4 oifname != "lo" meta l4proto { tcp, udp } th dport 53 dnat ip to 172.18.0.2 counter packets 0 bytes 0
		ip daddr @inet4_local_address_set counter packets 324 bytes 21837 return
		ip daddr @inet4_route_exclude_address_set counter packets 327 bytes 19852 return
		meta nfproto ipv4 meta l4proto tcp counter packets 7 bytes 420 redirect to :39763 return
	}
--
	chain output_udp {
		type route hook output priority mangle; policy accept;
		meta mark 0x00002024 counter packets 1124 bytes 123606 return
		meta skuid { 1000 } counter packets 0 bytes 0 return
		meta l4proto != udp return
		ip daddr @inet4_local_address_set counter packets 1440 bytes 139776 return
		ip daddr @inet4_route_exclude_address_set counter packets 52 bytes 8633 return
		meta mark set 0x00002023 ct mark set meta mark counter packets 1832 bytes 322059
	}
```
通过 `nft list table ip test` 查看自定义监控结果
```txt
table ip test {
	chain output {
		type filter hook output priority filter; policy accept;
		meta skuid 1000 counter packets 5 bytes 339
	}
}
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by nekohasekai** [comment]
你能确认一下是否如果自定义监控改为 `meta skuid { 1000 } counter`，counter 也不为 0 吗？

**Comment by doveccl** [comment]
> 你能确认一下是否如果自定义监控改为 `meta skuid { 1000 } counter`，counter 也不为 0 吗？

@nekohasekai 这个我也试过，在 `nft -f` 之后再去 `nft list ruleset` 结果会把花括号自动去掉

不过我觉得这个不是问题的关键，因为我做过另一个实验
- 自定义 `meta skuid { 1000, 2000 } counter` ✅
- 配置文件 `exclude_uid: [1000, 2000]` ❌

**Comment by nekohasekai** [comment]
试试 https://github.com/SagerNet/sing-box/commit/983293246223887d03f0c9f17f5644f6b36d5615

**Comment by doveccl** [comment]
> 试试 [9832932](https://github.com/SagerNet/sing-box/commit/983293246223887d03f0c9f17f5644f6b36d5615)

还是不行

**Comment by nekohasekai** [comment]
测试发现似乎在 nat chain 里，skuid 始终无法匹配，不清楚是 bug 还是 feature。

**Comment by doveccl** [comment]
我现在的曲线救国方案是手动创建一个高优的规则
```nft
chain direct_user {
	type nat hook output priority mangle - 1
	meta skuid 1000 meta mark set 0x2024 counter
}
```
看看 sing-tun 那边是不是可以考虑做成类似 iptables 那种直接 exec nft 命令的方式来做

**Comment by nekohasekai** [comment]
我不认为你的方案会起效，你的测试看起来正常，是因为使用了 `type filter` 而不是路由所需的 `type nat`。

**Comment by doveccl** [comment]
> 我现在的曲线救国方案是手动创建一个高优的规则
> 
> ```
> chain direct_user {
> 	type nat hook output priority mangle - 1
> 	meta skuid 1000 meta mark set 0x2024 counter
> }
> ```
> 
> 看看 sing-tun 那边是不是可以考虑做成类似 iptables 那种直接 exec nft 命令的方式来做

@nekohasekai 在我的这一版方案里，我已经成功用上了，这个就是 nat 注意看 type
![image](https://github.com/user-attachments/assets/56e80350-3bbe-409f-a30d-ef38712dd8a4)

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/7a4876728fc8756b0c89d6882876e0256327f4db

**Comment by doveccl** [comment]
@nekohasekai 这个版本有效了
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/c9290185-a27d-4088-aee6-a0a6ba64382f">

**Comment by hyfink** [comment]
@nekohasekai 
关于此issue作者提到的：
另外还有一个 nftables 相关的问题是，sing-box 会把 counter 放在 dnat 指令之后
导致 dns 53 hijack 那几行的统计 counter 永远是 0（功能上不会受影响）

能否修复下，目前v1.11.4还是如此。之前查找问题的时候，看统计一直以为拦截dns失效了，绕了好大弯路。感谢！
