### ISSUE TITLE
Feature Request: Add ClientIDs to DoH/DoT/DoQ resolvers

### ISSUE THREAD

**Issue by mazzz1y** [SagerNet/sing-box#206]
Refer to: https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#clientid

> ClientIDs are identifiers that can be used with the following DNS protocols: DNS-over-HTTPS, DNS-over-TLS, and DNS-over-QUIC. To use this identifier, clients should perform queries using a special domain name or URL.

```
https://example.org/dns-query/my-client
quic://my-client.example.org
tls://my-client.example.org
```

An example of sing-box configuration:
```json
{
  "dns": {
    "servers": [
      {
        "tag": "adguard-clientid",
        "address": "https://adguard.com/dns-query/$user",
        "address_resolver": "local",
        "detour": "direct"
      }
    ]
  }
}
```

**Comment by nekohasekai** [comment]
Unclear description.

**Comment by mazzz1y** [comment]
Add option to pass Client ID(name) in DoH/DoT/DoQ URL to allow client tracking in DNS server.

Is it still unclear?

**Comment by mazzz1y** [comment]
Not sure, but in my opinion it is very useful feature. It looks clear to me. I can explain if something looks ambiguously
