### ISSUE TITLE
Sing-Box delisted from Japanese App Store

### ISSUE THREAD

**Issue by zytakeshi** [SagerNet/sing-box#2062]
### Operating system

iOS

### System version

16

### Installation type

sing-box for iOS Graphical Client

### Description

Dear SagerNet Team,

I hope this message finds you well.

I am writing to inquire about the recent removal of Sing-Box from the Japanese App Store. As a user who relies on this application, I was surprised to find it delisted, and I would greatly appreciate any information you can provide regarding the reasons behind this decision.

Furthermore, I would like to kindly request that you consider re-adding Sing-Box to the Japanese App Store. It has been a valuable tool for many users, and its absence is being keenly felt.

Thank you for your attention to this matter. I look forward to your response.

Best regards,
Your loyal user

### Reproduction

https://apps.apple.com/jp/app/sing-box/id6451272673
![photo_2024-08-25_07-56-14](https://github.com/user-attachments/assets/27af92d4-6318-4461-9fa4-ed856f436195)

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
https://sing-box.sagernet.org/clients/apple/
