### ISSUE TITLE
Please provide the .app release for SFM and the .ipa release for SFI.

### ISSUE THREAD

**Issue by uprprc777** [SagerNet/sing-box#2063]
### Operating system

iOS

### System version

iOS and macOS

### Installation type

sing-box for iOS Graphical Client

### Description

I understand that there are issues with Sing-Box’s Apple developer account, which have led to the unavailability of the SFM and SFI apps on the Apple App Store. I sincerely hope that SFI and SFM will be able to return to the App Store soon. While I regret that I cannot assist in resolving this matter directly, I respectfully request that you provide the .app release for SFM and the .ipa release for SFI.

Given that macOS allows apps to be installed outside the App Store, and .ipa files can be sideloaded on non-jailbroken devices, this could serve as a temporary workaround. This solution would at least enable users to access SFM and SFI without too much trouble.

### Reproduction

n/a

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
Without the relevant permissions, we cannot compile artifacts. You can buy ADP and do it yourself, or at least sponsor it and then ask for it.
