### ISSUE TITLE
能否在 SFA 的官方构建版加上 with_dhcp tag 

### ISSUE THREAD

**Issue by moosetk** [SagerNet/sing-box#2068]
### 操作系统

Android

### 系统版本

14

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.10.0-beta.4

### 描述

![tempFileForShare_20240826-141506](https://github.com/user-attachments/assets/195c7433-d6a3-462c-ba90-f81ab031266c)

### 重现方式

无

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by PuerNya** [comment]
请使用 `local` 替代，`dhcp` 传输层在 android app 上并不能工作的更好
