### ISSUE TITLE
Problem with subdir (trojan's fallback)

### ISSUE THREAD

**Issue by miullu** [SagerNet/sing-box#2075]
### Operating system

Linux

### System version

satou@archlinux OS: Arch Linux Kernel: x86_64 Linux 6.6.47-1-lts

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.9.3

Environment: go1.22.4 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: 085f60337799afc906069b540a38368968c123e4
CGO: disabled
```

### Problem with trojan's fallback

when using fallback of trojan with nginx and subdir, fallback to wrong port

### Reproduction

For example there is a subdir /dist and the domain of the sing-box server is abc.com meanwhile the trojan is setted to fallback to port 7235

when i go abc.com/dist

"Hmmm… can't reach this page"

and according to url on url bar show 

"http://[abc.com](http://abc.com:7235/dist/):7235/dist/" (copy from the bar)

the fallback go the port 7235 instead of port 443

### config
```
{
    "inbounds": [
        {
            "type": "trojan",
            "tag": "trojan-in",
            "listen": "0.0.0.0",
            "listen_port": 443,
            "tls": {
                "enabled": true,
                "server_name": "abc.com",
                "certificate_path": "/etc/sing-box/abc.cer",
                "key_path": "/etc/sing-box/abc.key"
            },
            "fallback": {
                "server": "192.168.1.101",
                "server_port": 7235
            },
            "multiplex": {
                "enabled": true
            },
            "transport": {}
        }
    ]
}
``` 

### Logs

```shell
sing-box  | INFO[0040] [4174694078 0ms] inbound/trojan[trojan-in]: inbound connection from x.x.x.x:51797
sing-box  | INFO[0040] [2275445351 0ms] inbound/trojan[trojan-in]: inbound connection from x.x.x.x:51799
sing-box  | INFO[0056] [4174694078 16.86s] inbound/trojan[trojan-in]: fallback connection to x.x.x.x:7235
sing-box  | INFO[0056] [4174694078 16.86s] outbound/direct: outbound connection to x.x.x.x:7235
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
fallback does not support use as a reverse proxy, even in other projects.

And there is no evidence that GFW detects and blocks Trojan servers based on HTTP responses, and opening the standard http/s port on the server is a much bigger signature.
