### ISSUE TITLE
Android DNSrules 1层 DNSserver 配置问题

### ISSUE THREAD

**Issue by solanab** [SagerNet/sing-box#2081]
### 操作系统

Android

### 系统版本

Android 12 (MIUI 14.0.5) 

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.9.4

### 描述

问题是无法访问常用网站

Android 手机如果使用中国移动流量，不会出现本问题
如果使用 Wlan ，1层DNS server 设置为 Wlan分配的DNS服务器，不会出现本问题
如果使用 Wlan ，1层DNS server 设置为 组播DNS服务器，会出现本问题

### 重现方式

Android sing-box
WLan

DNS配置1，可正常联网 
211.82.112.111 为mac在同Wi-Fi下 Wi-Fi详情里的一个DNS服务器
```json
	"dns": {
		"servers": [
			{
				"tag": "default-dns",
				"address": "211.82.112.111",
				"detour": "direct-out"
			},
			{
				"tag": "ali",
				"address": "https://dns.alidns.com/dns-query",
				"address_resolver": "default-dns"
			},
			{
				"tag": "google",
				"address": "https://dns.google/dns-query",
				"address_resolver": "ali",
				"client_subnet": "218.107.132.66"
			}
		],
		"rules": [
			{
				"outbound": "any",
				"server": "default-dns"
			},
			{
				"rule_set": "cnsite",
				"server": "ali"
			},
			{
				"clash_mode": "direct",
				"server": "ali"
			},
			{
				"clash_mode": "global",
				"server": "google"
			}
		],
		"disable_cache": false,
		"disable_expire": false,
		"independent_cache": false,
		"strategy": "ipv4_only",
		"final": "google"
	},
```

DNS配置2，无法正常联网

```json
	"dns": {
		"servers": [
			{
				"tag": "ali",
				"address": "223.5.5.5",
				"detour": "direct-out"
			},
			{
				"tag": "google",
				"address": "https://dns.google/dns-query",
				"address_resolver": "ali",
				"client_subnet": "218.107.132.66"
			}
		],
		"rules": [
			{
				"outbound": "any",
				"server": "default-dns"
			},
			{
				"rule_set": "cnsite",
				"server": "ali"
			},
			{
				"clash_mode": "direct",
				"server": "ali"
			},
			{
				"clash_mode": "global",
				"server": "google"
			}
		],
		"disable_cache": false,
		"disable_expire": false,
		"independent_cache": false,
		"strategy": "ipv4_only",
		"final": "google"
	},
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by solanab** [comment]
找到原因了，校园网的问题。

校园网把国内网站屏蔽了，但没屏蔽ss和DNS。。

**Comment by FBI-dev** [comment]
那要怎么解决啊，我也有同样的问题😂

**Comment by solanab** [comment]
> 那要怎么解决啊，我也有同样的问题😂

我的可能是因为校园网防火墙设置过严 导致无法启动Android客户端。。

先在原来的国内的DNS server 223.5.5.5 前面 加一层局域网DNS server

局域网DNS server 地址是WLan详情里查到的

然后在确认geo文件正常的前提下，一直点连接快10次，然后不报错启动了。

**Comment by solanab** [comment]
先用数据连上，下载ruleset，然后连wlan

**Comment by FBI-dev** [comment]
ok，谢谢

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: solanab ***@***.***>
发送时间: Monday, October 7, 2024 9:59:47 PM
收件人: SagerNet/sing-box ***@***.***>
抄送: FBI ***@***.***>; Comment ***@***.***>
主题: Re: [SagerNet/sing-box] Android DNSrules 1层 DNSserver 配置问题 (Issue #2081)


先用数据连上，下载ruleset，然后连wlan

―

**Comment by solanab** [comment]
> 找到原因了，校园网的问题。
> 
> 校园网把国内网站屏蔽了，但没屏蔽ss和DNS。。

现在再来看，可能是校园网用的阿里云，不限制阿里云流量。

我的机场的部分节点正好是阿里云中转，所以可以免流？

但是因为没交钱，所以阿里云外的流量，包括国内流量都给屏蔽了
