### ISSUE TITLE
Android 客户端日志界面建议可复制

### ISSUE THREAD

**Issue by hu-boss** [SagerNet/sing-box#2086]
Android 客户端日志界面建议可复制，因为日志可以分析流量，检查一些问题，单在应用上一行行看太难受

**Comment by ib8** [comment]
加上output配置，如
"log": { "level": "debug", "output": "boxc.log", "timestamp": true},
日志路径生成在
/storage/emulated/0/Android/data/io.nekohasekai.sfa/files/boxc.log
