### ISSUE TITLE
处理 SOCKS5 入站第一个 UDP 包的时候，超时时间过短

### ISSUE THREAD

**Issue by Haerbin23456** [SagerNet/sing-box#2092]
### 操作系统

Windows

### 系统版本

Windows 11

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
1.9.4
```

### 描述

这个是一个处理 SOCKS5 的 UDP association 时的 bug。
根据 [RFC 1928](https://datatracker.ietf.org/doc/html/rfc1928)，当客户端发送的 UDP ASSOCIATE request 中的 DST.ADDR 和 DST.PORT 全为零的时候，sing-box 不是要等客户端发过来一个 UDP 包嘛，然后使用那个 UDP 包里提供的 DST.ADDR 和 DST.PORT。
问题就在于 sing-box 给这个“读取这个 UDP 包里的 DST.ADDR 和 DST.PORT”的过程，设置了一个只有 300ms 的超时，而有些情况下客户端没法在短时间内把这个 UDP 包发到 sing-box（比如 qBittorrent）。然后 sing-box 会直接结束这个 UDP association，就炸啦。

（另外 RFC 说到 “A UDP association terminates when the TCP connection that the UDP ASSOCIATE request arrived on terminates”。也就是说 UDP association 的断开，按理来说是要等客户端与 Socks5 服务器之间的 TCP 连接断开后才断开的。）

还有上次我在 sing 开的 issue 说的太含糊了，而且都是我自己都没搞清楚，知道错了啦 QWQ

### 重现方式

sing-box 配置如下（简化了的）：
```json
{
  "log": {
    "level": "trace",
    "timestamp": true
  },
  "inbounds": [
    {
      "type": "mixed",
      "listen": "::",
      "listen_port": 11451
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    }
  ],
  "route": {
    "final": "direct",
    "auto_detect_interface": true
  }
}
```

启动 sing-box 之后，运行这个 GO 代码就能复现 BUG
（没怎么写过 GO，勿喷）
```go
package main

import (
	"bufio"
	"fmt"
	"net"
	"time"
)

func main() {
	// 模拟 UDP association 过程的代码
	addr, _ := net.ResolveTCPAddr("tcp", "127.0.0.1:11451")
	conn, _ := net.DialTCP("tcp", nil, addr) // 连接 SOCKS5 服务器
	conn.SetKeepAlive(true)
	conn.SetKeepAlivePeriod(time.Second)
	defer conn.Close()

	reader := bufio.NewReader(conn)

	conn.Write([]byte{5, 1, 0}) // 与 SOCKS5 服务器建立 NO AUTHENTICATION REQUIRED 的连接

	var buf [2]byte
	n, _ := reader.Read(buf[:])
	fmt.Println(n, buf)

	conn.Write([]byte{5, 3, 0, 1, 0, 0, 0, 0, 0, 0}) // 发送一个 UDP ASSOCIATE request

	var buf2 [10]byte
	n, _ = reader.Read(buf2[:])
	fmt.Println(n, buf2)

	time.Sleep(time.Minute * 2) // 模拟某 q 开头的软件发送第一个 UDP 包之前的延时

	// 其实我为了 debug 时间充足一点才设置成两分钟。实际 qBittorrent 延时没有这么巨大的
	// 至于为什么 qBittorrent 会有延时，我一两句也讲不清楚 qwq，总之就是有

	/*
	 * 假装这里有发送第一个 UDP 包的代码
	 */

	// 由于实际上并不需要真的发送 UDP 包，只要延时了就能触发 bug，所以其实这里不需要相关代码，况且我也不会写（逃）
}
```

### 日志

```shell
+0800 2024-09-08 10:08:06 INFO router: updated default interface WLAN 2, index 8
+0800 2024-09-08 10:08:06 INFO inbound/mixed[0]: tcp server started at [::]:11451
+0800 2024-09-08 10:08:06 INFO sing-box started (0.22s)
+0800 2024-09-08 10:08:15 INFO [2971485540 0ms] inbound/mixed[0]: inbound connection from 127.0.0.1:9837
+0800 2024-09-08 10:08:15 INFO [2971485540 1ms] inbound/mixed[0]: inbound packet connection to 0.0.0.0:0
+0800 2024-09-08 10:08:15 INFO [2971485540 301ms] outbound/direct[direct]: outbound packet connection
+0800 2024-09-08 10:08:15 DEBUG [2971485540 327ms] inbound/mixed[0]: connection closed: process connection from 127.0.0.1:9837: upload: write udp [::]:58223->:0: wsasendto: The requested address is not valid in its context. | download: raw-read udp [::]:58223: use of closed network connection | writeto tcp 127.0.0.1:11451->127.0.0.1:9837: read tcp 127.0.0.1:11451->127.0.0.1:9837: use of closed network connection
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by Haerbin23456** [comment]
还有就是处理 UDP association 的代码在这里
https://github.com/SagerNet/sing/blob/26511a251ffe0765f0068ebed820e48b3b3342a3/protocol/socks/handshake.go#L207-L233

不过你看那里也看不出啥，因为那个超时不是在那里被设置的。超时是在这被设置的：
https://github.com/SagerNet/sing-box/blob/8cfc3117a9b288f5a44d8ac906d9883369ae8f19/route/router.go#L989-L998
这里超时被设置成 `C.ReadPayloadTimeout == 300ms`。
~~一个粗暴的方法是直接改成 `C.UDPTimeout == 5min`，就是不知道这样会不会产生别的 BUG。~~

**Comment by nekohasekai** [comment]
应该已经在 main-next 与 dev-next 修复了这个 bug。
