### ISSUE TITLE
unexpected EOF  when updating binary rulesets

### ISSUE THREAD

**Issue by ilfat12** [SagerNet/sing-box#2105]
### Operating system

Linux

### System version

Linux 6.6

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box-1.10.0~beta.7-1.x86_64
```

### Description

If I add large lists of rulesets, such as catagory-ads-all or ip countries, then unexpected EOF errors appear in the logs when updating binary rulesets. There are no problems in source format.

This error is probably due to the fact that sometimes a real IP is given instead of a fake IP. I have not noticed this with source format.

### Reproduction

Run:
```
sing-box geosite export category-ads-all
sing-box rule-set compile geosite-category-ads-all.json
```
Add geosite-category-ads-all.srs as binary ruleset to the config file.
Restart sing-box and watch its output.
Run the following command again to have the file changed and the application reread the rulesets (thanks for this feature):
`sing-box rule-set compile geosite-category-ads-all.json`

### Logs

```shell
сен 13 15:46:55 server sing-box[621995]: ERROR[0026] router: reload rule-set block: unexpected EOF
сен 13 15:46:55 server sing-box[621995]: ERROR[0026] router: reload rule-set block: read rule[1]: LabelBitmap: unexpected EOF
сен 13 15:46:55 server sing-box[621995]: ERROR[0027] router: reload rule-set block: read rule[1]: Labels: unexpected EOF
сен 13 15:46:56 server sing-box[621995]: ERROR[0027] router: reload rule-set block: read rule[1]: Labels: unexpected EOF
сен 13 15:46:56 server sing-box[621995]: ERROR[0027] router: reload rule-set block: read rule[2]: LabelBitmap: unexpected EOF
сен 13 15:46:56 server sing-box[621995]: ERROR[0027] router: reload rule-set block: read rule[2]: LabelBitmap: unexpected EOF
сен 13 15:46:56 server sing-box[621995]: ERROR[0027] router: reload rule-set block: read rule[2]: Labels: unexpected EOF
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by ilfat12** [comment]
> This error is probably due to the fact that sometimes a real IP is given instead of a fake IP. I have not noticed this with source format.

Still, this problem is not related to the one described above. I will describe it in another bug

**Comment by nekohasekai** [comment]
Only files that are written continuously (like cp/mv) can be reloaded. In your use case, there will be long write pauses waiting for compilation, so this scenario is not supported.

**Comment by ilfat12** [comment]
Now I understand why there are no errors when restarting the service. I will use mv. Thanks!

**Comment by ilfat12** [comment]
Even with mv there was an error:
`ERROR[91140] router: reload rule-set block: EOF`

Disabling COW on btrfs for the directory with these files solved the problem completely.
