### ISSUE TITLE
adding rule-set geolocation-!ir.srs and geolocation-!ru.srs

### ISSUE THREAD

**Issue by fsheidaiee** [SagerNet/sing-box#2106]
Hi
to prevent dns leak the documentation says that we have to use geolocation-!cn.srs
https://sing-box.sagernet.org/manual/proxy/client/#__tabbed_3_2

but the problem is that, this rule-set is only available for china users. iran and russian users dont have geolocation-!ir.srs and geolocation-!ru.srs
how can we have these sources?

**Comment by nekohasekai** [comment]
These rule sets are not the core of fixing DNS leaks, but improve routing accuracy. For Iranian users, I found https://github.com/Chocolate4U/Iran-sing-box-rules/tree/rule-set which also provides similar domain name rule sets geosite-ir, but Russians don't seem to need them much.
