### ISSUE TITLE
1.10.0-beta.8 入站开启 Sniff 时发送UDP包异常

### ISSUE THREAD

**Issue by bemarkt** [SagerNet/sing-box#2109]
### 操作系统

Windows

### 系统版本

Windows 11 24H2

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.10.0-beta.8

Environment: go1.23.1 windows/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: df8baa65618bb37a2e71ef9da2b06af995e242ca
CGO: disabled
```

### 描述

第一次向 UDP 服务端发送 UDP 包时，服务端显示没有收到，在不断开此 UDP 连接的情况下重复发送，服务端响应正常。
使用 Wireshark 抓包显示第一次发送时 tun 有 UDP 包发出，而实际网卡没有对应的 UDP 包发出，重复发送时实际网卡有相应 UDP 包发出；断开该连接，重新发包时复现异常。
在关闭入站的 Sniff 功能后，测试发送恢复正常。
出现版本:1.10.0-beta.8 1.10.0-beta.7
正常版本:1.10.0-beta.6

![image](https://github.com/user-attachments/assets/78e801d3-eccf-44d8-838b-f194a3d9614c)
 

### 重现方式

sing-box 配置：
```json
{
  "log": {
    "level": "trace",
    "timestamp": true
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "auto_route": true,
      "strict_route": true,
      "stack": "mixed",
      "sniff": true,
      "sniff_override_destination": false,
      "platform": {
        "http_proxy": {
          "enabled": false,
          "server": "127.0.0.1",
          "server_port": 7890
        }
      }
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    }
  ],
  "route": {
    "final": "direct",
    "auto_detect_interface": true
  }
}
```

复现方式：
发送Sniff功能中支持的协议以外的UDP包

### 日志

```shell
+0800 2024-09-14 00:00:51 INFO [4205874048 0ms] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:55585
+0800 2024-09-14 00:00:51 INFO [4205874048 0ms] inbound/tun[tun-in]: inbound packet connection to 8.135.10.183:52328
+0800 2024-09-14 00:00:51 INFO [4205874048 0ms] router: found process path: E:\Tools\PacketSenderPortable\packetsender.exe
+0800 2024-09-14 00:00:51 INFO [4205874048 0ms] outbound/direct[direct]: outbound packet connection
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by nekohasekai** [comment]
试试 https://github.com/SagerNet/sing-box/commit/bb14bb68c671e55b25ded5941113d9b0c5688b07

**Comment by bemarkt** [comment]
> 试试 [bb14bb6](https://github.com/SagerNet/sing-box/commit/bb14bb68c671e55b25ded5941113d9b0c5688b07)

测试正常
