### ISSUE TITLE
tor-out 如何指定 ExitNodes？提示 failed to open geoip file

### ISSUE THREAD

**Issue by GeorgeRudd** [SagerNet/sing-box#211]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

tor-out 如何指定 ExitNodes？提示 failed to open geoip file 
geoip file 地址 https://github.com/torproject/tor/tree/main/src/config 手动添加无效

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.1-beta12

Environment: go1.19.2 linux/amd64
Tags: with_quic,with_grpc,with_wireguard,with_ech,with_utls,with_acme,with_clash_api,with_v2ray_api,with_gvisor,with_embedded_tor
CGO: enabled

```

</details>

### Server and client configuration file

<details>

```console
		{
			"type": "tor",
			"tag": "tor-out",
			"extra_args": [],
			"data_directory": "/usr/local/etc/sing-box/cache/tor",
			"torrc": {
				"ClientOnly": "1",
				"ExitNodes": "{us}",
				"StrictNodes": "1"
			}
		}
```

</details>

### Server and client log file

<details>

```console
WARN outbound/tor[tor-out]: failed to open geoip file /tor/geoip. 
WARN outbound/tor[tor-out]: we've been configured to use (or avoid) nodes in certain countries, and we need geoip information to figure out which ones they are. 
WARN outbound/tor[tor-out]: failed to open geoip file /tor/geoip6. 
WARN outbound/tor[tor-out]: we've been configured to use (or avoid) nodes in certain countries, and we need geoip information to figure out which ones they are. 

```

</details>

**Comment by nekohasekai** [comment]
geoip files will be read from the working directory in the configuration.

**Comment by nekohasekai** [comment]
Try 3d767777607e67eefce6b4a974bec750bc5a7aae
