### ISSUE TITLE
sing-box 安卓客户端疯狂占用CPU并且内存泄漏

### ISSUE THREAD

**Issue by youlinaixu2017** [SagerNet/sing-box#2134]
### Operating system

Android

### System version

9

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.9.6

### Description

打开sing-box安卓官方图形客户端，并启动代理，再打开某些软件（如起点阅读）后，sing-box占用CPU100%并疯狂占用内存，手机和烤机一样立马发烫
![Screenshot_20240924_215442_com android settings](https://github.com/user-attachments/assets/cdd046c3-ab8d-4c76-8400-9018d0a1835c)
![Screenshot_20240924_221213_com android settings](https://github.com/user-attachments/assets/5e8ef959-4e32-49d6-b710-461fb67c5f6e)
![Screenshot_20240924_221216_com android settings](https://github.com/user-attachments/assets/3906340d-765f-49a9-b6f8-84171188b245)
![Screenshot_20240924_221218_com android settings](https://github.com/user-attachments/assets/770c7df2-d6f1-4356-9653-2f015f09c940)
![Screenshot_20240924_221221_com android settings](https://github.com/user-attachments/assets/3c12ca40-45f0-4b01-bfd2-505311398cc5)
![Screenshot_20240924_221223_com android settings](https://github.com/user-attachments/assets/fc1932f0-861a-44be-a049-5746ad452284)
![Screenshot_20240924_221226_com android settings](https://github.com/user-attachments/assets/a3a718b6-4a8f-4155-bc8a-33addae98d88)
![Screenshot_20240924_221229_com android settings](https://github.com/user-attachments/assets/6b7a9d80-c6a2-48c4-8ef5-980ac4d659ca)
![Screenshot_20240924_221232_com android settings](https://github.com/user-attachments/assets/1fb9667f-c9b1-4ac5-addc-ff3aab959258)
![Screenshot_20240924_221234_com android settings](https://github.com/user-attachments/assets/7c8b916c-cedb-4561-9e3d-ce0c0252797b)
![Screenshot_20240924_221247_com android settings](https://github.com/user-attachments/assets/c3a7932c-1e7b-4fb2-962e-453db11c758f)

### Reproduction

环境：启用了分应用代理，配置只允许手机上的浏览器使用代理
步骤：打开sing-box安卓官方图形客户端，并启动代理，再打开某些软件（如起点阅读）

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [x] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by ywtafatyw-design** [comment]
老哥我也是这个情况 解决了没
