### ISSUE TITLE
安卓编译添加了with_quic，但报错，日志提示没有

### ISSUE THREAD

**Issue by catbreast** [SagerNet/sing-box#215]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

1.1-beta 13 compiled with termux, with_quic is enabled, but the log prompt is not

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```
sudo /data/adb/sing/bin/sing-box version           sing-box version 1.1-beta13                                
Environment: go1.19.3 android/arm64
Tags: with_clash_api,with-quic,with_gvisor,with_ech
CGO: enabled
</details>

### Server and client configuration file

<details>

```console
# paste json here
```
{
				"tag": "local",
				"address": "h3://101.6.6.6:8443/dns-query",
				"detour": "direct"
			},
</details>

### Server and client log file

<details>

```console
# paste log here
```
[31mFATAL[0m[0000] create service: parse route options: parse dns server[local]: QUIC is not included in this build, rebuild with -tags with_quic
[Error]: Start sing service Failed.

</details>

**Comment by nekohasekai** [comment]
'with_quic' is not 'with-quic'.
