### ISSUE TITLE
singbox开启tun模式后，在实体网卡中看不到dns请求

### ISSUE THREAD

**Issue by adamduan0201** [SagerNet/sing-box#2154]
singbox开启了tun，dns也配置了相应的dns服务器和路由规则，各种上网一切正常。按照我的理解：

设定走节点的dns请求走节点，不走节点的dns请求就直出，针对不走节点的dns请求，我应该是能在实体网卡中看到dns请求的。可是看不到。

如果说虚拟网卡劫持dns，于是在实体网卡看不到dns请求，只能在虚拟网卡中看到dns请求，那是否泄露我怎么知道？

是哪里理解错了？路过的大神指点一下。可能就是某个概念不清楚。

**Comment by luweijun1992** [comment]
一样的疑问，dig @223.5.5.5 www.baidu.com 会无法解析，但是直接ping www.baidu.com 解析正常
