### ISSUE TITLE
关于sing-box衍生作品再授权的申请

### ISSUE THREAD

**Issue by REIJI007** [SagerNet/sing-box#2159]
开发团队你们好。我制作了一个下游衍生作品，名称使用到了”sing-box“字样，根据许可证最后一条要求，需要向你们申请关于名称使用许可的授权。

https://github.com/REIJI007/AdBlock_Rule_For_Sing-box

**Comment by nekohasekai** [comment]
许可证不是商标，不限制衍生作品。
