### ISSUE TITLE
Multi user support for hysteria inbound will break the backward compatibility

### ISSUE THREAD

**Issue by Gzxhwq** [SagerNet/sing-box#216]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

这个变动https://github.com/SagerNet/sing-box/commit/617aba84e437df0a42aa1c5502361b2be8c5bde5 会强行要求现有Hysteria用户去更改服务端的配置文件。会令一部分使用cron job更新服务端的用户不能启动。请问是否可以考虑保留原来的结构，不强制使用多用户，类似SS2022那样？

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by nekohasekai** [comment]
不。

**Comment by Gzxhwq** [comment]
好的，那至少在更新日志上提一下，我就踩到坑上，查找了一个多小时才发现这里不兼容

**Comment by nekohasekai** [comment]
> 会令一部分使用cron job更新服务端的用户不能启

不应该自动更新非稳定版本。

**Comment by Gzxhwq** [comment]
> > 会令一部分使用cron job更新服务端的用户不能启
> 
> 不应该自动更新非稳定版本。

这个知道，但是如果正式引入了这个改动，就算稳定版自动更新了也一样会出现卡壳。这是个服务器端的breaking change，引入还是需要慎重考虑。
