### ISSUE TITLE
cannot install macOS SFM extension - SFM 1.9.7

### ISSUE THREAD

**Issue by laye0619** [SagerNet/sing-box#2166]
### Operating system

macOS

### System version

15.0.1

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.9.7 and installed via HomeBrew Cask

### Description

Upgraded the new SFM 1.9.7 and tried to install Macos system extension, I got the following error:

<img width="579" alt="image" src="https://github.com/user-attachments/assets/cec378ca-7d3b-435b-a6cc-2987eb6ca9eb">

### Reproduction

Open SFM 1.9.7 -> prompt install system extension -> click install -> get the error.
Go to setting -> App -> System Extension -> update -> get the error
Go to setting -> App -> System Extension -> uninstall -> get following error
<img width="650" alt="image" src="https://github.com/user-attachments/assets/c7f28066-39e7-479b-a6ee-2ba55f88ab13">

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by laye0619** [comment]
somebody else has the same problem?

**Comment by curtainp** [comment]
I'm having the same problem and solve it by manually turned on this system settings.
<img width="470" alt="image" src="https://github.com/user-attachments/assets/127bbaef-308d-4e7a-a012-09f3ac0cfb6a">

hopes that help you.

**Comment by laye0619** [comment]
> I'm having the same problem and solve it by manually turned on this system settings. <img alt="image" width="470" src="https://private-user-images.githubusercontent.com/20302295/375947433-127bbaef-308d-4e7a-a012-09f3ac0cfb6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzAxNzAsIm5iZiI6MTcyODcyOTg3MCwicGF0aCI6Ii8yMDMwMjI5NS8zNzU5NDc0MzMtMTI3YmJhZWYtMzA4ZC00ZTdhLWEwMTItMDlmM2FjMGNmYjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEwNDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMWFjMmM0NjIwMTYwODlkNDhmMzgzYTkzMzRjNDcwMDAxYWM1NjRiOTQ1YzBjM2EwYjM5NTVlYjEyZmI3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JozVuF-8E4VGXFHpAJqygp5FGE16X4Ak1zyYQ9FRvfI">
> 
> hopes that help you.

it works. thanks bro.
