### ISSUE TITLE
无法启动，service start无法启动

### ISSUE THREAD

**Issue by xuchensu** [SagerNet/sing-box#2175]
### Operating system

Android

### System version

Android 12

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.9.6

### Description

![Screenshot_2024-10-12-22-47-00-175_io nekohasekai sfa](https://github.com/user-attachments/assets/29bd3861-ec19-46ac-8f23-cc70fa86c301)
请问这是由于什么问题造成？如何解决？

### Reproduction

![Screenshot_2024-10-12-22-47-00-175_io nekohasekai sfa](https://github.com/user-attachments/assets/8e732491-c4f5-4608-911c-8538173a66ef)

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by choicky** [comment]
I thiny it's because you have updated the config file, resulting conflicts with the cached file.
Deleted the cached file should resolve the problem.  The cached files are usually located in `/var/lib/sing-box/`

**Comment by xuchensu** [comment]
Thank you for your answer. I will try again later
