### ISSUE TITLE
SFA v1.10 版本导入文件错误

### ISSUE THREAD

**Issue by TsingShui** [SagerNet/sing-box#2184]
### 操作系统

Android

### 系统版本

Any

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

v1.10

### 描述

在 v1.10 的 SFA Release 版本中，从文件导入失效。
![image](https://github.com/user-attachments/assets/1281293a-8de5-49cf-b9e5-f95682530c8f)
![image](https://github.com/user-attachments/assets/24529fe0-e32c-4ef3-9d61-2f3a3f72f982)

读取错误发生在 [sing-box/experimental/libbox/profile_import.go - Line: 221。](https://github.com/SagerNet/sing-box/blob/dev-next/experimental/libbox/profile_import.go#L221)，错误使用 reader ,应该修复成 bReader。修复之后重编译 libbox.aar ，可以正常导入。

pr: #2183

### 重现方式

下载然后从文件导入失效。
https://github.com/SagerNet/sing-box/releases/tag/v1.10.0

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by n-WN** [comment]
I have the same issue

**Comment by TsingShui** [comment]
> I have the same issue
see #2183 , change reader to bReader can fix this problem.
