### ISSUE TITLE
geoip:ir not working in sing-box

### ISSUE THREAD

**Issue by fsheidaiee** [SagerNet/sing-box#219]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

Hi
geoip:ir not working in sing-box
is that because the country is not included in the geoip.db file?

### Version of sing-box

<details>

```console
$ sing-box version

```
Environment: go1.19.3 windows/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_clash_api
Revision: 2fc1a0a9dddde96f7087155f6f02c513bf2c42ad
CGO: disabled
</details>

### Server and client configuration file

<details>

```console
# paste json here
```
{
    "log": {
        "disabled": false,
        "level": "info",
        "output": "./log",
        "timestamp": true
    },
  "dns": {
    "servers": [
      {
        "tag": "mydns",
        "address": "5.200.200.200",
        "detour": "direct"
      },
      {
        "tag": "ddns",
        "address": "tcp://1.1.1.1",
        "detour": "select"
      }
    ],
    "rules": [
      {
        "process_name": ["msedge.exe", "Sagernet.exe", "v2ray.exe", "v2rayN.exe", "nekoray.exe", "nekoray_core.exe"],
        "server": "mydns"
      },
      {
        "domain_suffix": [".ir", ".bale.ai"],
        "server": "mydns"
      },
      {
        "source_geoip": ["ir"],
        "server": "mydns"
      },
      {
        "domain": ["bale.ai"],
        "server": "mydns"
      }
    ],
    "final": "ddns",
    "disable_cache": false,
    "disable_expire": false
  },
    "inbounds": [
        {
            "type": "tun",
            "tag": "tun-in",
            "interface_name": "singbox",
            "inet4_address": "172.19.0.1/30",
            "inet6_address": "fdfe:dcba:9876::1/126",
            "auto_route": true,
            "stack": "system",
            "mtu": 1500,
            "sniff": true
        }
    ],
    "outbounds": [
{
  ....................................
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "geosite": ["private"],
        "outbound": "direct"
      },
      {
        "geoip": ["private"],
        "outbound": "direct"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "domain_suffix": [".ir", ".bale.ai"],
        "outbound": "direct"
      },
      {
        "geoip": ["ir"],
        "outbound": "direct"
      },
{
"process_name": [
"msedge.exe","adguardhome.exe", "Sagernet.exe", "v2ray.exe", "v2rayN.exe", "nekoray.exe", "nekoray_core.exe"
],
"outbound": "direct"
}
    ],
    "auto_detect_interface": true,
        "final": "select"
  },
  "experimental": {
    "clash_api": {
      "external_controller": "127.0.0.1:9090",
      "external_ui": "dashboard",
      "direct_io": false,
      "default_mode": "rule",
      "store_selected": true
    }
}
}
</details>

### Server and client log file

<details>

```console
# paste log here
```
[log.log](https://github.com/SagerNet/sing-box/files/9984611/log.log)

</details>

**Comment by nekohasekai** [comment]
Send this question to maxmind.
