### ISSUE TITLE
TunnelCrack 缓解

### ISSUE THREAD

**Issue by oppressor1761** [SagerNet/sing-box#2191]
### 操作系统

其他

### 系统版本

不适用

### 安装类型

sing-box for iOS 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.10.1

### 描述

[TunnelCrack](https://tunnelcrack.mathyvanhoef.com) 是2023年发现的漏洞，适用使用tunnel的VPN客户端，包括sing-box的tun。包括LocalNet和ServerIP两个漏洞。
在Apple平台，可以使用includeAllNetworks=true与excludeLocalNetworks=false进行LocalNet缓解，引用：[5.4.2小节](https://papers.mathyvanhoef.com/usenix2023-tunnelcrack.pdf)。
在Android，个人推测可以打开“屏蔽未使用VPN的所有连接”进行部分缓解。

个人希望将确认的缓解记载进文档中，类似TunnelVision缓解。

### 重现方式

不适用

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by nekohasekai** [comment]
LocalNet 就是 TunnelVision、ServerIP 就是 DNS 劫持，加起来起了个唬人名字罢了。
