### ISSUE TITLE
请考虑使 SFM 支持 macOS 原生的 VPN menu bar 特性

### ISSUE THREAD

**Issue by vstar37** [SagerNet/sing-box#2213]
### 操作系统

macOS

### 系统版本

15.0.1

### 安装类型

sing-box for macOS 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.10.1

### 描述

macOS 的 VPN menu bar应该不仅可以断开VPN，还可以连接到VPN，目前SFM只能断开，而不能连接。正确的效果应该如下
<img width="927" alt="image" src="https://github.com/user-attachments/assets/bf8d7930-f1e4-47ef-9030-db02a83e4ff9">

### 重现方式

在 macOS 的 系统设置-> 控制中心打开VPN显示。

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by nekohasekai** [comment]
Packet Tunnel 不是原生 VPN，不可比较。
