### ISSUE TITLE
shadowtls-server填写1.1.1.1后，客户端可以随意更换握手网站（TLS1.3域名）

### ISSUE THREAD

**Issue by LutongZhu** [SagerNet/sing-box#2225]
之前是看到VLESS-TCP-XTLS-Vision-REALITY示例配置中需要填写支持 TLS1.3 和 h2 的网站，也可以使用 1.1.1.1:443 作为目标。
今天测试shadowtls-server也是可以配置1.1.1.1，且客户端可以随意更换握手网站（TLS1.3域名）后可以正常使用，不知道是否有不可预知问题？

![](https://img.passeway.de/picturebed/2024/10/82fd29a61048ea939f3ffd92efcc1a69.png)

sing-box服务端配置文件
```
{
      "type": "shadowtls",
      "listen": "::",
      "listen_port": prot,
      "detour": "shadowsocks-in",
      "version": 3,
      "users": [
        {
          "password": "password"
        }
      ],
      "handshake": {
        "server": "1.1.1.1",
        "server_port": 443
      },
      "strict_mode": true
    },
    {
      "type": "shadowsocks",
      "tag": "shadowsocks-in",
      "listen": "127.0.0.1",
      "listen_port": prot,
      "method": "2022-blake3-aes-128-gcm",
      "password": "password==",
      "multiplex": {
        "enabled": true
      }
    }
```
![](https://img.passeway.de/picturebed/2024/10/feaa1dc435d2081fd371b099b82d6e10.png)

**Comment by zedifen** [comment]
I think Reality shares same idea with ShadowTLS and they would probably works similarly under the hood. What is your concern exactly?

**Comment by LutongZhu** [comment]
> I think Reality shares same idea with ShadowTLS and they would probably works similarly under the hood. What is your concern exactly?

配置示例的要求基本都是支持 TLS1.3 和 h2 的网站，而我现在使用的是1.1.1.1，在实际使用中会不会出现不安全问题？是否需要切换至使用支持 TLS1.3 和 h2 的网站，而不是去使用1.1.1.1？

**Comment by zedifen** [comment]
@LutongZhu Check with `curl -v https://1.1.1.1` you would find that it supports both TLSv1.3 and HTTP/2. The thing is that I'm not sure sing-box treats IP site the same as to domain ones. You can check the source code if you'd like.
