### ISSUE TITLE
节点类型 http 无法使用

### ISSUE THREAD

**Issue by kindle939393** [SagerNet/sing-box#223]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

network: http的节点无法使用，测速。
请问如何解决

![photo_2022-11-12_08-58-40](https://user-images.githubusercontent.com/61257638/201450677-6023c697-4cd1-4a3f-b469-e96b5c764acc.jpg)

### Version of sing-box

<details>
[1.1-beta14](https://github.com/SagerNet/sing-box/releases/tag/v1.1-beta14)
```console
$ sing-box version
# Paste output here
```

</details>

### Server and client configuration file

<details>
singbox for magisk
```console
# paste json here
```

</details>

### Server and client log file

<details>
No
```console
# paste log here
```

</details>

**Comment by ron777-777** [comment]
我拥有同样的问题
