### ISSUE TITLE
求增加编译一个openwrt 系统的安装包

### ISSUE THREAD

**Issue by iamckun** [SagerNet/sing-box#2240]
### 操作系统

Linux

### 系统版本

ImmortalWrt 23.05.3 r27917-81a1f98d5b / LuCI openwrt-23.05 branch git-24.092.44091-d24c2e3

### 安装类型

sing-box 原始命令行程序

### 描述

求一个openwrt的程序安装包

### 重现方式

求一个openwrt的程序安装包

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by Mosney** [comment]
OpenWrt就是Linux，直接用对应CPU架构的Linux的二进制就可以。
再说OpenWrt的软件源里本来就有sing-box包

**Comment by iamckun** [comment]
> OpenWrt就是Linux，直接用对应CPU架构的Linux的二进制就可以。 ImmortalWrt的软件源里也有sing-box包

他那个源里面的版本比这里的少了好多代了哦，就是想用源的方式安装哎，这个二进制咋弄，之前安装都是用的ipk的包

**Comment by Mosney** [comment]
直接替换二进制文件就可以

**Comment by devchenli** [comment]
> > OpenWrt就是Linux，直接用对应CPU架构的Linux的二进制就可以。 ImmortalWrt的软件源里也有sing-box包
> 
> 他那个源里面的版本比这里的少了好多代了哦，就是想用源的方式安装哎，这个二进制咋弄，之前安装都是用的ipk的包

你好，我也是想用二进制文件，ipk包提供的版本太低了，但是官方release的二进制中并没有我的架构：[mipsel_24kc]。貌似只能自己编译了，你解决了吗？

**Comment by iamckun** [comment]
> > > OpenWrt就是Linux，直接用对应CPU架构的Linux的二进制就可以。 ImmortalWrt的软件源里也有sing-box包
> > 
> > 
> > 他那个源里面的版本比这里的少了好多代了哦，就是想用源的方式安装哎，这个二进制咋弄，之前安装都是用的ipk的包
> 
> 你好，我也是想用二进制文件，ipk包提供的版本太低了，但是官方release的二进制中并没有我的架构：[mipsel_24kc]。貌似只能自己编译了，你解决了吗？

我不会啊，只能等大佬解救了

**Comment by devchenli** [comment]
没事了，我自己编译了，看错了，我要的是二进制，你要的是ipk，自己编译吧，我照着chatgpt 自己编译的。

**Comment by Mosney** [comment]
https://github.com/immortalwrt/packages/pull/1362 
ImmortalWrt的snapshot软件源已经更新到1.10.1，实在不会替换二进制的可以手动下载ipk升级

https://downloads.immortalwrt.org/snapshots/packages
