### ISSUE TITLE
关于通过拦截加密DNS解决DNS泄漏存在的问题

### ISSUE THREAD

**Issue by devchenli** [SagerNet/sing-box#2248]
小弟在使用Singbox的RealIP的时候，一直有个疑问，经常在一些配置文件中会看到类似写法：
```
       {
        "type": "logical",
        "mode": "or",
        "rules": [
          {
            "port": 853
          },
          {
            "network": "udp",
            "port": 443
          }
        ],
        "outbound": "block"
      },
```
目的是为了拦截DoT、DoH等加密DNS请求，防止DNS泄漏，那么如果某些程序只允许通过加密DNS请求才能正常运行，那这些程序都不能正常工作了？这样解决通过拦截的方式解决dns泄漏是否不妥？小弟对这方面不是很了解，只是有所疑虑，所以前来请教一下。

**Comment by mejinotdove** [comment]
seems like to block quic request? not for dot/doh
