### ISSUE TITLE
内网地址如何不走代理，以及如何关闭广告过滤。

### ISSUE THREAD

**Issue by Garnett1314** [SagerNet/sing-box#225]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

想知道该怎么配置内网的地址不会走代理。以及怎么把广告过滤给关了

### Version of sing-box

sing-box version 1.1-beta6

### Server and client configuration file

{
  "log": {
    "level": "info"
  },
  "inbounds": [
    {
      "type": "trojan",
      "tag": "trojan-in",
      "listen": "127.0.0.1",
      "listen_port": 52000,
      "tcp_fast_open": true,
      "udp_fragment": true,
      "sniff": true,
      "sniff_override_destination": false,
      "udp_timeout": 300,
      "proxy_protocol": true,
      "proxy_protocol_accept_no_header": false,
      "users": [
        {
          "name": "shouta",
          "password": "shouta"
        }
      ],
      "tls": {
        "enabled": true,
        "server_name": "xxxx",
        "alpn": [
          "http/1.1"
        ],
        "min_version": "1.2",
        "max_version": "1.3",
        "certificate_path": "",
        "key_path": "",
        "acme": {
          "domain": ["xxxx"],
          "data_directory": "/usr/local/etc/sing-box",
          "default_server_name": "",
          "email": "xxx@xx.com",
          "provider": "letsencrypt"
        } 
      },
      "fallback": {
        "server": "127.0.0.1",
        "server_port": 23333
      }
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    }
  ]
}

### Server and client log file

none

**Comment by soffchen** [comment]
"geoip": "pravite" 就是内网地址
默认不会拦截广告，一般通过 "geosite": "category-ads-all", 实现

建议参考文档 https://sing-box.sagernet.org/examples/ss-tun/ 
"geoip": "cn", 那边加一行 pravite 就可以了

**Comment by Garnett1314** [comment]
好的，谢了。
