### ISSUE TITLE
Deprecated Warning

### ISSUE THREAD

**Issue by LinJaMn** [SagerNet/sing-box#2283]
![Screenshot_20241114-235518.png](https://github.com/user-attachments/assets/ad27b602-33b4-4075-b2f0-a9bf96789488)

**Comment by LinJaMn** [comment]
这是什么问题？

**Comment by gg4924** [comment]
这是因为新版本1.11废弃了以前的部分配置方式，你现在用的配置应该只适合在1.10及以下版本的sing-box中使用。要么使用旧版本，要么更改配置方式。
