### ISSUE TITLE
希望能支持Hysteria 协议1.3.0版本的port-hopping功能 

### ISSUE THREAD

**Issue by chidedao** [SagerNet/sing-box#229]
如题
hysteria的udp高位端口还是会被封，加入端口跳跃可以实现自动化变动udp端口，非常实用

**Comment by JuanCldCmt** [comment]
帮忙加上wiki链接： https://hysteria.network/zh/docs/port-hopping/
> 为什么要用端口跳跃？
> 一直以来都有中国用户反馈长时间单端口 UDP 连接容易被运营商封锁/QoS 的问题。如遇类似问题可尝试使用端口跳跃来解决。

之前用hysteria的程序，端口跳跃确实能完美解决封锁问题，希望作者有空能加上这个功能

**Comment by nekohasekai** [comment]
暂时没有计划添加这种服务器只能使用特定 Linux 系统 + 特权运行的功能。

**Comment by lyc8503** [comment]
> 帮忙加上wiki链接： https://hysteria.network/zh/docs/port-hopping/
> 
> > 为什么要用端口跳跃？
> > 一直以来都有中国用户反馈长时间单端口 UDP 连接容易被运营商封锁/QoS 的问题。如遇类似问题可尝试使用端口跳跃来解决。
> 
> 之前用hysteria的程序，端口跳跃确实能完美解决封锁问题，希望作者有空能加上这个功能

尝试使用 Hysteria 2 天左右就会被封端口, 但直接更换端口就能解决, 在随机 TCP 和 TLS Tunnel 都已经遭到封锁的情况下, Hysteria 确实是不错的选择. 实现 port-hopping 应该可以显著提高 Hysteria 可用性.

~~但我并不会 Go~~ 希望有大佬能 PR.

**Comment by moll33er** [comment]
> 暂时没有计划添加这种服务器只能使用特定 Linux 系统 + 特权运行的功能。

只需客户端支持即可，服务端端口不会也不需要修改端口。

**Comment by yrwy** [comment]
> 

不行的，这样sing-box认为是重新开的连接，客户端会超时重连的。

**Comment by nekohasekai** [comment]
> 尝试使用 Hysteria 2 天左右就会被封端口, 实现 port-hopping 应该可以显著提高 Hysteria 可用性.

饮鸩止渴

**Comment by moll33er** [comment]
> > 
> 
> 不行的，这样sing-box认为是重新开的连接，客户端会超时重连的。

hy是udp没有连接一说吧，服务端的动态接口是利用iptables将多个端口转发到同一个端口，因此我个人认为服务端不需要做出更改，如有错误请指正。

**Comment by yrwy** [comment]
> 

你试下就知道了，用singbox做server会导致客户端重连
我这边已经关闭了客户端的hopping
原版的hy是对hopping进行处理的
要不是那个chat都没必要这么麻烦

**Comment by lyc8503** [comment]
> 饮鸠止渴

我在我的使用场景下启用 Hysteria 官方的 port-hopping 确实解决了被封锁的问题, 至今使用稳定. 互联网的环境错综复杂, GFW 也是黑盒, 就算 port-hopping 的方法之后会被墙, 也可能可以用于在国内绕过 QoS.
