### ISSUE TITLE
Error decode config: invalid character 'd' looking for beginning of value: row 1, column 1

### ISSUE THREAD

**Issue by MENJI-TRIWATER** [SagerNet/sing-box#2292]
### Operating system

macOS

### System version

15.1

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.9.3

### Version

```shell
Version 1.9.3 (271)
```

### Description

when i try to import a remote URL into sing-box, i pressed down the create button and error came
<img width="226" alt="截屏2024-11-17 22 03 29" src="https://github.com/user-attachments/assets/1c1a9177-16dd-4fa9-bd57-fccae922d0b5">

### Reproduction

just create a remote node and it happens

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by DearZack** [comment]
我也遇到了这个问题，如果不打算解决的话，是否有人有其他方式可以规避掉这个问题？

**Comment by doubuns** [comment]
> 我也遇到了这个问题，如果不打算解决的话，是否有人有其他方式可以规避掉这个问题？

从机场选择导入是可以的，我手动添加就不行。。。
