### ISSUE TITLE
大神帮忙看看, 1.10.1 macos15.2 一直提示需要 full disk access 权限, 实际已经赋权了

### ISSUE THREAD

**Issue by jojohappy** [SagerNet/sing-box#2296]
### 操作系统

macOS

### 系统版本

15.2

### 安装类型

sing-box for macOS 图形客户端程序

### 版本

```shell
1.10.1
```

### 描述

<img width="748" alt="image" src="https://github.com/user-attachments/assets/a0b25e83-f940-45fa-9dfd-14cd087fa076">
1.10.1 macos15.2 一直提示需要 full disk access 权限, 实际已经赋权了
<img width="480" alt="image" src="https://github.com/user-attachments/assets/55f641fe-6d63-4283-aa7d-de7449fe7df7">
大神们 求助还需要如何进行配置

### 重现方式

Application -> SFM 打开, 开始运行

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by yorunning** [comment]
你需要给`SFMExtension`全盘访问权限

<img width="464" src="https://github.com/user-attachments/assets/d677a1c0-e28b-4e25-af86-dbbd1154acb2">

**Comment by JoysKang** [comment]
添加访问权限时，找不到 SFMExtension，可以给些提示吗？
我在 /Library/SystemExtensions/CE77D5A7-1A10-4ACC-9D21-01E60AEF416D 中找到了 io.nekohasekai.sfavt.system.systemextension，但是它无法添加到磁盘访问中。

**Comment by yorunning** [comment]
> 添加访问权限时，找不到，可以给些提示吗？
> 
> 我在 /Library/SystemExtensions/CE77D5A7-1A10-4ACC-9D21-01E60AEF416D 中找到了 io.nekohasekai.sfavt.system.systemextension，但是它无法添加到磁盘访问中。

系统设置 通用 登陆项和扩展 看SFMExtension有没有打开

**Comment by JoysKang** [comment]
打开状态
![CleanShot 2024-11-27 at 09 32 38@2x](https://github.com/user-attachments/assets/cb59d8df-6d73-4b65-89d0-df8df71a30ba)

**Comment by yorunning** [comment]
全盘权限 把这个加上

**Comment by JoysKang** [comment]
![CleanShot 2024-11-27 at 09 35 25@2x](https://github.com/user-attachments/assets/8b281e66-7846-49fb-b01a-4e1c2552df84)
找不到 SFMExtension，只找到了 SFM。我应该去哪里找它？

**Comment by yorunning** [comment]
不行重装  第一次打开app时 提示全盘权限时  会引导你给这个扩展的权限  而不是SFM

**Comment by yorunning** [comment]
SFM的全盘访问权限 不加是因为每次打开app会弹框

对使用没有影响

**Comment by JoysKang** [comment]
重装也不行，而且不授权不能启动，启动就会报 
![CleanShot 2024-11-27 at 09 50 45@2x](https://github.com/user-attachments/assets/7838dfb1-5aa0-49cb-85ab-4c859525c97e)
但是去添加又找不到 SFMExtension...
而且我卸载使用 brew install sfm 也一样。
系统是 15.1.1，不知道是不是有影响。

**Comment by yorunning** [comment]
一样的环境 15.1.1 brew 点弹框的授权

**Comment by AlawnCN** [comment]
一样的问题，无限跳这个授权框

**Comment by wang93wei** [comment]
我现在用 1.12.0 beta.33 ，在 macos 26 beta3 也会弹，解决不了

**Comment by ricky0829** [comment]
一样的问题，1.12.4 macos 15.6.1

<img width="2128" height="1236" alt="Image" src="https://github.com/user-attachments/assets/6a4e7364-ce48-47d9-bc4b-01f0ba372165" />

**Comment by yay** [comment]
Same issue here in macOS Tahoe. SFM v1.12.11 installed via Homebrew.

<img width="835" height="921" alt="Image" src="https://github.com/user-attachments/assets/d96f26d7-d97e-4379-9172-87b0b676b9de" />
<img width="835" height="921" alt="Image" src="https://github.com/user-attachments/assets/b86d656a-d7d1-4017-abce-3f0733afa584" />

**Comment by 3k2s** [comment]
为什么唯独sing-box需要full disk access，别的同类软件，以及早期版本都没有这个需求。是否有人可以解释一下。我已经不敢用了。
