### ISSUE TITLE
Feature request: SIGHUP handling

### ISSUE THREAD

**Issue by ghost** [SagerNet/sing-box#23]
I know one can update configs using the Clash API. But such a feature plays well with `systemd.service`'s `ExecReload` and makes life easier.

**Comment by nekohasekai** [comment]
sing-box does not support hot reload, what is the difference between it and restart?

**Comment by nekohasekai** [comment]
Try aa8cdaee2281bdfbd333a8be8a6bf74efa6bff4b

**Comment by nekohasekai** [comment]
Yes, it's completely new instance.

**Comment by nekohasekai** [comment]
What should it do if there is something wrong with the configuration?

**Comment by nekohasekai** [comment]
c91d23b1e77e34f765ff10fbf829e5c47de3cfc5
