### ISSUE TITLE
I feel lost between all the configuration variants

### ISSUE THREAD

**Issue by cornAndFriends** [SagerNet/sing-box#232]
I'm a newbie from Iran and wanted to thank you for this powerful software. I've been reading every page of the documentation these past days and the more I read, the more confused I get. I could setup the shadowsocks examples and it works good.

What is your recommendation for an all around usage? Something that supports both udp and tcp, high performance and won't be detected easily. In the examples there is only shadowsocks and shadowtls, does that mean it's the recommended approach?

Thank you

**Comment by JuanCldCmt** [comment]
Hello,

I'm not the author of this software, but I think I can help you in some ways.

For the first question, I recommend using the [Hysteria mode](https://sing-box.sagernet.org/configuration/outbound/hysteria/), it's easy to setup (I set up that in less than 15 minutes) and meets all your needs. (at least it's true here in China)
Also, this software is a third party implementation of the Hysteria Proxy, if you want to know about how to setup servers, or generally about the protocol, you can check this link out: https://hysteria.network/

For the second question, I personally think it is recommended, The configuration is really simple, although I haven't used the shadowsocks protocol for a long while, so I don't know too much about its performance, etc. I suggest that for now you can use the example config(remember to change the password!), and test if it meets all of your need, and come back later to try more protocols and modes if you feel less confused about this software.

Moreover, I found some resources that might be useful to you, there is a tutorial page for a censorship-circumventing software named `v2ray`, it's different than this, but it is similar. You can get to know how censorship works, how software like this are bypassing it, and how to configure the software to meet your needs.

Hope it helps.
