### ISSUE TITLE
ssh loses connection in tun mode

### ISSUE THREAD

**Issue by imkerberos** [SagerNet/sing-box#2322]
### Operating system

macOS

### System version

15.1.1

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.10.1

Environment: go1.23.2 darwin/arm64
Tags: with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_gvisor
CGO: enabled
```

### Description

When the TUN mode is enabled, the SSH client loses connection if there is no input for 1 second, resulting in the following error: "client_loop: send disconnect: Broken pipe". However, when TUN mode is disabled, no such error occurs.

### Reproduction

```json
{
  "dns": {
    "final": "dns-dhcp",
    "rules": [
      {
        "outbound": "any",
        "server": "dns-dhcp"
      }
    ],
    "servers": [
      {
        "address": "rcode://success",
        "tag": "dns-block"
      },
      {
        "address": "dhcp://auto",
        "tag": "dns-dhcp"
      }
    ],
    "strategy": "prefer_ipv4"
  },
  "experimental": {
    "cache_file": {
      "enabled": true
    },
    "clash_api": {
      "default_mode": "rule",
      "external_controller": "127.0.0.1:9090",
      "external_ui": "ui",
      "external_ui_download_detour": "out-global",
      "external_ui_download_url": "https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip"
    }
  },
  "inbounds": [
    {
      "address": [
        "172.19.0.1/30",
        "fdfe:dcba:9876::1/126"
      ],
      "auto_route": true,
      "mtu": 9000,
      "sniff": true,
      "sniff_override_destination": true,
      "stack": "system",
      "strict_route": false,
      "tag": "in-tun",
      "type": "tun",
      "udp_timeout": "5s"
    }
  ],
  "log": {
    "disabled": false,
    "level": "debug",
    "timestamp": true
  },
  "outbounds": [
    {
      "tag": "out-block",
      "type": "block"
    },
    {
      "tag": "out-direct",
      "type": "direct"
    }
  ],
  "route": {
    "auto_detect_interface": true,
    "final": "out-direct",
    "rule_set": [],
    "rules": []
  }
}
```

ssh config:
```plain
Host lightsail-ap
    User admin
    Hostname xxx.xxx.xxx.xxx
    Port 22
    TCPKeepAlive yes
    ServerAliveInterval 60
    ServerAliveCountMax 100
    IPQoS 0
    IdentityFile ~/.ssh/Lightsail-AP.pem
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by imkerberos** [comment]
resolved with "gvisor" stack.

**Comment by StoneMoe** [comment]
same issue here on Windows 11
SSH clients cannot connect to remote server with "system"/"mixed" stack tun device.
and "gvisor" workaround works

Tested on both OpenSSH_for_Windows_9.5p2 and bitvise SSH Client
