### ISSUE TITLE
wifi_ssid and wifi_bssid not working on GrapheneOS (Pixel 8)

### ISSUE THREAD

**Issue by 21M4TW** [SagerNet/sing-box#2323]
### Operating system

Android

### System version

GrapheneOS 2024112700 Stable Android 15 Pixel 8

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.10.3, tried also with 1.10.1 (SFA-1.10.x-arm64-v8a.apk from GitHub)

### Description

When using "wifi_ssid" or "wifi_bssid" under "route": {"rules"}, sing-box does not seem to detect it properly on my phone. I get the following in the logs:
`INFO[0000] router: updated WIFI state: SSID=<unknown ssid>, BSSID=02:00:00:00:00:00`

My phone is connected to my wifi. I tried the same configuration, but with 1.10.1 and on an old phone running Google Android 11 and both the SSID and BSSID are detected properly.

### Reproduction

Install 1.10.3 on GrapheneOS Android 15 (not sure if it is specific to Pixel 8), allow all location permissions for sing-box, try using the following configuration with your own ssid, and look at the log:

`{
"log": { "level": "info" },
"inbounds": [
{
"type": "socks",
"tag": "socks-in",
"listen": "::",
"listen_port": 8080
}
],
"outbounds": [
{ "type": "direct", "tag": "direct" },
{ "type": "block", "tag": "block" },
{ "type": "dns", "tag": "dns" }
],
"route": {
"final": "direct",
"auto_detect_interface": true,
"rules": [
{
"wifi_ssid": ["myssid"],
"outbound": "direct"
},
{
"ip_is_private": false,
"outbound": "direct"
}
]
}
}`

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by Fei1Yang** [comment]
I'm unable to reproduce this issue on GrapheneOS 15 2024112700 installed on Pixel 8a.

**Comment by 21M4TW** [comment]
> I'm unable to reproduce this issue on GrapheneOS 15 2024112700 installed on Pixel 8a.

Ok, so it could be specific to Pixel 8? Otherwise, what could I be missing? I have the location permissions for sing-box set to "Allow all the time", and I have "Use precise location" activated.

**Comment by 21M4TW** [comment]
> > I'm unable to reproduce this issue on GrapheneOS 15 2024112700 installed on Pixel 8a.
> 
> Ok, so could it be specific to Pixel 8? Otherwise, what could I be missing? I have the location permissions for sing-box set to "Allow all the time", and I have "Use precise location" activated.

Hmm, I just tried it on another Pixel 8 phone with the same OS, but that uses a different VPN app and also has the App Store installed as opposed to the first device, and it works fine on this second device?!

**Comment by 21M4TW** [comment]
I tried uninstalling my VPN app, tried installing the sandbox Google Play app, and I tried putting a SIM card in the phone, but neither of these changes fixed the issue with wifi_ssid. The only thing I have not tried yet is to reinstall the OS from scratch. Any idea of what could be causing this issue? Thanks!

**Comment by 21M4TW** [comment]
Hmm, so I did a factory reset of the phone and after installing sing-box it worked?! This is very mysterious, I don't recall doing anything special with this phone, GrapheneOS had been installed very recently and I had barely used it... Anyway
