### ISSUE TITLE
按照文档的编译命令，编译出来的文件没有插件。

### ISSUE THREAD

**Issue by lin1123** [SagerNet/sing-box#233]
go install -v -tags with_clash_api -tags with_quic github.com/sagernet/sing-box/cmd/sing-box@latest
![image](https://user-images.githubusercontent.com/62827465/202187455-80d23413-3c7f-4bde-92e8-50423aff243a.png)

**Comment by Gzxhwq** [comment]
https://github.com/SagerNet/sing-box/blob/f5c656f79adaf14b1c1c7569381ac239fc30425c/release/local/install.sh#L13

**Comment by lin1123** [comment]
> https://github.com/SagerNet/sing-box/blob/f5c656f79adaf14b1c1c7569381ac239fc30425c/release/local/install.sh#L13

还是没有
![image](https://user-images.githubusercontent.com/62827465/202209508-97dda4e1-72fd-4858-9d8b-01c3119cc00e.png)

**Comment by longmoon77** [comment]
我有闲空，我晚上编译一下看看

**Comment by longmoon77** [comment]
![截图_2022-11-18_08-07-23](https://user-images.githubusercontent.com/62339707/202586585-f2c4a53f-daeb-4457-bf9c-a8c7f90f5fbf.png)

![截图_2022-11-18_08-11-26](https://user-images.githubusercontent.com/62339707/202586919-e99f9387-5049-4f5a-8516-f896d2581fd1.png)

![截图_2022-11-18_08-14-44](https://user-images.githubusercontent.com/62339707/202587310-5c46777b-968e-44eb-893a-1f432bdccc55.png)

![截图_2022-11-18_08-19-12](https://user-images.githubusercontent.com/62339707/202587822-622d287b-df46-404b-a488-22bbc668446e.png)

**Comment by lin1123** [comment]
> ![截图_2022-11-18_08-07-23](https://user-images.githubusercontent.com/62339707/202586585-f2c4a53f-daeb-4457-bf9c-a8c7f90f5fbf.png)
> 
> ![截图_2022-11-18_08-11-26](https://user-images.githubusercontent.com/62339707/202586919-e99f9387-5049-4f5a-8516-f896d2581fd1.png)
> 
> ![截图_2022-11-18_08-14-44](https://user-images.githubusercontent.com/62339707/202587310-5c46777b-968e-44eb-893a-1f432bdccc55.png)
> 
> ![截图_2022-11-18_08-19-12](https://user-images.githubusercontent.com/62339707/202587822-622d287b-df46-404b-a488-22bbc668446e.png)

没插件？

**Comment by longmoon77** [comment]
> > ![截图_2022-11-18_08-07-23](https://user-images.githubusercontent.com/62339707/202586585-f2c4a53f-daeb-4457-bf9c-a8c7f90f5fbf.png)
> > ![截图_2022-11-18_08-11-26](https://user-images.githubusercontent.com/62339707/202586919-e99f9387-5049-4f5a-8516-f896d2581fd1.png)
> > ![截图_2022-11-18_08-14-44](https://user-images.githubusercontent.com/62339707/202587310-5c46777b-968e-44eb-893a-1f432bdccc55.png)
> > ![截图_2022-11-18_08-19-12](https://user-images.githubusercontent.com/62339707/202587822-622d287b-df46-404b-a488-22bbc668446e.png)
> 
> 没插件？

研究测试了一下，虽然执行`sing-box version`时没有显示有额外构建标志，但是按照我上面的图片编译之后，使用了一下发现quic功能是正常的。

**Comment by longmoon77** [comment]
![截图_2022-11-18_09-02-57](https://user-images.githubusercontent.com/62339707/202592623-9fc29404-0edf-40ba-94b8-a6f817cdd141.png)

![截图_2022-11-18_09-04-02](https://user-images.githubusercontent.com/62339707/202592707-7c58269d-5321-45b8-b43f-734b606abb5a.png)

**Comment by yaotthaha** [comment]
切到dev-next分支试试

**Comment by Gzxhwq** [comment]
https://sing-box.sagernet.org/zh/changelog/#11-beta5

1.1-beta5之后才有print tags的功能

**Comment by lin1123** [comment]
我是编译的最新稳定版，命令添加了tags，但是查看版本时tags里面啥都没有。
交叉编译的windows版本clash api本地静态文件，输入127.0.0.7：端口号，不会出现yacd页面。之前用beta版本启动后是正常的。

**Comment by longmoon77** [comment]
![截图_2022-11-18_18-03-43](https://user-images.githubusercontent.com/62339707/202676409-f0fd38ba-b812-4b82-90aa-6e3803d1a69f.png)


![截图_2022-11-18_18-05-14](https://user-images.githubusercontent.com/62339707/202676448-15744f33-fdbf-4cfe-a7a4-4641ca3ea324.png)

**Comment by longmoon77** [comment]
编译命令上图已给出，您的问题已被完成。
