### ISSUE TITLE
Domain names not sent to remotes (outbounds) after `resolve` route action

### ISSUE THREAD

**Issue by john-jane-doe** [SagerNet/sing-box#2330]
### Operating system

Linux

### System version

Ubuntu 20.04.6 LTS (Linux 6.5.0-1025-azure)

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.11.0-beta.4

Environment: go1.23.1 linux/amd64
Tags: with_gvisor,with_dhcp,with_wireguard,with_reality_server,with_clash_api,with_quic,with_utls,with_ech
Revision: 2d4c4e243b213c47b711240e2b7989a1569ae5e8
CGO: enabled
```

### Description

Ideally, the domain name of a request should be resolved remotely to get better performance and to avoid the effect of DNS pollution in local resolution. However, it seems if a request matches a route rule after it hits the `resolve` route action, sing-box will send locally-resolved IP addresses to the remote, instead of the domain name.

### Reproduction

**Steps to reproduce:**

1. Run a simple (mocked) upstream HTTP proxy with the following Go code:

    <details>
    <summary>Source code of mocked HTTP proxy</summary>
    
    ```golang
    package main
    
    import (
	    "fmt"
	    "net/http"
    )
    
    func main() {
        server := &http.Server{
            Addr: "127.0.0.1:8080",
            Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
                if r.Method != "CONNECT" {
                    w.WriteHeader(http.StatusNotImplemented)
                    return
                }
                fmt.Printf("Connecting to %s\n", r.URL)
                w.WriteHeader(http.StatusOK)
                // We are only mocking the CONNECT method instead of actually proxying
            }),
        }
	    server.ListenAndServe()
    }
    ```
    
    </details>

2. Run sing-box with the following configuration:

    <details>
    <summary>sing-box configuration</summary>
    
    ```json
    {
      "log": {
        "level": "info"
      },
      "inbounds": [
        {
          "type": "mixed",
          "listen": "127.0.0.1",
          "listen_port": 7890
        }
      ],
      "outbounds": [
        {
          "type": "http",
          "tag": "http-proxy-mock",
          "server": "127.0.0.1",
          "server_port": 8080
        }
      ],
      "route": {
        "rules": [
          {
            "domain_suffix": [
              ".youtube.com"
            ],
            "outbound": "http-proxy-mock"
          },
          {
            "action": "resolve"
          },
          {
            "domain_suffix": [
              ".google.com"
            ],
            "outbound": "http-proxy-mock"
          }
        ]
      }
    }
    ```
    
    </details>

3. Issue requests to `www.youtube.com` (matching rule before the resolve action) and `www.google.com` (matching rule after the resolve action):

    ```bash
    curl -x socks5h://127.0.0.1:7890 www.youtube.com
    curl -x socks5h://127.0.0.1:7890 www.google.com
    ```

4. Observe output of the mocked upstream HTTP proxy server.

**Expected outcome:**

Whether the domain is resolved locally or not, the domain name (instead of IPs) should be sent to the remote (upstream proxy) to be resolved remotely to get optimal performance and to avoid the effect of DNS pollution.

**Actual outcome:**

If the domain is not resolved locally (e.g. `www.youtube.com` in this example), the domain name is sent to the remote side as desired; otherwise (e.g. `www.google.com` in this example) the resolved IPs will be sent to remote, which is not desired.

Actual output of the mocked upstream proxy server:

```
Connecting to //www.youtube.com:80
Connecting to //172.253.118.106:80  # instead of //www.google.com:80
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by abuits** [comment]
因为他的技术是个大牛，但做人上是个傻逼，我看了很多issue，都是被他直接打个spam

**Comment by nekohasekai** [comment]
Because you shouldn’t be routing based on polluted DNS results.
