### ISSUE TITLE
1.11 beta random crash

### ISSUE THREAD

**Issue by vanes32** [SagerNet/sing-box#2367]
### Operating system

Linux

### System version

RouterOS 7.16.2

### Installation type

Original sing-box Command Line

### Version

```shell
1.11 beta 9
```

### Description

random crash

### Reproduction

![image](https://github.com/user-attachments/assets/ccfd3322-a088-403a-8a61-70533ba44a5f)

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by DeHb86** [comment]
**Operating system**
RouterOS

**System version**
7.16.2

**Installation type**
Docker container from hub.docker.com/r/gzxhwq/sing-box

**If you are using a graphical client, please provide the version of the client.**
Yacd 0.3.7

**Version**
sing-box version 1.11.0-beta.8

**Description**
At random times, regardless of the load, the container falls. The first and subsequent container launches occur without errors in the log.
"local-dns" is an adguardhome container that is also running on the router.

**Reproduction**
The configuration I use is as follows:

```
{
  "log": {
    "disabled": false,
    "level": "error",
    "timestamp": true
  },
  "experimental": {
    "clash_api": {
      "external_ui": "ui",
      "external_controller": "0.0.0.0:9090",
      "external_ui_download_detour": "direct",
      "default_mode": "rule"
    },
    "cache_file": {
      "enabled": true,
      "store_fakeip": true
    }
  },
  "dns": {
    "servers": [
      {
        "tag": "local-dns",
        "address": "10.6.0.2",
        "detour": "direct"
      },
      {
        "tag": "google-dns",
        "address": "tls://8.8.8.8",
        "detour": "direct"
      },
      {
        "tag": "fakeip-dns",
        "address": "fakeip"
      }
    ],
    "rules": [
      {
        "query_type": [
          "HTTPS",
          "SVCB"
        ],
        "action": "reject"
      },
      {
        "query_type": [
          "A"
        ],
        "domain_suffix": [
          "synology.com",
          "synologyupdate.com",
          "habr.com",
          "lenovo.com",
          "intel.com",
          "dnsleaktest.com",
          "whoer.net",
          "ntc.party",
          "amnezia.org"
        ],
        "rule_set": [
          "adguard",
          "adobe",
          "adobe-activation",
          "adobe-ads",
          "discord",
          "facebook",
          "instagram",
          "intel",
          "openai",
          "tmdb",
          "twitter",
          "youtube"
        ],
        "action": "route",
        "server": "fakeip-dns"
      }
    ],
    "strategy": "ipv4_only",
    "fakeip": {
      "enabled": true,
      "inet4_range": "198.18.0.0/15"
    },
    "disable_cache": false,
    "final": "local-dns"
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun",
      "address": "172.19.0.1/30",
      "stack": "system",
      "auto_route": true,
      "auto_redirect": true,
      "strict_route": true
    },
    {
      "type": "direct",
      "tag": "dns-in",
      "listen_port": 53,
      "network": "udp",
      "listen": "0.0.0.0"
    }
  ],
  "route": {
    "rules": [
      {
        "inbound": "dns-in",
        "action": "sniff",
        "sniffer": "dns"
      },
      {
        "inbound": "tun",
        "action": "sniff"
      },
      {
        "protocol": "dns",
        "action": "hijack-dns"
      },
      {
        "rule_set": [
          "adguard",
          "adobe",
          "adobe-activation",
          "adobe-ads",
          "discord",
          "facebook",
          "instagram",
          "intel",
          "openai",
          "tmdb",
          "twitter",
          "youtube"
        ],
        "domain_suffix": [
          "synology.com",
          "synologyupdate.com",
          "habr.com",
          "lenovo.com",
          "intel.com",
          "dnsleaktest.com",
          "whoer.net",
          "ntc.party",
          "amnezia.org"
        ],
        "ip_cidr": [
          "5.200.14.128/25",
          "34.0.0.0/15",
          "34.2.0.0/16",
          "34.3.0.0/23",
          "34.3.2.0/24",
          "35.192.0.0/12",
          "35.208.0.0/12",
          "35.224.0.0/12",
          "35.240.0.0/13",
          "66.22.192.0/18",
          "138.128.136.0/21",
          "162.158.0.0/15",
          "172.64.0.0/13"
        ],
        "action": "route",
        "outbound": "vps-lat"
      }
    ],
    "rule_set": [
      {
        "type": "local",
        "format": "binary",
        "tag": "adguard",
        "path": "/home/adguard.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "adobe",
        "path": "/home/adobe.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "adobe-activation",
        "path": "/home/adobe-activation.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "adobe-ads",
        "path": "/home/adobe-ads.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "discord",
        "path": "/home/discord.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "facebook",
        "path": "/home/facebook.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "instagram",
        "path": "/home/instagram.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "intel",
        "path": "/home/intel.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "openai",
        "path": "/home/openai.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "tmdb",
        "path": "/home/tmdb.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "twitter",
        "path": "/home/twitter.srs"
      },
      {
        "type": "local",
        "tag": "youtube",
        "format": "binary",
        "path": "/home/youtube.srs"
      }
    ],
    "auto_detect_interface": true,
    "final": "direct"
  },
  "outbounds": [
    {
      "tag": "Proxy",
      "outbounds": [
        "vps-lat",
        "vps-hor"
      ],
      "interrupt_exist_connections": true,
      "type": "selector"
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "tag": "vps-lat",
      "server": "xyz",
      "server_port": 443,
      "type": "vless",
      "uuid": "xyz",
      "flow": "xtls-rprx-vision",
      "tls": {
        "enabled": true,
        "insecure": false,
        "server_name": "xyz",
        "reality": {
          "enabled": true,
          "public_key": "xyz",
          "short_id": "xyz"
        },
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      }
    },
    {
      "tag": "vps-hor",
      "server": "xyz",
      "server_port": 443,
      "type": "vless",
      "uuid": "xyz",
      "flow": "xyz",
      "tls": {
        "enabled": true,
        "insecure": false,
        "server_name": "xyz",
        "reality": {
          "enabled": true,
          "public_key": "xyz",
          "short_id": "xyz"
        },
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      }
    }
  ]
}
```

**Logs**

```
 01:35:30 container,info,debug panic: runtime error: invalid memory address or nil pointer dereference
 01:35:30 container,info,debug [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a31e0]
 01:35:30 container,info,debug 
 01:35:30 container,info,debug goroutine 97 [running]:
 01:35:30 container,info,debug github.com/sagernet/sing-box/route.(*dnsHijacker).NewPacketEx(0x0, 0x4000865500, {{{0x0, 0xffffac130002}, {0x400000c300}}, 0x35, {0x0, 0x0}})
 01:35:30 container,info,debug tgithub.com/sagernet/sing-box/route/dns.go:91 +0x50
 01:35:30 container,info,debug github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket(0x40002f8a50, {0x4000efbdc0, 0x1, 0xa7ed0?}, {{{0x0, 0xffff0a0a0c03}, {0x400000c300}}, 0x99d0, {0x0, 0x0}}, ...)
 01:35:30 container,info,debug tgithub.com/sagernet/sing@v0.6.0-beta.5/common/udpnat2/service.go:80 +0x3a4
 01:35:30 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x40000ca180, {0x400041c000, 0x42, 0x2328}, {0x400041c014, 0x2e, 0x2314})
 01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:524 +0x21c
 01:35:30 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4(0x40000ca180, {0x400041c000, 0x42, 0x2328})
 01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:319 +0x204
 01:35:30 container,info,debug github.com/sagernet/sing-tun.(*System).processPacket(0x40000ca180, {0x400041c000?, 0x0?, 0x0?})
 01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:263 +0xf4
 01:35:30 container,info,debug github.com/sagernet/sing-tun.(*System).tunLoop(0x40000ca180)
 01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:188 +0x324
 01:35:30 container,info,debug created by github.com/sagernet/sing-tun.(*System).Start in goroutine 1
 01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:105 +0x64


 04:02:00 container,info,debug panic: runtime error: invalid memory address or nil pointer dereference
 04:02:00 container,info,debug [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a31e0]
 04:02:00 container,info,debug 
 04:02:00 container,info,debug goroutine 14 [running]:
 04:02:00 container,info,debug github.com/sagernet/sing-box/route.(*dnsHijacker).NewPacketEx(0x0, 0x4000b13840, {{{0x0, 0xffffac130002}, {0x40000c42e8}}, 0x35, {0x0, 0x0}})
 04:02:00 container,info,debug tgithub.com/sagernet/sing-box/route/dns.go:91 +0x50
 04:02:00 container,info,debug github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket(0x40002a8150, {0x40009b3dc0, 0x1, 0xa7ed0?}, {{{0x0, 0xffff0a0a0c03}, {0x40000c42e8}}, 0xbae1, {0x0, 0x0}}, ...)
 04:02:00 container,info,debug tgithub.com/sagernet/sing@v0.6.0-beta.5/common/udpnat2/service.go:80 +0x3a4
 04:02:00 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x40004f2000, {0x40001dc000, 0x42, 0x2328}, {0x40001dc014, 0x2e, 0x2314})
 04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:524 +0x21c
 04:02:00 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4(0x40004f2000, {0x40001dc000, 0x42, 0x2328})
 04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:319 +0x204
 04:02:00 container,info,debug github.com/sagernet/sing-tun.(*System).processPacket(0x40004f2000, {0x40001dc000?, 0x0?, 0x0?})
 04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:263 +0xf4
 04:02:00 container,info,debug github.com/sagernet/sing-tun.(*System).tunLoop(0x40004f2000)
 04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:188 +0x324
 04:02:00 container,info,debug created by github.com/sagernet/sing-tun.(*System).Start in goroutine 1
 04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:105 +0x64



 11:58:01 container,info,debug panic: runtime error: invalid memory address or nil pointer dereference
 11:58:01 container,info,debug [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a31e0]
 11:58:01 container,info,debug 
 11:58:01 container,info,debug goroutine 103 [running]:
 11:58:01 container,info,debug github.com/sagernet/sing-box/route.(*dnsHijacker).NewPacketEx(0x0, 0x4000eadc40, {{{0x0, 0xffffac130002}, {0x400000c300}}, 0x35, {0x0, 0x0}})
 11:58:01 container,info,debug tgithub.com/sagernet/sing-box/route/dns.go:91 +0x50
 11:58:01 container,info,debug github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket(0x4000335950, {0x40018d1dc0, 0x1, 0xa7ed0?}, {{{0x0, 0xffff0a0a0c03}, {0x400000c300}}, 0xaa8b, {0x0, 0x0}}, ...)
 11:58:01 container,info,debug tgithub.com/sagernet/sing@v0.6.0-beta.5/common/udpnat2/service.go:80 +0x3a4
 11:58:01 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x4000572000, {0x40007c0000, 0x42, 0x2328}, {0x40007c0014, 0x2e, 0x2314})
 11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:524 +0x21c
 11:58:01 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4(0x4000572000, {0x40007c0000, 0x42, 0x2328})
 11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:319 +0x204
 11:58:01 container,info,debug github.com/sagernet/sing-tun.(*System).processPacket(0x4000572000, {0x40007c0000?, 0x2328?, 0x2328?})
 11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:263 +0xf4
 11:58:01 container,info,debug github.com/sagernet/sing-tun.(*System).tunLoop(0x4000572000)
 11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:188 +0x324
 11:58:01 container,info,debug created by github.com/sagernet/sing-tun.(*System).Start in goroutine 1
 11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:105 +0x64
```

**Comment by Nobita309** [comment]
> **Operating system** RouterOS
> 
> **System version** 7.16.2
> 
> **Installation type** Docker container from hub.docker.com/r/gzxhwq/sing-box
> 
> **If you are using a graphical client, please provide the version of the client.** Yacd 0.3.7
> 
> **Version** sing-box version 1.11.0-beta.8
> 
> **Description** At random times, regardless of the load, the container falls. The first and subsequent container launches occur without errors in the log. "local-dns" is an adguardhome container that is also running on the router.
> 
> **Reproduction** The configuration I use is as follows:
> 
> ```
> {
>   "log": {
>     "disabled": false,
>     "level": "error",
>     "timestamp": true
>   },
>   "experimental": {
>     "clash_api": {
>       "external_ui": "ui",
>       "external_controller": "0.0.0.0:9090",
>       "external_ui_download_detour": "direct",
>       "default_mode": "rule"
>     },
>     "cache_file": {
>       "enabled": true,
>       "store_fakeip": true
>     }
>   },
>   "dns": {
>     "servers": [
>       {
>         "tag": "local-dns",
>         "address": "10.6.0.2",
>         "detour": "direct"
>       },
>       {
>         "tag": "google-dns",
>         "address": "tls://8.8.8.8",
>         "detour": "direct"
>       },
>       {
>         "tag": "fakeip-dns",
>         "address": "fakeip"
>       }
>     ],
>     "rules": [
>       {
>         "query_type": [
>           "HTTPS",
>           "SVCB"
>         ],
>         "action": "reject"
>       },
>       {
>         "query_type": [
>           "A"
>         ],
>         "domain_suffix": [
>           "synology.com",
>           "synologyupdate.com",
>           "habr.com",
>           "lenovo.com",
>           "intel.com",
>           "dnsleaktest.com",
>           "whoer.net",
>           "ntc.party",
>           "amnezia.org"
>         ],
>         "rule_set": [
>           "adguard",
>           "adobe",
>           "adobe-activation",
>           "adobe-ads",
>           "discord",
>           "facebook",
>           "instagram",
>           "intel",
>           "openai",
>           "tmdb",
>           "twitter",
>           "youtube"
>         ],
>         "action": "route",
>         "server": "fakeip-dns"
>       }
>     ],
>     "strategy": "ipv4_only",
>     "fakeip": {
>       "enabled": true,
>       "inet4_range": "198.18.0.0/15"
>     },
>     "disable_cache": false,
>     "final": "local-dns"
>   },
>   "inbounds": [
>     {
>       "type": "tun",
>       "tag": "tun",
>       "address": "172.19.0.1/30",
>       "stack": "system",
>       "auto_route": true,
>       "auto_redirect": true,
>       "strict_route": true
>     },
>     {
>       "type": "direct",
>       "tag": "dns-in",
>       "listen_port": 53,
>       "network": "udp",
>       "listen": "0.0.0.0"
>     }
>   ],
>   "route": {
>     "rules": [
>       {
>         "inbound": "dns-in",
>         "action": "sniff",
>         "sniffer": "dns"
>       },
>       {
>         "inbound": "tun",
>         "action": "sniff"
>       },
>       {
>         "protocol": "dns",
>         "action": "hijack-dns"
>       },
>       {
>         "rule_set": [
>           "adguard",
>           "adobe",
>           "adobe-activation",
>           "adobe-ads",
>           "discord",
>           "facebook",
>           "instagram",
>           "intel",
>           "openai",
>           "tmdb",
>           "twitter",
>           "youtube"
>         ],
>         "domain_suffix": [
>           "synology.com",
>           "synologyupdate.com",
>           "habr.com",
>           "lenovo.com",
>           "intel.com",
>           "dnsleaktest.com",
>           "whoer.net",
>           "ntc.party",
>           "amnezia.org"
>         ],
>         "ip_cidr": [
>           "5.200.14.128/25",
>           "34.0.0.0/15",
>           "34.2.0.0/16",
>           "34.3.0.0/23",
>           "34.3.2.0/24",
>           "35.192.0.0/12",
>           "35.208.0.0/12",
>           "35.224.0.0/12",
>           "35.240.0.0/13",
>           "66.22.192.0/18",
>           "138.128.136.0/21",
>           "162.158.0.0/15",
>           "172.64.0.0/13"
>         ],
>         "action": "route",
>         "outbound": "vps-lat"
>       }
>     ],
>     "rule_set": [
>       {
>         "type": "local",
>         "format": "binary",
>         "tag": "adguard",
>         "path": "/home/adguard.srs"
>       },
>       {
>         "type": "local",
>         "format": "binary",
>         "tag": "adobe",
>         "path": "/home/adobe.srs"
>       },
>       {
>         "type": "local",
>         "format": "binary",
>         "tag": "adobe-activation",
>         "path": "/home/adobe-activation.srs"
>       },
>       {
>         "type": "local",
>         "format": "binary",
>         "tag": "adobe-ads",
>         "path": "/home/adobe-ads.srs"
>       },
>       {
>         "type": "local",
>         "format": "binary",
>         "tag": "discord",
>         "path": "/home/discord.srs"
>       },
>       {
>         "type": "local",
>         "format": "binary",
>         "tag": "facebook",
>         "path": "/home/facebook.srs"
>       },
>       {
>         "type": "local",
>         "format": "binary",
>         "tag": "instagram",
>         "path": "/home/instagram.srs"
>       },
>       {
>         "type": "local",
>         "format": "binary",
>         "tag": "intel",
>         "path": "/home/intel.srs"
>       },
>       {
>         "type": "local",
>         "format": "binary",
>         "tag": "openai",
>         "path": "/home/openai.srs"
>       },
>       {
>         "type": "local",
>         "format": "binary",
>         "tag": "tmdb",
>         "path": "/home/tmdb.srs"
>       },
>       {
>         "type": "local",
>         "format": "binary",
>         "tag": "twitter",
>         "path": "/home/twitter.srs"
>       },
>       {
>         "type": "local",
>         "tag": "youtube",
>         "format": "binary",
>         "path": "/home/youtube.srs"
>       }
>     ],
>     "auto_detect_interface": true,
>     "final": "direct"
>   },
>   "outbounds": [
>     {
>       "tag": "Proxy",
>       "outbounds": [
>         "vps-lat",
>         "vps-hor"
>       ],
>       "interrupt_exist_connections": true,
>       "type": "selector"
>     },
>     {
>       "type": "direct",
>       "tag": "direct"
>     },
>     {
>       "tag": "vps-lat",
>       "server": "xyz",
>       "server_port": 443,
>       "type": "vless",
>       "uuid": "xyz",
>       "flow": "xtls-rprx-vision",
>       "tls": {
>         "enabled": true,
>         "insecure": false,
>         "server_name": "xyz",
>         "reality": {
>           "enabled": true,
>           "public_key": "xyz",
>           "short_id": "xyz"
>         },
>         "utls": {
>           "enabled": true,
>           "fingerprint": "chrome"
>         }
>       }
>     },
>     {
>       "tag": "vps-hor",
>       "server": "xyz",
>       "server_port": 443,
>       "type": "vless",
>       "uuid": "xyz",
>       "flow": "xyz",
>       "tls": {
>         "enabled": true,
>         "insecure": false,
>         "server_name": "xyz",
>         "reality": {
>           "enabled": true,
>           "public_key": "xyz",
>           "short_id": "xyz"
>         },
>         "utls": {
>           "enabled": true,
>           "fingerprint": "chrome"
>         }
>       }
>     }
>   ]
> }
> ```
> 
> **Logs**
> 
> ```
>  01:35:30 container,info,debug panic: runtime error: invalid memory address or nil pointer dereference
>  01:35:30 container,info,debug [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a31e0]
>  01:35:30 container,info,debug 
>  01:35:30 container,info,debug goroutine 97 [running]:
>  01:35:30 container,info,debug github.com/sagernet/sing-box/route.(*dnsHijacker).NewPacketEx(0x0, 0x4000865500, {{{0x0, 0xffffac130002}, {0x400000c300}}, 0x35, {0x0, 0x0}})
>  01:35:30 container,info,debug tgithub.com/sagernet/sing-box/route/dns.go:91 +0x50
>  01:35:30 container,info,debug github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket(0x40002f8a50, {0x4000efbdc0, 0x1, 0xa7ed0?}, {{{0x0, 0xffff0a0a0c03}, {0x400000c300}}, 0x99d0, {0x0, 0x0}}, ...)
>  01:35:30 container,info,debug tgithub.com/sagernet/sing@v0.6.0-beta.5/common/udpnat2/service.go:80 +0x3a4
>  01:35:30 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x40000ca180, {0x400041c000, 0x42, 0x2328}, {0x400041c014, 0x2e, 0x2314})
>  01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:524 +0x21c
>  01:35:30 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4(0x40000ca180, {0x400041c000, 0x42, 0x2328})
>  01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:319 +0x204
>  01:35:30 container,info,debug github.com/sagernet/sing-tun.(*System).processPacket(0x40000ca180, {0x400041c000?, 0x0?, 0x0?})
>  01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:263 +0xf4
>  01:35:30 container,info,debug github.com/sagernet/sing-tun.(*System).tunLoop(0x40000ca180)
>  01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:188 +0x324
>  01:35:30 container,info,debug created by github.com/sagernet/sing-tun.(*System).Start in goroutine 1
>  01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:105 +0x64
> 
> 
>  04:02:00 container,info,debug panic: runtime error: invalid memory address or nil pointer dereference
>  04:02:00 container,info,debug [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a31e0]
>  04:02:00 container,info,debug 
>  04:02:00 container,info,debug goroutine 14 [running]:
>  04:02:00 container,info,debug github.com/sagernet/sing-box/route.(*dnsHijacker).NewPacketEx(0x0, 0x4000b13840, {{{0x0, 0xffffac130002}, {0x40000c42e8}}, 0x35, {0x0, 0x0}})
>  04:02:00 container,info,debug tgithub.com/sagernet/sing-box/route/dns.go:91 +0x50
>  04:02:00 container,info,debug github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket(0x40002a8150, {0x40009b3dc0, 0x1, 0xa7ed0?}, {{{0x0, 0xffff0a0a0c03}, {0x40000c42e8}}, 0xbae1, {0x0, 0x0}}, ...)
>  04:02:00 container,info,debug tgithub.com/sagernet/sing@v0.6.0-beta.5/common/udpnat2/service.go:80 +0x3a4
>  04:02:00 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x40004f2000, {0x40001dc000, 0x42, 0x2328}, {0x40001dc014, 0x2e, 0x2314})
>  04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:524 +0x21c
>  04:02:00 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4(0x40004f2000, {0x40001dc000, 0x42, 0x2328})
>  04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:319 +0x204
>  04:02:00 container,info,debug github.com/sagernet/sing-tun.(*System).processPacket(0x40004f2000, {0x40001dc000?, 0x0?, 0x0?})
>  04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:263 +0xf4
>  04:02:00 container,info,debug github.com/sagernet/sing-tun.(*System).tunLoop(0x40004f2000)
>  04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:188 +0x324
>  04:02:00 container,info,debug created by github.com/sagernet/sing-tun.(*System).Start in goroutine 1
>  04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:105 +0x64
> 
> 
> 
>  11:58:01 container,info,debug panic: runtime error: invalid memory address or nil pointer dereference
>  11:58:01 container,info,debug [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a31e0]
>  11:58:01 container,info,debug 
>  11:58:01 container,info,debug goroutine 103 [running]:
>  11:58:01 container,info,debug github.com/sagernet/sing-box/route.(*dnsHijacker).NewPacketEx(0x0, 0x4000eadc40, {{{0x0, 0xffffac130002}, {0x400000c300}}, 0x35, {0x0, 0x0}})
>  11:58:01 container,info,debug tgithub.com/sagernet/sing-box/route/dns.go:91 +0x50
>  11:58:01 container,info,debug github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket(0x4000335950, {0x40018d1dc0, 0x1, 0xa7ed0?}, {{{0x0, 0xffff0a0a0c03}, {0x400000c300}}, 0xaa8b, {0x0, 0x0}}, ...)
>  11:58:01 container,info,debug tgithub.com/sagernet/sing@v0.6.0-beta.5/common/udpnat2/service.go:80 +0x3a4
>  11:58:01 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x4000572000, {0x40007c0000, 0x42, 0x2328}, {0x40007c0014, 0x2e, 0x2314})
>  11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:524 +0x21c
>  11:58:01 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4(0x4000572000, {0x40007c0000, 0x42, 0x2328})
>  11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:319 +0x204
>  11:58:01 container,info,debug github.com/sagernet/sing-tun.(*System).processPacket(0x4000572000, {0x40007c0000?, 0x2328?, 0x2328?})
>  11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:263 +0xf4
>  11:58:01 container,info,debug github.com/sagernet/sing-tun.(*System).tunLoop(0x4000572000)
>  11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:188 +0x324
>  11:58:01 container,info,debug created by github.com/sagernet/sing-tun.(*System).Start in goroutine 1
>  11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:105 +0x64
> ```

Can I block ads?
