### ISSUE TITLE
开启cloudflare代理的域名会优先使用http/3 (with QUIC)导致域名规则分流失败。

### ISSUE THREAD

**Issue by lvxj11** [SagerNet/sing-box#2369]
使用环境：alpine3.20，sing-box 1.11.0-beta.8

1. 使用cloudflare代理域名，开启速度，优化中HTTP/3（使用 QUIC）选项。（默认为开启）
2. 示例域名：https://www.leisurecloud.link，https://www.qichiyu.com

3. 在不禁用quic的情况下访问域名，不会按域名分流而是按解析到的ip分流。

4. 禁用quic，可以正确按域名分流。

**Comment by yegetables** [comment]
quic协议用 DOMAIN-SUFFIX  匹配不到, 规则集 的  "+.sb" 才能匹配到    
而tcp连接 就可以
补充: 不一定是按ip分流的, 规则集 domain yml "+.sb" 不是 ip规则也匹配到了 @lvxj11
