### ISSUE TITLE
proxy_protocol 的h2无法回落后端

### ISSUE THREAD

**Issue by pmkol** [SagerNet/sing-box#237]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

proxy_protocol 对h2的支持存在问题
当配置h2回落后端后
开启proxy_protocol true时，回落到nginx无法连接，访问域名失效
关闭proxy_protocol false时，回落到nginx正常，访问域名成功

之前有反馈这个问题，看在beta14中有修复h2c，但经过测试依旧有问题。

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```
beta15
</details>

### Server and client configuration file

<details>

```{
  "log": {
    "level": "error",
    "output": "/etc/sing-box/error.log",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "address": "208.67.222.222"
      }
    ]
  },
  "inbounds": [
    {
      "type": "trojan",
      "tag": "trojan-in",
      "listen": "0.0.0.0",
      "listen_port": 443,
      "proxy_protocol": true,
      "proxy_protocol_accept_no_header": true,
      "tcp_fast_open": true,
      "users": [
        {
          "name": "xxxxxx",
          "password": "xxxxxx"
        }
      ],
      "tls": {
        "enabled": true,
        "server_name": "xxx.com",
        "alpn": [
          "h2",
          "http/1.1"
        ],
        "min_version": "1.2",
        "max_version": "1.3",
        "acme": {
          "domain": ["xxx.com"],
          "data_directory": "/etc/sing-box",
          "email": "mail@xxx.com",
          "provider": "letsencrypt"
        }
      },
      "fallback_for_alpn": {
        "http/1.1": {
        "server": "127.0.0.1",
        "server_port": 80
        },
        "h2": {
        "server": "127.0.0.1",
        "server_port": 8080
        }
      }
    }
  ]
}
```
nginx server段
```
    server {
        listen       80 proxy_protocol;
        listen       8080 proxy_protocol http2;
        server_name  localhost;
        location / {
            root   html;
            index  index.html index.htm;
        }
    }
```

</details>

### Server and client log file

<details>

```console
+0800 2022-11-20 21:57:56 ERROR inbound/trojan[trojan-in]: accept: proxyproto: proxy protocol signature not present
```

</details>

**Comment by H1JK** [comment]
reminder: 1.1-beta14 h2c fix is not related to trojan fallbacks, it's for v2ray transport h2 & grpc lite server side h2c listening.  
btw, I think the `proxy_protocol` is for inbound connection only, it would not fallback with proxy protocol header.

**Comment by pmkol** [comment]
> reminder: 1.1-beta14 h2c fix is not related to trojan fallbacks, it's for v2ray transport h2 & grpc lite server side h2c listening. btw, I think the `proxy_protocol` is for inbound connection only, it would not fallback with proxy protocol header.

谢谢，beta14的问题清楚了

经过测试
开启proxy_protocol 用于http1.1时，是可以正确回落nginx的
开启proxy_protocol 用于h2时，无法回落nginx

而我使用xray测试，h2+proxy_protocol模式也是可以正确回落nginx的
所以sing-box只需要修复h2+proxy_protocol无法回落的问题就可以了

**Comment by nekohasekai** [comment]
没有提供 proxy_protocol 与 fallback 的兼容性保证，请自行调试。

**Comment by nekohasekai** [comment]
您可能需要咨询提供该 proxy_protocol 功能 pull request 的作者。
