### ISSUE TITLE
UDP support for SSH outbound

### ISSUE THREAD

**Issue by rojer** [SagerNet/sing-box#2374]
SSH provides very good encapsulation and stealthiness but unfortunately does not support UDP directly.
My suggestion is to implement a TCP-to-UDP conversion on the client side, working with a server-side bridge.
A streaming gRPC channel can be used to encapsulate a UDP session:

UDP to 1.2.3.4:5678 ----> | TUN inbound -> sing-box client -> TCP gRPC to 127.0.0.1:9876 | ---- SSH ---> | server  -> sing-box TCP gRPC service on 127.0.0.1:9876 | ----> UDP to 1.2.3.4:5678

**Comment by rojer** [comment]
if the idea sounds good, i can help with implementation

**Comment by mazzz1y** [comment]
[udp-over-tcp](https://sing-box.sagernet.org/configuration/shared/udp-over-tcp)

**Comment by rojer** [comment]
thank you, good to know! yeah, adding support for `udp_over_tcp` to SSH would be nice.
performance is pretty decent, especially if multiplexed over multiple connections/outbounds (i use 4).
the advantage is that it needs zero support on the server side (for TCP-only service at least).
