### ISSUE TITLE
packet-tunnel error 

### ISSUE THREAD

**Issue by hokifungcalvin** [SagerNet/sing-box#2375]
### 操作系统

iOS

### 系统版本

iOS 16.7.10

### 安装类型

sing-box for iOS 图形客户端程序

### 描述

Sing-box for iOS error 

### 重现方式

(packet-tunnel) error: start service: initialize rule-

set [17]: initial rule-set: geosite-category-ads-all: Get

"https://ghp.ci/https://raw.githubusercontent.com/

MetaCubeX/meta-rules-dat/sing/geo/geosite/category-ads-

all.srs": read tcp 192.168.1.6:49707->144.24.83.236:443:

read: connection reset by peer | initialize rule-

set[17]: initial rule-set: geosite-google: Get "https://

ghp.ci/https://raw.githubusercontent.com/MetaCubeX/meta-

rules-dat/sing/geo/geosite/google.srs": read tcp

192.168.1.6:49706->144.24.83.236:443: read: connection

reset by peer | initialize rule-set [17]: initial rule-

set: geoip-cn: Get "https://ghp.ci/https://

raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/

geo/geoip/cn.srs": initialize rule-set [17]: initial

rule-set: geosite-category-ads-all: Get "https://ghp.ci/

https://raw.githubusercontent.com/MetaCubeX/meta-rules-

dat/sing/geo/geosite/category-ads-all.srs": read tcp

192.168.1.6:49707->144.24.83.236:443: read: connection

reset by peer | initialize rule-set [17]: initial rule-

set: geosite-github: Get "https://ghp.ci/https://

raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/

geo/geosite/github.srs": initialize rule-set [17]:

initial rule-set: geosite-category-ads-all:

Get

"https://ghp.ci/https://raw.githubusercontent.com/

MetaCubeX/meta-rules-dat/sing/geo/geosite/category-ads-

all.srs": read tcp 192.168.1.6:49707->144.24.83.236:443:

read: connection reset by peer | initialize rule-

set[17]: initial rule-set: geosite-apple: Get "https://

ghp.ci/https://raw.githubusercontent.com/MetaCubeX/meta-

rules-dat/sing/geo/geosite/apple.srs": initialize rule-

set [17]: initial rule-set: geosite-category-ads-all: Get

"https://ghp.ci/https://raw.githubusercontent.com/

MetaCubeX/meta-rules-dat/sing/geo/geosite/category-ads-

all.srs": read tcp 192.168.1.6:49707->144.24.83.236:443:

read: connection reset by peer

### 支持我们

- [X] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by leechaojie** [comment]
我也遇到了相同的问题，但我看你关闭了 issues，你是如何解决的呢？我昨晚打开突然就不行了，弹窗提示了相同的错误。
