### ISSUE TITLE
无分流规则，启动正常，仅访问国内网络，报错无法连接

### ISSUE THREAD

**Issue by tttbaolattt** [SagerNet/sing-box#2386]
### 操作系统

Android

### 系统版本

Android 14 / OneUI 6.1

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.11.0-beta.12

### 描述

无分流规则，启动正常，仅访问国内网络，报错无法连接。
退回 1.11.0-beta.9 正常。
已提供本地可复现最简配置。
![Screenshot_20241221_230749_sing-box](https://github.com/user-attachments/assets/e2332d6e-d3cd-4043-9de1-e5f1a3e96b40)

### 重现方式

```
{
  "log": {
    "level": "error"
  },
  "dns": {
    "strategy": "ipv4_only",
    "servers": [
      {
        "address": "tls://223.5.5.5"
      }
    ]
  },
  "inbounds": [
    {
      "type": "tun",
      "address": [
        "172.18.0.1/30"
      ],
      "stack": "system",
      "auto_route": true,
      "strict_route": true
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    }
  ],
  "route": {
    "rules": [
      {
        "type": "logical",
        "mode": "or",
        "rules": [
          {
            "protocol": "dns"
          },
          {
            "port": 53
          }
        ],
        "action": "hijack-dns"
      }
    ],
    "auto_detect_interface": true
  }
}
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by nekohasekai** [comment]
试试 https://github.com/SagerNet/sing-box/actions/runs/12452178463

**Comment by tttbaolattt** [comment]
> 试试 https://github.com/SagerNet/sing-box/actions/runs/12452178463/artifacts/2352975700

已尝试，依旧报错，网络无法连接

**Comment by nekohasekai** [comment]
#2384
