### ISSUE TITLE
稳定版能否取消那几个升级弃用的提示，或者减少到一次，提示N次一点意义都没有。

### ISSUE THREAD

**Issue by kumagaya68** [SagerNet/sing-box#2387]
穩定内核1.10.5，手机运行4-5个提示，之后停在开始界面，此时已经可以外访了。正常外访时应该是个方块的停止图标。安卓9盒子，第一次升级后启动，直接蹦了，第二次才正常加载。关键是那个提示，不点确定还无法进行下一步，已经是鸡肋似的提示了，有时点不上确定的按钮，不知为何，程序就直接蹦了。这种状况就是前几个版本的共同的问题。1.10.4改善了很多，但1.10.5貌似提示又多起来了。点不上确定那个按钮的意思不是不点，而是点在确定按钮上无反应的意思。那按钮犹如死了似的。提示对于手机还好操作点，但对于电视盒子，那个提示可是要了命了，飞鼠，遥控器，找到确定这个按钮，点确定响应了还好，点击完确定根本无反应那才叫崩溃。还有我的节点是从网站上扫描最新的二维码生成的，仍然被识别为老配置。

**Comment by nekohasekai** [comment]
你也配让开源项目兼容垃圾黑产
