### ISSUE TITLE
Fakeip will cause disconnection and must be refreshed manually

### ISSUE THREAD

**Issue by AtticusZeller** [SagerNet/sing-box#2395]
### Operating system

Linux

### System version

1.11.beta13

### Installation type

Original sing-box Command Line

### Description

The fakeip mechanism will cause the connection to be automatically disconnected after a long period of use, and you need to refresh it manually each time

Remove fakeip automatic recovery

And the waiting time for the first connection after fakeip boot is very long

###  Reproduction

Configured according to the official website

[Document](https://sing-box.sagernet.org/manual/proxy/client/#basic-tun-usage-for-chinese-users)

For fakeip configuration, only the dns part is referenced, and the rest are the latest configurations in the document, without any abandoned configurations

[Cache file](https://sing-box.sagernet.org/configuration/experimental/cache-file/) configures store_fakeip

Inbound is tun mode

### Logs

```shell
The log does not show obvious abnormalities, except that some connections are unreachable
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default  values.  
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data. 
 - [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software. 
 - [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by AtticusZeller** [comment]
delete the issue if you have no plan for it

Thank you so much for gorgeous work

**Comment by nekohasekai** [comment]
#
