### ISSUE TITLE
Add language selection and Russian language support in Sing Box

### ISSUE THREAD

**Issue by dtkoe** [SagerNet/sing-box#2397]
### Operating system

Android

### System version

13

### Installation type

sing-box for Android Graphical Client

### Version

```shell
google play
```

### Description

Hello,

I would like to report an issue. For Russian users, the Sing Box app defaults to the Chinese language, which makes it difficult to use.

It would be great if you could add a language selection feature in the app and include Russian as one of the supported languages. I am happy to assist with the translation into Russian if needed.

Thank you for your app and for considering this feedback!

### Reproduction

start app

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
Can't reproduce on the emulator and my device. It should be noted that Android 13 already has the ability to set the language for each app separately.
