### ISSUE TITLE
tun network card printed a large number of DNS 53 port logs

### ISSUE THREAD

**Issue by ztj1993** [SagerNet/sing-box#2398]
### Operating system

Windows

### System version

1.11.0-beta.14

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.11.0-beta.14

Environment: go1.23.4 windows/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: 4f8b382fb3cbe9c889c8d78dae8755a1955d8d06
CGO: disabled
```

### Description

I used a Tun network card with the following configuration:
```
{
    "log": {
        "level": "debug",
        "timestamp": true
    },
    "inbounds": [
        {
            "type": "tun",
            "address": [
                "172.18.0.1/30"
            ],
            "route_address": [
                "192.168.120.0/24"
            ],
            "auto_route": true,
            "strict_route": false
        }
    ],
    "outbounds": [
        {
            "type": "socks",
            "tag": "xsc-out",
            "server": "[2408:8220::1]",
            "server_port": 1080,
            "username": "***",
            "password": "***",
            "version": "5"
        }
    ],
    "route": {
        "rules": [
            {
                "ip_cidr": [
                    "192.168.120.0/24"
                ],
                "outbound": "xsc-out"
            }
        ]
    }
}
```
After running .\sing-box.exe -c .\vpn.json run, countless DNS 53 logs are printed as follows:
```
+0800 2024-12-25 16:12:06 INFO [1144447787 0ms] inbound/tun[0]: inbound packet connection from 172.18.0.1:62218
+0800 2024-12-25 16:12:06 INFO [1144447787 0ms] inbound/tun[0]: inbound packet connection to 172.18.0.2:53
+0800 2024-12-25 16:12:06 INFO [1144447787 1ms] outbound/socks[xsc-out]: outbound packet connection to 172.18.0.2:53
+0800 2024-12-25 16:12:06 INFO [555040649 0ms] inbound/tun[0]: inbound packet connection from 172.18.0.1:63362
+0800 2024-12-25 16:12:06 INFO [555040649 0ms] inbound/tun[0]: inbound packet connection to 172.18.0.2:53
+0800 2024-12-25 16:12:06 INFO [555040649 0ms] outbound/socks[xsc-out]: outbound packet connection to 172.18.0.2:53
+0800 2024-12-25 16:12:06 ERROR [555040649 186ms] connection: listen outbound packet connection: socks5: request rejected, code=7
+0800 2024-12-25 16:12:06 ERROR [1144447787 189ms] connection: listen outbound packet connection: socks5: request rejected, code=7
+0800 2024-12-25 16:12:06 INFO [3937215563 0ms] inbound/tun[0]: inbound packet connection from 172.18.0.1:62218
+0800 2024-12-25 16:12:06 INFO [2540350280 0ms] inbound/tun[0]: inbound packet connection from 172.18.0.1:63362
+0800 2024-12-25 16:12:06 INFO [2540350280 0ms] inbound/tun[0]: inbound packet connection to 172.18.0.2:53
+0800 2024-12-25 16:12:06 INFO [3937215563 0ms] inbound/tun[0]: inbound packet connection to 172.18.0.2:53
+0800 2024-12-25 16:12:06 INFO [2540350280 0ms] outbound/socks[xsc-out]: outbound packet connection to 172.18.0.2:53
+0800 2024-12-25 16:12:06 INFO [3937215563 1ms] outbound/socks[xsc-out]: outbound packet connection to 172.18.0.2:53
```

How can I optimize my configuration to prevent these 172.18.0.2:53 logs from being printed, or how can I configure it to suppress this log?

### Reproduction

Refer to the description content.

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by devopg** [comment]
change your log level to other ex: warm, error
```
 "log": {
        "level":
```

**Comment by ztj1993** [comment]
我还需要一定的 INFO 日志，只是这个 dns 日志导致我的日志文件太庞大了

**Comment by ztj1993** [comment]
@nekohasekai @devopg Or a more specific demand, how can DNS not use Tun network card.

**Comment by ztj1993** [comment]
@devopg @nekohasekai 
I still think this is an issue. After detailed testing, I found that removing "auto_route": true prevents these logs from being printed. Then I checked the routing and found this route: 192.168.120.0 255.255.255.0 172.18.0.2 172.18.0.1 0. I noticed an anomaly with the tun network interface configuration.

I reconfigured my network interface and cleared the DNS setting to 172.18.0.2 (DNS set to auto). After that, the logs mentioned above stopped printing, and the error log ERROR [555040649 186ms] connection: listen outbound packet connection: socks5: request rejected, code=7 is also gone.
------
我仍然认为这是一个问题，经过详细的测试，去掉  `"auto_route": true` 后不会打印这些日志，然后我查看了路由，发现了 `192.168.120.0    255.255.255.0         172.18.0.2         172.18.0.1      0` 这条路由，我发现了 tun 网卡的配置异常。

我重新配置了我的网卡，清理了 dns = 172.18.0.2 (dns 设置为 auto) 后，上面的那些日志不在打印了，这个错误日志 `ERROR [555040649 186ms] connection: listen outbound packet connection: socks5: request rejected, code=7` 也没有了。

**Comment by ztj1993** [comment]
If my tun network interface has IP = 172.18.0.1 and DNS = 172.18.0.2, any local request will print the following log (note: the requests do not go through the sing-box proxy): 

```
+0800 2024-12-26 12:55:13 ERROR [3804489488 219ms] connection: listen outbound packet connection: socks5: request rejected, code=7
+0800 2024-12-26 12:55:13 INFO [3030403468 0ms] inbound/tun[0]: inbound packet connection from 172.18.0.1:54616
+0800 2024-12-26 12:55:13 INFO [3030403468 0ms] inbound/tun[0]: inbound packet connection to 172.18.0.2:53
+0800 2024-12-26 12:55:13 INFO [3030403468 0ms] outbound/socks[xsc-out]: outbound packet connection to 172.18.0.2:53
+0800 2024-12-26 12:55:13 ERROR [3030403468 201ms] connection: listen outbound packet connection: socks5: request rejected, code=7
+0800 2024-12-26 12:55:15 INFO [869215570 0ms] inbound/tun[0]: inbound packet connection from 172.18.0.1:53536
+0800 2024-12-26 12:55:15 INFO [869215570 0ms] inbound/tun[0]: inbound packet connection to 172.18.0.2:53
+0800 2024-12-26 12:55:15 INFO [869215570 0ms] outbound/socks[xsc-out]: outbound packet connection to 172.18.0.2:53
+0800 2024-12-26 12:55:15 ERROR [869215570 212ms] connection: listen outbound packet connection: socks5: request rejected, code=7
```

After setting the tun network interface to IP = auto and DNS = auto, these logs no longer print.

**Comment by ztj1993** [comment]
@nekohasekai Please reopen this issue.
