### ISSUE TITLE
侧边栏关闭开启窗口会移动

### ISSUE THREAD

**Issue by helson-lin** [SagerNet/sing-box#2408]
### 操作系统

macOS

### 系统版本

15.1

### 安装类型

sing-box for macOS 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

版本1.10.5 (1)

### 描述

![Shot2024-12-December-nJZjaUHG](https://github.com/user-attachments/assets/aef165a9-c5e3-410f-a4e6-041b773cce65)

### 重现方式

点击关闭侧边栏按钮，然后再打开。多次操作，窗口位移。

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by nekohasekai** [comment]
对此没有什么可做的。如果你非常在意这个，自己修复它并打开一个 PR。
