### ISSUE TITLE
异常的sniff导致fakeip被当作目标地址发送

### ISSUE THREAD

**Issue by ashes-777** [SagerNet/sing-box#2409]
### 操作系统

Linux

### 系统版本

ImmortalWrt 23.05.1

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.11.0-beta.15

Environment: go1.23.4 linux/arm64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: e5fc7178196898c2b91019b3d7dd50fcdd93d8ea
CGO: disabled
```

### 描述

观察日志发现，sniff既未成功也未超时，同时fakeip被当作目标地址发送到了服务端。
若不执行sniff,则功能正常

### 重现方式

跑speedtest测速即可复现
```
{
    "dns": {
        "servers": [
            {
                "tag": "local",
                "address": "223.5.5.5",
                "detour": "direct"
            },
            {
                "tag": "fakeip",
                "address": "fakeip"
            }
        ],
        "rules": [
            {
                "outbound": "any",
                "server": "local"
            },
            {
                "query_type": "A",
                "server": "fakeip"
            }
        ],
        "fakeip": {
            "enabled": true,
            "inet4_range": "198.18.0.0/15"
        },
        "strategy": "ipv4_only",
        "independent_cache": true
    },
    "inbounds": [
        {
            "type": "tun",
            "tag": "tun-in",
            "mtu": 9000,
            "address": "172.18.0.1/30",
            "auto_route": true,
            "auto_redirect": true,
            "strict_route": true,
            "stack": "mixed",
            "endpoint_independent_nat": true
        }
    ],
    "outbounds": [
        {
            "type": "hysteria2"
        },
        {
            "type": "direct",
            "tag": "direct"
        }
    ],
    "route": {
        "rules": [
            {
                "port": 53,
                "action": "hijack-dns"
            },
            {
                "action": "sniff",
                "sniffer": [
                    "stun",
                    "bittorrent",
                    "dtls"
                ],
                "timeout": "10ms"
            },
            {
                "ip_is_private": true,
                "rule_set": [
                    "geoip-cn",
                    "geosite-geolocation-cn"
                ],
                "outbound": "direct"
            }
        ],
        "rule_set": [
            {
                "type": "remote",
                "tag": "geosite-geolocation-cn",
                "format": "binary",
                "url": "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-cn.srs"
            },
            {
                "type": "remote",
                "tag": "geoip-cn",
                "format": "binary",
                "url": "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs"
            }
        ],
        "auto_detect_interface": true
    },
    "experimental": {
        "cache_file": {
            "enabled": true,
            "store_fakeip": true
        }
    }
}
```

### 日志

```shell
##客户端日志
+0000 2024-12-27 02:27:22 DEBUG router: found fakeip domain: speedtest.race.com
+0000 2024-12-27 02:27:22 INFO [1929063794 0ms] inbound/tun[tun-in]: inbound packet connection from 192.168.31.98:39279
+0000 2024-12-27 02:27:22 INFO [1929063794 0ms] inbound/tun[tun-in]: inbound packet connection to 198.18.0.33:41248
+0000 2024-12-27 02:27:22 DEBUG [1929063794 0ms] router: found fakeip domain: speedtest.race.com
+0000 2024-12-27 02:27:22 DEBUG [1929063794 0ms] router: match[1] => sniff(stun,bittorrent,dtls,10ms)
+0000 2024-12-27 02:27:22 INFO [1929063794 0ms] outbound/hysteria2[]: outbound packet connection to 198.18.0.33:41248

##服务端日志
-0500 2024-12-26 21:27:22 INFO [2297487696 0ms] inbound/hysteria2[hy2-in]: inbound packet connection from [::ffff:x.x.x.x]:52246
-0500 2024-12-26 21:27:22 INFO [2297487696 1ms] inbound/hysteria2[hy2-in]: [] inbound packet connection to 198.18.0.33:41248
-0500 2024-12-26 21:27:22 INFO [2297487696 4ms] outbound/direct[direct]: outbound packet connection
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by nekohasekai** [comment]
试试 1.11.0-beta.16

**Comment by AaA197588** [comment]
在哪里下载最新版本

ashes-777 ***@***.***> 于 2024年12月28日周六 19:44写道：

**Comment by Dr4tez** [comment]
> > 试试 1.11.0-beta.16
> 
> 已经成功修复了！

您在1.11.0版本中再次遇到了这个问题吗？我想我在 1.11.0 上遇到了同样的问题。同时，有超过1000个连接同时处于活动状态，这就是为什么路由器的处理器负载几乎达到100％。没有这个问题的最新版本是1.11.0-beta.20

`+0300 2025-01-31 21:55:48 DEBUG router: found fakeip domain: update.googleapis.com
+0300 2025-01-31 21:55:48 DEBUG [3997708164 0ms] router: sniffed packet protocol: quic, client: chromium
+0300 2025-01-31 21:55:48 INFO [927211628 0ms] inbound/tun[tunin]: inbound packet connection from 172.19.0.1:46832
+0300 2025-01-31 21:55:48 INFO [927211628 0ms] inbound/tun[tunin]: inbound packet connection to 198.18.0.5:443
+0300 2025-01-31 21:55:48 INFO [3997708164 0ms] outbound/direct[direct]: outbound packet connection
+0300 2025-01-31 21:55:48 DEBUG [927211628 0ms] router: found fakeip domain: optimizationguide-pa.googleapis.com
+0300 2025-01-31 21:55:48 DEBUG [927211628 0ms] router: match[0] => sniff
+0300 2025-01-31 21:55:48 DEBUG [927211628 0ms] router: sniffed packet protocol: quic, client: chromium
+0300 2025-01-31 21:55:48 INFO [1961734035 0ms] inbound/tun[tunin]: inbound packet connection from 172.19.0.1:45180
+0300 2025-01-31 21:55:48 INFO [1961734035 0ms] inbound/tun[tunin]: inbound packet connection to 198.18.0.5:443
+0300 2025-01-31 21:55:48 INFO [927211628 0ms] outbound/direct[direct]: outbound packet connection
+0300 2025-01-31 21:55:48 DEBUG [1961734035 0ms] router: found fakeip domain: optimizationguide-pa.googleapis.com
+0300 2025-01-31 21:55:48 DEBUG [1961734035 0ms] router: match[0] => sniff
+0300 2025-01-31 21:55:48 INFO [3526770370 0ms] inbound/tun[tunin]: inbound packet connection from 172.19.0.1:48725
+0300 2025-01-31 21:55:48 INFO [3526770370 0ms] inbound/tun[tunin]: inbound packet connection to 198.18.0.8:443`
