### ISSUE TITLE
request feture multiple inbound support on same port with different path

### ISSUE THREAD

**Issue by degidevops** [SagerNet/sing-box#244]
Can add multiple inbound support on same port like vmess ws tls + trojan ws tls on port 443 like feture configuration on [Xray Examples](https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-WHATEVER)? this may help for creating multiple protocol inbound on same port with different path.

**Comment by nekohasekai** [comment]
No
