### ISSUE TITLE
FATAL[0000] decode config: inbound options: json: unknown field "inet4_route_address"

### ISSUE THREAD

**Issue by leeaash** [SagerNet/sing-box#245]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

Tun inbound 配置 "inet4_route_address" 时启动报错

### Version of sing-box

<details>
1.06 and 1.07
```console
$ sing-box version
# Paste output here
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```
client configuation

{
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "interface_name": "tun0",
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "mtu": 9000,
      "auto_route": true,
      "strict_route": true,
      "inet4_route_address": "172.16.3.125/32"
    }
  ]
}

</details>

### Server and client log file

<details>

```console
# paste log here
```
FATAL[0000] decode config: inbound options: json: unknown field "inet4_route_address"
FATAL[0000] decode config: inbound options: json: unknown field "inet4_route_address"

</details>

**Comment by nekohasekai** [comment]
文档的版本是最新。稳定版本不会合并新功能。

**Comment by leeaash** [comment]
> 

我需要用beta版？
