### ISSUE TITLE
Feature request: Search assets in XDG Base Directory by default for Linux

### ISSUE THREAD

**Issue by attrr** [SagerNet/sing-box#25]
Hi, 
Currently, sing-box only searches assets in the current working directory by default.
It would be nice to also search for other directories by default:
- `$XDG_DATA_DIRS/sing-box` or `/usr/local/share/sing-box` or `/usr/share/sing-box`
- `$XDG_DATA_HOME/sing-box` or `~/.local/share/sing-box`
- `that same path as executable`

Also, download assets to `$XDG_DATA_HOME/sing-box` or `~/.local/share/sing-box` by default might be a good idea.
ref: https://github.com/v2fly/v2ray-core/pull/1578

**Comment by nekohasekai** [comment]
It already exists.

```
/etc/config/sing-box
/usr/local/etc/
/usr/share
/usr/local/share
$HOME/.local/share
$XDG_CONFIG_HOME
$XDG_CACHE_HOME
```
