### ISSUE TITLE
部署完 sing-box 后无法自行修改默认密码？

### ISSUE THREAD

**Issue by ssydb** [SagerNet/sing-box#251]
系统为 debian 10 采用的是 deb 格式方式拉取和部署 完成自行修改密码 restart 后报错 填回默认密码 restart 后又正常 无论配置采用是原始配置 还是依照自己在网上收集的其他大佬的配置均出现不能修改默认密码的问题 其他修改都没有问题.... 

sing-box 版本为 1.0.7

所谓的默认密码 即为部署完 sing-box 后自动生成的 config.json 文件里面的那个密码...

**Comment by fs8vsx59h** [comment]
部分协议有密码格式和长度要求
例如ss需要16位base64密码

**Comment by ssydb** [comment]
感谢 解决了 之前用 lastpass 算的密码一直不成功原来是格式和强度不对...
