### ISSUE TITLE
139.155.59.177:4443: wsarecv: An existing connection was forcibly closed by the  remote host.

### ISSUE THREAD

**Issue by isaac574** [SagerNet/sing-box#254]
WIN7 下运行，不能连上YOUTUBE;
SING-BOX版本 1.0.7

不过在一台新装WIN7系统的机子可以运行，无以上错误。
不知如何解决？

兹附上CONFIG.JSON
{
  "inbounds": [
    {
      "type": "mixed",
      "listen_port": 10810,
      "sniff": true,
      "set_system_proxy": true
    }
  ],
  "outbounds": [
    {
      "type": "shadowsocks",
      "method": "2022-blake3-aes-128-gcm",
      "password": "5JCsPssfgS8tiRwiMlhAR5==",
      "detour": "shadowtls-out",
      "multiplex": {
        "enabled": true,
        "max_connections": 4,
        "min_streams": 4
      }
    },
    {
      "type": "shadowtls",
      "tag": "shadowtls-out",
      "server": "139.155.59.177",
      "server_port": 4443,
      "tls": {
        "enabled": true,
        "server_name": "bing.com"
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    }
  ],
  "route": {
    "rules": [
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "geosite": "cn",
        "geoip": "cn",
        "outbound": "direct"
      }
    ]
  }
}

**Comment by 70599** [comment]
注意隐藏自己的IP

**Comment by isaac574** [comment]
谢了，已作伪装。
