### ISSUE TITLE
希望支持 provider 或 订阅。

### ISSUE THREAD

**Issue by laincat** [SagerNet/sing-box#263]
没有订阅，手动更新起来太麻烦了。

希望能支持节点订阅(Node list)，让他优雅并安静的工作在小机器里。（docker，或者虚拟机）

拜托了。

**Comment by simplerick-simplefun** [comment]
同求。有订阅的话能方便很多，一个节点出了问题能无缝切换。

**Comment by xaotag** [comment]
同求。json都写了600行有的话 确实方便

**Comment by DustinWin** [comment]
真的很需要这个功能。
