### ISSUE TITLE
V2ray API

### ISSUE THREAD

**Issue by Erdisam** [SagerNet/sing-box#270]
Hello, I am tryin to learn stuff but cant quite figure out how to use th V2ray Grpc Api

It errors me out by: "unknown service experimental.v2rayapi.StatsService"

**Comment by Erdisam** [comment]
I am also using the sing-box-dev\experimental\v2rayapi\stats.proto in Postman

**Comment by nekohasekai** [comment]
This interface is made to be compatible with v2ray, please check the API client of v2ray to learn how to use it.

**Comment by h3110w0r1d-y** [comment]
need change package name in `stats.proto ` from `experimental.v2rayapi` to `v2ray.core.app.stats.command`

**Comment by xvv6u577** [comment]
> need change package name in `stats.proto ` from `experimental.v2rayapi` to `v2ray.core.app.stats.command`

Good to find someone who knows how to use it. could you give more hints?
