### ISSUE TITLE
Incorrect semantic version v1.1

### ISSUE THREAD

**Issue by mazzz1y** [SagerNet/sing-box#276]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

`go install` not working with incorrect semantic version.

### Actual
```bash
~ go install github.com/sagernet/sing-box/cmd/sing-box@v1.1 
go: github.com/sagernet/sing-box/cmd/sing-box@v1.1: no matching versions for query "v1.1"
```

### Expected
command above works

### Expected solution
create `v1.1.0` tag

### Additional info
Refer to https://github.com/golang/go/issues/37529#issuecomment-592301127

**Comment by nekohasekai** [comment]
Created.

**Comment by mazzz1y** [comment]
Best!
