### ISSUE TITLE
客户端模式运行时可以设置排除局域网地址吗？

### ISSUE THREAD

**Issue by raycke** [SagerNet/sing-box#279]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

Hi,

请问客户端模式运行时可以设置排除局域网地址吗？比如192.168段

<img width="673" alt="image" src="https://user-images.githubusercontent.com/70388114/206088866-5e28596d-17f9-45f2-8f72-9becbea737a2.png">

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here

PS D:\sing> .\sing.exe version
sing-box version 1.1

Environment: go1.19.3 windows/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: df3b130dc9a16211d7a68ab7737fd96695b4dec2
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by nekohasekai** [comment]
Read the documentation.
