### ISSUE TITLE
trojan和vmess結合quic傳輸層，作為隧道無法轉傳udp流量

### ISSUE THREAD

**Issue by hsly109** [SagerNet/sing-box#281]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

使用隧道模式，direct inbound，outbound為trojan或者vmess，傳輸層quic，目的地伺服器inbound為vmess或者trojan，outbound為direct並且override ip與port，只有tcp流量能正常通過，udp會出現invalid argument或者: unknown address

### Version of sing-box

$ sing-box version
sing-box version 1.1-rc1

Environment: go1.19.3 linux/amd64
Tags: with_quic,with_grpc,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_acme,with_clash_api,with_gvisor,with_embedded_tor,with_lwip
CGO: enabled

### Server and client configuration file

server conf:
{
   "log":{
      "disabled":true,
      "level":"trace",
      "output":"/root/sb-server.log",
      "timestamp":true
   },
   "dns":{
      "servers":[
         {
            "tag":"Cisco_Public_DNS_DOH",
            "address":"https://208.67.222.222:443/dns-query",
            "address_strategy":"prefer_ipv4",
            "strategy":"prefer_ipv4"
         }
      ],
      "rules":[

      ],
      "final":"",
      "strategy":"prefer_ipv4",
      "disable_cache":false,
      "disable_expire":false
   },
   "inbounds":[
      {
         "type":"trojan",
         "tag":"trojan-in",
         "listen":"::",
         "listen_port":443,
         "tcp_fast_open":false,
         "udp_fragment":false,
         "sniff":false,
         "sniff_override_destination":false,
         "sniff_timeout":"300ms",
         "domain_strategy":"prefer_ipv4",
         "udp_timeout":300,
         "proxy_protocol":false,
         "proxy_protocol_accept_no_header":false,
         "users":[
            {
               "name":"testingcf",
               "password":"rLhrx2tvf/kEo8BRJEmC+W2sMmPYMc4PMDmJvPhgVPc="
            }
         ],
         "tls":{
            "enabled":true,
            "server_name":"tesingcf.com",
            "alpn":[
               "h3"
            ],
            "min_version":"1.3",
            "max_version":"1.3",
            "cipher_suites":"TLS_CHACHA20_POLY1305_SHA256",
            "certificate_path":"/root/singbox/ssl/.ca.crt",
            "key_path":"/root/singbox/ssl/com.key"
         },
         "fallback":{
            "server":"127.0.0.1",
            "server_port":81
         },
         "transport":{
            "type":"quic"
         }
      }
   ],
   "outbounds":[
      {
         "type":"direct",
         "tag":"direct-out",
         "override_address": "8.8.8.8,
         "override_port": 53,
         "reuse_addr": false,
         "connect_timeout": "5s",
         "tcp_fast_open": false,
         "udp_fragment": false,
         "domain_strategy": "prefer_ipv4",
         "fallback_delay": "300ms"
      }
   ]
}

##########################################################

client conf：

{
   "log":{
      "disabled":false,
      "level":"trace",
      "output":"/root/sb-client.log",
      "timestamp":true
   },
   "dns":{
      "servers":[
         {
            "tag":"twnic-dns",
            "address":"https://101.101.101.101/dns-query",
            "address_strategy":"prefer_ipv4",
            "strategy":"prefer_ipv4"
         }
      ],
      "rules":[
         
      ],
      "final":"",
      "strategy":"prefer_ipv4",
      "disable_cache":false,
      "disable_expire":false
   },
   "inbounds":[
      {
         "type":"direct",
         "tag":"direct-in",
         "listen":"127.0.0.1",
         "listen_port":2001,
         "tcp_fast_open":false,
         "udp_fragment":false,
         "sniff":false,
         "sniff_override_destination":false,
         "sniff_timeout":"300ms",
         "domain_strategy":"prefer_ipv4",
         "udp_timeout":300,
         "proxy_protocol":false,
         "proxy_protocol_accept_no_header":false
      }
   ],
   "outbounds":[
      {
         "type":"trojan",
         "tag":"trojan-out",
         "server":"x.x.x.x",
         "server_port":443,
         "password":"rLhrx2tvf/kEo8BRJEmC+W2sMmPYMc4PMDmJvPhgVPc=",
         "reuse_addr": false,
         "connect_timeout": "5s",
         "tcp_fast_open": false,
         "udp_fragment": false,
         "domain_strategy": "prefer_ipv4",
         "fallback_delay": "300ms",
         "tls":{
            "enabled":true,
            "disable_sni":true,
            "server_name":"testingcf.com",
            "insecure":false,
            "alpn":[
               "h3"
            ],
            "min_version":"1.3",
            "max_version":"1.3",
            "cipher_suites":"TLS_CHACHA20_POLY1305_SHA256",
            "ech":{
               "enabled":false,
               "pq_signature_schemes_enabled":false,
               "dynamic_record_sizing_disabled":false,
               "config":""
            },
            "utls":{
               "enabled":false,
               "fingerprint":"random"
            }
         },
         "multiplex":{
            "enabled":false,
            "protocol":"smux",
            "max_connections":4,
            "min_streams":4,
            "max_streams":0
         },
         "transport":{
            "type":"quic"
         }
      }
   ]
}

### Server and client log file
+0800 2022-12-07 19:22:27 INFO inbound/trojan[trojan-in]: udp server started at [::]:443
+0800 2022-12-07 19:22:27 INFO sing-box started (0.00s)
+0800 2022-12-07 19:23:26 INFO [3791568825] inbound/trojan[trojan-in]: inbound connection from x.x.x.x:4193
+0800 2022-12-07 19:23:26 INFO [3791568825] inbound/trojan[trojan-in]: [roctaiwan] inbound packet connection to x.x.x.x:443
+0800 2022-12-07 19:23:26 INFO [3791568825] outbound/direct[direct-out]: outbound packet connection
+0800 2022-12-07 19:23:26 ERROR [3791568825] inbound/trojan[trojan-in]: process connection from x.x.x.x:4193: upload: write udp [::]:59962->:0: sendto: invalid argument | download: read udp [::]:59962: use of closed network connection
+0800 2022-12-07 19:23:30 INFO [2450432463] inbound/trojan[trojan-in]: inbound connection from x.x.x.x:4193
+0800 2022-12-07 19:23:30 INFO [2450432463] inbound/trojan[trojan-in]: [roctaiwan] inbound packet connection to x.x.x.x:443
+0800 2022-12-07 19:23:30 INFO [2450432463] outbound/direct[direct-out]: outbound packet connection
+0800 2022-12-07 19:23:30 ERROR [2450432463] inbound/trojan[trojan-in]: process connection from x.x.x.x:4193: upload: write udp [::]:8272->:0: sendto: invalid argument | download: read udp [::]:8272: use of closed network connection
+0800 2022-12-07 19:23:35 INFO [2705847217] inbound/trojan[trojan-in]: inbound connection from x.x.x.x:4193
+0800 2022-12-07 19:23:35 INFO [2705847217] inbound/trojan[trojan-in]: [roctaiwan] inbound packet connection to x.x.x.x:443
+0800 2022-12-07 19:23:35 INFO [2705847217] outbound/direct[direct-out]: outbound packet connection
+0800 2022-12-07 19:23:35 ERROR [2705847217] inbound/trojan[trojan-in]: process connection from x.x.x.x:4193: upload: write udp [::]:14599->:0: sendto: invalid argument | download: read udp [::]:14599: use of closed network connection

client log:
+0800 2022-12-07 19:23:17 INFO sing-box started (0.00s)
+0800 2022-12-07 19:23:25 INFO [890825907] inbound/direct[direct-in]: inbound packet connection from 127.0.0.1:56115
+0800 2022-12-07 19:23:25 INFO [890825907] outbound/trojan[trojan-out]: outbound packet connection to :0
+0800 2022-12-07 19:23:26 DEBUG [227700184] inbound/direct[direct-in]: connection closed: download: read destination: EOF | upload: io: read/write on closed pipe
+0800 2022-12-07 19:23:30 INFO [2248389688] inbound/direct[direct-in]: inbound packet connection from 127.0.0.1:48693
+0800 2022-12-07 19:23:30 INFO [2248389688] outbound/trojan[trojan-out]: outbound packet connection to :0
+0800 2022-12-07 19:23:30 DEBUG [426393930] inbound/direct[direct-in]: connection closed: download: read destination: EOF | upload: io: read/write on closed pipe
+0800 2022-12-07 19:23:35 INFO [3740086048] inbound/direct[direct-in]: inbound packet connection from 127.0.0.1:15178
+0800 2022-12-07 19:23:35 INFO [3740086048] outbound/trojan[trojan-out]: outbound packet connection to :0
+0800 2022-12-07 19:23:35 DEBUG [1036189120] inbound/direct[direct-in]: connection closed: download: read destination: EOF | upload: io: read/write on closed pipe

**Comment by nekohasekai** [comment]
UDP 连接需要地址，添加 override 为你的 inbound。

**Comment by yyiu** [comment]
`"override_address": "8.8.8.8,`     ----------> `"override_address": "8.8.8.8",`
