### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by memory971027** [SagerNet/sing-box#288]
开启时候打印如下图
![image](https://user-images.githubusercontent.com/47736423/207233708-95d0494c-6d63-4fd4-96de-c420308c9441.png)
配置如下
{
  log: {
    disabled: false,
    level: 'error',
    /* 没事别看日志喵 */
    output: './src/log/box.log',
    timestamp: true,
  },
  dns: {
    servers: [
      {
        tag: 'proxyServerNameServer',
        address: 'https://1.12.12.12/dns-query',
        detour: 'domestic',
        // detour: 'proxyServerNameServerOut',
        address_strategy: 'prefer_ipv6',
      },
      {
        tag: 'dnspod',
        address: 'https://1.12.12.12/dns-query',
        detour: 'domestic',
      },
      {
        tag: 'googledns',
        address: 'tcp://8.8.4.4',
        detour: 'proxy',
      },
      {
        tag: 'nxdomain',
        address: 'RCode://name_error',
      },
    ],
    rules: [
      {
        geosite: 'category-ads-all',
        server: 'nxdomain',
        disable_cache: false,
      },
      {
        domain_suffix: [
          '.xn--ngstr-lra8j.com',
          '.googleapis.cn',
          '.dev',
        ],
        geosite: [
          'tiktok',
        ],
        server: 'googledns',
        disable_cache: false,
      },
      {
        domain_keyword: [
          'ntp',
        ],
        domain_regex: [
          '(^|\\.)(alt[1-8]-mtalk|mtalk|mtalk4)\\.google\\.com$',
        ],
        geosite: [
          'bytedance',
          'microsoft@cn',
          'apple@cn',
          'category-games@cn',
          'cn',
        ],
        server: 'dnspod',
        disable_cache: false,
      },
    ],
    final: 'googledns',
    strategy: 'prefer_ipv6',
    /* 开启 ipv6 时改为 prefer_ipv4/prefer_ipv6 即可喵 */
    disable_cache: false,
    disable_expire: false,
  },
  inbounds: [
    {
      tag: 'tun',
      type: 'tun',
      interface_name: 'memory',
      inet4_address: '172.19.0.1/30',
      inet6_address: 'fdfe:dcba:9876::1/126',
      mtu: 30000,
      auto_route: true,
      strict_route: true,
      stack: 'system',
      sniff: true,
      sniff_override_destination: true,
      domain_strategy: 'prefer_ipv6',
    },
  ],
  outbounds: [
    {
      tag: 'direct',
      type: 'direct',
    },
    {
      tag: 'block',
      type: 'block',
    },
    {
      tag: 'dns',
      type: 'dns',
    },
  /*
    {
      tag: 'proxyServerNameServerOut',
      type: 'selector',
      outbounds: [
        'direct',
      ],
      default: 'direct',
    },
  */
    {
      tag: 'proxy',
      type: 'selector',
      outbounds: [
        'domestic',
      ],
    },
    {
      tag: 'domestic',
      type: 'selector',
      outbounds: [
       
      ],
    },
  ],
  route: {
    geosite: {
      path: './src/geosite.db',
      download_url: 'https://raw.githubusercontent.com/CHIZI-0618/v2ray-rules-dat/release/geosite.db',
      download_detour: 'proxy',
    },
    geoip: {
      path: './src/geoip.db',
      download_url: 'https://raw.githubusercontent.com/CHIZI-0618/v2ray-rules-dat/release/geoip.db',
      download_detour: 'proxy',
    },
    rules: [
      {
        protocol: 'dns',
        outbound: 'dns',
      },
      {
        protocol: [
          'quic',
        ],
        outbound: 'block',
      },
      // 屏蔽所有的 斗鱼, B站 的 stun. geosite
      // https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/BiliBili/BiliBili.yaml
      {
        protocol: [
          'stun',
        ],
        ip_cidr: [
          '106.75.74.76/32',
          '111.206.25.147/32',
          '119.3.238.64/32',
          '120.92.108.182/32',
          '120.92.113.99/32',
          '120.92.153.217/32',
          '134.175.207.130/32',
          '203.107.1.0/24',
        ],
        domain_keyword: [
          'bilibili',
          'douyu',
        ],
        geosite: [
          'bilibili',
          'douyu',
        ],
        outbound: 'block'
      },
      // 屏蔽所有的 斗鱼, B站 的 stun. 域名关键词
      {
        type: 'logical',
        mode: 'and',
        rules: [
          {
            domain_keyword: [
              'stun',
            ],
          }, 
          {
            domain_keyword: [
              'bilibili',
              'douyu',
            ],
            geosite: [
              'bilibili',
              'douyu',
            ],
          },
        ],
        outbound: 'block'
      },
      // 屏蔽B站 的 mcdn. 域名关键词
      {
        type: 'logical',
        mode: 'and',
        rules: [
          {
            domain_keyword: [
              'mcdn',
            ],
          },
          {
            domain_keyword: [
              'bilibili',
            ],
            geosite: [
              'bilibili',
            ],
          },
        ],
        outbound: 'block'
      },
      // 屏蔽B站 的 mcdn. ip段+域名关键词+geosite+端口号
      {
        ip_cidr: [
          '106.75.74.76/32',
          '111.206.25.147/32',
          '119.3.238.64/32',
          '120.92.108.182/32',
          '120.92.113.99/32',
          '120.92.153.217/32',
          '134.175.207.130/32',
          '203.107.1.0/24',
        ],
        domain_keyword: [
          'bilibili',
          'mcdn',
        ],
        geosite: [
          'bilibili',
        ],
        port: [
          4483,
          9305,
        ],
        outbound: 'block',
      },
      {
        domain_suffix: [
          '.xn--ngstr-lra8j.com',
          '.googleapis.cn',
          '.dev',
        ],
        geosite: [
          'tiktok',
        ],
        outbound: 'proxy',
      },
      {
        domain_keyword: [
          'ntp',
        ],
        domain_regex: [
          '(^|\\.)(alt[1-8]-mtalk|mtalk|mtalk4)\\.google\\.com$',
        ],
        geosite: [
          'bytedance',
          'microsoft@cn',
          'apple@cn',
          'category-games@cn',
          'cn',
        ],
        outbound: 'domestic',
      },
      {
        geoip: [
          'private',
        ],
        outbound: 'direct',
      },
      {
        geoip: [
          'cn',
        ],
        outbound: 'domestic',
      },
    ],
    final: 'proxy',
    auto_detect_interface: true,
    find_process: true,
  },
  experimental: {
    clash_api: {
      external_controller: '0.0.0.0:9909',
      external_ui: 'Dashboard',
      secret: 'singBox',
      cache_file: './src/cache.db',
      store_selected: true,
    },
  },
}

**Comment by memory971027** [comment]
域名是https://********.dns.navy/

**Comment by memory971027** [comment]
昨天还是正常的，今天突然就报错了....

**Comment by isnowly** [comment]
hi, @memory971027 

可以在android里执行shell？ 请问你这是什么app呀？需要root吗？

**Comment by memory971027** [comment]
@isnowly 可以，mt文件管理器，有无root都可以用
