### ISSUE TITLE
Add obfuscated-openssh support

### ISSUE THREAD

**Issue by zolagonano** [SagerNet/sing-box#295]
Adding obfuscated-openssh patch to ssh library used in sing-box would help with DPI censoring openssh based on its handshake
https://github.com/zinglau/obfuscated-openssh-patches
https://zinglau.com/projects/ObfuscatedOpenSSHPatches.html

(this requires re-implementing the patch for the golang.org/x/crypto/ssh package)

**Comment by nekohasekai** [comment]
SSH is not designed to proxy traffic, I think.

**Comment by goldadigida** [comment]
today i tried to use ssh+v2ray http transport in singbox,i think its working,then i compare my ssh+v2ray transport connection form with http injector apk in android playstore and it is same,difference is http injector apk has payload replacer for response to be 200 connection established or 200ok cmiiw.....
this is just for my study material about golang

**Comment by nekohasekai** [comment]
We do not provide support for such black-box closed-source software.
