### ISSUE TITLE
Use sing-box as remote dst-nat 

### ISSUE THREAD

**Issue by alirezadigi** [SagerNet/sing-box#296]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

hi , and thanks for this great tool , 
i have a problem , and it's not a bug , maybe a feature request ...
i have a Mikrotik router , and in NAT section it has Dst-Nat option
it gets a host and its relevant port...

tried to forward part of my router's traffic to sing-box ,,, but it doesnt work...
i want to use a socks5 proxy as outbound , and any config that works as inbound ...

so i want the router to send the packets to sing-box and then it sends that to socks proxy and so on ...

i'll send the configs that i have tried, and i also assume that i dont need sudo permissions to run this config ...

and also one more thing , snail007/goproxy with its SPS protocol works find for me ,but for being more flexible i love using sagernet/singbox , but direct inbound , or tproxy inbound doesnt work for me...

### Version of sing-box

<details>

```console
sing-box version 1.1.1

Environment: go1.19.4 linux/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: 8afb8ca7eb8aa52e7a3b44253be0f3df9474fa64
CGO: disabled
```

</details>

### Server and client log file
<details>

```console

{
  "log": {
    "level": "info"
  },
  "dns": {
    "servers": [
      {
        "address": "tls://8.8.8.8"
      }
    ]
  },
  "inbounds": [
    {
      "type": "mixed", //"direct",
      "tag": "mixed-in",
      "listen":"0.0.0.0",
      "listen_port":9095,
      "sniff": false

    },
    {
      "type": "tproxy",
      "tag": "tproxy-in",
      "listen":"0.0.0.0",
      "listen_port":9096,
      "network": "tcp"
    }
  ],
  "outbounds": [
    {
      "type":"socks",
      "tag": "socks-out",
      "server": "127.0.0.1",
      "server_port": 9090,
      "version": "5",
      "udp_over_tcp": true,
      "network": "tcp"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "outbound": "socks-out",
        "inbound": [
          "direct-in",
          "tproxy-in"
        ]
      }
    ]
  }
}
```
</details>

<details>

```console
 sudo sing-box run -c /etc/sing-box/config.json  
INFO[0000] router: using socks[socks-out] as default outbound for connection
INFO[0000] router: using dns[dns-out] as default outbound for packet connection
INFO[0000] inbound/mixed[mixed-in]: tcp server started at 0.0.0.0:9095
INFO[0000] inbound/tproxy[tproxy-in]: tcp server started at 0.0.0.0:9096
INFO[0000] sing-box started (0.00s)
INFO[0005] [3992279482] inbound/mixed[mixed-in]: inbound connection from 192.168.1.1:51612
INFO[0023] [1149572114] inbound/mixed[mixed-in]: inbound connection from 192.168.1.1:36000
INFO[0025] [3213620903] inbound/mixed[mixed-in]: inbound connection from 192.168.1.1:36014
INFO[0039] [1809635585] inbound/mixed[mixed-in]: inbound connection from 192.168.1.1:35210
ERROR[0039] [1809635585] inbound/mixed[mixed-in]: process connection from 192.168.1.1:35210: read http request: malformed HTTP request "\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x82\xe1\xfeNğ3\x13Z\xac\xfd>\xd6riL'F`\xc1\xc6\x10A}#\xe8G\xb9fQ\x12\xf0 {\x12\xb0\x120\xbd\xea"

```

</details>

**Comment by nekohasekai** [comment]
Can't understand.

**Comment by alirezadigi** [comment]
Sorry @nekohasekai 
I just mean this
I just want to have a proxy box and a router with any os , and then forward traffic of cluents to proxy box

Sth like below

Client --> router --> proxy box --> proxy (socks5 for example) --> internet

How Can i do this with sing-box?

(Or even tldr,er how to use sing box as gateway and / or transparent proxy)

**Comment by alirezadigi** [comment]
Sth like [This tuturial](https://www.howtogeek.com/683971/how-to-use-a-raspberry-pi-as-a-proxy-server-with-privoxy/) 
But without need for setting proxy in each client , instead setting proxy in router with dst-nat

**Comment by alirezadigi** [comment]
@nekohasekai ... can you please help?
i really need it ...
