### ISSUE TITLE
smux weird behaviour

### ISSUE THREAD

**Issue by m0ckinGuY** [SagerNet/sing-box#309]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

Hi, 
Im using the example config of shadowtls+shadowsocks 
Everything works perfectly 
Something that caught my attention was the huge traffic usage 
I looked at the network usage and an interesting observation happened 
when you're using smux, for example if you download for 10seconds and stop it the traffic will go on for like 20~30 seconds 
sounds like mux streams doesnt close (I dont have much technical knowledge about that)

Regards 

### Version of sing-box

sing-box version 1.1.2

Environment: go1.19.4 linux/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: ff0693be3210e6434eb1d6be7eb21c5bc1ffde88
CGO: disabled

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by oplle** [comment]
这个问题我之前就发现了，在issues/273反馈过。被管理员隐藏了
我再说一下我测试的情况

关于多路复用，我也有个问题需要反馈下。尝试的版本1.0.7-1.1.2，协议是shadowtls（非tun）

当我添加并开启多路复用，三个max相关的值不管设置为多少。
使用IDM走sing的代理，单线程下载https://lg.naranja.tech/1024MB.test这个文件，下载几秒钟之后取消下载，然后sing会一直占用下载网速，测试过多次，也测试过v4v6都会这样，v6应该是更容易复现。
只有关闭或删除多路复用，才不会出现
我后来又使用了多路复用里面的另一个参数，"protocol": "smux",将smux改为"protocol": "yamux",之后，就不会再出现这种情况了，但是yamux的速度不如smux，不知道为什么会出现这种情况，所以来这里反馈下。

**Comment by malikshi** [comment]
+1 the problem I face with smux enable are the speed in modem won't go back to normal after doing speedtest apps. Even cost me 5-40GB, the modem speed about 80-120Mbps. Yamux pretty normal no issues so far.

**Comment by reeceyng** [comment]
[79ed636](https://github.com/xtaci/smux/commit/79ed6364e64973ccf475b1e14f7378f008c8a5af) Latest smux may solve this problem

**Comment by malikshi** [comment]
> [79ed636](https://github.com/xtaci/smux/commit/79ed6364e64973ccf475b1e14f7378f008c8a5af) Latest smux may solve this problem

boss updated deps. testing speedtest 5x the speed modem back to normal around this time 40-60 seconds. i think it's good improvement.


> Even cost me 5-40GB, the modem speed about 80-120Mbps. Yamux pretty normal no issues so far.

no wasting qoutas / bw like this again. TYVM!
