### ISSUE TITLE
Add faketcp type to hysteria

### ISSUE THREAD

**Issue by Mars160** [SagerNet/sing-box#310]
希望可以给hysteria添加faketcp类型
如果不考虑，那希望可以给hysteria出站添加faketcp类型增强兼容性

**Comment by nekohasekai** [comment]
暂时没有计划添加这种服务器只能使用特定 Linux 系统 + 特权运行的功能。

**Comment by Weltolk** [comment]
> 暂时没有计划添加这种服务器只能使用特定 Linux 系统 + 特权运行的功能。

请问可以参考一下udp2raw,添加faketcp的支持吗?(linux服务端,windows客户端)

https://github.com/wangyu-/udp2raw-multiplatform
