### ISSUE TITLE
Connectivity problem related to TFO and DNS

### ISSUE THREAD

**Issue by kabegoe** [SagerNet/sing-box#313]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

sing-box failed to connect to server as a client, only if `tcp_fast_open` is **enabled** and there are **more than 1 DNS results** of the server domain. 

Any change to attached `config.json` listed below can resolve the problem:
- Change `"tcp_fast_open": true` to `"tcp_fast_open": false`
- Change `"strategy": "prefer_ipv4"` to `"strategy": "ipv4_only"`
- Change `"strategy": "prefer_ipv4"` to `"strategy": "ipv6_only"`

Following changes do not resolve the problem:
- Change `"strategy": "prefer_ipv4"` to `"strategy": "prefer_ipv6"`
- Delete `"strategy": "prefer_ipv4"`

### Version of sing-box

https://github.com/SagerNet/sing-box/commit/8dc3fdfff625badbd1aaee1a8edfae07cea6b92a
<details>

```console
$ sing-box version
sing-box version 1.1.2

Environment: go1.19.4 linux/amd64
CGO: enabled
```

</details>

### Client configuration file
<details>

```json
{
  "log": {
    "level": "trace"
  },
  "dns": {
    "servers": [
      {
        "tag": "local",
        "address": "udp://192.168.0.1",
	"strategy": "prefer_ipv4",
        "detour": "direct-out"
      }
    ],
    "final": "local",
    "disable_cache": false
  },
  "inbounds": [
    {
      "type": "socks",
      "tag": "socks-in",
      "listen": "127.0.0.1",
      "listen_port": 1080,
      "sniff": false,
      "sniff_override_destination": false
    }
  ],
  "outbounds": [
    {
      "type": "shadowsocks",
      "tag": "ss-out",
      "server": "server.domain.name",
      "server_port": 1080,
      "method": "2022-blake3-aes-128-gcm",
      "password": "PASSWORD",
      "bind_interface": "wlo1",
      "tcp_fast_open": true
    },
    {
      "type": "direct",
      "tag": "direct-out"
    }
  ],
  "route": {
    "final": "ss-out",
    "default_interface": "wlo1"
  }
}
```

</details>

### Client log file
<details>

```console
INFO[0000] inbound/socks[socks-in]: tcp server started at 127.0.0.1:1080
INFO[0000] sing-box started (0.00s)
INFO[0002] [515689036] inbound/socks[socks-in]: inbound connection from 127.0.0.1:38938
INFO[0002] [515689036] inbound/socks[socks-in]: inbound connection to www.bilibili.com:443
INFO[0002] [515689036] outbound/shadowsocks[ss-out]: outbound connection to www.bilibili.com:443
DEBUG[0002] [515689036] dns: lookup domain server.domain.name
INFO[0002] outbound/direct[direct-out]: outbound packet connection to 192.168.0.1:53
DEBUG[0002] [515689036] dns: exchanged server.domain.name NOERROR 600
INFO[0002] [515689036] dns: exchanged server.domain.name AAAA server.domain.name. 300 IN AAAA xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
DEBUG[0002] [515689036] dns: exchanged server.domain.name NOERROR 600
INFO[0002] [515689036] dns: exchanged server.domain.name A server.domain.name. 300 IN A xxx.xxx.xxx.xxx
INFO[0002] [515689036] dns: lookup succeed for server.domain.name: xxx.xxx.xxx.xxx xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
DEBUG[0002] [515689036] inbound/socks[socks-in]: connection closed: process connection from 127.0.0.1:38938: client handshake: dial tcp xxx.xxx.xxx.xxx:1080: operation was canceled
```

</details>

`xxx.xxx.xxx.xxx` = A record of `server.domain.name`
`xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx` = AAAA record of `server.domain.name`

**Comment by nekohasekai** [comment]
For architectural reasons, sing-box is temporarily unable to connect to multiple addresses sequentially or in parallel when TFO is enabled. You can set the domain_strategy at the outbound level to avoid connecting to multiple addresses.

**Comment by chise0713** [comment]
> For architectural reasons, sing-box is temporarily unable to connect to multiple addresses sequentially or in parallel when TFO is enabled. You can set the domain_strategy at the outbound level to avoid connecting to multiple addresses.

Seems like when udp connection resolved as multiple IPs at inbound will also have this problem, I have to set `domain_stratgy` at outbound and leave inboud's `domain_stratgy` empty to make udp connection work.

Is this intentionally designed like this, or is it a bug?

I personally believe that when there are `domain_stratgy`  for both inbound and outbound, the outbound should initiate connections using the single IP resolved from outbound resolution.
