### ISSUE TITLE
No fallback feature for naiveproxy

### ISSUE THREAD

**Issue by RayWangQvQ** [SagerNet/sing-box#317]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

For  original naiveproxy, we can add fallback as a fake website by Caddy and forward_proxy.

With sing-box, I only found fallback feature in trojan, but not in naive.

So I want to know if I missed something in documentation or it is not currently supported.

If it is not supported, will this feature be supported in the future?

Thx.

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.1.4

Environment: go1.19.5 linux/amd64
Tags: with_quic,with_wireguard,with_acme
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```console
Null
```

</details>

### Server and client log file

<details>

```console
Null
```

</details>

**Comment by nekohasekai** [comment]
There is no evidence that GFW performs blocking based on HTTP responses.

**Comment by RayWangQvQ** [comment]
Since this is a classic feature loved by users, I want to know if sing-box will consider to support it in the future?

If not, this issue can be closed.

**Comment by nekohasekai** [comment]
Usually naive users are not so superstitious

**Comment by isnowly** [comment]
The fallback should not be useless. The trojan implementation of sing-box has fallback, but naive does not.
