### ISSUE TITLE
求助naiveproxy节点的认证用户名分流

### ISSUE THREAD

**Issue by CJLUGaoXinyu** [SagerNet/sing-box#325]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

想实现多用户，每个用户走不同出站。如下设置后，所有用户依然走同一个默认出站。
求教我的配置文件要怎么改？

### Version of sing-box

sing-box version 1.1.1

Environment: go1.19.3 linux/amd64
Tags: with_quic,with_wireguard,with_acme
Revision: 8afb8ca7eb8aa52e7a3b44253be0f3df9474fa64
CGO: enabled

### Server and client configuration file

"inbounds": [
{
      "type": "naive",
      "tag": "naive-in",
      "network": "tcp",
      "listen": "::",
      "listen_port": 443,
      "tcp_fast_open": true,
      "sniff": true,
      "sniff_override_destination": false,
      "domain_strategy": "prefer_ipv4",
      "udp_timeout": 300,
      "proxy_protocol": false,
      "users": [
        {
          "username": "user1",
          "password": ""
        },
        {
          "username": "user2",
          "password": ""
        },
        {
          "username": "user3",
          "password": ""
        }
      ],
      "tls": {
        "enabled": true,
        "min_version": "1.2",
        "max_version": "1.3",
        "alpn": ["h2",
                 "http/1.1"],
        "certificate_path": "/usr/local/etc/sing-box/cert.pem",
        "key_path": "/usr/local/etc/sing-box/key.pem"
        }
      }
]

有多个outbound, 分别是out1,out2.....，还有默认default

"route":{
  "rules": [
     {
        "network": "tcp",
        "auth_user": "user1",
        "outbound": "out1"
      },
      {
        "network": "tcp",
        "auth_user": "user2",
        "outbound": "out2"
      },
...........
  ],
 "final": "default"
}

### Server and client log file

+0800 2023-01-18 01:14:58 INFO [2755324490] inbound/naive[naive-in]: inbound connection from xxxxxxx:51489
+0800 2023-01-18 01:14:58 INFO [2755324490] inbound/naive[naive-in]: inbound connection to www.youtube.com:443
+0800 2023-01-18 01:14:58 DEBUG [2755324490] dns: lookup domain www.youtube.com
+0800 2023-01-18 01:14:58 INFO [2755324490] dns: lookup succeed for www.youtube.com: 142.250.181.238 142.250.185.174 142.250.184.206 142.250.185.206 142.250.185.110 142.250.185.142 172.217.16.142 172.217.16.206 172.217.23.110 142.250.186.142 172.217.18.14 142.250.184.238 142.250.186.174 142.250.185.238 142.250.185.78 142.250.74.206 2a00:1450:4001:812::200e 2a00:1450:4001:80b::200e 2a00:1450:4001:806::200e 2a00:1450:4001:813::200e
+0800 2023-01-18 01:14:58 DEBUG [2755324490] dns: resolved [142.250.181.238 142.250.185.174 142.250.184.206 142.250.185.206 142.250.185.110 142.250.185.142 172.217.16.142 172.217.16.206 172.217.23.110 142.250.186.142 172.217.18.14 142.250.184.238 142.250.186.174 142.250.185.238 142.250.185.78 142.250.74.206 2a00:1450:4001:812::200e 2a00:1450:4001:80b::200e 2a00:1450:4001:806::200e 2a00:1450:4001:813::200e]
+0800 2023-01-18 01:14:58 INFO [2755324490] outbound/direct[default]: outbound connection to www.youtube.com:443

**Comment by nekohasekai** [comment]
Try fe492904e9a5d217fc5fa748d5b53a476f0e67cb

**Comment by CJLUGaoXinyu** [comment]
> Try [fe49290](https://github.com/SagerNet/sing-box/commit/fe492904e9a5d217fc5fa748d5b53a476f0e67cb)

可以了，非常感谢
