### ISSUE TITLE
特性请求：路由规则支持将域名解析为 IP 进行匹配

### ISSUE THREAD

**Issue by seiuneko** [SagerNet/sing-box#326]
类似 v2ray 的 domainStrategy 选项：
> IPIfNonMatch：当域名没有匹配任何基于域名的规则时，将域名解析成 IP（A 记录或 AAAA 记录），进行基于 IP 规则的匹配；
>
>    当一个域名有多个 IP 地址时，会尝试匹配所有的 IP 地址，直到其中一个与某个 IP 规则匹配为止；
>    解析后的 IP 仅在路由选择时起作用，转发的数据包中依然使用原始域名。
>
> IPOnDemand：当匹配时碰到任何基于 IP 的规则，立即将域名解析为 IP 进行匹配。
<br>
使用情景：Tun 开启 sniff_override_destination 选项后需要按 IP 分流。

**Comment by nekohasekai** [comment]
Reread the documentation.

**Comment by seiuneko** [comment]
抱歉，找到问题了，是 v2ray 服务端不会嗅探 HTTP 的 Host 原因。
