### ISSUE TITLE
ShadowTLS v2 fallback (to handshaking server) does not work?

### ISSUE THREAD

**Issue by myocytebd** [SagerNet/sing-box#335]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

ShadowTLS v2 fallback (to handshaking server) does not seem to work.  
(Without GFW) Using ShadowTLS v2 as socks5 works.
But when trying to visit shadow tls port as a webpage, it does not behave correctly:  
- chrome: ERR_CONNECTION_RESET  
- firefox: after certificate error screen, shows various website dependent error messages: service unavailable, invalid request, etc. As if the shadow tls sends an invalid request to the handshaking server.  
- wget: ```ERROR: certificate common name <...> doesn't match requested host name <sing-box-ip>.```
- wget --no-check-certificate: ```HTTP request sent, awaiting response... 400 Bad Request
2023-01-30 03:59:30 ERROR 400: Bad Request.```
- curl: ```curl: (60) SSL: no alternative certificate subject name matches target host name <sing-box-ip>```
- curl -k: Same response as firefox (after accepting certificate risk screen).
Tested with various handshake server settings.
(browser tested on client w/ VPN; wget & curl tested on sing-box server itself.)

(With GFW, shadow tls port is blocked)

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.1.4

Environment: go1.19.4 linux/amd64
Tags: with_quic,with_wireguard,with_acme
Revision: f32c1497388af7adc2eac2e9c83213c3ee831a8a
CGO: enabled
```

</details>

### Server and client configuration file

<details>

```console
{
  "log": { "level": "trace" },
  "dns": {
    "servers": [ {
        "address": "tls://8.8.8.8"
      } ]
  },
  "inbounds": [ {
      "type": "shadowtls",
      "listen": "...",
      "listen_port": 443,
      "version": 2,
      "password": "...",
      "handshake": {
        "server": "www.bing.com",
        "server_port": 443 
      },
      "detour": "shadowsocks-in"
    }, {
      "type": "shadowsocks",
      "tag": "shadowsocks-in",
      "listen": "127.0.0.1",
      "method": "2022-blake3-aes-128-gcm",
      "password": "..."
    } ],
  "outbounds": [ {
      "type": "direct"
    }, {
      "type": "dns",
      "tag": "dns-out"
    } ],
  "route": {
    "rules": [ {
        "protocol": "dns",
        "outbound": "dns-out"
      } ]
  }
}
```
(client configuration is skipped because the issue is for fallback)

</details>

### Server and client log file

<details>

```console
Jan 30 03:31:45 xxx systemd[1]: Started sing-box service.
Jan 30 03:31:45 xxx sing-box[1307328]: INFO[0000] inbound/shadowtls[0]: tcp server started at ***:443
Jan 30 03:31:45 xxx sing-box[1307328]: INFO[0000] inbound/shadowsocks[shadowsocks-in]: tcp server started at 127.0.0.1:37921
Jan 30 03:31:45 xxx sing-box[1307328]: INFO[0000] inbound/shadowsocks[shadowsocks-in]: udp server started at 127.0.0.1:41249
Jan 30 03:31:45 xxx sing-box[1307328]: INFO[0000] sing-box started (0.00s)
Jan 30 03:31:58 xxx sing-box[1307328]: INFO[0012] [2436040423] inbound/shadowtls[0]: inbound connection from 133.242.51.171:46342
Jan 30 03:31:58 xxx sing-box[1307328]: DEBUG[0012] [2436040423] dns: lookup domain www.ebay.com
Jan 30 03:31:58 xxx sing-box[1307328]: INFO[0012] outbound/direct[0]: outbound connection to 8.8.8.8:853
Jan 30 03:31:58 xxx sing-box[1307328]: DEBUG[0012] [2436040423] dns: exchanged response www.ebay.com NOERROR 600
Jan 30 03:31:58 xxx sing-box[1307328]: INFO[0012] [2436040423] dns: exchanged www.ebay.com CNAME www.ebay.com. 210 IN CNAME slot9428.ebay.com.edgekey.net.
Jan 30 03:31:58 xxx sing-box[1307328]: INFO[0012] [2436040423] dns: exchanged www.ebay.com CNAME slot9428.ebay.com.edgekey.net. 314 IN CNAME e9428.a.akamaiedge.net.
Jan 30 03:31:58 xxx sing-box[1307328]: INFO[0012] [2436040423] dns: exchanged www.ebay.com SOA a.akamaiedge.net. 490 IN SOA n0a.akamaiedge.net. hostmaster.akamai.com. 1675077808 1000 1000 1000 >
Jan 30 03:31:58 xxx sing-box[1307328]: DEBUG[0012] [2436040423] dns: exchanged response www.ebay.com NOERROR 600
Jan 30 03:31:58 xxx sing-box[1307328]: INFO[0012] [2436040423] dns: exchanged www.ebay.com CNAME www.ebay.com. 234 IN CNAME slot9428.ebay.com.edgekey.net.
Jan 30 03:31:58 xxx sing-box[1307328]: INFO[0012] [2436040423] dns: exchanged www.ebay.com CNAME slot9428.ebay.com.edgekey.net. 17329 IN CNAME e9428.a.akamaiedge.net.
Jan 30 03:31:58 xxx sing-box[1307328]: INFO[0012] [2436040423] dns: exchanged www.ebay.com A e9428.a.akamaiedge.net. 20 IN A 23.204.250.188
Jan 30 03:31:58 xxx sing-box[1307328]: INFO[0012] [2436040423] dns: lookup succeed for www.ebay.com: 23.204.250.188
Jan 30 03:31:58 xxx sing-box[1307328]: DEBUG[0012] [2436040423] inbound/shadowtls[0]: connection closed: process connection from 133.242.51.171:46342: EOF
Jan 30 03:32:02 xxx sing-box[1307328]: INFO[0016] [2826052923] inbound/shadowtls[0]: inbound connection from 133.242.51.171:36158
Jan 30 03:32:02 xxx sing-box[1307328]: DEBUG[0016] [2826052923] dns: lookup domain www.ebay.com
Jan 30 03:32:02 xxx sing-box[1307328]: INFO[0016] [2826052923] dns: lookup succeed for www.ebay.com: 23.204.250.188
Jan 30 03:32:02 xxx sing-box[1307328]: WARN[0016] [2826052923] inbound/shadowtls[0]: fallback connection
Jan 30 03:40:14 xxx systemd[1]: Stopping sing-box service...
Jan 30 03:40:14 xxx systemd[1]: sing-box.service: Deactivated successfully.
```
(client log is skipped because the issue is for fallback)

</details>

**Comment by myocytebd** [comment]
> try this:
> 
> curl -v --resolve [www.bing.com:443:"sing-box-ip](http://www.bing.com:443:%22sing-box-ip)" https://www.bing.com

It seems to work.  
Does this means that shadow tls is broken that regular https client cannot actually trigger the correct fallback?

**Comment by Gzxhwq** [comment]
I think these two error you had posted can answer your question. ShadowTLS is work as expected.

certificate common name <...> doesn't match requested host name <sing-box-ip>

no alternative certificate subject name matches target host name <sing-box-ip>
