### ISSUE TITLE
Can't install with the latest Golang 1.20

### ISSUE THREAD

**Issue by msshn** [SagerNet/sing-box#338]
Sing-box can't be installed (with or without options) with the latest Golang version 1.20 .
as far as I've seen, there are problems with quic-go and shadowsocks-2022 during installation.

**Comment by nekohasekai** [comment]
e3123545f2f768b22623aac44bfae548d8e0e9a2

**Comment by debiansid** [comment]
GOARCH=amd64 GOOS=linux GOAMD64=v3 CGO_ENABLED=1  go build -v -trimpath -tags "osusergo,netgo,with_gvisor,with_quic,with_wireguard,with_utls,with_grpc,with_provider,with_clash_api" -ldflags="-extldflags=-static -s -w -buildid=" ./cmd/sing-box
crypto/internal/nistec
# crypto/internal/nistec
/usr/local/go/src/crypto/internal/nistec/p256_ordinv.go:14:6: p256OrdMul redeclared in this block
        /usr/local/go/src/crypto/internal/nistec/p256_asm_ordinv.go:14:6: other declaration of p256OrdMul
/usr/local/go/src/crypto/internal/nistec/p256_ordinv.go:19:6: p256OrdSqr redeclared in this block
        /usr/local/go/src/crypto/internal/nistec/p256_asm_ordinv.go:19:6: other declaration of p256OrdSqr
/usr/local/go/src/crypto/internal/nistec/p256_ordinv.go:21:6: P256OrdInverse redeclared in this block
        /usr/local/go/src/crypto/internal/nistec/p256_asm_ordinv.go:21:6: other declaration of P256OrdInverse

**Comment by msshn** [comment]
Thanks, issue resolved with version 1.1.5 .
