### ISSUE TITLE
vmess 节点似乎不支持 path:/?ed=2048

### ISSUE THREAD

**Issue by 0730aa** [SagerNet/sing-box#347]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

橘子机场本来订阅到 v2ray 安卓客户端的 path 全是 /?ed=2048，而且全部能够正常使用
![Screenshot_20230205_234852](https://user-images.githubusercontent.com/97997625/216830055-4ec4208a-6e4e-471d-a3c9-8b3e3a070081.jpg)
![Screenshot_20230205_234903](https://user-images.githubusercontent.com/97997625/216830064-a2c88ed8-56c9-4d81-83a3-b0f9c1d3aabc.jpg)
这两张图是 v2 直接默认订阅的（他家机场默认全是/?ed=2048），啥也每改，都能正常使用
但是 在 singbox 上
![Screenshot_20230205_235051](https://user-images.githubusercontent.com/97997625/216830159-dfafa062-a6be-4aec-813c-2d1370acff45.jpg)
![Screenshot_20230205_235056](https://user-images.githubusercontent.com/97997625/216830170-0d2e53c7-7297-48c4-82d8-de9e2c0a2529.jpg)
![Screenshot_20230205_235115](https://user-images.githubusercontent.com/97997625/216830178-ea93bf0f-2e34-42e1-bf96-c5f2dd9fb3cb.jpg)
却用不了，这三张图是 singbox 直接导入默认订阅
下面这另外三张是我把订阅的 path 全部改成 \，突然发现全部有网
![Screenshot_20230205_235203](https://user-images.githubusercontent.com/97997625/216830264-ff367df1-5279-4bf7-823d-52ec11b3dbd5.jpg)
![Screenshot_20230205_235208](https://user-images.githubusercontent.com/97997625/216830271-1d806d43-4696-4225-b77b-193ca5819e8c.jpg)
![Screenshot_20230205_235217](https://user-images.githubusercontent.com/97997625/216830283-b2502c57-f992-447e-afe6-6ddcbf466128.jpg)
很震惊，不知道怎么回事，1.1.1 到 1.1.5 的内核都试过了，都没网，只有改 path 为 ＼ 才能正常使用
本次实验使用 1.1.5 内核
![Screenshot_20230205_235251](https://user-images.githubusercontent.com/97997625/216830381-b0e2ea53-491b-4458-91d6-d0bc2853fd32.jpg)

### Version of sing-box

singBox version
sing-box version 1.1.5

Environment: go1.19.5 android/arm64
Tags: with_gvisor,with_quic,with_wireguard,with_clash_api,with_grpc,with_shadowsocksr,with_ech,with_utls
CGO: enabled

### Server and client configuration file

{
  log: {
    disabled: true,
    level: 'debug',
    /* 没事别看日志喵 */
    output: './src/log/box.log',
    timestamp: true,
  },
  dns: {
    servers: [
      {
        tag: 'proxyServerNameServer',
        /* 此项目不可删除，订阅域名解析相关强依赖此项目喵 */
        address: 'https://1.12.12.12/dns-query',
        /* 地址可以改成任意你想要的地址喵 */
        detour: '国内',
        // detour: 'proxyServerNameServerOut',
        /* detour 可以任意自定义，非免流可以直接改成 direct 喵 */
      },
      {
        tag: 'dnspod',
        address: 'https://1.12.12.12/dns-query',
        detour: '国内',
      },
      {
        tag: 'alidns',
        address: 'https://223.5.5.5/dns-query',
        detour: '国内',
      },
      {
        tag: 'googledns',
        address: 'tcp://8.8.4.4',
        detour: '国外',
      },
      {
        tag: 'nxdomain',
        address: 'RCode://name_error',
      },
    ],
    rules: [
      { geosite: 'category-ads-all', user_id: [ 10244, 10396, 10278, 10283 ],
        server: 'nxdomain',
        disable_cache: false,
      },
      { domain_suffix: [ '.xn--ngstr-lra8j.com', '.googleapis.cn', '.dev' ], geosite: [ 'tiktok' ],
        server: 'googledns',
        disable_cache: false,
      },
      { domain_keyword: [ 'ntp' ], domain_regex: [ '(^|\\.)(alt[1-8]-mtalk|mtalk|mtalk4)\\.google\\.com$' ], geosite: [ 'bytedance', 'microsoft@cn', 'apple@cn', 'category-games@cn', 'cn' ],
        server: 'dnspod',
        disable_cache: false,
      },
    ],
    final: 'googledns',
    strategy: 'ipv4_only',
    /* 开启 ipv6 时改为 prefer_ipv4/prefer_ipv6 即可喵 */
    disable_cache: false,
    disable_expire: false,
  },
  inbounds: [
    {
      tag: 'tun',
      type: 'tun',
      interface_name: 'wlan9',
      inet4_address: '172.19.0.1/30',
      inet6_address: 'fdfe:dcba:9876::1/126',
      mtu: 36000,
      auto_route: true,
      strict_route: true,
      stack: 'system',
      sniff: true,
      sniff_override_destination: true,
      domain_strategy: 'ipv4_only',
    },
  ],
  outbounds: [
    {
      tag: 'direct',
      type: 'direct',
    },
    {
      tag: 'block',
      type: 'block',
    },
    {
      tag: 'dns',
      type: 'dns',
    },
  /*
    {
      tag: 'proxyServerNameServerOut',
      type: 'selector',
      outbounds: [
        'direct',
        '国内',
      ],
      default: '国内',
    },
  */
    {
      tag: 'proxy',
      type: 'selector',
      outbounds: [
        'domestic',
      ],
    },
    {
      tag: '国内',
      type: 'selector',
      outbounds: [
        '橘子国内',
        '橘子国内 - 自动选择',
        '国际国内',
        '国际国内 - 自动选择',
        '倾城云国内',
        '倾城云国内 - 自动选择',
        '国外',
      ],
    },
    {
      tag: '故障转移',
      type: 'selector',
      outbounds: [
        '倾城云国内 - 自动选择',
        '倾城云国内',
        'direct',
      ],
    },
    {
      tag: 'UDP 代理',
      type: 'selector',
      outbounds: [
        '橘子国内 - 自动选择',
        'direct',
        '自建 UDP',
      ],
    },
    {
      tag: '国外',
      type: 'selector',
      outbounds: [
        '一元国外 - 自动选择',
        '国际国外 - 自动选择',
      ],
    },
    {
      tag: 'domestic',
      type: 'selector',
      outbounds: [
        'direct',
        'proxy',
      ],
    },
  ],
  route: {
    geosite: {
      path: './src/geosite.db',
      download_url: 'https://raw.githubusercontent.com/CHIZI-0618/v2ray-rules-dat/release/geosite.db',
      download_detour: '国外',
    },
    geoip: {
      path: './src/geoip.db',
      download_url: 'https://raw.githubusercontent.com/CHIZI-0618/v2ray-rules-dat/release/geoip.db',
      download_detour: '国外',
    },
    rules: [
      { protocol: 'dns', outbound: 'dns' }, // DNS. 不用管
      //{ package_name: 'com.pubg.krmobile', outbound: '国外' },
      //{ package_name: 'com.tencent.mobileqq', outbound: '故障转移' },
      {
        type: 'logical',
        mode: 'or',
        rules: [{ protocol: 'quic' }, { protocol: 'stun', domain_keyword: [ 'bilibili', 'douyu' ], geosite: [ 'bilibili', 'douyu' ] }],
        invert: false,
        outbound: 'block'
      },
      { network: 'udp', geoip: 'cn', geosite: 'cn', outbound: 'UDP 代理' },
      //{ geosite: 'tencent', geoip: 'tencent', outbound: '故障转移' },
      { geosite: [ 'google', 'bytedance@!cn', 'microsoft' ], outbound: '国外' },
      { ip_cidr: [ '47.246.0.0/16', '128.1.157.0/24', '198.11.128.0/18' ], geosite: 'cn', geoip: 'cn', outbound: '国内' },
    ],
    final: '国外',
    auto_detect_interface: true,
    find_process: true,
  },
  experimental: {
    clash_api: {
      /* 此项目可自定义，相关参数设置及网路面板地址与 clash 保持一致喵 */
      external_controller: ':9909',
      /*
        依据 : 划分，可得到两个参数 ${host} 和 ${port}
        若 ${host} 为空，默认解析为 0.0.0.0，即任意地址
        本机访问时，0.0.0.0 可视作 127.0.0.1
      */
      external_ui: 'Dashboard',
      default_mode: 'rule',
      // 预置三种模式，rule global direct
      secret: 'singBox',
      // 由上可得网路面板访问地址为 http://${host}:${port}/ui/?hostname=${host}&port=${port}&secret=${secret}
      cache_file: './src/cache.db',
      store_selected: true,
    },
  },
}

### Server and client log file

日志暂时没开，希望你们可以看看图文🌝🌝🌝

**Comment by 0730aa** [comment]
纠正一下，path 是改成"/"，不是改成"\"

**Comment by nekohasekai** [comment]
该 ?ed 参数是 xray 程序发明的快捷配置方法，并不作为实际参数发送。要学习如何配置 WebSocket Early Data 相关功能，请查看文档。
