### ISSUE TITLE
Document request: Redirect proxy example

### ISSUE THREAD

**Issue by Ali-Flt** [SagerNet/sing-box#360]
Sing-box looks like a decent proxy software. But the documentation need more attention. Not really that easy to use and not many use-case examples are available.
I want to use it as a redirect/tproxy transparent proxy in my home server. So outbound : vmess, inbound: redirect/tproxy
Setting up the outbound is easy but other configs (dns, inbounds, rules) are not easy to do without an example.
Could you add more examples?
Thanks

**Comment by 1sling5stones** [comment]
Can you point me to an example where I can use sing-box as a transparent proxy? E.g. can I on my router change the gateway to the Ip address of the sing-box machine?
