### ISSUE TITLE
1.2-beta4 server ERROR: inject shadowsocks-in: unknown address family: 71

### ISSUE THREAD

**Issue by AmberisMyShiba** [SagerNet/sing-box#372]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

ShadowTLS detour ss ,version 1.2-beta4
client no errors
server error:**inject shadowsocks-in: unknown address family: 71**

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```

sing-box version 1.2-beta4

Environment: go1.20.1 linux/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: e99741159bcc3e863534219835286b5d534585e5
CGO: disabled

</details>

### Server and client configuration file

<details>

```console
# paste json here
```
## server config
{
  "log": {
    "level": "debug",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "address": "tls://8.8.8.8"
      }
    ]
  },
  "inbounds": [
    {
      "type": "shadowtls",
      "detour": "shadowsocks-in",
      "listen": "::",
      "listen_port": 4443,
      "version": 3,
      "strict_mode": true,
        "users": [
        {
          "name": "A-001",
          "password": "mypassword"
        }
      ],
       "handshake": {
        "server": "cloudflare.com",
        "server_port": 443
      }
    },
    {
      "type": "shadowsocks",
      "tag": "shadowsocks-in",
      "listen": "127.0.0.1",
      "listen_port": 8443,
      "sniff": true,
      "method": "none",
      "password": ""
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "geoip": {
      "path": "/usr/local/etc/sing-box/geoip.db",
      "download_url": "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db",
      "download_detour": "direct"
    },
    "geosite": {
      "path": "/usr/local/etc/sing-box/geosite.db",
      "download_url": "https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db",
      "download_detour": "direct"
    },
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "protocol": "bittorrent",
        "geosite": [
          "cn",
          "category-ads-all"
        ],
        "geoip": [
          "cn",
          "private"
        ],
        "outbound": "block"
      }
    ]
  }
}

## Client config
{
 "log": {
    "level": "info",
    "timestamp":true,
    "output":""
  },
  "dns": {
    "servers": [
      {
        "tag": "google",
        "address": "tls://8.8.8.8"
      },
      {
        "tag": "local",
        "address": "223.5.5.5",
        "detour": "direct"
      }
    ],
    "rules": [
      {
        "domain": [
          "mydomain.abc"
        ],
        "geosite": "cn",
        "server": "local"
      }
    ],
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
        "type": "mixed",
        "tag": "mixed-in",
        "listen": "::",   
        "listen_port": 8010
    }
  ],
  "outbounds": [
    {
      "type": "shadowsocks",
      "tag": "ss-out-dmit",
      "detour": "shadowtls-out",
      "method": "none",
      "password": "",
      "multiplex": {
        "enabled": true,
        "max_connections": 4,
        "min_streams": 4
      }
    },
    {
      "type": "shadowtls",
      "tag": "shadowtls-out",
      "server": "mydomain.abc",
      "server_port": 4443,
      "version": 3,
      "password": "mypassword",
      "tls": {
        "enabled": true,
        "server_name": "cloudflare.com",
        "utls": {
            "enabled": false,
            "fingerprint": ""
        }
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "geosite": "cn",
        "geoip": "cn",
        "outbound": "direct"
      }
    ],
    "auto_detect_interface": true
  }
}

</details>

### Server and client log file

<details>

```console
# paste log here
```
## Client Log
sing-box run -c config.json 

+0800 2023-02-24 09:27:31 INFO router: loaded geoip database: 250 codes
+0800 2023-02-24 09:27:31 INFO router: loaded geosite database: 1287 codes
+0800 2023-02-24 09:27:31 INFO router: updated default interface enp3s0, index 2
+0800 2023-02-24 09:27:32 INFO inbound/mixed[mixed-in]: tcp server started at [::]:8010
+0800 2023-02-24 09:27:32 INFO inbound/http[http-in]: tcp server started at [::]:1090
+0800 2023-02-24 09:27:32 INFO sing-box started (0.122s)
+0800 2023-02-24 09:27:35 INFO [3546557182] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:54658
+0800 2023-02-24 09:27:35 INFO [3546557182] inbound/mixed[mixed-in]: inbound connection to ip111.cn:80
+0800 2023-02-24 09:27:35 DEBUG [3546557182] router: match[2] domain=[bulianglin.com ip111.cn] => shadowtls-out
+0800 2023-02-24 09:27:35 INFO [4204678550] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:54660
+0800 2023-02-24 09:27:35 DEBUG [3546557182] inbound/mixed[mixed-in]: connection closed: process connection from 127.0.0.1:54658: download: EOF | upload: EOF
+0800 2023-02-24 09:27:35 INFO [4204678550] inbound/mixed[mixed-in]: inbound connection to ip111.cn:80
+0800 2023-02-24 09:27:35 DEBUG [4204678550] router: match[2] domain=[bulianglin.com ip111.cn] => shadowtls-out
+0800 2023-02-24 09:27:36 INFO [3804660282] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:54666
+0800 2023-02-24 09:27:36 DEBUG [4204678550] inbound/mixed[mixed-in]: connection closed: process connection from 127.0.0.1:54660: download: EOF | upload: EOF
+0800 2023-02-24 09:27:36 INFO [3804660282] inbound/mixed[mixed-in]: inbound connection to ip111.cn:80
+0800 2023-02-24 09:27:36 DEBUG [3804660282] router: match[2] domain=[bulianglin.com ip111.cn] => shadowtls-out
+0800 2023-02-24 09:27:36 INFO [3265868986] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:54676
+0800 2023-02-24 09:27:36 DEBUG [3804660282] inbound/mixed[mixed-in]: connection closed: process connection from 127.0.0.1:54666: download: EOF | upload: EOF
+0800 2023-02-24 09:27:36 INFO [3265868986] inbound/mixed[mixed-in]: inbound connection to ip111.cn:80
+0800 2023-02-24 09:27:36 DEBUG [3265868986] router: match[2] domain=[bulianglin.com ip111.cn] => shadowtls-out
+0800 2023-02-24 09:27:37 INFO [1521839652] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:54684
+0800 2023-02-24 09:27:37 DEBUG [3265868986] inbound/mixed[mixed-in]: connection closed: process connection from 127.0.0.1:54676: download: EOF | upload: EOF
+0800 2023-02-24 09:27:37 INFO [1521839652] inbound/mixed[mixed-in]: inbound connection to ip111.cn:80
+0800 2023-02-24 09:27:37 DEBUG [1521839652] router: match[2] domain=[bulianglin.com ip111.cn] => shadowtls-out
+0800 2023-02-24 09:27:37 INFO [3294504587] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:54700
+0800 2023-02-24 09:27:37 DEBUG [1521839652] inbound/mixed[mixed-in]: connection closed: process connection from 127.0.0.1:54684: download: EOF | upload: EOF
+0800 2023-02-24 09:27:37 INFO [3294504587] inbound/mixed[mixed-in]: inbound connection to ip111.cn:80
+0800 2023-02-24 09:27:37 DEBUG [3294504587] router: match[2] domain=[bulianglin.com ip111.cn] => shadowtls-out
+0800 2023-02-24 09:27:37 INFO [3680190721] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:54712
+0800 2023-02-24 09:27:37 DEBUG [3294504587] inbound/mixed[mixed-in]: connection closed: process connection from 127.0.0.1:54700: download: EOF | upload: EOF
+0800 2023-02-24 09:27:37 INFO [3680190721] inbound/mixed[mixed-in]: inbound connection to ip111.cn:80
+0800 2023-02-24 09:27:37 DEBUG [3680190721] router: match[2] domain=[bulianglin.com ip111.cn] => shadowtls-out
+0800 2023-02-24 09:27:38 INFO [3238992361] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:54716
+0800 2023-02-24 09:27:38 DEBUG [3680190721] inbound/mixed[mixed-in]: connection closed: process connection from 127.0.0.1:54712: download: EOF | upload: EOF
+0800 2023-02-24 09:27:38 INFO [3238992361] inbound/mixed[mixed-in]: inbound connection to ip111.cn:80
+0800 2023-02-24 09:27:38 DEBUG [3238992361] router: match[2] domain=[bulianglin.com ip111.cn] => shadowtls-out
+0800 2023-02-24 09:27:38 INFO [1288551385] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:54732
+0800 2023-02-24 09:27:38 DEBUG [3238992361] inbound/mixed[mixed-in]: connection closed: process connection from 127.0.0.1:54716: download: EOF | upload: EOF
+0800 2023-02-24 09:27:38 INFO [1288551385] inbound/mixed[mixed-in]: inbound connection to ip111.cn:80
+0800 2023-02-24 09:27:38 DEBUG [1288551385] router: match[2] domain=[bulianglin.com ip111.cn] => shadowtls-out
+0800 2023-02-24 09:27:39 INFO [4253944495] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:54740

## Serverlog

journalctl -u sing-box.service -f -o cat
+0000 2023-02-24 01:29:18 INFO router: loaded geoip database: 250 codes
+0000 2023-02-24 01:29:18 INFO router: loaded geosite database: 1359 codes
+0000 2023-02-24 01:29:19 INFO inbound/shadowtls[0]: tcp server started at 0.0.0.0:4443
+0000 2023-02-24 01:29:19 INFO inbound/shadowsocks[shadowsocks-in]: tcp server started at 127.0.0.1:36829
+0000 2023-02-24 01:29:19 INFO inbound/shadowsocks[shadowsocks-in]: udp server started at 127.0.0.1:34628
+0000 2023-02-24 01:29:19 INFO sing-box started (0.122s)
+0000 2023-02-24 01:29:26 INFO [3012506661] inbound/shadowtls[0]: inbound connection from 122.226.16.234:6906
+0000 2023-02-24 01:29:26 DEBUG [58248434] dns: lookup domain cloudflare.com
+0000 2023-02-24 01:29:26 INFO outbound/direct[direct]: outbound connection to 8.8.8.8:853
+0000 2023-02-24 01:29:26 DEBUG [58248434] dns: exchanged cloudflare.com NOERROR 600
+0000 2023-02-24 01:29:26 DEBUG [58248434] dns: exchanged cloudflare.com AAAA cloudflare.com. 300 IN AAAA 2606:4700::6810:84e5
+0000 2023-02-24 01:29:26 DEBUG [58248434] dns: exchanged cloudflare.com AAAA cloudflare.com. 300 IN AAAA 2606:4700::6810:85e5
+0000 2023-02-24 01:29:26 DEBUG [58248434] dns: exchanged cloudflare.com NOERROR 600
+0000 2023-02-24 01:29:26 DEBUG [58248434] dns: exchanged cloudflare.com A cloudflare.com. 300 IN A 104.16.132.229
+0000 2023-02-24 01:29:26 DEBUG [58248434] dns: exchanged cloudflare.com A cloudflare.com. 300 IN A 104.16.133.229
+0000 2023-02-24 01:29:26 DEBUG [58248434] dns: lookup succeed for cloudflare.com: 104.16.132.229 104.16.133.229 2606:4700::6810:84e5 2606:4700::6810:85e5
+0000 2023-02-24 01:29:26 INFO [58248434] inbound/shadowtls[0]: inbound connection to 67.230.171.156:4443
+0000 2023-02-24 01:29:26 ERROR [3012506661] inbound/shadowtls[0]: process connection from 122.226.16.234:6906: inject shadowsocks-in: unknown address family: 71
+0000 2023-02-24 01:29:26 INFO [3806208955] inbound/shadowtls[0]: inbound connection from 122.226.16.234:6910
+0000 2023-02-24 01:29:26 DEBUG [357257015] dns: lookup domain cloudflare.com
+0000 2023-02-24 01:29:26 DEBUG [357257015] dns: lookup succeed for cloudflare.com: 104.16.132.229 104.16.133.229 2606:4700::6810:84e5 2606:4700::6810:85e5
+0000 2023-02-24 01:29:26 INFO [357257015] inbound/shadowtls[0]: inbound connection to 67.230.171.156:4443
+0000 2023-02-24 01:29:26 ERROR [3806208955] inbound/shadowtls[0]: process connection from 122.226.16.234:6910: inject shadowsocks-in: unknown address family: 71

</details>

**Comment by AmberisMyShiba** [comment]
以解决。服务端的ss-in删除server字段即可。

**Comment by freedgw** [comment]
> solved. delete server field in ss-in。

hello，I encounter the same problem on Windows terminal: traffic hijacked or TLS1.3 is not supported.
Could you give a clue about how to solve the problem?

**Comment by AmberisMyShiba** [comment]
> > solved. delete server field in ss-in。
> 
> hello，I encounter the same problem on Windows terminal: traffic hijacked or TLS1.3 is not supported. Could you give a clue about how to solve the problem?

pls post your client and server config files.

**Comment by freedgw** [comment]
> > > solved. delete server field in ss-in。
> > 
> > 
> > hello，I encounter the same problem on Windows terminal: traffic hijacked or TLS1.3 is not supported. Could you give a clue about how to solve the problem?
> 
> pls post your client and server config files.

Hi, my server config is:
```json
{
  "inbounds": [
    {
      "type": "shadowtls",
      "listen": "::",
      "listen_port": 4443,
      "version": 3,
      "users": [
        {
          "name": "xxx",
          "password": "8JCsPssfgS8tiRwiMlhARg=="
        }
      ],
      "handshake": {
        "server": "bing.com",
        "server_port": 443
      },
      "detour": "shadowsocks-in"
    },
    {
      "type": "shadowsocks",
      "tag": "shadowsocks-in",
      "listen": "127.0.0.1",
      "method": "2022-blake3-aes-128-gcm",
      "password": "8JCsPssfgS8tiRwiMlhARg=="
    }
  ]
}

```

the client's config:
```json
{
  "inbounds": [
    {
      "type": "mixed",
      "listen_port": 7080,
      "sniff": true,
      "set_system_proxy": true
    }
  ],
  "outbounds": [
    {
      "type": "shadowsocks",
      "method": "2022-blake3-aes-128-gcm",
      "password": "8JCsPssfgS8tiRwiMlhARg==",
      "detour": "shadowtls-out",
      "multiplex": {
        "enabled": true,
        "max_connections": 4,
        "min_streams": 4
      }
    },
    {
      "type": "shadowtls",
      "tag": "shadowtls-out",
      "server": "ip",
      "server_port": 4443,
      "version": 3,
      "tls": {
        "enabled": true,
        "server_name": "bing.com",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    }
  ],
  "route": {
    "rules": [
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "geosite": "cn",
        "geoip": "cn",
        "outbound": "direct"
      }
    ]
  }
}
```

**Comment by AmberisMyShiba** [comment]
> > > > solved. delete server field in ss-in。
> > > 
> > > 
> > > hello，I encounter the same problem on Windows terminal: traffic hijacked or TLS1.3 is not supported. Could you give a clue about how to solve the problem?
> > 
> > 
> > pls post your client and server config files.
> 
> Hi, my server config is:
> 
> ```json
> {
>   "inbounds": [
>     {
>       "type": "shadowtls",
>       "listen": "::",
>       "listen_port": 4443,
>       "version": 3,
>       "users": [
>         {
>           "name": "xxx",
>           **"password": "ABcd1234"**
>         }
>       ],
>       "handshake": {
>         "server": "bing.com",
>         "server_port": 443
>       },
>       "detour": "shadowsocks-in"
>     },
>     {
>       "type": "shadowsocks",
>       "tag": "shadowsocks-in",
>       "listen": "127.0.0.1",
>       "method": "2022-blake3-aes-128-gcm",
>       "password": "8JCsPssfgS8tiRwiMlhARg=="
>     }
>   ]
> }
> ```
> 
> the client's config:
> 
> ```json
> {
>   "inbounds": [
>     {
>       "type": "mixed",
>       "listen_port": 7080,
>       "sniff": true,
>       "set_system_proxy": true
>     }
>   ],
>   "outbounds": [
>     {
>       "type": "shadowsocks",
>       "method": "2022-blake3-aes-128-gcm",
>       "password": "8JCsPssfgS8tiRwiMlhARg==",
>       "detour": "shadowtls-out",
>       "multiplex": {
>         "enabled": true,
>         "max_connections": 4,
>         "min_streams": 4
>       }
>     },
>     {
>       "type": "shadowtls",
>       "tag": "shadowtls-out",
>       "server": "ip",
>       "server_port": 4443,
>       "version": 3,
>       **"passowrd": "ABcd1234",**
>       "tls": {
>         "enabled": true,
>         "server_name": "bing.com",
>         "utls": {
>           "enabled": true,
>           "fingerprint": "chrome"
>         }
>       }
>     },
>     {
>       "type": "direct",
>       "tag": "direct"
>     },
>     {
>       "type": "block",
>       "tag": "block"
>     }
>   ],
>   "route": {
>     "rules": [
>       {
>         "geosite": "category-ads-all",
>         "outbound": "block"
>       },
>       {
>         "geosite": "cn",
>         "geoip": "cn",
>         "outbound": "direct"
>       }
>     ]
>   }
> }
> ```

I think you should add password field in shadowtls section

**Comment by freedgw** [comment]
> > > > > solved. delete server field in ss-in。
> > > > 
> > > > 
> > > > hello，I encounter the same problem on Windows terminal: traffic hijacked or TLS1.3 is not supported. Could you give a clue about how to solve the problem?
> > > 
> > > 
> > > pls post your client and server config files.
> > 
> > 
> > Hi, my server config is:
> > ```json
> > {
> >   "inbounds": [
> >     {
> >       "type": "shadowtls",
> >       "listen": "::",
> >       "listen_port": 4443,
> >       "version": 3,
> >       "users": [
> >         {
> >           "name": "xxx",
> >           **"password": "ABcd1234"**
> >         }
> >       ],
> >       "handshake": {
> >         **"server": "aws.amazon.com",**
> >         "server_port": 443
> >       },
> >       "detour": "shadowsocks-in"
> >     },
> >     {
> >       "type": "shadowsocks",
> >       "tag": "shadowsocks-in",
> >       "listen": "127.0.0.1",
> >       "method": "2022-blake3-aes-128-gcm",
> >       "password": "8JCsPssfgS8tiRwiMlhARg=="
> >     }
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the client's config:
> > ```json
> > {
> >   "inbounds": [
> >     {
> >       "type": "mixed",
> >       "listen_port": 7080,
> >       "sniff": true,
> >       "set_system_proxy": true
> >     }
> >   ],
> >   "outbounds": [
> >     {
> >       "type": "shadowsocks",
> >       "method": "2022-blake3-aes-128-gcm",
> >       "password": "8JCsPssfgS8tiRwiMlhARg==",
> >       "detour": "shadowtls-out",
> >       "multiplex": {
> >         "enabled": true,
> >         "max_connections": 4,
> >         "min_streams": 4
> >       }
> >     },
> >     {
> >       "type": "shadowtls",
> >       "tag": "shadowtls-out",
> >       "server": "ip",
> >       "server_port": 4443,
> >       "version": 3,
> >       **"passowrd": "ABcd1234",**
> >       "tls": {
> >         "enabled": true,
> >         **"server_name": "aws.amazon.com",**
> >         "utls": {
> >           "enabled": true,
> >           "fingerprint": "chrome"
> >         }
> >       }
> >     },
> >     {
> >       "type": "direct",
> >       "tag": "direct"
> >     },
> >     {
> >       "type": "block",
> >       "tag": "block"
> >     }
> >   ],
> >   "route": {
> >     "rules": [
> >       {
> >         "geosite": "category-ads-all",
> >         "outbound": "block"
> >       },
> >       {
> >         "geosite": "cn",
> >         "geoip": "cn",
> >         "outbound": "direct"
> >       }
> >     ]
> >   }
> > }
> > ```
> 
> I suggest changing your password field in shadowtls block(it should be a text). And then, it looks like the website **bing.com** doesn't support TLS1.3, I suggest replacing **bing.com** with another site. If it doesn't work either, try to streamline your config, remove all additional lines and blocks, only reserve basic connection blocks.In my experience, keeping the **method** and the **password** in shadowsocks configures with "none" is a good way to debug.

Thanks for your suggestions! It seems bing does't support tls1.3. Changing the website works.

**Comment by andfk44** [comment]
{
  "inbounds": [
    {
      "type": "shadowtls",
      "listen": "::",
      "listen_port": 4443,
      "version": 3,
      "users": [
        {
          "name": "xxx",
          **"password": "ABcd1234"**
        }
      ],
      "handshake": {
        **"server": "aws.amazon.com",**
        "server_port": 443
      },
      "detour": "shadowsocks-in"
    },
    {
      "type": "shadowsocks",
      "tag": "shadowsocks-in",
      "listen": "127.0.0.1",
      "method": "2022-blake3-aes-128-gcm",
      "password": "8JCsPssfgS8tiRwiMlhARg=="
    }
  ]
}
客户端的配置：

{
  "inbounds": [
    {
      "type": "mixed",
      "listen_port": 7080,
      "sniff": true,
      "set_system_proxy": true
    }
  ],
  "outbounds": [
    {
      "type": "shadowsocks",
      "method": "2022-blake3-aes-128-gcm",
      "password": "8JCsPssfgS8tiRwiMlhARg==",
      "detour": "shadowtls-out",
      "multiplex": {
        "enabled": true,
        "max_connections": 4,
        "min_streams": 4
      }
    },
    {
      "type": "shadowtls",
      "tag": "shadowtls-out",
      "server": "ip",
      "server_port": 4443,
      "version": 3,
      **"passowrd": "ABcd1234",**
      "tls": {
        "enabled": true,
        **"server_name": "aws.amazon.com",**
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    }
  ],
  "route": {
    "rules": [
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "geosite": "cn",
        "geoip": "cn",
        "outbound": "direct"
      }
    ]
  }
}

大佬好，上面的客户端很好用，求个tun模式的客户端。

**Comment by andfk44** [comment]
{
  "inbounds": [
    {
      "type": "shadowtls",
      "listen": "::",
      "listen_port": 4443,
      "version": 3,
      "users": [
        {
          "name": "xxx",
          **"password": "ABcd1234"**
        }
      ],
      "handshake": {
        **"server": "aws.amazon.com",**
        "server_port": 443
      },
      "detour": "shadowsocks-in"
    },
    {
      "type": "shadowsocks",
      "tag": "shadowsocks-in",
      "listen": "127.0.0.1",
      "method": "2022-blake3-aes-128-gcm",
      "password": "8JCsPssfgS8tiRwiMlhARg=="
    }
  ]
}
客户端的配置：

{
  "inbounds": [
    {
      "type": "mixed",
      "listen_port": 7080,
      "sniff": true,
      "set_system_proxy": true
    }
  ],
  "outbounds": [
    {
      "type": "shadowsocks",
      "method": "2022-blake3-aes-128-gcm",
      "password": "8JCsPssfgS8tiRwiMlhARg==",
      "detour": "shadowtls-out",
      "multiplex": {
        "enabled": true,
        "max_connections": 4,
        "min_streams": 4
      }
    },
    {
      "type": "shadowtls",
      "tag": "shadowtls-out",
      "server": "ip",
      "server_port": 4443,
      "version": 3,
      **"passowrd": "ABcd1234",**
      "tls": {
        "enabled": true,
        **"server_name": "aws.amazon.com",**
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    }
  ],
  "route": {
    "rules": [
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "geosite": "cn",
        "geoip": "cn",
        "outbound": "direct"
      }
    ]
  }
}
大佬好，上面的客户端很好用，求个tun模式的客户端，谢谢。
