### ISSUE TITLE
Socks5 UDP error when server is not 127.0.0.1

### ISSUE THREAD

**Issue by arm64v8a** [SagerNet/sing-box#374]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

sing-box as socks5 client

It looks like the socks udp traffic is sent to 127.0.0.1 when the server doesn't specify a bind IP.

https://github.com/SagerNet/sing/blob/3401d210384bae25c540993262295d4dbec398e3/protocol/socks/client.go#L136-L150

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.2-beta4

Environment: go1.20.1 linux/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: e99741159bcc3e863534219835286b5d534585e5
CGO: disabled
```

</details>

### Server and client configuration file

<details>

Client:

```json
{
    "inbounds": [
        {
            "type": "tun",
            "interface_name": "tun0",
            "inet4_address": "172.19.0.1/28",
            "mtu": 9000,
            "auto_route": false,
            "strict_route": false,
            "stack": "system",
            "endpoint_independent_nat": true,
            "sniff": false
        }
    ],
    "outbounds": [
        {
            "type": "socks",
            "tag": "socks-out",
            "udp_fragment": true,
            "server": "x.x.x.x",
            "server_port": 1080
        }
    ]
}
```

</details>

### Server and client log file

<details>

```console
Server: No Log

Client:
INFO[0000] inbound/tun[0]: started at tun0
INFO[0000] sing-box started (0.00s)
INFO[0002] [1549936579] inbound/tun[0]: inbound packet connection from 172.19.0.1:44678
INFO[0002] [1549936579] inbound/tun[0]: inbound packet connection to 8.8.8.8:53
INFO[0002] [1549936579] outbound/socks[socks-out]: outbound packet connection to 8.8.8.8:53
ERROR[0002] [1549936579] inbound/tun[0]: download: read udp 127.0.0.1:59153->127.0.0.1:1080: read: connection refused | upload: io: read/write on closed pipe
```

</details>

**Comment by nekohasekai** [comment]
I think the server returned 127.0.0.1 on purpose because bind is not optional.
