### ISSUE TITLE
自定义安装，默认是以sing-box version 1.1.6构建，请问如何构建最新版本？

### ISSUE THREAD

**Issue by chika0801** [SagerNet/sing-box#379]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

使用自定义安装 reality，命令如下：
`go install -v -tags with_reality_server github.com/sagernet/sing-box/cmd/sing-box@latest`

得到的文件显示是以1.1.6版本构建的，不支持VLESS协议

```
FATAL[0000] decode config: unknown inbound type: vless
```

```
root@localhost:~# sing-box version
sing-box version 1.1.6

Environment: go1.20.1 linux/amd64
Tags: with_reality_server
CGO: disabled
```

请问以最新源码构建的命令是什么？

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by kunish** [comment]
go install 支持传入不同的 revision

改一下分支就好了

```shell
go install -v -tags with_reality_server github.com/sagernet/sing-box/cmd/sing-box@dev-next
```

**Comment by chika0801** [comment]
感谢你的帮助

**Comment by kunish** [comment]
不客气

**Comment by chika0801** [comment]
> go install 支持传入不同的 revision
> 
> 改一下分支就好了
> 
> ```shell
> go install -v -tags with_reality_server github.com/sagernet/sing-box/cmd/sing-box@dev-next
> ```

不好意义，再请问一个问题。

我用 vps 编译，系统是 debian11，我要编译一个windows平台 amd64的.exe 。

请问命令 go install 命令是什么？

**Comment by kunish** [comment]
添加golang的环境变量

```shell
GOOS=windows GOARCH=amd64 go install github.com/sagernet/sing-box/cmd/sing-box@dev-next
```

**Comment by chika0801** [comment]
> 添加 golang 的环境变量
> 
> ```shell
> GOOS=windows GOARCH=amd64 go install github.com/sagernet/sing-box/cmd/sing-box@dev-next
> ```

感谢你的回复

**Comment by kunish** [comment]
没事
