### ISSUE TITLE
Feature request: shadowsocks AEAD inbound Single-port Multi-user

### ISSUE THREAD

**Issue by zakuwaki** [SagerNet/sing-box#38]
Hi, sing-box has already implemented single-port multi-user for aead2022. However, many low-end devices can only run shadowsocks-libev which only supports old aead methods like `chacha20-ietf-poly1305` and `aes-128-gcm`. It is worth considering to add multi-user support for these methods. Meanwhile, it's more better if different users can use different aead ciphers in multi-user mode.

Xray supports it by ranging all users https://github.com/XTLS/Xray-core/blob/33755d6e908227f270881e7b859eabedb393c3dc/proxy/shadowsocks/protocol.go#L93-L111

**Comment by nekohasekai** [comment]
This method is ugly and low performance.

**Comment by nekohasekai** [comment]
What device can't run shadowsocks-rust?

**Comment by zakuwaki** [comment]
> This method is ugly and low performance.
Yes, I agree...

> What device can't run shadowsocks-rust?
Like lots of old routers(k2/k2p) with padavan or openwrt. Also [ShadowsocksX-NG](https://github.com/shadowsocks/ShadowsocksX-NG) does not support aead2022 either. But they really work stably.

In this case a client sing-box serves as a relay in GFW or rather in CRENET, and connects to the remote sing-box server using trojan.

**Comment by nekohasekai** [comment]
Various proxy frontend projects are usually of lower quality and there is no reason to give in for them.
