### ISSUE TITLE
Enable XUDP packet encoding with VLESS will result in UDPBlocked

### ISSUE THREAD

**Issue by WitchHuntTV** [SagerNet/sing-box#382]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

Using VLESS protocol , With xtls-rprx-vision flow, Reality security, Xray-core server(latest artifact),Tested with both "packet_encoding": "xudp" and "packet_encoding": "", The former blocks UDP connection while the latter can use UDP but not fullcone.
That most likely not server or TUN interface issue, Because when using xray-core as REALITY client, sing-box as tun interface(outbound to socks5 of xray-core), Fullcone UDP works normally.

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.2-beta5

Environment: go1.20.1 windows/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: cd5c2a7999b157e3ca25b35a958a050efee9456c
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```console
  "outbounds": [
    {
      "type": "vless",
      "tag": "proxy",
    
      "server": "example",
      "server_port": 443,
      "uuid": "example",
      "flow": "xtls-rprx-vision",
      "tls": {
        "enabled": true,
        "disable_sni": false,
        "server_name": "example.com",
        "insecure": false,
        "alpn": ["h2,http/1.1"],
        "min_version": "1.3",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "example",
          "short_id": "example"
        }
      },
      "tcp_fast_open": true,
      "packet_encoding": "xudp"
    }
]
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by luotuoa233** [comment]
some ai issus want to be chat with each other on a safty platform

**Comment by mclovin-2k** [comment]
Same issue here.

**Comment by simplerick-simplefun** [comment]
should be fixed now with lastest commit of sing-box([dab6803](https://github.com/SagerNet/sing-box/commit/dab680326180bd5fcc15e3b403e6e03965d274c5)) running client side, latest Xray core (1.8.1) running server side.
Ref: https://github.com/SagerNet/sing-box/issues/540

**Comment by amirarad6** [comment]
gh repo clone MatsuriDayo/NekoBoxForAndroid

**Comment by amirarad6** [comment]
Thank you
