### ISSUE TITLE
可以提供mipsle的版本吗？

### ISSUE THREAD

**Issue by weihu120** [SagerNet/sing-box#395]
你好，可以编译一个mipsle的版本吗，我想在路由器上使用，谢谢！

**Comment by Chikage0o0** [comment]
openwrt吗？直接安装ipk就行了

**Comment by yaotthaha** [comment]
golang支持交叉编译，直接编译使用即可

**Comment by weihu120** [comment]
> openwrt吗？直接安装ipk就行了

自已用go编译了一份，目前正在用着。

**Comment by weihu120** [comment]
> golang支持交叉编译，直接编译使用即可
> 
> ```
> GOMIPS=softfloat GOOS=linux GOARCH=mipsle make build
> ```

已经弄好了

**Comment by zjsailor** [comment]
我也编译成功了一个,mips平台的，谁要可以省点力气，直接拿走使用，该链接1年有效。
http://173.249.201.185:8080/api/public/dl/8u2iNWPE/youtube/sing-box
以下网盘，应该一直有效
https://drive.google.com/file/d/1ErtzvYbWZzS8PhZmj5BJgcmBkLCX6xQA/view?usp=drive_link
