### ISSUE TITLE
Reload will fail when `clash_api.store_selected` is enabled

### ISSUE THREAD

**Issue by kanna5** [SagerNet/sing-box#406]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

When performing the [check](https://github.com/SagerNet/sing-box/blob/dd0a07624edd45c8c52d196c664863214fdc0249/cmd/sing-box/cmd_run.go#L107) before reloading config, a [new instance](https://github.com/SagerNet/sing-box/blob/dd0a07624edd45c8c52d196c664863214fdc0249/cmd/sing-box/cmd_check.go#L34) is created, it will try to [open](https://github.com/SagerNet/sing-box/blob/dd0a07624edd45c8c52d196c664863214fdc0249/experimental/clashapi/server.go#L78) the cache file, which would still be locked by the running instance. So the check will always timeout and fail.

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.2-beta5

Environment: go1.20.1 linux/amd64
Tags: with_acme,with_clash_api,with_dhcp,with_ech,with_grpc,with_gvisor,with_quic,with_shadowsocksr,with_utls,with_v2ray_api,with_wireguard
Revision: cd5c2a7999b157e3ca25b35a958a050efee9456c
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```console
{
  "log": { "level": "debug" },
  "inbounds": [
    {
      "tag": "i",
      "type": "direct"
    }
  ],
  "outbounds": [
    {
      "tag": "sel",
      "type": "selector",
      "outbounds": ["o"],
      "default": "o"
    },
    {
      "tag": "o",
      "type": "direct"
    }
  ],
  "experimental": {
    "clash_api": {
      "external_controller": "127.0.0.1:9090",
      "secret": "rqITpB-2e8k",
      "store_selected": true
    }
  }
}
```

</details>

### Server and client log file

<details>

```console
INFO[0000] inbound/direct[i]: tcp server started at [::]:32787
INFO[0000] inbound/direct[i]: udp server started at [::]:53289
INFO[0000] clash-api: restful api listening at 127.0.0.1:9090
INFO[0000] sing-box started (0.00s)
ERROR[0038] reload service: create clash api server: open cache file: timeout
```

</details>

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/9f80bb181050c7c9a4858c728a88dc97137843ce

**Comment by kanna5** [comment]
Thank you for your response!

With https://github.com/SagerNet/sing-box/commit/9f80bb181050c7c9a4858c728a88dc97137843ce I'm getting segfault when starting the selector outbound. (With same config file as above)

```plain
bash $ sing-box run
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd5c9f9]

goroutine 1 [running]:
github.com/sagernet/sing-box/outbound.(*Selector).Start(0xc0001d7860)
	github.com/sagernet/sing-box/outbound/selector.go:65 +0x279
github.com/sagernet/sing-box.(*Box).start(0xc000156630)
	github.com/sagernet/sing-box/box.go:218 +0xa7
github.com/sagernet/sing-box.(*Box).Start(0xc000132f60?)
	github.com/sagernet/sing-box/box.go:199 +0x39
main.create()
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:86 +0x45a
main.run()
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:99 +0x118

```

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/a2d43b3746e14017f9a48a6065cc271d4c103d57

**Comment by kanna5** [comment]
I did some tests, and it is working now.
