### ISSUE TITLE
1.2-beta6 没改版本号，检查sing-box version还是beta5

### ISSUE THREAD

**Issue by simplerick-simplefun** [SagerNet/sing-box#408]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

https://github.com/SagerNet/sing-box/blob/ac7cc09694f39b3f802cc56638c17e50bab41e0d/constant/version.go#L3

\sing-box-1.2-beta6-windows-amd64v3> ./sing-box version
sing-box version 1.2-beta5

Environment: go1.20.1 windows/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: ac7cc09694f39b3f802cc56638c17e50bab41e0d
CGO: disabled

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by Gzxhwq** [comment]
应该是世界忘记改了，可以在编译时通过-ldflags -X参数指定

-ldflags "-s -w -buildid= -X 'github.com/sagernet/sing-box/constant.Version=v1.2-beta6'"

**Comment by nekohasekai** [comment]
确实。
