### ISSUE TITLE
Suggestion: release IPA package for iOS

### ISSUE THREAD

**Issue by WitchHuntTV** [SagerNet/sing-box#409]
Congratulations on your iOS release! I believe that iOS users will be very happy. Sing-Box uses latest protocols and is free. Such good platform like this, TestFlight will be full soon.

If the IPA package is released, we can still install it through technical means like Sideloadly even after it is full.

**Comment by nekohasekai** [comment]
I think this is not necessary. The quota for TF internal testing currently only accounts for 0.3%.

**Comment by luotuoa233** [comment]
leave your safty email,i will attach you in the time.thanks

**Comment by xiaojinlii** [comment]
I want to experience the preview version of the client on iOS. I can use sidestore to self-sign the certificate, but only the stable version is available in the App Store. Therefore, I hope to release the release IPA package.
