### ISSUE TITLE
Features Requests: Add Support Conn Handling/PolicyObject

### ISSUE THREAD

**Issue by malikshi** [SagerNet/sing-box#413]
i don't know if these features already implemented or not but it's great addtional features. 
cases for server used 1 people usually having 10-20 active connections for very long time. if 100 people using it will be 1000+ active connections eating resources. Could you please add support for policyobject/conn handler for solve cases like that?
Thank your for your hard work!

reff: https://xtls.github.io/en/config/policy.html#policyobject

**Comment by nekohasekai** [comment]
作为从 v2ray 继承而来的功能之一，它在很多地方不生效，并且不是一个好的设计。

**Comment by malikshi** [comment]
> 作为从 v2ray 继承而来的功能之一，它在很多地方不生效，并且不是一个好的设计。

thank you for the explanation. 
it there any other good ideas to solve longtime connections, or leave it be those connections.
