### ISSUE TITLE
sing-box里集成的shadow-tls v3是否有原版的SNI Proxy特性？

### ISSUE THREAD

**Issue by 70599** [SagerNet/sing-box#415]
https://github.com/ihciah/shadow-tls/wiki/How-to-Run#common-issues

> I want to use port 443, but it is already used by nginx: Shadow-tls support multiple SNI now, so it can be used as a SNI proxy. Let your nginx listen on 127.0.0.1:8443, and use tls settings like your.domain:127.0.0.1:8443;captive.apple.com;www.feishu.cn.

主要是多SNI和SNI代理（可以复用443端口）

**Comment by nekohasekai** [comment]
`handshake_for_server_name`

**Comment by 70599** [comment]
> `handshake_for_server_name`

`handshake_for_server_name`可以添加多个吗？文档里看起来没有数组

**Comment by nekohasekai** [comment]
重新阅读文档。

**Comment by 70599** [comment]
> 重新阅读文档。

反复查看文档，`handshake_for_server_name`字段下实在是没有看到数组。
不知道怎么配置我链接里，原版shadow-tls那样的3个、或更多域名。

刚才尝试这样的配置实现了2个域名（shadow-tls和vless reality共用443端口）
```json
"handshake": {
  "server": "captive.apple.com",
  "server_port": 443
},
"handshake_for_server_name": {
  "www.lovelive-anime.jp": {
    "server": "127.0.0.1",
    "server_port": 50443
  }
}
```

能加入更多域名吗？

**Comment by nekohasekai** [comment]
您可能需要学习 JSON Object 语法。

**Comment by 70599** [comment]
可以了，感谢指点
