### ISSUE TITLE
beta7的utls fingerprint问题反馈

### ISSUE THREAD

**Issue by zcluo** [SagerNet/sing-box#416]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

客户端用的sing-box_1.2-beta7，服务端用的nginx tls + v2ray vmess ws。配置了utls fingerprint后就无法连接到服务端在nginx报错。去掉指纹后其他配置不变连接正常

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```
sing-box version 1.2-beta7

Environment: go1.19.7 linux/amd64
Tags: with_acme,with_clash_api,with_ech,with_grpc,with_gvisor,with_lwip,with_quic,with_reality_server,with_shadowsocksr,with_utls,with_v2ray_api,with_wireguard
CGO: enabled
</details>

### Server and client configuration file

<details>

```console
# paste json here
```
client config:
{
	"log": {
		"disabled": false,
		"level": "warn",
		"output": "/var/run/homeproxy/sing-box.log",
		"timestamp": true
	},
	"dns": {
		"servers": [
			{
				"tag": "default-dns",
				"address": "114.114.114.114",
				"detour": "direct-out"
			},
			{
				"tag": "block-dns",
				"address": "rcode://name_error"
			},
			{
				"tag": "main-dns",
				"address": "tcp://1.1.1.1",
				"strategy": "ipv4_only",
				"detour": "main-out"
			}
		],
		"rules": [
			{
				"domain": "mysite.com",
				"server": "default-dns"
			},
			{
				"domain_keyword": [
					"services.googleapis.cn",
					"xn--ngstr-lra8j.com"
				],
				"server": "default-dns"
			}
		],
		"disable_cache": false,
		"disable_expire": false,
		"final": "main-dns"
	},
	"inbounds": [
		{
			"type": "direct",
			"tag": "dns-in",
			"listen": "::",
			"listen_port": 5333
		},
		{
			"type": "redirect",
			"tag": "redirect-in",
			"listen": "::",
			"listen_port": 5331,
			"sniff": true,
			"sniff_override_destination": true
		},
		{
			"type": "tproxy",
			"tag": "tproxy-in",
			"listen": "::",
			"listen_port": 5332,
			"network": "udp",
			"sniff": true,
			"sniff_override_destination": true
		}
	],
	"outbounds": [
		{
			"type": "direct",
			"tag": "direct-out",
			"routing_mark": 100
		},
		{
			"type": "block",
			"tag": "block-out"
		},
		{
			"type": "dns",
			"tag": "dns-out"
		},
		{
			"type": "vmess",
			"tag": "main-out",
			"routing_mark": 100,
			"server": "mysite.com",
			"server_port": 1234,
			"uuid": "myuuid",
			"security": "none",
			"global_padding": false,
			"authenticated_length": false,
			"packet_encoding": "xudp",
			"tls": {
				"enabled": true,
				"server_name": "mysite.com",
				"insecure": false,
				"utls": {
					"enabled": true,
					"fingerprint": "chrome"
				}
			},
			"transport": {
				"type": "ws",
				"path": "/home"
			},
			"udp_fragment": true
		}
	],
	"route": {
		"geoip": {
			"path": "/etc/homeproxy/resources/geoip.db",
			"download_url": "https://github.com/1715173329/sing-geoip/releases/latest/download/geoip.db",
			"download_detour": "main-out"
		},
		"geosite": {
			"path": "/etc/homeproxy/resources/geosite.db",
			"download_url": "https://github.com/1715173329/sing-geosite/releases/latest/download/geosite.db",
			"download_detour": "main-out"
		},
		"rules": [
			{
				"inbound": "dns-in",
				"outbound": "dns-out"
			},
			{
				"protocol": "dns",
				"outbound": "dns-out"
			},
			{
				"source_ip_cidr": [
					"10.0.0.100"
				],
				"outbound": "main-out"
			},
			{
				"ip_cidr": [
					"91.108.4.0/22",
					"91.108.8.0/22",
					"91.108.12.0/22",
					"91.108.56.0/22",
					"95.161.64.0/20",
					"149.154.160.0/22",
					"149.154.164.0/22",
					"149.154.172.0/22"
				],
				"outbound": "main-out"
			},
			{
				"domain_keyword": [
					"services.googleapis.cn",
					"xn--ngstr-lra8j.com"
				],
				"outbound": "direct-out"
			},
			{
				"geosite": [
					"cn"
				],
				"geoip": [
					"cn"
				],
				"outbound": "direct-out"
			}
		],
		"auto_detect_interface": true,
		"final": "main-out"
	}
}

</details>

### Server and client log file

<details>

```console
# paste log here
```
nginx server error log:
invalid connection preface while processing HTTP/2 connection, client: xx.xxx.xx.xxx,, server: 0.0.0.0:5017
client sing-box error:
+0000 2023-03-09 09:44:03 ERROR [2071545977] inbound/redirect[redirect-in]: process connection from 10.0.0.158:38668: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x80\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\x7f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"
+0000 2023-03-09 09:44:03 ERROR [2261403655] inbound/redirect[redirect-in]: process connection from 10.0.0.158:43834: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x80\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\x7f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"
</details>

**Comment by nekohasekai** [comment]
WebSocket 不兼容与 uTLS 和 nginx 前置一起使用。

**Comment by zcluo** [comment]
> WebSocket 不兼容与 uTLS 和 nginx 前置一起使用。

我昨天调整成nginx。前面用caddy2也不行。但是我用的clash.meta和v2rayng手机客户端是可以的。

**Comment by nekohasekai** [comment]
他们会有明显的指纹。
