### ISSUE TITLE
[Feature Request] 支持 gPRC / H2 健康检查

### ISSUE THREAD

**Issue by 1715173329** [SagerNet/sing-box#420]
请求为 gPRC / H2 传输层添加健康检查支持。

ref:
https://xtls.github.io/config/transports/grpc.html#grpcobject
https://xtls.github.io/config/transports/h2.html#httpobject

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/6af9c2b3ca16fa3d6a2c3de592ca0fb320f12582

**Comment by 1715173329** [comment]
测试 OK，辛苦了~
