### ISSUE TITLE
[Feature (Request)] JSON Schema support for the config file

### ISSUE THREAD

**Issue by artiga033** [SagerNet/sing-box#425]
Hello, I've written a [json-schema for the config file of sing-box](https://gist.github.com/artiga033/fea992d95ad44dc8d024b229223b1002), and it works like this in vscode:
![sing-box-json-schema](https://user-images.githubusercontent.com/16872488/224553864-ce1b5742-2e0b-4ae0-9a73-843930614416.gif)

However, if I try to run the program with the config(which has an extra "$schema" field), there would be some thing wrong.
```
FATAL[0000] decode config: json: unknown field "$schema"
```
I'm not actually farmilar with Golang's json serialization, but I think there's a way to ignore this extra field in the config file. Thus the schema would make a better experience.

By the way I wonder if you'd like to have this schema file merged or refered to in the document :D, though it's not fully tested yet.

**Comment by bjxdqs** [comment]
There is a simple solution: commet it(//  $schema) and delete ','

**Comment by nekohasekai** [comment]
7d22cf9b45d6de0c068b4b0c5b5bf6c9f037c7e3

**Comment by nekohasekai** [comment]
LGTM. I may refer to this file and provide an official schema in the future.

**Comment by g0ne150** [comment]
Hi, is there any official schema has been provided for now?

**Comment by fbigun** [comment]
看来还是没有配置示例可以看

**Comment by Guanran928** [comment]
Not stale, please re-open.

**Comment by dh2004** [comment]
> LGTM。将来我可能会参考此文件并提供官方模式。

世界大佬,快做个官方config模版,小白东抄一下,西抄一下太痛苦啦.
