### ISSUE TITLE
mac 设置系统代理错误 set system proxy: exit status 4

### ISSUE THREAD

**Issue by izhangxm** [SagerNet/sing-box#426]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

入站就一个监听，不论是最新版的1.2beta7或稳定版1.1.6 都有这个问题，加了sudo也不行
```
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "listen_port": 1081,
      "set_system_proxy": true,
      "sniff": true,
      "tag": "mixed-in",
      "type": "mixed"
    }
  ],
```
<img width="676" alt="image" src="https://user-images.githubusercontent.com/16874796/224562698-111f083b-a350-4de8-960a-ae6a56ee3990.png">

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
sing-box version 1.2-beta7

Environment: go1.19.6 darwin/arm64
Tags: with_quic,with_grpc,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_v2ray_api,with_gvisor
CGO: enabled

```

</details>

### Server and client configuration file

<details>

```console
# paste json here
 "inbounds": [
    {
      "listen": "127.0.0.1",
      "listen_port": 1081,
      "set_system_proxy": true,
      "sniff": true,
      "tag": "mixed-in",
      "type": "mixed"
    }
  ]
```

</details>

### Server and client log file

<details>

```console
# paste log here
```
INFO[0000] clash-api: restful api listening at 127.0.0.1:9090
INFO[0000] router: loaded geoip database: 250 codes
INFO[0000] router: loaded geosite database: 1374 codes
INFO[0000] router: updated default interface en5, index 7
INFO[0000] inbound/mixed[mixed-in]: tcp server started at 127.0.0.1:1081
** Error: The parameters were not valid.
FATAL[0000] start service: initialize inbound/mixed[mixed-in]: set system proxy: exit status 4
</details>

**Comment by nekohasekai** [comment]
请问您的设备型号与 macOS 版本。

**Comment by nekohasekai** [comment]
请尝试使用 39d8c7bd24b1d2dea7c8adee7085dda73c891b46 运行以显示出错的命令内容。

**Comment by nekohasekai** [comment]
是的，您也可以使用 go install 带有 @commit

**Comment by jyogyou** [comment]
mac用哪个版本的sing-box啊，我看下载里面linux win的都有就是没看到mac的版本
