### ISSUE TITLE
Feature request: Reverse proxy

### ISSUE THREAD

**Issue by mazzz1y** [SagerNet/sing-box#43]
Is this feature planned to add?

https://www.v2ray.com/en/configuration/reverse.html

This is a very useful thing for connecting to devices behind nat

Thank you

**Comment by muziling** [comment]
有计划吗？

**Comment by starmoon-1134** [comment]
期待大佬能支持这个功能

**Comment by Weltolk** [comment]
need

**Comment by e3lz** [comment]
really need this future , please add
