### ISSUE TITLE
WebSocket 协议对于 SNI 的支持似乎存在问题

### ISSUE THREAD

**Issue by Xeath** [SagerNet/sing-box#442]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

服务端是 Xray 未配置 TLS，通过 Nginx 反代部署 TLS。
当 `server` 为 IP 地址的时候，就会出现一个奇怪的问题，无论 sing-box 怎么配置 `server_name` 都是无法发送正确的 ServerName，导致 Nginx 发回了错误的证书。
简单研究一下，问题可能出在 [transport/v2raywebsocket/client.go](https://github.com/SagerNet/sing-box/blob/a8fcadab2554ad3c3ce390eddaa0bf96bbd8b13e/transport/v2raywebsocket/client.go) 或者 [gorilla/websocket](https://github.com/gorilla/websocket)。
当我尝试把 `uri.Host = serverAddr.String()` 修改为 `uri.Host = tlsConfig.Server()` 虽然也能链接，但是并不符合我预期的设置。尝试了删除 [`wsDialer.NetDialTLSContext`](https://github.com/SagerNet/sing-box/blob/a8fcadab2554ad3c3ce390eddaa0bf96bbd8b13e/transport/v2raywebsocket/client.go#L40) 并改用 `wsDialer.TLSClientConfig` 依旧返回了错误的证书。

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.2-beta8

Environment: go1.20.1 darwin/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: 775c44b0f902d7814314393ea7812ebe712058df
CGO: disabled
```

</details>

### Server and client configuration file

<details>

Client configuration file:

```console
{
    "log": {
        "disabled": false,
        "level": "debug"
    },
    "dns": {},
    "inbounds": [
        {
            "type": "socks",
            "tag": "socks-in",
            "listen": "127.0.0.1",
            "listen_port": 3081
        }
    ],
    "outbounds": [
        {
            "type": "vless",
            "tag": "vless-out",
            "server": "8.8.8.8",
            "server_port": 443,
            "uuid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx",
            "network": "tcp",
            "tls": {
                "enabled": true,
                "disable_sni": false,
                "server_name": "123.com",
                "certificate_path": "ca-lets-encrypt.crt"
            },
            "transport": {
                "type": "ws",
                "path": "/xray",
                "headers": {
                    "Host": "123.com"
                }
            }
        }
    ],
    "route": {},
    "experimental": {}
}
```

Server configuration file:
[Xray-examples: VLESS-WSS-Nginx](https://github.com/XTLS/Xray-examples/tree/main/VLESS-WSS-Nginx)

</details>

### Server and client log file

<details>

```console
INFO[0000] router: using vless[vless-out] as default outbound for connection
INFO[0000] router: using direct[default] as default outbound for packet connection
INFO[0000] inbound/socks[socks-in]: tcp server started at 127.0.0.1:3081
INFO[0000] sing-box started (0.00s)
INFO[0003] [846755615] inbound/socks[socks-in]: inbound connection from 127.0.0.1:61117
INFO[0003] [846755615] inbound/socks[socks-in]: inbound connection to [2606:4700:20::681a:d1f]:80
ERROR[0003] [846755615] inbound/socks[socks-in]: process connection from 127.0.0.1:61117: tls: failed to verify certificate: x509: certificate is valid for abc.com, not 123.com
```

</details>

**Comment by nekohasekai** [comment]
请提供完整的服务器端日志和配置文件。请不要假定客户端发送了错误的服务器名称指示，从日志来看不是这样的。

**Comment by Xeath** [comment]
> 请提供完整的服务器端日志和配置文件。请不要假定客户端发送了错误的服务器名称指示，从日志来看不是这样的。

误会了，原来只是 Nginx 没有监听 `[::]:443` 导致🤣
