### ISSUE TITLE
所有经过type为direct的outbound出站的ICMP Echo 报文都会收到ICMP Reply响应报文

### ISSUE THREAD

**Issue by hvvvvvvv** [SagerNet/sing-box#443]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

不管是实际可达还是不可达的ip地址，只要是经direct出站的，使用ping命令都会得到响应。
如果配置文件如下这样，那么ping任何ip地址都会响应，根据ms值看，应该是被sing-box劫持响应的，不知道是程序本身的bug还是配置有不合理的地方，如果是后者，就请教下需要更改哪项配置才能避免这个问题。
![屏幕截图 2023-03-16 214232](https://user-images.githubusercontent.com/64669899/225635753-6807606c-27a6-43df-9a04-5b063ea3d3e4.png)

### Version of sing-box

<details>
1.1.6
</details>

### Server and client configuration file

{
  "log": {
    "disabled": false,
    "level": "debug",
    "output": "test.log",
    
    "timestamp": true
  }
 ,
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "interface_name": "singbox_tun",
      "inet4_address": "172.19.0.1/30",

      "mtu": 9000,
      "auto_route": true,
      "strict_route": false,
      "stack": "gvisor",
      "endpoint_independent_nat": true,
      "sniff": true
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    }
  ],
  "route": {
    "auto_detect_interface": true,
    "final": "direct"
  }
}

### Server and client log file

[test.log](https://github.com/SagerNet/sing-box/files/10991535/test.log)

**Comment by sixleaves** [comment]
我再为ping不通烦扰，你ping通烦恼啥。
