### ISSUE TITLE
support proxy providers

### ISSUE THREAD

**Issue by Ehco1996** [SagerNet/sing-box#449]
I started a discussion last week related to this issue, but for some reason that issue disappeared.
So I am starting a new one to discuss the support for `proxy-provider` with everyone.
If we can come up with a standard configuration file format, I can submit a pull request and work on it.

Looking forward to your guys reply thanks

**Comment by nekohasekai** [comment]
There is no such thing as a proxy in sing-box, please fork if you want to make a clash alternative.

**Comment by chenzhiguo** [comment]
Regarding this requirement, are there any taboos that developers do not want to mention? I searched several similar issues and they were all closed without allowing comments.
