### ISSUE TITLE
以 sing-box 两次中转流量至落地端的 DIRECT 出站，会出现错误

### ISSUE THREAD

**Issue by UptonEdward** [SagerNet/sing-box#452]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

**我的使用场景**（因为需要复杂的分流，才会有这种看起来奇怪的配置）：
在 Mac 上的 sing-box 客户端使用 VLESS + Reality + Vision 与服务器 A 的 sing-box 中转端通信，同时服务器 A 上的 sing-box 中转端使用 Shadowsocks2022 与服务器 B 上面的 sing-box 落地端通信。落地端 B 的唯一出站是 WireGuard，从而形成了一个完整的代理链。

**问题**：
今晚测试时发现，如果将服务器 B 的唯一出站设置为 DIRECT，则会导致部分连接出现错误。
但是，如果去掉代理链中的服务器 B，直接使用服务器 A 的 DIRECT 出站作为落地，则不会出现这个问题。

### Version of sing-box

<details>

所有 sing-box 二进制文件均使用 dev-next 分支最新版本 [99b2ab5](https://github.com/SagerNet/sing-box/commit/99b2ab5526fb9cde7daba9cfd5802f8043d78e38) 进行编译。

Mac：
```console
$ sing-box version unknown

Environment: go1.20.2 darwin/amd64
Tags: with_quic,with_utls,with_gvisor,with_reality_server
CGO: enabled
```

服务器 A：
```console
$ sing-box version
sing-box version unknown

Environment: go1.20.2 linux/amd64
Tags: with_reality_server,with_quic,with_wireguard,with_utls,with_gvisor
Revision: 99b2ab5526fb9cde7daba9cfd5802f8043d78e38
CGO: disabled
```

服务器 B：
```console
$ sing-box version
sing-box version unknown

Environment: go1.20.2 linux/amd64
Tags: with_reality_server,with_quic,with_wireguard,with_utls,with_gvisor
Revision: 99b2ab5526fb9cde7daba9cfd5802f8043d78e38
CGO: disabled
```
</details>

### Server and client configuration file

以下为最简配置，可用于复现问题。
<details>

Mac：

```console
{
  "log": {
    "level": "trace",
    "output": "~/sing-box/sing-box.log",
    "timestamp": true
  },
  "route": {
    "rules": [
      {
        "inbound": "test-in",
        "outbound": "a-out"
      }
    ]
  },
  "inbounds": [
    {
      "type": "socks",
      "tag": "test-in",
      "listen": "127.0.0.1",
      "listen_port": 50001,
      "tcp_fast_open": true
    }
  ],
  "outbounds": [
    {
      "type": "vless",
      "tag": "a-out",
      "server": "vps_a_ip",
      "server_port": 444,
      "tcp_fast_open": true,
      "uuid": "uuid",
      "flow": "xtls-rprx-vision",
      "tls": {
        "enabled": true,
        "server_name": "s0.awsstatic.com",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "pubkey",
          "short_id": "id"
        }
      }
    }
  ]
}
```
服务器 A：

```console

{
  "log": {
    "level": "trace",
    "output": "/root/sing-box.log",
    "timestamp": true
  },
  "route": {
    "final": "b-out",
    "rules": [
      {
        "inbound": "mac-in",
        "outbound": "b-out"
      }
    ]
  },
  "inbounds": [
    {
      "type": "vless",
      "tag": "mac-in",
      "listen": "0.0.0.0",
      "sniff": true,
      "listen_port": 444,
      "tcp_fast_open": true,
      "users": [
        {
          "name": "MyMac",
          "uuid": "uuid",
          "flow": "xtls-rprx-vision"
        }
      ],
      "tls": {
        "enabled": true,
        "server_name": "s0.awsstatic.com",
        "reality": {
          "enabled": true,
          "handshake": {
            "server": "s0.awsstatic.com",
            "server_port": 443
          },
          "private_key": "pubkey",
          "short_id": "id"
        }
      }
    }
  ],
  "outbounds": [
    {
      "type": "shadowsocks",
      "tag": "b-out",
      "server": "vps_b_ip",
      "server_port": 52048,
      "method": "2022-blake3-aes-256-gcm",
      "password": "password",
      "tcp_fast_open": true
    }
  ]
}
```
服务器 B：

```console

{
  "log": {
    "level": "trace",
    "output": "/root/sing-box.log",
    "timestamp": true
  },
  "inbounds": [
    {
      "type": "shadowsocks",
      "tag": "a-in",
      "listen": "0.0.0.0",
      "listen_port": 52048,
      "sniff": true,
      "tcp_fast_open": true,
      "method": "2022-blake3-aes-256-gcm",
      "password": "password"
    }
  ]
}
```
</details>

### Server and client log file

<details>

Mac：

```console
+0800 2023-03-18 21:22:45 INFO inbound/socks[test-in]: tcp server started at 127.0.0.1:50001
+0800 2023-03-18 21:22:45 INFO sing-box started (0.00s)
+0800 2023-03-18 21:22:46 INFO [505908455] inbound/socks[test-in]: inbound connection from 127.0.0.1:62973
+0800 2023-03-18 21:22:46 INFO [505908455] inbound/socks[test-in]: inbound connection to speed.cloudflare.com:443
+0800 2023-03-18 21:22:46 DEBUG [505908455] router: match[0] inbound=test-in => a-out
+0800 2023-03-18 21:22:46 INFO [505908455] outbound/vless[a-out]: outbound connection to speed.cloudflare.com:443
+0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: XtlsFilterTls found tls client hello! 414
+0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: XtlsPadding 414 668 0
+0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: Xtls Unpadding new block 21 2647 padding 176 0
+0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: XtlsFilterTls found tls 1.3! 2351 4866 true
+0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: XtlsPadding 80 1200 0
+0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: XtlsPadding 184 875 2
+0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: XtlsWrite writeV 0 0 0
+0800 2023-03-18 21:22:46 DEBUG [505908455] inbound/socks[test-in]: connection closed: process connection from 127.0.0.1:62973: download: EOF | upload: EOF
+0800 2023-03-18 21:22:47 INFO [1736569712] inbound/socks[test-in]: inbound connection from 127.0.0.1:62976
+0800 2023-03-18 21:22:47 INFO [1736569712] inbound/socks[test-in]: inbound connection to speed.cloudflare.com:443
+0800 2023-03-18 21:22:47 DEBUG [1736569712] router: match[0] inbound=test-in => a-out
+0800 2023-03-18 21:22:47 ERROR [1736569712] inbound/socks[test-in]: process connection from 127.0.0.1:62976: connectx: connection refused
```
服务器 A：

```console
+0800 2023-03-18 21:22:41 INFO inbound/vless[mac-in]: tcp server started at 0.0.0.0:444
+0800 2023-03-18 21:22:41 INFO sing-box started (0.00s)
+0800 2023-03-18 21:22:46 INFO [3314033174] inbound/vless[mac-in]: inbound connection from mac_ip:4294
+0800 2023-03-18 21:22:46 DEBUG [3314033174] dns: lookup domain s0.awsstatic.com
+0800 2023-03-18 21:22:46 DEBUG [3314033174] dns: lookup succeed for s0.awsstatic.com: 13.225.89.202
+0800 2023-03-18 21:22:46 INFO [2740691262] inbound/vless[mac-in]: [MyMac] inbound connection to speed.cloudflare.com:443
+0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: Xtls Unpadding new block 21 414 padding 668 0
+0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: XtlsFilterTls found tls client hello! 414
+0800 2023-03-18 21:22:46 DEBUG [2740691262] router: sniffed protocol: tls, domain: speed.cloudflare.com
+0800 2023-03-18 21:22:46 DEBUG [2740691262] router: match[0] inbound=mac-in => b-out
+0800 2023-03-18 21:22:46 INFO [2740691262] outbound/shadowsocks[b-out]: outbound connection to speed.cloudflare.com:443
+0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: XtlsFilterTls found tls 1.3! 2647 4866 true
+0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: XtlsPadding 2647 176 0
+0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: Xtls Unpadding new block 5 80 padding 1200 0
+0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: Xtls Unpadding new block 5 184 padding 875 2
+0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: XtlsRead readV
+0800 2023-03-18 21:22:56 INFO inbound/vless[mac-in]: tcp server started at 0.0.0.0:444
+0800 2023-03-18 21:22:56 INFO sing-box started (0.00s)
```
服务器 B：

```console
+0800 2023-03-18 21:22:40 INFO inbound/shadowsocks[a-in]: tcp server started at 0.0.0.0:52048
+0800 2023-03-18 21:22:40 INFO inbound/shadowsocks[a-in]: udp server started at 0.0.0.0:52048
+0800 2023-03-18 21:22:40 INFO sing-box started (0.00s)
+0800 2023-03-18 21:22:46 INFO [2422815126] inbound/shadowsocks[a-in]: inbound connection from vps_a_ip:36910
+0800 2023-03-18 21:22:46 INFO [3648145625] inbound/shadowsocks[a-in]: inbound connection to speed.cloudflare.com:443
+0800 2023-03-18 21:22:46 DEBUG [3648145625] router: sniffed protocol: tls, domain: speed.cloudflare.com
+0800 2023-03-18 21:22:46 INFO [3648145625] outbound/direct: outbound connection to speed.cloudflare.com:443
+0800 2023-03-18 21:22:46 DEBUG [3648145625] dns: lookup domain speed.cloudflare.com
+0800 2023-03-18 21:22:46 DEBUG [3648145625] dns: lookup succeed for speed.cloudflare.com: 2606:4700::6810:4326 2606:4700::6810:4426 104.16.68.38 104.16.67.38
+0800 2023-03-18 21:22:46 DEBUG [2422815126] inbound/shadowsocks[a-in]: connection closed: process connection from 199.15.77.236:36910: shadowsocks: serve TCP from 199.15.77.236:36910: upload: EOF | download: write tcp4 103.178.54.62:52048->199.15.77.236:36910: write: connection reset by peer
```

</details>

**Comment by z3473** [comment]
> ### Welcome
> * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> * [x]  Yes, I'm using the latest Golang release. Only such installations are supported.
> * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> * [x]  Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).
> 
> ### Description of the problem
> **我的使用场景**（因为需要复杂的分流，才会有这种看起来奇怪的配置）： 在 Mac 上的 sing-box 客户端使用 VLESS + Reality + Vision 与服务器 A 的 sing-box 中转端通信，同时服务器 A 上的 sing-box 中转端使用 Shadowsocks2022 与服务器 B 上面的 sing-box 落地端通信。落地端 B 的唯一出站是 WireGuard，从而形成了一个完整的代理链。
> 
> **问题**： 今晚测试时发现，如果将服务器 B 的唯一出站设置为 DIRECT，则会导致部分连接出现错误。 但是，如果去掉代理链中的服务器 B，直接使用服务器 A 的 DIRECT 出站作为落地，则不会出现这个问题。
> 
> ### Version of sing-box
> ### Server and client configuration file
> 以下为最简配置，可用于复现问题。
> 
> Mac：
> 
> ```
> {
>   "log": {
>     "level": "trace",
>     "output": "~/sing-box/sing-box.log",
>     "timestamp": true
>   },
>   "route": {
>     "rules": [
>       {
>         "inbound": "test-in",
>         "outbound": "a-out"
>       }
>     ]
>   },
>   "inbounds": [
>     {
>       "type": "socks",
>       "tag": "test-in",
>       "listen": "127.0.0.1",
>       "listen_port": 50001,
>       "tcp_fast_open": true
>     }
>   ],
>   "outbounds": [
>     {
>       "type": "vless",
>       "tag": "a-out",
>       "server": "vps_a_ip",
>       "server_port": 444,
>       "tcp_fast_open": true,
>       "uuid": "uuid",
>       "flow": "xtls-rprx-vision",
>       "tls": {
>         "enabled": true,
>         "server_name": "s0.awsstatic.com",
>         "utls": {
>           "enabled": true,
>           "fingerprint": "chrome"
>         },
>         "reality": {
>           "enabled": true,
>           "public_key": "pubkey",
>           "short_id": "id"
>         }
>       }
>     }
>   ]
> }
> ```
> 
> 服务器 A：
> 
> ```
> {
>   "log": {
>     "level": "trace",
>     "output": "/root/sing-box.log",
>     "timestamp": true
>   },
>   "route": {
>     "final": "b-out",
>     "rules": [
>       {
>         "inbound": "mac-in",
>         "outbound": "b-out"
>       }
>     ]
>   },
>   "inbounds": [
>     {
>       "type": "vless",
>       "tag": "mac-in",
>       "listen": "0.0.0.0",
>       "sniff": true,
>       "listen_port": 444,
>       "tcp_fast_open": true,
>       "users": [
>         {
>           "name": "MyMac",
>           "uuid": "uuid",
>           "flow": "xtls-rprx-vision"
>         }
>       ],
>       "tls": {
>         "enabled": true,
>         "server_name": "s0.awsstatic.com",
>         "reality": {
>           "enabled": true,
>           "handshake": {
>             "server": "s0.awsstatic.com",
>             "server_port": 443
>           },
>           "private_key": "pubkey",
>           "short_id": "id"
>         }
>       }
>     }
>   ],
>   "outbounds": [
>     {
>       "type": "shadowsocks",
>       "tag": "b-out",
>       "server": "vps_b_ip",
>       "server_port": 52048,
>       "method": "2022-blake3-aes-256-gcm",
>       "password": "password",
>       "tcp_fast_open": true
>     }
>   ]
> }
> ```
> 
> 服务器 B：
> 
> ```
> {
>   "log": {
>     "level": "trace",
>     "output": "/root/sing-box.log",
>     "timestamp": true
>   },
>   "inbounds": [
>     {
>       "type": "shadowsocks",
>       "tag": "a-in",
>       "listen": "0.0.0.0",
>       "listen_port": 52048,
>       "sniff": true,
>       "tcp_fast_open": true,
>       "method": "2022-blake3-aes-256-gcm",
>       "password": "password"
>     }
>   ]
> }
> ```
> 
> ### Server and client log file
> Mac：
> 
> ```
> +0800 2023-03-18 21:22:45 INFO inbound/socks[test-in]: tcp server started at 127.0.0.1:50001
> +0800 2023-03-18 21:22:45 INFO sing-box started (0.00s)
> +0800 2023-03-18 21:22:46 INFO [505908455] inbound/socks[test-in]: inbound connection from 127.0.0.1:62973
> +0800 2023-03-18 21:22:46 INFO [505908455] inbound/socks[test-in]: inbound connection to speed.cloudflare.com:443
> +0800 2023-03-18 21:22:46 DEBUG [505908455] router: match[0] inbound=test-in => a-out
> +0800 2023-03-18 21:22:46 INFO [505908455] outbound/vless[a-out]: outbound connection to speed.cloudflare.com:443
> +0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: XtlsFilterTls found tls client hello! 414
> +0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: XtlsPadding 414 668 0
> +0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: Xtls Unpadding new block 21 2647 padding 176 0
> +0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: XtlsFilterTls found tls 1.3! 2351 4866 true
> +0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: XtlsPadding 80 1200 0
> +0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: XtlsPadding 184 875 2
> +0800 2023-03-18 21:22:46 TRACE outbound/vless[a-out]: XtlsWrite writeV 0 0 0
> +0800 2023-03-18 21:22:46 DEBUG [505908455] inbound/socks[test-in]: connection closed: process connection from 127.0.0.1:62973: download: EOF | upload: EOF
> +0800 2023-03-18 21:22:47 INFO [1736569712] inbound/socks[test-in]: inbound connection from 127.0.0.1:62976
> +0800 2023-03-18 21:22:47 INFO [1736569712] inbound/socks[test-in]: inbound connection to speed.cloudflare.com:443
> +0800 2023-03-18 21:22:47 DEBUG [1736569712] router: match[0] inbound=test-in => a-out
> +0800 2023-03-18 21:22:47 ERROR [1736569712] inbound/socks[test-in]: process connection from 127.0.0.1:62976: connectx: connection refused
> ```
> 
> 服务器 A：
> 
> ```
> +0800 2023-03-18 21:22:41 INFO inbound/vless[mac-in]: tcp server started at 0.0.0.0:444
> +0800 2023-03-18 21:22:41 INFO sing-box started (0.00s)
> +0800 2023-03-18 21:22:46 INFO [3314033174] inbound/vless[mac-in]: inbound connection from mac_ip:4294
> +0800 2023-03-18 21:22:46 DEBUG [3314033174] dns: lookup domain s0.awsstatic.com
> +0800 2023-03-18 21:22:46 DEBUG [3314033174] dns: lookup succeed for s0.awsstatic.com: 13.225.89.202
> +0800 2023-03-18 21:22:46 INFO [2740691262] inbound/vless[mac-in]: [MyMac] inbound connection to speed.cloudflare.com:443
> +0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: Xtls Unpadding new block 21 414 padding 668 0
> +0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: XtlsFilterTls found tls client hello! 414
> +0800 2023-03-18 21:22:46 DEBUG [2740691262] router: sniffed protocol: tls, domain: speed.cloudflare.com
> +0800 2023-03-18 21:22:46 DEBUG [2740691262] router: match[0] inbound=mac-in => b-out
> +0800 2023-03-18 21:22:46 INFO [2740691262] outbound/shadowsocks[b-out]: outbound connection to speed.cloudflare.com:443
> +0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: XtlsFilterTls found tls 1.3! 2647 4866 true
> +0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: XtlsPadding 2647 176 0
> +0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: Xtls Unpadding new block 5 80 padding 1200 0
> +0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: Xtls Unpadding new block 5 184 padding 875 2
> +0800 2023-03-18 21:22:46 TRACE inbound/vless[mac-in]: XtlsRead readV
> +0800 2023-03-18 21:22:56 INFO inbound/vless[mac-in]: tcp server started at 0.0.0.0:444
> +0800 2023-03-18 21:22:56 INFO sing-box started (0.00s)
> ```
> 
> 服务器 B：
> 
> ```
> +0800 2023-03-18 21:22:40 INFO inbound/shadowsocks[a-in]: tcp server started at 0.0.0.0:52048
> +0800 2023-03-18 21:22:40 INFO inbound/shadowsocks[a-in]: udp server started at 0.0.0.0:52048
> +0800 2023-03-18 21:22:40 INFO sing-box started (0.00s)
> +0800 2023-03-18 21:22:46 INFO [2422815126] inbound/shadowsocks[a-in]: inbound connection from vps_a_ip:36910
> +0800 2023-03-18 21:22:46 INFO [3648145625] inbound/shadowsocks[a-in]: inbound connection to speed.cloudflare.com:443
> +0800 2023-03-18 21:22:46 DEBUG [3648145625] router: sniffed protocol: tls, domain: speed.cloudflare.com
> +0800 2023-03-18 21:22:46 INFO [3648145625] outbound/direct: outbound connection to speed.cloudflare.com:443
> +0800 2023-03-18 21:22:46 DEBUG [3648145625] dns: lookup domain speed.cloudflare.com
> +0800 2023-03-18 21:22:46 DEBUG [3648145625] dns: lookup succeed for speed.cloudflare.com: 2606:4700::6810:4326 2606:4700::6810:4426 104.16.68.38 104.16.67.38
> +0800 2023-03-18 21:22:46 DEBUG [2422815126] inbound/shadowsocks[a-in]: connection closed: process connection from 199.15.77.236:36910: shadowsocks: serve TCP from 199.15.77.236:36910: upload: EOF | download: write tcp4 103.178.54.62:52048->199.15.77.236:36910: write: connection reset by peer
> ```

配置中转也遇到问题了，B节点能看netflix，用A中转配置如下：
{
    "log": {
        "disabled": false,
        "level": "info",
        "output": "/usr/local/sing-box/sing-box.log",
        "timestamp": true
    },
    "inbounds": [
        {
            "type": "naive",
            "tag": "naive-in",
            "network": "tcp",
            "listen": "0.0.0.0",
            "listen_port": 52903,
            "sniff": true,
            "sniff_override_destination": false,
            "proxy_protocol": false,
            "proxy_protocol_accept_no_header": false,
	    "users": [
	      {
		"username": "zhangsan",
		"password": "lisi"
	      }
        
    ],
    "tls": {
        "enabled": true,
        "server_name": "zhangsan.shop",
        "acme": {
          "domain": ["zhangsan.shop"],
          "data_directory": "/usr/local/etc/sing-box",
          "default_server_name": "",
          "email": "zhangsan@gmail.com",
          "provider": "letsencrypt"
        }
      }
    }
  ],
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "shadowsocks",
            "tag": "Unlock-netflix",
            "server": "vpsB",
            "server_port": 58013,
            "method": "2022-blake3-aes-128-gcm",
            "password": "passwd",
            "network": "tcp"
        }
    ],
    "route": {
        "rules": [
            {
                "geosite": "category-ads-all",
                "outbound": "block"
            },
            {
                "geosite": "cn",
                "geoip": "cn",
                "outbound": "block"
            },
	    {   "geosite": "netflix",
	        "domain_keyword": "ip.sb",
		"outbound": "Unlock-netflix"
	    }
        ],
        "geoip": {
            "path": "geoip.db",
            "download_url": "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db",
            "download_detour": "direct"
        },
        "geosite": {
            "path": "geosite.db",
            "download_url": "https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db",
            "download_detour": "direct"
        },
        "auto_detect_interface": true
    }
}

**Comment by nekohasekai** [comment]
基于安全性要求，shadowsocks2022 可能无法处理被代理的 TCP 请求。

**Comment by univerioiln233** [comment]
能否模仿sock5h？出站sock5h，入站sock5
