### ISSUE TITLE
Tun with ShadowTLS mode produces lots of ERROR messages in log file

### ISSUE THREAD

**Issue by Iamnvincible** [SagerNet/sing-box#454]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

I'm using Tun mode on Linux arm platform. When I set tun inbound's outbound to shadowsocks-shadowtls, it works fine, while there are **a lot of ERROR messages** in log file, here is an example.
```
ERROR [2621775284] inbound/tun[tun-in]: invalid argument
```
notice: server side is not sing-box, just shadowtls&shadowsocks.
If I just use mixed inbounds and shadowsocks-shadowtls outbounds mode, there's no error message,every thing works fine. Add if i use trojan outbounds for tun, it is also fine.

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
sing-box version 1.2-beta9

Environment: go1.20.1 linux/arm64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: 8a9cb086854f53a188099a8649ecdb142f49c403
CGO: disabled

```

</details>

### Server and client configuration file

<details>

```console
{
	"inbounds": [
		{
			"type": "tun",
			"tag": "tun-in",
			"inet4_address": "172.19.0.1/30",
			"auto_route": true,
			"sniff": true
		}
	],
	"outbounds": [
		{
			"type":"shadowsocks",
			"tag":"a-out",
			"method":"",
			"password":"",
			"detour":"b-out"
		},
		{
			"type":"shadowtls",
			"tag":"b-out",
			"server":"",
			"server_port":,
			"version":3,
			"password":"",
			"tls":{
				"enabled":true,
				"disable_sni":false,
				"server_name":"",
				"insecure":false,
				"alpn":[
					"h2",
					"http1.1"
				],
				"utls": {
					"enabled": true,
					"fingerprint": ""
				}
			}
		},
		{
			"type": "direct",
			"tag": "direct-out"
		}
	],
	"route": {
		"rules": [ 
			{
				"inbound": [
					"tun-in"
				],
				"outbound": "a-out"
			}
		],
		"auto_detect_interface": true
	}
}



```

</details>

### Server and client log file

<details>

```console
ERROR [709961863] inbound/tun[tun-in]: invalid argument
ERROR [3402496593] inbound/tun[tun-in]: invalid argument
ERROR [2621775284] inbound/tun[tun-in]: invalid argument

```

</details>

**Comment by er888kh** [comment]
I am also experiencing this, though the tunnel itself seems to be fine.
I will start investigating this issue. I have a hunch that this is caused by DNS hijacking but let's not rule out other causes.

**Comment by nekohasekai** [comment]
When udp_over_tcp or multiplex is not enabled, shadowsocks outbound will use native UDP, and shadowtls does not support UDP, which is why the example is not configured like this.

**Comment by nekohasekai** [comment]
This is an example where the error stack is not passed correctly, invalid arguments will be gradually replaced with human-readable errors.
