### ISSUE TITLE
direct-out启用tcp_fast_open时，svn请求断流

### ISSUE THREAD

**Issue by mejinotdove** [SagerNet/sing-box#465]
连接能建立，但是没有数据传输，移除tcp_fast_open配置后连接正常

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/dd5b0abc67b024e767aec09d4769a08cf07b72f6

**Comment by mejinotdove** [comment]
comfirm fixed, thanks!
