### ISSUE TITLE
When I was in the case of campus network, after running singbox, both campus network and tun showed no network link

### ISSUE THREAD

**Issue by zhangthree123** [SagerNet/sing-box#480]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

When I was in the case of campus network or other wifi networks, after running singbox, both campus network and tun showed no network link. I'm not sure if it's an Internet loop. 
When I turn on the hotspot on my phone, I can link it

### Version of sing-box

<details>

```console
$ sing-box version
1.1.6
win
# Paste output here
```

</details>

### Server and client configuration file

{
	"log": {
		"level": "info"
	},
	"dns": {
		"servers": [
			{
				"tag": "google",
				"address": "tcp://8.8.8.8"
			},
			{
				"tag": "local",
				"address": "223.5.5.5",
				"detour": "direct"
			},
			{
				"tag": "block",
				"address": "rcode://success"
			}
		],
		"rules": [
			{
				"domain_suffix": [
					"cjhh.beauty",
					"cjhh.mom",
					"cjhh.lol",
					"ghproxy.com",
					"inforun.work",
					"iote.bond",
					"ddll.bond",
					"iijj.sbs",
					"tuil.xyz"
				],
				"server": "local"
			},
			{
				"geosite": [
					"apple@cn",
					"google@cn",
					"microsoft@cn",
					"cn"
				],
				"server": "local"
			},
			{
				"clash_mode": "direct",
				"server": "local"
			}
		],
		"strategy": "ipv4_only"
	},
	"inbounds": [
		{
			"type": "tun",
			"tag": "tun-in",
			"mtu": 9000,
			"inet4_address": "172.19.0.1/30",
			"auto_route": true,
			"strict_route": true,
			"stack": "gvisor",
			"sniff": true,
			"domain_strategy": "ipv4_only"
		},
		{
			"type": "mixed",
			"tag": "mixed-in",
			"listen": "::",
			"listen_port": 2080,
			"set_system_proxy": false
		}
	],
	"outbounds": [
		{
			"type": "selector",
			"tag": "节点",
			"outbounds": ["US SJC D/KCD TR","US SJC R/KCD/B TR","HK HKG R/KCD/E TR","HK HKG R/KCD/C TR","TW TPE D/HiNet/01 TR","DE FRA D/CN2 TR","GB LHR R/VMH TR","TW TPE D/HiNet/02 TR","US SEA D/163 TR","HK HKG R/KCD/A TR","JP TYO D/KCD/A TR","JP TYO R/KCD/B TR","JP TYO D/CMI TR","US SJC D/CN2 TR","US SJC R/KCD/A TR","HK HKG D/CMI TR","JP TYO D/KCD TR","HK HKG R/KCD/B TR","HK HKG D/KCD TR","HK HKG D/HKT TR","HK HKG R/KCD/D TR","US SJC D/KCD V2","US SJC R/KCD/B V2","HK HKG R/KCD/E V2","HK HKG R/KCD/C V2","TW TPE D/HiNet/01 V2","DE FRA D/CN2 V2","GB LHR R/VMH V2","TW TPE D/HiNet/02 V2","US SEA D/163 V2","HK HKG R/KCD/A V2","JP TYO D/KCD/A V2","JP TYO R/KCD/B V2","JP TYO D/CMI V2","US SJC D/CN2 V2","US SJC R/KCD/A V2","HK HKG D/CMI V2","JP TYO D/KCD V2","HK HKG R/KCD/B V2","HK HKG D/KCD V2","HK HKG D/HKT V2","HK HKG R/KCD/D V2"]
		},
		{
			"type": "selector",
			"tag": "国内流量",
			"outbounds": [
				"直连",
				"节点"
			]
		},
		
}

### Server and client log file

启动 sing-box...

INFO[0000] router: loaded geoip database: 10 codes
INFO[0000] router: loaded geosite database: 1326 codes
INFO[0000] router: updated default interface WLAN, index 7
INFO[0001] inbound/tun[tun-in]: started at tun0
INFO[0001] inbound/mixed[mixed-in]: tcp server started at [::]:2080
INFO[0001] clash-api: restful api listening at [::]:9090
INFO[0001] sing-box started (1.111s)
INFO[0001] [2259476818] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:63651
INFO[0001] [2259476818] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0001] [2259476818] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0001] outbound/trojan[US SJC D/CN2 TR]: outbound connection to 8.8.8.8:53
INFO[0001] outbound/direct[direct]: outbound packet connection to 223.5.5.5:53
INFO[0001] [4279509139] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:65070
INFO[0001] [4279509139] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0001] [4279509139] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0001] [1367321078] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:137
INFO[0001] [1367321078] inbound/tun[tun-in]: inbound packet connection to 172.19.0.3:137
INFO[0001] [1367321078] router: found process path: :System
INFO[0003] [3022383403] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:63876
INFO[0003] [3022383403] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0003] [3022383403] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0007] [1673603559] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:51141
INFO[0007] [1673603559] inbound/tun[tun-in]: inbound packet connection to 106.38.231.42:2000
INFO[0007] [1673603559] router: found process path: \Device\HarddiskVolume1\software\youdao_de\Dict\YoudaoDict.exe
INFO[0007] [1673603559] outbound/direct[直连]: outbound packet connection
ERROR[0011] dns: lookup failed for jjmmk-1038-tr-2.sjc-d-cn2.jd.cjhh.lol: context deadline exceeded
INFO[0011] outbound/direct[direct]: outbound packet connection to 223.5.5.5:53
ERROR[0011] [2259476818] dns: exchange failed for sg.mjt001.com. IN A: context deadline exceeded
INFO[0011] outbound/trojan[US SJC D/CN2 TR]: outbound connection to 8.8.8.8:53
INFO[0013] [3987353150] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:65055
INFO[0013] [3987353150] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0013] [1154657802] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:52588
INFO[0013] [1154657802] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0013] [3987353150] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0013] [1154657802] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0013] [1671397303] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:58617
INFO[0013] [1671397303] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0013] [1671397303] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0013] outbound/direct[direct]: outbound packet connection to 223.5.5.5:53
ERROR[0013] [3022383403] dns: exchange failed for dict.youdao.com. IN A: context deadline exceeded
INFO[0014] outbound/direct[direct]: outbound packet connection to 223.5.5.5:53
ERROR[0014] [3022383403] dns: exchange failed for dict.youdao.com. IN A: context deadline exceeded
ERROR[0014] [3022383403] dns: exchange failed for dict.youdao.com. IN A: context canceled
ERROR[0014] [3022383403] dns: exchange failed for dict.youdao.com. IN A: context canceled
INFO[0019] [1896950856] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:59286
INFO[0019] [1896950856] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0019] [1896950856] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0020] [1064506386] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:61572
INFO[0020] [1064506386] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0020] [1064506386] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0021] [316192375] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:50749
INFO[0021] [316192375] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0021] [316192375] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
ERROR[0021] dns: lookup failed for jjmmk-1038-tr-2.sjc-d-cn2.jd.cjhh.lol: context deadline exceeded
ERROR[0021] [3022383403] dns: exchange failed for dict.youdao.com. IN A: context canceled
INFO[0021] outbound/direct[direct]: outbound packet connection to 223.5.5.5:53
ERROR[0021] [4279509139] dns: exchange failed for www.msftconnecttest.com. IN A: context deadline exceeded
INFO[0021] outbound/trojan[US SJC D/CN2 TR]: outbound connection to 8.8.8.8:53
INFO[0021] [160221192] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:50934
INFO[0021] [160221192] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0021] [160221192] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0021] [4175366752] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:58542
INFO[0021] [4175366752] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0021] [4175366752] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0021] [61241613] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:60784
INFO[0021] [61241613] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0021] [61241613] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0022] [255944953] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:61908
INFO[0022] [255944953] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0022] [255944953] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0023] [319330564] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:64225
INFO[0023] [319330564] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0023] [319330564] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0023] [4210872041] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:62732
INFO[0023] [4210872041] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0023] [4210872041] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0023] [1294010627] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:63577
INFO[0023] [1294010627] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0023] [1294010627] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0025] [2255316419] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:58279
INFO[0025] [2255316419] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0025] [2255316419] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0025] [139202513] inbound/tun[tun-in]: inbound connection from 172.19.0.1:59193
INFO[0025] [139202513] inbound/tun[tun-in]: inbound connection to 172.19.0.2:53
INFO[0025] [139202513] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
INFO[0025] [2028316019] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:59264
INFO[0025] [2028316019] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0025] [2028316019] router: found process path: \Device\HarddiskVolume6\Windows\System32\svchost.exe
ERROR[0027] dns: lookup failed for jjmmk-1038-tr-2.sjc-d-cn2.jd.cjhh.lol: context canceled
INFO[0027] outbound/direct[direct]: outbound packet connection to 223.5.5.5:53
ERROR[0027] [160221192] dns: exchange failed for sofire.bdstatic.com. IN A: context canceled
ERROR[0027] [4175366752] dns: exchange failed for eclick.baidu.com. IN A: context canceled
ERROR[0027] [1294010627] dns: exchange failed for pos.baidu.com. IN A: context canceled
ERROR[0027] [1367321078] dns: exchange failed for EEEFFDELFEEPFACNDDDJDIDICACACACA. IN NIMLOC: context canceled
ERROR[0027] [319330564] dns: exchange failed for exp-new.bdstatic.com. IN A: context canceled
ERROR[0027] [1294010627] dns: exchange failed for pos.baidu.com. IN A: context canceled
ERROR[0027] [4210872041] dns: exchange failed for kstj.baidu.com. IN A: context canceled
ERROR[0027] [4210872041] dns: exchange failed for kstj.baidu.com. IN A: context canceled
ERROR[0027] [319330564] dns: exchange failed for exp-new.bdstatic.com. IN A: context canceled
ERROR[0027] [160221192] dns: exchange failed for sofire.bdstatic.com. IN A: context canceled
ERROR[0027] [255944953] dns: exchange failed for ksv-video-publish-m3u8.cdn.bcebos.com. IN A: context canceled
ERROR[0027] [1294010627] dns: exchange failed for pos.baidu.com. IN A: context canceled
ERROR[0027] [1064506386] dns: exchange failed for dict.youdao.com. IN A: context canceled
ERROR[0027] [4210872041] dns: exchange failed for kstj.baidu.com. IN A: context canceled
ERROR[0027] [4175366752] dns: exchange failed for eclick.baidu.com. IN A: context canceled
ERROR[0027] [319330564] dns: exchange failed for exp-new.bdstatic.com. IN A: context canceled
ERROR[0027] [61241613] dns: exchange failed for hm.baidu.com. IN A: context canceled
ERROR[0027] [4175366752] dns: exchange failed for eclick.baidu.com. IN A: context canceled
ERROR[0027] [255944953] dns: exchange failed for ksv-video-publish-m3u8.cdn.bcebos.com. IN A: context canceled
ERROR[0027] [61241613] dns: exchange failed for hm.baidu.com. IN A: context canceled
ERROR[0027] [255944953] dns: exchange failed for ksv-video-publish-m3u8.cdn.bcebos.com. IN A: dial udp 223.5.5.5:53: operation was canceled
ERROR[0027] [4210872041] dns: exchange failed for kstj.baidu.com. IN A: context canceled
ERROR[0027] [61241613] dns: exchange failed for hm.baidu.com. IN A: context canceled
INFO[0027] outbound/trojan[US SJC D/CN2 TR]: outbound connection to 8.8.8.8:53
ERROR[0027] [4175366752] dns: exchange failed for eclick.baidu.com. IN A: context canceled
ERROR[0027] [255944953] dns: exchange failed for ksv-video-publish-m3u8.cdn.bcebos.com. IN A: context canceled
ERROR[0027] [319330564] dns: exchange failed for exp-new.bdstatic.com. IN A: context canceled
ERROR[0027] [1064506386] dns: exchange failed for dict.youdao.com. IN A: context

**Comment by nekohasekai** [comment]
您最好将您的配置文件中敏感信息隐藏，像服务器地址和密码。由于 github issue 会留下大量记录，我不会删除这个 issue。

在提交 bug report 前，您应该将 log.level 设为 trace。

请重新提交日志文件并描述您的校园网如何实施该认证过程。

**Comment by zhangthree123** [comment]
感谢您，当我连接校园网后，会弹出一个登录窗口，当我输入密码账号的时候就可以登录。实际上，除了手机热点可以使用外，当我连接其他WIFI后，都会出现像校园网一样的情况，都会显示“该网络无internet链接，tun无internet链接”。

**Comment by nekohasekai** [comment]
如果您的配置由第三方软件生成，请向他们报告问题。

如果如此运行可以浏览网页但系统提示 “该网络无internet链接”，请修改您的描述。

如果如此运行不能浏览网页，请将 log level 设为 trace 并重新提交日志。
