### ISSUE TITLE
[question/features requests] Format logs

### ISSUE THREAD

**Issue by malikshi** [SagerNet/sing-box#486]
hello, want to ask about format logs from different types of inbound,

Trojan
```
+0700 2023-03-30 13:07:29 INFO [1274883241] inbound/trojan[trojan-ws]: inbound connection from ipaddressclient:50248
+0700 2023-03-30 13:07:29 INFO [1274883241] inbound/trojan[trojan-ws]: [Shinobi] inbound connection to log.byteoversea.com:443
+0700 2023-03-30 13:07:29 INFO [1274883241] outbound/direct[direct]: outbound connection to log.byteoversea.com:443
``` 

vmess
```
+0700 2023-03-30 13:17:30 INFO [4176208660] inbound/vmess[vmess-ws]: [xixixi66] inbound packet connection to 142.251.85.230:443
+0700 2023-03-30 13:17:30 INFO [4176208660] outbound/block[block]: blocked packet connection to rr1---sn-npoe7nsd.googlevideo.com:443
```
inbound connection from ipaddressclient different log id
vless
```
+0700 2023-03-30 13:19:32 INFO [1193567044] inbound/vless[vless-ws]: [testlogin] inbound connection to 142.251.84.103:443
+0700 2023-03-30 13:19:32 INFO [1193567044] outbound/direct[remote0]: outbound connection to rr2---sn-npoe7ns6.googlevideo.com:443
```
inbound connection from ipaddressclient different log id

`cat /var/log/box.log | grep logid`

it's seem each of inbound has different format writing log. trojan with log id 1274883241 are complete with inbound connection from, inbound connection to, outbound connection to with same log id. but vmess and vless are different log id. is is possible to have same format like trojan?

**Comment by nekohasekai** [comment]
We currently do not output parseable logs.
