### ISSUE TITLE
TUN inbound leaks memory on Windows

### ISSUE THREAD

**Issue by dyhkwong** [SagerNet/sing-box#5]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

TUN inbound leaks memory on Windows.
[pprof001.svg](https://user-images.githubusercontent.com/50692134/182159650-a2dbafdf-35de-402e-9677-ffac472030ed.svg)
![image](https://user-images.githubusercontent.com/50692134/182160737-1849b582-3774-4947-bcab-2c9696346898.png)

### Version of sing-box

b526ab2

### Server and client configuration file

can be reproduce with a "passthrough" config

<details>

```json
{
	"log": {
		"level": "trace"
	},
	"inbounds": [
		{
			"type": "tun",
			"tag": "tun-in",
			"inet4_address": "172.19.0.1/30",
			"mtu": 1500,
			"auto_route": true,
			"endpoint_independent_nat": true,
			"sniff": true,
			"sniff_override_destination": false
		}
	],
	"outbounds": [
		{
			"type": "direct",
			"tag": "direct"
		}
	],
	"route": {
		"auto_detect_interface": true
	}
}
```

</details>

**Comment by nekohasekai** [comment]
b1c2440371ee4e75634175753507ab50e4beccc6

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/8ce263669e05c59a8753abbab45e67473b0351f5

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/5fddd3c34cee43c129e0bf28edd533de4e3f7732
