### ISSUE TITLE
关于smux使用过程中的现象

### ISSUE THREAD

**Issue by yyiu** [SagerNet/sing-box#504]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

出站smux配置如下，在使用过程发现一个现象，如当500个连接同时通过此outbounds出站，在短时间几分钟或几个小时内可以看到总共建立20个链接，可以计算出每个通道承载了25个链接；但是长时间运行后，总链接会增加，每个通道承载的连接数会无限接近 "min_streams": 10,这个值，如果用mux.cool来对比，只要设置一个最高限制，长时间每个通道承载的连接数一直可以控制在30-50左右，想了解一下smux现在有没有这个功能或者说有要怎么启用，另外能否为mux增加一个内存使用量设置

### Version of sing-box

<details>

```console
$ sing-box 1.2.2

</details>


            "multiplex": {
                 "enabled": true,
                 "protocol": "smux",
                 "max_connections": 100,
                 "min_streams": 10,
                 "max_streams": 0
             },
            "server": "4.5.6.7",
            "server_port": 2222,


</details>

**Comment by oplle** [comment]
我发现个事情，vmess+ws启用多路复用，然后使用IDM设置http代理走sing-box，IDM线程设置为8，IDM下载 http://38.45.64.1/1GB.zip 这个文件，几秒钟之后sing-box的代理就连不上了。如果我把multiplex"设置成false再次测试就代理就是正常的。
      "multiplex": {
        "enabled": true,
        "max_connections": 4,
        "min_streams": 4

**Comment by moranno** [comment]
我也有相同的疑问，在连接数很多的情况下，如何才是最佳实践的配置呢？

**Comment by yyiu** [comment]
环境是ubuntu 20.04，使用中有发现几天后会突然所有连接重连，但是这个问题出现周期太长，也不好确定是不是smux引起的。

**Comment by yyiu** [comment]
> 我发现个事情，vmess+ws启用多路复用，然后使用IDM设置http代理走sing-box，IDM线程设置为8，IDM下载 http://38.45.64.1/1GB.zip 这个文件，几秒钟之后sing-box的代理就连不上了。如果我把multiplex"设置成false再次测试就代理就是正常的。 "multiplex": { "enabled": true, "max_connections": 4, "min_streams": 4

这里有个mux相关的，但应该不是一类问题。他们修复了下载时子连接不能正常关断的问题。
https://github.com/XTLS/Xray-core/pull/1417

**Comment by oplle** [comment]
> > 我发现个事情，vmess+ws启用多路复用，然后使用IDM设置http代理走sing-box，IDM线程设置为8，IDM下载 http://38.45.64.1/1GB.zip 这个文件，几秒钟之后sing-box的代理就连不上了。如果我把multiplex"设置成false再次测试就代理就是正常的。 "multiplex": { "enabled": true, "max_connections": 4, "min_streams": 4
> 
> 这里有个mux相关的，但应该不是一类问题。修复了下载时子连接不能正常关断的问题。 [XTLS/Xray-core#1417](https://github.com/XTLS/Xray-core/pull/1417)

你这个问题其实sing-box也有讨论过，我当时也有参与讨论，好像是说修复了，我也不会看代码所以不清楚。
而我现在反馈的这个问题是完全新的发现。
