### ISSUE TITLE
Non-standard HTTP behavior in v2ray transport http/1.1

### ISSUE THREAD

**Issue by TargetLocked** [SagerNet/sing-box#505]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

I've encountered the same issue in #472 .

After some investigation, I found that Content-Length was 0 in the client request, so maybe reverse proxies like nginx don't recognize the following fragments and not forwarding them. Setting Transfer-Encoding to chunked (like the server response does) may fix the issue.

![image](https://user-images.githubusercontent.com/32962687/230343003-ce67261f-393c-4f37-ad18-df6d6d5d1610.png)

Some other thoughts: in most cases where we can't control the gateway,  http/1.1 transport is hard to use since the default behavior of a reverse proxy is to [cache chunked requests rather than just forwarding them](https://serverfault.com/questions/624897/getting-a-chunked-request-through-nginx). Not sure if h2 would be better. This may be footnoted in the documentation.

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version unknown

Environment: go1.20.1 windows/amd64
Tags: with_quic,with_grpc,with_wireguard,with_utls
CGO: enabled
```

</details>

### Server and client configuration file

<details>

```console
{
    "log": {
        "disabled": false,
        "level": "debug",
        "output": "test.log",
        "timestamp": true
    },
    "ntp": {
        "enabled": true,
        "server": "time.apple.com",
        "server_port": 123,
        "interval": "30m"
        // Dial Fields
    },
    "inbounds": [
        {
            "type": "vmess",
            "tag": "vmess-in",
            "listen": "::",
            "listen_port": 11451,
            "users": [
                {
                    "uuid": "6981c7fa-0885-44bf-841f-4c981ca9e5ff",
                    "alterId": 0
                }
            ],
            "tls": {},
            "transport": {
                "type": "http",
                "host": [],
                "path": "/4a627d1c",
                "method": "PUT",
                "headers": {}
            }
        }
    ]
}
```

```console
{
    "log": {
        "disabled": false,
        "level": "debug",
        "output": "singbox.log",
        "timestamp": true
    },
    "ntp": {
        "enabled": false,
        "server": "time.apple.com",
        "server_port": 123,
        "interval": "30m"
        // Dial Fields
    },
    "route": {
        "geoip": {},
        "geosite": {},
        "rules": [],
        "final": "vmess-out",
        "auto_detect_interface": true
    },
    "inbounds": [
        {
            "type": "socks",
            "tag": "socks-in",
            // Listen Fields
            "listen": "::",
            "listen_port": 10002
        }
    ],
    "outbounds": [
        {
            "type": "vmess",
            "tag": "vmess-out",
            "server": "127.0.0.1",
            "server_port": 11452,
            "uuid": "6981c7fa-0885-44bf-841f-4c981ca9e5ff",
            "security": "auto",
            "alter_id": 0,
            "global_padding": false,
            "authenticated_length": true,
            "network": "tcp",
            "tls": {
                "enabled": false
            },
            "packet_encoding": "",
            "multiplex": {},
            "transport": {
                "type": "http",
                "host": [
                    // "test.test"
                ],
                "path": "/4a627d1c",
                "method": "PUT",
                "headers": {}
            }
            // "detour": "socks-out"
        }
    ]
}
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/679b1b2a0efce76e6b7bb200b11dcb47e194b9b9

**Comment by TargetLocked** [comment]
Thank you for your efforts. That doesn't work with the following logs.

`+0800 2023-04-07 11:44:29 ERROR [4264053273 12ms] inbound/socks[socks-in]: process connection from 127.0.0.1:7784: http: Request.ContentLength=-1 with nil Body`

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/fc80289da938c0bf8566158297be85bfd9a8f11a

**Comment by TargetLocked** [comment]
Doesn't work even without nginx. Will capture traffic and see what happens.

**Comment by TargetLocked** [comment]
I'm not quite sure about the protocol, but it is different from the working version that
1) client now sends the 2nd packet without waiting for server response
2) server didn't reply until Ctrl-C was sent to curl (which I used to make requests)

![image](https://user-images.githubusercontent.com/32962687/230555239-85076f84-3a15-45ce-96ba-e38a4ea99fb5.png)

Above analysis is without nginx, i.e. changing server_port in the original config to 11451 here.

**Comment by nekohasekai** [comment]
I forgot a problem, it seems that the http/1.1 server has to wait for the request to be completed before responding, which is why http1 in v2ray is a kind of "TCP header", which should also can't be proxied.

**Comment by TargetLocked** [comment]
Ahh, thanks for pointing out that, which I didn't know. Adding up this conclusion and [the mentioned cache issue](https://serverfault.com/questions/624897/getting-a-chunked-request-through-nginx), I would suggest adding a brief description for this in the doc.

It may be possible to change both client and server (potentially by manipulating raw TCP conn) to make it work, as long as buffering is disabled. But I doubt whether the potential benefit would outweigh the future maintenance burden, since practical application would require control of the gateway.

**Comment by nekohasekai** [comment]
Anyway, I think making http/1.1 transport use chunked request will break compatibility with v2ray.
