### ISSUE TITLE
About transport h2

### ISSUE THREAD

**Issue by aetoray** [SagerNet/sing-box#506]
Does sing-box support h2 transports?
If not, when will it be added?
Is it integrated with transport http if supported?
The reason for these questions is that some of the configs are v2ray h2 and do not work in sing-box.

**Comment by amirhosss** [comment]
Yes, sing-box support h2 with TLS.
They fixed an issue related to h2 in the last release.

**Comment by EndermanCo** [comment]
thank you.

**Comment by aetoray** [comment]
thank you.
