### ISSUE TITLE
panic: repeated read on failed websocket connection

### ISSUE THREAD

**Issue by xh116** [SagerNet/sing-box#509]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

I am running the sing-box in container as vmess  server.  (inside RouterOS)
and quantumult X as client. 
It worked well before v1.16 for 4 months, but after upgraded to 1.2.2 and 1.2.3.  it often got panic and container stopped. 
It happend after successfully connected and will stop unexpectedly. 

### Version of sing-box

 
> sing-box version 1.2.2-5edad47
> 
> Environment: go1.20.3 linux/arm
> Tags: with_gvisor,with_quic,with_wireguard,with_reality_server,with_clash_api,with_acme
> Revision: 5edad47d52b3e3786c8c36839ce5ebc48717f9a4
> CGO: disabled

 

### Server and client configuration file

server config: 
 

```
{
    "log":
    {
        "level": "debug" 
    },
    "inbounds":
    [
        {
            "type": "vmess",
            "tag": "vmess-in",
            "listen": "0.0.0.0",
            "listen_port": 2080,
            "tcp_fast_open": true,
            "udp_fragment": true,
            "sniff": true,
            "sniff_override_destination": false,
            "sniff_timeout": "300ms",
            "domain_strategy": "prefer_ipv4",
            "udp_timeout": 300,
            "proxy_protocol": false,
            "proxy_protocol_accept_no_header": false,
            "users":
            [
                {
                    "name": "sing-box",
                    "uuid": "UUID",
                    "alterId": 0
                }
            ],
            "tls":
            {},
            "transport":
            {
                "type": "ws",
                "path": "/189.cn",
                "headers":
                {},
                "max_early_data": 0,
                "early_data_header_name": "Sec-WebSocket-Protocol"
            }
        }
    ],
    "outbounds":
    [
        {
            "type": "direct",
            "tag": "direct"
        }
    ]
}
```
 
client:  quantumult X
`
vmess=xxx.com:22080, method=chacha20-poly1305, password=UUID, obfs=ws, obfs-host=example.com, obfs-uri=/189.cn,fast-open=true, udp-relay=true, tag=V2
 `
 

### Server and client log file

 

server log :
![image](https://user-images.githubusercontent.com/37950502/230615707-43fae2cf-6a92-4cf4-986d-334a59357337.png)

**Comment by xh116** [comment]
sorry, it seems duplicated 
https://github.com/SagerNet/sing-box/issues/473

**Comment by nekohasekai** [comment]
I didn't buy these paid apps, can you guys give a configuration file like xray that can reproduce the problem?

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/f8aa0dc7a36bbc26cc96c10ac8a38fe81e81fb78

**Comment by xh116** [comment]
> 

```
/ # sing-box version
sing-box version 1.3-beta1-f8aa0dc

Environment: go1.20.3 linux/arm
Tags: with_gvisor,with_quic,with_wireguard,with_reality_server,with_clash_api,with_acme
Revision: f8aa0dc7a36bbc26cc96c10ac8a38fe81e81fb78
CGO: disabled
done
```

I just tested the beta version, seems problem solved, at least I can be connected much longer time than before. 
because that problem happened randomly, I can not reproduce and find a way to trigger it.

**Comment by xh116** [comment]
by the way, is there any way to disable or hide the "time" at each line ?
I found  ` "timestamp": false` not work. 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/37950502/230708499-6b64e4ce-dbb5-42b9-9369-a851614d10b8.png">

**Comment by xh116** [comment]
> Try [f8aa0dc](https://github.com/SagerNet/sing-box/commit/f8aa0dc7a36bbc26cc96c10ac8a38fe81e81fb78)

Problem solved.
