### ISSUE TITLE
How to config the exception addresss for system proxy?

### ISSUE THREAD

**Issue by jewian** [SagerNet/sing-box#518]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

![image](https://user-images.githubusercontent.com/2015792/230767568-82c6ebb7-7b87-45a6-a5e5-12ae4b5a8ff2.png)

If system proxy is enabled, it will auto add a group of intranet IP addresses as exceptions.

However, I would like some of above CIDR to outbound with proxy.

In v2ray, there is an attribute "defIEProxyExceptions" for that. Is there any same config in sing-box?

### Version of sing-box

1.1.6

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by nekohasekai** [comment]
You can manually modify this field, sing-box will not overwrite it.
