### ISSUE TITLE
VMess HTTP，clash 无法连接至 sing-box server

### ISSUE THREAD

**Issue by SimonTLS** [SagerNet/sing-box#523]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

VMess HTTP
sing-box 与 xray 互为 server client 可正常连接，同配置下 clash 能连接至 xray 但 sing-box server 报错 bad request

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.3-beta4

Environment: go1.20.2 linux/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_reality_server,with_clash_api
Revision: e20130de85a3a9cb6a09f2808fb3bbff661bba76
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```console
clash proxy config
- {name: test, server: 1.1.1.1, port: 80, type: vmess, uuid: 994434d1-71f2-4d42-95a9-b5049d4e2cb0, alterId: 0, cipher: auto, network: http, http-opts: {method: "GET", path: ["/test"],headers: {Host: ["1.1.1.1"]}}, udp: true}

sing-box server config
{
    "log": {
        "disabled": false,
        "level": "debug",
        "timestamp": true
    },
    "dns": {
        "servers": [
            {
                "tag": "cloudflare",
                "address": "tls://1.1.1.1",
                "strategy": "ipv4_only",
                "detour": "direct"
            }
        ]
    },
    "inbounds": [
        {
            "listen": "::",
            "listen_port": 80,
            "sniff": true,
            "sniff_override_destination": true,
            "type": "vmess",
            "users": [
                {
                    "uuid": "994434d1-71f2-4d42-95a9-b5049d4e2cb0",
                    "alterId": 0
                }
            ],
            "transport": {
                "type": "http",
                "host": "1.1.1.1",
                "path": "/test",
                "method": "GET",
                "headers": {}
            }
        }
    ],
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        }
    ],
    "route": {
        "rules": []
    }
}

xray server config
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": 80,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "994434d1-71f2-4d42-95a9-b5049d4e2cb0",
            "email": "",
            "alterId": 0
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tcpSettings": {
          "header": {
            "type": "http",
            "request": {
              "method": "GET",
              "path": [
                "/test"
              ],
              "headers": {
                "Host": [
                  "1.1.1.1"
                ]
              }
            }
          }
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ]
}
```

</details>

### Server and client log file

<details>

```console
sing-box server log
INFO [2784954275 0ms] inbound/vmess[0]: inbound connection from x.x.x.x:46664
ERROR [2784954275 0ms] inbound/vmess[0]: process connection from x.x.x.x:46664: bad request
```

</details>

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/194b36b987338e24fd15648f002a131dec47f081

**Comment by SimonTLS** [comment]
> Try [194b36b](https://github.com/SagerNet/sing-box/commit/194b36b987338e24fd15648f002a131dec47f081)

panic

go install -v github.com/sagernet/sing-box/cmd/sing-box@dev-net

root@KVM:~# ./go/bin/sing-box run -c ./config.json 
+0100 2023-04-11 05:38:11 INFO inbound/vmess[0]: tcp server started at [::]:80
+0100 2023-04-11 05:38:11 INFO sing-box started (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8be44f]

goroutine 9 [running]:
github.com/sagernet/sing-box/transport/v2rayhttp.(*Server).Serve(0xc00014aab0, {0xdadb00, 0xc0000138d8})
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.2.4-0.20230411033853-534c4928294d/transport/v2rayhttp/server.go:162 +0x2f
github.com/sagernet/sing-box/inbound.(*VMess).Start.func1()
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.2.4-0.20230411033853-534c4928294d/inbound/vmess.go:105 +0x4b
created by github.com/sagernet/sing-box/inbound.(*VMess).Start
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.2.4-0.20230411033853-534c4928294d/inbound/vmess.go:104 +0x1c5

**Comment by SimonTLS** [comment]
> Try [194b36b](https://github.com/SagerNet/sing-box/commit/194b36b987338e24fd15648f002a131dec47f081)

panic

go install -v github.com/sagernet/sing-box/cmd/sing-box@dev-next

root@KVM:~# ./go/bin/sing-box run -c ./config.json 
+0100 2023-04-11 05:38:11 INFO inbound/vmess[0]: tcp server started at [::]:80
+0100 2023-04-11 05:38:11 INFO sing-box started (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8be44f]

goroutine 9 [running]:
github.com/sagernet/sing-box/transport/v2rayhttp.(*Server).Serve(0xc00014aab0, {0xdadb00, 0xc0000138d8})
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.2.4-0.20230411033853-534c4928294d/transport/v2rayhttp/server.go:162 +0x2f
github.com/sagernet/sing-box/inbound.(*VMess).Start.func1()
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.2.4-0.20230411033853-534c4928294d/inbound/vmess.go:105 +0x4b
created by github.com/sagernet/sing-box/inbound.(*VMess).Start
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.2.4-0.20230411033853-534c4928294d/inbound/vmess.go:104 +0x1c5

**Comment by SimonTLS** [comment]
> f798287

可以用了，非常感谢！！！
