### ISSUE TITLE
希望sing-box能有模块化的编译方式，用以减少软件大小

### ISSUE THREAD

**Issue by Wai5888** [SagerNet/sing-box#531]
你好，开发者们，目前的sing-box很强大，已经满足大部分日常需求。我这边也尝试将sing-box集成到自己的openwrt路由器里面，但是碍于路由器容量有限，我希望能像v2ray一样，支持模块化编译，通过参数控制需要继承的功能模块，小小建议，望采纳。

**Comment by CHIZI-0618** [comment]
> 你好，开发者们，目前的sing-box很强大，已经满足大部分日常需求。我这边也尝试将sing-box集成到自己的openwrt路由器里面，但是碍于路由器容量有限，我希望能像v2ray一样，支持模块化编译，通过参数控制需要继承的功能模块，小小建议，望采纳。

请参考：https://sing-box.sagernet.org/installation/from-source/
可以加入 `-ldflags "-w -s"` 参数进一步减小编译后体积。
如果想进一步减小二进制体积，可以考虑使用 [upx](https://github.com/upx/upx) 压缩

**Comment by Wai5888** [comment]
感谢两位的建议 @yaotthaha @CHIZI-0618，我之前尝试的是下载源码进行编译，试过上述的方法，但是体积不但没有变小，反而变大了。

**Comment by firefoxOnFire** [comment]
> Thanks for the two suggestions @yaotthaha @CHIZI-0618, using the method you provided, the size of the software has been significantly reduced, thanks

What is the final size of your binary now? I have 8.18MB sapce in my openwrt router, can I install this??

**Comment by firefoxOnFire** [comment]
@Wai5888 can you help me regarding the size of binary?
Please reply to me if you see this.

**Comment by Wai5888** [comment]
@firefoxOnFire 
In my case, I build it with `with_v2ray_api`, the size decreased from 22+M to 17M. I haven’t used UPX yet, so you can try it yourself

**Comment by firefoxOnFire** [comment]
> @firefoxOnFire In my case, I build it with `with_v2ray_api`, the size decreased from 22+M to 17M. I haven’t used UPX yet, so you can try it yourself

what is your available size in your router?? mine is 8.1MB
