### ISSUE TITLE
[Feature Request]: 希望加入流量控制模块

### ISSUE THREAD

**Issue by zakuwaki** [SagerNet/sing-box#538]
目标：给sing-box加入流量控制模块，可以对特定的连接限制上传/下载速率，实现带宽资源的合理分配
需求：类似于router模块，抽象出一个limiter模块，可以针对inbound/outbound/domain/ip_cidr/geoip/geosite/source_ip_cidr等命中特定规则的流量实现限流，包括单链接限流或全局限流
参考：frp基于[令牌桶](https://pkg.go.dev/golang.org/x/time/rate)方法实现了一套[限速模块](https://github.com/fatedier/frp/tree/dev/pkg/util/limit)，读了sing-box的代码，应该需要和route模块深度绑定，并在sing里面封装好一套支持有锁和无锁的LimitedConn使用，奈何技术太菜写不出来，这种大规模的更改怕腐化了代码。还是得请大佬出山相助

**Comment by JimmyHuang454** [comment]
你可以使用具有流量控制功能的前置代理，例如说ngnix，他们更专业，生态好，功能成熟；并且我觉得个人用户不会使用这种功能，除非是机场主

**Comment by zakuwaki** [comment]
还真不是机场主。公益给好几名同学使用，奈何个别人用来挂bt下毛片。我是想让他用，不过别把流量刷的太快搞得大家都没得用了

**Comment by 716c** [comment]
> 还真不是机场主。公益给好几名同学使用，奈何个别人用来挂bt下毛片。我是想让他用，不过别把流量刷的太快搞得大家都没得用了

keywords: 学生；毛片；刷太快！

**Comment by 173223163** [comment]
> 还真不是机场主。公益给好几名同学使用，奈何个别人用来挂bt下毛片。我是想让他用，不过别把流量刷的太快搞得大家都没得用了

雀氏狗

**Comment by yogurt7771** [comment]
> 还真不是机场主。公益给好几名同学使用，奈何个别人用来挂bt下毛片。我是想让他用，不过别把流量刷的太快搞得大家都没得用了

下bt应该不需要梯子吧

**Comment by linzzzzllll** [comment]
ios能加个小组件快速启用吗

**Comment by kkocdko** [comment]
有类似需求的可以考虑用楼主的 PR 自行编译，用了一下挺正常的。也可以考虑用 [hysteria2 协议](https://sing-box.sagernet.org/manual/proxy-protocol/hysteria2/#server-example) 然后配置 `"up_mbps": 50, "down_mbps": 50` 这样。
