### ISSUE TITLE
wireguard连回家里后，无法访问

### ISSUE THREAD

**Issue by mjyhj** [SagerNet/sing-box#542]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

在路由上看到，WG成功连接，但是无法访问目的地网段，估计是不能像APP那样设置 路由的DNS和允许访问0.0.0.0/0

以下是APP上的配置，就能正常 访问192.168.123.0/24
[Interface]
Address = 192.168.19.2
PrivateKey = 2O/tZ0Zj4vYuFfXd7*****LzBIK3SE4r+F6bUgKs4XY=
### DNS = 192.168.123.1
[Peer]
PublicKey = u9lqJlgZK0b2APyg*****kbnRYRjxiyXTfJ0/5cFHM=
### AllowedIPs = 0.0.0.0/0
presharedKey = LuWdqhmUXbIA3B*****PFuiF59jR42ZHHITUFnLY8=
Endpoint = *****
PersistentKeepalive = 30

### Version of sing-box

模块版，不知道哪里能看到

### Server and client configuration file

模块版，实在找不到

### Server and client log file

<details>

```console
  "outbounds": [
    {
      "type": "wireguard",
      "tag": "wireguard",
      "server": "*****",
      "server_port": 58888,
      "local_address": [
        "192.168.19.2/32"
      ],
      "private_key": "2O/tZ0Zj4vYuFfXd7*****LzBIK3SE4r+F6bUgKs4XY=",
      "peer_public_key": "u9lqJlgZK0b2APyg*****kbnRYRjxiyXTfJ0/5cFHM=",
      "pre_shared_key": "LuWdqhmUXbIA3B*****PFuiF59jR42ZHHITUFnLY8=",
      "mtu": 1420
    },
    {
      "tag": "direct",
      "type": "direct"
    },
```

```console
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns"
      },
      {
        "protocol": "quic",
        "outbound": "block"
      },
        "outbound": "direct"
      },
      {
        "ip_cidr": [
          "192.168.123.0/24"
        ],
        "outbound": "wireguard"
      },
```
</details>

**Comment by nekohasekai** [comment]
issue 不提供帮你调通的服务，请前往社区 （ https://community.sagernet.org/c/sing-box ）。

**Comment by mjyhj** [comment]
3Q，发现是MTU问题，调到1350就正常了

**Comment by llity** [comment]
> 3Q，发现是MTU问题，调到1350就正常了

你就配置了这些能成功连上了吗？
