### ISSUE TITLE
软路由运行SING-BOX，NTP服务不断开

### ISSUE THREAD

**Issue by usaxyh** [SagerNet/sing-box#543]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

我在软路由上裸跑SING-BOX核心，使用YACD面板观察到，sing-box代理的路由器的NTP客户端服务在连接一段时间后不会断开，并且连接数会越来越多。另外代理的局域网NTP服务也不会断开。附件YACD面板截图
![1681778704277](https://user-images.githubusercontent.com/39816297/232640546-20004f92-96cc-4de1-807b-65183fa62943.jpg)
![1681778673216](https://user-images.githubusercontent.com/39816297/232640550-8215eff2-3bfb-4d24-8a37-8d31a90f5a89.jpg)

### Version of sing-box

<details>

```console
$ sing-box version
dev-next最新 with_utls,with_clash_api,with_quic
```

</details>

### Server and client configuration file

<details>

```console
{
  "log": {
    "disabled": false,
    "level": "warn"
,
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "dns-remote",
        "address": "1.1.1.1",
        "address_resolver": "dns-direct",
        "detour": "proxy"
      },
      {
        "tag": "dns-direct",
        "address": "https://223.5.5.5/dns-query",
        "address_resolver": "dns-local",

        "detour": "direct"
      },
      {
        "tag": "dns-local",
        "address": "local",
        "detour": "direct"
      },
      {
        "tag": "dns-block",
        "address": "rcode://success"
      }
    ],
    "rules": [
      {
        "outbound": "any",
        "server": "dns-direct"
      },
      {
        "clash_mode": "direct",
        "server": "dns-direct"
      },
      {
        "clash_mode": "global",
        "server": "dns-remote"
      },
      {
        "geosite": "tiktok",
        "server": "dns-remote"
      },
      {
        "domain_keyword": [
          "hicloud",
          "dbankcloud",
          "uber"
        ],
        "geosite": [
          "cn"
        ],
        "server": "dns-direct"
      },
      {
        "geosite": "category-ads-all",
        "server": "dns-block",
        "disable_cache": true
      }
    ],
    "final": "dns-remote",
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
      "type": "direct",
      "tag": "dns-in",
      "listen": "127.0.0.1",
      "listen_port": 7874,
      "network": "udp",
      "override_address": "1.1.1.1",
      "override_port": 53
    }, 
    {
      "type": "tun",
      "tag": "tun-in",
      "interface_name": "tun0",
      "mtu": 9000,
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "strict_route": false,
      "stack": "system",
      "sniff": true,
      "sniff_override_destination": false
    }
  ],
"outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "geoip": {
      "download_url": "https://cdn.jsdelivr.net/gh/soffchen/sing-geoip@release/geoip.db",
      "download_detour": "direct"
    },
    "geosite": {
      "download_url": "https://cdn.jsdelivr.net/gh/soffchen/sing-geosite@release/geosite.db",
      "download_detour": "direct"
    },
    "rules": [
      {
        "clash_mode": "direct",
        "outbound": "direct"
      },
      {
        "clash_mode": "global",
        "outbound": "proxy"
      },
      {
        "inbound": "dns-in",
        "outbound": "dns-out"
      },
      {
        "domain_keyword": [
          "hicloud",
          "uber",
          "dbankcloud"
        ],
        "outbound": "direct"
      },
      {
        "geosite": "tiktok",
        "outbound": "proxy"
      },
      {
        "ip_cidr": [
        	"36.152.44.96/32",
        	"36.152.44.95/32"
        ],	
        "port": 80,
        "outbound": "block"
      },
      {
        "network": "udp",
        "geosite": "youtube",
        "port": 443,
        "outbound": "block"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "geosite": [
          "microsoft",
          "openai"
        ],
        "outbound": "microsoft"
      },
      {
        "geoip": "telegram",
        "outbound": "telegram"
      },
      {
        "geosite": [
          "cn"
        ],
        "outbound": "direct"
      },
      {
        "geoip": [
          "cn",
          "private"
        ],
        "outbound": "direct"
      }
    ],
    "final": "proxy",
    "auto_detect_interface": true
  },
  "experimental": {
    "clash_api": {
      "external_controller": "0.0.0.0:9090",
      "external_ui": "/root/sing-box/yacd",
      "default_mode": "rule",
      "store_selected": true,
      "store_fakeip": false,
      "cache_file": ""
    }
  }
}
```

</details>

### Server and client log file

<details>

```console
服务器无报错，具体看问题描述的附件截图
```

</details>

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/49d6695a37b9bfef7c99904e2eb6728e64efc07e

**Comment by usaxyh** [comment]
> Try [49d6695](https://github.com/SagerNet/sing-box/commit/49d6695a37b9bfef7c99904e2eb6728e64efc07e)
新的commit没有解决这个问题。观察到53端口UDP连接正常断开，非53端口UDP连接均存在此问题。
![image](https://user-images.githubusercontent.com/39816297/232649667-49189cef-9ba5-4e9a-889c-a6a44520cbfe.png)
![image](https://user-images.githubusercontent.com/39816297/232650135-34aae95f-0e09-4c47-8f07-e8f43cb86b66.png)

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/f4fa22f14508f9812c0f1649c8b299ae7fb481b1

**Comment by usaxyh** [comment]
> [f4fa22f](https://github.com/SagerNet/sing-box/commit/f4fa22f14508f9812c0f1649c8b299ae7fb481b1)
> 
> 测试没有发现问题，请使用此 commit 重新尝试。（并且等待 udp_timeout 的双倍时间，在默认情况下是十分钟）
好像还是不行，当然我菜，不排除是我的问题。。。
![image](https://user-images.githubusercontent.com/39816297/232706484-d3598762-6146-4df8-8767-2b4e173ee231.png)

**Comment by zakuwaki** [comment]
tcp connection leak reproduced on 18f0564c5cb02a791d27ac620328419076252b43, however not reproduced on stable version.

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/f98de04fdd5bee961f96e3e778bbc9acd7d8c949

**Comment by usaxyh** [comment]
> [f98de04](https://github.com/SagerNet/sing-box/commit/f98de04fdd5bee961f96e3e778bbc9acd7d8c949)
感谢，终于UDP连接可以正常关闭了，我先跑一段时间看看还有没有问题
![1681814709925](https://user-images.githubusercontent.com/39816297/232754249-142a9188-a2cb-4e93-80c3-85c4ed3e8c25.jpg)

**Comment by zakuwaki** [comment]
confirm to be fixed

**Comment by usaxyh** [comment]
从昨天测试到现在又发现一个新的问题，在访问github之后，关闭网页页面，YACD面板显示github tcp连接不会中断，如果再打开GITHUB，又会出现新的重复连接，看图
![1681887663376](https://user-images.githubusercontent.com/39816297/232994765-b33dea65-aa58-4f30-bc83-a83d2ca16d8d.jpg)
就算关闭电脑，TCP连接一直存在
