### ISSUE TITLE
[建议] 多配置文件格式支持

### ISSUE THREAD

**Issue by 1trapcode** [SagerNet/sing-box#545]
简短的说
json在写配置上面没什么优势
希望支持jsonc
后续继续支持YAML或者TOML

**Comment by dev-techmoe** [comment]
a workaround is using [yq](https://github.com/mikefarah/yq) to combine and convert your yaml to json format.

I'm also hoping for the support of yaml format config.

**Comment by james-curtis** [comment]
+1
