### ISSUE TITLE
连接 hysteria 节点 DNS 问题

### ISSUE THREAD

**Issue by ximiTech** [SagerNet/sing-box#549]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

服务端为 原版hysteria，使用 tls 时 报错，无法使用代理

### Version of sing-box

<details>

```console
1.2.4
```

</details>

### Server and client configuration file

<details>

```console
使用 homeproxy
```

</details>

### Server and client log file

<details>

```console
+0000 2023-04-19 14:53:41 ERROR dns: exchange failed for dr._dns-sd._udp.0.29.168.192.in-addr.arpa. IN PTR: CRYPTO_ERROR 0x12a (local): tls: failed to verify certificate: x509: certificate signed by unknown authority
+0000 2023-04-19 14:53:41 ERROR dns: exchange failed for www.youtube.com. IN A: CRYPTO_ERROR 0x12a (local): tls: failed to verify certificate: x509: certificate signed by unknown authority
+0000 2023-04-19 14:53:41 ERROR dns: exchange failed for www.youtube.com. IN AAAA: CRYPTO_ERROR 0x12a (local): tls: failed to verify certificate: x509: certificate signed by unknown authority
+0000 2023-04-19 14:53:41 ERROR dns: exchange failed for www.youtube.com. IN HTTPS: CRYPTO_ERROR 0x12a (local): tls: failed to verify certificate: x509: certificate signed by unknown authority
+0000 2023-04-19 14:53:43 ERROR dns: exchange failed for www.youtube.com. IN A: CRYPTO_ERROR 0x12a (local): tls: failed to verify certificate: x509: certificate signed by unknown authority
```

</details>

**Comment by yrwy** [comment]
服务端的dns不能用tls，还有服务端的规则domain也不起作用，得用domain_keyword。

**Comment by ximiTech** [comment]
> 服务端的dns不能用tls，还有服务端的规则domain也不起作用，得用domain_keyword。
服务端dns用的udp，规则未设置domain。。。

**Comment by elric8** [comment]
> > 服务端的dns不能用tls，还有服务端的规则domain也不起作用，得用domain_keyword。
> 
> 服务端dns用的udp，规则未设置domain。。。

我软路由也这个错误，兄弟你最后怎么解决的
