### ISSUE TITLE
希望能屏蔽no raw query support by current transport

### ISSUE THREAD

**Issue by shadow750d6** [SagerNet/sing-box#550]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

用local或者fakeip做dns的时候，会有大量的log

```
dns: exchange failed for XXXX.com. IN HTTPS: no raw query support by current transport
```

我知道这是什么意思，我只想屏蔽它，因为这种log数量太多掩盖了真正有意义的log。

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```

iOS版本，sing-box 1.3-beta8

</details>

### Server and client configuration file

<details>

```json
{
  "log": {
    "level": "warn",
    "timestamp": true
  },
  "dns": {
    "reverse_mapping": true,
    "fakeip": {
      "enabled": true,
      "inet4_range": "198.18.0.0/15",
      "inet6_range": "fc00::/18"
    },
    "servers": [
      {
        "tag": "fakeip",
        "address": "fakeip"
      },
      {
        "tag": "local",
        "address": "local",
        "detour": "direct"
      },
      {
        "tag": "block",
        "address": "rcode://success"
      }
    ],
    "rules": [
      {
        "domain_suffix": [
          "google.cn"
        ],
        "geosite": [
          "cn",
          "apple"
        ],
        "server": "local"
      }
    ],
    "strategy": "prefer_ipv6",
    "final": "fakeip"
  },
  "inbounds": [
    {
      "type": "tun",
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "auto_route": true,
      "strict_route": false,
      "sniff": true
    }
  ],
  "outbounds": [
    {
      "type": "trojan",
      "tag": "proxy",
      "server": "XXXX",
      "server_port": 443,
      "password": "XXXXX",
      "domain_strategy": "prefer_ipv6",
      "tls": {
        "enabled": true,
        "alpn": "http/1.1",
        "server_name": "XXXXX"
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "ip_cidr": [
          "198.18.0.0/15",
          "fc00::/18"
        ],
        "outbound": "proxy"
      },
      {
        "domain_suffix": [
          "google.cn"
        ],
        "geosite": [
          "cn",
          "apple"
        ],
        "geoip": [
          "private",
          "cn"
        ],
        "outbound": "direct"
      }
    ],
    "auto_detect_interface": true
  }
}
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by nekohasekai** [comment]
不要将非 IP 查询路由到 fakeip。

**Comment by shadow750d6** [comment]
OK，这个建议很不错，我加了一个DNS rule

```javascript
      {
        "query_type": [
          "HTTPS",
          "SVCB"
        ],
        "server": "block"
      },
```

**Comment by bi4nbn** [comment]
加了也不管用呢

24-03-24 21:30:47[ error ]dns: exchange failed for cdn.oaistatic.com. IN HTTPS: no raw query support by current transport
24-03-24 21:30:47[ error ]dns: exchange failed for chat.openai.com. IN HTTPS: no raw query support by current transport
24-03-24 21:30:08[ error ]dns: exchange failed for logs.netflix.com. IN HTTPS: no raw query support by current transport
24-03-24 21:28:28[ error ]dns: exchange failed for cdn.oaistatic.com. IN HTTPS: no raw query support by current transport
24-03-24 21:28:26[ error ]dns: exchange failed for ichnaea-web.netflix.com. IN HTTPS: no raw query support by current transport
24-03-24 21:28:26[ error ]dns: exchange failed for www.netflix.com. IN HTTPS: no raw query support by current transport
24-03-24 21:28:26[ error ]dns: exchange failed for web.prod.cloud.netflix.com. IN HTTPS: no raw query support by current transport
24-03-24 21:28:25[ error ]dns: exchange failed for logs.netflix.com. IN HTTPS: no raw query support by current transport
24-03-24 21:28:23[ error ]dns: exchange failed for assets.nflxext.com. IN HTTPS: no raw query support by current transport
24-03-24 21:28:19[ error ]dns: exchange failed for www.netflix.com. IN HTTPS: no raw query support by current transport
24-03-24 21:28:18[ error ]dns: exchange failed for help.netflix.com. IN HTTPS: no raw query support by current transport

**Comment by bi4nbn** [comment]
这个是服务器dns解锁的  其他网站没事
