### ISSUE TITLE
External geo files

### ISSUE THREAD

**Issue by msshn** [SagerNet/sing-box#551]
Is it possible to use external Geo files in sing-box like v2ray core? I couldn't find anything in documentation
For example I want to use the following file to block IR domains

https://github.com/bootmortis/iran-hosted-domains/releases/download/202304081539/iran-geosite.db

Thanks.

**Comment by nekohasekai** [comment]
https://sing-box.sagernet.org/configuration/route/geosite/

**Comment by msshn** [comment]
Sorry for reopen, But this way iran-geosite.db will replace default geosite.db, I want to use both geosite files at the same time, block ads with geosite.db and block IR domains using iran-geosite.db

Like this in v2ray:
"geosite:category-ads-all",
"ext:iran-geosite.dat:ir"
