### ISSUE TITLE
clash-api: yacd overview aren't match with usage

### ISSUE THREAD

**Issue by malikshi** [SagerNet/sing-box#565]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

i noticed in [1f11d9b](https://github.com/SagerNet/sing-box/commit/1f11d9ba80951e6e65bbcb070d070d36c563ff9f) overview in yacd aren't updated/matched with usage of traffics. e.g i am downloading 1 GB but the aren't show it right stats and speed. 
![image](https://user-images.githubusercontent.com/9080737/234140189-3a1f712f-dc28-4775-91ff-499f5bb788b5.png)

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version unknown

Environment: go1.20.3 linux/arm64
Tags: with_clash_api,with_grpc,with_wireguard,with_utls,with_gvisor,with_quic,with_dhcp,with_ech,with_reality_server
CGO: enabled
```

</details>

### Server and client configuration file

<details>

```console
{
  "log": {
    "disabled": false,
    "level": "debug",
    "output": "/var/log/box.log",
    "timestamp": true
  },
  "ntp": {
    "enabled": true,
    "server": "time.google.com",
    "server_port": 123,
    "interval": "30m",
    "detour": "direct"
  },
  "experimental": {
    "clash_api": {
      "external_controller": "0.0.0.0:9090",
      "external_ui": "/etc/sing-box/yacd",
      "external_ui_download_url": "https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip",
      "external_ui_download_detour": "direct",
      "secret": "abcded",
      "default_mode": "rule",
      "store_selected": true,
      "cache_file": "/etc/sing-box/clash.db"
    }
  },
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by malikshi** [comment]
solved in recent commits

**Comment by 716c** [comment]
Can I see your rules page with yacd web ui?
