### ISSUE TITLE
能否把“Experimental Android client for sing-box”变成一个github的开放项目

### ISSUE THREAD

**Issue by egg1234** [SagerNet/sing-box#579]
能否像sing-box-for-ios一样把“Experimental Android client for sing-box”变成一个github的开放项目，
这样可以方便用户提issues或提新功能请求，谢谢！

https://sing-box.sagernet.org/installation/clients/sfa/

**Comment by CHIZI-0618** [comment]
> 能否像sing-box-for-ios一样把“Experimental Android client for sing-box”变成一个github的开放项目， 这样可以方便用户提issues或提新功能请求，谢谢！
> 
> https://sing-box.sagernet.org/installation/clients/sfa/

参见 https://github.com/SagerNet/sing-box/issues/541#issuecomment-1511133048
