### ISSUE TITLE
shadowsocks: password bad key length, required 16, got 0

### ISSUE THREAD

**Issue by shumvgolove** [SagerNet/sing-box#580]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

1. Get ShadowTLS configs[ from the official docs](https://sing-box.sagernet.org/examples/shadowtls).
2. Customize "password" field with `base64` string longer/shorter than 16 chars.
3. `sing-box` as a server works fine, while `sing-box` as a client throws this error:
```sh
$ sing-box check -c client-config.json
FATAL[0000] parse outbound[0]: bad key length, required 16, got 0
```

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.3-beta10

Environment: go1.20.3 linux/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_reality_server,with_clash_api,with_acme
Revision: d3b41dfc0128957953a4d8173953e01818680318
CGO: disabled
```
</details>

### Server and client configuration file

<details>

`server-config.json`
```json
{
  "inbounds": [
    {
      "type": "shadowtls",
      "listen": "::",
      "listen_port": 4443,
      "version": 3,
      "users": [
        {
          "name": "sekai",
          "password": "eWVhaF90aGlzX2lzX2FfYnVnCg=="
        }
      ],
      "handshake": {
        "server": "google.com",
        "server_port": 443
      },
      "detour": "shadowsocks-in"
    },
    {
      "type": "shadowsocks",
      "tag": "shadowsocks-in",
      "listen": "127.0.0.1",
      "network": "tcp",
      "method": "2022-blake3-aes-128-gcm",
      "password": "eWVhaF90aGlzX2lzX2FfYnVnCg=="
    }
  ]
}
```
`client-config.json`

```json
{
  "outbounds": [
    {
      "type": "shadowsocks",
      "method": "2022-blake3-aes-128-gcm",
      "password": "eWVhaF90aGlzX2lzX2FfYnVnCg==",
      "detour": "shadowtls-out",
      "multiplex": {
        "enabled": true,
        "max_connections": 4,
        "min_streams": 4
      }
      // or "udp_over_tcp": true
    },
    {
      "type": "shadowtls",
      "tag": "shadowtls-out",
      "server": "127.0.0.1",
      "server_port": 4443,
      "version": 3,
      "password": "eWVhaF90aGlzX2lzX2FfYnVnCg==",
      "tls": {
        "enabled": true,
        "server_name": "google.com",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      }
    }
  ]
}
```

</details>

### Server and client log file

<details>

`server.log`
```sh
$ sing-box check -c server-config.json
TRACE[0000] closing inbound/shadowtls[0]
TRACE[0000] closing inbound/shadowsocks[1]
TRACE[0000] closing outbound/direct[0]
TRACE[0000] closing router
TRACE[0000] router: closing transport[0]
TRACE[0000] closing log factory
```

`client.log`
```sh
$ sing-box check -c client-config.json
FATAL[0000] parse outbound[0]: bad key length, required 16, got 0
```

</details>

**Comment by er888kh** [comment]
I am also having the same issue.

**Comment by er888kh** [comment]
I found the error!
I comes from `sing-shadowsocks2/shadowaead_2022/method.go` (the same problem exists in `shadowaead` too), function `NewMethod`.
It expects the key as `[]byte` to be in `options.Key`. But the caller, which is `sing-box/outbout/shadowsocks.go` only fills `options.Password`, which the user specifies in the configuration as base64 encoding of the key. The solution is to try to decode the `options.Password` into `options.Key` if the key is empty.

I will create a PR and fix the problem if I can tonight.

**Comment by er888kh** [comment]
Done.

Seems to fix the error on my own system.

https://github.com/SagerNet/sing-shadowsocks2/pull/1

**Comment by shumvgolove** [comment]
Thanks, will check tomorrow!

**Comment by nekohasekai** [comment]
No, you should use the key that matches the method. Compatibility with longer keys is a legacy and does not conform to the protocol specification.

https://sing-box.sagernet.org/configuration/inbound/shadowsocks/#password

**Comment by er888kh** [comment]
> No, you should use the key that matches the method. Compatibility with longer keys is a legacy and does not conform to the protocol specification.
> 
> https://sing-box.sagernet.org/configuration/inbound/shadowsocks/#password
> 
> https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/main/2022-1-shadowsocks-2022-edition.md#21-psk

Okay, but at least the part that says `got key length 0` is wrong :sweat_smile:

**Comment by shumvgolove** [comment]
> https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/main/2022-1-shadowsocks-2022-edition.md#21-psk
>
> The PSK is encoded in base64

Ohhh, I thought it just a password (random string) encoded to `base64` for some reason. Perhaps `password` field should be named `key` to avoid confusion.

> https://sing-box.sagernet.org/configuration/inbound/shadowsocks/#password

Thanks, that's good to know!
