### ISSUE TITLE
TUN 模式支持自定义 Metric

### ISSUE THREAD

**Issue by mainians** [SagerNet/sing-box#583]
`Windows` 上开 `TUN` 模式
设置 `"auto_route": true`
路由优先级 `Metric`  默认值为 0
https://github.com/SagerNet/sing-tun/blob/dev/tun_windows.go#L137

---

希望该值可以自定义

**Comment by Hexmile** [comment]
是否有支持此功能的计划？该功能我这边用于调整路由达到多个VPN共存的目的。
