### ISSUE TITLE
strict_route=true 导致 dns lag，怀疑是dns回环？

### ISSUE THREAD

**Issue by simplerick-simplefun** [SagerNet/sing-box#588]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

不知道算不算bug，report一下：

版本：https://github.com/SagerNet/sing-box/releases/tag/v1.3-beta11
~安卓cmd~，安卓app，ios app，windows cmd，都是最新的beta11。客户端的配置文件均相同。
安卓cmd使用的是android-arm64-beta9。
突然发现beta10和beta11在我手机上都没法打开网页/打开巨慢。。。晚些时候有空单独提一个issue。

windows 11（AMD5800）无法使用system stack，使用gvisor，strict_route=true会有较长时间dns lag，strict_route=false没有lag。
安卓app使用gvisor stack会导致dns慢，system stack流畅，strict_route=true/false似乎不影响。（Android13/RedmiK50）
安卓root运行cmd版本，system stack不可用，使用gvisor，strict_route=true无问题，很流畅。（Android13/RedmiK50）
ios使用system stack，strict_route=true无问题。但手动打开settings中的Enforce Routes后，彻底无法打开任何网页。

因不知道是不是属于bug，如果需要更多信息，请回复。安卓app的log文件我不知道怎么获取，如果需要请提示。

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by nekohasekai** [comment]
请拆分为多个 issue

123. 几乎没有提供有效信息，请按 issue template 反馈，或转去 https://community.sagernet.org
4. iOS tunnel settings 由 Apple 提供，请检查 Apple 文档以确保正确使用
