### ISSUE TITLE
Wireguard outbound in multiple config

### ISSUE THREAD

**Issue by malikshi** [SagerNet/sing-box#59]
I running 4 config config  of sing-box.

```
systemctl start sing-box@config1.json
systemctl start sing-box@config2.json
systemctl start sing-box@config3.json
systemctl start sing-box@config4.json
```

I want to ask about wireguard outbound. I put exactly same wireguard outbound for all of them. So how they're gonna work? Is it always re-dial/reconnecting between them? Since sing-box yet supported appended files/config so I use multi instance like that.

**Comment by nekohasekai** [comment]
Obviously they are different processes.

**Comment by malikshi** [comment]
thanks you. i will add new instance as wg-out with mixed-in. and use mixed-in port for other instances. i don't want to create tun/new interface so i use mixed-in.
