### ISSUE TITLE
[Feature Request] DNS expectIPs 功能，验证解析结果是否符合预期

### ISSUE THREAD

**Issue by simplerick-simplefun** [SagerNet/sing-box#592]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

在dns模块中，增加一个验证dns解析出的ip结果是否符合特定规则的功能，类似：*ray的dns.servers[].expectIPs
https://xtls.github.io/config/dns.html#serverobject

对于sing-box，建议增加在dns.rules[].expectIPs位置。
match规则后，解析得出结果，验证解析结果是否符合预期，如果不符合，丢弃该结果，并继续尝试match后面的dns.rules[]。如果全部不符合，则用dns.final来解析。

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by nekohasekai** [comment]
大大增加了延迟并使你的 DNS 泄漏，什么人需要这样的功能？
