### ISSUE TITLE
Support for multi geosite files

### ISSUE THREAD

**Issue by aetoray** [SagerNet/sing-box#595]
What bothers me is that sing-box only supports one geo file and I can't import the list of domains I need And I have to manipulate the original geosite.
Actually, the domain list of my country is not in the main list, and if it is combined with the main list, it is not clear which domain belongs to where.

**Comment by nekohasekai** [comment]
Currently you can send MRs to https://github.com/v2fly/domain-list-community, or create a merged geosite to use.

**Comment by charliez0** [comment]
But maxmind format geoip cannot merge,so multi geoip or another format of geoip is needed

**Comment by XuuKoo** [comment]
> Currently you can send MRs to https://github.com/v2fly/domain-list-community, or create a merged geosite to use.

How to create a custom geosite file?

**Comment by aetoray** [comment]
This message is only for removing the stale tag

**Comment by aetoray** [comment]
This message is only for removing the stale tag
