### ISSUE TITLE
[feature request] SNI-based XTLS-Reality detour

### ISSUE THREAD

**Issue by uprt** [SagerNet/sing-box#596]
The proposal is to add SNI-based XTLS-Reality detour support.

According to the XTLS-Reality idea, the only detour possible is transferring the connection to some real 3rd-party website (like google.com) with its real certificate.

However, this prevents having the same time on the same port VLESS+XTLS-Reality, and a backup option with VLESS+WS or VLESS+gRPC to work over CDNs in case if server's IP address is blocked.

This can be achieved by analyzing the SNI field of the incoming TLS connection ClientHello and setting a special "detour domain" in the config. The simple implementation of SNI proxy in Go is [naive and short](https://www.agwa.name/blog/post/writing_an_sni_proxy_in_go).

So when a new connection is established, we may have the following:

If the user is valid according to XTLS-Reality mechanism, the connection is established with the proxy (VLESS or Trojan)
If not - we check the SNI in ClientHello. If it equals the "secret detour domain", we pass it to the corresponding detour inbound handler.
If it is not equal to the "secret detour domain" - we pass it to the upstream server ("handshake.server" field) as usual in XTLS-Reality.
So by this, we can have XTLS-Reality and WS/gRPC backup on the same server and port. "Detour" to a secret domain will be used only to connect through CDNs, so the censors won't see any direct connections using it and cannot detect it (also would be nice to add IP address filter for it, but probably I'm asking for too much).

I know this can be achieved by using haproxy or sniproxy behind or in front of XRay, but would be nice to have a built-in functionality.

**Comment by nekohasekai** [comment]
1. There is no evidence that GFW actively sends HTTP requests and performs blocking based on responses
2. The behavior of the SNI forwarder, which does not exist on most websites, creates a signature

**Comment by uprt** [comment]
> There is no evidence that GFW actively sends HTTP requests and performs blocking based on responses

GFW is not the only censorship mechanism in the world, other authoritarian countries have their own detection systems too, and you never know what exactly heuristic may trigger blocking of your server,  so having a backup way to reach it always makes sense.

> The behavior of the SNI forwarder, which does not exist on most websites, creates a signature

For the case I described above this statement is technically not true. Until you are trying to reach the "secret domain", the fingerprint and the behavior of the proxy server is 100% equal to the real server (as it happens with XTLS-Reality) - so there's no way for censors to detect the presence of SNI forwarder and proxy if thry don't know the exact secret domain string. That's why I explicitly mentioned that this secret domain should never be accessed directly, only via CDN, so the censors will not be able to trace the server. As a more robust solution to prevent mistakes,  SNI proxy can be used only when the request came from one of the IPs in the list (example https://www.cloudflare.com/ips-v4).
