### ISSUE TITLE
这是确有其事吗

### ISSUE THREAD

**Issue by a649ddi349** [SagerNet/sing-box#599]
![IMG_20230512_030929](https://github.com/SagerNet/sing-box/assets/133263907/bf86c08e-13a7-41bf-bbff-f0d0714903f2)
![IMG_20230512_030943](https://github.com/SagerNet/sing-box/assets/133263907/c0a87e1a-78c4-462a-a143-79cc5dfb6e72)

**Comment by Johnshall** [comment]
1. 世界同时是 v2ray 和 xray 的核心贡献者，比如 ss-2022 在 xray 的实现是世界本人写的。*ray 慢是架构问题。没有必要和意义在这里挑起不必要的矛盾。
2. 性能自己测一下就知道结果了，问是得不到结果的。

**Comment by chika0801** [comment]
积极回复那位红底A字母的和发起话题那位白底无字母头像的，昨天就给他们说清楚了。不用在这引什么。

**Comment by nekohasekai** [comment]
Xray 养着一个 toxic 社区迟早自噬，Xray 在那些测试项目并没有什么优化（最多是调大了 buffer）。
