### ISSUE TITLE
[Feature Request] Support exists preconfigured tun device for linux

### ISSUE THREAD

**Issue by attrr** [SagerNet/sing-box#6]
Currently, sing-box tun mode is only supported when run as root.
Using an unprivileged user, even when user and group set when tun device created is result permission denied.
It would be helpful to support tun device managed by another program such as NetworkManager, so sing-box itself can run as a non-root user.

**Comment by nekohasekai** [comment]
Can you provide a usage example?

**Comment by nekohasekai** [comment]
Try 587739e95c0ab486258a0e17c75b96ccb953f0f8
