### ISSUE TITLE
是不是不给下载了啊

### ISSUE THREAD

**Issue by jjiikkkk** [SagerNet/sing-box#603]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

无法下载

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```
~$ wget https://github.com/SagerNet/sing-box/releases/download/https://github.com/SagerNet/sing-box/releases/download/v1.2.6/sing-box-1.2.6-linux-amd64v3.tar.gz
--2023-05-12 04:09:51--  https://github.com/SagerNet/sing-box/releases/download/https://github.com/SagerNet/sing-box/releases/download/v1.2.6/sing-box-1.2.6-linux-amd64v3.tar.gz
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 40
</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>~$ wget https://github.com/SagerNet/sing-box/releases/download/https://github.com/SagerNet/sing-box/releases/download/v1.2.6/sing-box-1.2.6-linux-amd64v3.tar.gz
--2023-05-12 04:09:51--  https://github.com/SagerNet/sing-box/releases/download/https://github.com/SagerNet/sing-box/releases/download/v1.2.6/sing-box-1.2.6-linux-amd64v3.tar.gz
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 40

### Server and client log file

<details>

```console
# paste log here
```

</details>~$ wget https://github.com/SagerNet/sing-box/releases/download/https://github.com/SagerNet/sing-box/releases/download/v1.2.6/sing-box-1.2.6-linux-amd64v3.tar.gz
--2023-05-12 04:09:51--  https://github.com/SagerNet/sing-box/releases/download/https://github.com/SagerNet/sing-box/releases/download/v1.2.6/sing-box-1.2.6-linux-amd64v3.tar.gz
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 40

**Comment by nekohasekai** [comment]
不给，跑路了。
