### ISSUE TITLE
[Bug Report] connection leaks

### ISSUE THREAD

**Issue by zakuwaki** [SagerNet/sing-box#607]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

The latest sing-box can reproduce connection leaks in many scenarios.

A minimal client config with socks inbound and vless-reality outbound is provided.

Also a production version with shadowsocks/socks inbound and socks/dns/vless-reality also have the connection leaking problem.

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.3-beta11-5065ab3e

Environment: go1.20.4 linux/amd64
Tags: with_utls,with_reality_server,with_gvisor,with_wireguard,with_clash_api
Revision: 5065ab3ee54a441dc496212aa4195de824f06406
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```json
{
    "log": {
        "level": "debug",
        "output": "sing-box.log",
        "timestamp": true
    },
    "route": {
        "rules": [
            {
                "outbound": "direct",
                "geoip": [
                    "private",
                    "cn"
                ],
                "geosite": [
                    "private",
                    "cn"
                ]
            }
        ],
        "final": "proxy"
    },
    "inbounds": [
        {
            "tag": "socks",
            "type": "socks",
            "listen": "0.0.0.0",
            "listen_port": 2080
        }
    ],
    "outbounds": [
        {
            "tag": "direct",
            "type": "direct"
        },
        {
            "tag": "proxy",
            "type": "vless",
            "server": "$server$",
            "server_port": 443,
            "uuid": "$uuid$",
            "flow": "xtls-rprx-vision",
            "packet_encoding": "xudp",
            "tls": {
                "enabled": true,
                "server_name": "$server_name$",
                "utls": {
                    "enabled": true,
                    "fingerprint": "chrome"
                },
                "reality": {
                    "enabled": true,
                    "public_key": "$public_key$",
                    "short_id": "$short_id$"
                }
            }
        }
    ],
    "experimental": {
        "clash_api": {
            "external_controller": "0.0.0.0:9191"
        }
    }
}
```

</details>

### Server and client log file

<details>

# minimal version

Log seems normal, so leaking info is attached

[sing-box.log](https://github.com/SagerNet/sing-box/files/11485446/sing-box.log)

![1684229127283](https://github.com/SagerNet/sing-box/assets/79925675/12bb7386-8eb2-4e4c-a28a-eaa1c66710de)

# production version

```console
$ netstat -tunp | sort | grep sing | wc -l
3482
```

![2](https://github.com/SagerNet/sing-box/assets/79925675/865e1767-d20e-454d-b493-975bbbc696ff)
![3](https://github.com/SagerNet/sing-box/assets/79925675/733e437d-34f4-4acf-a9fb-6c735e6e0f70)

</details>

**Comment by zakuwaki** [comment]
可能是inbound没有`SetReadDeadline`？
如果遇到问题上游，没有传输数据，且一直不主动close TCP连接，server就不会清理？

**Comment by Mahdi-zarei** [comment]
I have the same problem here, my setup uses a socks5 inbound and a shadowsocks detouring into a shadowtls outbound, and eventually as the client is being used the number of open UDP connections (I know it is not exactly a connection) rises to some thousands and my vps ram is finally all used up and the kernel kills the sing-box proccess. I guess things might go better if I use TCP network for my shadowsocks outbound and turn on udp_over_tcp, any other ideas to sidewalk this problem is appreciated.
