### ISSUE TITLE
Routing bug with multiple configuration

### ISSUE THREAD

**Issue by kabegoe** [SagerNet/sing-box#616]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

Inbound from second configuration(`2.json`) is following routing rules from first configuration(`1.json`) when running `sing-box` with command `./sing-box run -c 1.json -c 2.json`.

### Version of sing-box

<details>

```console
$ ./sing-box version
sing-box version 1.2.7

Environment: go1.20.4 linux/amd64
CGO: enabled
```

</details>

### Server and client configuration file

`1.json`

```json
{
  "log": {
    "level": "trace"
  },
  "inbounds": [
    {
      "type": "socks",
      "tag": "2080-in(direct-out)",
      "listen": "127.0.0.1",
      "listen_port": 2080
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct-out",
      "bind_interface": "wlo1"
    }
  ],
  "route": {
    "rules": [
      {
        "inbound": "socks-in",
	"outbound": "direct-out"
      }
    ],
    "final": "direct-out",
    "default_interface": "wlo1"
  }
}
```

`2.json`

```json
{
  "log": {
    "level": "trace"
  },
  "inbounds": [
    {
      "type": "socks",
      "tag": "3080-in(block-out)",
      "listen": "127.0.0.1",
      "listen_port": 3080
    }
  ],
  "outbounds": [
    {
      "type": "block",
      "tag": "block-out"
    }
  ],
  "route": {
    "rules": [
      {
        "inbound": "socks-in",
	"outbound": "block-out"
      }
    ],
    "final": "block-out",
    "default_interface": "wlo1"
  }
}
```

### Server and client log file

Issue `./sing-box run -c 1.json` and access `https://1.1.1.1` with socks5 proxy 127.0.0.1:**2080**. (**Works**. The traffic is sent to `direct-out` as expected)

```console
$ ./sing-box run -c 1.json 
TRACE[0000] initializing inbound/socks[2080-in(direct-out)]
INFO[0000] inbound/socks[2080-in(direct-out)]: tcp server started at 127.0.0.1:2080
INFO[0000] sing-box started (0.00s)
INFO[0013] [1273948834 0ms] inbound/socks[2080-in(direct-out)]: inbound connection from 127.0.0.1:53262
INFO[0013] [1273948834 0ms] inbound/socks[2080-in(direct-out)]: inbound connection to 1.1.1.1:443
INFO[0013] [1273948834 0ms] outbound/direct[direct-out]: outbound connection to 1.1.1.1:443
```

Issue `./sing-box run -c 2.json` and access `https://1.1.1.1` with socks5 proxy 127.0.0.1:**3080**. (**Works**. The traffic is blocked as expected)

```console
$ ./sing-box run -c 2.json 
TRACE[0000] initializing inbound/socks[3080-in(block-out)]
INFO[0000] inbound/socks[3080-in(block-out)]: tcp server started at 127.0.0.1:3080
INFO[0000] sing-box started (0.00s)
INFO[0014] [3183656878 0ms] inbound/socks[3080-in(block-out)]: inbound connection from 127.0.0.1:52294
INFO[0014] [3183656878 0ms] inbound/socks[3080-in(block-out)]: inbound connection to 1.1.1.1:443
INFO[0014] [3183656878 0ms] outbound/block[block-out]: blocked connection to 1.1.1.1:443
INFO[0014] [4009015083 0ms] inbound/socks[3080-in(block-out)]: inbound connection from 127.0.0.1:52306
INFO[0014] [4009015083 0ms] inbound/socks[3080-in(block-out)]: inbound connection to 1.1.1.1:443
INFO[0014] [4009015083 0ms] outbound/block[block-out]: blocked connection to 1.1.1.1:443
```

Issue `./sing-box run -c 1.json -c 2.json` and access `https://1.1.1.1` with socks5 proxy 127.0.0.1:**3080**. (**Not Work**. The traffic should be blocked instead of being sent to  `direct-out`)

```console
$ ./sing-box run -c 1.json -c 2.json 
TRACE[0000] initializing inbound/socks[2080-in(direct-out)]
INFO[0000] inbound/socks[2080-in(direct-out)]: tcp server started at 127.0.0.1:2080
TRACE[0000] initializing inbound/socks[3080-in(block-out)]
INFO[0000] inbound/socks[3080-in(block-out)]: tcp server started at 127.0.0.1:3080
INFO[0000] sing-box started (0.00s)
INFO[0002] [200980176 0ms] inbound/socks[3080-in(block-out)]: inbound connection from 127.0.0.1:60054
INFO[0002] [200980176 0ms] inbound/socks[3080-in(block-out)]: inbound connection to 1.1.1.1:443
INFO[0002] [200980176 0ms] outbound/direct[direct-out]: outbound connection to 1.1.1.1:443
```

**Comment by nekohasekai** [comment]
Profiles are sorted by name, rules will be sorted by priority, and if there is a conflict, the higher priority item takes effect. Also, if you're not making things up, the socks-in tag in the rules doesn't exist.

**Comment by lux5am** [comment]
> Profiles are sorted by name, rules will be sorted by priority, and if there is a conflict, the higher priority item takes effect. Also, if you're not making things up, the socks-in tag in the rules doesn't exist.

do the rules priority sorted by the config name/the order it's loaded?
If I use `sing-box run -D folder -C folder`
- config_rules_1base.json
- config_rules_2games.json
- config_rules_5domestic.json
- config_rules_8ads.json
- config_rules_9final.json

is that alright?
