### ISSUE TITLE
what is inbound for ssh ?

### ISSUE THREAD

**Issue by hosseinkhojany** [SagerNet/sing-box#619]
### Welcome

- [ ] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

Help wanted

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```
</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by H1JK** [comment]
Same to the protocol that you used to manage your remote server. For most Linux servers they do not need a inbound because OpenSSH(sshd) just works as it.
