### ISSUE TITLE
FATAL[0000] decode config at config.json: json: unknown field "type"  

### ISSUE THREAD

**Issue by mshigemoto** [SagerNet/sing-box#620]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

Thanks for the great project.

I'm working on using ”naive proxy"  with the sing-box.
The following error occurs with the attached server configuration file.

`FATAL[0000] decode config at config.json: json: unknown field "type"
`

Probably, there is an error in the part.
  
` "type": "naive",
`

However, this is according to the sample on the following page.
https://sing-box.sagernet.org/configuration/inbound/naive/

I would appreciate any information from you.

note1:
The Sign-box installation followed the steps below.
https://sing-box.sagernet.org/examples/linux-server-installation/
(CENTOS 7.9) 

note:2:
Shadowsocks worked fine with this setting.
`   "type": "shadowsocks",
`

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here

Environment: go1.20.4 linux/amd64
Tags: with_quic,with_wireguard,with_acme
Revision: c74d3a53d41b0e8586257a2a1071faf394d1ed2f
CGO: enabled
```
</details>

### Server and client configuration file

<details>

```console
# paste json here
{
  "type": "naive",
  "tag": "naive-in",
  "network": "udp",
  "listen": "::",
  "listen_port": 8080,
  "tcp_fast_open": false,
  "udp_fragment": false,
  "sniff": false,
  "sniff_override_destination": false,
  "sniff_timeout": "300ms",
  "domain_strategy": "prefer_ipv6",
  "udp_timeout": 300,
  "proxy_protocol": false,
  "proxy_protocol_accept_no_header": false,
  "detour": "another-in",
  "users": [
    {
      "username": "user",
      "password": "pass"
    }
  ],
  "tls": {}
}

#Since the error occurs before client connection, client settings are omitted.
```

</details>

### Server and client log file

<details>

```console
# paste log here
Comamnd and results...

sing-box format -w
FATAL[0000] decode config at config.json: json: unknown field "type"

sing-box check
FATAL[0000] decode config at config.json: json: unknown field "type"

```
</details>

**Comment by Ricardo-Evans** [comment]
It seems you misunderstand the config format. See [configuration](http://sing-box.sagernet.org/configuration/) for the config format. The naive inbound should be an item of field "inbounds".

**Comment by mshigemoto** [comment]
Thank you for your replay.
I will ceck and try.

Thank you again

**Comment by Morrigan-Ship** [comment]
same problem
my config.json:

{
  "type": "vless",
  "tag": "vless-out",

  "server": "127.0.0.1",
  "server_port": 1080,
  "uuid": "cef727eb-b587-457b-bf89-1dcb3f6e3e8f",
  "flow": "xtls-rprx-vision",
  "network": "tcp",
  "tls": {},
  "packet_encoding": "",
  "multiplex": {},
  "transport": {}

}
