### ISSUE TITLE
issue about user UUID privacy

### ISSUE THREAD

**Issue by epsilonzeio** [SagerNet/sing-box#642]
Hi,
I'm using Hiddify panel with singbox core as i'ts mentioned as one of the verified Web panels in Xcore main page repository.
But I faced an issue in my panel logs realizing that for each user& the UUID info is sent to a Hiddify automatic email. Please check the screenshots as below.

https://ibb.co/WfNCBxR
https://ibb.co/198nLtr
https://ibb.co/X7g43s3

As proxy webpanel is your field profession just want to be sure if is there any security or privacy issue about that.
It felt a warning about this issue.

**Comment by nekohasekai** [comment]
If the protocol does not use TLS or WireGuard, all transmissions can be decrypted with the UUID.

**Comment by epsilonzeio** [comment]
many thanks for your answer.
