### ISSUE TITLE
请问能否考虑在sfa编译选项中增加DHCP吗？

### ISSUE THREAD

**Issue by charliez0** [SagerNet/sing-box#647]

**Comment by charliez0** [comment]
安卓端还不能用，有权限问题

**Comment by charliez0** [comment]
dhcp: prepare inferface: route ip+net: netlinkrib: permission denied

@nekohasekai

**Comment by nekohasekai** [comment]
netlink socket is banned by Google since Android 11.

**Comment by nekohasekai** [comment]
现在您可以转而使用 `local` DNS transport，它应该正常使用系统 DNS （Build 34）。

https://install.appcenter.ms/users/nekohasekai/apps/sfa/distribution_groups/publictest

**Comment by charliez0** [comment]
解决了，谢谢

**Comment by sinoon** [comment]
> 现在您可以转而使用 `local` DNS transport，它应该正常使用系统 DNS （Build 34）。
> 
> https://install.appcenter.ms/users/nekohasekai/apps/sfa/distribution_groups/publictest

我现在在 android 上用的就 local，但是这个选项在 mac 上不能用，会无法解析内网地址，需要 dhcp 才行
