### ISSUE TITLE
utls in iran

### ISSUE THREAD

**Issue by realartin** [SagerNet/sing-box#652]
hi there 
tnx for your great work 

according to this tweet 
 [https://twitter.com/uo0sef/status/1668080992052027392?t=cNSQWkDTozhMT9QVOaOHUg&s=19]()

there is an experiment done by uosof that proves dpi in iran can define utls sign packages !

please if it possible make a way for iranian folks that really need your help ❤️🙏

**Comment by JohnSirous** [comment]
> hi there tnx for your great work
> 
> according to this tweet https://twitter.com/uo0sef/status/1668080992052027392?t=cNSQWkDTozhMT9QVOaOHUg&s=19
> 
> there is an experiment done by uosof that proves dpi in iran can define utls sign packages !
> 
> please if it possible make a way for iranian folks that really need your help ❤️🙏

Hi realartin
utls is a package that different from sing-box.
based on sing-box docs, it's effect may be unproven.
![image](https://github.com/SagerNet/sing-box/assets/115221409/a7a1f37b-513c-40c8-b53b-7e3fd45a1846)
