### ISSUE TITLE
sing-box 站群多ip如何搭socks5源进源出？

### ISSUE THREAD

**Issue by 1247004718** [SagerNet/sing-box#653]
有一台站群服务有62个IP地址，比如：
123.123.123.1
123.123.123.2
.......
123.123.123.62

用sing-box如何搭建多ip socks5，即实现
socks5代理从123.123.123.1进来，也从123.123.123.1返回，123.123.123.2进来，也从123.123.123.2返回。以此类推，用v2ray 实现比较简单，但是sing-box 没有发现有相关的案例。

**Comment by SafaSafari** [comment]
Write a simple python script and with for loop crate json object and finally write it to config.json file =)))

**Comment by binyangzheng** [comment]
我也遇到这样的问题，比如一个机器有IP1、IP2、IP3，如果客户端连哪个，最终都是用ip1去连接目的地
