### ISSUE TITLE
sing-box产生僵尸进程

### ISSUE THREAD

**Issue by charliez0** [SagerNet/sing-box#657]
![image](https://github.com/SagerNet/sing-box/assets/20507989/da7aa8c5-0ab4-4705-8d6d-5a8a5ed2260a)
![image](https://github.com/SagerNet/sing-box/assets/20507989/3ff6cb25-565e-499e-9abc-babc864057b3)

**Comment by zakuwaki** [comment]
最后一张图是把grep给算进去了吧

**Comment by zakuwaki** [comment]
试试`ps aux | grep <PID> | grep -v grep`

**Comment by charliez0** [comment]
> 最后一张图是把grep给算进去了吧

是算进去了，但是不影响看到这是sing-box产生的进程啊

**Comment by charliez0** [comment]
@nekohasekai 最新的rc2问题仍然存在

**Comment by nekohasekai** [comment]
没看懂你在说什么
