### ISSUE TITLE
Suggestion: using yamux as default

### ISSUE THREAD

**Issue by zakuwaki** [SagerNet/sing-box#67]
When enabling multiplexing, `smux v1` is default method and will regularly cause a connection block.

This [topic](https://github.com/fatedier/frp/issues/2987) also discusses smux vs yamux. Maybe bandwidth usage is a key metric to proxy tool, but stable should also be considered.

This [comment](https://github.com/fatedier/frp/issues/2987#issuecomment-1225490802) analyze the reason and I overwrite the yamux default config by setting `MultiplexBufferSize = 16 * 1024 * 1024` and really have a good performance.
```go
func yaMuxConfig() *yamux.Config {
	config := yamux.DefaultConfig()
	config.LogOutput = io.Discard
	config.StreamCloseTimeout = C.TCPTimeout
	config.StreamOpenTimeout = C.TCPTimeout
	config.MaxStreamWindowSize = C.MultiplexBufferSize
	return config
}
```

**Comment by nekohasekai** [comment]
Reducing latency is a top priority for multiplexing in proxies.

yamux has greater latency and memory usage, while smux doesn't require connection or stream level buffers at all.

Also, the discussion you provided doesn't come from the project author and doesn't look right.

**Comment by zakuwaki** [comment]
Yes, the purpose of multiplexing is to decrease handshakes to reduce latency. However stability show also be considered.

The reason you mentioned why smux v1 is faster and memory saving (no connection/stream buffer)  is the basis cause of stream block, especially for connections over pacific. So, the author of smux developed v2 to handle this issue(introduce the same problem with yamux).

**Comment by nekohasekai** [comment]
Maybe your understanding of smux v2 is wrong, check the code.

Buffers over 64k are not acceptable. v2ray uses 4k and clash uses max 32k, they both work fine, the problem is in yamux.

**Comment by zakuwaki** [comment]
Gotcha, I'll read the code and try to understand it.
Thank you!

**Comment by ShervinR** [comment]
> Gotcha, I'll read the code and try to understand it. Thank you!

All three, Yamux, smux, and h2mux, are connection multiplexers, but they have some key differences:

Focus and Origin:
Yamux (Yet another Multiplexer): Developed by Hashicorp, it's a general-purpose multiplexer for various applications. It's implemented in Go, Rust, JavaScript, and others.
smux (Simple MUltipleXing): A Go library designed for low memory usage, often used with the kcp-go library for reliable UDP connections.
h2mux (HTTP/2 Multiplexing): Built-in functionality of HTTP/2 protocol for multiplexing HTTP requests and responses over a single TCP connection.
Compatibility:
Yamux: Not compatible with HTTP/2.
smux: Protocol specific, primarily for kcp-go.
h2mux: Only works with HTTP/2 traffic.
Features:
Yamux: Offers features like bi-directional streams, server-side push, and flow control for efficient data management.
smux: Focuses on simplicity and low memory footprint. May have fewer features compared to Yamux.
h2mux: Designed for HTTP/2 specifically, optimized for web traffic with features like header compression.
Choosing the right one depends on your needs:

General multiplexing: Yamux is a good choice with its flexibility and features.
Low-memory applications: smux might be preferable for its lightweight design.
HTTP/2 traffic: h2mux is the clear choice as it's an integral part of the protocol.
