### ISSUE TITLE
服务的路由规则里没有DNS策略

### ISSUE THREAD

**Issue by toyo2333** [SagerNet/sing-box#670]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

我需要在服务的禁用回国流量，路由这样写，但是结果无效：
```
 "rules": [
      {
        "geoip": "cn",
        "outbound": "block"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      }
    ],
```

我客户端开启全局代理后，类似douban这样的网站，预期应该是无法打开。但事实上还是出站打开了。

我对比过Xray的服务的，如果配置方法是一样的，但如果要实现域名解析匹配ip规则，还需要加上

`domainStrategy": "IPIfNonMatch"`

这样才会进行域名解析后用ip去匹配      "geoip": "cn",

我想知道singbox该如何设置，我在配置文档种没有找到相关说明。

另外，singbox的配置文档中，对于“省缺”值（默认值）的说明很少，很多自动不知道如果不配置会是什么值，这个有计划改进么？

盼望回复解答！

谢谢

### Version of sing-box

最新

### Server and client configuration file

```
 "rules": [
      {
        "geoip": "cn",
        "outbound": "block"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      }
    ],
```

### Server and client log file

null

**Comment by toyo2333** [comment]
那geoip：cn这样的规则还有什么用？到底在哪个环节才会把域名解析为IP然后批评IP规则呢？

**Comment by KyonLi** [comment]
入站监听字段的`domain_strategy`可以在路由前解析成ip，不过这样的话域名规则是不是就没用了，还是有点迷
