### ISSUE TITLE
如何‘’更新‘服务端程序

### ISSUE THREAD

**Issue by toyo2333** [SagerNet/sing-box#671]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

我是通过小白脚本一键安装完成的服务的安装和配置，安装方式是git后编译然 安装。

我想知道我日后如果想升级版本，最简单的方法是怎样的？比如这样的方法：http://sing-box.sagernet.org/zh/examples/linux-server-installation/

是否会覆盖掉我之前的配置文件？我不希望覆盖掉我原来的config.json配置文件。我只是希望完成sing-box服务的程序的新版本更新

纯新手小白，盼望解答。

### Version of sing-box

最新

### Server and client configuration file

null

### Server and client log file

null

**Comment by yingziwu** [comment]
https://github.com/SagerNet/sing-box/blob/dev-next/release/local/update.sh

**Comment by yingziwu** [comment]
如果你是按照官方文档中的 [Linux 服务器安装](https://sing-box.sagernet.org/zh/examples/linux-server-installation/) 进行安装的，直接使用 [update.sh](https://github.com/SagerNet/sing-box/blob/dev-next/release/local/update.sh) 进行升级就OK。

如果你是使用一键脚本，那你就要读一读你使用的一键脚本中的安装逻辑，然后基于安装逻辑进行升级。

另外，不键议使用任何一键脚本安装代理软件，不安全（参见 [vpstoolbox 一键脚本上传用户密码事件](https://v2ex.com/t/928400)），难以维护，难以升级，总之问题多多。

直接使用 Docker 是更好的方案。
操作简单，宿主机只需要安装 docker、docker-compose ，然后放上配置文件（docker-compose.yml），再 docker-compose up -d 就一切完事；
安全性高，Docker自带隔离，即使软件有恶意行为也难以危害宿主机；
维护方便，只需要保存相关的配置文件即可。结合 watchtower 更可以实现软件的自动升级。

**Comment by toyo2333** [comment]
> 如果你是按照官方文档中的 [Linux 服务器安装](https://sing-box.sagernet.org/zh/examples/linux-server-installation/) 进行安装的，直接使用 [update.sh](https://github.com/SagerNet/sing-box/blob/dev-next/release/local/update.sh) 进行升级就OK。
> 
> 
> 
> 如果你是使用一键脚本，那你就要读一读你使用的一键脚本中的安装逻辑，然后基于安装逻辑进行升级。
> 
> 
> 
> 另外，不键议使用任何一键脚本安装代理软件，不安全（参见 [vpstoolbox 一键脚本上传用户密码事件](https://v2ex.com/t/928400)），难以维护，难以升级，总之问题多多。
> 
> 
> 
> 直接使用 Docker 是更好的方案。
> 
> 操作简单，宿主机只需要安装 docker、docker-compose ，然后放上配置文件（docker-compose.yml），再 docker-compose up -d 就一切完事；
> 
> 安全性高，Docker自带隔离，即使软件有恶意行为也难以危害宿主机；
> 
> 维护方便，只需要保存相关的配置文件即可。结合 watchtower 更可以实现软件的自动升级。
> 
> 
> 
> 

https://github.com/BoxXt/installReality/blob/main/installReality.sh 是这个。 它是编译的。所以我直接更换二进制文件是不是也可以？还是说该怎么搞？
