### ISSUE TITLE
zombie process.

### ISSUE THREAD

**Issue by bart3nder** [SagerNet/sing-box#680]
Hi!
After updating the core to latest version (1.3.0), I'm facing sing-box being zombie process and system wants to kill it.
```
$ ps -A -ostat,ppid | grep -e '[zZ]'| awk '{ print $2 }' | uniq | xargs ps -p
    PID TTY          TIME CMD
   2375 ?        00:00:00 sing-box  
``` 
EDIT: I'm using wireguard outbound, And I noticed it will make an interface in this update, And disabling the whole outbound would solve the zombie process issue.

**Comment by Atoii** [comment]
docker版本镜像什么时候更新啊
