### ISSUE TITLE
建议padding功能在服务端新增一个padding_force参数

### ISSUE THREAD

**Issue by liuhgiceblood** [SagerNet/sing-box#687]
当服务端配置好了后，基于安全的考虑，希望客户端使用h2mux的时候启用padding，这样能提高安全性，但是在客户端不启用同样能对接成功，这样就违反了服务端建设的初衷，因此建议服务端新增padding_force，默认可以为false，但是当设为true时，就要求客户端必须启用padding，这样保证客户端连接的安全性。
关键是不会因为客户端配置问题。gfw把我服务端封了。

**Comment by nekohasekai** [comment]
没有证据表明 GFW 应用基于 TLS in crypto 检测的封锁；另外，根据一项未发表的研究，现有协议的 padding 都不能有效降低连接在一种模型中的特征。
