### ISSUE TITLE
Feature Request: Can "lazy resolution of domain to IP when routing (like IPOnDemand & IPIfNonMatch in v2ray)" be added?

### ISSUE THREAD

**Issue by walkeronedge** [SagerNet/sing-box#693]
v2ray's [`domainStrategy: IPOnDemand` and `domainStrategy: IPIfNonMatch`](https://www.v2fly.org/config/routing.html#routingobject) allows lazy resolution to IP address when doing routing rules matching. It enables quicker connection establishment (when current connection is to a domain and matches only domain rules) while also broadening the applicability of IP-based rules.

- `IPIfNonMatch`: When the domain name does not match any domain-based rules, the domain name is resolved to an IP address for matching based on IP rules.
- `IPOnDemand`: When matching encounters any IP-based rule, immediately resolve the domain name to an IP address for matching.

Will this be planned?

**Comment by walkeronedge** [comment]
> I tried to add `IPOnDemand` (mainly for non-TUN usage)

For others seeing this, it's https://github.com/SagerNet/sing-box/pull/695 .

> 其他项目存在这样的逻辑的原因是解析后无法同时匹配域名与IP

Not the case with Clash: https://github.com/Dreamacro/clash/blob/24186a488a395e532b9379db3d26b7672e76ea68/tunnel/tunnel.go#L390-L399

> 这种仅仅在浏览器使用，本地解析一次用 IP 匹配服务器、还需要在远程使用域名匹配的扭曲需求

I still hold that this behaviour remains useful in practical settings, not beautiful though it may seem.

**Comment by nekohasekai** [comment]
> Not the case with Clash

与 V2Ray 相反，这是作为 fake-ip 的后果之一，因为Clash 没有连接域名探测。

> I still hold that this behaviour remains useful in practical settings

要匹配这样类型的人的需求，更好的选择是转换到其他应用程序。
