### ISSUE TITLE
Question: tag uniqueness & load balancing ?

### ISSUE THREAD

**Issue by luochen1990** [SagerNet/sing-box#698]
Hello, I find that the doc has'nt talked about the uniqueness of the `tag` field of `outbounds`,  I mean, is that possible to specify multiple outbounds with a same tag, and will that make them a **load balanced group** ?

**Comment by luochen1990** [comment]
I tried that and it failed with:

```
FATAL[0000] start service: outbound tag proxy duplicated
```

So, is there any solution for load balancing?

**Comment by luochen1990** [comment]
Could you please tell me, which issue is this duplicated with?    I have searched 'load balance' and 'lb' but nothing there.   hoping to follow the latest news, thanks.

**Comment by SanujaNS** [comment]
> Could you please tell me, which issue is this duplicated with? I have searched 'load balance' and 'lb' but nothing there. hoping to follow the latest news, thanks.

[Feature Request: Support load balancing #227](https://github.com/SagerNet/sing-box/issues/227)
