### ISSUE TITLE
how to use sing-box on android phone?

### ISSUE THREAD

**Issue by aa51513** [SagerNet/sing-box#71]
I download the file named "sing-box-1.0-android-arm64.tar.gz"
then I decompression the file ,and do not see any files ending with apk

I'm confused on how to use it, any pointers would be greatly appreciated

**Comment by nekohasekai** [comment]
Run the binary in termux.

**Comment by kingsman9413** [comment]
@nekohasekai do you have documentation on how to install on android?

**Comment by kingsman9413** [comment]
@nekohasekai I have installed it but don't know the uses

**Comment by reeceyng** [comment]
> @nekohasekai我已经安装了，但不知道用途 ![截图_2022-09-09-18-20-49-533_com termux](https://user-images.githubusercontent.com/94727017/189339154-99f5ef0b-82f6-4415-b77b-cee4d7250a98.jpg)

sudo ~/go/bin/sing-box run -c config.json

**Comment by kingsman9413** [comment]
> 

@reeceyng not working
![Uploading Screenshot_2022-09-12-23-05-50-032_com.termux.jpg…]()

**Comment by kingsman9413** [comment]
@reeceyng not working

![Screenshot_2022-09-12-23-05-50-032_com termux](https://user-images.githubusercontent.com/94727017/189724430-1ac4fe5b-71eb-4df5-a6ef-f8ed5bbaa8ed.jpg)
