### ISSUE TITLE
flymeos 无法正常拉起核心

### ISSUE THREAD

**Issue by PuerNya** [SagerNet/sing-box#715]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

使用命令 `sing-box run -D <work_dir> -c config.json` 运行核心时，会出现 `FATAL[0000] start service: read packages list: unexpected attribute`

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```
`sing-box version 1.3.1-beta.1-9d75385`

</details>

### Server and client configuration file

<details>

```console
# paste json here
```
```json
{
  "log": {
    "disabled": false,
    "level": "trace",
    "output": "./src/log/box.log",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "domesticDns",
        "address": "https://1.12.12.12/dns-query",
        "detour": "direct"
      }
    ],
    "rules": [],
    "final": "domesticDns",
    "strategy": "ipv4_only",
    "reverse_mapping": true
  },
  "inbounds": [
    {
      "tag": "tun",
      "type": "tun",
      "interface_name": "tun1",
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "auto_route": true,
      "strict_route": true,
      "stack": "system",
      "sniff": true
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "type": "direct"
    }
  ],
  "route": {
    "rules": [],
    "final": "direct",
    "auto_detect_interface": true,
    "find_process": true
  }
}
```
</details>

### Server and client log file

<details>

```console
# paste log here
```

`FATAL[0000] start service: read packages list: unexpected attribute`

</details>

**Comment by PuerNya** [comment]
这里贴一个从 `/data/system` 取出来的 `packages.xml`

[packages.zip](https://github.com/SagerNet/sing-box/files/12039543/packages.zip)

**Comment by xtdy508** [comment]
安卓13 （2023.6.1布丁）

**Comment by PuerNya** [comment]
> 提供 Android 版本

![Uploading IMG_20230714_094523_703.jpg…]()

**Comment by nekohasekai** [comment]
尝试最新版本。

**Comment by PuerNya** [comment]
> 尝试最新版本。

截止 1.3.1-rc.1-407cf68 仍然未修复

**Comment by nekohasekai** [comment]
可以认为该 OEM 破坏了该格式。由于没有源代码，不再处理该问题，请转而使用 SFA。
