### ISSUE TITLE
Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by hosseinkhojany** [SagerNet/sing-box#716]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [x] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

Network adapter interface not generating in windows 10 , 8 ,7 but it work correctly in windows 11

After the below error is printed, if you try again, singbox making the adapter successfully, but it takes about 15 seconds to print this error

SingBox FATAL[0016] start service: initialize inbound/tun[tun-in]: configure tun interface: Cannot create a file when that file already exists.

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.3-beta11

Environment: go1.20.3 windows/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_reality_server,with_clash_api
Revision: e02317a34851617c0eb2cb6634b4b62901aa04dc
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```console
# asdg
```

</details>

### Server and client log file

<details>

```console
# dsafsadg
```

</details>

**Comment by hosseinkhojany** [comment]
I tested on last major but have this issue

**Comment by hosseinkhojany** [comment]
I found a solution for this, changing the interface_name solves the problem, you just need to change the interface_name before starting the tunnel.

**Comment by Sp1ke47** [comment]
Same for most GUI clients using singbox as core like NekoRay and V2rayN. In some situations like startup after a former accidental quit, the previous network interface isn't removed automatically. Sometimes more restarts are needed do the trick.

**Comment by zhouxinghong** [comment]
> I found a solution for this, changing the interface_name solves the problem, you just need to change the interface_name before starting the tunnel.

May I ask which interface name needs to be modified, for example: V2rayN tool

**Comment by zhouxinghong** [comment]
This error occurs very frequently.

**Comment by Totoro-Li** [comment]
Any progress on this? More than 1 month and this issue gets reflected in all downstream proxy projects.

**Comment by hosseinkhojany** [comment]
interface_name in the singbox config
https://sing-box.sagernet.org/configuration/inbound/tun/#interface_name

**Comment by zhouxinghong** [comment]
> @zhouxinghong interface_name in the singbox config https://sing-box.sagernet.org/configuration/inbound/tun/#interface_name

Thank you very much! 👍

**Comment by Zhopeful88** [comment]
> @zhouxinghong interface_name in the singbox config https://sing-box.sagernet.org/configuration/inbound/tun/#interface_name

I can not find the config on sinbox folder,and it should be on the where folder?

**Comment by hosseinkhojany** [comment]
What client are you using?
@Zhopeful88

**Comment by Zhopeful88** [comment]
> What client are you using? @Zhopeful88

Windows /V2RyaN ，if not use the Tun，WhatsApp can not chat，if open the tun，WhatsApp was ok，but ins ， fb and other
many website can''t open，I test just amazon and other one could be open （had not test more）

**Comment by Zhopeful88** [comment]
> What client are you using? @Zhopeful88

I had find config.json files,but can't modification the name,like me change the name like the "***-tun1",but if I open the Tun model,the name will be changed the "****-tun"

**Comment by hosseinkhojany** [comment]
why not start singbox directly with cmd in windows ? 
singbox.exe run -c config.json

**Comment by Zhopeful88** [comment]
> 

Had test，this will appear on next time

**Comment by Zhopeful88** [comment]
> You have to change the interface_name each time If you are familiar with Python or any scripting language, you can easily write a program that automatically changes the interface_name every time.

I just have the VS IDE,but if I change the name on the congfig files ,Tun on TUN,the name will reset

**Comment by Zhopeful88** [comment]
> Same for most GUI clients using singbox as core like NekoRay and V2rayN. In some situations like startup after a former accidental quit, the previous network interface isn't removed automatically. Sometimes more restarts are needed do the trick.

Yes,I thinks so this,I had see on V2rayN github,the some one tell me add one remove function  when open TUN,check it first,if exist ,remove  it ,and open later,but the Devcon name was not consistent,I had not time to test it

**Comment by nekohasekai** [comment]
Since this is an issue caused by a third-party application, we will not discuss it any further.
