### ISSUE TITLE
打包ios库

### ISSUE THREAD

**Issue by llliu000** [SagerNet/sing-box#717]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

ios14及以下低版本的network extension内存限制15M，超过15M后VPN进程直接闪退
使用makefile命令直接打包

### Version of sing-box

latest

### Server and client configuration file

ssr

### Server and client log file

.

**Comment by nekohasekai** [comment]
我们没有提供对 iOS 15 以下的支持。如果您要开发商业 VPN，请招募相关专业人士；如果您用于开源软件，请考虑指导用户越狱以绕过该限制。
