### ISSUE TITLE
Build error after upgrading dependecies

### ISSUE THREAD

**Issue by z4x7k** [SagerNet/sing-box#724]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

Updating `https://github.com/caddyserver/certmagic` package to `v0.19.0` in `v1.3.1-rc.1` breaks ACME TLS package build with the following log message:

```txt
github.com/sagernet/sing-box@v1.3.1-rc.1/common/tls/acme.go:32:8: w.cfg.Unmanage undefined (type *certmagic.Config has no field or method Unmanage)
```

Also, as noted in the release notes of [`https://github.com/caddyserver/certmagic@v0.19.0`](https://github.com/caddyserver/certmagic/releases/tag/v0.19.0):

> Removed `Config.Unmanage()` since it does not actually rely on the config at all. Replaced with `Cache.RemoveManaged()`. Removing a managed cert from the cache stops maintenance.

### Version of sing-box

<details>

```console
$ sing-box version
Does not build
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by xeptore** [comment]
Closing due to #722.

**Comment by z4x7k** [comment]
Closing due to #722.
