### ISSUE TITLE
[功能需求] 希望sing-box的dns能让用户指定端口号

### ISSUE THREAD

**Issue by ximiTech** [SagerNet/sing-box#729]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

希望sing-box的dns能实现让用户指定端口号的功能，目前使用homeproxy感觉很不错，就差这个dns指定端口号的功能，希望能够实现(passwall和openclash都支持此功能)。

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```

</details>

1.3.3

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

not needed

### Server and client log file

<details>

```console
# paste log here
```

</details>

not needed

**Comment by liaoliaots** [comment]
- tcp://x.x.x.x:3305
- udp://x.x.x.x:3306
- tls://x.x.x.x:3307
- https://x.x.x.x:3308/dns-query
- quic://xxx.com:3309
- h3://x.x.x.x:3310/dns-query

**Comment by ximiTech** [comment]
> * tcp://x.x.x.x:3305
> * udp://x.x.x.x:3306
> * tls://x.x.x.x:3307
> * https://x.x.x.x:3308/dns-query
> * quic://xxx.com:3309
> * h3://x.x.x.x:3310/dns-query

Where are these configs from ?
It seems dns is not working with the port numbers ?
