### ISSUE TITLE
Feature Request: Add systemd socket activation / fd passing support for Linux

### ISSUE THREAD

**Issue by attrr** [SagerNet/sing-box#733]
Hi,
I use sing-box as a proxy server and listen on several privileged ports. However, this is currently only achievable via the `CAP_NET_BIND_SERVICE` capability.
It would be nice to have systemd socket activation support in sing-box, receive socket created by systemd, while sing-box itself runs without any capabilities. 
It is also easy to add Unix domain socket support via socket activation. At the same time, it makes the permission config of UDS less complicated. (Only need to change ownership of UDS to the client user. Instead of needs to be readable and writable by both server and client) And thus can solve https://github.com/SagerNet/sing-box/issues/320
In some not-so-common cases, 
Like running sing-box in a rootless container, it is typically impossible to listen on privileged ports without changing `net.ipv4.ip_unprivileged_port_start`, and this feature makes it possible. 
Or using sing-box as a forwarder to VPN, run both sing-box and VPN inside a netns to make default netns cleaner(you still need to deal with firewall and routing even run them in default netns, as vpn block other interfaces). With this feature, sing-box will still be able to receive traffic from physical interfaces of main netns while itself sitting in another netns, without adding veth or doing port forward within the firewall. It will save a lot of trouble.

**Comment by HEUDavid** [comment]
This feature is not yet completed? The code is not merged.

**Comment by Lstarc** [comment]
While TCP loopback is functional, adding UDS support would allow for tighter security (using file permissions) and slightly better performance for high-traffic server-side deployments where sing-box sits behind a reverse proxy like Nginx or HAProxy.
