### ISSUE TITLE
Feature Request：outbound add type: relay

### ISSUE THREAD

**Issue by July-Peel** [SagerNet/sing-box#736]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

看文档里好像出口类型不支持relay，能relay转发的话就非常棒，可以增加吗

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by CHIZI-0618** [comment]
建议仔细阅读文档
https://sing-box.sagernet.org/configuration/outbound 中的 Dial Fields 字段，
https://sing-box.sagernet.org/configuration/shared/dial/#detour

**Comment by jiz4oh** [comment]
Hi @CHIZI-0618  @nekohasekai 
![image](https://github.com/SagerNet/sing-box/assets/41264693/812875e9-4b8d-44eb-8562-b5e49144f072)
请问 selector 可以支持配置 detour 吗？如上图所示，这样可以自由选择 中转节点 和 落地节点
