### ISSUE TITLE
send an example ios client config

### ISSUE THREAD

**Issue by its0ka** [SagerNet/sing-box#738]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

im posting here because [comminity.sagernet.org](https://community.sagernet.org/) doesn't approve my post. If you don't like this, please don't lock as spam as this https://github.com/SagerNet/sing-box/issues/734#issuecomment-1653573922, just unsubscribe and let someone else help me.

can someone please give me an example config for ios app? i don't understand what inbound i should use. i tried TUN and Mixed.

### Version of sing-box

latest from app-store

### Server and client configuration file

mixed https://pastebin.com/MNXcRw40
tun https://pastebin.com/hU9JgiGk

### Server and client log file

<details>

![image](https://github.com/SagerNet/sing-box/assets/125186204/e36b76a0-f544-4b32-8a7a-9b965a414dfd)
![image](https://github.com/SagerNet/sing-box/assets/125186204/1338bd6e-2c90-4398-ab6d-d8755692a5c1)

</details>

**Comment by nekohasekai** [comment]
This is not the place to ask for free teaching.

**Comment by its0ka** [comment]
@nekohasekai i don't ask you, you already developed the app (which i can't even use), please open the issue and let **someone else** help me. unsubscribe and i will close the issue by myself

**Comment by its0ka** [comment]
@nekohasekai im 90% done to go online and you stop me right here, why?
