### ISSUE TITLE
 parse x509 key pair: tls: failed to find any PEM data in certificate input

### ISSUE THREAD

**Issue by kinsan2007** [SagerNet/sing-box#74]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

服务器端配置hysteria
自签证书，hysteria中运行正常
singbox显示
FATAL[0000] create service: parse inbound[0]: parse x509 key pair: tls: failed to find any PEM data in certificate input

### Version of sing-box

1.0

### Server and client configuration file

<details>
{
  "inbounds": [
    {
  "type": "hysteria",
  "tag": "hysteria-in",
  "listen": "::",
  "listen_port": 5353,
  "up": "100 Mbps",
  "down": "100 Mbps",
  "disable_mtu_discovery": false,
  "tls": {
    "enabled": true,
    "certificate": "/root/certificate.pem",
  "key": "/root/key.pem"
  }
    }
  ]
}
</details>

### Server and client log file

<details>

FATAL[0000] create service: parse inbound[0]: parse x509 key pair: tls: failed to find any PEM data in certificate input
root@racknerd-0d6900:~#

</details>

**Comment by lilarcor** [comment]
https://sing-box.sagernet.org/zh/configuration/shared/tls/ ， 这里的帮助里是不是把certificate和key移除比较好，否则让人疑惑
