### ISSUE TITLE
[Feature Request]: Optimize URL Test

### ISSUE THREAD

**Issue by hiddify1** [SagerNet/sing-box#752]
URL Test is working well however it consume battery since it test periodically the links particularly when we have a lot of outbounds.

It would be great if you can lazy test URL, which means do the test when receiving a request at time greater than the mentioned period. Therefore, it will not do not needed tests during the night, etc.

**Comment by nekohasekai** [comment]
If you use the official client and the device is idle (Android/iOS/macOS), URLTest will pause.
