### ISSUE TITLE
[Feature Request] Add an array in GEO IP and GEO site url 

### ISSUE THREAD

**Issue by hiddify1** [SagerNet/sing-box#753]
Since we are facing with uneven blocking of the internet, it would be great to have some fallback for geoip and geosite URLs.

Therefore, we can use github, and in case of failure, we can use some proxy to github.

**Comment by charliez0** [comment]
Good idea, by the way adding download retry count is also needed.

**Comment by hiddify1** [comment]
Currently, failure in downloading the geoIP file cause crash in running singbox which is so problematic
