### ISSUE TITLE
SOCKS5 UDP 问题

### ISSUE THREAD

**Issue by innocencefool** [SagerNet/sing-box#755]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

SOCKS5 UDP 会匹配到 geoip:private 路由规则，导致 UDP 都会从 geoip:private 规则配置的 outbound 出去。

### Version of sing-box

sing-box version 1.3.6

Environment: go1.20.6 windows/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_reality_server,with_clash_api
Revision: 09ffa2c66e6276fda5fcf3c16da142444a984458
CGO: disabled

### Server and client configuration file

```
{
  "log": {
    "disabled": false,
    "level": "debug"
  },
  "inbounds": [
    {
      "type": "mixed",
      "tag": "mixed",
      "listen": "0.0.0.0",
      "listen_port": 1080
    }
  ],
  "outbounds": [
    {
      "type": "trojan",
      "tag": "trojan",
      "server": "example.com",
      "server_port": 443,
      "password": "========================",
      "tls": {
        "enabled": true,
        "server_name": "example.com"
      },
      "multiplex": {
        "enabled": true,
        "protocol": "h2mux",
        "padding": true
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    }
  ],
  "route": {
    "rules": [
      {
        "geoip": [
          "private"
        ],
        "outbound": "direct"
      }
    ],
    "final": "trojan"
  }
}
```

### Server and client log file

INFO [4078623990 0ms] inbound/mixed[mixed]: inbound connection from 127.0.0.1:49608
INFO [4078623990 5ms] inbound/mixed[mixed]: inbound packet connection to 127.0.0.1:61608
DEBUG [4078623990 5ms] router: match[0] geoip=private => direct
INFO [4078623990 5ms] outbound/direct[direct]: outbound packet connection
DEBUG [4078623990 6.61s] inbound/mixed[mixed]: connection closed: process connection from 127.0.0.1:49608: upload: read udp 127.0.0.1:62182: use of closed network connection | download: read udp [::]:62183: use of closed network connection

**Comment by hiddify1** [comment]
add udp over tcp option

**Comment by innocencefool** [comment]
> add udp over tcp option

sing-box version 1.4.0-beta.1

Environment: go1.20.7 windows/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_reality_server,with_clash_api
Revision: cd44487ebcd2529af5ac0c77fe6a78b2f45fa99e
CGO: disabled

```
  "inbounds": [
    {
      "type": "mixed",
      "tag": "mixed",
      "listen": "0.0.0.0",
      "listen_port": 1080,
      "udp_over_tcp": {
        "enabled": true,
        "version": 2
      }
    }
  ],
```

FATAL[0000] decode config at sing-box.json: inbound options: json: unknown field "udp_over_tcp"
