### ISSUE TITLE
[Features Requests] add support fallback/fastest/parallel dns server

### ISSUE THREAD

**Issue by malikshi** [SagerNet/sing-box#758]
I had some cases with premium dns services, sometimes h3/doh/for not working at all I need changes manually to dot or even dns legacy(port 53). I hope sing-box support one of method I requested. Sometimes I am using dnsproxy instead of placing h3/doh in sing-box.
Reff: https://github.com/AdguardTeam/dnsproxy#usage

**Comment by megapro17** [comment]
why it's not planned? very useful feature. Will you accept a pull request with this? Also a selector with random dns server

**Comment by megapro17** [comment]
clash has it btw https://wiki.metacubex.one/en/config/dns/diagram/
