### ISSUE TITLE
Feature request: add utls fingerprint option for tls dialer

### ISSUE THREAD

**Issue by zakuwaki** [SagerNet/sing-box#76]
https://github.com/refraction-networking/utls

**Comment by nekohasekai** [comment]
utls is no longer maintained and the built-in signatures are old.

**Comment by zakuwaki** [comment]
I've noticed it has an update in recent days, it invokes me that it is alive or I'll miss too.
https://github.com/refraction-networking/utls/pull/116

**Comment by nekohasekai** [comment]
I think it still needs to be updated with the standard library to be widely available as a library.

**Comment by nekohasekai** [comment]
I'll consider if the dev-ech branch is eventually merged.
