### ISSUE TITLE
[Feature Request] Add UDP-over-TCP to SSH outbound

### ISSUE THREAD

**Issue by er888kh** [SagerNet/sing-box#766]
Hi!

I have written a small SSH server with a good user management interface (especially for integrating with other tools), [ssh-liberty-bridge](https://github.com/er888kh/ssh-liberty-bridge). It would be awesome if the project starts supporting UoT for use with custom SSH servers. Also, I highly appreciate any hints for how I can implement UoT using the `sing` project.

Thanks in advance

**Comment by nekohasekai** [comment]
SSH is an established specification, and was not designed for anti-censorship, you should not reinvent the protocol with its name.
