### ISSUE TITLE
软路由内使用tun模式局域网设备无法连接外网，请教如何配置

### ISSUE THREAD

**Issue by yvvw** [SagerNet/sing-box#767]
如题，我在软路由内创建了一个直连的配置如下，我希望此配置可以给局域网内设备提供网络服务，现在情况是

- 软路由内可以正常上网
- 局域网其它设备不能上网，dns查询可以返回ip，ping ip可以连通，使用wireshark检测设备连接信息，抱歉不是很懂这些数据怎么看，不过看正常连接的流量是绿色的，这个深色的看起来好像是连接不通
![image](https://github.com/SagerNet/sing-box/assets/15168529/a836cbe4-c51f-402a-bdb5-96b70b9ebce9)

路由表信息，里面有zerotier的设备，这些网络内的服务是可以访问的
![image](https://github.com/SagerNet/sing-box/assets/15168529/1d2584d4-9221-48e0-bdcb-ae61ef1c482a)

关掉sing-box后，局域网设备可以上网，我猜测是局域网流量无法进入tun设备或者是被丢弃了，但不清楚如何配置，麻烦大神指导下

```json
{
  "log": {
    "level": "info"
  },
  "dns": {
    "servers": [
      {
        "tag": "dns",
        "address": "223.5.5.5"
      }
    ]
  },
  "inbounds": [
    {
      "type": "tun",
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "strict_route": false,
      "sniff": true
    },
    {
      "type": "direct",
      "tag": "dns",
      "listen": "0.0.0.0",
      "listen_port": 53,
      "network": "udp"
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "inbound": "dns",
        "outbound": "dns-out"
      }
    ],
    "final": "direct",
    "auto_detect_interface": true
  }
}
```

**Comment by yvvw** [comment]
找到解决办法了，需要允许tun0设备转发才行

`iptables -D FORWARD -i tun0 -j ACCEPT`

**Comment by Alex-Joe-Lee** [comment]
> 找到解决办法了，需要允许tun0设备转发才行
> 
> `iptables -I FORWARD -o tun0 -j ACCEPT`

请教一下，在软路由上配置只需要如下2个步骤吗？
1.写好配置文件，启动sing-box.
2.执行iptables开启网口转发的命令.

**Comment by yvvw** [comment]
> 

我是在防火墙自定义规则里加了这两条就ok了，你可以用 nc 测试 tcp 连接
# sing-box
iptables -C input_rule -i tun0 -j ACCEPT > /dev/null 2>&1 || iptables -I input_rule -i tun0 -j ACCEPT
iptables -C forwarding_rule -o tun0 -j ACCEPT > /dev/null 2>&1 || iptables -I forwarding_rule -o tun0 -j ACCEPT
