### ISSUE TITLE
sing-box 支持 arm v5 的设备吗 ？ 

### ISSUE THREAD

**Issue by cary-sas** [SagerNet/sing-box#769]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

支持 arm v5 的设备吗？ 
我在 VPS 上尝试 交叉编译一个支持 arm v5 的二进制，但是编译出来的文件却无法在 arm v5 的设备上执行。 
我的编译命令如下：
`CGO_ENABLED=0 GOOS=linux  GOARM=5 GOARCH=arm  go build -o sing-box  -trimpath -ldflags "-s -w -buildid="`

放进设备后无法执行，

![image](https://github.com/SagerNet/sing-box/assets/61653855/5359f57d-3168-4575-8a87-27b52339d9a4)

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
1.3.6
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
NA
```
</details>

### Server and client log file

<details>

```console
# paste log here
line 1: syntax error: unexpected newline
```
</details>

**Comment by 471309682** [comment]
你成功了吗？我也是armv5设备不能用
