### ISSUE TITLE
iOS TestFlight Sing-Box 1.4.0 (11) 客户端无法每次都成功启动，需要重复启动多次，才可能成功启动一次

### ISSUE THREAD

**Issue by jklolixxs** [SagerNet/sing-box#772]
### Operating system

iOS

### System version

iOS 16.6 (20G75)

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

TestFlight Sing-box 1.4.0(11)

### Description

点击按钮开启Sing-Box，随机启动成功，大部分情况是点开始按钮，看日志，秒显示(log client closed) EOF

### Reproduction

已脱敏
{
  "log": {
    "disabled": false,
    "level": "info",
    "timestamp": true
  },
  "experimental": {
    "clash_api": {
      "external_controller": "127.0.0.1:9090",
      "store_selected": true
    }
  },
  "dns": {
    "servers": [
      { 
        "address": "tls://8.8.4.4",
        "tag": "dns-remote"
      },
      {
        "address": "h3://223.5.5.5/dns-query",
        "detour": "direct",
        "tag": "dns-direct"
      },
      {
        "address": "rcode://success",
        "tag": "dns-block"
      }
    ],
    "rules": [
      {
        "geosite": [
          "category-ads-all"
        ],
        "disable_cache": true,
        "server": "dns-block"
      },
      {
        "domain_suffix": [
          "appcenter.ms",
          "app-measurement.com",
          "firebase.io",
          "crashlytics.com",
          "google-analytics.com"
        ],
        "disable_cache": true,
        "server": "dns-block"
      },
      {
        "domain_suffix": [
          "googleapis.cn"
        ],
        "server": "dns-remote"
      },
      {
        "geosite": [
          "private",
          "cn"
        ],
        "server": "dns-direct"
      },
      {
        "outbound": [
          "any"
        ],
        "server": "dns-remote"
      }
    ]
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "sing-box",
      "stack": "gvisor",
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "strict_route": false,
      "sniff": true,
      "sniff_override_destination": true
    }
  ],
  "outbounds": [
    {
      "type": "selector",
      "tag": "✈️ Proxy",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "🪜 VLESS-Vision",
      "outbounds": [
        "VPS-Vision",
        "VPS-Vision-BackUp"
      ],
      "default": "VPS-Vision-BackUp"
    },
    {
      "type": "selector",
      "tag": "🪜 VLESS-Padding",
      "outbounds": [
        "VPS-Padding",
        "VPS-Padding-BackUp"
      ],
      "default": "VPS-Padding-BackUp"
    },
    {
      "type": "selector",
      "tag": "🪜 VLESS-Padding-CDN",
      "outbounds": [
        "VPS-VLESS-Padding-CDN",
        "VPS-VLESS-Padding-CDN-BackUp"
      ],
      "default": "VPS-VLESS-Padding-CDN-BackUp"
    },
    {
      "type": "selector",
      "tag": "🪜 VMESS-Padding-CDN",
      "outbounds": [
        "VPS-VMESS-Padding-CDN",
        "VPS-VMESS-Padding-CDN-BackUp"
      ],
      "default": "VPS-VMESS-Padding-CDN-BackUp"
    },
    {
      "type": "selector",
      "tag": "🪜 ShadowTLS-Padding",
      "outbounds": [
        "VPS-ShadowTLS",
        "VPS-ShadowTLS-BackUp"
      ],
      "default": "VPS-ShadowTLS-BackUp"
    },
    {
      "type": "selector",
      "tag": "🪜 Hysteria",
      "outbounds": [
        "VPS-Hysteria",
        "VPS-Hysteria-BackUp"
      ],
      "default": "VPS-Hysteria-BackUp"
    },
    {
      "type": "selector",
      "tag": "🪜 TUIC",
      "outbounds": [
        "VPS-TUIC",
        "VPS-TUIC-BackUp"
      ],
      "default": "VPS-TUIC-BackUp"
    },
    {
      "type": "selector",
      "tag": "✍️ My",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC"
      ]
    },
    {
      "type": "selector",
      "tag": "📱 Telegram",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "🎵 Spotify",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "📺 BiliBili",
      "outbounds": [
        "direct",
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "🖥 YouTube",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "🖥 Twitch",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "🎤 Discord",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "💃 TikTok",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "🎥 NETFLIX",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "🗣 Twitter",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "🤖 OpenAI",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "📚 Scholar",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "🍎 Apple",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急",
        "direct"
      ]
    },
    {
      "type": "selector",
      "tag": "📢 Google",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "Ⓜ️ Microsoft",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急",
        "direct"
      ]
    },
    {
      "type": "selector",
      "tag": "💳 PayPal",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急",
        "direct"
      ]
    },
    {
      "type": "selector",
      "tag": "💰 USDT",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "🎮 Game",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急",
        "direct"
      ]
    },
    {
      "type": "selector",
      "tag": "❇️ Nvidia",
      "outbounds": [
        "🪜 VLESS-Vision",
        "🪜 VLESS-Padding",
        "🪜 VLESS-Padding-CDN",
        "🪜 VMESS-Padding-CDN",
        "🪜 ShadowTLS-Padding",
        "🪜 Hysteria",
        "🪜 TUIC",
        "WARP-应急"
      ]
    },
    {
      "type": "selector",
      "tag": "🎯 direct",
      "outbounds": [
        "direct",
        "block",
        "✈️ Proxy"
      ],
      "default": "direct"
    },
    {
      "type": "selector",
      "tag": "🛑 block",
      "outbounds": [
        "block",
        "direct",
        "✈️ Proxy"
      ],
      "default": "block"
    },
    {
      "tag": "direct",
      "type": "direct"
    },
    {
      "tag": "block",
      "type": "block"
    },
    {
      "tag": "dns-out",
      "type": "dns"
    },
    {
      "type": "vless",
      "tag": "VPS-Vision",
      "server": "1.1.1.1",
      "server_port": 12345,
      "uuid": "uuid",
      "flow": "xtls-rprx-vision",
      "packet_encoding": "xudp",
      "tls": {
        "enabled": true,
        "server_name": "server_name",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "public_key",
          "short_id": "short_id"
        }
      }
    },
    {
      "type": "vless",
      "tag": "VPS-Vision-BackUp",
      "server": "1.1.1.1",
      "server_port": 12345,
      "uuid": "uuid",
      "flow": "xtls-rprx-vision",
      "packet_encoding": "xudp",
      "tls": {
        "enabled": true,
        "server_name": "server_name",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "public_key",
          "short_id": "short_id"
        }
      }
    },
    {
      "type": "vless",
      "tag": "VPS-Padding",
      "server": "1.1.1.1",
      "server_port": 12345,
      "uuid": "uuid",
      "flow": "",
      "packet_encoding": "xudp",
      "tls": {
        "enabled": true,
        "server_name": "server_name",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "public_key",
          "short_id": "short_id"
        }
      },
      "multiplex": {
        "enabled": true,
        "protocol": "h2mux",
        "max_connections":  16,
        "min_streams": 4,
        "padding": true
      }
    },
    {
      "type": "vless",
      "tag": "VPS-Padding-BackUp",
      "server": "1.1.1.1",
      "server_port": 12345,
      "uuid": "uuid",
      "flow": "",
      "packet_encoding": "xudp",
      "tls": {
        "enabled": true,
        "server_name": "server_name",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "public_key",
          "short_id": "short_id"
        }
      },
      "multiplex": {
        "enabled": true,
        "protocol": "h2mux",
        "max_connections":  16,
        "min_streams": 4,
        "padding": true
      }
    },
    {
      "type": "vless",
      "tag": "VPS-VLESS-Padding-CDN",
      "server": "1.1.1.1",
      "server_port": 2087,
      "uuid": "uuid",
      "flow": "",
      "packet_encoding": "xudp",
      "tls": {
        "enabled":true,
        "server_name":"server_name",
        "utls": {
          "enabled":true,
          "fingerprint":"chrome"
        }
      },
      "transport": {
        "type": "ws",
        "path": "path",
        "headers": {
          "Host": "server_name"
        },
        "max_early_data": 2048,
        "early_data_header_name": "Sec-WebSocket-Protocol"
      }
    },
    {
      "type": "vless",
      "tag": "VPS-VLESS-Padding-CDN-BackUp",
      "server": "1.1.1.1",
      "server_port": 8443,
      "uuid": "uuid",
      "flow": "",
      "packet_encoding": "xudp",
      "tls": {
        "enabled":true,
        "server_name":"server_name",
        "utls": {
          "enabled":true,
          "fingerprint":"chrome"
        }
      },
      "transport": {
        "type": "ws",
        "path": "path",
        "headers": {
          "Host": "server_name"
        },
        "max_early_data": 2048,
        "early_data_header_name": "Sec-WebSocket-Protocol"
      }
    },
    {
      "type":"vmess",
      "tag":"VPS-VMESS-Padding-CDN",
      "server":"1.1.1.1",
      "server_port":2087,
      "uuid":"uuid",
      "security":"auto",
      "alter_id":0,
      "packet_encoding": "xudp",
      "domain_strategy":"",
      "tls": {
        "enabled":true,
        "server_name":"server_name",
        "utls": {
          "enabled":true,
          "fingerprint":"chrome"
        }
      },
      "transport": {
        "type":"ws",
        "path":"path",
        "headers": {
          "Host": "server_name"
        },
        "max_early_data":2408,
        "early_data_header_name":"Sec-WebSocket-Protocol"
      },
      "multiplex": {
        "enabled":true,
        "protocol":"h2mux",
        "max_connections":32,
        "min_streams": 4,
        "padding":true
      }
    },
    {
      "type":"vmess",
      "tag":"VPS-VMESS-Padding-CDN-BackUp",
      "server":"1.1.1.1",
      "server_port":8443,
      "uuid":"uuid",
      "security":"auto",
      "alter_id":0,
      "packet_encoding": "xudp",
      "domain_strategy":"",
      "tls": {
        "enabled":true,
        "server_name":"server_name",
        "utls": {
          "enabled":true,
          "fingerprint":"chrome"
        }
      },
      "transport": {
        "type":"ws",
        "path":"path",
        "headers": {
          "Host": "server_name"
        },
        "max_early_data":2408,
        "early_data_header_name":"Sec-WebSocket-Protocol"
      },
      "multiplex": {
        "enabled":true,
        "protocol":"h2mux",
        "max_connections":32,
        "min_streams": 4,
        "padding":true
      }
    },
    {
      "type": "shadowsocks",
      "tag": "VPS-ShadowTLS",
      "method": "2022-blake3-aes-128-gcm",
      "password": "password",
      "detour": "VPS-Shadowsocks-OUT",
      "udp_over_tcp": {
        "enabled": true,
        "version": 2
      },
      "multiplex": {
        "enabled": true,
        "protocol": "h2mux",
        "max_connections":  16,
        "min_streams": 4,
        "padding": true
      }
    },
    {
      "type": "shadowtls",
      "tag": "VPS-Shadowsocks-OUT",
      "server": "1.1.1.1",
      "server_port": 12345,
      "version": 3,
      "password": "password",
      "tls": {
        "enabled": true,
        "server_name": "server_name",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      }
    },
    {
      "type": "shadowsocks",
      "tag": "VPS-ShadowTLS-BackUp",
      "method": "2022-blake3-aes-128-gcm",
      "password": "password",
      "detour": "VPS-Shadowsocks-BackUp-OUT",
      "udp_over_tcp": {
        "enabled": true,
        "version": 2
      },
      "multiplex": {
        "enabled": true,
        "protocol": "h2mux",
        "max_connections":  16,
        "min_streams": 4,
        "padding": true
      }
    },
    {
      "type": "shadowtls",
      "tag": "VPS-Shadowsocks-BackUp-OUT",
      "server": "1.1.1.1",
      "server_port": 12345,
      "version": 3,
      "password": "password",
      "tls": {
        "enabled": true,
        "server_name": "server_name",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      }
    },
    {
      "type": "hysteria",
      "tag": "VPS-Hysteria",
      "server": "1.1.1.1",
      "server_port": 12345,
      "up_mbps": 100,
      "down_mbps": 300,
      "obfs": "obfs",
      "auth_str": "auth_str",
      "tls": {
        "enabled": true,
        "server_name": "server_name",
        "alpn": [
          "h3"
        ]
      }
    },
    {
      "type": "hysteria",
      "tag": "VPS-Hysteria-BackUp",
      "server": "1.1.1.1",
      "server_port": 12345,
      "up_mbps": 100,
      "down_mbps": 300,
      "obfs": "obfs",
      "auth_str": "auth_str",
      "tls": {
        "enabled": true,
        "server_name": "server_name",
        "alpn": [
          "h3"
        ]
      }
    },
    {
      "type": "tuic",
      "tag": "VPS-TUIC",
      "server": "1.1.1.1",
      "server_port": 12345,
      "uuid": "uuid",
      "password": "password",
      "congestion_control": "bbr",
      "tls": {
        "enabled": true,
        "server_name": "server_name",
        "alpn": [
          "h3"
        ]
      }
    },
    {
      "type": "tuic",
      "tag": "VPS-TUIC-BackUp",
      "server": "1.1.1.1",
      "server_port": 12345,
      "uuid": "uuid",
      "password": "password",
      "congestion_control": "bbr",
      "tls": {
        "enabled": true,
        "server_name": "server_name",
        "alpn": [
          "h3"
        ]
      }
    },

    {
      "type": "wireguard",
      "tag": "WARP-应急",
      "server": "162.159.192.120",
      "server_port": 500,
      "local_address": [
        "172.16.0.2/32",
        "2606:4700:110:88da:d3ce:475:bacb:2ef3/128"
      ],
      "private_key": "WGoeUNN6EMTk9UzBISLYKaW77NjESeGckwL/u7+HJkQ=",
      "peer_public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
      "reserved":[138,161,24]
    }
  ],
  "route": {
    "geosite": {
      "download_url": "https://testingcf.jsdelivr.net/gh/soffchen/sing-geosite@release/geosite.db",
      "download_detour": "✈️ Proxy"
      },
    "geoip": {
      "download_url": "https://testingcf.jsdelivr.net/gh/soffchen/sing-geoip@release/geoip.db",
      "download_detour": "✈️ Proxy"
      },
    "rules": [
      {
        "port": [
          53
        ],
        "outbound": "dns-out"
      },
      {
        "inbound": [
          "dns-in"
        ],
        "outbound": "dns-out"
      },
      {
        "network": [
          "udp"
        ],
        "port": [
          443,
          3478,
          10000,
          19302,
          19305
        ],
        "outbound": "block"
      },
      {
        "domain_suffix": [
          "httpdns.bilivideo.com",
          "ourdvsss.com",
          "sentry.io"
        ],
        "outbound": "block"
      },
      {
        "ip_cidr": [
          "1.1.1.1/32"
        ],
        "outbound": "✍️ My"
      },
      {
        "domain_suffix": [
          "theporndude.com",
          "porndudecdn.com"
        ],
        "outbound": "✈️ Proxy"
      },
      {
        "domain_suffix": [
          "qiandurebo.com",
          "qianduzhibo.com"
        ],
        "outbound": "🎯 direct"
      },
      {
        "geosite": [
          "category-ads-all"
        ],
        "outbound": "block"
      },
      {
        "domain_suffix": [
          "appcenter.ms",
          "app-measurement.com",
          "firebase.io",
          "crashlytics.com",
          "google-analytics.com"
        ],
        "outbound": "block"
      },
      {
        "domain_suffix": [
          "googleapis.cn"
        ],
        "outbound": "✈️ Proxy"
      },
      {
        "geosite": [
          "category-ads-all"
        ],
        "outbound": "🛑 block"
      },
      {
        "geosite": [
          "bilibili"
        ],
        "outbound": "📺 BiliBili"
      },
      {
        "geosite": [
          "youtube"
        ],
        "outbound": "🖥 YouTube"
      },
      {
        "geosite": [
          "twitch"
        ],
        "outbound": "🖥 Twitch"
      },
      {
        "geosite": [
          "discord"
        ],
        "outbound": "🎤 Discord"
      },
      {
        "geosite": [
          "tiktok"
        ],
        "outbound": "💃 TikTok"
      },
      {
        "geosite": [
          "netflix"
        ],
        "outbound": "🎥 NETFLIX"
      },
      {
        "geosite": [
          "twitter"
        ],
        "outbound": "🗣 Twitter"
      },
      {
        "geosite": [
          "openai@ads"
        ],
        "outbound": "block"
      },
      {
        "geosite": [
          "openai"
        ],
        "outbound": "🤖 OpenAI"
      },
      {
        "geosite": [
          "category-scholar-!cn"
        ],
        "outbound": "📚 Scholar"
      },
      {
        "geosite": [
          "apple"
        ],
        "outbound": "🍎 Apple"
      },
      {
        "geosite": [
          "google"
        ],
        "outbound": "📢 Google"
      },
      {
        "geosite": [
          "microsoft"
        ],
        "outbound": "Ⓜ️ Microsoft"
      },
      {
        "geosite": [
          "paypal"
        ],
        "outbound": "💳 PayPal"
      },
      {
        "geosite": [
          "binance",
          "okx"
        ],
        "outbound": "💰 USDT"
      },
      {
        "geosite": [
          "steam",
          "epicgames",
          "ea",
          "ubisoft"
        ],
        "outbound": "🎮 Game"
      },
      {
        "geosite": [
          "nvidia"
        ],
        "outbound": "❇️ Nvidia"
      },
      {
        "geosite": [
          "geolocation-!cn",
          "tld-!cn"
        ],
        "outbound": "✈️ Proxy"
      },
      {
        "geosite": [
          "private",
          "cn"
        ],
        "outbound": "🎯 direct"
      },
      {
        "geoip": [
          "telegram"
        ],
        "outbound": "📱 Telegram"
      },
      {
        "geoip": [
          "netflix"
        ],
        "outbound": "🎥 NETFLIX"
      },
      {
        "geoip": [
          "google"
        ],
        "outbound": "📢 Google"
      },
      {
        "geoip": [
          "apple"
        ],
        "outbound": "🍎 Apple"
      },
      {
        "geoip": [
          "twitter"
        ],
        "outbound": "🗣 Twitter"
      },
      {
        "geoip": [
          "private",
          "cn"
        ],
        "outbound": "🎯 direct"
      }
    ],
    "final": "✈️ Proxy"
  }
}

### Logs

(packet-tunnel) log server started
INFO[0000] router: loaded geoip database: 259 codes
INFO[0000] router : loaded geosite database : 1416 codes
INFO[0000] router: updated default interface pdp_ip0,
index 4
(log client closed) EOF

**Comment by nekohasekai** [comment]
请检查 View Service Log，如果为空白，则为内存过大被杀死，请避免使用过大第三方 geosite

**Comment by jklolixxs** [comment]
破案了，是第三方geosite太大导致的，换回Sing-box官方提供的就好了
