### ISSUE TITLE
Support go1.21.0 

### ISSUE THREAD

**Issue by chenrui333** [SagerNet/sing-box#774]
👋 currently, there is some build issue with go1.21.0 as for the error shown below:

```
/Users/rui/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/sagernet/quic-go@v0.0.0-20230731012313-1327e4015111/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/sagernet/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
```

relates to https://github.com/Homebrew/homebrew-core/pull/134468

**Comment by nekohasekai** [comment]
We already support Go 1.21 in beta versions, since the new quic-go is not compatible with Go 1.18 and 1.19 with simple modifications, we will not bring it to the stable version.

**Comment by chenrui333** [comment]
> We already support Go 1.21 in beta versions, since the new quic-go is not compatible with Go 1.18 and 1.19 with simple modifications, we will not bring it to the stable version.

but go1.18 and go1.19 is already EOL? How can I pull the related changes to build with go1.21.0?

**Comment by nekohasekai** [comment]
No you can't, we support go 1.21 in the next minor release. It is absurd that homebrew requires all software to be able to compile under go 1.21 instead, just as they arrogantly modify the compilation parameters when compiling instead of using Makefile. If it doesn't support a fixed go version, just use the binaries from releases, like they do for closed source software.

**Comment by chenrui333** [comment]
> No you can't, we support go 1.21 in the next minor release. It is absurd that homebrew requires all software to be able to compile under go 1.21 instead, just as they arrogantly modify the compilation parameters when compiling instead of using Makefile.

it is pretty much the same as the other package managers.

**Comment by nekohasekai** [comment]
Go 1.21 is already supported in the latest code, so your issue can be closed.

Also, I think it's arrogant and unreasonable to arbitrarily change the compiler and compilation parameters of an open source project, and this is a redistribution. This behavior applies to the additional terms of the agreement of this project, so homebrew redistribution using the original name of this project may violate the license.
