### ISSUE TITLE
Add juicity support

### ISSUE THREAD

**Issue by degfw** [SagerNet/sing-box#788]
https://github.com/juicity/juicity

**Comment by rpwtinfo** [comment]
As Juicity 0.3.0 seems to be stable for a while. Could you please consider to add it? Thank you.

**Comment by rdgjiose** [comment]
Juicity's performance stands out among many proxy protocols. It belongs to the UDP protocol too. Moreover, It also has been steadily updating, recently the number of using it has risen. Could you please consider adding it? Thank you.
