### ISSUE TITLE
The acme module of the TUIC protocol cannot normally apply for a configuration certificate

### ISSUE THREAD

**Issue by TinrLin** [SagerNet/sing-box#795]
go install -v -tags \
with_quic,\
with_grpc,\
with_dhcp,\
with_wireguard,\
with_shadowsocksr,\
with_ech,\
with_utls,\
with_reality_server,\
with_acme,\
with_clash_api,\
with_v2ray_api,\
with_gvisor,\
with_lwip \
github.com/sagernet/sing-box/cmd/sing-box@v1.4.0-beta.6
Compile and install the sing-box1.40-beta.6 version

Server configuration file
{
  "log": {
    "disabled": false,
    "level": "info",
    "timestamp": true
  },
  "inbounds": [
    {
      "type": "tuic",
      "tag": "tuic-in",
      "listen": "::",
      "listen_port": 443, 
      "users": [
        {
          "uuid": "0029b306-4416-4080-be71-00258yyybea1",
          "password": "pass"
        }    
      ],
      "congestion_control": "bbr",
      "auth_timeout": "3s",
      "zero_rtt_handshake": false,
      "heartbeat": "10s",
      "tls": {
        "enabled": true,
        "alpn": ["h3"],
        "acme": {
          "domain": ["domain.com"],
          "data_directory": "/usr/local/etc/sing-box",
          "email": "email@gmail.com",
          "provider": "letsencrypt"
        } 
      }      	
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    }
  ]
}
The test configuration file has been stuck at started background certificate maintenance, and no acme-related files are generated in the /usr/local/etc/sing-box directory

log

 root@vultr:~# /usr/local/bin/sing-box run -c /usr/local/etc/sing-box/config.json
+0000 2023-08-21 01:15:56 INFO router: updated default interface enp1s0, index 2
+0000 2023-08-21 01:15:56 INFO inbound/tuic[tuic-in]: udp server started at [::]:443
+0000 2023-08-21 01:15:56 INFO sing-box started (0.00s)
1.6925805569405158e+09  info    maintenance     started background certificate maintenance      {"cache": "0xc0000e3900"}

**Comment by yv-code** [comment]
This bug still exists. I can consistently reproduce it in the latest stable version 1.5.4.
