### ISSUE TITLE
GUI for windows version

### ISSUE THREAD

**Issue by paolosezart** [SagerNet/sing-box#798]
I use singbox on android, a very convenient and multifunctional tool for proxying. I wanted to install it myself on windows 10. But after I downloaded it, I didn't find any GUI controls, just a command line interface. Are there any options to install GUI for windows version of this program?

**Comment by nekohasekai** [comment]
Yes, but there are some third-party VPN software with ads that use sing-box as core, but their technical level is very poor, not up to the basic level of software like Clash for Windows. I suggest you switch to macOS or make that missing software yourself: if you're technically solid and willing to contribute to the community, we're more than happy to help.

**Comment by unipoco** [comment]
[nekoray](https://github.com/MatsuriDayo/nekoray)
