### ISSUE TITLE
Shadowsocks relay doesn't work for me

### ISSUE THREAD

**Issue by reeceyng** [SagerNet/sing-box#8]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

I can both connect these 2 service. So i'm sure the basic config is good.
But when I add relay part like [relay-structure](https://sing-box.sagernet.org/configuration/inbound/shadowsocks/#relay-structure).
```
      "destinations": [
        {
          "server": "222.222.222.222",
          "server_port": 8080,
          "password": "HyVta+GNgKhpsrNUTNykQg=="
        }
```
I can't connect it.

VPS1 log
```
sing-box[10278]: INFO[0019] [211937545] inbound/shadowsocks[0]: inbound connection from [::ffff:my_local_ip]:6717
sing-box[10278]: ERROR[0019] [211937545] inbound/shadowsocks[0]: process connection from [::ffff:my_local_ip]:6717: shadowsocks: serve TCP from [::ffff:my_local_ip]:6717: invalid request
```
VPS2 have no log

### Version of sing-box

<details>

```console
$ sing-box --version
sing-box version nightly (go1.19 linux/amd64)

```

</details>

### Server and client configuration file

Server No.1
<details>

```
{       
  "inbounds": [
    { 
      "type": "shadowsocks",
      "listen": "::",
      "listen_port": 8089,
      "method": "2022-blake3-aes-128-gcm",
      "password": "TAxFqoWSEc0phlr3096a4w==",
      "destinations": [
        {
          "server": "222.222.222.222",
          "server_port": 8080,
          "password": "HyVta+GNgKhpsrNUTNykQg=="
        }
      ]
    }
  ]
}
```

</details>

Server No.2

<details>

```
{
  "inbounds": [
    {
      "type": "shadowsocks",
      "listen": "::",
      "listen_port": 8080,
      "method": "2022-blake3-aes-128-gcm",
      "password": "HyVta+GNgKhpsrNUTNykQg=="
    }
  ]
}
```

</details>

Client side
<details>

```
    {
      "type": "shadowsocks",
      "server": "111.111.111.111",
      "server_port": 8089,
      "method": "2022-blake3-aes-128-gcm",
      "password": "TAxFqoWSEc0phlr3096a4w=="
    }
```

</details>

**Comment by nekohasekai** [comment]
Check https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022 for references.

**Comment by nekohasekai** [comment]
Please don't abuse the bug tag.

**Comment by reeceyng** [comment]
> Check https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022 for references.

Thank you for your help! Sorry for using wrong tag. I will check the tags before asking questions.
I put colons between passwords in client config solved the problem.

    {
      "type": "shadowsocks",
      "server": "111.111.111.111",
      "server_port": 8089,
      "method": "2022-blake3-aes-128-gcm",
      "password": "TAxFqoWSEc0phlr3096a4w==:HyVta+GNgKhpsrNUTNykQg=="
    }
