### ISSUE TITLE
tuic协议入站无法探测协议

### ISSUE THREAD

**Issue by chowyuan1314** [SagerNet/sing-box#802]
### Operating system

Linux

### System version

Debian 10

### Installation type

Original sing-box Command Line

### Version

sing-box version 1.4.0-rc.1

Environment: go1.21.0 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_reality_server,with_clash_api
Revision: 376f5277429e74edb1a50c0e4cc747c21b1f7706
CGO: disabled

### Description

tuic入站，开启sniff后，在日志里看不到协议探测的信息。其他协议入站则可以正常探测。

### Reproduction

脱敏的入站配置：
{
            "type": "tuic",
            "tag": "tuic-in",
            "listen": "::",
            "listen_port": **,
            "sniff": true,
            "sniff_override_destination": false,
            "users": [
                {
                    "name": "**",
                    "uuid": "**",
                    "password": "**"
                }
            ],
            "congestion_control": "bbr",
            "tls": {
                "enabled": true,
                "server_name": "**",
                "alpn": [
                    "h3"
                ],
                "certificate_path": "**",
                "key_path": "**"
            }
        }

**Comment by nekohasekai** [comment]
应该已经修复
