### ISSUE TITLE
macos中sfi桌面端中tun模式下自定义路由未成功生效

### ISSUE THREAD

**Issue by ctermiii** [SagerNet/sing-box#805]
### Operating system

macOS

### System version

macos13

### Installation type

sing-box for macOS Graphical Client

### Version

<details>
```console
# Replace this line with the output
```
</details>

1.4.0-rc2  

### Description

开启tun模式(启用fakeip)，配置inet_route_address情况下，启动后添加了inet中地址路由到tun网卡，但是系统仍旧添加默认路由到了tun网卡；
在sing-box命令行模式下，运行结果同预期，只添加了inet中的地址路由到tun网卡，默认路由没有改动。

另：
在rc1及之前的版本中，tun模式(启用fakeip)，配置inet_route_address情况下sfi直接无法成功启动。

### Reproduction

在tun配置中增加inet4_route_address，如：
 198.18.0.0/16

### Logs

<details>
```console
# Replace this line with logs
```
</details>

**Comment by nekohasekai** [comment]
根据一些检查，该路由在一些设备上为 ifscope，在其余的设备上实际也并不户路由所有流量，请重新检查并按 issue template 打开新问题。
