### ISSUE TITLE
VLESS-XTLS-uTLS-REALITY在ios上通过chrome浏览器经常无法播放youtube视频。

### ISSUE THREAD

**Issue by chowyuan1314** [SagerNet/sing-box#807]
### Operating system

iOS

### System version

ios16.6

### Installation type

sing-box for iOS Graphical Client

### Version

1.4.0-rc.1

### Description

IOS上使用VLESS-XTLS-uTLS-REALITY，使用chrome或safari打开youtube网页版，经常遇到视频无法播放的问题，使用youtube客户端没问题。观察日志发现，每次无法播放视频时，客户端均会出现以下报错：
inbound/mixed[mixed- in]: connection closed: process connection from 127.0.0.1:50013: download: write tcp 127.0.0.1:7890- >127.0.0.1:50013: write: broken pipe

### Reproduction

服务端为sing- box 1.4.0-rc.1及1.4.0-rc.2，搭建VLESS-XTLS-uTLS-REALITY，IOS上运行SFI，使用chrome或safari打开youtube网页版，有很大概率遇到视频无法播放的问题。可排除线路质量问题。

**Comment by chowyuan1314** [comment]
猜测可能是服务端的问题，同一个服务器上用xray部署REALITY，用sfi当客户端，就没有这个问题，网页端播放youtube秒开。

**Comment by chika0801** [comment]
> 猜测可能是服务端的问题，同一个服务器上用xray部署REALITY，用sfi当客户端，就没有这个问题，手机网页端播放youtube秒开。

如果你这样做了对比测试，那么你要以多的服务端配置，别人才能帮你

**Comment by chowyuan1314** [comment]
服务端（部分）：
{
    "log": {
        "disabled": false,
        "level": "warn",
        "output": "box.log",
        "timestamp": true
    },
    "dns": {
        "servers": [
            {
                "address": "8.8.8.8"
            }
        ]
    },
    "inbounds": [
        {
            "type": "vless",
            "tag": "vless-in",
            "listen": "::",
            "listen_port": **,
            "tcp_fast_open": false,
            "sniff": true,
            "sniff_override_destination": false,
            "tcp_multi_path": true,
            "udp_fragment": false,
            "users": [
                {
                    "name": "**",
                    "uuid": "**",
                    "flow": "xtls-rprx-vision"
                }
            ],
            "tls": {
                "enabled": true,
                "server_name": "www.yahoo.com",
                "reality": {
                    "enabled": true,
                    "handshake": {
                        "server": "www.yahoo.com",
                        "server_port": 443
                    },
                    "private_key": "**",
                    "short_id": [
                        "**"
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "type": "direct",
            "tcp_fast_open": false,
            "tcp_multi_path": true,
            "udp_fragment": false,
            "tag": "direct-out"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        }
    ],
    "route": {
        "rules": [
            {
                "protocol": "dns",
                "outbound": "dns-out"
            },
            {
                "inbound": [
                    "vless-in"
                ],
                "outbound": "direct-out"
            }
        ]
    }
}

客户端（部分）：
{
    "log": {
        "level": "debug",
        "timestamp": true
    },
    "dns": {
        "servers": [
            {
                "tag": "alidns",
                "address": "223.5.5.5",
                "strategy": "prefer_ipv4",
                "detour": "🎯 直连"
            },
            {
                "tag": "alidoh-bing",
                "address": "https://dns.alidns.com/dns-query",
                "strategy": "prefer_ipv4",
                "address_resolver": "alidns",
                "detour": "🅱️ bing"
            },
            {
                "tag": "alidoh",
                "address": "https://dns.alidns.com/dns-query",
                "strategy": "prefer_ipv4",
                "address_resolver": "alidns",
                "detour": "🎯 直连"
            },
            {
                "tag": "googledns",
                "address": "tls://8.8.8.8",
                "strategy": "prefer_ipv4",
                "detour": "🚀 节点选择"
            },
            {
                "tag": "googledns-openai",
                "address": "tls://8.8.8.8",
                "strategy": "prefer_ipv4",
                "detour": "🇯🇵日本-tuic"
            }
        ],
        "rules": [
            {
                "clash_mode": "direct",
                "server": "alidoh"
            },
            {
                "outbound": [
                    "any"
                ],
                "server": "alidoh"
            },
            {
                "clash_mode": "GLOBAL",
                "server": "googledns"
            },
            {
                "geosite": [
                    "openai"
                ],
                "server": "googledns-openai"
            },
            {
                "geosite": [
                    "bing"
                ],
                "server": "alidoh-bing"
            },
            {
                "geosite": [
                    "gfw"
                ],
                "domain_suffix": [],
                "domain_keyword": [],
                "server": "googledns"
            }
        ],
        "independent_cache": false,
        "final": "alidoh"
    },
    "inbounds": [
        {
            "type": "mixed",
            "tag": "mixed-in",
            "listen": "127.0.0.1",
            "listen_port": 7890,
            "sniff": true,
            "sniff_override_destination": false,
            "domain_strategy": "prefer_ipv4",
            "set_system_proxy": false
        },
        {
            "type": "tun",
            "tag": "tun-in",
            "sniff": true,
            "sniff_override_destination": false,
            "inet4_address": "172.19.0.1/30",
            "auto_route": true,
            "stack": "gvisor",
            "platform": {
                "http_proxy": {
                    "enabled": true,
                    "server": "127.0.0.1",
                    "server_port": 7890
                }
            }
        }
    ],
    "outbounds": [
        {
            "type": "dns",
            "tag": "dns-out"
        },
        {
            "type": "direct",
            "tag": "🎯 直连"
        },
        {
            "type": "vless",
            "tag": "🇸🇬新加坡-vision",
            "server": "**",
            "server_port": **,
            "tcp_multi_path": true,
            "uuid": "**",
            "flow": "xtls-rprx-vision",
            "tls": {
                "enabled": true,
                "server_name": "www.yahoo.com",
                "utls": {
                    "enabled": true,
                    "fingerprint": "chrome"
                },
                "reality": {
                    "enabled": true,
                    "public_key": "**",
                    "short_id": "**"
                }
            }
        },
        {
            "type": "selector",
            "tag": "🚀 节点选择",
            "outbounds": [
                "🇺🇸洛杉矶-vless",
                "🇺🇸洛杉矶-vmess",
                "🇺🇸洛杉矶-hy",
                "🇺🇸洛杉矶-vision",
                "🇯🇵日本-vless",
                "🇯🇵日本-tuic",
                "🇸🇬新加坡-hy",
                "🇸🇬新加坡-vision",
                "🇸🇬新加坡-tuic"
            ],
            "default": "🇺🇸洛杉矶-vless"
        },
        {
            "type": "selector",
            "tag": "☁️ onedrive",
            "outbounds": [
                "🎯 直连",
                "🚀 节点选择"
            ],
            "default": "🚀 节点选择"
        },
        {
            "type": "selector",
            "tag": "🅱️ bing",
            "outbounds": [
                "🎯 直连",
                "🚀 节点选择"
            ],
            "default": "🚀 节点选择"
        },
        {
            "type": "block",
            "tag": "🚫 阻止"
        }
    ],
    "route": {
        "geoip": {
            "download_url": "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db",
            "download_detour": "🚀 节点选择"
        },
        "geosite": {
            "download_url": "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db",
            "download_detour": "🚀 节点选择"
        },
        "rules": [
            {
                "protocol": "dns",
                "outbound": "dns-out"
            },
            {
                "clash_mode": "direct",
                "outbound": "🎯 直连"
            },
            {
                "geosite": [
                    "bing"
                ],
                "outbound": "🅱️ bing"
            },
            {
                "geosite": [
                    "openai"
                ],
                "clash_mode": "rule",
                "outbound": "🇯🇵日本-vless"
            },
            {
                "geosite": [
                    "onedrive"
                ],
                "clash_mode": "rule",
                "outbound": "☁️ onedrive"
            },
            {
                "geosite": [
                    "gfw"
                ],
                "domain_suffix": [],
                "domain_keyword": [],
                "geoip": [
                    "telegram"
                ],
                "clash_mode": "rule",
                "outbound": "🚀 节点选择"
            },
            {
                "geosite": [
                    "cn",
                    "apple",
                    "microsoft",
                    "adobe",
                    "cloudflare"
                ],
                "domain_suffix": [],
                "domain_keyword": [],
                "clash_mode": "rule",
                "outbound": "🎯 直连"
            },
            {
                "geoip": [
                    "cn",
                    "private"
                ],
                "clash_mode": "rule",
                "outbound": "🎯 直连"
            },
            {
                "network": [
                    "udp"
                ],
                "port": [
                    123
                ],
                "clash_mode": "rule",
                "outbound": "🎯 直连"
            }
        ],
        "auto_detect_interface": true,
        "final": "🚀 节点选择"
    },
    "experimental": {
        "clash_api": {
            "external_controller": "127.0.0.1:9090",
            "store_selected": true,
            "store_fakeip": true,
            "external_ui": "dashboard"
        }
    }
}

反复测试过多次，只有在iOS设备上存在这个问题，测试的iOS设备为iPhone13 pro和iPhone 7 plus，iPad和Mac上均正常。
