### ISSUE TITLE
reality 这是啥情况

### ISSUE THREAD

**Issue by areyouokhaha** [SagerNet/sing-box#808]
### Operating system

Windows

### System version

1.4.0rc

### Installation type

Others

### If you are using a graphical client, please provide the version of the client.

nekoray

### Version

<details>
```console
# Replace this line with the output
```
</details>

### Description

inbound/vless[VLESS-Reality+Padding]: process connection from 112.97.81.92:55407: REALITY: processed invalid connection
出现此报错

### Reproduction

inbound/vless[VLESS-Reality+Padding]: process connection from 112.97.81.92:55407: REALITY: processed invalid connection

### Logs

<details>
```console
# Replace this line with logs
```
</details>+0000 2023-08-24 12:52:44 INFO dns: exchanged itunes.apple.com A e673.dsce9.akamaiedge.net. 20 IN A 23.208.8.24
+0000 2023-08-24 12:52:44 INFO [1768348863 0ms] inbound/tuic[tuic-in]: inbound connection to cp.cloudflare.com:80
+0000 2023-08-24 12:52:44 INFO [1768348863 0ms] outbound/direct[0]: outbound connection to cp.cloudflare.com:80
+0000 2023-08-24 12:52:44 INFO dns: exchanged cp.cloudflare.com AAAA cp.cloudflare.com. 300 IN AAAA 2606:4700::6810:85e5
+0000 2023-08-24 12:52:44 INFO dns: exchanged cp.cloudflare.com AAAA cp.cloudflare.com. 300 IN AAAA 2606:4700::6810:84e5
+0000 2023-08-24 12:52:44 INFO dns: exchanged cp.cloudflare.com A cp.cloudflare.com. 300 IN A 104.16.132.229
+0000 2023-08-24 12:52:44 INFO dns: exchanged cp.cloudflare.com A cp.cloudflare.com. 300 IN A 104.16.133.229
+0000 2023-08-24 12:52:45 INFO [3492378168 0ms] inbound/vless[VLESS-Reality+Padding]: inbound connection from 112.97.81.92:55407
+0000 2023-08-24 12:52:45 ERROR [2057047895 1.22s] inbound/vless[VLESS-Reality+Padding]: process connection from 112.97.81.92:55406: REALITY: processed invalid connection
+0000 2023-08-24 12:52:46 ERROR [3492378168 1.35s] inbound/vless[VLESS-Reality+Padding]: process connection from 112.97.81.92:55407: REALITY: processed invalid connection

**Comment by chika0801** [comment]
就是不通的意思。检查 REALITY 的几个因素。替换法排除。

**Comment by areyouokhaha** [comment]
> 就是不通的意思。检查 REALITY 的几个因素。替换法排除。

ERROR[0010] dns: exchange failed for test.steampowered.com. IN A: Post "https://8.8.8.8/dns-query":

**Comment by areyouokhaha** [comment]
> > > 就是不通的意思。检查 REALITY 的几个因素。替换法排除。
> > 
> > 
> > 我怀疑是跟我写的inbounds有关，我的inbounds里面有两个type类型，一个是tuic，另外个就是这个vless reality padding,tuic可以用，这个vless用不了，我的reality对过好多遍了，没发现有问题
> 
> 你要别人帮你，要你发配置，光打字只有过猜。

不好意思哈哈哈
{
    "log": {
    "disabled": false,  
    "level": "info", 
    "timestamp": true  
  },
  
  "dns": {
    "servers": [
      {
        "tag": "google",
        "address": "udp://8.8.8.8" 
      }
    ]
  },
 
  

  "inbounds": [
   {
      "type": "tuic",
      "tag": "tuic-in",
      "listen": "::",
      "listen_port": 12343,
      "sniff": false,
      "sniff_override_destination": false,
      "users": [
        {
          "name": "sb",
          "uuid": "66050798-7d8a-4fb5",
          "password": "888"
        }
      
      ],
      "congestion_control": "bbr",
      "auth_timeout": "3s",
      "zero_rtt_handshake": false,
      "heartbeat": "10s",
      "tls": {
        "enabled": true,
        "alpn": [ "h3" ],
        "certificate_path": "/etc/v2ray-agent/tls/xxx.cer",
        "key_path": "/etc/v2ray-agent/tls/xxx.key"
      }

      },
      {
      "type": "vless",
      "tag": "VLESS-Reality+Padding",
      "listen": "::",
      "listen_port": 18443, 
      "tcp_fast_open": true,
      "udp_fragment": true,
      "sniff": true,
      "sniff_override_destination": false,
      "users": [
        {
          "name": "singbox",
          "uuid": "6e0bf51e-8eb3-4564-a2cc-xxxx",
          "flow": ""
        }
      ],
      "tls": {
        "enabled": true,
        "server_name": "gateway.icloud.com",
        "reality": {
          "enabled": true,
          "handshake": {
            "server": "gateway.icloud.com",
            "server_port": 443
          },
          "private_key": "4KYvXAdTpTOGTPHyuUpcg1VaiMM-RqE0ckpDtdlNZm4",
          "short_id": [
          "3989c026"
          ]
        }
      }
    }
    ],

    "outbounds": [
        {
            "type": "direct",
	    "tag": "direct"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        }
    ],
    "route": {
        "rules": [
            {
                "protocol": "bittorrent",
                "outbound": "direct"
            }
        ]
    }

}

**Comment by chika0801** [comment]
看了你配置，TUIC没问题。REALITY的

这2个我不知道加了起不起作用，建议删了。
```
  "tcp_fast_open": true,
  "udp_fragment": true,
```

看你tag，客户端是你想要用Padding，服务端flow留空是正确的。我不确定是不是能配REALITY，普通TLS肯定能。

"gateway.icloud.com", 如果这个目标网址不行，再换其它的。
`  "tag": "VLESS-Reality+Padding",`

**Comment by chika0801** [comment]
如果你的REALITY配置是从来都没通过，建议自己调试，一直不通证明你这样组合是就是不行的。

建议你在这里 https://github.com/chika0801/sing-box-examples 选一组用得了，不是太懂自己乱试只能自己查错。

**Comment by areyouokhaha** [comment]
> 如果你的REALITY配置是从来都没通过，建议自己调试，一直不通证明你这样组合是就是不行的。
> 
> 建议你在这里 https://github.com/chika0801/sing-box-examples 选一组用得了，不是太懂自己乱试组合就只能自己查错。

谢谢，我想用这种组合的，不知道这样组合能不能用，xray那些都可以。

**Comment by areyouokhaha** [comment]
> 如果你的REALITY配置是从来都没通过，建议自己调试，一直不通证明你这样组合是就是不行的。
> 
> 建议你在这里 https://github.com/chika0801/sing-box-examples 选一组用得了，不是太懂自己乱试组合就只能自己查错。

另外我昨天用了另外一个人的脚本利用singbox搭建vless reality xtls 不是padding[另外台服务器] 但是搭完可以用，看了下他的脚本配置文件，上面跟我这个除了padding其他都一样，只有一个type 没写其他type，我怀疑是sinbox无法接受这种两个以上的类型组合，或者是说这种组合的模板不是这样写的？

**Comment by areyouokhaha** [comment]
> 看了你配置，TUIC没问题。REALITY的
> 
> 这2个我不知道加了起不起作用，建议删了。
> ```
>   "tcp_fast_open": true,
>   "udp_fragment": true,
> ```
> 
> 看你tag，客户端是你想要用Padding，服务端flow留空是正确的。我不确定是不是能配REALITY，普通TLS肯定能。
> 
> "gateway.icloud.com", 如果这个目标网址不行，再换其它的。
> `  "tag": "VLESS-Reality+Padding",`

解决了，把私钥和公钥看错了
