### ISSUE TITLE
hysteria出站无法使用udp协议的dns解析

### ISSUE THREAD

**Issue by chowyuan1314** [SagerNet/sing-box#814]
### Operating system

macOS

### System version

13.4.1 

### Installation type

Original sing-box Command Line

### Version

sing-box version 1.4.0-rc.3

Environment: go1.21.0 darwin/arm64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_reality_server,with_clash_api
Revision: 05669eaaadf46b9c2d4f09e58c09ecb473c97b01
CGO: disabled

### Description

hysteria出站使用udp协议的dns服务器解析报错，换成dot、doh都正常。其他协议也正常。

### Reproduction

客户端配置一个8.8.8.8的dns服务器，detour指向hy的出站，打开任意一个需要走代理出站的网站，均无法打开，sing-box做服务端及hysteria官方程序做服务端都有这个问题。具体报错见日志。

### Logs

客户端日志：
+0800 2023-08-28 16:51:03 INFO [3874692145 0ms] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:54094
+0800 2023-08-28 16:51:03 INFO [3874692145 0ms] inbound/mixed[mixed-in]: inbound connection to www.bing.com:443
+0800 2023-08-28 16:51:03 DEBUG [3874692145 0ms] router: sniffed protocol: tls, domain: www.bing.com
+0800 2023-08-28 16:51:03 DEBUG [3874692145 0ms] dns: lookup domain www.bing.com
+0800 2023-08-28 16:51:03 DEBUG [3874692145 0ms] dns: match[4] geosite=bing => googledns
+0800 2023-08-28 16:51:03 INFO outbound/hysteria[🇸🇬新加坡-hy]: outbound packet connection to 8.8.8.8:53
+0800 2023-08-28 16:51:03 INFO outbound/hysteria[🇸🇬新加坡-hy]: outbound packet connection to 8.8.8.8:53
+0800 2023-08-28 16:51:03 INFO outbound/hysteria[🇸🇬新加坡-hy]: outbound packet connection to 8.8.8.8:53
+0800 2023-08-28 16:51:03 INFO outbound/hysteria[🇸🇬新加坡-hy]: outbound packet connection to 8.8.8.8:53
+0800 2023-08-28 16:51:03 ERROR [3874692145 244ms] dns: lookup failed for www.bing.com: exchange4: invalid argument | exchange6: invalid argument
+0800 2023-08-28 16:51:03 ERROR [3874692145 244ms] inbound/mixed[mixed-in]: process connection from 127.0.0.1:54094: exchange4: invalid argument | exchange6: invalid argument

+0800 2023-08-28 16:52:14 INFO [3593527530 0ms] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:54199
+0800 2023-08-28 16:52:14 INFO [3593527530 0ms] inbound/mixed[mixed-in]: inbound connection to outlook.office365.com:443
+0800 2023-08-28 16:52:14 DEBUG [3593527530 1ms] router: sniffed protocol: tls, domain: outlook.office365.com
+0800 2023-08-28 16:52:14 DEBUG [3593527530 1ms] dns: lookup domain outlook.office365.com
+0800 2023-08-28 16:52:14 DEBUG [3593527530 1ms] dns: match[2] clash_mode=GLOBAL => googledns
+0800 2023-08-28 16:52:14 INFO outbound/hysteria[🇸🇬新加坡-hy]: outbound packet connection to 8.8.8.8:53
+0800 2023-08-28 16:52:14 INFO outbound/hysteria[🇸🇬新加坡-hy]: outbound packet connection to 8.8.8.8:53
+0800 2023-08-28 16:52:14 INFO outbound/hysteria[🇸🇬新加坡-hy]: outbound packet connection to 8.8.8.8:53
+0800 2023-08-28 16:52:14 INFO outbound/hysteria[🇸🇬新加坡-hy]: outbound packet connection to 8.8.8.8:53
+0800 2023-08-28 16:52:14 ERROR [3593527530 299ms] dns: lookup failed for outlook.office365.com: exchange4: invalid argument | exchange6: invalid argument
+0800 2023-08-28 16:52:14 ERROR [3593527530 299ms] inbound/mixed[mixed-in]: process connection from 127.0.0.1:54199: exchange4: invalid argument | exchange6: invalid argument

服务端日志：
+0800 2023-08-28 16:28:16 INFO [2795004915 1m56s] inbound/hysteria[hysteria-in]: inbound packet connection to 8.8.8.8:53
+0800 2023-08-28 16:28:16 INFO [2795004915 1m56s] inbound/hysteria[hysteria-in]: inbound packet connection to 8.8.8.8:53
+0800 2023-08-28 16:28:16 DEBUG [2795004915 1m56s] inbound/hysteria[hysteria-in]: connection closed: process stream from ****:8783: use of closed network connection

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/a96995a136a34633fce5a5a6eaffee91f4e10179
