### ISSUE TITLE
Windows系统从睡眠唤醒后sing-box内存占用极高

### ISSUE THREAD

**Issue by chowyuan1314** [SagerNet/sing-box#819]
### 操作系统

Windows

### 系统版本

Windows11

### 安装类型

sing-box 原始命令行程序

### 版本

1.4.0

### 描述

1.4.0版本在Windows上直接跑内核，系统从睡眠唤醒后的一瞬间，sing-box内存飙升，可达几个G，之前版本在Mac上也存在同样的问题，1.4.0版本上Mac此问题已修复，但Windows还存在这个问题。

### 重现方式

1.4.0版本sing-box在windows上跑内核，睡眠唤醒后内存占用可达几个G，如果不重启内核，在十分钟内内存会下降一些，但无法恢复正常运行的内存占用。

### 日志

<details>
```console
# 使用日志内容覆盖此行
```
</details>

**Comment by zhouxinghong** [comment]
@chowyuan1314 大佬您的内核是怎么用cmd 跑起来的，能不能给个教程，非常感谢！

**Comment by chowyuan1314** [comment]
> 你能尝试[ab9ee74](https://github.com/SagerNet/sing-box/commit/ab9ee7447a4e77daab3253d53821e0772ed59e52)吗？

[fa471a5](https://github.com/SagerNet/sing-box/commit/fa471a51ab3dec60213311a520fdd0d9d487daf7)编译arm64版本在虚拟机上验证是解决问题了，不知道amd64版本是不是也一样。不过我看日志，发现是在睡眠期间会不断重启sing-box来避免内存暴涨。之前版本我是自己写了个脚本，当从睡眠唤醒时重启sing-box，并把日志重命名归档到对应目录下。

**Comment by chowyuan1314** [comment]
> @chowyuan1314 大佬您的内核是怎么用cmd 跑起来的，能不能给个教程，非常感谢！

你可以参考这个https://github.com/chika0801/sing-box-examples 来尝试运行，我是注册为服务来实现开机以管理员权限运行并隐藏命令行窗口的，注册为服务后方便管理，自己写了一些简单的脚本来实现在线更新配置文件、日志定期按规则归档、服务按规则重启等逻辑。

**Comment by zhouxinghong** [comment]
@chowyuan1314  按照这个https://github.com/chika0801/sing-box-examples 完全启动不了 cmd 窗口一闪而过。

**Comment by nekohasekai** [comment]
尝试 https://github.com/SagerNet/sing-box/commit/1cb688c49cd285ec3082546198d42f0e0ec3f110

**Comment by nekohasekai** [comment]
我决定撤回这些更改，在没有网络时拒绝请求是错误的，除非有人贡献代码以检查 Windows 是否处在睡眠中，我不会对这种情况作出处理（macOS 的正确支持来自于平台特定的代码）。
