### ISSUE TITLE
missing supported outbound

### ISSUE THREAD

**Issue by BlackHorse151** [SagerNet/sing-box#830]
when I use shadowsocks obfs tls I always get an error response like this
ERROR [2777486739 5ms] inbound/tproxy[tproxy-in]: process connection from ip:port: missing supported outbound, closing connection
any solutions or suggestions?
or where can I see the source code that generates the error response?

**Comment by ouyeantai** [comment]
If it can be used normally, you can ignore it. This is because your outbound target server does not support UDP, but your local request does have a UDP request.

**Comment by BlackHorse151** [comment]
when i use it always no internet connection
