### ISSUE TITLE
how to use tun over local socks5

### ISSUE THREAD

**Issue by qy527145** [SagerNet/sing-box#831]
### 操作系统

Windows

### 系统版本

10

### 安装类型

sing-box 原始命令行程序

### 版本
<details>

4e22ac1a350f16cfc2f98e5289d232cb838d8bfc

```console
sing-box version 1.1.5

Environment: go1.20 windows/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: 4e22ac1a350f16cfc2f98e5289d232cb838d8bfc
CGO: disabled
```
</details>

### 描述

入站使用tun，出站使用本地socks5（例如：socks5://127.0.0.1:1080）无法正常工作（PS：使用非本机代理端口可以）

### 重现方式
<details>

本地PC无法直接访问互联网，而是通过某个局域网socks5代理实现外网访问，为了使某些不支持设置代理的应用程序通过代理联网，我使用了tun模式，以下是我简化后的配置文件：
```json
{
  "dns": {
    "servers": [
      {
        "tag": "remote",
        "address": "tcp://1.1.1.1",
        "detour": "proxy"
      }
    ]
  },
  "inbounds": [
    {
      "type": "tun",
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "strict_route": true,
      "stack": "gvisor"
    }
  ],
  "outbounds": [
    {
      "type": "socks",
      "tag": "proxy",
      "server": "192.168.1.**",
      "server_port": 1080
    },
    {
      "type": "dns",
      "tag": "dns_out"
    }
  ],
  "route": {
    "auto_detect_interface": true,
    "rules": [
      {
        "port": 53,
        "outbound": "dns_out"
      }
    ]
  }
}
```
现在我可以实现任意程序连接外网。
但是在某些场景下（比如说：fiddler抓包），我需要在局域网代理上游增加一个本地前置socks5代理端口，可以简化成我本机的某个端口映射到了局域网代理服务器（比如：我本机端口127.0.0.1:1080映射到了局域网代理端口192.168.1.xx:1080）。
此时，我需要使用tun模式over 127.0.0.1:1080，我尝试了在rules中加入进程条件，让相关代理程序走直连，但是貌似不能正常工作。
</details>

**Comment by KoinuDayo** [comment]
把本机的socks代理软件加入排除名单或者在路由中分流至直连
