### ISSUE TITLE
Request to support Cloak

### ISSUE THREAD

**Issue by piloer** [SagerNet/sing-box#837]
https://github.com/cbeuw/Cloak

**Comment by nekohasekai** [comment]
There are already enough TLS proxies in the sing-box, such protocols have so many problems that they no longer make sense for bypassing firewalls.

**Comment by JimmyHuang454** [comment]
我粗略地看了一下Cloak，貌似思路跟 JLS v2版是一样的，但需要进一步确认一些细节，比如说：握手之后是如何加密的？ Cloak的加密是跟ShadowTLS的思路一致的？

另外我看了一下commit的时间，早在2020年就开始了，这样的话 Cloak 应该是比 shadowTLS 还早（我之前未留意过Cloak）。

JLS v2版多做了很多东西，其实就只需认证一下Hello，什么加密、协议时序都交给TLS就行了。 Fake TLS 认证方法都差不多，REALITY还以 “使用AES-GCM” 为理由来指责我 “照抄” 。这样看来，REALITY 也“照抄”了Cloak

还有一个很关键的点，就是认证信息放在Client Hello的哪个地方；ShadowTLS 、REALITY、Cloak同根同源，都使用了 Session ID，这样就导致了，这些 Fake TLS 都无法替换真正的TLS；比如说 QUIC 就要求 Session ID 必须为 0。

Fake TLS 起码看起来要像一个TLS，比如说 0-RTT，先不说安不安全，RFC有这方面的规定，PSK可由服务器选择接受与否，他们都没处理这些细节。
