### ISSUE TITLE
开启 Tun 模式后 TCPing / TCP Traceroute 异常

### ISSUE THREAD

**Issue by Glucy-2** [SagerNet/sing-box#841]
### 操作系统

Linux

### 系统版本

Debian GNU/Linux trixie/sid x86_64

### 安装类型

其他

### 如果您使用图形客户端程序，请提供该程序版本。

NekoBox 3.19-2023-08-30

### 描述

TCPing 得到的时间极短：
![图片](https://github.com/SagerNet/sing-box/assets/53287753/7a9de234-0aba-4f09-872a-af864d75d564)

TCP Traceroute 只要一跳就到达目标且延迟极短：
![图片](https://github.com/SagerNet/sing-box/assets/53287753/9ad1e4c3-5078-4b72-a709-5a4a808c4587)

### 重现方式

1. 安装 NekoBox 3.19-2023-08-30 并选择 sing-box 作为核心
2. 连接一个服务器并开启 Tun 模式
3. 进行 TCPing 测试和 TCP Traceroute 测试

**Comment by nekohasekai** [comment]
是预期行为。

**Comment by Glucy-2** [comment]
没有方法能让 Tun 模式下的 TCPing / TCP Traceroute 正常工作吗？
