### ISSUE TITLE
Keep crashing

### ISSUE THREAD

**Issue by ars1364** [SagerNet/sing-box#847]
### Operating system

Android

### System version

8.1.0

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.5.0-beta.3-dc985ed9

### Version

<details>
```console
# Replace this line with the output
```
</details>

### Description

thanks for your app, but the app keep crashing in my phone.
I've downloaded from this link:
<https://github.com/SagerNet/sing-box/releases/download/v1.4.1/SFA-1.4.1-universal.apk> 
but after running the app immediately new update appeared and I downloaded the new one.
phone type and model: Huawei honor 8x (JSN-L22)
EMUI version: 8.2.0
Android version: 8.1.0
kernel version: 4.4.103
beside, no stderr.log file available in: /sdcard/Android/data/io.nekohasekai.sfa/files/stderr.log

### Reproduction

just open the app, import the setting and tap the start/play button.

### Logs

<details>
```console
# Replace this line with logs
```
</details>

**Comment by nekohasekai** [comment]
We fixed some bugs reported to Microsoft App Center, you can download the new version and check if the bug still occurs. If you continue to encounter crashes, you need to provide logcat and other information within your capacity, instead of such meaningless issues.
