### ISSUE TITLE
[Feature Request] using singbox on server side

### ISSUE THREAD

**Issue by smaznet** [SagerNet/sing-box#852]
hi there and thanks for this great project 

we want use singbox on server side because of more inbounds that supports but there's 
some missing features which is reason's we can't use on server side

1. dynamic user management 
2. no way to monitor user traffic usage
3. not important but no way to listen on unix socket (management of multi inbounds is easier and lower overhead behind nginx or etc)

### for dynamic user management there is some way 

1. API 
Adding 1 api to manage users add or delete from inbound (like v2ray)

2. http auth (i like it)
singbox sends a POST request to x endpoint with inbound tag,uuid,ip of user and if server respond 200 it's okay and caches response (like hysteria)

3. check directly from redis,mysql or etc for traffic and auth (like trojan-server)

**Comment by nekohasekai** [comment]
There isn't a meaningful standard for these things, and many use cases directly rely on or modify the original project. If you have some programming skills, it's easy to implement these according to your own needs, rather than asking the open source community to serve the black industry.
