### ISSUE TITLE
inbounds mixed-in 设置系统代理有问题

### ISSUE THREAD

**Issue by IAMJ** [SagerNet/sing-box#855]
### Operating system

macOS

### System version

13.5.1

### Installation type

sing-box for macOS Graphical Client

### Version

<details>
```console
# Replace this line with the output
```
</details>

### Description

入站 `"tag": "mixed-in"` 且 `"set_system_proxy": true` ，会把系统代理设置为：
![001](https://github.com/SagerNet/sing-box/assets/2928760/dafc6bfc-cf8c-4104-986e-c2e8176ef87a)
这样会导致safari无法打开网页

正确设置如下：
![002](https://github.com/SagerNet/sing-box/assets/2928760/999d5b5f-d961-4b5f-90e1-081a9f3ded57)

### Reproduction

入站设置如下：

```
"inbounds": [
    {
      "type": "mixed",
      "tag": "mixed-in",
      "listen": "127.0.0.1",
      "listen_port": 7890,
      "sniff": true,
      "set_system_proxy": true,
      "sniff_override_destination": false,
      "domain_strategy": "ipv4_only"
    }
  ]
```

### Logs

<details>
```console
# Replace this line with logs
```
</details>

**Comment by nekohasekai** [comment]
尝试最新 commit。另外，推荐所有图形客户端用户使用 tun + platform HTTP proxy 的组合（可以在图形界面开关 HTTP
 代理）。

**Comment by IAMJ** [comment]
beta5 已验证无问题
