### ISSUE TITLE
hy2 crashes

### ISSUE THREAD

**Issue by aligoldenhat** [SagerNet/sing-box#856]
### Operating system

Linux

### System version

debian

### Installation type

Original sing-box Command Line

### Version

<details>
sing-box version 1.5.0-beta.4

Environment: go1.21.0 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_apiRevision: 2aa2320270104a4c998a1122c051517efc3b983b
CGO: disabled
</details>

### Description

i am using hy2 on sing-box core on both server and client 
after i use it several times 
it crashes when i think several connections are established
or sometime it doesnt crash But the download speed does not exceed 3 Mbps and after that i cant use hy2

### Reproduction

server :

> {
          "type": "hysteria2",
          "tag": "hy2-in",
          "listen": "::",
          "listen_port": ,
          "up_mbps": 150,
          "down_mbps": 150,
          "sniff": true,
          "masquerade": "",
          "obfs": {
                    "type": "salamander",
                    "password": "cry_with_me"
                  },
          "users": [
            {
              "name": "main",
              "password": "temp"
            }
          ],
          "tls": {
                        "enabled": true,
                        "certificate_path": "/root/ca.crt",
                        "key_path": "/root/ca.key"
                 }
    },

client:

> {
           "type": "hysteria2",
           "tag": "hy2-out",
           "server": "",
           "server_port": ,
           "up_mbps": 150,
           "down_mbps": 150,
           "obfs": {
                     "type": "salamander",
                     "password": "cry_with_me"
                   },
           "password": "temp",
           "tls": {
                 "enabled": true,
                 "server_name": "www.speedtest.net",
                 "insecure": true
             }
         },

journalctl when sing-box crashed:
![Screenshot from 2023-09-07 13-18-24](https://github.com/SagerNet/sing-box/assets/62204940/b9137841-269f-4244-9631-c95435433377)

### Logs

<details>
```console
# Replace this line with logs
```
</details>

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/3002292406aae5bfd5e74b807f2817899143bbc0
