### ISSUE TITLE
DNS 

### ISSUE THREAD

**Issue by yuumimi** [SagerNet/sing-box#86]
一个局域网下的 2 台设备，IP 分别为 192.168.1.2 和 192.168.1.5 。两台使用同样的配置文件，曾经同时运行过 sing-box (作为网关)。
现在 192.168.1.5 正常，192.168.1.2 总是会尝试连接到 192.168.1.5 的 DNS。

我做了以下操作仍然有问题：

> 两设备同时重装过系统，测试时只开了 192.168.1.2
> 重启过路由器
> 重启过虚拟机环境
> 修改过配置文件的10几种参数（各种tag、IP等）

root@tunnel:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether 00:0c:29:09:de:23 brd ff:ff:ff:ff:ff:ff
    altname enp11s0
    inet **192.168.1.2/24** brd 192.168.1.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 240e:390:7806:d7f0:20c:29ff:fe09:de23/64 scope global dynamic mngtmpaddr
       valid_lft 259200sec preferred_lft 172800sec
    inet6 fe80::20c:29ff:fe09:de23/64 scope link
       valid_lft forever preferred_lft forever
root@tunnel:~# ./sing-box run
INFO[0000] router: loaded geoip database: 1 codes
INFO[0000] router: loaded geosite database: 1260 codes
INFO[0000] router: updated default interface ens192, index 2
INFO[0000] inbound/tun[tun-in]: started at tun0
INFO[0000] inbound/mixed[mixed-in]: tcp server started at [::]:1080
INFO[0000] clash-api: restful api listening at [::]:9090
INFO[0000] sing-box started (0.344s)
INFO[0003] [1223400112] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:48073
INFO[0003] [1223400112] inbound/tun[tun-in]: inbound packet connection to **192.168.1.5:53**
INFO[0003] outbound/shadowsocks[CN2SS]: outbound multiplex connection to 8.8.8.8:853
INFO[0004] outbound/shadowsocks[CN2SS]: outbound multiplex connection to 8.8.8.8:853
INFO[0005] outbound/shadowsocks[CN2SS]: outbound multiplex connection to 8.8.8.8:853
ERROR[0006] [1223400112] dns: exchange failed for 0.debian.pool.ntp.org.: read tcp 192.168.1.2:53602->*.*.*.*:4443: read: connection reset by peer
INFO[0008] outbound/shadowsocks[CN2SS]: outbound multiplex connection to 8.8.8.8:853
INFO[0009] outbound/shadowsocks[CN2SS]: outbound multiplex connection to 8.8.8.8:853
INFO[0010] outbound/shadowsocks[CN2SS]: outbound multiplex connection to 8.8.8.8:853
ERROR[0011] [1223400112] dns: exchange failed for 0.debian.pool.ntp.org.: read tcp 192.168.1.2:53628->*.*.*.*:4443: read: connection reset by peer
INFO[0013] [3199036542] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:57118
INFO[0013] [3199036542] inbound/tun[tun-in]: inbound packet connection to **192.168.1.5:53**
INFO[0013] outbound/shadowsocks[CN2SS]: outbound multiplex connection to 8.8.8.8:853
INFO[0014] outbound/shadowsocks[CN2SS]: outbound multiplex connection to 8.8.8.8:853
INFO[0015] outbound/shadowsocks[CN2SS]: outbound multiplex connection to 8.8.8.8:853

**Comment by nekohasekai** [comment]
Not following template.

**Comment by yuumimi** [comment]
> Not following template.

同样的配置文件，在 192.168.1.5 上没问题。

现在重新复制了模板，只加了个节点，仍然连接到了 192.168.1.5
```
{
  "dns": {
    "servers": [
      {
        "tag": "google",
        "address": "tls://8.8.8.8"
      },
      {
        "tag": "local",
        "address": "223.5.5.5",
        "detour": "direct"
      }
    ],
    "rules": [
      {
        "domain": "mydomain.com",
        "geosite": "cn",
        "server": "local"
      }
    ],
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
      "type": "tun",
      "inet4_address": "172.19.0.1/30",
      "mtu": 9000,
      "auto_route": true,
      "strict_route": true,
      "stack": "gvisor",
      "sniff": true,
      "sniff_override_destination": true
    }
  ],
  "outbounds": [
    {
      "type": "shadowsocks",
      "tag": "CN2-SS",
      "tcp_fast_open": true,
      "method": "2022-blake3-aes-128-gcm",
      "password": "8JCsPssffS8tiRwiMlhARg==",
      "detour": "CN2-shadowtls",
      "multiplex": {
        "enabled": true,
        "max_connections": 4,
        "min_streams": 4
      }
    },
    {
      "type": "shadowtls",
      "tag": "CN2-shadowtls",
      "server": "myserver",
      "server_port": 4443,
      "tls": {
        "enabled": true,
        "server_name": "baidu.com"
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "geosite": "cn",
        "geoip": "cn",
        "outbound": "direct"
      }
    ],
    "auto_detect_interface": true
  }
}
```

日志：
```
root@tunnel:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether 00:0c:29:09:de:23 brd ff:ff:ff:ff:ff:ff
    altname enp11s0
    inet 192.168.1.2/24 brd 192.168.1.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 240e:390:7806:d7f0:20c:29ff:fe09:de23/64 scope global dynamic mngtmpaddr
       valid_lft 259185sec preferred_lft 172785sec
    inet6 fe80::20c:29ff:fe09:de23/64 scope link
       valid_lft forever preferred_lft forever
root@tunnel:~# ./sing-box run
INFO[0000] router: loaded geoip database: 1 codes
INFO[0000] router: loaded geosite database: 1260 codes
INFO[0000] router: updated default interface ens192, index 2
INFO[0000] inbound/tun[0]: started at tun0
INFO[0000] sing-box started (0.644s)
INFO[0002] [719507464] inbound/tun[0]: inbound packet connection from 172.19.0.1:58958
INFO[0002] [719507464] inbound/tun[0]: inbound packet connection to 192.168.1.5:53
DEBUG[0002] [719507464] router: sniffed packet protocol: dns
DEBUG[0002] [719507464] router: match[0] protocol=dns => dns-out
DEBUG[0002] [719507464] dns: exchange 2.debian.pool.ntp.org.tunnel.lan AAAA INET
DEBUG[0002] [719507464] dns: exchange 2.debian.pool.ntp.org.tunnel.lan A INET
INFO[0002] outbound/shadowsocks[CN2-SS]: outbound multiplex connection to 8.8.8.8:853
INFO[0003] outbound/shadowsocks[CN2-SS]: outbound multiplex connection to 8.8.8.8:853
INFO[0005] outbound/shadowsocks[CN2-SS]: outbound multiplex connection to 8.8.8.8:853
ERROR[0006] [719507464] dns: exchange failed for 2.debian.pool.ntp.org.tunnel.lan.: read tcp 192.168.1.2:44950->myserver:4443: read: connection reset by peer
DEBUG[0007] [719507464] dns: exchange 2.debian.pool.ntp.org.tunnel.lan AAAA INET
DEBUG[0007] [719507464] dns: exchange 2.debian.pool.ntp.org.tunnel.lan A INET
INFO[0007] outbound/shadowsocks[CN2-SS]: outbound multiplex connection to 8.8.8.8:853
INFO[0008] outbound/shadowsocks[CN2-SS]: outbound multiplex connection to 8.8.8.8:853
INFO[0010] outbound/shadowsocks[CN2-SS]: outbound multiplex connection to 8.8.8.8:853
ERROR[0011] [719507464] dns: exchange failed for 2.debian.pool.ntp.org.tunnel.lan.: read tcp 192.168.1.2:44960->myserver:4443: read: connection reset by peer
INFO[0012] [1932962955] inbound/tun[0]: inbound packet connection from 172.19.0.1:56845
INFO[0012] [1932962955] inbound/tun[0]: inbound packet connection to 192.168.1.5:53
DEBUG[0012] [1932962955] router: sniffed packet protocol: dns
DEBUG[0012] [1932962955] router: match[0] protocol=dns => dns-out
DEBUG[0012] [1932962955] dns: exchange 3.debian.pool.ntp.org AAAA INET
DEBUG[0012] [1932962955] dns: exchange 3.debian.pool.ntp.org A INET
INFO[0012] outbound/shadowsocks[CN2-SS]: outbound multiplex connection to 8.8.8.8:853
INFO[0013] outbound/shadowsocks[CN2-SS]: outbound multiplex connection to 8.8.8.8:853
INFO[0015] outbound/shadowsocks[CN2-SS]: outbound multiplex connection to 8.8.8.8:853
```

**Comment by yuumimi** [comment]
配置文件在没有使用 192.168.1.5 之前也是没问题的。
192.168.1.5 部署网关之后，192.168.1.2 就不行了。
