### ISSUE TITLE
默认dns服务器使用tuic协议节点出站，且dns规则设置outbound规则，会导致节点无法进行dns解析。

### ISSUE THREAD

**Issue by chowyuan1314** [SagerNet/sing-box#860]
### 操作系统

其他

### 系统版本

macOS、Windows、iOS等均涉及

### 安装类型

sing-box 原始命令行程序

### 版本

sing-box version 1.5.0-beta.5

Environment: go1.21.0 windows/arm64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api
Revision: 6030e65605c901fcb9b8c11f401ec8c00bcd574a
CGO: disabled

### 描述

#853 的后续
经过进一步验证，发现在以下特定配置下，会出现客户端无法进行dns解析（可能连节点的域名也没有解析），同时在命令行中使用nslookup会提示：
DNS request timed out.
timeout was 2 seconds.

### 重现方式

1、设置一个tuic协议的出站节点，保证节点能正常使用。（必须）
 ```
       {
            "type": "tuic",
            "tag": "tuic",
            "server": "***",
            "server_port": ***,
            "uuid": "***",
            "password": "***",
            "congestion_control": "bbr",
            "tls": {
                "enabled": true,
                "server_name": "***",
                "disable_sni": false
            }
        }
```
2、dns服务器detour设置为tuic出站的标签。（必须）
```
           {
                "tag": "googledns",
                "address": "tls://8.8.8.8",
                "strategy": "prefer_ipv4",
                "detour": "tuic"
            }
```
3、设置一个默认dns服务器的标签（非必须，如果不设置，则必须把步骤2中的dns服务器放在第一的位置。）
            `"final": "googledns"`
4、dns规则里设置outbound规则。（必须）
```
           {
                "outbound": "any",
                "server": "alidns"
            }
```
以上几点在配置时必须同时满足才会引发问题。

以下为能重现问题的最小客户端配置：
```
{
    "dns": {
        "servers": [
            {
                "tag": "googledns",
                "address": "tls://8.8.8.8",
                "strategy": "prefer_ipv4",
                "detour": "tuic"
            },
            {
                "tag": "alidns",
                "address": "223.5.5.5",
                "strategy": "prefer_ipv4",
                "detour": "直连"
            }
        ],
        "rules": [
            {
                "outbound": "any",
                "server": "alidns"
            }
        ],
        "final": "googledns",
        "independent_cache": false
    },
    "inbounds": [
        {
            "type": "tun",
            "tag": "tun-in",
            "sniff": true,
            "sniff_override_destination": false,
            "mtu": 9000,
            "inet4_address": "172.19.0.1/30",
            "auto_route": true,
            "stack": "system"
        }
    ],
    "outbounds": [
        {
            "type": "dns",
            "tag": "dns-out"
        },
        {
            "type": "direct",
            "tag": "直连"
        },
        {
            "type": "tuic",
            "tag": "tuic",
            "server": "***",
            "server_port": ***,
            "uuid": "***",
            "password": "***",
            "congestion_control": "bbr",
            "tls": {
                "enabled": true,
                "server_name": "***",
                "disable_sni": false
            }
        }
    ],
    "route": {
        "rules": [
            {
                "protocol": "dns",
                "outbound": "dns-out"
            }
        ],
        "auto_detect_interface": true,
        "final": "tuic"
    }
}
```

使用以上配置启动客户端，会出现无法进行dns解析的问题（应该是连节点服务器的域名也不会解析），如果有多个节点，则所有节点均无法进行dns解析。同时在客户端日志里没有任何报错，日志只会输出到请求了对应域名解析的位置。
若把dns规则里的outbound规则换成domain_suffix规则，配置上节点服务器的域名后缀，则问题解决。

### 日志

<details>
```console
# 使用日志内容覆盖此行
```
</details>

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/b1f289bce5d887b02103a69049a2992482205db8

**Comment by chowyuan1314** [comment]
> 尝试 1.5.0-beta.6

问题已修复！

**Comment by Qian119lsj** [comment]
请教个问题, dns规则里  
{
  "outbound": "any",
  "server": "alidns"
}
是不是代表所有dns请求都走alidns?如果是这样设置googledns有什么意义?如果不是那么"outbound": "any"代表什么含义?

**Comment by eurstein** [comment]
> 请教个问题, dns规则里 { "outbound": "any", "server": "alidns" } 是不是代表所有dns请求都走alidns?如果是这样设置googledns有什么意义?如果不是那么"outbound": "any"代表什么含义?

@Qian119lsj 看了眼[源码](https://github.com/SagerNet/sing-box/blob/001649cb077e9de48ff566f6ca383f6b92d1f23b/route/rule_item_outbound.go#L30C1-L36C1)，"any" 匹配所有 outbound，但不匹配空（""），非outbound的dns请求不会命中这条规则

**Comment by tanst** [comment]
> 请教个问题, dns规则里 { "outbound": "any", "server": "alidns" } 是不是代表所有dns请求都走alidns?如果是这样设置googledns有什么意义?如果不是那么"outbound": "any"代表什么含义?

这个 `any` 太容易误解了，写成 `outbound_dns` 多好

**Comment by Qian119lsj** [comment]
> > 请教个问题, dns规则里 { "outbound": "any", "server": "alidns" } 是不是代表所有dns请求都走alidns?如果是这样设置googledns有什么意义?如果不是那么"outbound": "any"代表什么含义?
> 
> 这个 `any` 太容易误解了，写成 `outbound_dns` 多好

outbound这玩意指的是出口服务器域名的解析器,反而按出口分别指定dns的功能没有
