### ISSUE TITLE
h2mux doesn't work as expected

### ISSUE THREAD

**Issue by its0ka** [SagerNet/sing-box#861]
### Operating system

Linux

### System version

latest arch

### Installation type

Original sing-box Command Line

### Version

```console
sing-box version 1.4.1

Environment: go1.20.7 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_reality_server,with_clash_api
Revision: a21426b552d7b00abe1233e4bfb98ac919e3143b
CGO: disabled
```

### Description

![image](https://github.com/SagerNet/sing-box/assets/125186204/fa63ddf4-1425-4ae3-9bee-eb5499244e75)
i can see multiple connections to the server even with very large "max_streams", is this right for h2mux? i can see only 1 connection with smux, but its very slow, my other connections drop when i download something, so i want to use h2mux. DPI in my country only allows 1 connection to the server to prevent people from using proxies.

### Reproduction

use h2mux with "max_streams": 99999 or any other value
{
                "multiplex": {
                "enabled": true,
                "max_streams": 99999,
                "padding": false,
                "protocol": "h2mux"
}
and start torrent download

### Logs

<details>
```console
# Replace this line with logs
```
</details>

**Comment by nekohasekai** [comment]
This is not a hard limit, and if the protocol used to carry the stream (such as http2) cannot accept new streams, this configuration cannot change this.
