### ISSUE TITLE
建议android客户端通知栏的"service started"更改为当前profile

### ISSUE THREAD

**Issue by yunxueyuan** [SagerNet/sing-box#865]
建议android客户端通知栏的"service started"更改为当前profile，以便快速分辨

**Comment by glaughlee** [comment]
建议通知栏的“sing-box”改为当前profile，"service started"改为当前选中的节点，这样更方便分辨当前使用的节点

**Comment by MrVb0** [comment]
I quite agree .  Please apply in the next update.

> 建议通知栏的“sing-box”改为当前profile，"service started"改为当前选中的节点，这样更方便分辨当前使用的节点

I quite agree .  Please apply in the next update.
