### ISSUE TITLE
Feature request: Prometheus metrics

### ISSUE THREAD

**Issue by mazzz1y** [SagerNet/sing-box#87]
I think it is good to have something to monitor service stats. With v2ray/xray we can use [v2ray-exporter](https://github.com/wi1dcard/v2ray-exporter) -- tool which converts built-in stats into prometheus metrics.

I think it is possible to serve `/metrics` path directly by sing-box and avoid to use external exporters.

For example:

```
{
    "stats": {
        "enabled": true
    },
    "inbounds": [
      {
        "type": "prometheus",
        "tag": "prometeus-in",
        "listen": "::",
        "listen_port": 1080,
        "path": "/metrics",
        // basic auth
        "users": [
            {
              "username": "admin",
              "password": "admin"
            }
          ]
      }
    ]
}
```

**Comment by PoneyClairDeLune** [comment]
So uhh... Has the feature been implemented yet before it got closed?
