### ISSUE TITLE
Request for providing a collection of minimal config.json files for easier usage

### ISSUE THREAD

**Issue by ghost** [SagerNet/sing-box#876]
Hi there,

I am a happy user of sing-box and I want to express my gratitude for your efforts put into developing such a powerful tool. However, new users have encountered some difficulties in configuring sing-box to make "it just work" first.

To address this issue and assist new users, I kindly request the sing-box team to provide a collection of minimal `config.json` files with cloze placeholders. These pre-configured files will serve as templates and help users understand the necessary configurations more easily.

Currently, setting up the `config.json` file from scratch **can be overwhelming for newcomers**. By providing a collection of minimal files with cloze placeholders, users will have a clear starting point and can quickly fill in the necessary details. This approach will not only simplify the initial setup process but also reduce the chances of misconfigurations.

Furthermore, it would be beneficial to emphasize that once users have successfully set up sing-box using the minimal config files, they can easily add additional configurations based on their specific needs. They can refer to the documentation for guidance on adding and modifying configurations later.

Having access to these pre-configured files will greatly benefit new users by guiding them through the necessary steps and ensuring a smooth onboarding experience. It will encourage more people to try out sing-box and help them get up and running quickly.

Thank you for considering this request. I appreciate your dedication to improving sing-box and look forward to seeing this feature implemented in future releases.

**Comment by Free2024** [comment]
Exactly, I just installed it based on the official doc and now I am looking where is the path for "config.json" when it runs as service.

**Comment by MacabreObserver** [comment]
Yes, I hope the maintainer will create a timely plan for this request.

**Comment by sdhz151** [comment]
用两台vps，vps1落地机(LNMP环境+WordPress)，vps2中转(反代)(LNMP环境+WordPress)
vps1落地机，安装nginx+sing-box(vmess+ws)

nginx配置
location /path/ {
            proxy_redirect off;
            proxy_pass http://127.0.0.1:13579;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            proxy_read_timeout 300s;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
sing-box配置

{
    "inbounds": [
        {
            "type": "vmess",
            "listen": "127.0.0.1",
            "listen_port": 13579,
            "users": [
                {
                    "uuid": "ff0c5ef1-cdc7-9fdc-3078-e43d01489fa0",
                    "alterId": 0
                }
            ],
            "transport": {
                "type": "ws",
                "path": "/path/",
                "max_early_data": 2048,
                "early_data_header_name": "Sec-WebSocket-Protocol"
            }
        }
    ],
    "outbounds": [
        {
            "type": "direct"
        }
    ]
}

vps2中转机
nginx配置
location /c141458b/ {

            proxy_pass https://vps1_ip:443/path/;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
客户端
域名填vps2域名
端口443
ws路径vps2
剩余，tls  都填vps1

安全性不知道,欢迎解答

**Comment by CXwudi** [comment]
https://github.com/malikshi/sing-box-examples
https://github.com/chika0801/sing-box-examples
Also official examples: https://sing-box.sagernet.org/examples/

**Comment by he-sb** [comment]
Maybe this repo can be a quick reference: https://github.com/chika0801/sing-box-examples
