### ISSUE TITLE
memory leak in multiple box instance running

### ISSUE THREAD

**Issue by uussoop** [SagerNet/sing-box#879]
### Operating system

Linux

### System version

ubuntu 22

### Installation type

Others

### Version

<details>
```console
v1.4.0
```
</details>

### Description

hi i am using singbox create to run multiple instances of singbox at the same time then closing them.
but after i close them (by the way closing is successful the logs indicate that) there are some memory leftovers that with each instance creation and closing it grows.
by using the go pprof i pin pointed  github.com/sagernet/sing/common/buf.init.func1 as the source of the memory leak.
in the attached image you can see the graph of pprof heap for this issue
![image](https://github.com/SagerNet/sing-box/assets/47169122/938ef088-9f4b-4374-8b7b-cf08df8c56b5)

### Reproduction

you can run multiple box instances then try and use them send some requests.
after that close instances but let the main program proceed and monitor memory usage of before and after of each instance start and close.

### Logs

<details>
```console
# Replace this line with logs
```
</details>

**Comment by uussoop** [comment]
could you be more specific?
what core?

**Comment by nekohasekai** [comment]
Make sure you do `Close`, don't retain the box.Box instance, and do `debug.FreeOSMemory()`.

**Comment by uussoop** [comment]
thanks for your suggestion i was already closing each instance but i added the garbage collector after closing and it seems to free it up but i need to test more i will keep this issue updated

**Comment by uussoop** [comment]
still i find myself even after instance.close and debug.FreeOSMemory() that there is memory leakage

**Comment by nekohasekai** [comment]
I think you need to provide more information.
