### ISSUE TITLE
服务端添加vmess出站，ws传输层添加路径后，无法链接  websocket: bad handshake: HTTP 200 200 OK

### ISSUE THREAD

**Issue by lin1123** [SagerNet/sing-box#884]
### 操作系统

Linux

### 系统版本

debian 12

### 安装类型

sing-box 原始命令行程序

### 版本

<details>
sing-box version 1.4.3

Environment: go1.21.1 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_reality_server,with_clash_api
Revision: be61ca64d4d00248cdf08a519b88e93881f6d0e3
CGO: disabled

</details>

### 描述

{
  "log": {
    "level": "debug",
    "output": "/etc/sing-box/box.log",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "address": "tls://1.1.1.1"
      }
    ],
    "strategy": "ipv4_only"
  },
  "ntp": {
    "enabled": true,
    "interval": "30m0s",
    "server": "ntp.tencent.com",
    "server_port": 123,
    "detour": "direct"
  },
  "inbounds": [
    {
      "type": "vless",
      "tag": "vless-in",
      "listen": "::",
      "listen_port": 12346,
      "sniff": true,
      "sniff_override_destination": true,
      "users": [
        {
          "name": "",
          "uuid": "*",
          "flow": "xtls-rprx-vision"
        }
      ],
      "tls": {
        "enabled": true,
        "server_name": "www.lovelive-anime.jp",
        "reality": {
          "enabled": true,
          "handshake": {
            "server": "www.lovelive-anime.jp",
            "server_port": 443
          },
          "private_key": "*",
          "short_id": "18173af00874a1b8"
        }
      }
    },
    {
      "type": "tuic",
      "tag": "tuic-in",
      "listen": "::",
      "listen_port": 8443,
      "users": [
        {
          "uuid": "uuid",
          "password": "sDtPGMg5ETSx"
        }
      ],
      "congestion_control": "bbr",
      "tls": {
        "enabled": true,
        "alpn": "h3",
        "certificate_path": "/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/0.xyz.crt",
        "key_path": "/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/0.xyz.key"
      }
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    },
    {
      "type": "vmess",
      "tag": "GoNetflix",
      "detour": "direct",
      "server": "域名",
      "server_port": 8880,
      "uuid": "FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF",
      "security": "none",
      "transport": {
        "type": "ws",
        "path": "/favicon.ico?t=personal&token=vhkcsvndsb",
        "early_data_header_name": "Sec-WebSocket-Protocol"
      }
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "geosite": [
          "cn",
          "category-ads-all"
        ],
        "geoip": [
          "cn",
          "private"
        ],
        "outbound": "block"
      },
      {
        "geosite": [
          "netflix",
          "disney"
        ],
        "outbound": "GoNetflix"
      }
    ],
    "final": "direct",
    "auto_detect_interface": true
  }
}

### 重现方式

在出站添加了这项配置
{
      "type": "vmess",
      "tag": "GoNetflix",
      "detour": "direct",
      "server": "域名",
      "server_port": 8880,
      "uuid": "FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF",
      "security": "none",
      "transport": {
        "type": "ws",
        "path": "/favicon.ico?t=personal&token=vhkcsvndsb",
        "early_data_header_name": "Sec-WebSocket-Protocol"
      }
 }
在clash.meta中使用链式代理能够正常使用此节点，v2vrayn中单独添加此节点也能够使用。

### 日志

<details>

+0800 2023-09-15 23:37:15 DEBUG [75636318 0ms] router: sniffed protocol: tls, domain: www.netflix.com
+0800 2023-09-15 23:37:15 DEBUG [75636318 0ms] router: match[2] geosite=[netflix disney] => GoNetflix
+0800 2023-09-15 23:37:15 INFO [75636318 0ms] outbound/vmess[GoNetflix]: outbound connection to www.netflix.com:443
+0800 2023-09-15 23:37:15 INFO [75636318 0ms] outbound/direct[direct]: outbound connection to media-sg-vmess01.tanainai.net:8880
+0800 2023-09-15 23:37:15 DEBUG [75636318 0ms] dns: lookup domain 此处为解析的节点域名
+0800 2023-09-15 23:37:15 DEBUG [75636318 0ms] dns: lookup succeed for 此处为解析的节点域名
+0800 2023-09-15 23:37:15 ERROR [1254175542 361ms] inbound/vless[vless-in]: process connection from IP:30770: websocket: bad handshake: HTTP 200 200 OK

</details>

**Comment by zqcccc** [comment]
transport 里的 path 有 query 好像就不行，我也遇到了这个问题，别人的流媒体解锁节点 ws 路径就是带 query 的，请问这个有解吗？
