### ISSUE TITLE
tun模式下IPv6无法使用ssh访问

### ISSUE THREAD

**Issue by ricolxwz** [SagerNet/sing-box#889]
### 操作系统

Linux

### 系统版本

ubuntu 22.04.1

### 安装类型

sing-box 原始命令行程序

### 版本

<details>
```console
sing-box version unknown
Environment: go1.21.1 linux/amd64
CGO: disabled
```
</details>

### 描述

#883 
✖️ 通过IPv6 ssh连接tun模式下的主机
✅ 通过IPv4 ssh连接tun模式下的主机

已将`strict_route`设置为`false`, 在debian11.4, debian12上存在同样的问题

<img width="258" alt="CleanShot 2023-09-17 at 09 32 32@2x" src="https://github.com/SagerNet/sing-box/assets/92409532/c09432ee-2c08-43a9-b81b-e448f8efe514">

### 重现方式

`inbounds`: 
```json
"inbounds": [
    {
      "type": "tun",
      "interface_name": "tun0",
      "inet4_address": "172.20.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "auto_route": true,
      "strict_route": false,
      "stack": "system",
      "sniff": true
    }
  ],
```

```console
root@ip-172-26-14-106:/usr/local/etc/sing-box# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination    
```

### 日志

<details>
```console
# 使用日志内容覆盖此行
```
</details>

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/issues/458
