### ISSUE TITLE
cannot use "store_selected" in clash_api

### ISSUE THREAD

**Issue by adiprasetya** [SagerNet/sing-box#894]
### Operating system

Android

### System version

11

### Installation type

Original sing-box Command Line

### Version

``` console
sing-box version 1.5.0-beta.11

Environment: go1.21.1 android/arm64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_clash_api
Revision: 64edacffb7409e6c367a537a4a9180b5989f4ac3
CGO: enabled
```

### Description

sing-box service will stopped when "store_selected" value is "true"

### Reproduction

following [sing-box example](https://sing-box.sagernet.org/examples/clash-api)

``` json
{
    "experimental": {
      "clash_api": {
        "external_controller": "127.0.0.1:9090",
        "external_ui": "dashboard",
        "store_selected": true
      }
    }
}
```

### Logs

``` console
FATAL[0000] start service: pre-starting clash api: open cache file: function not implemented
```

**Comment by nekohasekai** [comment]
This error comes from syscall ENOSYS and means that your kernel is missing some functionality that bbolt requires. Please provide more information about the device environment and how to reproduce it.

**Comment by adiprasetya** [comment]
me using miui mod by community, i guess it's the problem. i'll try change custom kernel or rom soon.

**Comment by adiprasetya** [comment]
os issue.
