### ISSUE TITLE
ssh outbound private key parser error

### ISSUE THREAD

**Issue by neh0chy** [SagerNet/sing-box#900]
### Operating system

macOS

### System version

Ventura

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

`*` <= 1.5.0rc1

### Description

I made a profile containing ssh outbound with "private_key" name and my ssh private key in value like "-----BEGIN OPENSSH PRIVATE KEY----- ...key... -----END OPENSSH PRIVATE KEY-----" as described [here](https://sing-box.sagernet.org/configuration/outbound/ssh/).

I made a string from the key and removed spaces but providing key this way (with/without spaces but as one string) ends up with an error: 
<img width="249" alt="Screenshot 2023-09-20 at 2 09 54 PM" src="https://github.com/SagerNet/sing-box/assets/103634915/daa203eb-5aad-4fa0-93cc-f432a803e3ee">

I get the same parser error on macOS (screen above) and Android versions:
<img width="305" alt="Screenshot 2023-09-20 at 2 50 40 PM" src="https://github.com/SagerNet/sing-box/assets/103634915/4ae68186-018a-4079-893c-ca346f99b178">

My actual key on server is ed25519, but same with rsa of any length.

Providing actual key file via "private_key_path" works like a charm...

### Reproduction

1. You need to have an SSH server with an authorization by keys.
2. Create a profile with ssh outbound as described [here](https://sing-box.sagernet.org/configuration/outbound/ssh/) and provide your server info.
3. For "private_key" name specify your private key as a json value.
4. Try to connect with created profile in sing-box Dashboard

**Comment by nekohasekai** [comment]
Please try converting private_key_path to private_key using the `sing-box merge` command and see if this error still occurs.

**Comment by neh0chy** [comment]
After using `sing-box merge output.json -c config.json` and using this config i receive the following error:

<img width="248" alt="Screenshot 2023-09-23 at 11 50 33 PM" src="https://github.com/SagerNet/sing-box/assets/103634915/52c5cc51-97cc-4aa6-9527-38987a830753">

**Comment by nekohasekai** [comment]
> After using `sing-box merge output.json -c config.json` and running output config i receive the following error:

You are using an older version of the app.
