### ISSUE TITLE
sb-tun is not compatible with Firewale 4

### ISSUE THREAD

**Issue by zesssttt** [SagerNet/sing-box#903]
### Operating system

Others

### System version

OpenWrt 23.05.0-rc3

### Installation type

Others

### Version

<details>
Sing-Box Version 1.5.0-rc.2
</details>

### Description

sb-tun is not compatible with Firewale 4
![267851265-3d515129-da5c-4dbc-b2a0-1f95f6ca3844](https://github.com/SagerNet/sing-box/assets/139041404/b2cf5ce8-5ed6-4974-b531-ca87b2b97286)
![267852231-1f7ea67f-8a09-4056-9c8c-377f7cafa581](https://github.com/SagerNet/sing-box/assets/139041404/3eab6aa8-331b-4025-b279-60da08deff24)

### Reproduction

start sing-box or when using sing-box

### Logs

<details>

</details>

**Comment by nekohasekai** [comment]
sing-box does not create iptables rules, please send an issue to the third-party program you use.
