### ISSUE TITLE
SFM: Clear Working Directory 点击后没有生效

### ISSUE THREAD

**Issue by yvvw** [SagerNet/sing-box#906]
### Operating system

macOS

### System version

Ventura 13.5.2

### Installation type

sing-box for macOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.4.3

### Description

清理geo数据功能失效，需要手动删除

### Reproduction

null

**Comment by nekohasekai** [comment]
无法重现

**Comment by yvvw** [comment]
日志里没什么错误

https://github.com/SagerNet/sing-box/assets/15168529/9fd5c073-5d11-43cb-ac2e-1798654ef019
