### ISSUE TITLE
多核调度

### ISSUE THREAD

**Issue by U201413497** [SagerNet/sing-box#908]
### Operating system

Linux

### System version

Armbian

### Installation type

Original sing-box Command Line

### If you are using a graphical client, please provide the version of the client.

sing-box-1.5.0-rc.2-linux-armv7.tar.gz

### Version

<details>
```console
# Replace this line with the output
```
</details>

### Description

首先感谢开发者，确实比v2ray性能好。
平台玩客云，芯片S805，系统armbian，使用v2ray做http入站，socks5出站，naive用socks5入站，使用geoip 和geosite分流，最高能跑到307Mbps。此时CPU占用百分之97，同样的使用sing-box能跑到410Mbps，CPU 占用百分之50左右。基础带宽500Mbps，没有跑满，CPU也没有满。请问是系统问题还是软件问题？

### Reproduction

无

### Logs

<details>
```console
# Replace this line with logs
```
</details>

**Comment by nekohasekai** [comment]
软件问题
