### ISSUE TITLE
ios 1.5.0(26) 无法启动

### ISSUE THREAD

**Issue by t2kDWjhAvB** [SagerNet/sing-box#909]
### Operating system

iOS

### System version

15.7.9

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.5.0(26)

### Version

<details>
```console
# Replace this line with the output
```
</details>

### Description

通过testlight 升级到1.5.0（26）版本。已经清理所有配置，点击启动按钮后不，界面卡住无vpn图标。因用了clashapi，可以访问clash API的界面，点击测速节点正常返回延迟。

### Reproduction

windows上使用相同client config正常，所以排除server config问题。

client config:
{
    "experimental": {
        "clash_api": {
            "external_controller": "127.0.0.1:9090",
            "external_ui": "ui",
            "store_selected": true
        }
    },
    "log": {
        "level": "warn",
        "timestamp": false
    },
    "dns": {
        "servers": [
            {
                "tag": "google",
                "address": "tls://8.8.8.8"
            },
            {
                "tag": "local",
                "address": "223.5.5.5",
                "detour": "direct"
            },
            {
                "tag": "remote",
                "address": "fakeip"
            },
            {
                "tag": "block",
                "address": "rcode://success"
            }
        ],
        "rules": [
            {
                "geosite": "category-ads-all",
                "server": "block",
                "disable_cache": true
            },
            {
                "outbound": "any",
                "server": "local"
            },
            {
                "geosite": "cn",
                "server": "local"
            },
            {
                "query_type": [
                    "A",
                    "AAAA"
                ],
                "server": "remote"
            }
        ],
        "fakeip": {
            "enabled": true,
            "inet4_range": "198.18.0.0/15",
            "inet6_range": "fc00::/18"
        },
        "independent_cache": true,
        "strategy": "ipv4_only"
    },
    "inbounds": [
        {
            "type": "tun",
            "inet4_address": "172.19.0.1/30",
            "auto_route": true,
            "strict_route": true,
            "stack": "system",
            "sniff": true
        }
    ],
    "outbounds": [
        {
            "type": "selector",
            "tag": "default",
            "outbounds": [
                "hy2-1",
                "hy2-2",
                "hy2-3"
            ]
        },
        {
            "type": "hysteria2",
            "tag": "hy2-2",
            "server": "ipaddress",
            "server_port": 11111,
            "password": "password",
            "tls": {
                "enabled": true,
                "server_name": "servername"
            }
        },
        {
            "type": "hysteria2",
            "tag": "hy2-3",
            "server": "ipaddress",
            "server_port": 11111,
            "password": "password",
            "tls": {
                "enabled": true,
                "server_name": "servername"
            }
        },
        {
            "type": "hysteria2",
            "tag": "hy2-1",
            "server": "ipaddress",
            "server_port": 11111,
            "password": "password",
            "tls": {
                "enabled": true,
                "server_name": "servername"
            }
        },
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        }
    ],
    "route": {
        "rules": [
            {
                "clash_mode": "direct",
                "outbound": "direct"
            },
            {
                "protocol": "dns",
                "outbound": "dns-out"
            },
            {
                "geosite": "cn",
                "geoip": [
                    "private",
                    "cn"
                ],
                "outbound": "direct"
            },
            {
                "geosite": "category-ads-all",
                "outbound": "block"
            }
        ],
        "final": "default",
        "auto_detect_interface": true
    }
}

### Logs

<details>
```
client using bbr
```
</details>

**Comment by nekohasekai** [comment]
请提供更多调试信息或最小重现配置或录屏，并开启新的 issue。
