### ISSUE TITLE
ios 1.5.0(26) 启动问题

### ISSUE THREAD

**Issue by t2kDWjhAvB** [SagerNet/sing-box#915]
### Operating system

iOS

### System version

15.7.9

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.5.0（26）

### Version

<details>
```console
# Replace this line with the output
```
</details>

### Description

通过testFlight 升级到1.5.0（26）版本。已经清理所有配置，点击启动按钮后不，界面卡住无vpn图标。因用了clashapi，可以访问clash API的界面，点击测速节点正常返回延迟。
![photo_2023-09-24_10-35-00](https://github.com/SagerNet/sing-box/assets/61587856/9f74aa16-8324-4a1d-aef4-31a287b9c9d1)
![photo_2023-09-24_10-35-15](https://github.com/SagerNet/sing-box/assets/61587856/a9b5febf-8844-4953-8817-9cc340447739)

### Reproduction

清理配置后，日志显示 geosite /geoip 全新下载，但是 Data Size 仍为0 size，感觉是没有保存成功。
杀掉vpn连接后，启动日志显示正常。但是无vpn图标。

![photo_2023-09-24_10-35-08](https://github.com/SagerNet/sing-box/assets/61587856/42336196-56ca-45b5-af9a-af54daa7b087)

![photo_2023-09-24_10-35-12](https://github.com/SagerNet/sing-box/assets/61587856/602fba13-38d2-4b80-bd95-82d4c23e3104)

windows上使用相同client config正常，所以排除server config问题。

client config:
{
"experimental": {
"clash_api": {
"external_controller": "127.0.0.1:9090",
"external_ui": "ui",
"store_selected": true
}
},
"log": {
"level": "warn",
"timestamp": false
},
"dns": {
"servers": [
{
"tag": "google",
"address": "tls://8.8.8.8"
},
{
"tag": "local",
"address": "223.5.5.5",
"detour": "direct"
},
{
"tag": "remote",
"address": "fakeip"
},
{
"tag": "block",
"address": "rcode://success"
}
],
"rules": [
{
"geosite": "category-ads-all",
"server": "block",
"disable_cache": true
},
{
"outbound": "any",
"server": "local"
},
{
"geosite": "cn",
"server": "local"
},
{
"query_type": [
"A",
"AAAA"
],
"server": "remote"
}
],
"fakeip": {
"enabled": true,
"inet4_range": "198.18.0.0/15",
"inet6_range": "fc00::/18"
},
"independent_cache": true,
"strategy": "ipv4_only"
},
"inbounds": [
{
"type": "tun",
"inet4_address": "172.19.0.1/30",
"auto_route": true,
"strict_route": true,
"stack": "system",
"sniff": true
}
],
"outbounds": [
{
"type": "selector",
"tag": "default",
"outbounds": [
"hy2-1",
"hy2-2",
"hy2-3"
]
},
{
"type": "hysteria2",
"tag": "hy2-2",
"server": "ipaddress",
"server_port": 11111,
"password": "password",
"tls": {
"enabled": true,
"server_name": "servername"
}
},
{
"type": "hysteria2",
"tag": "hy2-3",
"server": "ipaddress",
"server_port": 11111,
"password": "password",
"tls": {
"enabled": true,
"server_name": "servername"
}
},
{
"type": "hysteria2",
"tag": "hy2-1",
"server": "ipaddress",
"server_port": 11111,
"password": "password",
"tls": {
"enabled": true,
"server_name": "servername"
}
},
{
"type": "direct",
"tag": "direct"
},
{
"type": "block",
"tag": "block"
},
{
"type": "dns",
"tag": "dns-out"
}
],
"route": {
"rules": [
{
"clash_mode": "direct",
"outbound": "direct"
},
{
"protocol": "dns",
"outbound": "dns-out"
},
{
"geosite": "cn",
"geoip": [
"private",
"cn"
],
"outbound": "direct"
},
{
"geosite": "category-ads-all",
"outbound": "block"
}
],
"final": "default",
"auto_detect_interface": true
}
}

### Logs

<details>
```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x105063a34]

goroutine 6466 [running]:
github.com/sagernet/sing/common/buf.(*Buffer).Len(...)
	github.com/sagernet/sing@v0.2.10-0.20230830132630-30bf19f2833c/common/buf/buffer.go:321
github.com/sagernet/sing-box/transport/hysteria2.fragUDPMessage(0x130623360, 0x130129208?)
	github.com/sagernet/sing-box@v0.0.0-00010101000000-000000000000/transport/hysteria2/packet.go:77 +0x24
github.com/sagernet/sing-box/transport/hysteria2.(*udpPacketConn).WritePacket(0x130224680, 0x13007dd10, {{{0x0, 0x0}, 0x0}, 0x1bb, {0x13025a5a0, 0x17}})
	github.com/sagernet/sing-box@v0.0.0-00010101000000-000000000000/transport/hysteria2/packet.go:234 +0x2a0
github.com/sagernet/sing/common/bufio.CopyPacketWithPool({0x10a25d0a0?, 0x1304a6bd0}, {0x10a25d080?, 0x130224680}, {0x10a25d0a0, 0x1304a6bd0}, {0x0, 0x0, 0x104bb1354?}, {0x0, ...}, ...)
	github.com/sagernet/sing@v0.2.10-0.20230830132630-30bf19f2833c/common/bufio/copy.go:344 +0x258
github.com/sagernet/sing/common/bufio.CopyPacket({0x10a25d080?, 0x130224680?}, {0x10a25d0a0, 0x1304a6bd0})
	github.com/sagernet/sing@v0.2.10-0.20230830132630-30bf19f2833c/common/bufio/copy.go:283 +0x330
github.com/sagernet/sing/common/bufio.CopyPacketConnContextList.func1({0x0?, 0x0?})
	github.com/sagernet/sing@v0.2.10-0.20230830132630-30bf19f2833c/common/bufio/copy.go:400 +0x68
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
	github.com/sagernet/sing@v0.2.10-0.20230830132630-30bf19f2833c/common/task/task.go:68 +0x74
created by github.com/sagernet/sing/common/task.(*Group).RunContextList in goroutine 6455
	github.com/sagernet/sing@v0.2.10-0.20230830132630-30bf19f2833c/common/task/task.go:67 +0x170

```
</details>

**Comment by nekohasekai** [comment]
日志说明您提供配置内容和截图中运行的不同。

**Comment by t2kDWjhAvB** [comment]
> 日志说明您提供配置内容和截图中运行的不同。

是outbound中的hy2-out 和hy2-1区别吗？配置文件我进行了文本替换，所以看上去不同，实际是同一个配置文件
