### ISSUE TITLE
Multiple bugs

### ISSUE THREAD

**Issue by arm64v8a** [SagerNet/sing-box#917]
## 1 cause.go cause panic

https://github.com/arm64v8a/sing/commit/0e59a6354d3e36f4edaa266f1a1fee4962d8db8b

## 2 copy.go did not close the connections after finish

https://github.com/arm64v8a/sing/commit/717742fa0b454b6999adbc40c3e8042882b2827e

If you use `CloseWrite` instead of `Close` on a connection, and the peer of this connection does not send anything or close it, the connection may never be closed, even if another side of relay has been disconnected.

## 3 deadline/reader.go race condition cause goroutine leak

https://github.com/arm64v8a/sing/commit/ce137afc3f55da1416778e5dfc4b5b937d2d40e1

In addition, I didn’t understand the usage of the `deadline` package.

It adds a layer of pipe [for many connections](https://github.com/MatsuriDayo/sing-box/blob/e524eae442cae3a2d353cdb1fd1d71cb5a3a8bd3/route/router.go#L651-L653
), some of them seem unnecessary. If a connection correctly implemented `net.Conn` (everything in the Go standard library should be), then there is no need to implement another deadline.

## 4 task.go All tasks should exit when the upstream context is canceled

https://github.com/arm64v8a/sing/commit/59230b1bfface4d1452fd227f384c2d7d50e078e

## 5 sniff buffer should be released

https://github.com/MatsuriDayo/sing-box/commit/e524eae442cae3a2d353cdb1fd1d71cb5a3a8bd3

**Comment by nekohasekai** [comment]
1. 掩盖问题
2. 同样是掩盖问题
3. 请解释该 goroutine 是如何泄漏的
4. 看起来无效，请解释 taskCancel 没有被调用的场景
5. payload 有效，其他则是掩盖问题

如果您不在乎可维护性，而只是想让所有东西看起来工作，那么您可以制作并发行分支。
