### ISSUE TITLE
Is there any way to get build tags in sing-box command line itself?

### ISSUE THREAD

**Issue by FranzKafkaYu** [SagerNet/sing-box#92]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

I have read the whole document and didn't found some info about how can we check the build tags.Can you give me instructions or just add this function in sing-box command line.This may be helpful when we debug,thank you in advance~

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by Gzxhwq** [comment]
https://github.com/SagerNet/sing-box/commit/9aa7a20d9621eff5f4a35a488ce0812a317c7042

**Comment by FranzKafkaYu** [comment]
> [9aa7a20](https://github.com/SagerNet/sing-box/commit/9aa7a20d9621eff5f4a35a488ce0812a317c7042)

OK,I got it，thank you~
