### ISSUE TITLE
ios client 启动问题

### ISSUE THREAD

**Issue by t2kDWjhAvB** [SagerNet/sing-box#922]
### Operating system

iOS

### System version

15.7.9

### Installation type

sing-box for iOS Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.5.0(31)

### Version

<details>
```console
# Replace this line with the output
```
</details>

### Description

相同client.config 在Windows平台可以使用，ios 正式版1.4.3 也可以正常启动。
1.5.0(31)版本尝试过清空配置，卸载应用全新安装，仍卡住在 opening interface , 无法启动。 

![photo_2023-09-26_00-33-07](https://github.com/SagerNet/sing-box/assets/61587856/8fb86211-2b1b-469f-9abd-fb0da0d0a867)

![photo_2023-09-26_00-32-53](https://github.com/SagerNet/sing-box/assets/61587856/59d2f7fe-99fd-4e38-a537-55bc0a1a5318)

![photo_2023-09-26_00-32-59](https://github.com/SagerNet/sing-box/assets/61587856/fec188e0-6b52-4b59-a0ca-300499650563)

![photo_2023-09-26_00-33-02](https://github.com/SagerNet/sing-box/assets/61587856/831e7732-985a-4976-867f-4dd6fa8571ea)

### Reproduction

config.json:

{ 
    "experimental": { 
        "clash_api": { 
            "external_controller": "127.0.0.1:9090", 
            "external_ui": "ui", 
            "store_selected": true 
        } 
    }, 
    "log": { 
        "level": "trace", 
        "timestamp": false 
    }, 
    "dns": { 
        "servers": [ 
            { 
                "tag": "google", 
                "address": "tls://8.8.8.8" 
            }, 
            { 
                "tag": "local", 
                "address": "223.5.5.5", 
                "detour": "direct" 
            }, 
            { 
                "tag": "remote", 
                "address": "fakeip" 
            }, 
            { 
                "tag": "block", 
                "address": "rcode://success" 
            } 
        ], 
        "rules": [ 
            { 
                "geosite": "category-ads-all", 
                "server": "block", 
                "disable_cache": true 
            }, 
            { 
                "outbound": "any", 
                "server": "local" 
            }, 
            { 
                "geosite": "cn", 
                "server": "local" 
            }, 
            { 
                "query_type": [ 
                    "A", 
                    "AAAA" 
                ], 
                "server": "remote" 
            } 
        ], 
        "fakeip": { 
            "enabled": true, 
            "inet4_range": "198.18.0.0/15", 
            "inet6_range": "fc00::/18" 
        }, 
        "independent_cache": true, 
        "strategy": "ipv4_only" 
    }, 
    "inbounds": [ 
        { 
            "type": "tun", 
            "inet4_address": "172.19.0.1/30", 
            "auto_route": true, 
            "strict_route": true, 
            "stack": "system", 
            "sniff": true 
        } 
    ], 
    "outbounds": [ 
        { 
            "type": "selector", 
            "tag": "default", 
            "outbounds": [ 
                "hy2-out" 
            ] 
        }, 
        
        { 
            "type": "hysteria2", 
            "tag": "hy2-out", 
            "server": "...", 
            "server_port": 123, 
            "password": "...", 
            "tls": { 
                "enabled": true, 
                "server_name": "domain_name" 
            } 
        }, 
        { 
            "type": "direct", 
            "tag": "direct" 
        }, 
        { 
            "type": "block", 
            "tag": "block" 
        }, 
        { 
            "type": "dns", 
            "tag": "dns-out" 
        } 
    ], 
    "route": { 
        "rules": [ 
            { 
                "clash_mode": "direct", 
                "outbound": "direct" 
            }, 
            { 
                "protocol": "dns", 
                "outbound": "dns-out" 
            }, 
            { 
                "geosite": "cn", 
                "geoip": [ 
                    "private", 
                    "cn" 
                ], 
                "outbound": "direct" 
            }, 
            { 
                "geosite": "category-ads-all", 
                "outbound": "block" 
            } 
        ], 
        "final": "default", 
        "auto_detect_interface": true 
    } 
}

### Logs

<details>
```console
service log 显示空
```
</details>

**Comment by nekohasekai** [comment]
尝试 Build 32

**Comment by t2kDWjhAvB** [comment]
Hysteria 2 协议不支持，换了协议正常启动运行，谢谢

**Comment by t2kDWjhAvB** [comment]
原来Build 32 是1.4.5版本的，知道Hysteria 2不支持的原因了

**Comment by nekohasekai** [comment]
是上传错误，等更新修复。

**Comment by nekohasekai** [comment]
是上传错误，等更新修复。
