### ISSUE TITLE
sniff bug for analytics.google.com

### ISSUE THREAD

**Issue by AkramiPro** [SagerNet/sing-box#924]
### Operating system

Linux

### System version

5.15

### Installation type

Original sing-box Command Line

### If you are using a graphical client, please provide the version of the client.

nekoray

### Version

```console
sing-box version 1.5.0-rc.5
Environment: go1.21.1 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api
Revision: 8311cf112d5d8d211f6b13f2d6e71e27f0e4629a
CGO: disabled
```

### Description

i want some domain use direct and some other use wiregurd (warp) . 
so i using rule section and when i set the domain rule it is not work because i must enable sniff in inbound
but when the sniff is true some sites not loaded and get this error :

[analytics.google.com](https://analytics.google.com/)

![image](https://github.com/SagerNet/sing-box/assets/54323929/56875224-85fb-4585-9ff0-f3430623f8fc)

### Reproduction

"sniff": true,

**Comment by nekohasekai** [comment]
Send your issue to the program that generated the configuration file.

**Comment by AkramiPro** [comment]
what do you mean ?!!! 
i generated myself 
all of you chines are crazy

**Comment by CXwudi** [comment]
Just a very simple question. Did you check if analytics.google.com belong to `category-ads-all`?

There's a reason why sekai is angry
