### ISSUE TITLE
安卓客户端高内存占用

### ISSUE THREAD

**Issue by ouyeantai** [SagerNet/sing-box#926]
### Operating system

Android

### System version

Android13，oneui5.1,miui14

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.5.0-rc5-df905040

### Version

<details>
```console
# Replace this line with the output
```
</details>

### Description

![Screenshot_20230927_111738_sing-box](https://github.com/SagerNet/sing-box/assets/38450065/68af8fc5-0257-477b-9d69-92c0693138d9)
![Screenshot_20230927_111654_sing-box](https://github.com/SagerNet/sing-box/assets/38450065/96a8f794-f059-4d48-8e23-f09d63e1b9da)

### Reproduction

随机出现

### Logs

<details>
```console
# Replace this line with logs
```
</details>

**Comment by Oliver-Yue** [comment]
请按照issue的要求反馈使用问题哦~
