### ISSUE TITLE
shadowTLS + shadowsocks with multiple users not work

### ISSUE THREAD

**Issue by everyx** [SagerNet/sing-box#93]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

I setup server and client follow https://sing-box.sagernet.org/examples/shadowtls/, the only change is the multiple user config, and sing-box is not working with both master and user's password, if I remove the multi-user config, everything get back work.

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
sing-box 1.0.4 (go1.19.1, linux/amd64, CGO enabled)
```

</details>

### Server and client configuration file

<details>
<summary>sever configuration</summary>

```diff
{
  "inbounds": [
    {
      "type": "shadowtls",
      "listen": "::",
      "listen_port": 4443,
      "handshake": {
        "server": "cloud.tencent.com",
        "server_port": 443
      },
      "detour": "shadowsocks-in"
    },
    {
      "type": "shadowsocks",
      "tag": "shadowsocks-in",
      "listen": "127.0.0.1",
      "method": "2022-blake3-aes-128-gcm",
      "password": "YRE12QvJFU9U4m292eybfw==",
+     "users": [
+        { "name": "one@example.com", "password": "ebvBSZcZEXD8eftIOwWH9w==" },
+        { "name": "two@example.com", "password": "W35WozUY8P8nAQ3SGuchpQ==" }
+     ]
    }
  ]
}
```

</details>

<details>
<summary>client configuration</summary>

```json
{
  "outbounds": [
    {
      "type": "shadowsocks",
      "method": "2022-blake3-aes-128-gcm",
      "password": "YRE12QvJFU9U4m292eybfw==",
      "detour": "shadowtls-out",
      "multiplex": {
        "enabled": true,
        "max_connections": 4,
        "min_streams": 4
      }
    },
    {
      "type": "shadowtls",
      "tag": "shadowtls-out",
      "server": "127.0.0.1",
      "server_port": 4443,
      "tls": {
        "enabled": true,
        "server_name": "cloud.tencent.com"
      }
    }
  ]
}
```

</details>

### Server and client log file

<details>

```console
# paste log here

```

</details>

**Comment by nekohasekai** [comment]
For multi-user server, client password format is `server psk:user psk`.
