### ISSUE TITLE
sfi使用hy2协议出站时，ios上的facebook无法加载视频。

### ISSUE THREAD

**Issue by 13wenwen** [SagerNet/sing-box#933]
### 操作系统

iOS

### 系统版本

16.7

### 安装类型

sing-box for iOS 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.5.0-rc.5

### 版本

<details>
```console
# 使用输出内容覆盖此行
```
</details>

### 描述

sfi使用hy2节点出站时，facebook无法加载图片。

**client日志**
`23-09-28 13:24:15[ info ][3906079353 0ms] outbound/hysteria2[HK-hy-no_ofbs]: outbound packet connection to 31.13.77.17:443

23-09-28 13:24:15[ info ][3906079353 0ms] inbound/tun[111]: inbound packet connection to 31.13.77.17:443
23-09-28 13:24:15[ info ][3906079353 0ms] inbound/tun[111]: inbound packet connection from 172.19.0.1:49242
23-09-28 13:23:56[ debug ][1922979105 10.8s] inbound/tun[111]: connection closed: upstream: context canceled | EOF
23-09-28 13:23:56[ debug ][1263166406 10.8s] inbound/tun[111]: connection closed: upstream: context canceled | EOF
23-09-28 13:23:55[ debug ][3784157124 10.8s] inbound/tun[111]: connection closed: upstream: context canceled | EOF
23-09-28 13:23:55[ debug ][1174098287 10.8s] inbound/tun[111]: connection closed: upstream: context canceled | EOF
23-09-28 13:23:55[ debug ][2162313433 10.8s] inbound/tun[111]: connection closed: upstream: context canceled | EOF
23-09-28 13:23:55[ debug ][680280600 10.9s] inbound/tun[111]: connection closed: upstream: context canceled | EOF`

**sever日志**

+0800 2023-09-28 13:24:46 DEBUG inbound/hysteria2[hysteria-no ofbs-in]: connection failed: receive message: PROTOCOL_VIOLATION (remote): DATAGRAM frame too large
+0800 2023-09-28 13:24:47 INFO [451971778 0ms] inbound/hysteria2[hysteria-no ofbs-in]: inbound connection to 157.240.199.22:443
+0800 2023-09-28 13:24:47 INFO [451971778 0ms] outbound/direct[direct]: outbound connection to 157.240.199.22:443
+0800 2023-09-28 13:24:47 INFO [2625310216 0ms] inbound/hysteria2[hysteria-no ofbs-in]: inbound connection to 157.240.211.13:443
+0800 2023-09-28 13:24:47 INFO [2625310216 0ms] outbound/direct[direct]: outbound connection to 157.240.211.13:443
+0800 2023-09-28 13:24:47 INFO [4233760999 0ms] inbound/hysteria2[hysteria-no ofbs-in]: inbound connection to 157.240.211.22:443
+0800 2023-09-28 13:24:47 INFO [4233760999 1ms] outbound/direct[direct]: outbound connection to 157.240.211.22:443
+0800 2023-09-28 13:24:47 INFO [2132020729 0ms] inbound/hysteria2[hysteria-no ofbs-in]: inbound packet connection to 157.240.211.13:443
+0800 2023-09-28 13:24:47 INFO [2132020729 1ms] outbound/direct[direct]: outbound packet connection
+0800 2023-09-28 13:24:48 INFO [3204039547 0ms] inbound/hysteria2[hysteria-no ofbs-in]: inbound connection to 157.240.211.3:5222
+0800 2023-09-28 13:24:48 INFO [3204039547 0ms] outbound/direct[direct]: outbound connection to 157.240.211.3:5222
+0800 2023-09-28 13:24:49 INFO [1655769385 0ms] inbound/hysteria2[hysteria-no ofbs-in]: inbound connection to 31.13.75.1:443
+0800 2023-09-28 13:24:49 INFO [1655769385 0ms] outbound/direct[direct]: outbound connection to 31.13.75.1:443

### 重现方式

[sing-box使用如下配置，即可复现。
{
    "log": {
        "level": "debug",
        "timestamp": true
    },
    "dns": {
        "servers": [
            {
                "tag": "DNS_proxy",
                "address": "1.1.1.1",
                "detour": "HK-tuic"
            },
            {
                "tag": "dnsdirect",
                "address": "https://223.5.5.5/dns-query",
                "detour": "direct"
            },
            {
                "tag": "block",
                "address": "rcode://success"
            }
        ],
        "rules": [
            {
                "clash_mode": "global",
                "server": "DNS_proxy"
            },
            {
                "clash_mode": "direct",
                "server": "dnsdirect"
            },
            {
                "domain_suffix": [
                    "qpic.cn",
                    "weixin.qq.com",
                    "zglchr.com",
                    "wxapp.tc.qq.com",
                    "servicewechat.com",
                    "tenpay.com",
                    "wechatlegal.net",
                    "wechatpay.com",
                    "weixin.com",
                    "clash.metacubex.one",
                    "yacd.metacubex.one",
                    "weixinbridge.com",
                    "weixinsxy.com"
                ],
                "geosite": [
                    "cn",
                    "apple@cn",
                    "microsoft@cn",
                    "category-games@cn",
                    "private"
                ],
                "server": "dnsdirect"
            },
            {
                "outbound": "any",
                "server": "dnsdirect"
            },
            {
                "geosite": "category-ads-all",
                "server": "block"
            }
        ],
        "final": "DNS_proxy",
        "independent_cache": true
    },
    "inbounds": [
        {
            "type": "tun",
            "tag": "111",
            "inet4_address": "172.19.0.1/30",
            "auto_route": true,
            "strict_route": true,
            "stack": "mixed",
            "sniff": true
        }
    ],
    "outbounds": [
        {
            "type": "selector",
            "tag": "select",
            "outbounds": [
                "urltest",
                "HK",
                "HK-CF",
                "HK-tuic",
                "HK-hy",
                "HK-hy-no_ofbs",
                "US",
                "US-CF",
                "US-容器",
                "US-tuic",
                "US-hy"
            ],
            "default": "urltest"
        },
        {
            "type": "urltest",
            "tag": "urltest",
            "outbounds": [
                "HK",
                "HK-CF",
                "HK-hy",
                "HK-tuic",
                "HK-hy-no_ofbs",
                "US",
                "US-CF",
                "US-容器",
                "US-tuic",
                "US-hy"
            ],
            "url": "http://cp.cloudflare.com/generate_204",
            "interval": "1m",
            "tolerance": 50
        },
        {
            "type": "vless",
            "tag": "HK",
            "server": "x.x.x.x",
            "server_port": 10086,
            "uuid": "x.x.x.x",
            "flow": "xtls-rprx-vision",
            "tls": {
                "enabled": true,
                "server_name": "x.x.x.x",
                "utls": {
                    "enabled": true,
                    "fingerprint": "chrome"
                },
                "reality": {
                    "enabled": true,
                    "public_key": "x.x.x.x",
                    "short_id": "1"
                }
            }
        },
        {
            "type": "vmess",
            "tag": "HK-CF",
            "server": "x.x.x.x",
            "server_port": 443,
            "uuid": "x.x.x.x",
            "security": "auto",
            "alter_id": 0,
            "tls": {
                "enabled": true,
                "server_name": "x.x.x.x",
                "insecure": true
            },
            "transport": {
                "type": "ws",
                "path": "/x.x.x.x",
                "headers": {
                    "Host": "x.x.x.x"
                }
            }
        },
        {
            "type": "tuic",
            "tag": "HK-tuic",
            "server": "x.x.x.x",
            "server_port": 10010,
            "uuid": "x.x.x.x",
            "password": "x.x.x.xx.x.x.x",
            "congestion_control": "bbr",
            "udp_over_stream": true,
            "tls": {
                "enabled": true,
                "server_name": "x.x.x.x",
                "alpn": "h3"
            }
        },
        {
            "type": "hysteria2",
            "tag": "HK-hy-no_ofbs",
            "server": "x.x.x.x",
            "server_port": 10098,
            "up_mbps": 50,
            "down_mbps": 50,
            "password": "x.x.x.xx.x.x.x",
            "tls": {
                "enabled": true,
                "server_name": "x.x.x.x",
                "alpn": [
                    "h3"
                ]
            }
        },
        {
            "type": "hysteria2",
            "tag": "HK-hy",
            "server": "x.x.x.x",
            "server_port": 10099,
            "up_mbps": 50,
            "down_mbps": 50,
            "obfs": {
                "type": "salamander",
                "password": "haha"
            },
            "password": "x.x.x.xx.x.x.x",
            "tls": {
                "enabled": true,
                "server_name": "x.x.x.x",
                "alpn": [
                    "h3"
                ]
            }
        },
        {
            "type": "vmess",
            "tag": "US-CF",
            "server": "x.x.x.x",
            "server_port": 443,
            "uuid": "x.x.x.x",
            "security": "auto",
            "multiplex": {
                "enabled": true,
                "protocol": "h2mux",
                "max_connections": 4,
                "min_streams": 4,
                "max_streams": 0
            },
            "tls": {
                "enabled": true,
                "server_name": "x.x.x.x",
                "insecure": true
            },
            "transport": {
                "type": "ws",
                "path": "/x.x.x.x",
                "headers": {
                    "Host": "x.x.x.x"
                }
            }
        },
        {
            "type": "vless",
            "tag": "US",
            "server": "x.x.x.x",
            "server_port": 10006,
            "uuid": "x.x.x.x",
            "flow": "xtls-rprx-vision",
            "tls": {
                "enabled": true,
                "server_name": "www.caltech.edu",
                "utls": {
                    "enabled": true,
                    "fingerprint": "chrome"
                },
                "reality": {
                    "enabled": true,
                    "public_key": "Zx.x.x.x",
                    "short_id": "3x.x.x.x6"
                }
            },
            "packet_encoding": "xudp"
        },
        {
            "type": "vmess",
            "tag": "US-容器",
            "server": "x.x.x.x",
            "server_port": 2095,
            "uuid": "x.x.x.x",
            "security": "auto",
            "transport": {
                "type": "ws",
                "path": "/x.x.x.x-vm",
                "headers": {
                    "Host": "hk2.780789.xyz"
                }
            }
        },
        {
            "type": "tuic",
            "tag": "US-tuic",
            "server": "x.x.x.x",
            "server_port": 10010,
            "uuid": "x.x.x.x",
            "password": "x.x.x.xx.x.x.x",
            "congestion_control": "bbr",
            "udp_over_stream": true,
            "tls": {
                "enabled": true,
                "server_name": "x.x.x.x",
                "alpn": "h3"
            }
        },
        {
            "type": "hysteria",
            "tag": "US-hy",
            "server": "x.x.x.x",
            "server_port": 10099,
            "up_mbps": 50,
            "down_mbps": 50,
            "auth_str": "x.x.x.xei",
            "tls": {
                "enabled": true,
                "server_name": "x.x.x.x",
                "alpn": [
                    "h3"
                ]
            }
        },
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        },
        {
            "type": "selector",
            "tag": "Gpt-bing-bard",
            "outbounds": [
                "US",
                "US",
                "US-容器",
                "US-tuic"
            ]
        },
        {
            "type": "selector",
            "tag": "youtube",
            "outbounds": [
                "HK",
                "US",
                "select"
            ]
        },
        {
            "type": "selector",
            "tag": "BiliBili",
            "outbounds": [
                "HK",
                "HK-CF",
                "direct"
            ],
            "default": "direct"
        },
        {
            "type": "selector",
            "tag": "Speedtest",
            "outbounds": [
                "select",
                "direct"
            ],
            "default": "select"
        }
    ],
    "route": {
        "rules": [
            {
                "port": 53,
                "outbound": "dns-out"
            },
            {
                "protocol": "dns",
                "outbound": "dns-out"
            },
            {
                "domain_suffix": [
                    "clash.metacubex.one",
                    "yacd.metacubex.one"
                ],
                "outbound": "select"
            },
            {
                "clash_mode": "direct",
                "outbound": "direct"
            },
            {
                "clash_mode": "global",
                "outbound": "select"
            },
            {
                "protocol": "quic",
                "outbound": "block"
            },
            {
                "geosite": "bilibili",
                "outbound": "BiliBili"
            },
            {
                "geosite": "youtube",
                "outbound": "youtube"
            },
            {
                "domain_suffix": [
                    "bing.com",
                    "bard.google.com"
                ],
                "geosite": "openai",
                "outbound": "Gpt-bing-bard"
            },
            {
                "geosite": "ookla-speedtest",
                "outbound": "Speedtest"
            },
            {
                "domain_suffix": [
                    "qpic.cn",
                    "weixin.qq.com",
                    "wxapp.tc.qq.com",
                    "servicewechat.com",
                    "tenpay.com",
                    "zglchr.com",
                    "wechatlegal.net",
                    "wechatpay.com",
                    "weixin.com",
                    "weixinbridge.com",
                    "weixinsxy.com",
                    "zxxk.com"
                ],
                "geosite": [
                    "apple@cn",
                    "category-games@cn",
                    "microsoft@cn",
                    "cn",
                    "private"
                ],
                "geoip": [
                    "cn",
                    "private"
                ],
                "outbound": "direct"
            },
            {
                "geosite": "category-ads-all",
                "outbound": "block"
            },
            {
                "geosite": "geolocation-!cn",
                "outbound": "select"
            }
        ],
        "final": "select",
        "auto_detect_interface": true
    },
    "experimental": {
        "clash_api": {
            "external_controller": "127.0.0.1:9090",
            "external_ui": "dashboard",
            "external_ui_download_detour": "select",
            "default_mode": "rule",
            "store_mode": true,
            "store_selected": true,
            "store_fakeip": true,
            "cache_file": "cache.db"
        }
    }
}

### 日志

<details>
```console
# 使用日志内容覆盖此行
```
</details>

**Comment by NEPDream** [comment]
您好，请按照模版格式要求重新排版，并同时附上客户端和服务端的配置

**Comment by Oliver-Yue** [comment]
您好，请按照模版格式要求重新排版，并同时附上客户端和服务端的配置。最好简化一下你的配置，请提供最简可复现问题的双端配置。
