### ISSUE TITLE
URLTest for choosing fastest config does not work correctly

### ISSUE THREAD

**Issue by OxJ4ck** [SagerNet/sing-box#934]
### Operating system

Android

### System version

12

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.5.0-rc.5

### Description

hi I am reporting that the URLTest for choosing fastest config does not work correctly. when i click on the flash icon the URLTest will run and choose a server. however, the server that it chooses will not necessarily be the fastest server.
I have attached a screenshot of the Dashboard tab with the URLTest results. As you can see, the fastest server is "DE 02" with a ping of 346ms. However, the URLTest chose the server "DE 05" with a ping time of 401ms.
![image](https://github.com/SagerNet/sing-box/assets/117680088/21aa2922-a0a9-4223-8e9f-5c025864fdc9)

### Reproduction

1. Open the app and go to the Dashboard tab
2. Click on the "Start" button
3. Select "Groups" tab
4. Click on the URLTest flash icon

**Comment by nekohasekai** [comment]
RTFM
