### ISSUE TITLE
dns选项中doh无法使用双栈域名

### ISSUE THREAD

**Issue by uythb** [SagerNet/sing-box#939]
### 操作系统

Windows

### 系统版本

10

### 安装类型

sing-box 原始命令行程序

### 如果您使用图形客户端程序，请提供该程序版本。

1.5.0

### 版本

<details>
```console
dns: lookup failed for alive.github.com: Post "https://dns.touka.link/dns-query": io: read/write on closed pipe
```
</details>

### 描述

捣鼓了一晚上 最后锁定问题 发现对于doh服务器 如果是双栈的 sing box不能给出正常响应 如果是单栈(不管单栈v4还是v6) 都可以正常返回结果 反复修改DNS记录确定是这个问题无疑
测试dns服务器
dns.touka.link (此为双栈)
dns1.touka.link (此为单栈v4)
两个服务器均使用curl请求过与在firefox使用确认有效

虽然我这描述看起来很刁钻但是最常见的情况就是用户写了一个  https://cloudflare-dns.com/ 然后喜提不能用 这个情况我发现的更早 当时没在意 最近比较闲把这玩意再拖出来研究得到的结论
PS 我大号 @Fangliding 似乎莫名其妙被这个org ban了 如果能解开就更好了

### 重现方式

下为DNS配置
{
    "disable_cache": false,
    "disable_expire": false,
    "fakeip": {
    },
    "final": "test",
    "independent_cache": false,
    "reverse_mapping": false,
    "rules": [
    ],
    "servers": [
        {
            "address": "https://dns.touka.link/dns-query",
            "address_resolver": "cf",
            "address_strategy": "",
            "detour": "proxy",
            "strategy": "ipv4_only",
            "tag": "test"
        },
        {
            "address": "1.1.1.1",
            "address_strategy": "",
            "detour": "proxy",
            "strategy": "ipv4_only",
            "tag": "cf"
        }
    ],
    "strategy": "prefer_ipv4"
}

其中 如果 address_strategy 被设置为 ipv6_only 或者 ipv4_only 均可以正常返回 设置为其他的就会无法访问(不难猜测被设置为only的时候情况同单栈)

**Comment by nekohasekai** [comment]
缺少完整的重现过程。
