### ISSUE TITLE
sing-box在使用ws early data时 无法正常向服务端发送doh请求

### ISSUE THREAD

**Issue by uythb** [SagerNet/sing-box#944]
都测到这份上懒得填模板了 基本情况见 #939 

后来又测了一个晚上尝试给出完整复现流程 误打误撞发现了真实原因 如题
基本描述
在sing box使用doh时 如果该域名为双栈 且对应的detour为一vmess ws出站 对端为xray 启用early data 那么将会导致无法发送doh post请求 服务端则是根本看不到日志
由于对端是xray这里不便给出完整复现
下面的出站是我自己的的服务器 用pgp加密了一下 可以自行测试

-----BEGIN PGP MESSAGE-----

hF4DQe4swyo1RTgSAQdA6x0X6llgQnO1XAnC2miplI4h8yPlcv3FGKvVKCer6RUw
Wr5Ge2h+fxMwLp3LlVOgDfm3sMhYqfU2FodT38kFIUR/LkU0acMqoUhDdf1ZmulL
0ukBZE1oOoTDTAKHD7YD+CCI+7+zafdmtCSBbnSFzW10yBhnCgpQ+jARLaFlyHFz
k/qXLSttGM9IddouXREHdTyr87hcCWVFdMjiJIgsqqJWmYDii+Z8alJo0tASf4Zg
Gp3Buswi3rhIk5+gaiF7qnynIVL4ru8y3cLhAdabe9BrtIX3Ls0k4h5jHwHucEQS
C28fdcOr5TPzc97h9Kn8jvftR6EF6OyYyZKK6/VT17jxOTL3zEpuFK0VvCNHoBWr
Rwr8K9ZKe/aocrUAOzRCattDlTuWhXzQMTfQXnO+q8s8OadeMH007yJ0mvJbE4M1
PJViklEzNY7eBUFzp0/EfcqOhA2FaHx1jNp5Lgpg2UeK+zKMdcKOHfvMzFSbaGLZ
yvAo+KO4Swg+nC4ASVo63yR8uvUn+zL1Ry0iBoMKQEazuVc03zOOwI8OzC9iXrFI
HZEFMgCm3ntnnDpaQ2aMj418r2m4+7rzGozhe8LP0EEcckvnWxsVXTUUvx50cByJ
03bHxHXHEyw11y+yP5gIrfRlOOKXfY/ZzPZZDROM8kAIwnxep2Jx5FT9wVZQQVdV
O6A683E0zCX/osOHwM+hfYDxVhxl9Kv31YZdYXXLFdWcwO57ij++7HumeMqOXeqY
wN6lUhvOdcLPv63SElXCe5cndtb5AdtZ9sHgKK3yK3aPv8B8/OLEiDlc4PHvR9m5
tarb6qTlAK05uily8PYqcfACeDSf804j7lKjuuximBnyoT7cRwAUahoD+yHbYK5u
a/7SiztVqzgPYuU6LwsPalLLIaOWi/8qnIO+/EFjGgyX1otRvWLOrtetDgR7kXCj
Jt+fqlMtuXwwus9is1xKhm1bzCKjQgkzOEviaDrRcVPBcFNXe4nzNQMaR9r6OPaW
b4djEL81ky17wxIR0JicX7Hm//40xcflKfbJXrJzZsQB8pYR7xtHnwhmzJ8Kjq4O
1HTkN9gxJ2MJCzvipKePqYg3rR+pNKJr1h5i9QXLV2TIGDaGcesU3anv9M3WfdCk
VkQZmlKAiloel7laW6mJZ5NLTNLQTehRAWM5lE1Y1vUMCYluzqOZuBHT+/KM5EtS
LlZQe4lttfOTqNujpnijfg==
=wVwO
-----END PGP MESSAGE-----

测试方法 nslookup www.google.com 127.0.0.1 这会向singbox发送一个dns请求 直观获得输出(需要本地53端口空闲 systemd-resolved也可能会占用本地的53端口 我自己的平台是Windows)
将 ```"max_early_data": 2048,``` 修改为 ```"max_early_data": 0,``` 禁用early data 即可以获得正常输出
真的是想破脑袋也不会想到这去
或者替换为单栈doh服务器 dns1.touka.link 也可以获得正常输出
grpc似乎也也存在类似问题 没细看
~~顺便还是提一嘴把我大号解ban的事~~

**Comment by nekohasekai** [comment]
使用您的配置文件与自行配置的本地服务器无法重现您的问题，另外，您从没有给出过完整的本地重现流程。

**Comment by uythb** [comment]
> 使用您的配置文件与自行配置的本地服务器无法重现您的问题，另外，您从没有给出过完整的本地重现流程。

确定我的无法复现吗 好像有的时候nslookup会有回退机制 我在我的服务器上重新跑了这个config并把监听ip设成了0.0.0.0 再运行了 nslookup www.google.com +服务器  只跳了一个 DNS request timed out. 然后给出了回复 应该是回退到其他服务器上了 这也是出问题了 服务端也可以看到日志里的

dns: exchange failed for www.google.com. IN AAAA: Post "https://dns.touka.link/dns-query": dial tcp xxx.xxx.xxx.xxx:x: operation was canceled

**Comment by ekenchan** [comment]
遇到过同样情况，这应该是EarlyWebsocketConn里面的context超时造成的。从代码中可以看出，EarlyWebsocketConn的context是从DialContext时传入的，由于EarlyWebsocketConn是延迟请求，具有一定滞后性，到真正请求时这个context已经超时了
