### ISSUE TITLE
ECH retry support

### ISSUE THREAD

**Issue by er888kh** [SagerNet/sing-box#949]
### Description

Currently, when the server replies with `ech_rejected`, we don't attempt to use `retry_configs` in the server's response. The significance of this is that when we don't have DoH (or it is blocked) we can use a dummy/expired ECH config and get a valid one in the server's response (of course, after verifying their certificate).

**Comment by nekohasekai** [comment]
Since the ECH support library is provided by cloudflare, please submit feature requests to them.
