### ISSUE TITLE
SFA 安卓TV端 无法编辑 profile

### ISSUE THREAD

**Issue by lhbdhr** [SagerNet/sing-box#950]
### Operating system

Android

### System version

Amazon FireTV Stick 4K，最新固件。

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.6.0-alpha.2

### Version

<details>
```console
# Replace this line with the output
```
</details>

### Description

SFA 装在安卓TV上后， 可以创建remote profile，但是遥控无法选择 edit profile。
创建profile后，profile旁边的三个点倒是可以点击，但是只有share和delete功能。

**该问题导致无法设置自动更新订阅，而且无法手动更新订阅。**

### Reproduction

添加remote profile后，无法点击到 edit profile 按钮。

### Logs

<details>
```console
# Replace this line with logs
```
</details>

**Comment by csquya** [comment]
google 搜索 mouse toggle fire stick， 能找到模拟mouse的，我就是这样操作的。软件在商店下载要收费，也没多少钱， 不想出钱就去搜索也能找到。 Fire TV stick 要开启 usb 调试功能。

**Comment by nekohasekai** [comment]
https://community.sagernet.org/t/sing-box-android-tv-google-tv/125/3

**Comment by lhbdhr** [comment]
> google 搜索 mouse toggle fire stick， 能找到模拟mouse的，我就是这样操作的。软件在商店下载要收费，也没多少钱， 不想出钱就去搜索也能找到。 Fire TV stick 要开启 usb 调试功能。

感谢提醒，之前还用过这个软件，后来给忘了
