### ISSUE TITLE
pixel 7 pro使用问题

### ISSUE THREAD

**Issue by gzz4454** [SagerNet/sing-box#952]
编辑完配置文件后连接
出现提示
start service
pre-starting clash api: open cache file: function not implemented

**Comment by CHIZI-0618** [comment]
Duplicates with https://github.com/SagerNet/sing-box/issues/894

**Comment by gzz4454** [comment]
Android 14
sing-box version 1.5.1
{
  "dns": {
    "servers": [
      {
        "tag": "cf",
        "address": "https://1.1.1.1/dns-query"
      },
      {
        "tag": "local",
        "address": "223.5.5.5",
        "detour": "direct"
      },
      {
        "tag": "block",
        "address": "rcode://success"
      }
    ],
    "rules": [
      {
        "geosite": "category-ads-all",
        "server": "block",
        "disable_cache": true
      },
      {
        "outbound": "any",
        "server": "local"
      },
      {
        "geosite": "cn",
        "server": "local"
      }
    ],
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
      "type": "tun",
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "strict_route": false,
      "sniff": true
    }
  ],
  "outbounds": [
    {
      "type": "hysteria2",
      "tag": "proxy",
      "server": "23.106.***.*",
      "server_port": 59997,
      "up_mbps": 300,
      "down_mbps": 300,
      "password": "******1!",
      "tls": {
        "enabled": true,
        "server_name": "www.nidayegzz.online",
        "insecure": false
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "geosite": "cn",
        "geoip": [
          "private",
          "cn"
        ],
        "outbound": "direct"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      }
    ],
    "auto_detect_interface": true
  },
  "experimental": {
    "clash_api": {
      "external_controller": "127.0.0.1:9090",
      "store_selected": true
    }
  }
}

**Comment by gzz4454** [comment]
> Duplicates with #894

https://github.com/SagerNet/sing-box/issues/952#issuecomment-1749082846

**Comment by gzz4454** [comment]
> Duplicates with #894

OS issue？

**Comment by nekohasekai** [comment]
Are you using custom rom or stock?

**Comment by gzz4454** [comment]
> Are you using custom rom or stock?

No root or using custom rom.
