### ISSUE TITLE
Difference between Windows versions.

### ISSUE THREAD

**Issue by Abolfazl123** [SagerNet/sing-box#973]
![2342342343](https://github.com/SagerNet/sing-box/assets/47643911/76f0a88c-1355-4da8-98cb-74dd98cd6e30)

Hello. Can you please tell me what are the differences between these four versions of Sing Box Windows program?

[sing-box-1.6.0-beta.1-windows-386.zip
[sing-box-1.6.0-beta.1-windows-amd64.zip
[sing-box-1.6.0-beta.1-windows-amd64v3.zip

[sing-box-1.6.0-beta.1-windows-arm64.zip

**Comment by wintertee** [comment]
https://go.dev/wiki/MinimumRequirements#architectures
