### ISSUE TITLE
大量  inbound/socks[socks-in] 错误

### ISSUE THREAD

**Issue by hosxy** [SagerNet/sing-box#979]
### 操作系统

Windows

### 系统版本

windows 10 

### 安装类型

sing-box 原始命令行程序

### 版本

```console
sing-box version 1.5.3

Environment: go1.21.2 windows/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api
Revision: dc8ac01decb6ba298c6a43d7b2624ac991121a32
CGO: disabled
```

### 描述

可以正常使用，但是日志中出现大量  inbound/socks[socks-in] 错误

### 重现方式

协议使用 hysteria2，然后正常启动，打开网页(比如 https://meta.appinn.net/) 就会出现

### 日志

```console
23-10-15 17:04:30[ error ][3389160005 7.88s] inbound/socks[socks-in]: process connection from 127.0.0.1:10049: upload: stream 984 canceled by remote with error code 0
23-10-15 17:04:25[ error ][3247072969 0ms] inbound/socks[socks-in]: process connection from 127.0.0.1:10051: read tcp 127.0.0.1:1080->127.0.0.1:10051: wsarecv: An established connection was aborted by the software in your host machine.
23-10-15 17:04:01[ error ][316495477 2m0s] inbound/socks[socks-in]: process connection from 127.0.0.1:10017: upload: stream 952 canceled by remote with error code 0
23-10-15 17:04:01[ error ][1662377803 2m28s] inbound/socks[socks-in]: process connection from 127.0.0.1:9962: upload: stream 932 canceled by remote with error code 0
23-10-15 17:03:42[ error ][427260261 2m10s] inbound/socks[socks-in]: process connection from 127.0.0.1:9961: upload: stream 928 canceled by remote with error code 0
23-10-15 17:03:41[ error ][1532285017 2m6s] inbound/socks[socks-in]: process connection from 127.0.0.1:9970: upload: stream 940 canceled by remote with error code 0
23-10-15 17:03:38[ error ][3372828888 2m10s] inbound/socks[socks-in]: process connection from 127.0.0.1:9960: upload: stream 924 canceled by remote with error code 0
23-10-15 17:02:52[ error ][2271301300 1m16s] inbound/socks[socks-in]: process connection from 127.0.0.1:9982: upload: read tcp 127.0.0.1:1080->127.0.0.1:9982: wsarecv: An existing connection was forcibly closed by the remote host.
23-10-15 17:02:40[ error ][2678089032 10.1s] inbound/socks[socks-in]: process connection from 127.0.0.1:10037: upload: stream 968 canceled by remote with error code 0
23-10-15 17:02:19[ error ][2048940563 378ms] inbound/socks[socks-in]: process connection from 127.0.0.1:10026: download: write tcp 127.0.0.1:1080->127.0.0.1:10026: wsasend: An established connection was aborted by the software in your host machine.
23-10-15 17:02:19[ error ][2692288043 256ms] inbound/socks[socks-in]: process connection from 127.0.0.1:10024: download: write tcp 127.0.0.1:1080->127.0.0.1:10024: wsasend: An established connection was aborted by the software in your host machine.
23-10-15 17:02:19[ error ][3117219327 224ms] inbound/socks[socks-in]: process connection from 127.0.0.1:10022: download: write tcp 127.0.0.1:1080->127.0.0.1:10022: wsasend: An established connection was aborted by the software in your host machine.
23-10-15 17:02:19[ error ][2441777493 219ms] inbound/socks[socks-in]: process connection from 127.0.0.1:10021: download: write tcp 127.0.0.1:1080->127.0.0.1:10021: wsasend: An established connection was aborted by the software in your host machine.
23-10-15 17:02:19[ error ][25479504 210ms] inbound/socks[socks-in]: process connection from 127.0.0.1:10023: download: write tcp 127.0.0.1:1080->127.0.0.1:10023: wsasend: An established connection was aborted by the software in your host machine.
23-10-15 17:02:19[ error ][767541218 178ms] inbound/socks[socks-in]: process connection from 127.0.0.1:10025: download: write tcp 127.0.0.1:1080->127.0.0.1:10025: wsasend: An established connection was aborted by the software in your host machine.
```

**Comment by WeskerC** [comment]
有进展吗？

**Comment by uzzme** [comment]
not solve yet.
+0800 2024-06-01 15:27:19 ERROR [2958918487 354ms] inbound/http[http]: process connection from 127.0.0.1:47697: write tcp 127.0.0.1:10809->127.0.0.1:47697: wsasend: An established connection was aborted by the software in your host machine.
+0800 2024-06-01 15:28:22 ERROR [2808204845 328ms] inbound/http[http]: process connection from 127.0.0.1:47727: write tcp 127.0.0.1:10809->127.0.0.1:47727: wsasend: An existing connection was forcibly closed by the remote host.
+0800 2024-06-01 15:28:22 ERROR [3040067753 333ms] inbound/http[http]: process connection from 127.0.0.1:47726: write tcp 127.0.0.1:10809->127.0.0.1:47726: wsasend: An established connection was aborted by the software in your host machine.
+0800 2024-06-01 15:32:09 ERROR [1961704406 3.99s] inbound/http[http]: process connection from 127.0.0.1:47738: download: write tcp 127.0.0.1:10809->127.0.0.1:47738: wsasend: An established connection was aborted by the software in your host machine.
+0800 2024-06-01 15:32:13 ERROR [1872361619 857ms] inbound/http[http]: process connection from 127.0.0.1:47762: download: write tcp 127.0.0.1:10809->127.0.0.1:47762: wsasend: An established connection was aborted by the software in your host machine.
+0800 2024-06-01 15:32:13 ERROR [2612891860 298ms] inbound/http[http]: process connection from 127.0.0.1:47764: download: write tcp 127.0.0.1:10809->127.0.0.1:47764: wsasend: An established connection was aborted by the software in your host machine.
+0800 2024-06-01 15:32:13 ERROR [1142900161 278ms] inbound/http[http]: process connection from 127.0.0.1:47766: download: write tcp 127.0.0.1:10809->127.0.0.1:47766: wsasend: An established connection was aborted by the software in your host machine.
+0800 2024-06-01 15:32:13 ERROR [1795197836 247ms] inbound/http[http]: process connection from 127.0.0.1:47768: download: write tcp 127.0.0.1:10809->127.0.0.1:47768: wsasend: An established connection was aborted by the software in your host machine.
+0800 2024-06-01 15:32:14 ERROR [1885144246 263ms] inbound/http[http]: process connection from 127.0.0.1:47770: download: write tcp 127.0.0.1:10809->127.0.0.1:47770: wsasend: An established connection was aborted by the software in your host machine.
+0800 2024-06-01 15:37:08 ERROR [1950149729 3m8s] inbound/http[http]: process connection from 127.0.0.1:47805: upload: write tcp 192.168.11.63:47807->111.47.246.189:443: wsasend: An established connection was aborted by the software in your host machine.
