### ISSUE TITLE
ECH不支持VLESS xtls-rprx-vision

### ISSUE THREAD

**Issue by ekenchan** [SagerNet/sing-box#983]
### Operating system

Windows

### System version

Windows 10

### Installation type

Original sing-box Command Line

### Description

transport/vless下应该缺少了vision_ech.go，导致VLESS xtls-rprx-vision在ECH下不能用

### Reproduction

transport/vless下应该缺少了vision_ech.go，导致VLESS xtls-rprx-vision在ECH下不能用

**Comment by nekohasekai** [comment]
vision 设计为隐蔽协议，不应与 ECH 一起使用。
