### ISSUE TITLE
1.53 安卓版在 Fire TV 上无法启动

### ISSUE THREAD

**Issue by csquya** [SagerNet/sing-box#986]
### Operating system

Android

### System version

Fire TV OS

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.53

### Version

<details>
```console
# Replace this line with the output
```
</details>

### Description

无法启动，点击运行，显示 service starting，但一会儿结束就没了，显示服务没有启动

### Reproduction

从1.51 更新到1.53出现此情况，然后只能卸载，安装 1.52 版就没问题。

当然 sing-box 安装在 fire tv 上比较小众，所以只是报告bug， 并不急切希望修正， 开发者估计有更重要的事情要做，能关注最好，不能我就用旧版。

### Logs

<details>
```console
# Replace this line with logs
```
</details>

**Comment by nekohasekai** [comment]
提供 crash 日志或 logcat。
