### ISSUE TITLE
文档提供的go编译内核指令，在编译1.6.0-beta.3时，无法编译

### ISSUE THREAD

**Issue by jklolixxs** [SagerNet/sing-box#998]
### 操作系统

Linux

### 系统版本

Ubuntu 22.04.3 LTS

### 安装类型

sing-box 原始命令行程序

### 版本

<details>
```console
# 使用输出内容覆盖此行
```
</details>

### 描述

root@localhost:~# go version
go version go1.21.3 linux/amd64

在这个go版本下，使用文档提供的go编译命令，会显示如下信息，无法编译
root@localhost:~# go install -v -trimpath -ldflags "-s -w -buildid=" -tags with_quic,with_grpc,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_gvisor github.com/sagernet/sing-box/cmd/sing-box@v1.6.0-beta.3
go: github.com/sagernet/sing-box/cmd/sing-box@v1.6.0-beta.3 (in github.com/sagernet/sing-box@v1.6.0-beta.3):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.

### 重现方式

go版本为1.21.3 linux/amd64
使用指令
go install -v -trimpath -ldflags "-s -w -buildid=" -tags with_quic,with_grpc,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_gvisor github.com/sagernet/sing-box/cmd/sing-box@v1.6.0-beta.3

编译1.6.0-beta.2（包括以往版本）时正常，换成1.6.0-beta.3就会出现如下信息
go: github.com/sagernet/sing-box/cmd/sing-box@v1.6.0-beta.3 (in github.com/sagernet/sing-box@v1.6.0-beta.3):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.

### 日志

<details>
```console
# 使用日志内容覆盖此行
```
</details>

**Comment by CHIZI-0618** [comment]
Duplicates with https://github.com/SagerNet/sing-box/issues/992
